### ISSUE TITLE
Throttle email notifications

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1002]
We've reached the limit of what the current dumb system is capable of, it's time to put email notifications on a delayed job to ensure that we don't over-notify.

**Comment by tapaswenipathak** [comment]
Hi @tommoor: Can I work on the ticket or is the ticket internal?

**Comment by tommoor** [comment]
You can, but the ticket needs specing out a little better. Currently we send notifications to Slack / Email whenever a save occurs with the `done: true` parameter, this signifies that the user clicking "Done" in the app and exited editing mode.

The ideal approach would be that we ignore `done` completely and send Slack / Email notifications a predefined time period after the user has finished editing.

I believe this would involve:
- Every time a document is saved check for notification jobs on the queue and remove them
- Add a new job to the queue delayed to send in X minutes. A first implementation X could be 5 minutes, for example.
