### ISSUE TITLE
Ctrl + K isn't working on Chrome/Ubuntu

### ISSUE THREAD

**Issue by arikfr** [outline/outline#1005]
When I press Ctrl + K (in the hope of triggering search), it just jumps to the URL bar of the browser.

**Comment by tommoor** [comment]
Strange, I'm not sure what other extension might be kicking in? You can try hitting "/" as an alternative

**Comment by arikfr** [comment]
It looks like Ctrl+K triggering search in the URL bar (both in Chrome and Firefox):

![image](https://user-images.githubusercontent.com/71468/62269850-0025e900-b43d-11e9-9825-f6dc7acc0c7b.png)

It is possible to override this shortcut, because when I press Ctrl+K here in GitHub's issue editor, it inserts a link shortcut.

`/` does work.

**Comment by tommoor** [comment]
I can't reproduce on macOS, I wonder if it's an Ubuntu thing. Unfortunately I'm not sure what can be done to prevent it considering we're already stopping event propagation and preventing the default action 😬 

https://github.com/outline/outline/blob/master/app/components/Layout.js#L62-L67

**Comment by arikfr** [comment]
It's some limitation of `react-keydown`'s implementation. If you try it with mousetrap (another JS library to map keyboard shortcuts), it works: https://craig.is/killing/mice (Ctrl/Cmd+K is one of the examples on their homepage).

Also it's not an issue of event propagation: it's not that search triggers in Outline and then it jumps to the URL bar, Outline doesn't even receive this event. If I had to guess, I think it has to do with the DOM element you attach the keydown event handler to.
