### ISSUE TITLE
Cleaning database and S3 bucket on deletion

### ISSUE THREAD

**Issue by flaviuse** [outline/outline#1010]
Hello !
First thanks for all your work on this open source project !
I have deployed the app on Heroku with Heroku postgres, Heroku redis, Google Oauth and AWS S3 bucket and everything is working well for now.

I have questions about the cleaning of the postgres databse and S3 bucket when deleting a document/collection/image from a document.... 

It seems that deleting an image from a document doesn't delete it from S3 bucket. Do you plan to add S3 bucket deletion feature ? Or am I missing some options to make it done ? It can be a great feature for maintaining a wiki long term.

Deleting (not archiving) a document doesn't delete it in postgres but just soft delete by adding a timestamp to the "deletedAt" field. 
![image](https://user-images.githubusercontent.com/40322270/62637240-5ca46f00-b93b-11e9-862d-23a963e6479b.png)
Is there an option to use real deletion instead of soft deletion to keep the DB clean ? 

Are these features on your road map ?

Once again thank you for this awesome wiki !

**Comment by tommoor** [comment]
> It seems that deleting an image from a document doesn't delete it from S3 bucket. Do you plan to add S3 bucket deletion feature ? Or am I missing some options to make it done ? It can be a great feature for maintaining a wiki long term.

I'd definitely be open to a PR that implements this. I'd imagine there could be a post-document-update job similar to the one that processes backlinks to check if an image was removed and delete from S3. Right now It just hasn't been a priority.


> Deleting (not archiving) a document doesn't delete it in postgres but just soft delete by adding a timestamp to the "deletedAt" field.

Similarly, it's a "want to do" – the idea is to have a "Trash" menu item next to archive that would list the deleted documents for 30 days and have a job that will permanently clear them from the database after that.

**Comment by flaviuse** [comment]
> I'd definitely be open to a PR that implements this. I'd imagine there could be a post-document-update job similar to the one that processes backlinks to check if an image was removed and delete from S3. Right now It just hasn't been a priority.
> 
I'll check when I got time
