### ISSUE TITLE
can not upload images to s3

### ISSUE THREAD

**Issue by fmb-chin** [outline/outline#1011]
![image](https://user-images.githubusercontent.com/44079276/62683878-05ada100-b9f2-11e9-9a2a-945abc232235.png)
![image](https://user-images.githubusercontent.com/44079276/62684024-545b3b00-b9f2-11e9-9341-5059a50578be.png)

please help

**Comment by flaviuse** [comment]
Check CORS autorisations on the bucket & if you have disabled block public access (it's needed so you app can get the access to the bucket, i don't know if there is a better way to do it)
For Cors you can use : 
`<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>https://yourapp.com</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>

`

**Comment by tommoor** [comment]
@flaviuse has the right answer, you need to set the appropriate CORS headers.

**Comment by fmb-chin** [comment]
@tommoor @flaviuse 
Thanks for your help, but I already set CORS:
```json
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>https://xxxxx.com</AllowedOrigin>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

AS the image above shows, S3 already return the right CORS headers.

**Comment by fmb-chin** [comment]
My S3 env config

```shell
AWS_ACCESS_KEY_ID=xxxx
AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxxx
AWS_REGION=us-east-1
AWS_S3_UPLOAD_BUCKET_URL=https://outline.s3.amazonaws.com
AWS_S3_UPLOAD_BUCKET_NAME=outline
```

**Comment by deatherving** [comment]
@fmb-chin Have you got it fixed?

**Comment by fmb-chin** [comment]
@deatherving Haha, forget to update here.
Yes I got it fixed.

`AWS_REGION=us-east-1` should use `AWS_S3_UPLOAD_BUCKET_URL=https://s3.amazonaws.com` (without the bucket name in the domain)

Endpoint in region `us-east-1` seems special.

I don't known if this can help you.

**Comment by deatherving** [comment]
@fmb-chin Thanks for your help. My bucket is at us-east-2.

Just test it and still not working. 

Got a message that:

<Message>
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
</Message>

**Comment by deatherving** [comment]
@fmb-chin 
Just find out the solution for this. The bucket URL must be: 

https://s3-us-east-2.amazonaws.com

and AWS_REGION must be aligned. In my case it is:

us-east-2

**Comment by fmb-chin** [comment]
> @fmb-chin
> Just find out the solution for this. The us-east-2 bucket URL must be:
> 
> https://s3-us-east-2.amazonaws.com
> 
> and AWS_REGION must be aligned. In my case it is:
> 
> us-east-2

glad to hear that

**Comment by kolosek** [comment]
For me it worked with a  .

https://s3.us-east-2.amazonaws.com

**Comment by max-mykhailenko** [comment]
@kolosek thank you, your solution works for me also

**Comment by heyValdemar** [comment]
hey guys, I wrote [a detailed guide](https://www.heyvaldemar.com/install-outline-and-keycloak-using-docker-compose/) after I was able to configure Outline with MinIO and Keycloak.

Hopefully, it will help others.
