### ISSUE TITLE
Tcp error ECONNRESET

### ISSUE THREAD

**Issue by FlowShowcontrol** [outline/outline#1014]
Running latest Outline 0.34 on self hosted docker with nginx proxy

In the log:

Is there any way for me to debug this further?

Thanks

<img width="534" alt="Screen Shot 2019-08-10 at 1 16 54 AM" src="https://user-images.githubusercontent.com/10196339/62813719-a1cbcb00-bb0c-11e9-978f-5d757ff52adc.png">

**Comment by tommoor** [comment]
I'm afraid we can't provide support for your local setup here, this isn't an issue that seems familiar given the details you've provided.
