### ISSUE TITLE
Read-only Access for Collections

### ISSUE THREAD

**Issue by natefduncan** [outline/outline#1017]
Hi @tommoor, 

Thanks a ton for all your doing on this project. We have a self-hosted version of Outline running on Heroku. 

I know there was a discussion about collection permissions ( #668 ), but I'm having a hard time finding a way to change a user to read-only access on a collection. Is this a current feature? 

We have a couple of collections that we want users to be able to read but not edit.

**Comment by tommoor** [comment]
Hi @natefduncan – unfortunately this functionality doesn't exist yet, but work just started on it. The [policies architecture](https://github.com/outline/outline/pull/1016) is foundational work.

**Comment by tommoor** [comment]
This functionality now exists in private collections.

**Comment by tommoor** [comment]
Group permissions [has now landed](https://www.getoutline.com/changelog#v0.41.0). Adding groups is still limited to private collections however, this gets us another step closer.

**Comment by aam1r** [comment]
+1.

Our use case: Sharing certain collections outside of the company for public or third-party access

**Comment by tommoor** [comment]
This feature is now live on the cloud product https://app.getoutline.com/ and will be included in the next self hosted release in ~1 month.
