### ISSUE TITLE
Collection permissions cannot be toggled when opened from sidebar menu

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1018]
- Hover over collection
- Click "..." menu in sidebar
- Select "Permissions…"
- Attempt to toggle "Private"

This works when opening from the menu within a collection. Some observable / mobx quirk, perhaps the Collection model here isn't the same instance as the one in the store?

**Comment by danmakarov** [comment]
https://app.birdeatsbug.com/sessions/e0859X33b_DNZCagjq1_O
