### ISSUE TITLE
Outline bug? All information from second level hierarchy bullet points los

### ISSUE THREAD

**Issue by icannotcode-pdf-pptx** [outline/outline#1019]
Hey,

in our company workspace globally all bullet points of second or higher hierarchy level and the respective notes / information are lost.

Any ideas whats wrong? Anyone else experiencing it sind beginning of this week?

Cheers

**Comment by tommoor** [comment]
Investigating this now, thanks for the heads up.

**Comment by tommoor** [comment]
Fixed by db08263e5c72ccaa5f5fc371dc4cb679e863f777

The deploy is going out now, it will be fixed in production in under 5 minutes. Thanks!

**Comment by icannotcode-pdf-pptx** [comment]
Hey Tom,

thanks so much for investigating. Is the fix live then? Seemingly, information is still not displayed.

Thank you!

**Comment by icannotcode-pdf-pptx** [comment]
Hey @tommoor ,

did you have the time to take a look inside? In the meantime i found a few pages of our company workspace where 2nd level bullet points still exist. Looks like only in 70-80% of pages the bullet points are missed...

**Comment by tommoor** [comment]
Hi, I can't look at your documents however if the document was edited while the bug existed the second level bullets might have been lost. This can be fixed though – each document has a history, you can find it here:

![image](https://user-images.githubusercontent.com/380914/63157642-af56e880-c017-11e9-880f-edfdc75b366b.png)

Then navigate back through the history until you find the point where the bullets exist and either copy and paste them back into the doc or you can restore the document to that point in time.

Sorry for the trouble, we'll be putting tests in place to make sure a bug like this doesn't sneak in again.

**Comment by icannotcode-pdf-pptx** [comment]
Thank you so much Tom! @tommoor Problem is solved.
