### ISSUE TITLE
Lightweight Alpine Dockerfile

### ISSUE THREAD

**Issue by dominikstraessle** [outline/outline#1020]
If it's possible you should consider to also create an [Alpine Linux](https://www.alpinelinux.org/) Dockerfile for more lightweight images. To accomplish this you could use an alpine linux version of node as parent image.

Read more: https://github.com/nodejs/docker-node/tree/master#nodealpine

Consider something like this (not tested):
```Dockerfile
FROM node:8.11-alpine

ENV PATH /opt/outline/node_modules/.bin:/opt/node_modules/.bin:$PATH
ENV NODE_PATH /opt/outline/node_modules:/opt/node_modules
ENV APP_PATH /opt/outline
RUN mkdir -p $APP_PATH

WORKDIR $APP_PATH
COPY . $APP_PATH

RUN yarn install --pure-lockfile
RUN cp -r /opt/outline/node_modules /opt/node_modules

CMD yarn build && yarn start

EXPOSE 3000
```

**Comment by tommoor** [comment]
Thanks for the suggestion 👍
