### ISSUE TITLE
Add "+ New Doc" button to the no results page.

### ISSUE THREAD

**Issue by mylogon341** [outline/outline#1022]
To help with engagement in the company, I would like to request that the `+ New Doc` button is added to the no results page. 
Optionally, the copy on that page could also prompt the user to create the document when they find the answer they're after.

**Comment by mylogon341** [comment]
Added to feature request section in spectrum.chat

**Comment by tommoor** [comment]
This is a good idea, and low-hanging fruit. I'm going to reopen the issue.

**Comment by dav-m85** [comment]
Hi @bobrown101, still working on this or need help ?

**Comment by tommoor** [comment]
Done, looks like this:

---

![image](https://user-images.githubusercontent.com/380914/66263684-bdb9b900-e7ab-11e9-8847-4978f64dfc73.png)
