### ISSUE TITLE
Plans for mobile app

### ISSUE THREAD

**Issue by gaui** [outline/outline#1024]
Are there any plans on the roadmap to publish a mobile app?

**Comment by gaui** [comment]
The threshold could be minimized by switching to React Native and React Native Web and using React primitives and stop targeting everything towards the DOM. Styled Components already has React Native support.

**Comment by tclain** [comment]
In fact I think that it will be exactly the editor that will be the hardest part to port over, if you don't wan't use an hybrid solution (and slower) like cordova.  The slate project has a discussion about this and this is not a solved problem: https://github.com/ianstormtaylor/slate/issues/1374

**Comment by gaui** [comment]
How about https://editorjs.io

**Comment by chsasank** [comment]
Any updated thoughts on this @tommoor?

**Comment by GetPsyched** [comment]
I hope this can be reopened, and probably invested in soon :)
