### ISSUE TITLE
Problems using soft keyboards / alternative input methods

### ISSUE THREAD

**Issue by Coderhypo** [outline/outline#1027]
Hello，

I encountered a problem when I used Chinese input method editor

Under normal circumstances：
![image](https://user-images.githubusercontent.com/10693087/63739913-a096ee00-c8c1-11e9-9a6b-14a713a4e1dd.png)

But in outline：
![image](https://user-images.githubusercontent.com/10693087/63740038-1438fb00-c8c2-11e9-8d20-8c282209ba92.png)

the first issue is the position of cursor, as above screenshot.

second，When I add a title, when I select it with the spacebar, it will automatically switch to the content editor.

![CleanShot 2019-08-27 at 12 06 14](https://user-images.githubusercontent.com/10693087/63740356-3f701a00-c8c3-11e9-955b-cd6b478f04af.gif)

last，If I edit the content, there will be style overlaps before I enter anything.
![image](https://user-images.githubusercontent.com/10693087/63740125-6843df80-c8c2-11e9-847f-22e9213b0886.png)

and I find similar issue in other project（ https://github.com/ianstormtaylor/slate/issues/2457 ），I am not good at nodejs，maybe this issue can provide a solution

**Comment by Coderhypo** [comment]
so sad, the current version still have this problem
![CleanShot 2019-08-27 at 14 25 55](https://user-images.githubusercontent.com/10693087/63746191-c1b60980-c8d6-11e9-8e2f-76d38220309b.gif)

**Comment by yuankui** [comment]
same issue，really awful

**Comment by Coderhypo** [comment]
@yuankui  Hello, I have a very stupid way, but can solve this problem, Enter a space before you type anything, then replace the cursor in front of the space and enter the content of the article.

make sure the space are always followed by the cursor.

![image](https://user-images.githubusercontent.com/10693087/68828909-2ddc2880-06e2-11ea-908d-4634d052a60c.png)

**Comment by yuankui** [comment]
> @yuankui Hello, I have a very stupid way, but can solve this problem, Enter a space before you type anything, then replace the cursor in front of the space and enter the content of the article.
> 
> make sure the space are always followed by the cursor.
> 
> ![image](https://user-images.githubusercontent.com/10693087/68828909-2ddc2880-06e2-11ea-908d-4634d052a60c.png)

haha，this should be a new bug(or feature?)

I have found another hack solution. But has'nt decided to use it.

https://sijie.wang/2019/06/20/slate-chinese-input/

**Comment by Coderhypo** [comment]
@tommoor 
Hello, Good news, slate has fixed the problem: https://github.com/ianstormtaylor/slate/pull/3093 

![CleanShot 2019-11-28 at 13 18 21](https://user-images.githubusercontent.com/10693087/69779070-b201d600-11e1-11ea-8496-4796a83bfda2.gif)

**Comment by yuankui** [comment]
@Coderhypo 
really a HUGE change！

Tough works of imagrating。。。

Oh my god, I have written a lot of plugins already...

**Comment by tommoor** [comment]
Great that it's addressed – as you mentioned, the amount of changes here likely make this a monumental upgrade path 😢

**Comment by Coderhypo** [comment]
![CleanShot 2019-12-18 at 13 50 07](https://user-images.githubusercontent.com/10693087/71059304-85682b00-219d-11ea-98b1-120ea50f45d5.gif)
@tommoor hello,

I upgrade to 0.38.0 today, and I find the editor completely unavailable 😶, I got two character input when I type the first character.

No matter what I do, I can’t finally type anything successfully.

**Comment by tommoor** [comment]
You think it's gotten worse? Nothing should really have changed on this front yet.

**Comment by Coderhypo** [comment]
It ’s weird. The current situation is that I can’t make a complete input through the input method. And the only thing I did was upgrade to new version.

**Comment by BusyHe** [comment]
+1

**Comment by jie** [comment]
+1

**Comment by jie** [comment]
+1

**Comment by teddychan** [comment]
+1
It is really painful now and cannot input Chinese.
Really appreciate it if can push this fix at a higher priority.

**Comment by tommoor** [comment]
The work here will resolve the issue once merged:
https://github.com/outline/rich-markdown-editor/pull/150

**Comment by maijunsheng** [comment]
@tommoor 

> The work here will resolve the issue once merged:
> [outline/rich-markdown-editor#150](https://github.com/outline/rich-markdown-editor/pull/150)

Hi, I meet the same problem, want to know when do you expect the release of the new version to resolve this issue, thanks.
