### ISSUE TITLE
Browser context menu overlaps with text formatting toolbar

### ISSUE THREAD

**Issue by danmakarov** [outline/outline#1029]
1. Create a new document
2. Create a list item (i.e. "1.")
3. Right-click to the right of the item
<img width="809" alt="Screenshot 2019-08-28 at 10 53 41" src="https://user-images.githubusercontent.com/18628686/63841065-63defb80-c982-11e9-834a-33708ecebf35.png">

**Comment by danmakarov** [comment]
I think there are 2 separate things here tbh:
1. The panels overlap (but only in some cases, in others - they just open simultaneously): https://app.birdeatsbug.com/sessions/XFxrrTyRAwRNLrZA0nFzh
2. Maybe the editor panel should not be triggered on right click at all - only if you double-click to highlight, like here https://app.birdeatsbug.com/sessions/cdToMqTDtqG8eCZgVmYjo

**Comment by danmakarov** [comment]
Yeah. You're right. Then it's only the fact that they overlap in certain cases. I guess mostly (or only) when it's in the first line of a document

**Comment by tommoor** [comment]
Hey @danmakarov I'm going to close this out as unactionable as there is no way to place UI above the browser context menu, this case will always be possible.
