### ISSUE TITLE
optionable https in production mode

### ISSUE THREAD

**Issue by zironycho** [outline/outline#1041]
Hi, guys.
Thank you for supporting awesome open source project.

I have problem with enforce redirect in my service and ingress. I am using ACM(aws certificate manager), and aws load balancer received https, and then change 80/http for internal instance. after then, outline get the http request. 
If `outline` set the enforcehttps, it will make infinity redirect chain. I think enforcehttps should be optionable, and default might be `true` as you guys used.

Here is the my code location, I modified: https://github.com/neosapience/outline/blob/8d34dcf099eb0008f96313417d07fe71fb1fb7b9/server/app.js#L79-L87

**Comment by tommoor** [comment]
Makes sense, I would consider changing to `FORCE_HTTPS !== 'false'`, if you wanted to out a PR in for this it would be accepted otherwise will add to the backlog!

**Comment by tommoor** [comment]
FWIW if you're able to set the `x-forwarded-proto=https` from the load balancer then this will also work and is the preferred approach, for anyone that stumbles on this issue.

**Comment by unoexperto** [comment]
@tommoor @zironycho Guys, could you please advise how to make it work without https ? I'm launching outline with following parameters

```
docker run -d --name=outline --restart always \
    -p 3000:3000 \
    --network isolated \
    -e SECRET_KEY=xxx \
    -e URL=http://localhost:3000 \
    -e PORT=3000 \
    -e DATABASE_URL=postgres://uuuu:xxx@psql:5432/outlinedb \
    -e REDIS_URL=redis://redis:6379 \
    -e AWS_S3_UPLOAD_BUCKET_URL=https://s3.amazonaws.com \
    -e FORCE_HTTPS=false \
    outlinewiki/outline:latest
```

Outline listens on 3000 but returned html redirects to `https://localhost` (without port).

What am I missing ?
