### ISSUE TITLE
Question about production deployment process

### ISSUE THREAD

**Issue by karapas** [outline/outline#1045]
Hi all,

I have a question regarding deploying outline for production use.

Back in February 2019 when I first deployed outline (tag 0.25.0), the production deployment was still done using docker, but simply setting some flags to denote a production setup (eg `NODE_ENV=production`), at least if i remember correctly.

Now I see that the production deployment has changed. My question is: Can I migrate from the previous production deployment process to the new one? If yes, how? If not, can I still keep using the old method with no issues, even after pulling the latest updates from master?

**Comment by tommoor** [comment]
Hey, what issues are you seeing – the production deployment process hasn't changed in any meaningful way, docker will still work fine and `NODE_ENV=production` is the key.

Check the `.env.sample`, some new environment variables have been added through the year that you might be missing. Closing this ticket as it isn't an issue, but feel free to reply.
