### ISSUE TITLE
Slack command cannot be used with a Google team

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1047]
Currently it requires the slack user that initiates the command to have previously signed in to the team.

In hindsight this seems like an unnecessary requirement, it would be nice to enable anyone with access to run the Slack command to get results. This then also accounts for those users that only ever sign in with Google but still use Slack for comms.

**Comment by tommoor** [comment]
Currently the only way to search a wiki is through the `Document.searchForUser` method which requires a user model – this will need to be changed to achieve this.

**Comment by Precious5050** [comment]
Ok thanks
