### ISSUE TITLE
Install without the Cloud?

### ISSUE THREAD

**Issue by aadrian** [outline/outline#1048]
Hi,

Cant this project be installed and used **without** the cloud services? Amazon S3, Slack, Google?

Thank you.

**Comment by tommoor** [comment]
Hi, this project cannot be used without at least Google or Slack signin currently. LDAP / SSO is on the long term roadmap

**Comment by aadrian** [comment]
> Hi, this project cannot be used without at least Google or Slack signin currently. 

@tommoor Thank you very much for clarifying this.

> LDAP / SSO is on the long term roadmap

That would be a nice luxury, but what about the most simple and trivial local user/password based authentication?

It's a just a pitty that such a nice project can't be simply used in a typical company intranet (since it needs outside cloud connections) :( .

**Comment by kalbasit** [comment]
@tommoor would you consider a community contribution for a simple username and password feature?

**Comment by tommoor** [comment]
@kalbasit I don't believe there is such a thing as a simple version of that feature. But if you were to put a plan together as to how that would be added and which flows considered I'd be open to it, yes.

**Comment by rutger1140** [comment]
Just wondering, is this still on your radar?

Relying on big tech (Microsoft, Google, Slack) for signing in to an open source product gives me second thoughts on the word "open" in open source.

If I don't "sell my data" to big tech I'm unable to use your product. 😞 

Self-hosted GitLab OAuth would be a big improvement, as mentioned in #962
