### ISSUE TITLE
InVision infinite crash loop

### ISSUE THREAD

**Issue by JoeyJanson** [outline/outline#1050]
I'm having this unexpected result (11 sec. video):
![INVISION_OUTLINE_ERROR](https://user-images.githubusercontent.com/22045972/65452284-3e3df880-de41-11e9-9319-4d37aeb13829.gif)

With the following console error:

![image](https://user-images.githubusercontent.com/22045972/65452229-1babdf80-de41-11e9-9c1b-daf14b953a19.png)

Haven't had the time to debug any further; I'm new to Outline and this is the first big issue (in my case) I've discovered. Anyone with the same issue? Is there something wrong with my set up?

**Comment by tommoor** [comment]
Honestly this seems like a bug on InVision's end – we only embed an Iframe of their share link. I'd recommend reporting to their team too, you could create a public share link of your Outline document to help debugging

**Comment by JoeyJanson** [comment]
> Honestly this seems like a bug on InVision's end – we only embed an Iframe of their share link. I'd recommend reporting to their team too, you could create a public share link of your Outline document to help debugging

@tommoor I guess you're right.. It crashed for the last few hours but it's suddenly working as expected. Closing the issue now.. Thank you.
