### ISSUE TITLE
Is it possible to run without AWS?

### ISSUE THREAD

**Issue by b3z** [outline/outline#1052]
Is it possible to run outline without AWS? So keeping the files local on the server?

**Comment by b3z** [comment]
Alright - just tried it. Yes it is, just can't upload any images. But I keep them anyway in a separate git remote repo so I link the anyway.

**Comment by b3z** [comment]
Anyway is there a way for using local storage?

**Comment by tommoor** [comment]
Hey, you should use something like Minio to self-host an S3 compatible API using docker:
https://blog.alexellis.io/meet-minio/

(We actually do this in development mode too)

**Comment by kmahyyg** [comment]
@tommoor Then If I use Minio for myself, where can I change my AWS S3 endpoint to my self-hosted one?

**Comment by tommoor** [comment]
@kmahyyg no, that is not possible with this project currently.

**Comment by ipetrov-amatas** [comment]
What's the point of overcomplicating it? Why not have the option for locally hosted assets instead of having to pay for AWS S3?

**Comment by tommoor** [comment]
We've chosen to keep file storage as a separate concern to reduce complication in the project. Outline is designed to use scalable best practices for internet applications; storing user-uploaded files on the same machine that serves the site is generally an unwise idea from both a security and reliability point of view.

However, you don't have to pay for S3, there are _many_ ways to store files with an S3-compatible API. Including the Minio project linked above.
