### ISSUE TITLE
Why not to use any UI kit instead of developing yet another buttons and dropdown with bugs,  a11y, and other issues?

### ISSUE THREAD

**Issue by a-x-** [outline/outline#1060]

**Comment by tommoor** [comment]
Hi @a-x- – please provide specific examples of issues you've found and they will be addressed.

**Comment by a-x-** [comment]
E.g. #1044, #981

**Comment by a-x-** [comment]
There are some ready good tested developed ui kits, some of them are flex enough. 
I think to fork outline and base it on `material-ui` with or `antd` as flexible powerful ui kit. I don’t like some parts of mui guides but material-ui react library suggests good restyling abilities

**Comment by tommoor** [comment]
Yea, I think if the project was started today then material-ui might make a good foundation – although I'm not sure how difficult it would be to remove all the Googleiness from the styling. Of course this project is now over 3 years old and changing the entire UI setup would be no mean feat.

So, in principle I'm with you but building out missing functionality is just way more important as a time investment, the amount of UI bugs that we deal with are very minimal.

**Comment by a-x-** [comment]
Ok, thank you!
