### ISSUE TITLE
Empty sourceExpression

### ISSUE THREAD

**Issue by jirsbek** [outline/outline#1068]
Hi, firs of all thank you for interesting open-sourced project. I've tried too many wiki apps and Outline and it's simplicity seems to be exactly what I've been looking for.

I've been trying to run the app in Docker instance (using outlinewiki/outline 0.37.0 together with Redis and Postgress containers) on NAS Synology but I encounter an error below.

I believe I've got all need ENV variables filled up (SLACK_APP_ID, SLACK_VERIFICATION_TOKEN, SLACK_SECRET, SLACK_KEY, REDIS_URL, DATABASE_URL, SECRET_KEY), but still getting this error: 
```
/opt/outline/node_modules/helmet-csp/lib/check-options/check-directive/source-list.js:19 | stdout

throw new Error('"' + sourceExpression + '" is not a valid source expression. Only non-empty strings are allowed.')

Error: "undefined" is not a valid source expression. Only non-empty strings are allowed.
```

Am I missing something?

**Comment by tommoor** [comment]
You're missing `AWS_S3_UPLOAD_BUCKET_URL`

**Comment by BusyHe** [comment]
> Hi, firs of all thank you for interesting open-sourced project. I've tried too many wiki apps and Outline and it's simplicity seems to be exactly what I've been looking for.
> 
> I've been trying to run the app in Docker instance (using outlinewiki/outline 0.37.0 together with Redis and Postgress containers) on NAS Synology but I encounter an error below.
> 
> I believe I've got all need ENV variables filled up (SLACK_APP_ID, SLACK_VERIFICATION_TOKEN, SLACK_SECRET, SLACK_KEY, REDIS_URL, DATABASE_URL, SECRET_KEY), but still getting this error:
> 
> ```
> /opt/outline/node_modules/helmet-csp/lib/check-options/check-directive/source-list.js:19 | stdout
> 
> throw new Error('"' + sourceExpression + '" is not a valid source expression. Only non-empty strings are allowed.')
> 
> Error: "undefined" is not a valid source expression. Only non-empty strings are allowed.
> ```
> 
> Am I missing something?

can you install it in Nas?

**Comment by jirsbek** [comment]
I didn't succeed. Maybe I'll try again later.
