### ISSUE TITLE
Is it possible to start the frontend without the backend and connect to the official getoutline.com backend?

### ISSUE THREAD

**Issue by michaelpittino** [outline/outline#1071]
Hello, I'm not very used to javascript and the associated technologies, but I was wondering if it's possible just use the frontend and connect to the backend we already have purchased on getoutline.com.
The goal is to make some UI adjustments while still using the hosted solutions.
Thanks for any help!

**Comment by tommoor** [comment]
Hi Michael, this isn't possible. What kind of UI changes are you looking at making?
