### ISSUE TITLE
Accented characters

### ISSUE THREAD

**Issue by juliocoelho** [outline/outline#1072]
When writing an accented character like ã, â, à, á occurs the following:

- Writing in a text field, is ok.
- Writing in a description or the title of the document the character is written without the accent
- Writing in the wiki text editor the character is not written.

However if the character is copied into the text area, it is fine.

I know that you are using the slate editor and doing the test on that editor the character is written without the accent.

One easy fix for this situation is to have the ability to write plain markdown with a preview without using the slate editor.

**Comment by tommoor** [comment]
Hey @juliocoelho I'm unable to reproduce this issue on macOS – I can type accented characters. Which input method / OS are you using?

**Comment by juliocoelho** [comment]
Hi @tommoor, thank you for your reply.

I am using macOS with a Portuguese keyboard with the English has a primary language.

Attached a video that demonstrates the issue.

![accentedcharacters](https://user-images.githubusercontent.com/1031389/67642674-14776600-f906-11e9-9838-7a4bfd9bcfdd.gif)

**Comment by tommoor** [comment]
@juliocoelho thanks – could you confirm that this bug still exists on the latest version of Slate? There's a demo available here: https://www.slatejs.org/#/rich-text

**Comment by juliocoelho** [comment]
Hi @tommoor, thank you for the quick reply.

Did a better error testing and found that the error only occurs in the safari browser. Firefox and chrome do not suffer from this issue.

This issue also happens in the slate latest version, let's expect that slate team can figure this out.

**Comment by tommoor** [comment]
Combining this issue with #1027
