### ISSUE TITLE
How to update old self-hosted outline to latest version?

### ISSUE THREAD

**Issue by kkotharirefinepro** [outline/outline#1074]
Hi Tom,

Thanks for your great product, we using old version outline and want to upgrade it to newest.
What are the steps to update the old self-hosted outline so we don't loose the old data.

Thanks,
Keval

**Comment by tommoor** [comment]
- Back up the database
 - Install new dependencies and migrate the database: `yarn && yarn sequelize db:migrate` – if you're running Outline in a docker container it's going to look more like `docker-compose run --rm outline /bin/sh -c "yarn && yarn sequelize db:migrate"`
 - That should be it.

**Comment by kevalkothari** [comment]
Hi @tommoor 

Thanks for replying.  actually I have downloaded code from Git and then did the **yarn build**  and then I am running that way and not using docker.

What steps will be there in that case?

Thanks a lot!

Regards,
Keval

**Comment by tommoor** [comment]
As described above, you only need to migrate the database in order to run the latest code.

**Comment by kevalkothari** [comment]
Hi @tommoor 

So only migrating db will do the update?  I don't have to download the latest code from git and do **yarn build** ?

thanks,
Keval

**Comment by tommoor** [comment]
Yes, you'll need to download the code.

- Backup database
- Pull from git
- `yarn install`
- `yarn build`
- `yarn sequelize db:migrate`

**Comment by kevalkothari** [comment]
Thanks a lot @tommoor  :)
