### ISSUE TITLE
Emboldening the # symbol

### ISSUE THREAD

**Issue by tjmcewan** [outline/outline#1077]
I want to write something like this:

**#thing**

It works in edit mode, but when saving it displays various forms of asterisks and/or non-bold text.

The closest I've managed to get is to separate the octothorpe from the succeeding text and embolden each section independently.  I can't put them back together tho; they lose formatting.

**Comment by tommoor** [comment]
@tjmcewan great find, the octothorpe is clashing with the formatting for bold. I'm able to reproduce the bold not saving, but not asterisks appearing, do you know what you typed to achieve that?

**Comment by tjmcewan** [comment]
Ah it was several different incantations of repeatedly trying to trick it.  I think it was because I was actually using "text #thing" and "text" would be bold, but not "#thing" so I only re-bolded "#thing".

**Comment by tommoor** [comment]
Thanks for reporting, the fix is deploying to production now and will be available shortly.
