### ISSUE TITLE
Non-Image File Attachments?

### ISSUE THREAD

**Issue by nicholas-ochoa** [outline/outline#1079]
Are non-image attachments supported somehow? We have small code snippets and other miscellaneous files that we'd like to attach to documents. We're running a self-hosted instance if that matters.

**Comment by tommoor** [comment]
Code snippets are supported can be inserted with code blocks or by typing "```", you can also embed code with CodePen snippets.

Other misc file attachments are not yet supported I'm afraid, but the ability to do so is on the roadmap. In the meantime I'd recommend uploading to a service like Google Docs/Dropbox and linking from the doc.

**Comment by tommoor** [comment]
Merging this with #859
