### ISSUE TITLE
self hosted slack /outline command

### ISSUE THREAD

**Issue by alexcurtin** [outline/outline#1080]
After adding a self-installed Outline application, how do I get the `/outline` command + search working?

**Comment by tommoor** [comment]
- You'll need to create a [Slack app](https://api.slack.com/apps)
- Copy all of the credentials into the relevant environment variables defined in `.env.sample` – e.g `SLACK_KEY` etc.
- In Slack's interface you also need to create the slash command, unfortunately there is no direct link but it's in the left hand menu. The request url for the slash command should be set to `https://yourdomain.com/api/hooks.slack`

**Comment by alexcurtin** [comment]
@tommoor this worked great, but the "post to slack" button doesn't send the found article to slack, any pointers?

**Comment by tommoor** [comment]
Ah yes, you'd also need to enable *Interactive Components* in the Slack app store from the left hand menu. Enable "Interactivity" and then set the URL to `https://yourdomain.com/api/hooks.interactive`

**Comment by praveenaj** [comment]
I have followed these steps. But now I get this when try to run the command. Any idea?
![image](https://user-images.githubusercontent.com/538142/126795904-b78975df-abd5-4b8c-94f3-3b1bcdee42c7.png)

I have these under Scopes
![image](https://user-images.githubusercontent.com/538142/126796116-b7d02d9a-e31a-44a5-aebe-e6de96b940ca.png)

**Comment by tommoor** [comment]
Did you find [these instructions](https://wiki.generaloutline.com/share/be25efd1-b3ef-4450-b8e5-c4a4fc11e02a) ?

**Comment by yoramshai** [comment]
@tommoor same issue here, and yes, I followed the instructions. 
Anything else I am probably missing?

**Comment by pfennig42** [comment]
Small hint, that you need to reinstall the slack app, after changing the urls etc
