### ISSUE TITLE
Invite email is not working

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [outline/outline#1081]
Im using AWS SES to send emails. in .env file, I have added the following things.
Its in my own hosted infra.
```
SMTP_HOST=email-smtp.us-east-1.amazonaws.com
SMTP_PORT=587
SMTP_USERNAMEc=ACCEESS_KEY
SMTP_PASSWORD=SECRET_KEY
SMTP_FROM_EMAIL=Verified@ses.email
SMTP_REPLY_EMAIL=Verified@ses.email
```
But i didn't get any emails.

**Comment by tommoor** [comment]
`SMTP_USERNAMEc` should be `SMTP_USERNAME`, other than that I'm not able to provide support for this I'm afraid as the hosted version doesn't use SES.

**Comment by BhuviTheDataGuy** [comment]
Yes, later i changed it, but still it's not working.

**Comment by unoexperto** [comment]
@BhuviTheDataGuy Did you fix it ? I tried google smtp-relay and regular authenticated gmail smtp and I receive no notifications. Full debug mode doesn't produce any info either :(

**Comment by BhuviTheDataGuy** [comment]
Nope, wondering, even after 1 year the issue still persists.

**Comment by tommoor** [comment]
These ENV variables are just fed directly into `node-mailer`, it's been working on hundreds of installations for years – you can see the config here:
https://github.com/outline/outline/blob/449dc55aaa832eb9c8c68ed74ed04504cbcbdeeb/server/mailer.js#L162-L178

With `DEBUG=emails` you should see logs like "Sending email to blah"

**Comment by dieterdanger** [comment]
It is actually not working for me. Also, DEBUG=emails shows no infos about emails. Even DEBUG=* doesn't. 

I tried multiple smtp-servers (localhost, gmail, business-account, ethereal). There is no email send.

Any tips?

**Comment by MetaBliss** [comment]
Hi @dieterdanger thansk for your post, I'm having the same email not working issue to. What is the value you have put for the SMTP_TLS_CIPHERS field? My settings are below:
