### ISSUE TITLE
Include more details in docs on database usage

### ISSUE THREAD

**Issue by aam1r** [outline/outline#1083]
The docs currently say:

![image](https://user-images.githubusercontent.com/566418/69012545-a1797200-093c-11ea-8072-4570392c6fdd.png)

For someone self-hosting this, here are some questions that come to mind:

- Why is Postgres needed? Is it mandatory? What's stored in there?
- Why is Redis needed? Is it mandatory? What's stored in there?
- Which version of Redis do I need?
- Are there any minimum requirements for the Redis / Postgres servers?

**Comment by tommoor** [comment]
@aam1r all are required as is stated in the sentence above, there are no minimum requirements – Outline will run on the smallest box you have, it'll probably run fine on a Raspberry Pi if you must 😉 

I'll add a note on the minimum Redis version though 👍
