### ISSUE TITLE
Add 'Group' permissions

### ISSUE THREAD

**Issue by aam1r** [outline/outline#1085]
Permissions for collections (re: #989) are now based on a per-user basis. A user is explicitly added to collections and that controls what kind of access they have.

It would be pretty powerful to have Group based memberships. 

Instead of giving one-off permissions to users to individual collections, the administrator would define Groups. For example:

* Engineering
* Finance
* HR
* Operations
* Marketing, Sales, etc.

The collection permissions would then be granted to the group. This makes it much easier to control permissions for larger teams than having to individually grant permissions to users.

**Comment by tommoor** [comment]
Hey @aam1r – this project has been started, progress can be followed here: https://github.com/outline/outline/pull/1102
