### ISSUE TITLE
Add ability to delete team

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1086]
- Add option under "Settings -> Team" to delete the team
- Must include a confirmation modal
- New API endpoint `team.delete`
- Must require admin authorization
- Marks team record as deleted
- Add to `utils.gc` to destroy teams (and all associated data) that have been marked as deleted for 30 days

**Comment by TommyJackson85** [comment]
Can I help with this? I am looking for a first issue to solve, to make my first contribution to outline.

**Comment by tommoor** [comment]
I don't think this is a great first issue due to the complexity and consequences of getting everything correct here.
