### ISSUE TITLE
Slack webhook for updates and publishes not working

### ISSUE THREAD

**Issue by alfieyfc** [outline/outline#1087]
My webhook generated from slack works, as I have tried the CURL command provided on slack's settings page:
![image](https://user-images.githubusercontent.com/41598103/69260054-33fa6980-0bfa-11ea-9324-07e1e2ad21cd.png)
> ![image](https://user-images.githubusercontent.com/41598103/69260140-61471780-0bfa-11ea-9798-eb251aee8bc3.png)

---
But when a document is published, slack isn't receiving the POST, and outline gives error catch as below:
```
(node:144) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined
    at present (/opt/outline/server/presenters/slackAttachment.js:27:25)
    at Slack._callee3$ (/opt/outline/server/services/slack.js:105:23)
    at tryCatch (/opt/outline/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/opt/outline/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.<computed> [as next] (/opt/outline/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/opt/outline/server/services/slack.js:14:191)
    at /opt/outline/server/services/slack.js:14:361
(node:144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
```

I'm using Docker image `outlinewiki/outline:version-0.37.0`

**Comment by tommoor** [comment]
The error would suggest that for some reason `team` is `undefined` in this scenario, you can see where `team.url` is accessed on L27 of that file.

https://github.com/outline/outline/blob/b42e9737b63d22a1bed93101222b0a952bee0f8e/server/presenters/slackAttachment.js#L27

As for why this would be the case, I'm not sure at this time – the error does not reproduce in the hosted production version of outline.
