### ISSUE TITLE
Problem with Japanese input

### ISSUE THREAD

**Issue by ozasuke** [outline/outline#1094]
Thank you for a nice application.

There seems to be a problem with Japanese input.
[![Image from Gyazo](https://i.gyazo.com/e686b4a18b47c49fbae09c8d900ad6c7.gif)](https://gyazo.com/e686b4a18b47c49fbae09c8d900ad6c7)

I want to enter "あいうえお", but "aあいうえお" is entered.

By the way, this rich editor works fine.
https://www.slatejs.org/examples/richtext

**Comment by tommoor** [comment]
Thanks for the report – the reason that the example on the Slate website works is that they just released a major update that will be a painful upgrade process, however support for multiple languages is very important for this project. 🙏 

I'm combining this issue with #1027
