### ISSUE TITLE
UI hangs when updating a page that has been deleted

### ISSUE THREAD

**Issue by senyuuri** [outline/outline#1095]
**Problem:**
Assume we have two team members A and B, both want to edit a page X. They perform a sequence of operations in the following order:
1. A opens page X in editing mode, start typing
2. B deletes X
3. A clicks on "Done Editing", which sends a POST request to `/api/documents.update`. However, since X has been deleted, the backend returns a 403 error with payload `{"ok":false,"error":"authorization_error","message":"Authorization error"}`. The frontend does not handle the error and stuck in the "loading bar" animation.

![image](https://user-images.githubusercontent.com/2610986/70308012-608ec200-1845-11ea-9915-7ffe1c1b2b08.png)

**Comment by tommoor** [comment]
Thanks for the report!

**Comment by tommoor** [comment]
@senyuuri could you confirm that you're running the latest release? A variation of the bug still exists however it should at least show a banner at the top that tells you the document was deleted

**Comment by senyuuri** [comment]
@tommoor seems we're not running the latest release. Git log shows that our branch is newer than the latest v0.37  (released on 16 Oct).


```
commit 682151554bc69ec49c80e1a792609a3ee1ede52d (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Tom Moor <tom.moor@gmail.com>
Date:   Mon Nov 18 20:14:55 2019 -0800

fix: Additional SQL cascades required
```

**Comment by thenanyu** [comment]
to clarify, the current version of the error returns an auth error when attempting to edit a deleted document

![image](https://user-images.githubusercontent.com/427579/92316886-cb288600-efae-11ea-8faa-10b42813a7ca.png)

**Comment by thenanyu** [comment]
![image](https://user-images.githubusercontent.com/427579/92331721-8ee83a80-f02d-11ea-97aa-9aaf72b88761.png)
