### ISSUE TITLE
LHN can get in a dual highlight state

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#1096]
![image](https://user-images.githubusercontent.com/427579/70383029-cf3e4f00-191b-11ea-85e0-6e2f1b62094b.png)

### repro

1. mousedown on a navigation item
2. drag and release

**Comment by tommoor** [comment]
I think the active styling should just be tweaked to be more of an outline, so it's visually different to "selected"

**Comment by tommoor** [comment]
Resolved in https://github.com/outline/outline/commit/bf5f83e97d95fecc575fedae445d6f38e83aa3d7
