### ISSUE TITLE
show style toolbar on hover rather than whenever text is highlighted

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#1099]
![image](https://user-images.githubusercontent.com/427579/70490522-70abd900-1ab3-11ea-93bb-b86962afc021.png)

For users that navigate primarily with keyboard, the constant toolbar popping gets in the way

**Comment by tommoor** [comment]
Will try and fix as part of https://github.com/outline/rich-markdown-editor/pull/150

**Comment by tommoor** [comment]
We discussed this IRL and decided it wasn't worth it
