### ISSUE TITLE
Improved document viewers UI

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1105]
- New flyout shows who's viewed a document, when, how many times etc.

design: https://www.figma.com/file/GuoXp2gvvPykC9Ug3EkUFX/Viewer-menu?node-id=0%3A1

**Comment by MatheusRV** [comment]
How could I contribute to this? Any improve idea?

**Comment by tommoor** [comment]
Yea, this is kind of a placeholder issue – I have thoughts in mind but need to mock up some designs first

**Comment by MatheusRV** [comment]
Use new flyout menu - https://github.com/outline/outline/pull/1399#issuecomment-670962727

**Comment by renanfilipe** [comment]
I'll be working on it.

**Comment by a2tm7a** [comment]
Can we sort the list of people viewing the document in the order of ascending recency? https://github.com/outline/outline/discussions/1556

**Comment by matbrgz** [comment]
Still need it.
