### ISSUE TITLE
Line breaks are not recognized in cells of a table

### ISSUE THREAD

**Issue by JoeyJanson** [outline/outline#1107]
![outline-line-break-table_1](https://user-images.githubusercontent.com/22045972/70888795-691f8f00-1fe1-11ea-9d22-1bd2e14f8f6c.gif)

**Comment by tommoor** [comment]
Thanks for filing 👍 – this will be a relatively high priority fix.

**Comment by tommoor** [comment]
Will be attempting to fix this as part of https://github.com/outline/rich-markdown-editor/pull/150

**Comment by JoeyJanson** [comment]
@tommoor You mentioned it earlier but will this one still be fixed with https://github.com/outline/rich-markdown-editor/pull/150 ?

**Comment by tommoor** [comment]
Just started on the tables part of that so I can't say for 100% sure yet, but still hopeful.

**Comment by grv231** [comment]
Just ran into the same issue. Would really like some support on this, as this feature is not appealing to our folks who are used to excel tables :)

**Comment by JoeyJanson** [comment]
@tommoor Great, big improvements again! What is the status for this one? https://github.com/outline/rich-markdown-editor/pull/150 is merged but I can't see the fix for this one.

**Comment by tommoor** [comment]
Unfortunately a change to support line breaks in cells didn't make it into the release as much as I thought it might, the PR was already months in the making and I didn't want new functionality to become a blocker.

I'd still like to get to this, I might move this issue to the outline/rich-markdown-editor repo – in that case another user of the OSS library might take it on before I can get to it.

**Comment by MatheusRV** [comment]
Seems related to https://github.com/outline/rich-markdown-editor/issues/206. I think we could close this.
