### ISSUE TITLE
Child documents fixed to the bottom when there is content

### ISSUE THREAD

**Issue by JoeyJanson** [outline/outline#1112]
Is this correct? Works as designed? 

I think it would be better to place it always directly under the content instead of stuck to the bottom. Don't you think, @tommoor ?

![outline-child-margin](https://user-images.githubusercontent.com/22045972/71091009-96686a80-21a4-11ea-93b2-60ec6be0c66a.gif)

**Comment by tommoor** [comment]
Literally the question I asked myself a few hours ago… https://github.com/outline/outline/pull/1110
