### ISSUE TITLE
Sign-in broken via both slack and google

### ISSUE THREAD

**Issue by compengsamit** [outline/outline#1116]
I was trying to set up outline and found that the sign-in via google and slack is now broken. You will be able to to login first time. However, once you logout and login back, it gives an error:

"**Authentication failed - we were unable to sign you in at this time**."

I further enabled detailed logs and found the below error in the logs:

**EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL;**

Further, I checked out and found that it was trying to insert a row in the 'users' table and getting failed because of duplicate key error for the 'email' field.

This can also be produced in the development mode using docker-compose. 

I updated the HEAD to 5731ff34a44b7a701c0976fefd95e9281695a09d (Dec 7) and everything works fine now. 

Kindly check and let me know if this is a bug or something is missing from my side in the setup.

**Comment by vizcay** [comment]
@compengsamit same issue here, checked out tag `v0.38.0` while running locally on production mode with `yarn start`.

I was able to setup Slack OAuth and the first time and login and create wiki pages etc. Everything seemed to work fine.. then after a log out and log in.. totally stuck with:

> Authentication failed - we were unable to sign you in at this time. Please try again.

**Comment by vizcay** [comment]
More info: I've just nuked the db, checked out `v0.37.0` and setup everything again. The bug wasn't present there so it must be introduced on `v0.38.0`.

**Comment by filipenatanael** [comment]
I got the same issues yesterday! I tried several approaches but it didn't work. I noticed the cookie were passed as `undefined` then I thought, it might be something related to my insecure subdomain. I tried to add a nginx reverse proxy to serve instance but I didn't get success either. Than I decided to downgrade outline version to `v0.37.0` and evetything it working now.

**Comment by filipenatanael** [comment]
I got the same issues yesterday! I tried several approaches but it didn't work. I noticed the cookie were passed as undefined then I thought, it might be something related to my insecure subdomain. I tried to add a nginx reverse proxy to serve instance but I didn't get success either. Then I decided to downgrade outline version to v0.37.0 and everything it working now.

**Comment by filipenatanael** [comment]
I got the same issues yesterday! I tried several approaches but it didn't work. I noticed the cookie were passed as undefined then I thought, it might be something related to my insecure subdomain. I tried to add a nginx reverse proxy to serve instance but I didn't get success either. Then I decided to downgrade outline version to v0.37.0 and everything its working now.

**Comment by filipenatanael** [comment]
I got the same issues yesterday! I tried several approaches but it didn't work. I noticed the cookie were passed as `undefined` then I thought, it might be something related to my insecure subdomain. I tried to add a nginx reverse proxy to serve instance but I didn't get success either. Then I decided to downgrade outline version to `v0.37.0` and everything its working now.

**Comment by tommoor** [comment]
Looking into this – do you know if you sent out any invites from within the app? I have some leads as to what the issue might be.

**Comment by compengsamit** [comment]
@tommoor I did a fresh install and did not send out any invites or created any collection. Just a fresh install, sign-in and sign-out and then trying to sign in again doesn't work.

**Comment by tommoor** [comment]
This is now addressed on master, thanks for the heads up – I'll publish a point release shortly. 

If you have existing users that were created they'll need to be wiped from the DB, the easiest way to do this is to just make the email field a blank string.
