### ISSUE TITLE
Changing towards passport.js for authentication

### ISSUE THREAD

**Issue by Arteneko** [outline/outline#1120]
Lots of different OAuth providers are being requested, e.g. in #755, #962, or some other issues.

I'm in the process of working for #962 and was wondering about moving towards passport.js, which would make for a much easier provider addition procedure.

**Comment by tommoor** [comment]
Open to it. I think the path to getting this merged would be to covert the existing auth routes one at a time before adding any new ones though.

**Comment by Arteneko** [comment]
Fine by me. I'm not particularly familiar with koa / sequelize and the current auth flow.

From what I've been able to see in `/server/auth`, while `google` is using their oauth client library, but the Slack one seems like a custom implementation, so I don't know how such a change would be done, and would tend to avoid doing it myself.

**Comment by tommoor** [comment]
Yes, I believe when Slack was done ~3 years ago they didn't officially support "sign in", we were kind of hacking their OAuth flow to achieve it.

**Comment by MatheusRV** [comment]
@Arteneko is possible to help me with this?

**Comment by Arteneko** [comment]
I don't know how to work with React, and I've never been able to set up a local outline instance, so it is frozen on my side.

**Comment by jakoblorz** [comment]
Sadly passport.js doesn't support discord login strategies (related to #729) @Arteneko.
I have worked with the backend-stack outline uses countless times before, so I think I will take this passport.js integration for a spin, when I'm done with this term's exams (that is Mid-March).

@tommoor Is that okay with you? I read your [tweet](https://twitter.com/outlinewiki/status/1222299290862645248) regarding rebuilding outline, does it make sense to invest in improving / iterating on the current version? Does this rebuild happen more on the frontend, backend or full-stack?
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">We&#39;re currently completely rebuilding the Outline editor to make it more resilient and performant. ⚡️<br><br>There are lots of nice improvements being made at the same time – now would be a good time to make your editor-related requests!</p>&mdash; Outline (@outlinewiki) <a href="https://twitter.com/outlinewiki/status/1222299290862645248?ref_src=twsrc%5Etfw">January 28, 2020</a></blockquote>

**Comment by tommoor** [comment]
Hey, the rebuild is just of the core editor itself, doesn't affection authentication / team management etc :) . Can follow that one here:
https://github.com/outline/rich-markdown-editor/pull/150
