### ISSUE TITLE
Add ability to share to an existing user from document

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1122]
- Click "Share"
- Opens a fly-out with option to copy link or choose existing users to notify about the document

**Comment by MatheusRV** [comment]
Some idea design:

![image](https://user-images.githubusercontent.com/23284276/89722263-edce7b80-d9bd-11ea-8fc4-1225dd202e0d.png)
![image](https://user-images.githubusercontent.com/23284276/89722275-15254880-d9be-11ea-8915-d76d6f40f74a.png)

**Comment by matbrgz** [comment]
Keep it open please
