### ISSUE TITLE
Timestamps should update while a page stays loaded

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1126]
The `Time` component should include a shared timer that refreshes any mounted components once per minute so that the timestamps update inline without needing a full page re-render.

**Comment by TommyJackson85** [comment]
I will work on this now.

**Comment by TommyJackson85** [comment]
Where is the Time component? I tried searching it from the text editor and it doesn't seem to be appearing.

**Comment by TommyJackson85** [comment]
I can't find the Time component. Was it removed from another pull request? I tried searching Time.

Any other suggestions on where to start with this issue?

**Comment by tommoor** [comment]
https://github.com/outline/outline/blob/master/shared/components/Time.js

**Comment by TommyJackson85** [comment]
I will try to fix it in a day or 2. If anyone wants to take over and create a PR they can but I would like to atleast try this if its atleast under no pressure to be done.

**Comment by taylorlapeyre** [comment]
I think I can take this
