### ISSUE TITLE
Serving private content from s3

### ISSUE THREAD

**Issue by HUSSTECH** [outline/outline#1131]
Hello :wave:, first off this wiki is really quite fantastic! Neat, ergonomic and concise code. Thank you creators and contributors for developing it. I wanted to share some of my thoughts/experiments, on what turned out to be a continuation of this issue #796. I have had to do a fair bit of work with private/protected/restricted assets in the AWS environment specifically, so I thought I'd have a look at what it may take to bring it here.

## Summary
* switch the S3 bucket to be private, and set ACLs when uploading to private
* put an AWS CloudFront (CF) distribution in front of the S3 bucket, with signed cookies as access controls. (ccokies are good as they are passive, and don't need any dynamic rewrite/redirect to provide volatile signed urls for example.)
* simple find/replace the s3 image urls when serving a document with the url of the CF distribution

## Method
This can be broken up into two parts, *outline setup* and *aws setup*. I did this all using the docker-compose development setup for ease of debug.

### outline setup
My demo/mvp changes can be found on a fork [here](https://github.com/HUSSTECH/outline/tree/cf-private-content).

The changes here were not that large, but are done in a bit of a sub-optimal way at the moment. The main things to do in the outline codebase were to
1. setting s3 upload ACLs to `private`
1. be able to set cookies which would be used to authenticate to CF later
1. add a module (`cf.js`) to do all the CF related tasks and other miscellaneous helper functions for now
1. replace the s3 urls on the fly with the CF urls whenever documents text content is called
1. via the addition of 3 new config parameters (`AWS_CLOUDFRONT_URL, AWS_CLOUDFRONT_KEY_PAIR_ID, AWS_CLOUDFRONT_PRIVATE_KEY`), allow this to be toggled on/off

I added an nginx proxy to the compose definition, as per #898, required to make ssl and custom domain SSO work nicely. It is also needed to make the cookies set themselves properly.

### aws setup
This is the worst part! Working with cookies, DNS and CF is always tricky because there is no staging environment of the internet! I'll just leave a diagram below and the links required to replicate the CF setup.

![image](https://user-images.githubusercontent.com/5672889/71564076-4d60c200-2a92-11ea-86b1-c27acf550ffe.png)

- AWS docs [Serving Private Content with Signed URLs and Signed Cookies](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/PrivateContent.html) -> follow the links about using signed cookies, and then signing with "custom polices"
- Critical step is to have a trusted signer setup on your account, see AWS docs [Specifying the AWS Accounts That Can Create Signed URLs and Signed Cookies (Trusted Signers)](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-trusted-signers.html).
- a nice video step by step from AWS [How to Set up an Amazon CloudFront Distribution for Your Amazon S3 Origin](https://youtu.be/KIltfPRpTi4) (check yes for using signed cookies...the presenter skips this.)
- useful context blog post [Using Cloudfront Signed Cookies](https://www.spacevatican.org/2015/5/1/using-cloudfront-signed-cookies/)
- useful context blog post [Node.js — Serve Private Content using AWS CloudFront](https://medium.com/@apalshah/node-js-serve-private-content-using-aws-cloudfront-992e846259ae)

## TODOs
* Wanted to just stop at a quick MVP working setup, just to prove it could work. I have left TODO comments (some questions!) in my diffs. Mainly I think I'd say my implementation is messy, and likely has stuff in the wrong/inappropriate places.
* Not sure if replacing image urls on the fly is the right path. Maybe they can just be written directly to the committed document text with the CF urls in the first place.
* I don't like how I'm checking for the CF cookies every request. I just piggy backed on the `auth()` middleware and tried to limit the work being done in setting the cookie unless needed. TBH, I have seen cookie checks/sets on every request as a pattern in many other web frameworks...so maybe it has to be that way!

## Other stuff
* I also added the option to set a prefix on the S3 object key. This is not necessary to implement serving private content in this way, but I just found it a nice to have. E.g. you could eventually use the same bucket for different types of assets such as attachments.
* Not on my demo repo at the moment, but I was playing around with eliminating having to explicitly provide AWS credentials in the config when running on an ec2, and instead just letting the instance credentials take care of it. Works fine except only thing stopping it was the `makeCredential` function, as it needs an explicit `AWS_ACCESS_KEY_ID` set. Was thinking as you're already on the server side, it would be possible to use the `AWS.s3.putObject` or `AWS.s3.upload` methods directly, as they don't need a policy to be signed. Or I have often returned a signed POST url which allows the users' browsers to upload directly themselves. Offloading the work from the server entirely.

**Comment by HUSSTECH** [comment]
On my fork I just added in this [commit](https://github.com/HUSSTECH/outline/commit/167fd261ba8dbe063401cee3a246e1e2efa32971) an example of the original proxy idea from #796. I didn't implement the part which writes the url to the document, I just changed it manually in the database for now. The format of the saved image urls should now be this in the markdown:
```
![](/api/images.info?key=uploads/622109e6-2cdd-11ea-978f-2e728ce88125/f4f225d4-0d9f-4b0b-b9eb-54afbdb291f8/Top_secret.png)
```
When the image is loading on the page, it hits the proxy and then is issued a `302` redirect with the signed s3 url.

Works very well/fast, and has way fewer moving parts that the CloudFront method above. Even though the custom DNS features CF brings are great...it is a pain to set up (speaking as someone who has had to set up many CF distributions!)

### note
if you're trying to replicate/run this from my fork and branch, to test the s3 proxy method, you need to have the environment variable `AWS_CLOUDFRONT_URL` **not set**, so that you don't enter CloudFront mode.

**Comment by tommoor** [comment]
Hey @HUSSTECH – thanks for working on this, I'd definitely like to push on the approach where cloudfront is not needed. The project already needs a number of external services to work and I'd like to ensure that cloudfront or any additional env variables are not a requirement. Of course individual installations can always put cloudfront or any other CDN infront of S3 if they desire.

The other thing we need to take into account is how the images behave when a data export is requested. I think the easiest thing would be to pull the images out of each document, re-write the image path and include the image asset in the zip file.

Could you put in a PR so that I can comment directly?

**Comment by HUSSTECH** [comment]
Hi @tommoor, thanks for the support! I have made a PR #1137. I wasn't as comfortable with the export/zip code, but I got that "functional" too here. Nothing is sacred in my implementation, any and all comments welcome!

**Comment by tommoor** [comment]
I'm closing this in favor of your PR and the existing issue at #796 – trying to keep a single issue for each feature.
