### ISSUE TITLE
some services (s3 ,slack,google) can not use

### ISSUE THREAD

**Issue by bluegeek** [outline/outline#1132]
I am from China.as is known to all,We hasve the GFW,some services (s3 ,slack,google) can not use。Could you please support for other services？like email register,local storage etc.
Chinsese can not   support well.
![image](https://user-images.githubusercontent.com/3932305/71565095-e0771780-2ae5-11ea-85df-08d2f7459cee.png)
it should be 'shijie' ，but i got 'hijie'。's' is missed.

thank you

**Comment by tommoor** [comment]
Hi, I'm going to combine this with the existing issue for chinese language / soft keyboard support: https://github.com/outline/outline/issues/1027

Work should be starting in the next week to migrate our editor to a new framework that will fully support soft keyboards.

This project does not plan on implementing email/password sign-in, however SAML/LDAP is on the roadmap which should help out for most business usecases.
