### ISSUE TITLE
support embedded video

### ISSUE THREAD

**Issue by IdrisMiles** [outline/outline#1135]
Hey,

Are there any plans to support embedded video?
It would be great to be able to upload a mp4 video file for example

**Comment by tommoor** [comment]
We're planning on some file attachment support this year, I'm not sure yet whether this will include embedded videos – but it could.

For now your best bet is to upload to YouTube or Vimeo and make the video private/unlisted, you can then paste the link in Outline to get an embedded player.

**Comment by DeeGeeTill** [comment]
While this is by no means a good solution, for now we've decided to integrate just the embeds that Google Drive give us. JIC anyone is searching on Google for this, and wants a quick and dirty solution:

1. Add a new file in the `apps/embeds` section called Drive.js (or whatever you want to call it) and just add the file https://gist.github.com/DeeGeeTill/5343e777f1a1d25092c700f544b3d5fb
2. Modify the index.js file as well (see the comment on the gist)

Again, it's a super-quick bodge job that _will_ crash, but it's better than nothing. 

To use it, upload a file to Google Drive, click the Share Link button as you would normally and then paste that link into your Outline doc.

It works with most Google Drive files including video.

**Comment by tommoor** [comment]
@DeeGeeTill good stuff, this is exactly why we built the plugin system this way – if you're able to get it stable in the future I'd except a PR to add support for these to the main codebase

**Comment by acrob0t** [comment]
any chance of adding support for video links from Google Drive that embed the same way as YouTube or Vimeo?

**Comment by mxzinke** [comment]
#1804 Should address this.

**Comment by MatheusRV** [comment]
#1804 Definitely could help on this.
