### ISSUE TITLE
Migrate data

### ISSUE THREAD

**Issue by jastabile** [outline/outline#1136]
Hi!

Is there a simple way to migrate all the documents data in self hosted universe?
I am deploying outline on a new server and want to restore my data from outline of the old server.

Thanks

**Comment by tommoor** [comment]
Hi – you should just copy the postgres database itself or connect to the same database from the new server. The are lots of guides on how to do this, eg:
https://www.postgresqltutorial.com/postgresql-copy-database/

There is no permanent data stored on the server Outline is hosted on.

**Comment by jastabile** [comment]
@tommoor 
I am having problems with that. I am deploying with docker compose. 

I had copied the postgres database and made a volume. In the db i can see its all ok, but when i tried to login there is an error:

![image](https://user-images.githubusercontent.com/28830749/71683381-2bf12600-2d71-11ea-8e1d-2d8ff62250ec.png)

The log is:
`UnhandledPromiseRejectionWarning: Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt`

**Comment by tommoor** [comment]
If I had to guess it would be that the `SECRET_KEY` environment variable does not match the one on the previous server. They must be the same or encrypted fields in the database cannot be decrypted.
