### ISSUE TITLE
state cookie not set correctly for heroku domains

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#1142]
I'm trying to use the deploy to heroku button and run an instance of outline on the default herokuapp subdomain.

The URL looks like `https://my-app.herokuapp.com`. I think the outline code makes some assumptions that any subdomain is team-specific and not part of the base application URL.

https://github.com/outline/outline/blob/98dda567c222bcac48f2c2889f58376a73756aad/server/auth/slack.js#L30
Because the subdomain is stripped, the cookie attempts to be set on `.herokuapp.com` which is actually [blacklisted by browser vendors](https://devcenter.heroku.com/articles/cookies-and-herokuapp-com) due to its status as a hosting platform. 

Therefore, the cookie is unavailable to the my-app subdomain, and the result is a state mismatch error.

Instead of using the stripped domain, could we instead use the env var `BASE_URL`? I would imagine a similar issue would occur for the URL `my-app.co.uk`, so it's not just a heroku-specific problem

**Comment by tommoor** [comment]
If `SUBDOMAINS_ENABLED` = `false` perhaps we can avoid subdomain stripping logic altogether?

**Comment by thenanyu** [comment]
`SUBDOMAINS_ENABLED` is already false in this case; I don't think stripping the subdomain is the right approach here because it's unpredictable how the app will be deployed. There could be any number of subdomains even in a single user install.

For example: `outline.corporate.ikea.com`, or `outline.cs.berkeley.edu`

**Comment by tommoor** [comment]
> `SUBDOMAINS_ENABLED` is already false in this case

Yep, I understand. And to clarify this environment variable turns on support for having teams under multiple subdomains. So If it's `false` I think we could avoid doing any special logic with the cookie domain altogether... then it's making no assumptions

**Comment by mduecker** [comment]
Did anybody get it to work with the above mentioned PR #1145?
I'm still struggling with my Heroku setup and getting "Authentication failed" on /?notice=auth-error&error=state_mismatch

**Comment by tommoor** [comment]
Have you tried using that PR? I'm still looking for confirmation from folks in this situation

**Comment by mduecker** [comment]
Yes, I forked the outline repo and then merged your PR:
https://github.com/mduecker/outline

And then deployed this on Heroku with Slack configured:
https://dashboard.heroku.com/new?template=https://github.com/mduecker/outline/tree/master

Trying it now also with your PR branch directly:
https://dashboard.heroku.com/new?template=https://github.com/outline/outline/tree/fix/issue-1142

**Comment by enzolutions** [comment]
Hi folks.

I am running outline in a Heroku environment, I applied the PR https://github.com/outline/outline/pull/1145 and in my env variables  SUBDOMAINS_ENABLED = false

At my Heroku app is use a custom domain like `handbook.example.com`, when I try to do login with Slack, this is what I got my logs.

```
2020-03-26T19:08:25.906529+00:00 heroku[router]: at=info method=GET path="/auth/slack.callback?code=944351738855.1031154543318.8f6cfe7e4e3b016a9a2d06c6c73d9cd8b84ad145f7d01724d994515afb465fb8&state=rfsnql"
```

Then I got redirected to the homepage with an authentication problem.

```
2020-03-26T19:08:26.213099+00:00 heroku[router]: at=info method=GET path="/?notice=auth-error"
```

Any ideas what could  I change in my environment variables to enable the Slack login.

Thanks in advance for your help.

**Comment by tommoor** [comment]
@enzolutions I'd expect the underlying error to also appear in the server logs, do you not see that?

**Comment by enzolutions** [comment]
Hi @tommoor thank you for the follow up to this ticket

I don't get any error from the Heroky dyno web ( nodejs)

```
heroku logs --dyno web
2020-03-29T20:05:46.580001+00:00 heroku[web.1]: Cycling
2020-03-29T20:05:46.584447+00:00 heroku[web.1]: State changed from up to starting
2020-03-29T20:05:47.823734+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-03-29T20:05:47.912564+00:00 heroku[web.1]: Process exited with status 143
2020-03-29T20:05:58.385154+00:00 heroku[web.1]: Starting process with command `node index.js`
2020-03-29T20:06:02.165882+00:00 app[web.1]:
2020-03-29T20:06:02.166032+00:00 app[web.1]: Running Outline in production mode.
2020-03-29T20:06:32.682624+00:00 app[web.1]: (node:4) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Redis]. Use emitter.setMaxListeners() to increase limit
2020-03-29T20:06:32.685596+00:00 app[web.1]:
2020-03-29T20:06:32.685599+00:00 app[web.1]: > Listening on http://localhost:42647
2020-03-29T20:06:32.685600+00:00 app[web.1]:
2020-03-29T20:06:33.062599+00:00 heroku[web.1]: State changed from starting to up
```

**Comment by benmort** [comment]
i came across this also > needed custom domain

**Comment by asherccohen** [comment]
I confirm this is still an issue, having it myself. The state cookie doesnt get stored when outline is deployed to heroku (with no custom domain), we're simply redirected to login screen with authentication error.
In my case I'm using slack, I think that Google would work but I don't have a gmail business account so I can't try.

**Comment by thenanyu** [comment]
hey folks, I got this branch to work on a heroku subdomain — I think the issue is you may be setting `SUBDOMAINS_ENABLED` to `false` instead of removing the config altogether. Because the config is a string, `"false"` evaluate to a truthy value

that seems to be what's happening for you @enzolutions

**Comment by enzolutions** [comment]
Hi @thenanyu and @tommoor 

I remove the config `SUBDOMAINS_ENABLED` from my Heroku config and revert and reapply the diff for https://github.com/outline/outline/pull/1145 but still, I got the following error when I tried to log in with slack

<img width="665" alt="Screen Shot 2020-05-11 at 11 56 28 am" src="https://user-images.githubusercontent.com/907914/81517875-96e5e580-937f-11ea-8717-c0182482cb59.png">

In the URL I got these parameters `?notice=auth-error&error=state_mismatch `

However, I got an email from slack notifying me about the new login, as you can see in the following image.

<img width="555" alt="Screen Shot 2020-05-11 at 11 14 45 am" src="https://user-images.githubusercontent.com/907914/81518002-fe9c3080-937f-11ea-8174-5a2666364a93.png">

The login with Google is still working.

**Comment by thenanyu** [comment]
@enzolutions can you try again after clearing cookies? This works for me on a fresh install that I set up yesterday.
