### ISSUE TITLE
On master — Share links throw a null pointer

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#1143]
![image](https://user-images.githubusercontent.com/427579/71770466-932de800-2ee1-11ea-88e0-45cb5c3ff83e.png)

The stack trace leads to this line
https://github.com/outline/outline/blob/146e4da73bf6ec1110130020c699cd075b9205b7/app/scenes/Document/KeyedDocument.js#L18

**Comment by tommoor** [comment]
Glad I let these changes "bake" for a bit before finalizing a release
