### ISSUE TITLE
Visually differentiate unread documents in list views 

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1150]
I would like to add two new visual treatments to the document list views to help surface information. On teams were document updates are happening regularly it can be more difficult to find new and relevant docs that are being added.

- A subtle tweak in visual treatment when the current user has not read the document (perhaps bolder?)
- A "New" badge when the above is true and the document was created since users last visit.

To achieve this we would need to query views for the user whenever a document is returned and set a new property on the document.

### Note
I'm mildly concerned about performance of adding a join on the views table – need to sure it doesn't regress in any measurable way. Perhaps this data can be loaded async from the client?

**Comment by tommoor** [comment]
Just adding a note that this was recently requested on Hacker News, I still think this is quite important and will prioritize soon.

**Comment by thenanyu** [comment]
seems like this is fairly achievable because views are already recorded on a per-user basis right?

**Comment by tommoor** [comment]
Yep, correct

**Comment by guilherme-diniz** [comment]
@tommoor can you explain me this approach of query views (Which view has what, and how you were thinking)?

**Comment by tommoor** [comment]
Sure, we have a [View model](https://github.com/outline/outline/blob/develop/server/models/View.js#L7) – we store a single record per user, per document which records:

- First viewed
- Last viewed
- Last editing
- How many times (we're throwing away the individual view data)

So, I think part 1 of this is to return with a document when the user last viewed at as a new property on the document. Then part 2 is to add the UI treatments in the frontend and make sure that when a view is created in the frontend we update this property on the document locally.
