### ISSUE TITLE
Nested Document not rendering.

### ISSUE THREAD

**Issue by AnishLushte07** [outline/outline#1154]
Hi guys,
I'm trying to use nested document structure but facing weird issue.
When i click on nested doc I could see location url changing in browser but page is not rendering. On refresh i could see my doc. Please help.

**Comment by tommoor** [comment]
Are you seeing this issue on self hosted or the version at getoutline.com?

Does the doc continue to show the old doc from before the click?

Could you check to see if there are any errors in the console?
