### ISSUE TITLE
Serialize "class level" policies onto the team policy object

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#1158]
Some policies, especially admin ones, are effectively duplicated across the primary domain and the team domain. For example — whether to allow a user to invite new members to the team.

We need to do this in order to expose the policy on the frontend, because every policy must be tied to an entity object. Policies for domains (like "Users") rather than specific records don't get serialized in the normal process.

It would be more DRY to keep the policy definitions in their domain and just attach them to the Team entity.

**Comment by tommoor** [comment]
Totally agreed, if we can expose these on the team in an automated way that would be great. We could also consider having the team policy simply call the underling users policy, for example. so at least the logic isn't duplicated.

**Comment by iamsaumya** [comment]
From what I understand we don't want to use `user.isAdmin` on the frontend rather something very specific like `can.canInvite` or `can.createDocument`.  However, I guess I am missing some building blocks here. 

What is a primary domain and a team domain? 

What is the difference between these two policies? when to use the latter policy? 
https://github.com/outline/outline/blob/ad8c08497c6d477dad878fefdf4d73ca375556ca/server/policies/team.js#L20-L23
https://github.com/outline/outline/blob/ad8c08497c6d477dad878fefdf4d73ca375556ca/server/policies/user.js#L15-L17

An example of what is wrong and what needs to be done will help me I guess.

**Comment by tommoor** [comment]
> What is the difference between these two policies? when to use the latter policy?

The latter policy is just wrong and not currently used (thankfully). Let me take a look at this tomorrow, I should get time to whip up a PR that we can use for the read-only work.
