### ISSUE TITLE
self hosted plus AWS Cloudfront question

### ISSUE THREAD

**Issue by lfreneda** [outline/outline#1163]
After added CloudFront on my self hosted outline installation I'm redirected to /undefined over and over :(

/undefined?done=1569407928706
/undefined?done=1569407958977
/undefined?done=1569407957006

Looks like is something related to subdomains..

Everything is working good before CloudFront :thinking: 

Anyone who face it could help me out? :haircut_man:

**Comment by ADWadmin** [comment]
I came across something similar.
In some cases (not always), after authorization or updating the document, the page began to reload cyclically. At the same time, the browser address bar displays the same as yours:

> /undefined?done=1569407928706
> /undefined?done=1569407958977
> /undefined?done=1569407957006

I do not know what exactly was the solution to this problem.
But after redeploying using `Node.js v12.14.1` instead of `Node.js v13.2.0` this did not happen.

**Comment by lfreneda** [comment]
> I came across something similar.
> In some cases (not always), after authorization or updating the document, the page began to reload cyclically. At the same time, the browser address bar displays the same as yours:
> 
> > /undefined?done=1569407928706
> > /undefined?done=1569407958977
> > /undefined?done=1569407957006
> 
> I do not know what exactly was the solution to this problem.
> But after redeploying using `Node.js v12.14.1` instead of `Node.js v13.2.0` this did not happen.

Thanks, I'll try this one :haircut_man:

**Comment by tommoor** [comment]
The core team hasn't run the project behind Cloudfront so we don't have any knowledge of this particular setup I'm afraid. Closing out as this doesn't seem to be an issue with the software, if you find out otherwise feel free to reopen or continue discussion in this ticket.

**Comment by ADWadmin** [comment]
@lfreneda Did switching to `Node.js v12.14.1` solve the problem? I am curious.
