### ISSUE TITLE
Helm Chart for Kubernetes?

### ISSUE THREAD

**Issue by iMerica** [outline/outline#1168]
Hi,

Thanks for working on this project. I'm in the process of deploying this on Kubernetes and I'm curious if anyone has created a Helm chart yet? It would be awesome to deploy Outline with a single command (`helm install`).

Thanks,

Michael

**Comment by tommoor** [comment]
It hasn’t been created yet I’m afraid, but we’d be open to the PR

**Comment by iMerica** [comment]
I just discovered that Outline only offers Slack Authentication so I'll have to halt Kubernetes work on this after all.

If anyone has a fork that supports regular email/password authentication please shoot me an email imichael@pm.me !

**Comment by zuc** [comment]
@iMerica I drafted something here: https://github.com/zuc/helm-charts/tree/master/charts/outline

It's really not prod-ready, I'll refine it as soon as I have time, but if you want to have a look you'll be more than welcome!

**Comment by MatheusRV** [comment]
we are working in https://github.com/outline/outline/pull/1183 to put new login methods.

**Comment by Hokwang** [comment]
@zuc I hope your chart merge to here.

**Comment by MnrGreg** [comment]
@matbrgz added Azure parameters to @zuc chart. @zuc maybe you want to merge here?

**Comment by zuc** [comment]
@matbrgz @MnrGreg I'm more than happy to open a PR if @tommoor agrees!

**Comment by josephfinlayson** [comment]
@tommoor what do you think?

**Comment by tommoor** [comment]
The problem is maintenance, there isn't one on the team with knowledge of k8s.

So as much as I'd love to include official deployment options of all types it might be best to keep external.

**Comment by TartanLeGrand** [comment]
@tommoor  you are saying that even for hosted, you don't use k8s? 🤔

**Comment by xyfleet** [comment]
@tommoor any progress on helm chart release?

**Comment by reggermont** [comment]
Outline is such a great project, part of my company ecosystem, but lack of such important features to be deployed by personal users

Same issue with https://github.com/outline/outline/issues/1881
