### ISSUE TITLE
Any one becomes Admin who Login as "Sign In With Google"

### ISSUE THREAD

**Issue by kevalkothari** [outline/outline#1169]
Hello @tommoor 

Hope you doing well. I tried to install Outline Self Hosted and configured it to "Login With Google" ,  The issue currently I am getting is any one who login with Google becomes Admin.

And Also Admin is not able to see the List of User who joined.  Is this Bug or I am missing any important settings?

Thanks,
Keval

**Comment by tommoor** [comment]
There aren't any settings that cover this behavior. It sounds like everyone is signing in with Google accounts that belong to different teams…

**Comment by kevalkothari** [comment]
Hello @tommoor 

Thanks for your comment I got it now.  Just one question. Is it possible to share one Collection with multiple teams ?

Thanks,
Keval

**Comment by tommoor** [comment]
That's not possible, the wiki is designed around a "team" being the highest level entity at the moment – we'll be adding "groups" within teams soon for another level of organization.

Hope that helps, I'm going to close this as resolved
