### ISSUE TITLE
Checking version and updating Docker based deployment

### ISSUE THREAD

**Issue by vikasprogrammer** [outline/outline#1170]
Question 1: How to check in the UI that which version I am running. 

Question 2: I am running the full docker suite in production. But I am unable to update outline container to the latest version (0.39.0 as of writing). I tried this:

```
git pull
git checkout tags/0.39.0
docker-compose down
make up
```

**Comment by tommoor** [comment]
The tag is named `v0.39.0`, there is currently no way in the UI to check the version but that's a good idea .
