### ISSUE TITLE
Unhandled promise rejection from requesting access to Slack Workspace

### ISSUE THREAD

**Issue by TommyJackson85** [outline/outline#1171]
I requested another Pull request from the master branch and I restarted another development environment set up, from creating new keys in the .env file and generating a new Slack App and Workspace, HOWEVER..

I am getting an Unhandled promise rejection from requesting permission to access Slack Workspace. I created a "fake-app-2" app and a "fake-app" workspace. Here is the heading from the request page:
'fake-app-2 is requesting permission to access the fake-app Slack workspace'
On proceeding with this I get the following errors:

"Not Found" on the page

_From chrome console:_
`GET http://localhost:3000/auth/slack.callback?code=843234155683.934645818662.21a0f1db6a0e9cd641507043623c318f10f0b51209170b38688b9445f72e78ac&state=zaogsn 404 (Not Found)
Navigated to http://localhost:3000/auth/slack.callback?code=843234155683.934645818662.21a0f1db6a0e9cd641507043623c318f10f0b51209170b38688b9445f72e78ac&state=zaogsn
backend.js:32 Uncaught TypeError: Cannot read property 'sub' of undefined
    at g (backend.js:32)
    at e (backend.js:8)`

_From terminal console:_
`outline_1   |   <-- GET /auth/slack
outline_1   |   --> GET /auth/slack 302 4ms 497b
outline_1   |   <-- GET /auth/slack.callback?code=843234155683.934645818662.21a0f1db6a0e9cd641507043623c318f10f0b51209170b38688b9445f72e78ac&state=zaogsn
outline_1   |   --> GET /auth/slack.callback?code=843234155683.934645818662.21a0f1db6a0e9cd641507043623c318f10f0b51209170b38688b9445f72e78ac&state=zaogsn 404 306ms -
outline_1   | (node:40) UnhandledPromiseRejectionWarning: Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
outline_1   |     at Decipheriv.final (internal/crypto/cipher.js:170:29)
outline_1   |     at model.get (/opt/outline/node_modules/sequelize-encrypted/index.js:34:79)
outline_1   |     at model.get (/opt/outline/node_modules/sequelize/lib/model.js:3509:41)
outline_1   |     at model.funcs.<computed> (/opt/outline/node_modules/sequelize/lib/model.js:1098:25)
outline_1   |     at model.User.getJwtToken (/opt/outline/server/models/User.js:111:41)
outline_1   |     at _callee$ (/opt/outline/server/middlewares/authentication.js:133:45)
outline_1   |     at tryCatch (/opt/outline/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
outline_1   |     at Generator.invoke [as _invoke] (/opt/outline/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
outline_1   |     at Generator.prototype.<computed> [as next] (/opt/outline/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
outline_1   |     at step (/opt/outline/server/middlewares/authentication.js:38:191)
outline_1   |     at /opt/outline/server/middlewares/authentication.js:38:437
outline_1   |     at new Promise (<anonymous>)
outline_1   |     at Object.<anonymous> (/opt/outline/server/middlewares/authentication.js:38:99)
outline_1   |     at Object.signIn (/opt/outline/server/middlewares/authentication.js:84:5)
outline_1   |     at _callee2$ (/opt/outline/server/auth/slack.js:121:9)
outline_1   |     at tryCatch (/opt/outline/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
outline_1   |     at Generator.invoke [as _invoke] (/opt/outline/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
outline_1   |     at Generator.prototype.<computed> [as next] (/opt/outline/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
outline_1   |     at step (/opt/outline/server/auth/slack.js:41:191)
outline_1   |     at /opt/outline/server/auth/slack.js:41:361
outline_1   | (node:40) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
outline_1   |   <-- GET /favicon.ico
outline_1   |   --> GET /favicon.ico 200 12ms 953b`

I thought I set this up up properly from the Outline's Development process:
SECRET_KEY set to key generated from 'openssl rand -hex 32'
SLACK_KEY set to Client ID from Slack App
SLACK_SECRET set to Client Secret from Slack App
http://localhost:3000/auth/slack.callback set as a Redirect URL
I run `make up` regularly to set up development environment.

Anything else I could be missing that could help me avoid this issue? Might help to restart the a brand new repository or set up.

On a side note, yesterday I create a slack App and Workspace of the same name and was getting a different a failed authorisation error. Not sure if this was due to using the same name for both as I THINK I heard this causes issue. Now it's a different error with the App and Workspace being different names.

**Comment by tommoor** [comment]
Hard to say for sure but It seems likely that the `SECRET_KEY` value changed which is causing an error decrypting the values you previously had in the database… I recommend emptying the development database.

**Comment by TommyJackson85** [comment]
Is a Postgres database (DATABASE_URL and DATABASE_URL_TEST) required for the development environment? I am just looking up how to set one up but if its not required please let me know.
