### ISSUE TITLE
Tool to batch import markdown files (with Notion initial support)

### ISSUE THREAD

**Issue by paladini** [outline/outline#1172]
We're using Notion at our company and some people from our team started using the paid version of Outline. We would like to migrate the entire team from Notion to Outline, however there's no tool to migrate every article that we have at Notion to your platform.

A tool like that would be very useful and will attract a lot of people. If you're willing to doing that soon, you'll have more ~24 users. 

Desired features:

- [ ] The tool should be able to import articles in Markdown format (.MD) that are inside a recursive directory, but with special treatment for the ZIP given by the Notion export tool.
- [ ] Be able to traverse Notion exported folders and convert into beautiful collections at Outline
- [ ] Import images and multimedia content
- [ ] Import users and their relations with the articles created

Just another suggestion, thanks for your time!

**Comment by nokhodian** [comment]
This really will help us as well if you guys are developing it we will seriously move and I am sure many more do as well.

**Comment by MatheusRV** [comment]
I create a batch to import Confluence. I'm publishing it as open source.

**Comment by robertoamoreno** [comment]
> I create a batch to import Confluence. I'm publishing it as open source.

Did you release the batch import yet @MatheusRV

**Comment by Olshansk** [comment]
Hey, I wanted to follow up on a couple things:

1. Has a batch import tool been implemented yet?
2. For individual markdown files, even though https://github.com/outline/outline/discussions/1605 mentions that markdown import is supported, it doesn't seem to be working for me:

<img width="1668" alt="Screen Shot 2021-01-16 at 1 22 37 PM" src="https://user-images.githubusercontent.com/1892194/104819813-132da400-57fe-11eb-94ab-50c0c8a35fb5.png">

**Comment by tommoor** [comment]
@Olshansk I don't know why they would be disabled here, but you can always choose "Options -> All file formats" at the bottom of the import window to show all files.

**Comment by snoopckuu** [comment]
Hello, @matbrgz. Did you manage to release your batch confluence importer? We are interested in this functionality as well.

**Comment by fabiwlf** [comment]
I managed to move my notion documents just by drag and dropping all markdown files onto "collections" (left menu). It took a long time even for just 200 files (i think 10-15 minutes?, it uploaded each file separately) but it generally worked well!

**Comment by matbrgz** [comment]
Next week I'm publishing this.

**Comment by pulkitvyas08** [comment]
Any updates on this issue? Was the batch import tool implemented?

**Comment by tommoor** [comment]
Quick note for anyone subscribed to this issue – Notion import is now live.

**Comment by napest** [comment]
> Quick note for anyone subscribed to this issue – Notion import is now live.

Hi, thanks for the update, could you tell me when this feature will be in self-hosted version?

**Comment by Limezy** [comment]
Will be shipped with next version v0.64.0, which was scheduled to be this week. Don't know when Tom will decide to trigger a release but shouldn't be more than a few days

**Comment by paladini** [comment]
Thanks, mates!

**Comment by matbrgz** [comment]
Just release the version 0.8.0 to import from confluence https://github.com/matbrgz/confluence-outline-migration
