### ISSUE TITLE
Performance issues on getoutline.com

### ISSUE THREAD

**Issue by ADWadmin** [outline/outline#1173]
Hello!

First of all, I express my gratitude for the development of such a cool product!

I have performance issues. The situation is the same both on my own server and on getoutline.com

For reasons that are not entirely clear to me, this [document](https://github.com/outline/outline/files/4170178/RIPE.PART-ALL.txt) has been loading for a very long time. The page may freeze for several minutes, and the browser says: “The web page slows down your browser.”!

At first, I decided that this was due to the weight of the document (38 KB), but the [test](https://github.com/outline/outline/files/4170187/test.txt) document weighing 66 KB loads instantly.

The problem is probably Markdown specific markup.
I plan to write a lot of documents with similar markup. Such performance can be a problem =-(

**Comment by tommoor** [comment]
Hi @ADWadmin – yes I believe it's all of the code blocks in the document, they are expensive to process as each character is considered individually to see how it should be color/highlighted.

There is currently a big rewrite of the editor underway that addresses this though, using your expensive test document from above it renders in under 150ms in the new editor 👏

**Comment by ADWadmin** [comment]
Waiting for updates))
Thanks!

**Comment by tommoor** [comment]
This should be much better as of todays release.
