### ISSUE TITLE
Doc title if have _ the page will become Not found

### ISSUE THREAD

**Issue by teddychan** [outline/outline#1174]
Test on: https://www.getoutline.com/

Test case: test bug username_suffix work

![image](https://user-images.githubusercontent.com/1013507/74295868-342f7e80-4d7d-11ea-8770-fe6c05763d1d.png)

Generate URL
```
https://www.getoutline.com/doc/test-bug-username_suffix-work-MUKfXQsuFH
```

Result:
![image](https://user-images.githubusercontent.com/1013507/74295834-19f5a080-4d7d-11ea-92db-afcd403401e3.png)

A workaround, click ink, from left menu, it works.
But the link are the same... if direct access, not work.

```
https://www.getoutline.com/doc/test-bug-username_suffix-work-MUKfXQsuFH
```

**Comment by tommoor** [comment]
Thanks for the report 🙏
