### ISSUE TITLE
signin with local email and password -features

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [outline/outline#1179]
Hi @tommoor 

Currently outline is best performance Thank you 
but i think 

There are best way for use localization sign-in with local email and password 
but currently found login with email and slack so 
can it possible here ?

Thank you

**Comment by tommoor** [comment]
Hi, we're evaluating more sign-in options  – but do not plan to support individual email/password signin at this time. Are there any other services that your team uses to signin?

**Comment by fareszr** [comment]
this is a huge drop back for outline, i like the project, and i want to self host it.
but i care about my privacy(the reason to use outline in the first place) and using google and slack is not an option.

**Comment by MatheusRV** [comment]
> this is a huge drop back for outline, i like the project, and i want to self host it.
> but i care about my privacy(the reason to use outline in the first place) and using google and slack is not an option.

help us with https://github.com/outline/outline/pull/1183
