### ISSUE TITLE
Empty dashboard after sign with google on v0.40.0  bundle.js not found

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [outline/outline#1181]
Hi @tommoor 

There are good feature 
There are not showing dashboard after google login on ```v0.40.0``` outline 

I have following all steps from documentation 
I have all configuration setup then migration run , next before run yarn build:webpack

Error is static/bundle.js file not found after login
```http://localhost:3000/static/bundle.js```

Following error got on console after login 
![1](https://user-images.githubusercontent.com/35251001/75088934-86d91980-5579-11ea-9d6e-95a96b298ceb.png)

I don't know is it error or missing new some configuration on outline ?

Thank you

**Comment by tommoor** [comment]
Seems likely that the javascript bundle has failed to build. What is the contents of that file `bundle.js` ?

**Comment by rajesh-smartwebtech** [comment]
hi @tommoor 
empty file display on url new tab open ```bundle.js```

**Comment by tommoor** [comment]
Sounds like the bundle didn’t compile yea, double check you followed all
the installation steps in Readme and there are no errors.

**Comment by rajesh-smartwebtech** [comment]
Hi @tommoor 

I have following all steps for install and run

Note : There are no any error on old version on same step but only new version issue facing  

Same issue 
![image](https://user-images.githubusercontent.com/35251001/75087125-8d0fcb80-5562-11ea-8a06-88079663dda8.png)

There are successfully run this command ```yarn build:webpack``` after env file set 
but same result got after login all is blank 

So here i am trying some js injection for help to find  identification of  problem

1. Check on outline root folder here ```dist``` contains some ``bundle.XXX.js``` js files

![image](https://user-images.githubusercontent.com/35251001/75087203-42db1a00-5563-11ea-8b94-e151375a2015.png)

![image](https://user-images.githubusercontent.com/35251001/75087224-82a20180-5563-11ea-978b-36ae8aaa4b33.png)

2. I am copy the large file of bundle ```bundle.XXX.js``` that size is 2 mb
Then copy all js code 
and paste on console and press enter

3. After this step outline desktop show 
so i think it is some issue of mapping file or else
because ```yarn build ``` command create all file for build 
but runtime not found content of ```bundle.js```

![image](https://user-images.githubusercontent.com/35251001/75087269-268bad00-5564-11ea-8e36-8479e54bc07d.png)


![image](https://user-images.githubusercontent.com/35251001/75087284-5935a580-5564-11ea-95ef-fa698cc2e6ac.png)


I think you better understand me 

Thank you

**Comment by tommoor** [comment]
Because the bundle has a hash it means it was built for production, which is good – but it's attempting to load a bundle without a hash which means you're running in development? 

I've never seen this before. You're using `yarn start` to run the app?

Unfortunately I can't provide individual support to everyone that hosts the code themselves, this is why we offer a hosted version.

**Comment by rajesh-smartwebtech** [comment]
Hello @tommoor 
Thank you 

I also try ```yarn start``` same result

**Comment by AndreasWidmer** [comment]
Same here. If you try to start via yarn start in docker-compose, this happens

**Comment by Zmeu213** [comment]
Got same issue. It looks like server send something else instead of js code in bundle 
![image](https://user-images.githubusercontent.com/8945959/87158884-197c1a00-c2c9-11ea-810f-3343348a26cc.png)

**Comment by Zmeu213** [comment]
look like my problem was that `NODE_ENV` wasnt set to `production`
