### ISSUE TITLE
Are rich previews supported on a shared link when viewed on another device?

### ISSUE THREAD

**Issue by shankscoder** [outline/outline#1182]
So, I'm a not sure if this is a bug or a feature request.

My question is whether rich embeds are supposed to be rendered when viewing a shared link as a guest from another browser/system (ie not logged in)?

From what I've read in some of the older issues, it seems like the previews should be viewable even in shared links for other devices. 

However for a doc I've shared to verify this, the previews work when I'm logged in, but on shared links they're not visible.

Here's the share link I'm testing with btw: https://www.getoutline.com/share/6dcb6c33-f16b-432b-9f49-382a9a1ca10f

Can someone clarify what is the expected behaviour here? If it isn't by supposed to show previews, could this be added as a feature request?

It would allow for shared pages to be on par with Notion's shared pages capabilities in terms of utility.

Great work so far btw.

**Comment by tommoor** [comment]
This seems to be a bug, thanks for reporting. I'll get it fixed up.
