### ISSUE TITLE
Private Collections menu not populated when created. Needs refresh to show menu items

### ISSUE THREAD

**Issue by shankscoder** [outline/outline#1185]
Ok, so when creating a private collection, the menu on the sidebar doesn't populate with options to edit/delete etc.

This is what shows up immediately after creating a private collection:
![Screenshot 2020-02-24 at 11 04 07 PM](https://user-images.githubusercontent.com/1317569/75176640-8a77c680-575a-11ea-84c3-4d03112b122f.jpg)

If you refresh the browser, the menu is populated, as below:
![Screenshot 2020-02-24 at 11 05 03 PM](https://user-images.githubusercontent.com/1317569/75176659-94012e80-575a-11ea-8d42-6230c59d3e83.jpg)

I suspect there's a state issue that isn't being triggered for private collections. Looks ok for public collections, as shown below:

![Screenshot 2020-02-24 at 11 07 19 PM](https://user-images.githubusercontent.com/1317569/75176685-9e232d00-575a-11ea-9b3a-a406939c2532.jpg)

I've verified this happens on both the hosted version, and the current self-hosted version.

**Comment by tommoor** [comment]
Thanks for reporting, now fixed on `master` and getoutline.com
