### ISSUE TITLE
Add total user count to people management screen

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1186]
It's useful to know. This request came through support.

**Comment by mo-jinbuu** [comment]
Hey @tommoor is this still available? I'd like to implement this if possible.

**Comment by thenanyu** [comment]
this looks to still be needed @mo-jinbuu — design is a bit of a question, I would say, start by adding counts to the `active` `admins` and `invited` tabs on the people management screen

**Comment by mo-jinbuu** [comment]
Alright I'll get on it, I'll let you know if I need anything
