### ISSUE TITLE
Rich previews suggestions: oEmbed support, and option to view original embed link in editor

### ISSUE THREAD

**Issue by shankscoder** [outline/outline#1187]
So I have two enhancement suggestions for the rich preview capabilities in Outline:

**1. oEmbed Support**
I was wondering if it would be useful to support rich previews of any link that contains oEmbed tags. It would help increase the number of preview/embeds that could be supported in Outline, without having to manually add support for each media/embed source.

**2. Allow editor to see the original link that is used to generate rich preview in edit mode**
I was playing around with embed previews, and when I went to edit a doc I'd created earlier, I realized I didn't have a way to view/edit/copy the original embed URL/link. IMO there should be a mechanism to do copy/edit the link. Especially copy would be useful if I wanted to reuse a link in multiple documents, and wanted to copy between documents (without cloning/duplicating the entire document)

**Comment by tommoor** [comment]
Hey Ashwin, these are both good suggestions – the editor itself is in some flux at the moment as we're moving it to a new framework, once that's settled these improvements should be easier to make.
