### ISSUE TITLE
Need a way to view current code version in UI

### ISSUE THREAD

**Issue by shankscoder** [outline/outline#1195]
While I noticed the /changelog link was removed in the OSS version, the menu is still visible and pointing to a `/changelog` link that's showing a `notfound` message. 

Might be good to either link to the public changelog, or removing the link (TBH would recommend the former).

Also, might be useful to have a way to view the current running version of the code in the UI. I know this was mentioned in an earlier issue, but I didn't find an update on whether this was resolved or not, so raising to check on this again.

Happy to help contribute a PR for both, based on arrived consensus.

**Comment by tommoor** [comment]
Hey, I just fixed the link location – if you'd like to PR something for the second point you had I'd be very open to it.

**Comment by tommoor** [comment]
Closed by https://github.com/outline/outline/commit/64c3ff8d6b81d976ca62b687dd908157a834b29f

Will be in the next release.
