### ISSUE TITLE
504 Gateway Timeout / ETIMEDOUT 

### ISSUE THREAD

**Issue by AndreasWidmer** [outline/outline#1196]
I'm trying to get outline running, but I have no idea what the problem could be. I'm running all dockerized, with an nginx proxy in front. I tried many things, but I keep getting the following error, if I should get redirected from Google to the app. Even with exposing the app to 0.0.0.0 and trying to connect directly, gives the same error.

Do you have any idea what the problem could be? Thanks in advanced!

> outline_1   |   --> GET / 200 57ms 14.63kb
outline_1   |   <-- GET /auth/google
outline_1   |   --> GET /auth/google 302 5ms 817b
outline_1   |   <-- GET /auth/google.callback?code=4/xAFwgUbWyyxXAWjLvFqF9uHEKz15iDxpm_SRoQ7m4d6igdBTO0OucUvoVW6Fr-rAjcoioRHuANXXXXXXXX&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=0&hd=XXXXXX&prompt=consent
outline_1   | Error: connect ETIMEDOUT 169.254.169.254:80
outline_1   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
outline_1   |   message: 'Missing credentials in config',
outline_1   |   errno: 'ETIMEDOUT',
outline_1   |   code: 'CredentialsError',
outline_1   |   syscall: 'connect',
outline_1   |   address: '169.254.169.254',
outline_1   |   port: 80,
outline_1   |   time: 2020-02-29T21:55:05.636Z,
outline_1   |   originalError: {
outline_1   |     message: 'Could not load credentials from any providers',
outline_1   |     errno: 'ETIMEDOUT',
outline_1   |     code: 'CredentialsError',
outline_1   |     syscall: 'connect',
outline_1   |     address: '169.254.169.254',
outline_1   |     port: 80,
outline_1   |     time: 2020-02-29T21:55:05.636Z,
outline_1   |     originalError: {
outline_1   |       errno: 'ETIMEDOUT',
outline_1   |       code: 'ETIMEDOUT',
outline_1   |       syscall: 'connect',
outline_1   |       address: '169.254.169.254',
outline_1   |       port: 80,
outline_1   |       message: 'connect ETIMEDOUT 169.254.169.254:80'
outline_1   |     }
outline_1   |   }
outline_1   | }
outline_1   | Error: connect ETIMEDOUT 169.254.169.254:80
outline_1   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
outline_1   |   message: 'Missing credentials in config',
outline_1   |   errno: 'ETIMEDOUT',
outline_1   |   code: 'CredentialsError',
outline_1   |   syscall: 'connect',
outline_1   |   address: '169.254.169.254',
outline_1   |   port: 80,
outline_1   |   time: 2020-02-29T21:55:37.122Z,
outline_1   |   originalError: {
outline_1   |     message: 'Could not load credentials from any providers',
outline_1   |     errno: 'ETIMEDOUT',
outline_1   |     code: 'CredentialsError',
outline_1   |     syscall: 'connect',
outline_1   |     address: '169.254.169.254',
outline_1   |     port: 80,
outline_1   |     time: 2020-02-29T21:55:37.122Z,
outline_1   |     originalError: {
outline_1   |       errno: 'ETIMEDOUT',
outline_1   |       code: 'ETIMEDOUT',
outline_1   |       syscall: 'connect',
outline_1   |       address: '169.254.169.254',
outline_1   |       port: 80,
outline_1   |       message: 'connect ETIMEDOUT 169.254.169.254:80'
outline_1   |     }
outline_1   |   }
outline_1   | }
outline_1   | Error: connect ETIMEDOUT 169.254.169.254:80
outline_1   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
outline_1   |   message: 'Missing credentials in config',
outline_1   |   errno: 'ETIMEDOUT',
outline_1   |   code: 'CredentialsError',
outline_1   |   syscall: 'connect',
outline_1   |   address: '169.254.169.254',
outline_1   |   port: 80,
outline_1   |   time: 2020-02-29T21:56:09.375Z,
outline_1   |   originalError: {
outline_1   |     message: 'Could not load credentials from any providers',
outline_1   |     errno: 'ETIMEDOUT',
outline_1   |     code: 'CredentialsError',
outline_1   |     syscall: 'connect',
outline_1   |     address: '169.254.169.254',
outline_1   |     port: 80,
outline_1   |     time: 2020-02-29T21:56:09.375Z,
outline_1   |     originalError: {
outline_1   |       errno: 'ETIMEDOUT',
outline_1   |       code: 'ETIMEDOUT',
outline_1   |       syscall: 'connect',
outline_1   |       address: '169.254.169.254',
outline_1   |       port: 80,
outline_1   |       message: 'connect ETIMEDOUT 169.254.169.254:80'
outline_1   |     }
outline_1   |   }
outline_1   | }

**Comment by tommoor** [comment]
It looks like the error is thrown from the AWS SDK, did you correctly set the AWS credentials?

**Comment by AndreasWidmer** [comment]
Perfect, thanks.
Problem was the config for the fakeS3.

**Comment by PHPadawan** [comment]
@AndreasWidmer same issue for me, im also using minio for the storage. Can you tell me witch change in the config did the trick for you?
