### ISSUE TITLE
Embedding code snippets in tables throws the formatting to the wind when publishing

### ISSUE THREAD

**Issue by mylogon341** [outline/outline#1198]
It starts off fine during editing, but when you publish something it just turns to mush like this

https://imgur.com/a/WHRizFC

to recreate, create a table then do the triple tick to format the code ( I think i selected python, if that matters). When you publish, observe.

**Comment by tommoor** [comment]
Thanks, there is a bug here in that you shouldn't be able to insert code blocks inside of a table – how did you do that? Try using inline code (a single backtick) to achieve what you're after.

**Comment by mylogon341** [comment]
I literally just typed out the 3 backticks and the cell formatted like it would outside the table.

**Comment by tommoor** [comment]
Gotcha, yea the block-level markdown shortcuts should be disabled in this situation. Working on rebuilding tables at the minute so will make sure this is tackled one way or another.

**Comment by mylogon341** [comment]
Video attached here, in case it's useful. https://drive.google.com/file/d/1nRVq0XMsL_i67QXmOuaeWII4tAHexB5d/view?usp=sharing
I don't know if it's normal, but i can't get the usual single backtick to work - i usually have to select the text and use the tooltip.
Not a massive dealbreaker, just thought i'd bring it up :)
thanks

**Comment by tommoor** [comment]
It's no longer possible for this bug to happen, addressed as part of https://github.com/outline/outline/pull/1227
