### ISSUE TITLE
Documentation for slack slash command setup on self hosted version of Outline

### ISSUE THREAD

**Issue by maryolivier** [outline/outline#1199]
## Description
Setting up a self hosted version of outline is pretty straightforward. Setting up the accompanying slack app, however, is not. There seems to be some distributed information throughout issues, but no one source.

**Comment by tommoor** [comment]
I wrote up a rough guide here last week, let me know if that helps:
https://www.getoutline.com/share/be25efd1-b3ef-4450-b8e5-c4a4fc11e02a

**Comment by bryanjos** [comment]
Hey @tommoor we got it working! The problem we had was that somehow we ended up with 2 entries in the teams table. One from google and one from slack. I moved the slackId from the slack one to the google one and things seem to be working as expected now

**Comment by bryanjos** [comment]
One more question (that can maybe be cleared up in documentation), can you only have google oauth turned on and still use the slack integration? Are there specific slack environment variables we should set to turn on just the integration without turning on slack oauth?

**Comment by tommoor** [comment]
> Are there specific slack environment variables we should set to turn on just the integration without turning on slack oauth?

You can use Google Auth with the Slack integration but there isn't currently a way to disable the authentication on the homepage but retain the slash command integration – they are both enabled by the existence of the environment variables.

**Comment by bryanjos** [comment]
Thanks for the info. Would that be something you would be interested in a PR to alter? For instance, I think the `SLACK_VERIFICATION_TOKEN` and `SLACK_APP_ID` are what's needed for the integration and `SLACK_KEY` and `SLACK_SECRET` can be used to see if slack authentication should be turned on.

**Comment by maryolivier** [comment]
@tommoor yes that helped us as @bryanjos said! documentation should also include the redirect URLs needed, bot token scopes, and user token scopes

**Comment by enzolutions** [comment]
Hi @maryolivier && @tommoor for this guide

I think I did the integration using my self-hosted outline running in Heroku, and all looks connected as you can see in the following image.
<img width="776" alt="Screen Shot 2020-03-20 at 5 34 48 pm" src="https://user-images.githubusercontent.com/907914/77141629-b116ec00-6ad1-11ea-8308-fe5cd82d3d34.png">

One collection is private, but both post without problems in the designated channels in Slack.

I created a command `/handbook` instead `/outline`, but when I tried to search I got the following "error".

<img width="710" alt="Screen Shot 2020-03-20 at 5 34 37 pm" src="https://user-images.githubusercontent.com/907914/77141716-f5a28780-6ad1-11ea-872d-59d9ca0a2675.png">

Any ideas what configuration could be missing?

Thanks in advance.

**Comment by tommoor** [comment]
This error message means that the Slack team you are running the command from does not exist in your Outline installation.

**Comment by enzolutions** [comment]
Hi @tommoor thanks for your response.

Where should I check that, because in my self-hosted installation all looks connected [see image](https://user-images.githubusercontent.com/907914/77141629-b116ec00-6ad1-11ea-8308-fe5cd82d3d34.png).

Thanks in advance for your help

**Comment by tommoor** [comment]
You can compare your slack teamId (in the url when you access slack on web) against the slackId stored in your database to be sure

**Comment by enzolutions** [comment]
H @tommoor thanks for your help.

I have slack team id working at `expl.slack.com`, I just change the real one for example.

After check in the databse I got this.

```sql
handbook::DATABASE=> select * from teams;                                                                                         -[ RECORD 1 ]--+----------------------------------------
id             | 02dfbc62-b13c-4d78-8ddf-f5dd2993dc32
name           | Example
slackId        |
slackData      |
createdAt      | 2020-01-27 19:17:14.555+00
updatedAt      | 2020-03-19 20:56:57.01+00
googleId       | example.com
avatarUrl      | https://logo.clearbit.com/example.com
deletedAt      |
sharing        | f
subdomain      | example
documentEmbeds | t
guestSignin    | f
``` 

As you can see `slackId` is empty, so I run and SQL update and now the slack subdomain `expl` is in the table teams.

```sql
handbook::DATABASE=> select * from teams;                                                                                         -[ RECORD 1 ]--+----------------------------------------
id             | 02dfbc62-b13c-4d78-8ddf-f5dd2993dc32
name           | Example
slackId        | expl
slackData      |
createdAt      | 2020-01-27 19:17:14.555+00
updatedAt      | 2020-03-19 20:56:57.01+00
googleId       | example.com
avatarUrl      | https://logo.clearbit.com/example.com
deletedAt      |
sharing        | f
subdomain      | example
documentEmbeds | t
guestSignin    | f
```

But still got the same error, maybe there a cache or something that should I refresh or anything similar.

Or maybe something in my app? 

Thanks for your support.

**Comment by tommoor** [comment]
The slackId is not the subdomain, it's a database ID that begins with "T", eg in this url it's the part after "client/":

![image](https://user-images.githubusercontent.com/380914/77240700-0e7c6d00-6ba6-11ea-95bb-9caf9cb6d71b.png)

**Comment by enzolutions** [comment]
Hi @tommoor 

That does the magic, now I got a different error, so it's a progress :P
<img width="423" alt="slack-bot" src="https://user-images.githubusercontent.com/907914/77244707-7f865800-6c6c-11ea-81ec-485619e0c885.png">

Checking the log of my Heroku error, I got the following error.

```log
2020-03-22T07:36:44.419710+00:00 heroku[router]: at=info method=POST path="/api/hooks.slack" host=handbook.weknowinc.com request_id=f55add5e-26f8-4146-ab82-bdb65ec40a39 fwd="18.209.13.251" dyno=web.1 connect=1ms service=28ms status=500 bytes=262 protocol=https
2020-03-22T07:36:44.419909+00:00 app[web.1]:
2020-03-22T07:36:44.420021+00:00 app[web.1]: SequelizeDatabaseError: syntax error at or near ")"
2020-03-22T07:36:44.420023+00:00 app[web.1]: at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
2020-03-22T07:36:44.420023+00:00 app[web.1]: at /app/node_modules/sequelize/lib/dialects/postgres/query.js:72:18
2020-03-22T07:36:44.420024+00:00 app[web.1]: at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2020-03-22T07:36:44.420024+00:00 app[web.1]: at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
2020-03-22T07:36:44.420025+00:00 app[web.1]: at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
2020-03-22T07:36:44.420025+00:00 app[web.1]: at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
2020-03-22T07:36:44.420026+00:00 app[web.1]: at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:725:18)
2020-03-22T07:36:44.420026+00:00 app[web.1]: at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
2020-03-22T07:36:44.420027+00:00 app[web.1]: at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
2020-03-22T07:36:44.420027+00:00 app[web.1]: at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
2020-03-22T07:36:44.420027+00:00 app[web.1]: at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
2020-03-22T07:36:44.420028+00:00 app[web.1]: at processImmediate (internal/timers.js:456:21)
2020-03-22T07:36:44.420028+00:00 app[web.1]: at process.topLevelDomainCallback (domain.js:137:15)
2020-03-22T07:36:44.420080+00:00 app[web.1]:
```

I would appreciate any other guidance in term how to debug that error, or maybe a related issue.

Thanks for your contributions to the Open Source community.

**Comment by tommoor** [comment]
Unclear, If I had to guess the user / team doesn't have any collections.

**Comment by enzolutions** [comment]
Thanks for your help.

they have, but I will try to debug in my side.

**Comment by enzolutions** [comment]
Hi @tommoor 

I found the source of the problem. Inside the file  https://github.com/outline/outline/blob/master/server/api/hooks.js#L138 there is the following code.

```
  const user = await User.findOne({
    where: {
      teamId: team.id,
      service: 'slack',
      serviceId: user_id,
    },
  });
```

The team id is my database, but all my users sign in use `google` as service and the user_id send from slack looks like slack format `UTQ10RU3W` my records looks like `106629815691052806096`.

So my theory is because the users get login with google account and not with slack, they cannot search from Slack, could you confirm this theory, please.

I am trying to check why I cannot logging with slack in my self-hosted application.

**Comment by enzolutions** [comment]
I tried replacing the code with

```
  const user = ctx.state.user;
``` 

As was listed in PR https://github.com/outline/outline/pull/734/files#diff-0e6bed6356243da8195ed70411f59894R92 , but doesn't work

**Comment by tommoor** [comment]
@enzolutions the user query isn't the issue, it's designed to allow no result to be returned from that query for exactly your usecase of Google signed in users querying from within Slack, they just get less specific search results:

https://github.com/outline/outline/blob/master/server/api/hooks.js#L149

**Comment by enzolutions** [comment]
:'( then is other thing. thank you for your support

**Comment by jslopez** [comment]
> @tommoor yes, thank you, that helped us as @bryanjos said! documentation should also include the redirect URLs needed, bot token scopes, and user token scopes

Hi, I followed the guide shared by @tommoor, but I'm still not able to use the slash command.

@maryolivier any chance you can you share the redirect URLs and scopes that worked for you?

**Comment by jlb-qi** [comment]
hi @tommoor a bit of an extension to this question but i'm getting a `dispatch_unknown_error` when attempting to execute the slack search command. 

I tried a few things such as;

- changing the `SLACK_VERIFICATION_TOKEN` in the .env file with;

1. Verification Token (Basic Information page)
2. Signing Secret (Basic Information page)
3. OAuth Access Token (OAuth & Permissions page)
4. Bot User OAuth Access Token (OAuth & Permissions page)

- Also, `http://localhost:3000/auth/slack.commands` is added to the Redirect URIs list.

- The `commands` scope has been added the to the Bot Token Scopes but does not appear in the drop down for the User Token scopes. See image.

![image](https://user-images.githubusercontent.com/14451186/90402714-24805200-e0a0-11ea-8af5-6ee71bf3de25.png)

- I tried replacing the APP_ID with the `slack_route` that appears in the Request URL of the chat.command but that doesn't really make sense so I switched back to App ID found in Basic Information. 

So the configuration that seems to make the most sense is;

```
SLACK_VERIFICATION_TOKEN=`Bot User OAuth Access Token`
SLACK_APP_ID=`App ID (Basic Information)`
```

But i'm consistently getting the `dispatch_unknown_error`. I'm sure it's something pretty straight forward that I'm missing but I can't see it. Any nudge in the right direction would be appreciated.

**Comment by tommoor** [comment]
`SLACK_VERIFICATION_TOKEN` is the "Verification Token".  It's possible it doesn't work with the Bot User stuff, the production app hasn't been migrated to their new permissions setup yet, but other OSS _have_ set it up fairly recently.

**Comment by kcrazy** [comment]
hi @tommoor a bit of an extension to this question but i'm getting a dispatch_failed when attempting to execute the slack search command.
```
/outline failed with the error "dispatch_failed"
```
my version is tag: v0.47.1

I saw some logs and I don’t know if they are useful
```
koa-mount mount /auth unnamed -> false +39s
koa-mount mount /api unnamed -> /hooks.slack +0ms
koa-mount enter /api/hooks.slack -> /hooks.slack +1ms
```
my oauth setting is:
![image](https://user-images.githubusercontent.com/1505797/93660377-cb318700-fa80-11ea-9596-147c03064688.png)
