### ISSUE TITLE
Fonts, Diagrams and LaTeX

### ISSUE THREAD

**Issue by BackOrder** [outline/outline#1200]
Hi people!

Here are few questions because I haven't found any documentation for Outline besides API doc. 

How would it be possible to access more fonts and font colours?

Is there any diagram integration? google drawings, graphviz, svg, etc.

Is there any support for maths? LaTeX and such.

**Comment by BackOrder** [comment]
Oh, I'm forgetting, is there any TODO list support? Something that might parse TODOs on a page and report them on a TODO page.

**Comment by tommoor** [comment]
Hi @BackOrder – thanks for the question, none of these features exist today but let me add some more thoughts:

> How would it be possible to access more fonts and font colours?
We're probably not going new fonts but colors and other treatments are on the cards to be able to call out certain areas of information – is this your usecase?

> Is there any diagram integration? google drawings, graphviz, svg, etc.
Nothing yet but there is a pretty easy to use integration format for adding new embeds that should work well with any third-party hosted page such as google drawings. See the examples in [this directory](https://github.com/outline/outline/tree/master/app/embeds).

> Is there any support for maths? LaTeX and such.
We're currently re-writing the editor, LaTeX will be an easy addition once that's complete within the next month.

> Is there any TODO list support
You can add checkboxes to a document but these don't bubble up to a central TODO list

**Comment by BackOrder** [comment]
> We're probably not going new fonts but colors and other treatments are on the cards to be able to call out certain areas of information – is this your usecase?

It would be acceptable. There is no need to be fancy but simply a bit more flexibility. Sometimes, you just got to put a huge warning sign in red, right? :)

> Nothing yet but there is a pretty easy to use integration format for adding new embeds that should work well with any third-party hosted page such as google drawings. See the examples in this directory.

The API is lean and simple, examples are pretty good. Is any of these examples allow editing within Outline? Also, is it possible to create templates for newly created pages?

> We're currently re-writing the editor, LaTeX will be an easy addition once that's complete within the next month.

Fantastic! Will it be possible to write LaTeX directly in Outline and the rendering will be done once the document is saved?

> You can add checkboxes to a document but these don't bubble up to a central TODO list

Checkboxes are just not the same. WikidPad has an interesting approach that might interest you, [SignalTodoTags](http://wikidpad.sourceforge.net/help/SignalTodoTags.html). The views are particularly interesting because you can create groups that will be displayed in the views, such as, `project.outline.reminder: release outline next month (April)`.

**Comment by tommoor** [comment]
Cleanup, combining with #1038
