### ISSUE TITLE
"Sign-in with your email address" not showing up (guest feature)

### ISSUE THREAD

**Issue by jsoranzo** [outline/outline#1203]
Hello Outline team and thx for the great wiki.
We're running a self-hosted version of Outline, served via node12 + pm2 and SSL proxied via apache. Our instance is configured with Google auth and restricted to a few specific google domains (via GOOGLE_ALLOWED_DOMAINS).
I've been testing the "invite as guest" feature: the option is enabled in the Security settings, email invitations are sent correctly with the sign-in link like "mywikicustom.domain/?guest=true". However this page on our instance only shows the "Sign-in with Google" button, no option to sign-in with email address. Are we missing something? Thanks in advance for your help

**Comment by tommoor** [comment]
Hey @jsoranzo – you're not missing anything – currently the UI for allowing email signins only exists on the subdomain login page, it hasn't really been optimized for the self-hosting case yet.

So I think this issue can cover that. It should show on the main homepage when self hosted.

**Comment by jsoranzo** [comment]
@tommoor alright, thanks for the feedback
indeed, having this feature also enabled for the self-hosted env would be awesome
cheers

**Comment by grv231** [comment]
Ran into the same issue today while trying to explore the guest feature in self-hosted version. Didnt knew this was enabled only for the paid version

**Comment by tommoor** [comment]
It's not that it's specifically enabled for the paid version, the feature is dependent on the team setting being enabled so it only shows up on the team subdomain for that reason. 

I think we really need to rethink the self hosted option to be a single-team option which would make things like this easier to port to self-hosted.

**Comment by wfpaisa** [comment]
Hello @tommoor, Outline is beautiful.
@jsoranzo you can put this in the home for create a guest users. (the guest  need to have been invited first)

```html
<form method="POST" action="/auth/email">
  <input type="email" name="email" placeholder="mail@domain.com"> 
  <button type="submit">Sign In</button>
</form>
```

**Comment by jsoranzo** [comment]
Hello everyone
May I ask for this issue to be re-opened?
Previously, we manually added the above form as suggested by @wfpaisa, which worked nicely.

Then, and since it was marked as merged and available via the latest release 0.45.0, we upgraded our instance.
Yet, the "sign-in with email" button/option remains invisible for our self-hosted setup (as shown in the screenshot below). Email authentication is already enabled via Settings > Security.
Please let me know if you need further info from our side. Thanks!

![image](https://user-images.githubusercontent.com/4113305/89384750-c1e69800-d728-11ea-8f8c-e212e0761646.png)

**Comment by tommoor** [comment]
@jsoranzo do you have more than one team in the database? Make sure there is only a single team on your self hosted instance as it uses the settings from the first time to determine if guest auth should display.

**Comment by jsoranzo** [comment]
Hello @tommoor and thx for your reply.
We've got 3 teams in total: the main one (in use) plus 2 others that are results of previous tests but not being used.
Any tip on how to get rid of them? We're using pgsql and I can't just remove them from the db, as I'm hitting an errors such as "update or delete on table "teams" violates foreign key constraint "events_teamId_fkey" on table "events"".
Cheers

**Comment by jsoranzo** [comment]
@tommoor I cleaned up the database manually and can confirm the single team fix.
The "Continue with Email" button now appears on the login page.
Thanks for the quick support, Outline is great!
