### ISSUE TITLE
Usage of "Open Source" in marketing materials

### ISSUE THREAD

**Issue by Hummer12007** [outline/outline#1205]
After re-licensing to BSL v.1.1 the repository description as well as [getoutline.com](https://getoutline.com) still describe Outline as open-source, which is no longer true, as BSL v1.1 is not an Open Source license.

In addition, README still mentions the old BSD license.

**Comment by tommoor** [comment]
Thanks, closed by 6c451a34d4f483fc744ed61ee525ad9043abdbfa – the getoutline.com website is not covered by this repository.

**Comment by Hummer12007** [comment]
Thanks! Do I need to file an issues against the website somewhere?

**Comment by ryanprior** [comment]
@tommoor I was checking in on Outline today (thinking about deploying it for an upcoming project!) and noticed the new license. You should update your website! The BSL restricts field of endeavor, which contradicts the open source definition (https://opensource.org/osd#fields-of-endeavor)

Thank you!
