### ISSUE TITLE
Document concurrency is flaky and causing issues

### ISSUE THREAD

**Issue by shankscoder** [outline/outline#1213]
So, we're facing an issue with basically merge conflicts, when more than one person tries to work on the same document.

Even if a person saves the document, and the other person refreshes the browser and only then starts editing, often times the latest edits aren't being retrieved. This especially happens if you try and edit a doc within a minute or two of its last save.

We've just had an exercise where we had to edit the same doc around 5 times and essentially had one person at a time to ensure we had a final consistent copy.

I'd suggest allowing for this behavior to help address this:
- Lock down the doc consistently when someone else is editing (literally document level locking)

**Comment by tommoor** [comment]
@shankscoder are you self hosting or using getoutline.com ? We've not experienced issues like this typically, I'd want to check into regressions.

If self hosting are websockets enabled? That's key to keeping documents in sync and minimizing issues like this.

**Comment by shankscoder** [comment]
Self-hosted with websockets enabled in the .env file.

My webserver (Caddy) is setup for proxying websockets, and I can confirm this works with other websockets support node applications.

I'm seeing the socket being initialized on the browser, but it's constantly in a pending state, and looks like its failing back to XHR.

I've turned off all ad-blockers for my outline URL as well and checked.

**Comment by shankscoder** [comment]
I'm closing this for now, as I just updated versions and I'm not seeing this issue at the moment. If it happens again will re-open at that time.

**Comment by JustDoItSascha** [comment]
I think it should reopened, I'm seeing this issue as well. Websockets also activated and working. I think the problem is especially when the laptop is at sleeping mode, I open it and I am already at an outline page. If I start typing then I overwrite a newer version on the server.
