### ISSUE TITLE
ERR_EMPTY_RESPONSE when SUBDOMAINS_ENABLED = true

### ISSUE THREAD

**Issue by mzch** [outline/outline#1215]
When SUBDOMAINS_ENABLED = true, created subdomain responds no data.
Chome says, "ERR_EMPTY_RESPONSE". Any idea?

<img width="1623" alt="Shot006" src="https://user-images.githubusercontent.com/621178/77233449-c6336e00-6bea-11ea-82b4-4bab935be8f5.png">

**Comment by tommoor** [comment]
No ideas, it will be totally down to the configuration of your servers. I would not recommend running with subdomains enabled when self-hosting.

**Comment by mzch** [comment]
Well, I disable SUBDOMAINS_ENABLED now and Outline works very well. If it can be enabled, that's even better for me...

**Comment by tommoor** [comment]
Hi @mzch – I'm also noting that you are using the domain name "outlineup.com", this is a breach of the [licensing agreement](https://github.com/outline/outline/blob/master/LICENSE) and could easily be confused with the official domain.

I'd ask kindly that you rename the domain name your installation is hosted at, or make it inaccessible to the public internet.

**Comment by mzch** [comment]
OK... could you come up with another good domain name...?

**Comment by tommoor** [comment]
Most folks that self host either do it on an internal network or a subdomain of their corporate domain, eg wiki.mycompany.com. Hope this is useful!
