### ISSUE TITLE
Escape characters aren't being removed in the new TOC

### ISSUE THREAD

**Issue by shankscoder** [outline/outline#1226]
Just updated to the latest version on a self-hosted setup: v. 0.42.1

When using special characters for section headings in a document, the TOC display doesn't seem to remove the escape characters used to sanitize input.

Examples here:
Example 1:
![Screenshot 2020-04-06 at 1 54 37 PM](https://user-images.githubusercontent.com/1317569/78538438-9d2bf380-780e-11ea-8b83-56887c1f8c30.jpg)

Example 2:
![Screenshot 2020-04-06 at 1 55 07 PM](https://user-images.githubusercontent.com/1317569/78538468-aae17900-780e-11ea-8d3f-b45ba528beb2.jpg)

Seeing this in both old and new documents.

**Comment by tommoor** [comment]
Thanks for the report! Now fixed, will deploy to `getoutline.com` within the hour.
