### ISSUE TITLE
Could not load image

### ISSUE THREAD

**Issue by vinayak-at-vernacular** [outline/outline#1228]
I am getting a "could not load image" when I upload an image in a document
![Screenshot 2020-04-09 at 2 50 47 PM](https://user-images.githubusercontent.com/62427886/78881139-03658000-7a74-11ea-925b-03411e5e88d0.png)
.
Any help would be appreciated.

**Comment by tommoor** [comment]
- Self hosted or hosted?
- Any errors in the console?
- Any network errors?

**Comment by vinayak-at-vernacular** [comment]
Yes it is self-hosted. I do not manage the hosting. I'll reach out to the system administrator to know more on the console/network errors.
