### ISSUE TITLE
Idea: Make backlinks for linked docs traversable even in shared/public mode

### ISSUE THREAD

**Issue by shankscoder** [outline/outline#1231]
So, this is a feature request.

When I publish/share a doc (Doc1) publicly in Outline, if Doc1 has a link to another Outline doc (Doc2), for the link to Doc2 to be available in the public view of Doc1, 2 things need to happen:
1. Doc2 also has to be shared (a public URL must be generated)
2. The link to Doc2 in Doc1 has to point to the shared/public URL of Doc2 (not using Outline's internal linking methodology)

There's an issue with the 2nd action, as when I'm viewing Doc1 within Outline, the link to Doc2 still takes me to the public URL of Doc2 (not the internal link), which as a result takes me out of the Outline environment.

I think the behavior should respect the user context and navigate the appropriate version based on whether the user is viewing from inside Outline or not. 

I think this can be done by  having links resolved via an API call that returns the correct link based on user context. Combine this with an alert when a user intends to share a doc, informing them that even linked docs will be publicly visible if the current doc is shared, to maintain accessibility.

This way the user is reminded of the ramifications of publishing, and can choose actively on whether to publish a set of resources or not.

IMO, these features would bring Outline's sharing capabilities more on par with Notion in how useful/flexible they can be.

Curious to know if this is something that would be useful for other Outline users.

**Comment by tommoor** [comment]
I think resolving the share link as part of the click handler and redirecting the user internally when appropriate would be a good improvement, yep!
