### ISSUE TITLE
[feature request] Collection Document/Page

### ISSUE THREAD

**Issue by defunctzombie** [outline/outline#1232]
Rather than showing a list of documents within a collection, I'd like to create a curated "landing" page for the collection with similar capabilities to a regular document. This page would be shown when the user clicks on the collection name from the sidebar and has not yet selected a document. The page could still include a collection search and a TOC on the side.

**Comment by tommoor** [comment]
Hi @defunctzombie – it's not super well exposed, but if you go to:

Collection -> Click on "..." menu -> Edit -> Description

The description field has similar capabilities to a document, let me know if it fits the bill.

**Comment by defunctzombie** [comment]
@tommoor I did find that. It seemed to me that was more meant for a sentence or paragraph rather than a full page of content. Maybe that is because the field size is small. I am imagining editing more like I edit a regular document.

**Comment by tommoor** [comment]
It is optimized for that for sure, but you could write more in a rare case. I understand the want here though – we've definitely spoke about making collection pages act more like documents cc @thenanyu

**Comment by defunctzombie** [comment]
👍 I feel similarly about the wiki "Home" page as well. I would find more value in a curated page rather than seeing the recently updated or viewed documents.

**Comment by thenanyu** [comment]
This is more or less achieved through the collection description, which is available in the "edit collection" menu

![image](https://user-images.githubusercontent.com/427579/88744107-4454d380-d0fb-11ea-9a21-f0264773f93a.png)

It's not an amazing UX, but probably gets the job done for now.

**Comment by defunctzombie** [comment]
I'd say this request was to _enhance_ that UX to make it editable similar to a full page.

**Comment by amacneil** [comment]
Not sure why this is marked as done, but +1 on the original request. I would like to create a homepage for a collection. The provided solution has slightly odd behavior since you still end up with all the `Documents, Recently Updated, etc` tabs underneath the homepage content. A particularly long homepage content would hide those useful links.

I think it would be better to select a page to act as the collection homepage, and display that as the first tab on the collection overview. For example `Home, Documents, Recently Updated, etc`.

I think this could be entirely separate from the description, which feels like it should be used for a short collection description.

**Comment by jaimesdias** [comment]
> Not sure why this is marked as done, but +1 on the original request. I would like to create a homepage for a collection. The provided solution has slightly odd behavior since you still end up with all the `Documents, Recently Updated, etc` tabs underneath the homepage content. A particularly long homepage content would hide those useful links.
> 
> I think it would be better to select a page to act as the collection homepage, and display that as the first tab on the collection overview. For example `Home, Documents, Recently Updated, etc`.
> 
> I think this could be entirely separate from the description, which feels like it should be used for a short collection description.

I strongly support this. This maintains all the useful functionality while providing the customization we need. Would love to see this implemented.

**Comment by tommoor** [comment]
Good idea 👍🏻
