### ISSUE TITLE
Error before uploading image below an image at the end of document: can't find DOM node 38

### ISSUE THREAD

**Issue by Abdillah** [outline/outline#1234]
# Description
Uploading image at the end of document after an image. In v0.42.0 there's a fix `Crash on editing documents with image/embed as first node` yet I can't check that fixes since I use my company outline.

# Step to Reproduce
At the end of document, I want to add image using add (+) button. Once the toolbar popped up, I click the image and the document crashed (while still showing upload dialog).

# Expected
Document still intact and image uploading can proceed.

# Unexpected
Raised

```
Error: Unable to find a DOM node for "38". This is often because of forgetting to add `props.attributes` to a custom component.
```

# Software Info
v0.41.0

**Comment by tommoor** [comment]
@Abdillah thanks for filing – as you noted, your company is several releases behind, please let me know if the error persists on the latest version once your team has updated and I'll be happy to investigate. As you pointed out there have been fixes made in this area already.
