### ISSUE TITLE
Logo/profile images do not show (using Minio), but document images do

### ISSUE THREAD

**Issue by klickers** [outline/outline#1236]
I recently installed Outline on my server using docker.  I also installed Minio, and changed my environment variables look like this:
```
AWS_ACCESS_KEY_ID=minioaccess
AWS_SECRET_ACCESS_KEY=key_to_above
AWS_REGION=xx-xxxx-x  // left as is
AWS_S3_UPLOAD_BUCKET_URL=https://minio.example.com
AWS_S3_UPLOAD_BUCKET_NAME=bucket_name
AWS_S3_UPLOAD_MAX_SIZE=26214400
AWS_S3_ACL=private
```
When I try to change the profile image or logo image, however, the image is successfully placed into the Minio bucket, but doesn't show up on the page.  (Images within documents _do_ load.)  From what I see in the browser console, it seems like the old environment variables are still being used to try to get the profile/logo images.  How can this be fixed?

**Comment by tommoor** [comment]
I'm closing this issue as it isn't a bug in the software, you may continue to reply in the thread.

**Comment by Bmiest** [comment]
I am having the same issue after upgrading my docker image today to latest (53.1)
![image](https://user-images.githubusercontent.com/18619887/108205113-eb936980-7124-11eb-9dfb-56535edc4a3a.png)

Is this command required to be ran?:
docker run --rm outlinewiki/outline:latest yarn sequelize:migrate

**Comment by Bmiest** [comment]
Nevermind, it was the same issue with the public bucket policy:
https://github.com/outline/outline/issues/1581

docker run -it --entrypoint=/bin/sh minio/mc
sh-4.4# mc alias set minio http://redacted:9000 redacted redacted--api S3v4
Added `minio` successfully.
sh-4.4# mc policy set public minio/outline-bucket/public
Access permission for `minio/outline-bucket/public` is set to `public`
sh-4.4#

**Comment by tommoor** [comment]
Glad you figured it out, getting all the config "just right" for minio is quite tricky.

**Comment by xaralis** [comment]
For the record, Outline somehow refuses to work when the bucket is named `outline`. It then uses weird URLs, don't know why. Once switched to `outline-bucket`, I was too able to make it work.

**Comment by tommoor** [comment]
It might be this check – https://github.com/outline/outline/blob/main/server/utils/s3.js#L95 – I'm guessing the root bucket also includes the word "outline"?

**Comment by dedsxc** [comment]
Updated command: 

```bash
## Allowed values are [private, public, download, upload].
mc anonymous set public myminio/outline/public
```
