### ISSUE TITLE
Document-level embeds setting is gone

### ISSUE THREAD

**Issue by kpsuperplane** [outline/outline#1237]
It appears that #829 removed the document-level embeds toggle from the document menu. 

https://github.com/outline/outline/pull/829/files#diff-935fd8889de7cd0fb0b45b1862116f20 

Was this intentional? I can't find any documentation to suggest so.

**Comment by tommoor** [comment]
Thanks for filing, I'm honestly not sure how that slipped in – It seems fine to restore that option 👍
