### ISSUE TITLE
Horizontal scrollbar on long pages.

### ISSUE THREAD

**Issue by DeeGeeTill** [outline/outline#1241]
Unsure whether or not this is an issue just affecting Windows and Linux users or not. It's a little bit of a nit-pick of mine. In documents that extend past the bottom of the screen, there is a horizontal scrollbar when there shouldn't be.

![image](https://user-images.githubusercontent.com/34075000/80267010-e39aa280-8696-11ea-95a7-bc586e88bf8a.png)
_This image is kind of a bad example because there are multiple collapsed scrollbars with tables inside of them._

![image](https://user-images.githubusercontent.com/34075000/80267159-9b2fb480-8697-11ea-9507-0ad3d5532d5b.png)
_Here in Firefox_

![image](https://user-images.githubusercontent.com/34075000/80267289-d29e6100-8697-11ea-87c4-c5b836da08d1.png)
_As well as here in Chrome_

To recreate, on a non-mac make or view a document that extends past the bottom of the screen. It doesn't go away with scaling, or by using a different browser.

Again, it's quite a nit-picky bug, but it does just make scrolling with a touchpad a little janky.

EDIT: It also doesn't go away by switching into Production mode, and is still present on [getoutline.com](https://getoutline.com/)
![image](https://user-images.githubusercontent.com/34075000/80267108-64599e80-8697-11ea-96a4-bb7f449b21d6.png)

**Comment by tommoor** [comment]
I don't have access to a windows machine, but would accept a PR. It looks like you're running Outline in development mode in this screenshot, that might be affecting the styling

**Comment by DeeGeeTill** [comment]
Sorry I updated the post while you were responding (which btw, lol wow you responded quickly). I've also tried it on the official getoutline website, and that also shows the same bug. This also seems to happen on my Linux machine, though I don't have immediate access to that.

**Comment by tommoor** [comment]
It is possible to reproduce on mac by forcing the scrollbars to display 👍
