### ISSUE TITLE
I can't access error logs in production

### ISSUE THREAD

**Issue by carvalhorafael** [outline/outline#1243]
I've been working to host Outline in AWS Opsworks. The app is up and running.  However, I can't login with Google.

The main problem is that I can't access the error logs to see what is going on.

I used this command to start `NODE_ENV=production pm2 start index.js --name outline`.

How can I access error logs with the application running in production?

**Comment by tommoor** [comment]
Give `master` a try, I just pushed some changes to change the assumption that you have Sentry setup for capturing errors.

**Comment by carvalhorafael** [comment]
Thank you @tommoor 

I merged with `master` and configured Sentry setup. But I still couldn't get the logs.
I guess it is because there is no log in the file that I am having problems (`server/auth/google.js`).

Here is an image that shows which screen I'm stuck on.

<img width="939" alt="Screen Shot 2020-04-26 at 08 51 39" src="https://user-images.githubusercontent.com/496442/80307145-b553ba80-879d-11ea-99f0-f3f8760d6ef6.png">

After choosing an account to login, Google authenticates and redirects to the application. However, the application does not respond.

**Comment by tommoor** [comment]
closing this out as the error reporting has been improved and you opened a new ticket for the Google auth question.
