### ISSUE TITLE
Outline doesnt work since backlink update

### ISSUE THREAD

**Issue by giusimonetta** [outline/outline#1244]
Hey,
I got an auto deploy pipeline for my self hosted outline instance. Since [this commit](https://github.com/outline/outline/commit/c41e6e0423c171ef72a5391813eef0dba2f39f6b) my outline instance doesnt work anymore. 

Server logs
![Anmerkung 2020-04-26 135837](https://user-images.githubusercontent.com/16366544/80306841-0d9eb280-87c6-11ea-89cb-94285954f87c.png)

Browser console logs
![Anmerkung 2020-04-26 135953](https://user-images.githubusercontent.com/16366544/80306931-63735a80-87c6-11ea-8f7e-4b889f9a9e8a.png)

I've checked the postgres db, my backlinks table is now empty.

**Comment by tommoor** [comment]
Will be tackled today, I recommend against running `master` and instead a released version – it's always possible that it's broken.

**Comment by tommoor** [comment]
This is a weird one though, the issue seems be exactly what that PR was intending to resolve…

**Comment by tommoor** [comment]
The error in your logs points out L85, that's exactly where the error was before the guard was put in place on the commit that you said you're running: https://github.com/outline/outline/commit/c526adf2922b8ff82d5aa02e36890747d78e9982#diff-789bcaf3232c7604ae988b5bec595b53R85

I'd double check the commit you're running, with the current code I can't see a way this would be triggered.

**Comment by giusimonetta** [comment]
Ok, running on 0.42.2 now. But the app still doesnt work. The backlinks table is empty right now, but the document entrys are still there.
I've checked the deploy dates. It's getting weird now. On Fri, Apr 24, 2020 2:51 PM we made a deployment. The app seems to be broken since then. The funny thing is, the deployment came from the commit 6db92c9f. How the hell is this possible?😄

**Comment by tommoor** [comment]
Hi, try deploying this commit – https://github.com/outline/outline/commit/e1adb16c4364caf6af01577784a8187d7caf44dc – I'm 90% sure your problem was that Node 14 was being used as part of your auto deployment.

**Comment by tommoor** [comment]
Closing as resolved
