### ISSUE TITLE
Sign in method

### ISSUE THREAD

**Issue by ckc** [outline/outline#1246]
For use case under internal, is it possible no use either slack or google sign in? 
(If do so, I just only comment it https://github.com/outline/outline/blob/master/server/auth/index.js#L18)

Hope to diectly LDAP, rocket.chat or Mattermost

Thanks

**Comment by tommoor** [comment]
There are several open PR's for different authentication methods that you could take a look at. The most promising is #1183 – but yes, auth/google and auth/slack provide full authentication implementations if you wanted to fork and write your own 😄
