### ISSUE TITLE
Database migrations cannot be run locally for Heroku Postgres

### ISSUE THREAD

**Issue by asherccohen** [outline/outline#1248]
yarn sequelize:migrate cannot be run locally if you're using Heroku Postgres. 
The reason is that Heroku allows using posgres from within the platform but not externally.

SOLUTION:
I had to deploy the application so that migrations were run from within Heroku.

WHY:
https://devcenter.heroku.com/articles/connecting-to-heroku-postgres-databases-from-outside-of-heroku

EXPECTED:
Report this on documentation to help devs during first configuration.

**Comment by tommoor** [comment]
> Heroku allows using posgres from within the platform but not externally.

This isn't the case, even the article you linked to explains that heroku postgres can be connected to from anywhere. Could you provide some more tails on what you'd like the documentation to cover here?

**Comment by asherccohen** [comment]
Sorry, you're right about the link. I didn't read it carefully, I guess my question now is how to enable sslmode with heroku postgres from outline. I tried adding some config to the sequelize initialization and also tried appending sslmode=true to the url.

What I'm seeing is an error in the terminal that ssl is off and connection  was terminated.

**Comment by tommoor** [comment]
Ah, I see – if you still haven't figured it out you can do `heroku config:set PGSSLMODE=require`

**Comment by asherccohen** [comment]
Mmmh. I just tried that, and nothing changes. 
I tried with and without ?sslmode=require appended to the database URL.

The error I'm getting:

```
Sequelize CLI [Node: 12.16.1, CLI: 5.5.1, ORM: 5.21.6]

Loaded configuration file "server\config\database.json".
Using environment "development".

ERROR: no pg_hba.conf entry for host "194.230.xxx.xxx", user "&&&&&&&&&", database "&&&&&&&&", SSL off

error Command failed with exit code 1.
```

**Comment by tommoor** [comment]
Strange yea, I have successfully ran the current codebase in Heroku against a Heroku-hosted database without changing the code, just with `PGSSLMODE` set. There's not a lot more I can do to help here, this is the downside of self-hosting
