### ISSUE TITLE
Search doesn't return some documents

### ISSUE THREAD

**Issue by carvalhorafael** [outline/outline#1250]
Here is the document:
![image](https://user-images.githubusercontent.com/496442/80506232-add21400-894b-11ea-89a7-ecffd0b15758.png)

Search doesn't return, as below:
![image](https://user-images.githubusercontent.com/496442/80506117-8b3ffb00-894b-11ea-8de7-8de3c47ee87a.png)

**Comment by tommoor** [comment]
Thankyou, I believe I know what caused this regression.

**Comment by tommoor** [comment]
I actually tried to reproduce this and haven't been able to so far, so at this point I'm not sure what's going on – is this self hosted?

![image](https://user-images.githubusercontent.com/380914/81370601-69ace500-90aa-11ea-8c50-e25fbaa80a0f.png)

**Comment by carvalhorafael** [comment]
Yes, its self hosted.

I guess that this issue has some relation with the `limit` parameter on the query string, as you can see bellow.

<img width="898" alt="Screen Shot 2020-05-08 at 06 46 28" src="https://user-images.githubusercontent.com/496442/81394244-08136780-90f8-11ea-97aa-3db9b3b468d8.png">

I have a lot of documents, so maybe search is looking only to the first 25 or other behaviour like that.

**Comment by tommoor** [comment]
Maaaybe, but when the search term is perfectly matching the title like that it should be at the top of the list, not past the first page.
