### ISSUE TITLE
can't support Chinese！

### ISSUE THREAD

**Issue by BusyHe** [outline/outline#1251]
![image](https://user-images.githubusercontent.com/17348825/80520032-7307c480-89bb-11ea-9b12-753de0ba6970.png)

**Comment by tommoor** [comment]
This is a known issue with the editor framework we're using. There's a rebuild underway but it will likely be another month or so before it hits production, we're tracking the issue here: #1027

**Comment by BusyHe** [comment]
@tommoor thanks
