### ISSUE TITLE
Reordering elements within a document

### ISSUE THREAD

**Issue by gotjoshua** [outline/outline#1253]
Feature Request:

Drag and Drop and Hotkey based reordering of document elements would be really great.

I am thinking something like [observable uses:
![observableMoveCellHotkeys](https://user-images.githubusercontent.com/8686454/80628792-ce809380-8a49-11ea-96ee-3c8e7d93ed07.png)](https://observablehq.com/@observablehq/keyboard-shortcuts)

Is this in a pipeline/roadmap somewhere?

Would it be a reasonable first issue?

**Comment by tommoor** [comment]
Hi, we're currently rebuilding the editor based on top of Prosemirror. There is some basic functionality for drag and drop re-ordering built in but it could definitely be improved;

The new branch is self contained, clean code, and runs independently of the main Outline project if you did want to take a look: https://github.com/outline/rich-markdown-editor/pull/150 – most of the final pieces of work at the moment is focused on table support.
