### ISSUE TITLE
Code comments show up as content items on the sidebar

### ISSUE THREAD

**Issue by marcelinollano** [outline/outline#1255]
I am running a self-hosted instance of the version `v0.43.0`.

I noticed that when I add code comments inside code blocks, those show up as content items on the sidebar, see this example:

<img width="932" alt="Screenshot 2020-05-02 at 01 33 26" src="https://user-images.githubusercontent.com/6335/80848991-962db080-8c15-11ea-9e6e-0c5bff0afc04.png">

It seems like it is parsing the `#` char as a heading, but in the context of a `code` block it does not make sense. This makes jumping through texts with lots of code comments a bit of a pain, check this other example:

<img width="1090" alt="Screenshot 2020-05-02 at 01 30 05" src="https://user-images.githubusercontent.com/6335/80849016-ae9dcb00-8c15-11ea-8f38-4a7ab704f8ef.png">

This seems like a **bug**. BTW, outline is super great. Thank you!

**Comment by tommoor** [comment]
Great find, thanks for reporting 💪
