### ISSUE TITLE
Is there any steps if separately deploy Frontend & Backend?

### ISSUE THREAD

**Issue by ckc** [outline/outline#1256]
I saw readme mentioned the structure: 
app/ - Frontend React application
server/ - Backend

I hope to deploy as serverless website (eg.AWS Lambda/Azure Functions/GCP Functions) because my internal have a SSO Interceptor need include to frontend React side.

Like title mentioned, is it work if I just deploy these two folders separately? Any extra modify/steps?

Sorry I am new to Node and serverless, I'm not sure is it suitable ask in here

Thanks

**Comment by tommoor** [comment]
Hi Jack, Outline is not designed to deploy in a serverless environment. The app makes extensive use of websockets which require a standard server environment where connections can be held open to work.

**Comment by ckc** [comment]
Hi @tommoor, is it possible to work with API gateway stuff for websockets?

**Comment by tommoor** [comment]
I have no idea. By all means give it a try, but I just wanted to be clear that the project is not architected to run in a serverless environment.

**Comment by ckc** [comment]
Understood, thanks your prompt reply :)On 4 May 2020 01:32, Tom Moor <notifications@github.com> wrote:
I have no idea. By all means give it a try, but I just wanted to be clear that the project is not architected to run in a serverless environment.
