### ISSUE TITLE
Empty document can not be saved when editing

### ISSUE THREAD

**Issue by hotohoto** [outline/outline#1258]

**Comment by tommoor** [comment]
Hey, this is expected behavior. We protect against completely empty documents at the API level.

**Comment by hotohoto** [comment]
Then it should be not allowed?

**Comment by tommoor** [comment]
It might be useful if you share a gif of the behavior you're seeing, I'm not exactly sure what the expected behavior is from your point of view but happy to dig in further!

**Comment by hotohoto** [comment]
Oh, I see. Sorry for the unclear explanation. Here are what I'm thinking about it.

## steps to reproduce

- Create a page with some contents and save it

![image](https://user-images.githubusercontent.com/5404902/81256165-a0fba180-906a-11ea-8726-fe35767e28ab.png)

- Click the `Edit` button and delete the contents

![image](https://user-images.githubusercontent.com/5404902/81256193-b1ac1780-906a-11ea-9cc1-ae6aaeeb1a3f.png)

- Click the `Done Editing` button

## AS-IS

- The page goes to the read-mode with all the deleted contents being still there

![image](https://user-images.githubusercontent.com/5404902/81256416-69d9c000-906b-11ea-8ba6-56de712c6ae6.png)

## TO BE

There might be some options

- option1: disable `Done editing` when there is no content.
- option2: show an error message when clicking `Done editing` with no content. e.g. "Insert contents". and stay in the edit-mode.
- option3: just allow the content to be empty
