### ISSUE TITLE
URL disappears when adding a bullet in front

### ISSUE THREAD

**Issue by hotohoto** [outline/outline#1259]
## Steps to reproduce

- enter a URL
- insert `*` in front of the URL
- insert space bar (` `) 
- you'll see the URL disappears

## Screenshots

![image](https://user-images.githubusercontent.com/5404902/81194056-26456e80-8ff7-11ea-80b0-93a3194d3c82.png)

![image](https://user-images.githubusercontent.com/5404902/81194088-2e9da980-8ff7-11ea-9147-e64fa14680d5.png)

![image](https://user-images.githubusercontent.com/5404902/81194105-34938a80-8ff7-11ea-9e92-d34f600b9f24.png)

**Comment by tommoor** [comment]
Thanks for filing, we've been working on a rebuild of the editor and I just confirmed that this issue does not exist in the new version. We'll roll out as soon as practicable and I'll close this issue then.
