### ISSUE TITLE
Cannot input special characters inside a note

### ISSUE THREAD

**Issue by filipebanzoli** [outline/outline#1260]
Hello!

Apparently, special characters are working in titles, I can even search them, but I cannot input them inside a note, neither online, either in the hosted version.

I cannot insert with my keyboard characters like these bellow inside a note:

áãâéẽêíõôúũ

I am able to paste characters like these too, but I cannot make them inside the note with my keyboard.

Without it, it will be almost impossible for any spanish or portuguese language speaker use the app :((

Btw, besides it, your product is really great! Thanks.

**Comment by tommoor** [comment]
Hi, are you using a soft/virtual keyboard to input the characters?

**Comment by filipebanzoli** [comment]
No, I'm using my hard keyboard..

I went deeper into this issue and realized that in my Windows Chrome it works perfectly, but in my Ubuntu Chrome it wasn't, in both the self-hosted and online version.

I checked the console, and I think this bug is responsible for not allowing me to write special characters:

![Screenshot from 2020-05-06 14-35-30](https://user-images.githubusercontent.com/40249901/81211409-b6f55d80-8fa9-11ea-9c01-8f5f0383ecaa.png)


"Refused to load the font ... because it violates the following Content Security Policy directive: "default-src` `'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback."

I found in the internet that it might be because of one specific Chrome Extension, but even with incognito session that continued to happen.. but indeed it appears to be a CSP issue.

Thanks for your help, and apparently it seems to be a more specific issue that affects less number of devices/people.

**Comment by tommoor** [comment]
This must be an extension, I think it's a red herring as Outline does not use the OpenSans typeface. I'm going to combine this issue with the other issue for alternative language input as I'm 99% sure it's solved by the work that's happening there.

https://github.com/outline/outline/issues/1027
