### ISSUE TITLE
Sequelize migrations behind SSL in production

### ISSUE THREAD

**Issue by benmort** [outline/outline#1261]
I was unable to run my migrations in production heroku as the DB is behind SSL.
The behaviour was that migrations were failing silently. Expected behaviour is for them to run smoothly.

```
{
  "development": {
    "use_env_variable": "DATABASE_URL",
    "dialect": "postgres"
  },
  "test": {
    "use_env_variable": "DATABASE_URL_TEST",
    "dialect": "postgres"
  },
  "production": {
    "use_env_variable": "DATABASE_URL",
    "dialect": "postgres",
    "ssl":true,
    "dialectOptions": {
      "ssl": {
        "require":true
      }
    }
  }
}
```

**Comment by tommoor** [comment]
You can set the env variable `PGSSLMODE=require` in this circumstance, I don't think SSL should be enforced in the config, although obviously it's highly recommended.

**Comment by tommoor** [comment]
I recommend setting the env var instead of changing code, feel free to reopen if this doesn't work for you.
