### ISSUE TITLE
Broken Korean letter on editor

### ISSUE THREAD

**Issue by dev-nicelee** [outline/outline#1265]
### Issue

There is a problem when typing Korean letters like below.

![Screen Shot 2020-05-11 at 13 27 54](https://user-images.githubusercontent.com/32350596/81524203-3f4d7700-938b-11ea-82c1-d61e32d2c662.png)

For your more information about Korean letter, A Korean letter is usually made of a combination of consonants and vowels. For example, letter **밥** is the combination of **ㅂ** + **ㅏ** + **ㅂ**. But unfortunately I couldn't successfully manage to type Korean letters on my mac as well as iPhone. (Copy a normal text and paste to editor works though..)

This may happen especially the first letter of a syllable.

So far, this seems the only issue on Apple devices. I've checked Andorid, Windows and that works.

### Environment

Mac
- macOS Catalina (10.15.3)
- Chrome Version 81.0.4044.138

iPhone
- iPhone Xs
- iOS (13.3.1)
- Chrome mobile 81.0.4044.124

### Steps to reproduce

1. Create a doc
2. Type any letter of combination of Korean characters in editor.

### Possible solution

This might be the problem of text encoding. [Ref](https://twiki.org/cgi-bin/view/Codev/UnicodeMac)

**Comment by tommoor** [comment]
Thank you for the detailed report, I'm combining this with the other issues that are resulting from poor soft keyboard support (#1027). We have an effort underway to replace the editor that I hope to land soon, this will resolve the issue 👍

Please watch the PR at #1227 if you wish to be notified when the fix lands.
