### ISSUE TITLE
Broken first character in Korean

### ISSUE THREAD

**Issue by zironycho** [outline/outline#1268]
Writing in Korean on title section is working well. But on the editor body section, first character is broken.

**Screenshots**
![](https://drive.google.com/uc?id=1pcsPBFJNMHfiMgTAJV-EAMH2WDFxYVtq)

**Desktop (please complete the following information):**
 - OS: mac
 - chrome / safari

> outline version: https://github.com/outline/outline/releases/tag/v0.42.2

**Comment by tommoor** [comment]
closed by https://github.com/outline/outline/pull/1227
