### ISSUE TITLE
Bug: Cannot edit starred documents

### ISSUE THREAD

**Issue by mont5piques** [outline/outline#1273]
A document accessed thru the starred section is not editable. We must refresh the browser page to allow editing.

**To Reproduce**
1. Navigate to any document
2. Star it using three dots menu
3. Go to starred section
4. Select the document
4. Only share button is availabe (no editing nor New sub-document buttons)

**Expected behavior**
After selecting a starred document, get a regular button list (for edition and the rest).

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser: chromium-browser
 - Version  80.0.3987.163

**Smartphone (please complete the following information):**
Not tested

**Comment by tommoor** [comment]
closed by 218b0ea7
