### ISSUE TITLE
New editor doesn't support HTTP codeblocks

### ISSUE THREAD

**Issue by kpsuperplane** [outline/outline#1284]
Upon migrating to 0.43.0, some of my documents broke because we had codeblocks using the `http` language. Fortunately the editor continued to work so we could change the language to `none`, but before doing so the page would simply display:

```
Error: Unknown language: `http` is not registered
```

**To Reproduce**
Create a document with an `http` codeblock in 0.42
Upgrade to 0.43

**Expected behavior**
Things continue to work

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: 0.43

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Latest

**Comment by tommoor** [comment]
I take it those docs were imported? HTTP has never been a valid option from the editor itself.

**Comment by kpsuperplane** [comment]
@tommoor On second look, you are correct. My bad for assuming it was 0.42 that somehow supported it.

**Comment by tommoor** [comment]
No problem – it still counts as a regression 👍

**Comment by tommoor** [comment]
Reopening until dependency is bumped
