### ISSUE TITLE
Format issues with links

### ISSUE THREAD

**Issue by d1337ted** [outline/outline#1286]
Over the weekend something changed. It looks like you have added some new features for formatting/adding content which is great but visually it looks like I'm seeing some weird formatting issues. It almost appears as if I'm seeing 'escaping characters'. It is very noticeable when you try and use the link function. It also looks weird when you do a checklist item and then try and add anything inside square brackets after that (see second screen shot). 

**To Reproduce**
Create a new link to a website linking it to a single word or phrase,then save the document. 
Create a checklist item and then add square brackets after like this [1] then save document. (second screen shot)

**Expected behavior**
It should just show the single word or phrase with the underline. 

**Screenshots**
![Tool_Kit_Checklist_-_Outline](https://user-images.githubusercontent.com/4377302/82913899-79df1400-9f34-11ea-84d9-5e67ace15646.png)
![Tool_Kit_Checklist_-_Outline](https://user-images.githubusercontent.com/4377302/82914504-346f1680-9f35-11ea-8b8e-a74c9bc43a1c.png)

**Outline (please complete the following information):**
- Install: getoutline.com
- Version: 

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser Firefox
 - Version 76.0.1

**Comment by tommoor** [comment]
Wow, this is terrible. Yes we re-wrote the editor and this launched over the long holiday – it seems there was an unaccounted for edge case here perhaps with links inside of list items. 

The original data is backed up and can be easily restored. Please reach out to hello@getoutline.com with the document ID or a share link so we can take a look in more detail.

**Comment by d1337ted** [comment]
Thanks for the quick reply. I will reach out to hello@getoutline with the document ID. Thanks.
