### ISSUE TITLE
Code block contents count as header

### ISSUE THREAD

**Issue by Kevenvz** [outline/outline#1289]
If you place `#` inside a code block outline sees it as a header even though it's not.

**To Reproduce**
1. Create/Edit a page
2. Place a code block with a `#` inside it
3. It will be seen as a header

**Expected behavior**
I would expect it to not count as a header since some languages use `#` as the start character of a comment.

**Screenshots**
![image](https://user-images.githubusercontent.com/749898/83001510-24763600-a00c-11ea-8248-ffcc077e809d.png)

**Outline (please complete the following information):**
- Install: Self hosted
- Version: I guess 0.43.0 or 0.43.1

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge
 - Version 83.0.478.37

**Comment by tommoor** [comment]
Hi @Kevenvz – thanks for filing. This [was addressed](https://github.com/outline/outline/issues/1255) in v0.43.0, you must be running an older version.

![image](https://user-images.githubusercontent.com/380914/83036843-f125ae00-9fef-11ea-937d-9e384c2e5796.png)
