### ISSUE TITLE
Text not formatted properly when printing italics in Chrome

### ISSUE THREAD

**Issue by arpitchaudhari** [outline/outline#1305]
**To Reproduce**

1. Create a new doc
2. Select the Quote option from the add button.
3. Write something
4. Publish it then select the print option.

_**Note: This error is also occurring for italic text.**_ 

**Expected behavior**
Should show text but showing different format text.

**Screenshots**
Doc I want to print
<img width="1396" alt="Screenshot 2020-06-17 at 7 59 08 PM" src="https://user-images.githubusercontent.com/29978858/84910843-0369a800-b0d5-11ea-843a-9aa6ccced518.png">

When I select the print option
<img width="1412" alt="Screenshot 2020-06-17 at 8 00 10 PM" src="https://user-images.githubusercontent.com/29978858/84910952-28f6b180-b0d5-11ea-9a99-61e256e52736.png">

**Outline (please complete the following information):**
- Install: getoutline.com
- Version: null

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 83.0.4103.97 (Official Build) (64-bit)

**Comment by tommoor** [comment]
I don't know if this is a Chrome issue or a macOS issue but it's certainly bizarre – changing from italic or changing the font face away from the system default both fix the issue so it's unlikely to be anything in Outline's codebase. 

I'll see if there is any way to work around it though!

**Comment by tommoor** [comment]
Note: This is fixed on master, will be deployed to getoutline.com within the next day.
