### ISSUE TITLE
Disable Keyboard shortcuts on Edit Page

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1307]
At this moment is impossible to write a single question mark (?), always open Keyboard shortcuts.

**To Reproduce**:
1. Open a page
2. Edit page
3. Try to put a '?'

**Expected behavior**
Show a ? in text

**Outline:**
- Install: self hosted
- Version: 0.43.3

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Browser Chrome
 - Version Last

**Comment by tommoor** [comment]
This issue was addressed in the last release, https://github.com/outline/outline/releases/tag/v0.43.3 

Please fill out the bug template if you're seeing this still.

**Comment by MatheusRV** [comment]
@tommoor sorry, done!

**Comment by MatheusRV** [comment]
There is another bug with language localization. The code is taking a key position and not the typed character. Believe that this is even valid to change and create a receipt request for them or else report it as a problem, as this certainly impacts other platforms as well. Key / position of: without keyboard ABNT2 is the same as / without keyboard US-International.

**Comment by tommoor** [comment]
Sorry, I don’t understand what you mean.

**Comment by MatheusRV** [comment]
> Sorry, I don’t understand what you mean.

I mean it seems that to open the shortcut you are not reading the key "?" but the position of the key, because on the ABNT keyboard the keys "shift +;" and "shift +?" open the shortcut guide.

**Comment by tommoor** [comment]
If that's the case it must be a bug in a third party library, this is how we define the shortcut:
https://github.com/outline/outline/blob/develop/app/components/Layout.js#L65

You can also see the guard against editing there, so the shortcut is not active while editing a document.

**Comment by MatheusRV** [comment]
Fixed in https://github.com/outline/outline/releases/tag/v0.43.3
