### ISSUE TITLE
Empty lines cause extraneous backslashes when accessing raw text 

### ISSUE THREAD

**Issue by alexieyizhe** [outline/outline#1308]
When adding empty lines in the editor, they cause two backslashes `\\` to appear when grabbing the document through the Outline API.

This is the raw text output:
![image](https://user-images.githubusercontent.com/17508679/85185511-38efcc00-b262-11ea-994d-cea9f65523f0.png)

As far as I can tell, this isn't a quirk of Markdown to display new lines, but I may be wrong!

**To Reproduce**
1. Add empty lines in web editor through <kbd>Enter</kbd>
2. Fetch the document with `/api/documents.info?shareId=X`
3. Get raw text on the `response.data.text` property

**Expected behavior**
Empty lines should not contain any extra characters.

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 0.43.2

**Comment by tommoor** [comment]
This is expected behavior right now, a backslash is our way of encoding empty paragraphs – which isn't something that markdown supports. You can "clean up" the raw output using a regex like this:

https://github.com/outline/outline/blob/f3ea02fdd0881fbc86872e198c088806b5739745/shared/utils/unescape.js#L3-L7

**Comment by alexieyizhe** [comment]
Ah that totally makes sense - I do think the additional parameter for a clean output would be helpful like you said. Thanks for clarifying!

**Comment by tommoor** [comment]
We’ll add a new endpoint in the next release and let you know in this issue
once complete

**Comment by alexieyizhe** [comment]
Sounds good! Great work 😄
