### ISSUE TITLE
Show starred docs in sidebar

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1313]
Currently the treatment for starred is the same as other docs, they basically just get added to another screen that acts the same as any other collection . While this is _okay_ it's barely better than exposing the database schema to the user – starred docs should be **easier to access** than other docs.

### Proposed changes: 

- Remove the existing "Starred" item at the top of the sidebar
- Add a "Starred" heading to the sidebar when the user has starred documents above collections
- Render upto X (10?) documents below it in a flat list and a "Show more…" link at the end
- The "show more" link should navigate to the existing starred page for when there are many starred items to filter through (Use similar styling as the e.g. "New collection")

**Comment by tommoor** [comment]
cc @iamsaumya this is a nice self-contained improvement

**Comment by iamsaumya** [comment]
> * The "show more" link should navigate to the existing starred page for when there are many starred items to filter through (Use similar styling as the e.g. "New collection")

To make sure I have understood this. 

Clicking on "show more" should redirect to the starred page - there will be no way to reach this page except this link because we have removed the "starred" item at the top in the header. 

Also, there is no change on the starred page - we have to keep it as it is.

**Comment by tommoor** [comment]
I think we may need to make the starred header clickable and collapsible,
but it’s not a pattern that exists yet.

Probably implement as you described and we can assess how it feels?

**Comment by iamsaumya** [comment]
I agree. 👍
