### ISSUE TITLE
Redirect loop at /undefined

### ISSUE THREAD

**Issue by Keeperr** [outline/outline#1324]
After signing in with Slack, I enter a redirect loop:

https://example.com/undefined?done=159346533644
https://example.com/undefined?done=1593465301265

The `URL` variable in `.env` is set to `https://example.com`.
The redirect URL is set to: `https://example.com/auth/slack.callback`

I have the following setup:

- Ubuntu 20.04 LTS
- Apache/2.4.41
- psql (PostgreSQL) 12.2
- minio version RELEASE.2020-06-22T03-12-50Z
- Redis server v=5.0.7 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=636cde3b5c7a3923
- NodeJS v12.6.0

Using v0.43.3.

**Comment by tommoor** [comment]
Is `SUBDOMAINS_ENABLED` env set to false or missing? (It should be)
