### ISSUE TITLE
Content Quality Poll

### ISSUE THREAD

**Issue by matbrgz** [outline/outline#1326]
Feature that can be enabled or disabled according to collection, or global configuration that allows users to mark whether the content was useful or not, it would be interesting to have surveys with emojis (happy, neutral and sad).

![image](https://user-images.githubusercontent.com/23284276/86269915-d0c5b200-bba0-11ea-807c-b706822c5955.png)

![image](https://user-images.githubusercontent.com/23284276/86270210-3f0a7480-bba1-11ea-9501-03721e77d152.png)

![image](https://user-images.githubusercontent.com/23284276/86518118-079c0200-be05-11ea-8cd3-23bc19ec1b1e.png)

**Comment by tommoor** [comment]
I like this idea, I think it's also similar to showing a kudos / thanks for a document – as the author it's also really nice to know that others found what you wrote useful, so it might be nice to expose this info back to them.

**Comment by matbrgz** [comment]
Still need it.

**Comment by matbrgz** [comment]
@tommoor could you please reopen it?

@iamsaumya are you interested in a bounty to do that?

@thenanyu could you please help us with the design (& requirements)?
