### ISSUE TITLE
Command to Self Update Outline

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1328]
Upgrading Outline doesn't seem like an easy task. So this feature can assist in updating the platform. I imagine creating in package.json the so-called "update" that will run a script that updates the platform to the latest version.

**Comment by malekhijazi** [comment]
I came across this issue when I was searching for an upgrade guide. I'm currently upgrading from version 0.50.0 to 0.51.0. I couldn't find any documentation for the upgrade anywhere, so I decided to figure it out as this should be easy.

Below are the steps I did to do the upgrade on a production environment.

1. cd into your outline folder installation
2. `git fetch`
3. `git pull`
4. `git status` (check if the branch is up to date)
5. `yarn install` (in case there are any new dependencies)
6. `yarn build`
7. `yarn sequelize:migrate` or `yarn sequelize:migrate --env=production-ssl-disabled` depending on your case
8. `pm2 restart [process_id]`

PS: to get the process id you can call `pm2 list` that retrieves a list of all processes currently running.

After that refresh your outline browser tab and it should be up to date.

Compiling this into a `package.json` script should look something like this:
```
{
    "upgrade" : "git fetch && git pull && yarn install && yarn build && yarn sequelize:migrate"
}
```

For even a shorter version to use the scripts already defined it can be something like this:
```
{
    "upgrade" : "git fetch && git pull && yarn install && yarn heroku-postbuild"
}
```

**Comment by tommoor** [comment]
Nice, yea I think an `upgrade` command as you've defined it would work well – would accept a PR. I'd leave a reminder on this issue that the preferred way to run Outline now is through the published docker images which then means the only thing you have to run at upgrade is the migrations.
