### ISSUE TITLE
Compress large images for better performance

### ISSUE THREAD

**Issue by matbrgz** [outline/outline#1329]
With time and the use of many images it can make the project become heavy. For that I imagine using some node library that compresses the size of the images.

Ref:
[https://github.com/lovell/sharp](https://github.com/lovell/sharp)

**Comment by MatheusRV** [comment]
Just what I imagined after the image upload it goes through an instance of Sharp (or similar) and only after going to storage. With that any image sent will be compressed occupying less space in bytes of storage.

**Comment by thenanyu** [comment]
I updated the title of this issue for clarity

**Comment by cliftonc** [comment]
I would say it is (almost) always better to allow the images to be uploaded as is, and then deal with resizing and caching via a proxy like imgix or one of the many open source / lambda / other based solutions out there.  This gives so much more flexibility esp. when you get to mobile, support for different resolutions, or the ability to show thumbnails easily etc.  It's also a lot less work, as its simple configuration plus a plugin on image rendering to convert the S3 url.

**Comment by matbrgz** [comment]
Still need it.
