### ISSUE TITLE
Granular Permission

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1330]
The permissions are fantastic, but we can improve them even more. What do you think about being able to add jobs and select which collection each job can create, edit or delete documents.

**Comment by MatheusRV** [comment]
For this functionality I think of creating Roles and Permissions; Roles would be the positions that we would assign to users, from now on Admin would become a role. Permissions are the assignments that each role can make. For example, the role Admin has all the permissions, users have only the permissions assigned to it.

Some interesting permissions:
- [ ] Ability to see all collections even private ones not created by you
- [ ] Possibility to edit the settings
- [ ] Creation of API keys
- [ ] Possibility to add new people in groups
- [ ] CRUD Groups
- [ ] CRUD Collection
- [ ] CRUD Document

**Comment by ktfth** [comment]
Maybe was missing the roles for this actions, can we work more on that part?

**Comment by MatheusRV** [comment]
Task canceled, going the other way.
