### ISSUE TITLE
Different Icons Not Showing Locker

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1332]
**To Reproduce**
1. Create a Private Collection
2. Change Icon
3. Not seeing in sidebar the locker

**Expected behavior**
When I change icon i need to see locker.

**Screenshots**
![image](https://user-images.githubusercontent.com/23284276/86380620-ae946880-bc62-11ea-956e-35da3b14298e.png)

![image](https://user-images.githubusercontent.com/23284276/86380656-bb18c100-bc62-11ea-9a6d-74305715f2c6.png)

![image](https://user-images.githubusercontent.com/23284276/86380688-c4a22900-bc62-11ea-8123-7c084a6b79b7.png)

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: 0.43.3

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version Lastest

**Comment by tommoor** [comment]
Hi @MatheusRV – this is by design. We're moving away from the "lock" iconography in favor of granular permissions for all collections… in this middle migration period it might make sense to list public/private in text on the main collection screen

**Comment by MatheusRV** [comment]
is there any way to help you? Would it be possible to join the space where they are planning the platform? 
I'm closed on this issue since it's not a bug
