### ISSUE TITLE
Ability to Disable/Enable Embed Services

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1334]
I believe the title is self explanatory. But It would be very promising in the settings tab to be able to control which embed will appear in the menu plus (+) or bar (/).

**Comment by tommoor** [comment]
We have the ability to disable embeds under the security settings. What is the advantage of disabling individual embeds? Seems like overkill

**Comment by MatheusRV** [comment]
Since the list of embedded services is going to be huge, I think this feature would be interesting. I forgot to express the crucial point of functionality. I imagine a list with a switch button to individually enable and disable any of the services listed because it would be bad to browse the plus (+) menu with many options.

**Comment by tommoor** [comment]
I feel like I'm still not sure that there's a clear advantage to this functionality for all of the extra complexity it will introduce, the list is not really meant to be browsed. At the end of the day most folks will just paste a link and it'll either embed or not.

In an effort to keep the issue backlog focused I'm going to icebox this for now, but thanks for the idea – keep 'em coming.
