### ISSUE TITLE
Improve Draft

### ISSUE THREAD

**Issue by matbrgz** [outline/outline#1335]
Often in a knowledge base the content is not ready to be published and must go through a few steps to be published. For improve the draft system will be awesome to include a kanban screen in which the administrator can configure steps and users can move documents between the steps until the document is actually published.

**Comment by tommoor** [comment]
This one sounds quite similar to the concept we've been discussing called "maintainers", another similar issue here:
https://github.com/outline/outline/issues/1084

We definitely want to have some more workflows for approval of docs. In the first case I'm not sure that will take the form of kanban – the actual tracking should probably be kept in an issue tracker, but having some additional flags as to when docs were approved and by who would be a good start.

**Comment by MatheusRV** [comment]
I understand that there are already other alternatives to the publication workflow. But momentarily we will continue with this idea. At the moment I need that:

- [ ] Back a Document that was Published for Draft
- [ ] Improve Permissions on Drafts (Drafts aren't public, only document owner and invited people can see)
- [ ] Ability to invite to edit a draft with you
- [ ] Kanban for Drafts (sketch)

**Comment by tommoor** [comment]
>  Ability to invite to edit a draft with you

This one already works, just send the link to the person.

> Draft filters

Could you say more about what you were thinking here?

**Comment by giofcosta** [comment]
@MatheusRV ,
It would be like a drag and drop panel with this steps?
There's something ready like this or is  need to develop everything from the scratch?
This steps, the implementation, tables, are they ready?

**Comment by RafaelCoffani** [comment]
@MatheusRV 
Do we have document statuses defined? Draft for Published or others?

**Comment by MatheusRV** [comment]
> @MatheusRV ,
> It would be like a drag and drop panel with this steps?
> There's something ready like this or is need to develop everything from the scratch?
> This steps, the implementation, tables, are they ready?

1. Yes, I imagine use https://github.com/lourenci/react-kanban for kanban.
2. "Develop from scratch"
3. No

**Comment by giofcosta** [comment]
Looks Good!

**Comment by ktfth** [comment]
Have a relation of work on code base for a good start?

**Comment by alexjosesilva** [comment]
Qual a estimativa da sprint ? Quinze dias ou sete dias ?

**Comment by MatheusRV** [comment]
@tommoor whats you think use a react component for kanban?

**Comment by tommoor** [comment]
I think it's jumping the gun a little, I'm not even sure in any way that Kanban is the right solution here and we don't want to design features by deciding which libraries to use first 😉 .

I'd say the natural next step is some way of having "statuses" on documents so that you can denote different stages. Right now we essentially have two "virtual" statuses, "draft" -> "published" – I think that a "review" status is a clear addition and might be enough for 99% of use-cases without introducing a lot of configuration?

That still leaves a lot of open questions around UX – how does something get in review? Who reviews it? What happens when reviewed?

**Comment by guilherme-diniz** [comment]
Adding those statuses, would be a step into the Kanban view, but also we would need to allow a draft to be visible to a team, right?
Where can i change to allow this visibility?

**Comment by MatheusRV** [comment]
Tom how about this?

**Comment by tommoor** [comment]
Re-reading my comments from a month ago, I see two paths forward as next steps:

- Add the ability to invite individual users to drafts, at which point it will appear in their "Drafts" section
- Add document "statuses"

The first one makes the most sense to me as a logical continuation, more thought and planning is required around how statuses would work and be managed.

**Comment by thenanyu** [comment]
both of these directions are fairly close to adjacent features

> Add the ability to invite individual users to drafts, at which point it will appear in their "Drafts" section

this feels like adding document level permissions

> Add document "statuses"

very similar to tags

For both, I would consider just doing the adjacent, more general feature

**Comment by tommoor** [comment]
I agree that the first one is essentially document level positions and as
such would lay the foundation for it.

However, I don’t believe that document statuses are the same as tags. Tags
exist to make navigation and discovery easier, whereas statuses are are
part of an approval workflow
