### ISSUE TITLE
Add Google Tag Manager configuration to allow injection of scripts

### ISSUE THREAD

**Issue by matbrgz** [outline/outline#1336]
In many cases adding only Google Analytics is not possible. Here we work with Google Tag Manager, so I believe it will be interesting to allow adding a code snippet in the head and at the end of the body. So that you can add any metric system like Matomo, Hotjar etc.

**Comment by guilherme-diniz** [comment]
I'm doing this feat and I have 2 questions:
1. In which table should i store this information?
2. The first page that do some request is "/home". Should i do the request from there, or can I do from the index.js?

**Comment by tommoor** [comment]
Hey folks, chatting internally here and we don't feel comfortable enabling arbitrary injection of script tags into the application – even if this is restricted to admin users.

I think as a compromise we can allow an environment variable for specifically injecting Google Tag Manager (Similar to this PR for Hotjar: https://github.com/outline/outline/pull/1359), this can provide a single entry point for injecting others.

**Comment by MatheusRV** [comment]
I just need to add hotjar. GTM Could be a nice script to insert too.

**Comment by guilherme-diniz** [comment]
Should I do a PR to add the GTM like the one for Hotjar?

**Comment by tommoor** [comment]
Hotjar can be injected through GTM, we would accept such a PR.

**Comment by matbrgz** [comment]
I still need it.
