### ISSUE TITLE
Add folding/collapsing of headings

### ISSUE THREAD

**Issue by zwwhdls** [outline/outline#1338]
Hi, 

I upgraded outline to latest version, but I found that the title cannot be folded up any more. This feature is my favorite one, can you add this feature back please? 😣

**Comment by tommoor** [comment]
Hey @zwwhdls – yea, we rebuilt the editor from scratch and this feature didn't make it back in yet. I do think it was useful and would like to restore it on the new framework. Thanks for filing.
