### ISSUE TITLE
Add support for docx import

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1339]
Looks like `mammoth` might be a good package to help with this:
https://www.npmjs.com/package/mammoth

Right now import is done by reading the text/markdown file on the client and then creating a new doc with that text content in the same way you'd create any doc on the client, there is no differentiation. To support new file formats we'll want to wrap this in an API endpoint that can gain filetype support over time. eg:

`POST /files.import` with blob of file(s) and recipient `collectionId`, `parentDocumentId`.

The response should be the changed collection and documents. The Ideal UX is that the existing import flows support `.docx` files seamlessly.

**Comment by MatheusRV** [comment]
I think there is more important upload and embed pdf.

**Comment by whatl3y** [comment]
@tommoor @thenanyu cool if I take a stab at this?

**Comment by tommoor** [comment]
Absolutely, much appreciated. Drop any questions you have in a draft PR and
we’ll do our best to provide help
