### ISSUE TITLE
Lucidchart embeds not showing up

### ISSUE THREAD

**Issue by tecwriter** [outline/outline#1340]
**To Reproduce**

1. Create a share link (Publish or Embed) in Lucidchart.
2. Paste the link into the document or use the plus symbol embedding.
3. Error "Sorry, that link won't work for this embed type" showing up.

**Expected behavior**
When the link is pasted in the editor the Lucidchart diagramm should be embedded.

**Outline (please complete the following information):**
Install: Self Hosted
Version: 0.44.0

**Desktop (please complete the following information):**
OS: Ubuntu 18.04
Browser: Google Chrome
Version: Latest

**Comment by tommoor** [comment]
Do you have an example link? You can share to `hello@getoutline.com` if you'd prefer not to publish publicly.

**Comment by tecwriter** [comment]
I created an example Lucidchart link:
Publish Version: https://app.lucidchart.com/documents/view/1af2bdfa-da7d-4ea1-aa1d-bec5677a9837/0_0
Embedded Version: https://app.lucidchart.com/documents/embeddedchart/1af2bdfa-da7d-4ea1-aa1d-bec5677a9837

**Comment by tommoor** [comment]
Great, so looks like we just need to support the `app.` url variant, in the meantime the links will work if you change them to `www.` as the subdomain
