### ISSUE TITLE
Internal links should look different

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1352]
It's useful to know which links will lead to other documents in the knowledge base, a small "document" icon next to the link itself should suffice.

This will need changes in `rich-markdown-editor` package

**Comment by MatheusRV** [comment]
It would be better to show the external links, there is already an icon for that.  
![image](https://user-images.githubusercontent.com/23284276/89722341-f8d5db80-d9be-11ea-9fa5-17f372b04859.png)

**Comment by tommoor** [comment]
There's an icon for internal links too, I think it makes more sense to highlight links to internal documents as they should feel "more important" in the interface and have a different experience of direct navigation within the app.

Either way, we'll need a new callback in `rich-markdown-editor`, something like `getLinkDecoration` which can be passed `(href: string` and return a `React.Node`

**Comment by renanfilipe** [comment]
I'll be working on it.

**Comment by renanfilipe** [comment]
Where should I call `getLinkDecoration`? I tried to return a React element on src/marks/Link.ts:51 (get schema().toDOM) but it didn't work.

**Comment by tommoor** [comment]
`toDOM` does not support react components, we'd need to render the React component to a standard dom node using `ReactDOM.render` – does this help? It sounds like you're on the right track

**Comment by matbrgz** [comment]
Still need it.

**Comment by almereyda** [comment]
I'm also in favour of highlighting the external links. This correlates nicely with the convention in MediaWikis and other wiki engines, and which people might be used to from Wikipedia.

> There's an icon for internal links too, I think it makes more sense to highlight links to internal documents as they should feel "more important" in the interface and have a different experience of direct navigation within the app.

For me it feels the other way round: annotated links that go outside are marked with a visual fraction, while the native (=internal) links remain undecorated and seamless.

Should we roll a dice, or is there some empirics and evidence that one can use to make an informed decision?

**Comment by soulteary** [comment]
For the team, internal links do not require additional visual reminders, because the information inside the software is relatively safe and credible.

The external links are full of changes and uncertainties, giving a visual cue to help users understand the next context switch, and you are no longer browsing in the current application.

**Comment by tommoor** [comment]
Waiting on #2302 – work will start this week
