### ISSUE TITLE
Option to Choose Ordination in a Collection

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1357]
I understand that there is a related idea, but that idea is not as contemplative as this one. At this point I would like to improve the ordering of the **sidebar** to suit different types of documents.

- [X] Alphabetical order
- [ ] Lasted Updated
- [ ] Lasted Created
- [ ] Manual Order (Choose your order dragging and drop) (done with https://github.com/outline/outline/issues/622)

This option would be integrated into the option of creating a collection, and you can choose and change which option best suits that collection

Add an option when creating / editing a collection to select which sort you want to use.

Related to: https://github.com/outline/outline/issues/821

**Comment by thenanyu** [comment]
also related to https://github.com/outline/outline/issues/1310

**Comment by giofcosta** [comment]
@MatheusRV , basically what is needed to do is
- Modify creating collection page to support this feature
- save state of sort (db or cache)
- render sorted sidebar items in front-end
is that right?
