### ISSUE TITLE
Copy button on code blocks is ugly

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1379]
So ugly…

![image](https://user-images.githubusercontent.com/380914/88120769-94bab700-cb78-11ea-971a-590a4cb69644.png)

**Comment by tacurran** [comment]
@tommoor we had the same issue early on at Ory and moved to https://github.com/facebook/docusaurus. perhaps you can look at this: 
website-1.x/static/js/code-blocks-buttons.js
