### ISSUE TITLE
Make collection titles searchable

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1385]
Currently if you search a collection title it isn't included in the list of search results, it would be nice if it did. 

This can be done entirely locally as all collections are loaded on app boot.

**Comment by renanfilipe** [comment]
I'll be working on it.
I thought in only displaying the collection titles if the filter `any collection` is active, we could also show them before any of the documents. What do you think?

**Comment by MatheusRV** [comment]
@tommoor Hello, @renanfilipe is working with us too.

**Comment by thenanyu** [comment]
> displaying the collection titles if the filter any collection is active
sounds good

> we could also show them before any of the documents
yeah try it and see how it feels

**Comment by renanfilipe** [comment]
When no documents were found we display `No documents found for your search filters. Create a new document?`.

What should be the behavior when:
- collections were found but not documents?
- none of them were found?

**Comment by thenanyu** [comment]
> collections were found but not documents?

just show the collections, behaves like normal

> none of them were found?

same empty state as currently

**Comment by thenanyu** [comment]
opening back up

**Comment by tommoor** [comment]
This will be done as part of #2137

**Comment by tommoor** [comment]
You can now search collections by typing `o` `c`, and documents by typing `o` `d`.
