### ISSUE TITLE
Record search queries in the database

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1392]
So that it is possible to create reports on which terms are most searched within the platform, it would be convenient whenever researched to create a record in the database.

**Comment by thenanyu** [comment]
This should be covered by the normal events API — we can fire an event for every search query sent, and record the search term. Any analysis can happen downsteam

**Comment by tommoor** [comment]
I think this might be worthy of it's own table, I've had on mind tracking of search terms too – mainly to be able to show "recent searches", but also to allow team admins to see search terms that produced no results. This would tie in well with a "requested documents" feature!

**Comment by renanfilipe** [comment]
I'll be working on it

**Comment by tommoor** [comment]
Here's my thoughts / guidance on implementation
https://inside.getoutline.com/share/d45f8a75-3246-4da3-ad35-c6a0655edbc8

**Comment by renanfilipe** [comment]
How can I know if the user is from the `app` or from the `slack`? First I thought about using `user.service` but then I saw that it can be slack, email, or google. Should I assume that email and google mean that the user is from the `app`?

**Comment by tommoor** [comment]
It depends which endpoint the search is made from, in this case I mean searches that are literally made from within Slack through the API. The endpoint is here:

https://github.com/outline/outline/blob/develop/server/api/hooks.js#L149-L151

**Comment by sorvis** [comment]
> I think this might be worthy of it's own table, I've had on mind tracking of search terms too – mainly to be able to show "recent searches", but also to allow team admins to see search terms that produced no results. This would tie in well with a "requested documents" feature!

What is the name of the event that logs searches?
