### ISSUE TITLE
Ability to see everyone who visited the document

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1394]
When clicking on the button on the top bar with the number of people who visited the document, a tooltip with the name and how long they visited should appear.

![image](https://user-images.githubusercontent.com/23284276/88468512-58aa8d80-cebb-11ea-853c-8bc321a1bf2f.png)

**Comment by tommoor** [comment]
Agreed, going to close this out in favor of https://github.com/outline/outline/issues/1105 – which is supposed to cover improvements to this interface
