### ISSUE TITLE
Cancel editing saves anyway, apparently improperly formatted

### ISSUE THREAD

**Issue by sp** [outline/outline#1401]
**To Reproduce**
1. Click Edit on a page, go to bottom of doc
2. Type slash to bring up menu, choose "Table"; inserts empty table
3. Hit escape
4. Confirm intent to abandon changes
5. See raw markdown table at bottom of doc

**Expected behavior**
No change made to doc

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Brave]
 - Version [1.11.101 Chromium: 84.0.4147.89 (Official Build) (64-bit)]

**Comment by tommoor** [comment]
It could be that an autosave occurred, either way you should never see a raw markdown table in the editor – we'll take a look into this.

**Comment by tommoor** [comment]
So far I haven't been able to reproduce a raw markdown table appearing, let me know if you find reliable steps.
