### ISSUE TITLE
Make it clearer which link types are supported from /slash embed flow

### ISSUE THREAD

**Issue by sp** [outline/outline#1402]
**To Reproduce**
1. Type /she and select Google sheets from the autocomplete menu
2. Paste a fresh Google sheets link and hit Enter
3. See error: "Sorry, that link won't work for this embed type."

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Brave
 - Version 1.11.101 Chromium: 84.0.4147.89 (Official Build) (64-bit)

**Comment by MatheusRV** [comment]
You must publish content for web before try to embed.

**Comment by sp** [comment]
Ah. If that had been the error message, I wouldn't have thought it was a bug.

**Comment by tommoor** [comment]
Thanks Seth, you're right – we need to do a better job of making it clear which types of links are acceptable. You can checkout more information on the website, https://www.getoutline.com/integrations/google-docs

**Comment by MatheusRV** [comment]
![image](https://user-images.githubusercontent.com/23284276/88821252-d0690880-d198-11ea-82ec-066452b68bd0.png)
![image](https://user-images.githubusercontent.com/23284276/88821296-dd85f780-d198-11ea-843a-2e3b6cdbe20f.png)

**Comment by MatheusRV** [comment]
Tom is possible to make other links work? Because we want just embed documents shared with all gsuite domain.

**Comment by tommoor** [comment]
Not that I'm aware of, the sheet/doc must be published in order to be iframeable. If you know of any products that enable embedding of authenticated docs I'd be happy to take a look at how it works behind the scenes though.
