### ISSUE TITLE
Apache 2.0 is not compatible to GPL v2+

### ISSUE THREAD

**Issue by danny-laa** [outline/outline#1409]
https://github.com/outline/outline/blob/59c24aba7c0ad580d04c56771ff46b9595f2d5d3/LICENSE#L90-L95

> Despite our best efforts, the FSF has never considered the Apache License to be compatible with GPL version 2, citing the patent termination and indemnification provisions as restrictions not present in the older GPL license. The Apache Software Foundation believes that you should always try to obey the constraints expressed by the copyright holder when redistributing their work.
>
> https://www.apache.org/licenses/GPL-compatibility.html

Apache 2.0 is only compatible to GPL v3.

To fulfill the requirements of Business Source License 1.1, you may consider specifying change license with **both** GPL v2+ and Apache 2.0 (line 94 stated that specifying additional Change Licenses is allowed, with no limitation).

**Comment by tommoor** [comment]
Hi @danny-laa the BSL states "GPL Version 2.0 or any later version", which Apache 2.0 fulfills.

**Comment by danny-laa** [comment]
I get it. "GPL Version 2.0 or any later version" is not a phrase like I thought, but choices to pick from.
