### ISSUE TITLE
Improve Search Bar when Moving a Doc

### ISSUE THREAD

**Issue by HRRock** [outline/outline#1410]
When we need to move doc, it has been really hard to find the right "location" once the list of options doesn't show all the collections or docs that have the same title at the same time. 
Like the example below: We have " About Us" in every single collection but when you search is not showing that. 

![image](https://user-images.githubusercontent.com/65177059/89042693-5742f000-d315-11ea-98bb-20faa4b63fe5.png)

**Comment by MatheusRV** [comment]
![image](https://user-images.githubusercontent.com/23284276/89718552-d5e30180-d995-11ea-87c6-bf60b12080fd.png)
Using this filter could resolve this.
