### ISSUE TITLE
Desktop Application

### ISSUE THREAD

**Issue by matbrgz** [outline/outline#1413]
In the near future I will describe better.

**Comment by 07Gond** [comment]
Maybe we can get some ideas from the Slack desktop app.
https://slack.engineering/rebuilding-slack-on-the-desktop-308d6fe94ae4

**Comment by erlend-sh** [comment]
Highly recommend checking out https://tauri.studio/en/

**Comment by tommoor** [comment]
Closing as we built PWA support, you can install an app to your desktop directly from the browser address bar. We're not planning on building native apps at this time
