### ISSUE TITLE
Error: Minified React error #185: Something Unexpected Happened

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1415]
**To Reproduce**
1. Go to Editor
2. Add a H2 then select it

**Expected behavior**
Platform do not crash.

Seems Related to:
outline/rich-markdown-editor Error: Maximum update depth exceeded https://github.com/outline/rich-markdown-editor/issues/208
https://stackoverflow.com/questions/41326639/minified-react-error-in-react-while-navigation-one-component-to-anther
https://github.com/react-bootstrap/react-bootstrap/issues/3421
https://github.com/bigbluebutton/bigbluebutton/issues/8446

**Screenshots**
![image](https://user-images.githubusercontent.com/23284276/89211348-0ee73480-d598-11ea-8bd5-69b45f72fd47.png)

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: 0.45.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, IE, Edge, Firefox
 - Version We update all client's browser to last.

**Comment by tommoor** [comment]
Closing as duplicate, as you linked it's already filed in the editor repository – we don't need two issues for it.
