### ISSUE TITLE
New doc missing from collection in navbar (until page refresh)

### ISSUE THREAD

**Issue by sp** [outline/outline#1416]
**To Reproduce**
1. Created a new doc in a collection.
2. Titled it and pasted in a bunch of content.
3. Published the doc
4. Doc didn't appear in collection in navbar until page refresh

**Expected behavior**
Doc visible in collection in navbar

**Screenshots**
<img width="1239" alt="Screen Shot 2020-08-04 at 8 58 46 AM" src="https://user-images.githubusercontent.com/831118/89296841-f5de9200-d630-11ea-9a06-c601fc749fa0.png">

Using hosted version, Brave Version 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)

**Comment by MatheusRV** [comment]
Seems related to websocket.

**Comment by tommoor** [comment]
@sp is it possible that this tab was open for a long time? Perhaps pinned while the machine was shut down – wondering if the websocket did not reconnect successfully.

**Comment by sp** [comment]
It was definitely open for a long time, though I don’t think any restarts occurred while it was open, just a lot of sleeps.

**Comment by tommoor** [comment]
I'm going to combine with #1384 – trying to track down in which situations the websocket doesn't reconnect after long periods of inactivity.
