### ISSUE TITLE
Error: Maximum update depth exceeded

### ISSUE THREAD

**Issue by sudipbhandari126** [outline/outline#1426]
<img width="944" alt="Screenshot 2020-08-08 at 2 40 33 PM" src="https://user-images.githubusercontent.com/11029199/89706822-c8724b00-d986-11ea-8bf2-10e657f60f89.png">

**To Reproduce**
1. Go to any wiki page and try writing something
2. select a written text or highlight
4. See error (reload loop)

**Expected behavior**
I want to be able to highlight the text, edit, create a link and so on

**Desktop (please complete the following information):**
 - OS: [e.g. macOS catalina]
 - Browser chrome
 - Version 84.0.4147.105

**Comment by tommoor** [comment]
Self hosted or getoutline.com ? It sounds likely that you do not have permission to edit the particular document, double check with the admin of your knowledge base?

**Comment by MatheusRV** [comment]
Seems related to https://github.com/outline/rich-markdown-editor/issues/208

**Comment by sudipbhandari126** [comment]
@tommoor it's self hosted. I have permission and it works but the behavior is very random and it doesn't work most of the time

**Comment by tommoor** [comment]
Okay, it does seem related to #208 - I've still never reproduced it myself, it's unclear what the situation is that causes it to happen.

**Comment by MatheusRV** [comment]
Tom use Windows and try to edit some text. Use all "/" flashmenu options

**Comment by tommoor** [comment]
If you can reproduce then add this patch into the code and send the logs back here – I need to see what kind of flip flopping is happening in the internal state.

```diff
diff --git a/src/components/FloatingToolbar.tsx b/src/components/FloatingToolbar.tsx
index 4d38b6e..fe8fefc 100644
--- a/src/components/FloatingToolbar.tsx
+++ b/src/components/FloatingToolbar.tsx
@@ -107,6 +107,8 @@ class FloatingToolbar extends React.Component<Props> {
     // of the selection still
     const offset = Math.round(left - (centerOfSelection - offsetWidth / 2));
 
+    console.log({ left, top, offset, offsetWidth, offsetHeight });
+
     return {
       left: Math.round(left + window.scrollX),
       top: Math.round(top + window.scrollY),

```
