### ISSUE TITLE
Migrations won't run on a clean install

### ISSUE THREAD

**Issue by mmajko** [outline/outline#1440]
Migrations won't run, db is empty, logs too.

```
root@outline:/srv# npm run sequelize:migrate

> outline@0.43.3 sequelize:migrate /srv
> sequelize db:migrate


Sequelize CLI [Node: 14.7.0, CLI: 5.5.1, ORM: 5.22.3]

Loaded configuration file "server/config/database.json".
Using environment "production".

root@outline:/srv#
```

`.env` config contains:

```
DATABASE_URL=postgres://outline:XXXXXXXX@10.99.0.3/outline
```

Because of this, the Slack login gets stuck in an endless loop.

**To Reproduce**
1. Clean install according to the steps in "Production" section of README.md
2. Run `npm run sequelize:migrate`

**Expected behavior**
To perform migrations and fill the database with initial data.

**Outline**
- Install: self-hosted
- Version: 9be5597f4b27f2dc17a7b067034e3d2612fda395

**Desktop:**
 - OS: Linux 4.19.0-9-cloud-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

**Comment by mmajko** [comment]
Node version is causing this problem, downgrading to LTS v12 fixed the problem. Also after further investigation it seems that it's problem in sequelize standalone, not with outline.

**Comment by tommoor** [comment]
Yes it's on the list to address - Node engine <14 is specified in package.json for this reason
