### ISSUE TITLE
Allow unpublishing documents

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1463]
Split from: https://github.com/outline/outline/issues/1335

Published documents should have the option to "Unpublish" should you accidentally publish a draft or wish to take it back into a private space.

- Show an "Unpublish" option in the document menu
- Unpublish should remove the document from the collection tree structure
- It should set the `publishedAt` to empty
- "Unpublish" should only be available to the original creator and admins
- "Unpublish" will not be available on deleted or archived documents

**Comment by guilherme-diniz** [comment]
I will tackle this issue!

**Comment by tommoor** [comment]
Closed by 0aa338cccca7e83c93783a13a3277ce0a704ff9f
