### ISSUE TITLE
Add a .editorconfig

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1478]
Configure project's editor in .editorconfig file

**Comment by MatheusRV** [comment]
EditorConfig is a file format and collection of text editor plugins for maintaining consistent coding styles between different editors and IDEs.

I would like to facilitate the configuration of the environment by adding an editorconfig that corresponds to the project.

**Comment by tommoor** [comment]
Looking into the options that `.editorconfig` provides it doesn't seem applicable (perhaps a bit dated?) as all code formatting is enforced through the linter in this project. We don't want to have duplicate formatting rules.

You should set your editor to run eslint formatter on save, if you run VSCode it's already set up to do that through `.vscode` config included. I'd definitely accept PR's to enable lint on save automatically in editors other than VSCode.
