### ISSUE TITLE
Extreme Slow Plataform

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1485]
SequelizeConnectionAcquireTimeoutError null.<anonymous>(sequelize.lib.dialects.abstract:connection-manager)
Operation timeout

```
SequelizeConnectionAcquireTimeoutError: Operation timeout
  File "/opt/outline/node_modules/sequelize/lib/dialects/abstract/connection-manager.js", line 289, col 52, in null.<anonymous>
    if (error instanceof TimeoutError) throw new errors.ConnectionAcquireTimeoutError(error);
  ?, in runMicrotasks
  File "internal/process/task_queues.js", line 62, col 5, in runNextTicks
  File "internal/timers.js", line 518, col 9, in listOnTimeout
  File "internal/timers.js", line 492, col 7, in processTimers
```

```
environment: production
handled: yes
level: error
mechanism: generic
```

**To Reproduce**
1. Open Outline

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/23284276/91079699-c6f98180-e61a-11ea-8006-2c8b3ece1ae1.png)
![image](https://user-images.githubusercontent.com/23284276/91086326-28bee900-e625-11ea-84c1-5de958597060.png)
![image](https://user-images.githubusercontent.com/23284276/91087407-c2d36100-e626-11ea-90be-65125a26c985.png)

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: 0.46.0

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version Latest

**Comment by tommoor** [comment]
The operation timed out trying to connect to postgres, so perhaps your postgres server is down or overloaded?
