### ISSUE TITLE
Update deployment documentation to focus on using Docker

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1491]
The current docs talk about installing node etc, it's all unnecessary - we should push folks to use Docker for ease of updating and deployment.

**Comment by wlatic** [comment]
@tommoor I've actually got this up and running in a pretty simple way on Cyberpanel (uses openlitespeed).

I had to manually install nodejs 12 LTS/yarn + install and configure postgres. Once that was done it was just editing .env running the few commands and it was working.

Once I had it working via the pm2 command it was just a case of adding a context to my website:
`context / {
  type                    appserver
  location                /home/<domain>/public_html/outline
  binPath                 /bin/node
  appType                 node
  startupFile             index.js
  appserverEnv            1
  maxConns                100
  env                     process.env.NODE_ENV=production
  env                     NODE_TLS_REJECT_UNAUTHORIZED=0

  rewrite  {

  }
  addDefaultCharset       off
}`

And it was then running the same as any PHP website, but actually faster! The push to docker is probably going to cut off some users, who'd likely want to use it in a shared hosting environment (which should be possible) and with more users it'd bring into play revenue streams for paid/subscription addons (which I'd welcome as the product is good). Happy to doc out my steps if it helps keep the none docker version alive!

**Comment by wlatic** [comment]
From Cyberpanel steps:

- Install Nodejs 12 LTS
- Install Yarn
- Install and setup postgres (main thing about setup is the permissions for auth)
- Setup Postgres DB and user
- Su into the username of the account and go into its home directory
- Git Clone
- Build webpack
- edit .env
- Migrate DB
- Test run with pm2 and stop
- Edit vhost config from inside vhost

If you do decide to keep the docs for self hosting outside docker I'll do more detailed instructions!

**Comment by fooness** [comment]
It might be good to offer Docker images for people who’d like to use that, but please also offer manual installation (without needing AWS or Google or Slack). Also an Ansible Playbook might be a nice addition …

**Comment by wlatic** [comment]
@fooness this is a complete manual install, but you'll still need Google or Slack for authentication. It doesn't use docker, just nodejs + postgres + Openlitespeed. Cyberpanel just makes things a little easier.

**Comment by fooness** [comment]
But why is Google or Slack necessary? What about username/password, what about SSO/SAML/LDAP …

If Outline demands Google or Slack for authentication, we cannot use Outline in our education institution.

**Comment by wlatic** [comment]
I like this style of authentication because it allows the developer to focus on features and performance rather than authentication (which can be a complete time sink).

It'd be nice to see more options provided in the future (O365 etc.)

It is an opensource product and therefore the code could be modified to support another style of login.

**Comment by aam1r** [comment]
This would be amazing to have and is stopping me from switching to Outline.

I'd like to deploy Outline to AWS or GCP and I prefer doing so in the simplest way possible. The current instructions are quite involved.

Is there a simpler guide anywhere that has a Dockerized way of deploying Outline to production?

**Comment by tommoor** [comment]
Yes, the official docket image is here:

https://hub.docker.com/r/outlinewiki/outline

**Comment by aam1r** [comment]
This probably needs a separate issue, but I think having one-click deployments would help increase adoption.

Examples:

- https://aws.amazon.com/marketplace/pp/B00NN8Y43U
- https://marketplace.digitalocean.com/apps/wordpress
- https://azuremarketplace.microsoft.com/en-us/marketplace/apps/WordPress.WordPress

**Comment by rjsgn** [comment]
Hello folks, I wrote a Terraform script with Ansible Playbook that automates the installation on GCP. If you prefer deploying on other platforms, you could just use the Ansible Playbook.

Link:

[https://github.com/rjsgn/outline-terraform-ansible](https://github.com/rjsgn/outline-terraform-ansible)

@tommoor Do you think you could add this to documentation?

**Comment by tommoor** [comment]
Yep, I can't say I know anything about terraform but happy to link to it from the documentation!

**Comment by fooness** [comment]
There’s still no way to use Outline with some local db or ldap and WITHOUT Google/Slack?

**Comment by matbrgz** [comment]
> There’s still no way to use Outline with some local db or ldap and WITHOUT Google/Slack?

at this moment no. Take a look at #1183
