### ISSUE TITLE
Contents menu empty on reload

### ISSUE THREAD

**Issue by tjmcewan** [outline/outline#1499]
The Contents menu open/close state persists across page reloads, but the menu does not regenerate itself on load.

**To Reproduce**
1. Go to a page with a contents menu
2. Click on "Show contents"
3. Reload the page
4. Menu shows: `Headings you add to the document will appear here`

**Expected behavior**
The menu should show the page contents instead of the placeholder text.

**Outline (please complete the following information):**
- Install: self hosted
- Version: `9b5573c5e2`

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome, safari
 - Version 84, 13

**Comment by nickk024** [comment]
I am having this issue in the currently live version of outline web. The TOC will show the placeholder text until i click "Edit", and change one of the headings or add another one. After refreshing the page or navigating away/back, the placeholder text returns.

**Comment by nickk024** [comment]
Upon further experimentation, this only occurs with "Seamless Editing" disabled. Once I re-enable Seamless Editing, the TOC will show all the time as designed.
