### ISSUE TITLE
Not able to differ h4 from text and text bold

### ISSUE THREAD

**Issue by gustavorps** [outline/outline#1512]
Version: v0.45.0
Browser: Chromium Version 85.0.4183.83 (Official Build) snap (64-bit), Linux MX

There is h4, text and and text with bold. But as you can see there no diference.
![image](https://user-images.githubusercontent.com/516827/92310153-eaf58500-ef81-11ea-902e-6a871dd744b0.png)

**Comment by tommoor** [comment]
What type face is it using? Unfortunately the typography on Linux is poor, there is a clear difference on macOS and Windows.
