### ISSUE TITLE
Self hosted first startup improvements

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1513]
- [x] Add call to action for sponsorship
- [x] **When env variables are missing list all at once**
Currently the app will tell you about a different missing env variable every time you start it until they're all added. Let's improve this first run experience so that all the missing dependencies are listed at once.

**Comment by kelkarajay** [comment]
@tommoor I've been lurking and I finally wanted to dig in to this given I'm interested in self hosting. Is [this](https://github.com/outline/outline#development) an up to date development setup guideline?

I can then work on this issue

**Comment by tommoor** [comment]
It is upto date for `development` yes, but this issue is really more about the production experience – hoping to have something that would better guide you through what's needed if say for example you were to run the docker image with no environment variables.

**Comment by kelkarajay** [comment]
Alright, I asked about the dev guidelines because I'll try to spin up a setup and tackle this issue.
