### ISSUE TITLE
Show document preview hover card in backlinks

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#1520]
Seems like a good place to show the hover preview, ideally with the context in which it's referenced, but the baseline preview should be good for now

---
![image](https://user-images.githubusercontent.com/427579/92438530-dcfc5b80-f15d-11ea-91f0-40aac20d41aa.png)

**Comment by thenanyu** [comment]
This seems good to do still

**Comment by almereyda** [comment]
I like this idea. Navigating a LogSeq knowledge base feels frictionless due to the hover cards on the backlinks, which allows you to assess and browse your content recursively.

**Comment by kingfungdesign** [comment]
Would love this feature to be added! I'm currently building a zettlekasten for knowledge management which means there are a lot of backlinks that links knowledge to each other. Being able to preview the documents and backlinks without clicking into them will make it so much more convenient to browse. Almost like browsing a real analog zettlekasten but better.

**Comment by tommoor** [comment]
The want makes sense, I don't think the existing hover cards do the job though – we need a proper larger preview, possibly a  two-up view.
