### ISSUE TITLE
Tiny layout style bug of the nav bar

### ISSUE THREAD

**Issue by LaboratoryK** [outline/outline#1534]
There has been a misalignment of the nav bar in the recent versions, and thus the scroll bar emerges.
I am using Chrome and Safari on both Desktop and Mobile platform, and the discordant scroll bar is more salient on the desktop devices.

Speculating the style you want to implement, maybe alter the attribute of overflow-y with visible can make it work properly.

![outline](https://user-images.githubusercontent.com/23152458/92995826-77331980-f539-11ea-8a07-87b9c5a2d4e3.png)

**Comment by MatheusRV** [comment]
Same here, Self hosted 0.47.1.

**Comment by tommoor** [comment]
closed by ffab4fbf769478c9a46a67cb1dd34584ca1b3478
