### ISSUE TITLE
ReplyError parseError(redis-parser.lib:parser)

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1538]
If this is a local error, please close this.

ERR Error running script (call to f_0a9a51ee96320953ec7bde8e63f3f060b9dac00c): @user_script:41: @user_script: 41: -OOM command not allowed when used memory > 'maxmemory'.   

```
ReplyError: ERR Error running script (call to f_0a9a51ee96320953ec7bde8e63f3f060b9dac00c): @user_script:41: @user_script: 41: -OOM command not allowed when used memory > 'maxmemory'.   
  File "/opt/outline/node_modules/redis-parser/lib/parser.js", line 179, col 12, in parseError
    return new ReplyError(string)
  File "/opt/outline/node_modules/redis-parser/lib/parser.js", line 302, col 14, in parseType
    return parseError(parser)
```

```
Object
message: "OOM command not allowed when used memory > 'maxmemory'."
__proto__: Object
```

**To Reproduce**
1. Keep Tab Opened

**Expected behavior**
No Error

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: 0.47.0

**Comment by tommoor** [comment]
The error says that Redis is using more memory than the maximum memory setting.

This is not a bug in Outline, I recommend checking your redid configuration
