### ISSUE TITLE
Uncaught ReferenceError: Sentry is not defined

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1539]
If this is a local error, ignore and close please.

```
draft-contacts-cleanup-0Wa0y4ZQYv:41 Uncaught ReferenceError: Sentry is not defined
    at draft-contacts-cleanup-0Wa0y4ZQYv:41
```

**To Reproduce**
1. Open Console at Draft Page

**Expected behavior**
No Error

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: 0.47.0

**Comment by tommoor** [comment]
Do you have a better stack trace? Everywhere on the client that could be calling Sentry is guarded, eg:
https://github.com/outline/outline/blob/82433e02a01d7e4603d1a943f3c593bbc0a1be12/app/components/ErrorBoundary.js#L39
