### ISSUE TITLE
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1540]
```
pro.ip-api.com/json?key=<omited>:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

**To Reproduce**
1. Open Console at Any Page
1. See error

**Expected behavior**
No Error

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: 0.47.0

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser Chrome
 - Version Latest

**Comment by tommoor** [comment]
I have no idea what this is, must be an extension - it's not related to the Outline codebase.
