### ISSUE TITLE
ApiClient.js:69 POST shares.info 404

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1542]
`ApiClient.js:69 POST https://<omited>/api/shares.info 404
`
**To Reproduce**
1. Navigate into pages and collections

**Expected behavior**
No error

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: 0.47.1

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version Latest

**Comment by tommoor** [comment]
This is working as designed
