### ISSUE TITLE
People Directory & Profile Page

### ISSUE THREAD

**Issue by matbrgz** [outline/outline#1546]
A listing added to the sidebar menu under "Templates" with all users of the platform.

Design Reference
![image](https://user-images.githubusercontent.com/23284276/93035358-24c62b80-f613-11ea-9c4a-ec236d6fec3a.png)

Afterwards, you will need an internal profile page with all the information that will come slack (https://github.com/outline/outline/issues/1327) and a tab to the readme related https://github.com/outline/outline/issues/1545.

Design Reference
![image](https://user-images.githubusercontent.com/23284276/93035254-e597da80-f612-11ea-92d1-02573dcd5c78.png)

Can you please tell us your opinion, we want to develop this in the next sprint.

**Comment by Cosnavel** [comment]
I like the idea. The design of the internal profile page does not fit my taste. Its the navbar and the edit button that does not seem perfect for my eyes. But to make a point,  the design is easily changeable for self hosters so what 😛

**Comment by MatheusRV** [comment]
> I like the idea. The design of the internal profile page does not fit my taste. Its the navbar and the edit button that does not seem perfect for my eyes. But to make a point, the design is easily changeable for self hosters so what

I'm open for others design, could you suggest something?

**Comment by Cosnavel** [comment]
I would love it to match the overall design of outline. What do you think about that? 
<img width="819" alt="CleanShot 2020-09-15 at 2 06 29@2x" src="https://user-images.githubusercontent.com/42392570/93208443-dc1a8980-f75c-11ea-8b05-4326497b07b7.png">

**Comment by aariacarterweir** [comment]
Love this idea!

**Comment by matbrgz** [comment]
Still need it.

**Comment by almereyda** [comment]
Is Outline a Desktop app now, or where does this screenshot come from?

**Comment by matbrgz** [comment]
@almereyda just a screenshot from some other app. I didn't know the name.

@tommoor could you please reopen it?

@iamsaumya are you interested in a bounty to do that?

@thenanyu could you please help us with the design (& requirements)?
