### ISSUE TITLE
Allow setting default document language in team settings

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1552]
Currently the language of all documents in Outline is set to English. This affects searching when documentation is in other languages as stemming and stop words for full text search are calculated based on this.

A good improvement would be to add the ability to set a default `language` in the team settings, the list of available languages can be gotten from Postgres' included dictionaries: https://github.com/postgres/postgres/tree/master/src/backend/snowball/stopwords

Documents will also get a new `language` field which will be set by default based on the team setting, this field can be used in the stored procedure to calculate the `searchVector` and in the search endpoints to improve accuracy.

Useful reference:
http://rachbelaid.com/postgres-full-text-search-is-good-enough/

Existing stored procedure definition:
https://github.com/outline/outline/blob/5010b08e83bc98701bee30734fcf8a95ccd1666e/server/migrations/20160711071958-search-index.js#L3

**Comment by lddfg** [comment]
Can you provide more information about the full text search of `postgresql`? I searched, but I couldn't get very accurate information.
I use Chinese and I found: So far, `postgresql` still does not support Chinese natively, and when I install the corresponding extension, do I need to replace the `to_tsvector` function to achieve the effect?

**Comment by tommoor** [comment]
That's correct - the extension needs installing, the ts_vector calls need changing and the searchVector stored procedure needs updating as mentioned above ^^

I do imagine that supporting all the other languages would make chinese easier, you'd just need the extension installed and a mapping from chinese->extension to use in ts_vector.
