### ISSUE TITLE
Can't edit title in new and existing documents

### ISSUE THREAD

**Issue by pstuifzand** [outline/outline#1560]
I just created a new account and tried to create and edit a few documents. The editor itself works normally, but I can't
add (or change) the titles of documents.

**To Reproduce**
1. Create a new document
2. Click on the title field
3. Type your title
4. Nothing appears in the title field. When a title exists cursor moves to end of text.

**Expected behavior**
Change the title.

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser firefox and chrome
 - Version FF 80.0.1, Chrome Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by hieptuanle** [comment]
I'm having the same issue. I'm using Chrome on MacOS.

**Comment by deniskern** [comment]
Same here

**Comment by tommoor** [comment]
Hey folks, thanks for reporting – I'm really sorry for the disruption this caused. It's definitely time to get UI automation tests running so that issues like this can't sneak through in the future.
