### ISSUE TITLE
Wrong parsing '\n'

### ISSUE THREAD

**Issue by lddfg** [outline/outline#1561]
Hello, first of all thank you very much for writing such an excellent software `outline`.
My used `outline` on my server, and the version is `68148bd4d8be2ae8199d36ecd3c8ba651f41a5da`. 
The problem is that when I use `\n` in the document, after saving it, the system will parse it into a newline, which is not what I want. Even if I use the \`\` package, it will also be parsed.

**Comment by tommoor** [comment]
Thanks, fix is in the next release.
