### ISSUE TITLE
Moving down moves cursor to bottom of page

### ISSUE THREAD

**Issue by pstuifzand** [outline/outline#1565]
When using the arrow keys the cursor is not moved to the right position. Sometimes the cursor is moved to the bottom of the page when moving down. Sometimes when moving up, the cursor moves to the top, as if using Ctrl-Home/End.

**To Reproduce**
1. Edit a document
2. Type a few lines
3. Use the cursor keys to move up and down
4. Cursor moves to the wrong line

**Expected behavior**
Up key -> move one line up, Down key -> move one line down.

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: firefox
 - Version: 80.0.1 (64-bit)

**Comment by tommoor** [comment]
Hi @pstuifzand could you provide a screencast? I'm unable to reproduce with Firefox on macOS. Do you have any extensions installed like Grammarly for example that could be messing with it?

**Comment by pstuifzand** [comment]
I restarted Firefox to run without add-ons enabled. Without add-ons it still happens.

https://youtu.be/Aah2G7QWFa0

Steps
1. Press down three times. Cursor moves on third keypress to bottom of screen.
2. Press up three times, moves to header and then line below header
3. Press up one more time moves to top.

**Comment by tommoor** [comment]
Could be related to the heading then? Will check into it more and get back to you

**Comment by tommoor** [comment]
The fix has been deployed, lmk if that doesn't work out for you.
