### ISSUE TITLE
Pasting in the code block should not parse

### ISSUE THREAD

**Issue by lddfg** [outline/outline#1566]
Hello, first of all, I am sorry, because I don’t know whether this `Issus` is `bug` or `request`. I glanced at the other `Issus`, and it seems that no one has raised this question.

The environment:
* Service type: self-built service
* Outline version: 68148bd4d8be2ae8199d36ecd3c8ba651f41a5da
* server: linux
* client: chrome

The problem is:
When I copy and paste the text content, `outline` checks the content (maybe), which is fine. But when I plan to paste some program code, I first wrap it with ``````, and then, after I press `C-c`, the pasted content will leave the\<code\>block, and my code is treated as `markdown` parsing. If I copy the code of `python`, and use a comment like `# This is a comment`, this will be treated as a first-level title by `outline`

Of course, I can wrap the code with `markdown` syntax before copying and then copy and paste, but this requires me to modify the content to be pasted, and then restore it after pasting. I think this is painful.

If the way I am using is wrong, please tell me how to solve this problem.

Or I suggest that we should check where I pasted before analyzing the pasted data, and then analyze the pasted content accordingly. If I paste in the \<code\> block, it means that we don't want to parse what I pasted.

**Comment by tommoor** [comment]
Thanks for filing, agreed this would be a nice improvement 😄

**Comment by lddfg** [comment]
Surprisingly, you can understand what I mean. I used Google Translate to translate. I thought there would be problems in communication. I am very happy to find such a good project, thank you.
I don’t know much about `html`. I think the data that does not need to be escaped may be more than the content under the \<code\> tag, so please don’t drop other tags.
