### ISSUE TITLE
Block-scoped declarations

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1572]
```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
  at ? (/static/vendors.237dffc51eb02dab7222.js:2:69)
```

**To Reproduce**
1. Sentry Log

**Expected behavior**
No Error

**Screenshots**
![image](https://user-images.githubusercontent.com/23284276/94091451-a590de80-fdee-11ea-9dc9-2cd7bf022b7a.png)

**Outline (please complete the following information):**
Self Hosted 0.47.1

**Comment by tommoor** [comment]
Hi @MatheusRV – this error is from Chrome 23 according to your screenshot, this browser was released over 8 years ago – our settings are currently to only support browsers with greater than `0.25%` market share, that aren't considered dead.

https://github.com/outline/outline/blob/develop/package.json#L58
