### ISSUE TITLE
Copy and paste will have unnecessary node data

### ISSUE THREAD

**Issue by lddfg** [outline/outline#1576]
The environment:
Service type: self-built service
Outline version: v0.48.0
server: linux
client: chrome

The problem is:
When I copy a certain keyword in the code of the page and paste it somewhere on the current page, the structure field of the code will be pasted (I think it is structure data). I think this is not needed. It may be needed elsewhere, but such behavior may be inappropriate.
Example:
When I copy the `EXCLUSION` keyword in the code block and paste it on a new line, he will paste the data:
````
NoneBashCSSCC#HTMLJavaJavaScriptJSONPHPPowershellPythonRubyTypeScriptCopy
```javaScript
RESPONSE
```
````
Of course \```javaScript...\``` was added by me because `RESPONSE` is in the code block, but I can't copy it out, you can try it. If you can’t reproduce, or don’t understand what I mean, I can take a screenshot to illustrate.

**Comment by lddfg** [comment]
Okay, I see that there is an option to paste as plain text in the browser. This problem may need to be modified: when pasting formatted data, after parsing, you may have forgotten to delete the relevant data.

**Comment by tommoor** [comment]
I can check into it tomorrow for sure, a gif is always helpful ☺️

**Comment by lddfg** [comment]
![image](https://user-images.githubusercontent.com/11463045/94357093-6a313100-00c8-11eb-9144-2adc9e419d39.png)

**Comment by tommoor** [comment]
The underlying fix has merged, it will deploy to production soon
