### ISSUE TITLE
Unable to run yarn sequelize:migrate on docker

### ISSUE THREAD

**Issue by haydnhkim** [outline/outline#1577]
yarn sequelize:migrate is not executable on docker.
I override the command.
command: `sh -c "yarn sequelize:migrate && yarn start"`

The following error occurs when running the docker:

```sh
yarn run v1.22.5
$ sequelize db:migrate

Sequelize CLI [Node: 14.11.0, CLI: 6.2.0, ORM: 6.3.4]


ERROR: Cannot find "/opt/outline/server/config/database.json". Have you run "sequelize init"?
error Command failed with exit code 1.
```

The problem seems to be caused by deleting the server folder from Dockerfile.

https://github.com/outline/outline/blob/f2abf38fe46b31d871b26cf75d5ff63f7a47b9c6/Dockerfile#L15-L19

**Outline:**
- Install: docker outlinewiki/outline:version-0.48.0
- Version: 0.48.0

**Comment by tommoor** [comment]
Makes sense, thanks for finding - any way you can inject the config that you know of until a patch release is available?

**Comment by haydnhkim** [comment]
I tried a temporary method.

docker-compose.yml
```sh
 command: > "wget https://github.com/outline/outline/archive/v0.48.0.tar.gz -O /tmp/outline.tar.gz && \
  tar xvzf /tmp/outline.tar.gz --directory /tmp && \
  mv /tmp/outline-0.48.0 /tmp/outline && \
  cp -rf /tmp/outline /opt && \
  rm -f /opt/outline/.env.sample && \
  yarn install --production=false && \
  yarn build && \
  yarn sequelize:migrate && \
  NODE_ENV=production yarn start"
```

It seemed to work, but another problem occurred.

```sh
yarn run v1.22.5
$ sequelize db:migrate

Sequelize CLI [Node: 14.11.0, CLI: 6.2.0, ORM: 6.3.4]

Loaded configuration file "server/config/database.json".
Using environment "production".

ERROR: The server does not support SSL connections
```

sequelize.js is supposed to respond to PGSSLMODE=disable, but database.json does not have the option to disable SSL, which seems to be an error.

https://github.com/outline/outline/blob/6b6d67beb66fd6a1ff7bdace76723e4187166a3f/server/sequelize.js#L18-L26
https://github.com/outline/outline/blob/6b6d67beb66fd6a1ff7bdace76723e4187166a3f/server/config/database.json#L13-L16

**Comment by tommoor** [comment]
Docker image is building now with tag `v0.48.1` – this leaves the `server/` directory inside the image and adds an additional option to migrate without SSL, I opted for speed here – we might be able to have it pick the right config in the future but for now you can do:

`sequelize:migrate --env production-ssl-disabled`

**Comment by tommoor** [comment]
Closing, please re-open if issues persist with this release. Thanks for raising
