### ISSUE TITLE
When scrolling from TOC, title is off screen top

### ISSUE THREAD

**Issue by lddfg** [outline/outline#1578]
The environment:
Service type: self-built service
Outline version: v0.48.0
server: linux
client: chrome

The problem is:
When I click on the title on the left, `outline` can't locate the content position well. Because `outline` has a top bar, I think you may have overlooked it.
![image](https://user-images.githubusercontent.com/11463045/94360874-20097900-00e3-11eb-8a98-4b14d3cea460.png)
when i disable the banner??? This will be the correct display。
![image](https://user-images.githubusercontent.com/11463045/94360917-56df8f00-00e3-11eb-829b-073831d5db7d.png)

AND...
The div class is automatically generated. . . This has caused a lot of trouble in describing the problem. How can I describe this problem?

**Comment by tommoor** [comment]
You mean it scrolls a little bit too far up so the title is hidden behind the bar, yea?

**Comment by lddfg** [comment]
Yes, it's almost like this.
