### ISSUE TITLE
Uploading team logo doesn't respect AWS_S3_ACL

### ISSUE THREAD

**Issue by icabbi-joegarlick** [outline/outline#1581]
When I try to upload a logo for my team on the self hosted version I get an error back from S3 with Access Denied. However when pasting a image onto a post it works. The difference between the requests is when pasting acl is set to private (which is what I have in .env) however when uploading the logo through settings acl is set to public

**To Reproduce**
1. Go to settings
2. Team -> Details
3. Upload Image
4. Fails

**Expected behavior**
I expect the image to be uploaded successfully and the acl be set to what it is in .env

**Screenshots**
Upload from details page:
![image](https://user-images.githubusercontent.com/60359194/94629232-0d956800-02ba-11eb-9728-93a6e4f75e06.png)

Upload from post:
![image](https://user-images.githubusercontent.com/60359194/94629265-2271fb80-02ba-11eb-90f8-72db9edd669c.png)

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 0.48.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge (chromium)
 - Version: 85.0.564.63

**Comment by tommoor** [comment]
Hey @icabbi-joegarlick – I believe the "reason" behind this is that the team logo can be displayed on logged out pages, avatars have the same limitation. Can you loosen the restrictions on the AWS bucket?

**Comment by icabbi-joegarlick** [comment]
Hi Tommoor,

Thanks for getting back to me!

Ah I see, So its set to public so that when not logged in people can still see the team logo? I will try loosening the permissions to test to see if this is the reason, however I don't want to make this permanent as I dont want the bucket open.

I assume the workaround for this is setting the team URL in the .env file?

Thanks,
Joe

**Comment by icabbi-joegarlick** [comment]
Can confirm, opening the bucket permissions fixes the upload issue. 

Locking the bucket back down also has also stopped the upload working.

It would be good if team url was specified in the env then the upload for team image would default to that OR upload based on the ACL setting inside env.

Thanks!
Joe

**Comment by tommoor** [comment]
Keeping the avatar images public as designed, however they will now be uploaded into a separate `/public` folder to allow for separate policies.

**Comment by shankscoder** [comment]
Just tried to get this working with the 0.52.0 Docker image from Dockerhub.

In the Settings page, when setting logo, the upload loads and updates the database, but the image does not load. 

On checking the bucket in the S3 console, the `public` folder is not even created on AWS. (I migrated from a non-docker to a Docker installation).

The path it's trying to access for logo is: `https://{region}.amazonaws.com/{bucket}/public/{userid}/778c371f-3191-46d7-8848-35e373c75f94/logo_circle.png`

Uploads to AWS are working fine for documents however.

**Comment by tommoor** [comment]
Hi, there is now a detailed [guide here for setting up S3](https://wiki.generaloutline.com/share/125de1cc-9ff6-424b-8415-0d58c809a40f).

**Comment by heyValdemar** [comment]
hey guys, I wrote [a detailed guide](https://www.heyvaldemar.com/install-outline-and-keycloak-using-docker-compose/) after I was able to configure Outline with MinIO and Keycloak.

Hopefully, it will help others.
