### ISSUE TITLE
dark mode inline monospace styling is very low contrast

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#1593]
![image](https://user-images.githubusercontent.com/427579/96322015-55abce80-0fcc-11eb-9b1b-bd9684dee5b4.png)

This might be an editor issue?

**Comment by tommoor** [comment]
Nah, editor isn’t in use here. It should probably have a pitch black
background.

**Comment by RotonEvan** [comment]
@tommoor How do I recreate this issue? When I try in dark mode inline code works just fine? Is this issue fixed already?

**Comment by tommoor** [comment]
I haven't looked yet – but it seems like it is specific to this one spot in the settings area

**Comment by RotonEvan** [comment]
> I haven't looked yet – but it seems like it is specific to this one spot in the settings area

Can you tell me exactly where I can find this one spot? Like on which page exactly?

**Comment by RotonEvan** [comment]
Found! I'm working on this...

**Comment by RotonEvan** [comment]
#1595 added; this should fix the issue. Please check !

**Comment by RotonEvan** [comment]
#1596 added; this should fix the issue. Please check !
