### ISSUE TITLE
Title (H1, H2) not opening links

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1609]
When you put a H2 with a link the page opens a new blank page.

**To Reproduce**
1. Create a H2 Title
2. Put a link on this
3. Save
4. Click in the link

**Expected behavior**
Open the link

**Screenshots**
![image](https://user-images.githubusercontent.com/23284276/97321549-c2855b00-184d-11eb-8c5a-932cf7413a9f.png)

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: 0.47.1

**Comment by tommoor** [comment]
This was addressed in v0.49.0
