### ISSUE TITLE
Tom Clancy's Rainbow 6 Siege and Ubisoft not working properly

### ISSUE THREAD

**Issue by TarekSalama** [outline/outline#1615]
**To Reproduce**
I noticed that some games like Tom Clancy's Rainbow 6 Siege used to NOT work at all with Outline but now it does. I am assuming that's true since Outline started supporting UDP.
However I noticed that my connection to Ubisoft (which is accessed using Shift + F2 in game) goes down often especially when I am in the main menu. It doesn't matter if I'm idle or not, it just happens every now and then. I am pretty sure that this "component" of the game is based on UDP since this is exactly what used to not work before Outline started supporting UDP.

Any idea about how I can troubleshoot this or why it's happening?

**Expected behavior**
The game/Ubisoft works normally just like if I had used OpenVPN or WireGuard.

**Outline (please complete the following information):**
- Install: DigitalOcean
- Version: Latest

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 86.0.4240.111

**Comment by tommoor** [comment]
Not related to this repo.

**Comment by TarekSalama** [comment]
@tommoor Which repo then?

**Comment by tommoor** [comment]
No idea? This project has nothing to do with computer games.

**Comment by TarekSalama** [comment]
But it's one application that doesn't work properly when Outline is on.
Voice chat is blocked where I live and VPNs help me bypass that. Outline
does work sometimes but the voice chat component of the game which I am
pretty sure is related to Ubisoft (which handles the friends list as well)
goes down from time to time only when using Outline. I was hoping to get
some insight or help get it fixed if it's a bug.
All I know is that it was almost impossible for it to connect in the past
via Outline but now it does albeit unreliably.

**Comment by tituspijean** [comment]
This is Outline, the wiki software, and not Outline, the VPN software. You are looking for [these repositories](https://github.com/Jigsaw-Code/?q=outline).

**Comment by TarekSalama** [comment]
Oh I am so sorry! This is so embarrassing.
