### ISSUE TITLE
Version 0.49.0 has "version": "0.48.1" in package.json

### ISSUE THREAD

**Issue by japsu** [outline/outline#1617]
The [`package.json` file in the Git commit tagged v0.49.0](https://github.com/outline/outline/blob/v0.49.0/package.json#L200) actually has v0.48.1 in the version number field. Version number on the lower left in Setting reports v0.48.1 and being "1 version behind" even though the installed version is v0.49.0.

**To Reproduce**
1. Install Outline v0.49.0
2. Go to Settings

**Expected behavior**
v0.49.0 displayed on lower left

**Comment by tommoor** [comment]
Yep, you're right – this mistake was reported, but as the image is built there is nothing that can be done until the next release is published unfortunately.

You can safely ignore the "1 version behind" prompt in the meantime
