### ISSUE TITLE
Multiline selection in Edit mode Throws an error "Something Unexpected Happened"

### ISSUE THREAD

**Issue by kuldip-barot** [outline/outline#1623]
The Bug is not letting me select the multiple lines in the Edit mode.
Whenever I try to select anything while being in edit mode, using my keyboard ( shift + arrow keys ). It abruptly throws an error and throws me out of edit mode.

**To Reproduce**
1. Open up the Outline website in Microsoft Edge.
2. Login and open any wiki page.
3. Go to edit mode.
4. Writeup some text of 10 -50 lines (any number of line).
5. Select the multiple lines and scroll up or down and Stop.
6. It would abruptly show an error "Something Unexpected Happened" and will fetch you out of Edit mode.

**Expected behavior**
It should have let me select anything seamlessly.

**Screenshots**
![OUTLINE-error](https://user-images.githubusercontent.com/29619665/98285135-1ae3f780-1fc8-11eb-81d7-81b6d4a240fb.png)

**Desktop (please complete the following information):**
- Browser: Microsoft Edge
- version : Version 86.0.622.61 (Official build) (64-bit)

**Comment by tommoor** [comment]
Hi, Is this self hosted or cloud hosted Outline ? 
If self hosted which version are you running?

**Comment by MatheusRV** [comment]
I think this issue is already solved, at our wiki (self hosted) no one reported this error in last 3 months.

**Comment by kuldip-barot** [comment]
> I think this issue is already solved, at our wiki (self hosted) no one reported this error in last 3 months.

Yes, it seems that the issue is resolved now. I guess someone has updated the Outline version since I'm not facing the issue again.
