### ISSUE TITLE
Read only users should not be able to Publish to internet/share a document

### ISSUE THREAD

**Issue by amitjindal** [outline/outline#1636]
When I have assigned a read only user to private collection. That read only user should not be able to change share permission of the document as it is read only. This is a serious problem because this allows users who should have view only rights are able to change it.
Ideally there should be a "Allow share" for whole collection that only admin can change.

**To Reproduce**
1. Create a private collection.
2. Assign a read only user to collection.
3. Login as that read only user.
4. Go to a document and click share.
5. Toggle "Publish to internet". It works. This should not work.

**Expected behavior**
Publish to Internet should not be changed by read only user. If the document is shared only a link to that share should be visible. Else it should warn to ask someone with editing rights to allow share.

**Screenshots**
Not needed. Its easy to check.

**Outline (please complete the following information):**
- Install: getoutline.com
- Version: N/A

**Desktop (please complete the following information):**
 - OS: MacOSx Catalina
 - Browser Opera
 - Version 72.0.3815.186

**Comment by tommoor** [comment]
Hi @amitjindal  – this makes sense to me, thanks for filing.
