### ISSUE TITLE
Use pm2 for process management

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1640]
Currently the default `yarn start` runs plain old `node`. It would be wise to have a more resilient default in the form of a process manager that can recover from application crashes.

**Comment by rjsgn** [comment]
Interested in this task. Does this concern just the start command in package.json or the Dockerfile too? @tommoor

**Comment by tommoor** [comment]
Dockerfile runs `yarn start` so should only be the package json that needs updating

**Comment by rjsgn** [comment]
#1686 Created PR
