### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1646]
```
ResizeObserver loop limit exceeded
  at ? (/doc/-G2u8HBclOx/edit:0:0)
```

**To Reproduce**
1. Sentry Log Level

**Expected behavior**
No Error

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
![image](https://user-images.githubusercontent.com/23284276/98824968-b46d3800-2412-11eb-844b-c892c73125cd.png)

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: 0.49.0

**Comment by aam1r** [comment]
Are you using any Chrome Extensions?

**Comment by tommoor** [comment]
This error can be safely ignored, I'll add a suppression rule so that it doesn't end up in Sentry

https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded#50387233
