### ISSUE TITLE
making a new document collapses the left hand navigation state

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#1654]
1. open up several document trees in the left navigation
2. create a new document and save it
3. the state will have collapsed in the left nav.

This can be construed as acceptable behavior, but I don't think it was by design. When editing a doc instead of creating for instance, the left nav state remains intact.

**Comment by tommoor** [comment]
This might be because creating a document goes via a `/new` route 🤔

**Comment by thenanyu** [comment]
still worth examining I think

**Comment by iamsaumya** [comment]
The loss of the state was also happening when I would import a `.docx` file twice with the same title and content.

**Comment by iamsaumya** [comment]
Is this issue got resolved somehow? I'm unable to reproduce it at my end.

**Comment by tommoor** [comment]
You know, it might have – i did make the collection less finicky about collapsing itself a month or so back, I didn't have this issue in mind but it seems to have addressed it :)
