### ISSUE TITLE
cmd+shift+p for publish does not pipe out of the editor

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#1655]
1. create a new document
2. focus the editor, type some characters then try the keyboard shortcut for publish
3. the signal does not make it into the app

interestingly, cmd+enter while the title section is focused publishes as well as saves. it's unclear if this is intentional

**Comment by tommoor** [comment]
It seems it doesn't work in the title, is that what you're seeing?

**Comment by thenanyu** [comment]
> It seems it doesn't work in the title, is that what you're seeing?

The title seems to have the wrong mapping — cmd+shift+p doesn't seem to publish but...

> interestingly, cmd+enter while the title section is focused publishes as well as saves. it's unclear if this is intentional
