### ISSUE TITLE
Log on the settings page disappeared

### ISSUE THREAD

**Issue by themarketwizard** [outline/outline#1657]
After upgrading to 0.50 from 0.47
I manually added the domain column
```
ALTER TABLE public.teams
     ADD COLUMN domain character varying(255);
ALTER TABLE public.teams
     ADD CONSTRAINT teams_domain_key UNIQUE (domain);
```
But the Log on the settings page disappeared

---

When I visit the article:
POST https://wiki.marketwizards.cn/api/shares.info 404 (Not Found)

When I visit the deleted article:
POST https://wiki.marketwizards.cn/api/shares.info 404 (Not Found)
POST https://wiki.marketwizards.cn/api/views.list 403 (Forbidden)

Is this normal?

**Comment by tommoor** [comment]
**I manually added the domain column**

Please don't manually edit the database, there are migrations included and instructions to run them:
https://github.com/outline/outline#production

**POST https://wiki.marketwizards.cn/api/shares.info 404 (Not Found)**

This is normal for a document that hasn't been shared or is deleted yep.

**POST https://wiki.marketwizards.cn/api/views.list 403 (Forbidden)**

This may be a bug, will look into it.

**But the Log on the settings page disappeared**

This feature was removed in version `0.49.0`

**Comment by tommoor** [comment]
I filed as two new issues, thanks:

https://github.com/outline/outline/issues/1659
https://github.com/outline/outline/issues/1658

**Comment by themarketwizard** [comment]
Thank you very much for your answer!

After upgrading to 0.50 from 0.47
I encountered this problem, so I manually changed the database
```
column "domain" does not exist 
```
So, should I re-run when upgrading?
```
yarn sequelize:migrate
```

**Comment by tommoor** [comment]
Yes, `yarn sequelize:migrate` should be run whenever the database changes, it's safe to do it after every release. 

Now that you manually added the column it will fail so the column will need to be manually removed first. Hope this helps!

**Comment by themarketwizard** [comment]
Thank you very much
