### ISSUE TITLE
Change response of shares.info response for unshared document 

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1658]
It seems that this request being a 404 for unshared documents is confusing and has been reported as a bug on more than one occasion. 

Instead we should make it a `200` or `204` with an empty response.

**Comment by iamsaumya** [comment]
I'll get this done.

**Comment by iamsaumya** [comment]
Should the http error function be `DocumentNotSharedError` or `FileNotSharedError`?

**Comment by tommoor** [comment]
I think errors should be reserved for non-success codes, and a success response can be constructed inline in the controller method instead?
