### ISSUE TITLE
Scrollbar and Scrollable Shadow not visible on scrollable table element

### ISSUE THREAD

**Issue by PhilReinking** [outline/outline#1665]
The scrollbar should appear on hover when a table is scrollable. It is not.

Also the scrollable wrapper should have a shadow on the right side, to indicate that it has more scrollable content. The shadow is not there.

**To Reproduce**
1. Check out the latest version 0.50
2. Create a table that has overflow-x content
3. Scroll the table

**Expected behavior**
Scrollbar and shadow should be visible when hovering the table

**Screenshots**
<img width="794" alt="CleanShot 2020-11-19 at 15 33 38@2x" src="https://user-images.githubusercontent.com/2592996/99679773-9dff5600-2a7c-11eb-8904-7160e5e03982.png">

**Outline (please complete the following information):**
- Install: self hostest
- Version: 0.50.0

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by PhilReinking** [comment]
@tommoor not sure if this has something todo with some kind of minifying/compression plugin in the build process, but I could not find a failure in the outline/rich-markdown-editor repo. It seems to work there, but not in the outline/outline build.

**Comment by tommoor** [comment]
Thanks Phil, that's frustrating – I think it's because the new theme properties are missing inside of Outline. That was a mistake on my part

**Comment by PhilReinking** [comment]
Ah okay. Let me know if I should fix that in this repo :)
