### ISSUE TITLE
Failed to import Markdown: application-octet stream not supported.

### ISSUE THREAD

**Issue by zpuckeridge** [outline/outline#1675]
When attempting to re-upload a markdown file, some browsers will choose to send the file as an `application/octet-stream` which is not in the list of allowed mime types in outline. To properly fix this, we need to allow `application/octet-stream` and pass the file buffer to a tool like `mmmagic` to then decode the mime type from the buffer.

**To Reproduce**
1. In Chrome click on the "..." next to any collection.
2. Click the "Import Document" button
3. In the file selector, change the allowed filetypes from the list to "All files"
4. Click on a markdown file
5. Click upload

**Expected behavior**
The markdown file would be parsed and added to the collection

**Actual Behaviour**
Error message that says "File application/octet-stream not supported"

**Outline:**
- Install: self-hosted & getoutline.com
- Version: 0.50.0 1ce01fa9364db054da087764561962df4b30da82

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome, Firefox
 - Version: 86.0.4240.198 64bit, 82.0.2 (64-bit)

**Comment by tommoor** [comment]
Hey @zpuckeridge – thanks for filing, I'm unable to reproduce with those steps on macOS so it may be a function of the specific file or Windows OS. Perhaps you could provide the problematic file – you could email directly to hello@getoutline.com too.

**Comment by zpuckeridge** [comment]
G'day @tommoor - I've gone ahead and attempted to replicate with Chrome on MacOS and was greeted with the same error. 

I was not able to upload the MD file using Safari on MacOS Big Sur (Beta) as it was not possible to select the file.

<img width="777" alt="Import to Outline" src="https://user-images.githubusercontent.com/37718916/100312805-f72c3400-2ffe-11eb-98d2-4cf6bc52f1b1.png">

The MD file was exported from Outline as I'm currently in the process of moving from a paid instance to a self-hosted instance.

I've gone ahead and emailed one of the offending files to hello@getoutline.com now.

Cheers!

**Comment by tommoor** [comment]
My guess is that it has to do with which applications are installed for the OS to understand which mimetype the extension maps to.

It seems reasonable that we can have unknown mimetypes _attempt_ to parse the file as markdown, however it will be difficult to know if the result is reasonable or not purely within code
