### ISSUE TITLE
context menu for child documents only displays the "history" action

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#1688]
When parent is focused
![image](https://user-images.githubusercontent.com/427579/100568250-919aaa80-327f-11eb-9278-14d67852cabe.png)

When child is focused
![image](https://user-images.githubusercontent.com/427579/100568273-a9722e80-327f-11eb-9dd8-2a6270a3cc62.png)

**Comment by tommoor** [comment]
Weird, indicates the policy is missing – this on `develop` I take it?

**Comment by thenanyu** [comment]
yeah - repro'd in prod
