### ISSUE TITLE
Images copied from a page are deleted along with the original page (image reference counting?)

### ISSUE THREAD

**Issue by reidab** [outline/outline#1709]
When content is copied from one page to another that contains images and then then original page is deleted, the images are deleted from S3.

**To Reproduce**
1. Create `Page 1`, insert an image.
2. Select all of the content of `Page 1` and copy to the clipboard
3. Create `Page 2`, paste that content
4. Delete `Page 1`
5. View `Page 2` and see a broken image.

**Expected behavior**
Image content would be tracked based on how many pages reference a given image, or each page that contains an image would get its own copy of the image. Image copy/paste would detect internally-hosted images instead of copying the HTML directly to the new page.

**Screenshots**

<img width="764" alt="image" src="https://user-images.githubusercontent.com/13192/101452180-2e91bf00-38e2-11eb-9c84-a35583e2d4bc.png">

**Outline (please complete the following information):**
- Install: tested on both getoutline.com and a self hosted instance
- Version: 0.50.0

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 14.0.1

**Comment by tommoor** [comment]
Great find, thanks

**Comment by tommoor** [comment]
It looks like we can use the existing search index to find if any other documents contain the attachment before deleting it, this makes things simpler and avoids the need to do reference counting, `documentId` on attachment just becomes the first place it was uploaded.
