### ISSUE TITLE
docker-compose fails to start

### ISSUE THREAD

**Issue by Wundark** [outline/outline#1724]
I think this is caused by `nodemon` being in the devdependencies, but the dockerfile only pulls production dependencies. 

**To Reproduce**
1. `docker-compose up`

**Expected behavior**
Containers should start without error

**Actual behavior**

```
outline_1   | yarn run v1.22.5
outline_1   | $ nodemon --exec "yarn build:server && yarn build:i18n && node build/server/index.js" -e js --ignore build/ --ignore app/
outline_1   | /bin/sh: nodemon: not found
outline_1   | error Command failed with exit code 127.
outline_1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tommoor** [comment]
`nodemon` is a dev dependency, it looks like you're trying to run the development commands on the production docker container
