### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated

### ISSUE THREAD

**Issue by prodigerati** [outline/outline#1726]
New install on ubuntu 20 vm. Running production pm2 with slack and S3 storage.

I am having problems with images saving during edits. Below is in the pm2 log:

` (node:1365) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. `

Honestly, I'm not entirely sure the 2 issues are related. Is there any documentation or additional logs you can point me to for troubleshooting issues when trying to save images?

Thanks,

**Comment by tommoor** [comment]
Hi, yes this is a warning not an error and is unrelated. You should look for errors in the logs on the client and/or server, double check your S3 environment variables – it will almost definitely be a mistake in the configuration.

**Comment by tommoor** [comment]
Closed because the `DeprecationWarning` you reported has been addressed, but feel free to drop any further details on the problems with saving images you're having in here.
