### ISSUE TITLE
(Other) Shortcuts not working for Windows

### ISSUE THREAD

**Issue by Snuupy** [outline/outline#1745]
Ctrl-Enter/Ctrl-Shift-P doesn't work on Windows.

This bug may be related to https://github.com/outline/outline/issues/525.

**To Reproduce**
1. Be on a Windows machine (I'm on Windows 10)
2. Create a new doc
3. type something in, like "test"
4. attempt to save page using `Ctrl+Enter`, or publish via `Ctrl-Shift-P`
5. see that it does not publish, save, or save draft

**Expected behavior**

Publish, save, and save draft shortcuts should work in a document.

**Screenshots**

![image](https://user-images.githubusercontent.com/964538/103097994-39816a80-45d7-11eb-9091-f8defd9b4bdc.png)

Instead of publishing, I get a print dialog for example when I press `Ctrl-Shift-P`

**Outline (please complete the following information):**
- Install: self-hosted
- Version: v0.51.0 - https://github.com/outline/outline/commit/574fcc4bb337243178a9160f01008f64e11d6e38

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87

**Comment by Snuupy** [comment]
Hi @tommoor, could you please reopen this issue? `Ctrl+Enter` still does not work when you edit documents. This is on v0.52.

Steps to reproduce:
1. create a document, publish it
2. edit the document, change something
3. hit ctrl+enter, notice that it does not save.

I can confirm that Ctrl-Shift-P works now to publish a new document.

**Comment by tommoor** [comment]
Gotta catch em all
