### ISSUE TITLE
Cannot delete templates or archived documents

### ISSUE THREAD

**Issue by Maronato** [outline/outline#1746]
Deleting templates and archived documents does not work. They disappear for a brief moment from the UI, but reappear when reloading the page.

I've tried to find the source of the bug and discovered that the following assignment:
https://github.com/outline/outline/blob/ea57cef89c00792a7edb1184383d91eab5bebf60/server/models/Document.js#L663
does not seem to have any effect when deleting templates and archived documents. After the assignment, the value continues to be `null` inside the transaction.

**To Reproduce**
Delete a template or archived document from the UI.

Or run the following unit tests:
```js
test("should soft delete templates", async () => {
  let document = await buildDocument({ template: true });
  let user = await buildUser();

  await document.delete(user.id);

  document = await Document.findByPk(document.id, { paranoid: false });
  expect(document.lastModifiedById).toBe(user.id);
  expect(document.deletedAt).toBeTruthy();
});
test("should soft delete archived", async () => {
  let document = await buildDocument({ archivedAt: new Date() });
  let user = await buildUser();

  await document.delete(user.id);

  document = await Document.findByPk(document.id, { paranoid: false });
  expect(document.lastModifiedById).toBe(user.id);
  expect(document.deletedAt).toBeTruthy();
});
```

Both of them fail at `expect(document.deletedAt).toBeTruthy();`.

**Expected behavior**
Templates and archived documents should be deletable.

**Screenshots**
![CleanShot 2020-12-24 at 14 46 46](https://user-images.githubusercontent.com/19658460/103101545-e8816e80-45f6-11eb-8a15-43f9b34644b4.gif)

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: e966eb8c9abcfcf3f9a5a8f44feb22624b2a785e

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 85.0b2

**Comment by tommoor** [comment]
Thanks for the great report, this seems like a fairly critical fix – will look into it today
