### ISSUE TITLE
Tab in editor doesn’t consistently work

### ISSUE THREAD

**Issue by ShravanSunder** [outline/outline#1750]
Tab doesn’t always indent, it seems to jump to other elements.  Sometimes after creating a bullet it indents.  Additionally, shift tab seems to indent as well

**To Reproduce**
1. Go to default outline document
2. Click on edit
3. Scroll down to different texts and try to tab

I’ve attached a video to show the issue.  

https://user-images.githubusercontent.com/5294949/103139102-00183000-46a7-11eb-8cd2-460394ee548b.MP4

**Expected behavior**
in the editor i would expect the editor to not jump to other elements in the dim when tab is pressed. The tab button should indent elements when editing in the editor. 

**Screenshots**
I’ve attached a movie

**Outline (please complete the following information):**
- Install: [getoutline.com
- Version: commit sha if self hosted]

**Mobile (please complete the following information):**
 - Device: ipad
 - OS: iOS 14
 - Browser safari

**Comment by ShravanSunder** [comment]
Perhaps this belongs to the editor repo?

**Comment by tommoor** [comment]
Could you explain more about "I would expect the editor to tab"? 

What behavior exactly are you expecting? Thanks

**Comment by ShravanSunder** [comment]
> Could you explain more about "I would expect the editor to tab"?
> 
> What behavior exactly are you expecting? Thanks

I updated the expected behaviour.

**Comment by tommoor** [comment]
I see, indented text isn't something the editor supports right now – I recommend using a quote block or a notice block if you need to call out text as different.
