### ISSUE TITLE
Not able to add a link in a cell table

### ISSUE THREAD

**Issue by matbrgz** [outline/outline#1757]
When you try to add a link selecting the entire cell of a table you can't add the link, but when you select only the text you can.

**To Reproduce**
1. Go to Doc Editor
2. Create a Table and Insert Some Sample Text
3. Select the entire cell
4. Try to add a link in this cell

**Expected behavior**
Possible to add the link selecting only the text and the cell

**Outline (please complete the following information):**
- Install: SelfHosted
- Version: 0.50

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 87

**Comment by tommoor** [comment]
At a semantic level this makes sense, you have the table cell selected and a table cell cannot be linked. But from a UX point of view I understand the desire to have it just link the text, it's sometimes easier to select the cell itself.

**Comment by MatheusRV** [comment]
At this moment you can create a link in the cell, but you can't redirect to any place. The anchor is created and the href is empty.

**Comment by MatheusRV** [comment]
Using the editor today I feel that the error is double click select the entire cell, not the text, this means you can select the cell only when you click on the borders or empty space. This is just an opinion. For me just implement the easiest way, to avoid bugs for newbie outline users.

**Comment by matbrgz** [comment]
This bug wasn't fixed yet.
