### ISSUE TITLE
Allow sorting collections in sidebar

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1759]
### Why

Now that document drag and drop is complete, as an admin I should be able to choose the order of collections in the sidebar in the same manner.

### How

Probably a new `collections.move` endpoint to match `documents.move` and a new corresponding policy as well that only allows admins in a first version.

To avoid having to pass the entire list of collections back to the server we can use the concept of fractional indexing. I'll link the library here to achieve this soon.

**Comment by iamsaumya** [comment]
Hey Tom, I'd like to work with you on this. Could you link me to necessary issues for context, please?

**Comment by tommoor** [comment]
I will update once the fractional indexing library that's needed is open sourced this week

**Comment by tommoor** [comment]
Update, it's here: https://github.com/goabstract/fractional-index

**Comment by iamsaumya** [comment]
Noted. Will start working day after tomorrow when my last exam ends.

**Comment by iamsaumya** [comment]
Hey Tom,
I referred #1717 to understand how the document drag and drop was achieved. Feels solid. However, I have a few doubt with me.

What will happen when somebody has a private collection which is not visible to admin?

**Comment by tommoor** [comment]
Good edge case – so in that instance the frontend might submit an index to the backend that already exists on a private collection that the user doesn't have access to?

In this case it should act the same as if two people submitted the same index at the same moment – we can generate a new index on the server if it clashes with an existing index by just budging it below.
