### ISSUE TITLE
Inconsistent display between editing and history

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1769]
**To Reproduce**
1. Edit a Doc
2. Go to History

**Expected behavior**
Every edit must appear in history

**Screenshots**
![image](https://user-images.githubusercontent.com/23284276/103680178-89abe580-4f64-11eb-835c-f2606278c4dd.png)

**Outline (please complete the following information):**
- Install: SelfHosted
- Version: 0.50.0
- 
**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Browser Chrome
 - Version 87

**Comment by tommoor** [comment]
There are several types of modification that do not create a revision – revisions only track textual changes, my guess is that the document was archived/restored/moved, any of the above would result in the timestamp updating without a revision.
