### ISSUE TITLE
Text garbled when downloading document on iOS

### ISSUE THREAD

**Issue by RickCogley** [outline/outline#1791]
Added Japanese to the default "our editor" file, and on iOS, it is garbled on download. It is similar in appearance to when you select the wrong encoding in a text file. 

**To Reproduce**
1. Add Japanese to a document
2. In the ... menu, select download
3. Observe the Japanese is garbled

**Expected behavior**
The Japanese should not be garbled. Perhaps the encoding is not Utf-8?

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

![image](https://user-images.githubusercontent.com/512328/104090811-74182200-52bc-11eb-83aa-a0b887f0938a.jpeg)

**Outline (please complete the following information):**
- Install: [getoutline.com]
- Version: [commit sha if self hosted]

**Desktop (please complete the following information):**

**Mobile (please complete the following information):**
 - Device: [iPhone XS, iPad ]
 - OS: [iOS 14.3]
 - Browser [chrome]

**Comment by tommoor** [comment]
Agreed that this is an encoding issue of sorts, I'm guessing this is a Safari/iOS issue as I can't reproduce on Chrome desktop. Note that Chrome on iOS is just Safari in a skin.

**Comment by RickCogley** [comment]
hi @tommoor yes, it works for me on desktop. This occurs only on iOS, so far as I can test.

**Comment by tommoor** [comment]
In my testing on iOS I get a "View" and "Download" option when clicking "Export" in Outline, If I choose "Download" and then open the file from there it appears fine, but the view option is corrupted as you described

**Comment by RickCogley** [comment]
hi @tommoor , when I am in a single doc in iOS on iPhone (in Chrome), and click the ellipsis ... menu, I see only "Download" as an option. I don't see any "Export" selection at all. If I tap the ... menu next to a collection, I do see an export menu, but if I tap it on mobile, nothing happens in particular that I can see. I know it's supposed to make a zip, but, I don't see the zip anywhere, such as in the Files app.

**Comment by tommoor** [comment]
Sorry, I did mean "Download" in Outline, and then iOS gives an additional "view/download" modal afterwards.

**Comment by tommoor** [comment]
Honestly I think this is a Safari bug, it should be interpreted correctly as UTF-8 according to all documentation 🤷

**Comment by RickCogley** [comment]
Hi @tommoor, in Chrome, the modal is bypassed and the file is just displayed right in the chrome window. With the garbled text. FYI
