### ISSUE TITLE
Move collection description editing inline

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1802]
Currently editing the description of a collection happens in the "Edit" modal with name/icon/color etc. Because the description is a rich text area this doesn't work too well and unnecessarily disconnects the contents from where it appears – it should be more like a document. I suggest the following:

- Add an "Edit description…" option to the collection menu (ensure policies enable)
- Have it navigate to collection/<uuid>/edit
- Show the collection as normal except with the description area editable, focused, and with a "Save" button (design needed?)
- Remove the description from the "Edit collection" modal

**Comment by rubenmoya** [comment]
I was having a look at this issue to give it a try and found out that using `/edit` is going to conflict with the `recent`, `old`,  and `alphabetical` urls used by the tabs.

If I click on `old`, then try to edit the description it will change the order of the documents

**Comment by matbrgz** [comment]
Please use same editor of the document.
