### ISSUE TITLE
Newly published documents should go to the top of a manually sorted collection

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1805]
Currently they go to the bottom

**Comment by rubenmoya** [comment]
Hi! I've been having a look and I see two approaches to this, either sending an `index` in the `documents.update` or changing the logic of the `Document.publish` method [here](https://github.com/outline/outline/blob/1fd2ec31fd9cba2d5d6c090db2ea79d6875fede7/server/models/Document.js#L582) to add the index depending on the collection shorting.

What do you think?

**Comment by tommoor** [comment]
Adding the index in `publish` sounds like a good solution, It would be fine to add it regardless of sorting at this time – and I _guess_ it could always be `0`? It might be that simple.

**Comment by tommoor** [comment]
closed by eeb7650941f4ac301b768a3aec7cbb610e0cf986
