### ISSUE TITLE
GitHub discussions

### ISSUE THREAD

**Issue by justinhandley** [outline/outline#1809]
We have migrated the community from Spectrum to GitHub discussions, if you were looking for the answer to a question that was previously posted on Spectrum – please feel free to repost here.

_Originally posted by @tommoor in https://github.com/outline/outline/discussions/1368_

But your github discussions are locked except to maintainers?

I am experiencing a 405 error and found a previous issue, went to spectrum where you referenced the person to go, that referenced them back here.  So I'm opening a new issue as there doesn't seem to be another way to get support?

**Comment by tommoor** [comment]
Hi @justinhandley – it depends, for problems with self hosting yes this is the best place to get support. If you're using the cloud hosted version we offer support at [hello@getoutline.com](hello@getoutline.com).

**Comment by justinhandley** [comment]
Hey @tommoor - OK, how strange.  I wish I had a screenshot.  Earlier today on Discussions I just saw a gray box saying 'Discussions are locked'  I went back to check and can see them.

Thanks,
Justin
