### ISSUE TITLE
Sidebar not collapsing (until click outside)

### ISSUE THREAD

**Issue by matbrgz** [outline/outline#1822]
**To Reproduce**
1. Go to "<"
2. Click on it.
3. See error

**Expected behavior**
Minimize or expand sidebar

**Screenshots**
![captured](https://user-images.githubusercontent.com/23284276/105032773-009daf80-5a36-11eb-88fd-79d23a325681.gif)

**Outline (please complete the following information):**
- Install: SelfHosted
- Version: 0.52.0

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 87

**Comment by tommoor** [comment]
This is by design, the sidebar stays open while it has focus – I can see how it's confusing when toggling though, will try and improve for next release.
