### ISSUE TITLE
Ability to prevent/undo accidental drag and drop in sidebar

### ISSUE THREAD

**Issue by matbrgz** [outline/outline#1823]
**To Reproduce**
1. Drag Document Accidentally
2. Drop in Misplace
3. See error

**Expected behavior**
Enable or Disable document Drag & Drop in Order menu

**Screenshots**
![image](https://user-images.githubusercontent.com/23284276/105033089-68ec9100-5a36-11eb-837e-41c5203aa87c.png)

**Outline (please complete the following information):**
- Install: SelfHosted
- Version: 0.52.0

**Comment by tommoor** [comment]
I think a reasonable alternative here would be to have a toast message with option to "Undo" the move. Note that reordering is already disabled where the user does not have write permissions.

**Comment by MatheusRV** [comment]
A toast message could work for me.

**Comment by sharmanilay** [comment]
Can i pick this up?

**Comment by iamsaumya** [comment]
Go ahead! @sharmanilay 👍🏻

**Comment by iamsaumya** [comment]
@tommoor this issue was created keeping documents in mind. Now that we have draggable collections. What are your thoughts on having this for collections as well?

**Comment by tommoor** [comment]
I think it makes sense for collections too, but I'd keep them in separate PR's. We can do it for documents and make sure the methodology is correct and once that's working nicely the collections version should be even easier.

**Comment by iamsaumya** [comment]
Hey @sharmanilay, please let us know if you are working on this issue. Thanks!

**Comment by sharmanilay** [comment]
@iamsaumya I am not currently working on this issue, you can pick this up. Thanks!

**Comment by iamsaumya** [comment]
Keep it open pls

**Comment by iamsaumya** [comment]
bump
