### ISSUE TITLE
Trash auto deletion in a self hosted environment

### ISSUE THREAD

**Issue by enzolutions** [outline/outline#1828]
Hi Guys

I am running a self-hosted version of outline a Heroku instance but looks like the auto-deletion after 30 days is not working.

<img width="449" alt="Screen Shot 2021-01-21 at 7 29 26 am" src="https://user-images.githubusercontent.com/907914/105231079-66b33f80-5bba-11eb-9c8b-a0b5969411e4.png">

Anyone can point out the command of setting that I have to enable this feature.

Kind regards

**Comment by tommoor** [comment]
- Set an environment variable `UTILS_SECRET` with a secure string of your choice
- Set up Heroku Scheduler to hit up the `utils.gc` endpoint once per day with the secret string in the query params:
   `curl https://www.myoutlineinstallation.com/api/utils.gc?token=MY_SECRET_STRING`
