### ISSUE TITLE
Forbidden Amazon S3 Images

### ISSUE THREAD

**Issue by johngeer** [outline/outline#1836]
For the hosted version of outline at getoutline.com, I've started getting 403s for the image assets on s3. These images follow the url structure:

https://s3.amazonaws.com/dev.beautifulatlas.com/...

The error it is returning says:
```
   <Code>AllAccessDisabled</Code>
   <Message>All access to this object has been disabled</Message>
```

**Comment by tommoor** [comment]
Hi John, sorry for the trouble - working on resolving this now

**Comment by tommoor** [comment]
Now resolved 🙏

**Comment by johngeer** [comment]
Thanks for fixing this so quickly!
