### ISSUE TITLE
Highlighting a hyperlink in Dark theme makes it not readable

### ISSUE THREAD

**Issue by a2tm7a** [outline/outline#1838]
The links become unreadable when highlighting them in dark theme.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
![Screenshot 2021-01-22 at 11 27 56 AM](https://user-images.githubusercontent.com/10511458/105452782-eb7a8800-5ca4-11eb-8406-b8df1d44dc31.png)

**Outline (please complete the following information):**
- Install:  self hosted
- Version: 0.52.0

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser - Brave

**Comment by tommoor** [comment]
Confirmed - thanks for filing!

**Comment by a2tm7a** [comment]
Thanks for the quick fix! :D
