### ISSUE TITLE
CORS errors when loading manifest.json behind Cloudflare Access

### ISSUE THREAD

**Issue by aam1r** [outline/outline#1850]
**To Reproduce**
1. Deploy Outline on your own self-hosted deployment
2. Use Cloudflare for DNS and point a DNS record to your Outline deployment
3. Enable Cloudflare Access

**Expected behavior**

`manifest.json` will fail to load:

![image](https://user-images.githubusercontent.com/566418/106189162-e79fa780-6175-11eb-89ac-f4a3ca077cf8.png)

**Outline (please complete the following information):**

- Install: self-hosted v0.52.0

**Similar issues:**

https://community.cloudflare.com/t/cloudflare-access-manifest-json-issues/228716

**Comment by aam1r** [comment]
The fix here is to change from:

```html
<link rel="manifest" href="manifest.json">
```

to:

```html
<link rel="manifest" href="manifest.json" crossorigin="use-credentials">
```

I did this temporarily using a Cloudflare Worker that rewrites the HTML pre-serving:

```js
addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})

async function handleRequest(request) {
  const resp = await fetch(request);
  const body = await resp.clone().text();

  return new HTMLRewriter()
    .on('link[rel="manifest"]', {
      element(elem) {
        elem.setAttribute('crossorigin', 'use-credentials');
			  console.log('Added crossorigin=use-credentials to <link>');
      }
    })
    .transform(resp.clone());
}
```

If this is an acceptable solution, I can submit a PR that fixes this in https://github.com/outline/outline/blob/f6370ccf6defe5681bab642b591cdd4b5e9670b6/server/static/index.html#L15. Let me know!

**Comment by tommoor** [comment]
Are you able to share more of the screenshot? The manifest should never be served cross-origin so I'm having trouble understanding why this change would be needed - but happy to accept a PR if proven useful.

**Comment by aam1r** [comment]
Accidentally closed it 🤦 

Related to https://github.com/outline/outline/issues/1866
