### ISSUE TITLE
getaddrinfo EAI_AGAIN outline

### ISSUE THREAD

**Issue by bejaneps** [outline/outline#1855]
Hi, recently tried to install outline on my Ubuntu 20.04 Focal Fossa server, and got stuck in step **4** of production installation, by running following command:

```
yarn sequelize:migrate --env=production-ssl-disabled
```

**

**To Reproduce**
1. Follow steps of production installation
2. Run command in step 4: `yarn sequelize:migrate --env=production-ssl-disabled`
3. Get following output:
```
yarn run v1.22.10
$ sequelize db:migrate --env=production-ssl-disabled

Sequelize CLI [Node: 14.15.4, CLI: 6.2.0, ORM: 6.3.5]

Loaded configuration file "server/config/database.json".
Using environment "production-ssl-disabled".

ERROR: getaddrinfo EAI_AGAIN outline

error Command failed with exit code 1
```

**Expected behavior**
I expected migration to run successfully, but it didn't.

**Screenshots**
I don't see need for screenshots.

**Outline (please complete the following information):**
- Install: self hosted
- Version: eeb7650941f4ac301b768a3aec7cbb610e0cf986

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Extra**

Here is my .env file content, secret keys replaced with fake ones:

```
SECRET_KEY=--------------------------
UTILS_SECRET=--------------------------

DATABASE_URL=--------------------------
DATABASE_URL_TEST=--------------------------
REDIS_URL=redis://localhost:6379

# Must point to the publicly accessible URL for the installation
URL=https://docs.nullidea.app
PORT=4000

# Optional. If using a Cloudfront distribution or similar the origin server
# should be set to the same as URL.
CDN_URL=

# enforce (auto redirect to) https in production, (optional) default is true.
# set to false if your SSL is terminated at a loadbalancer, for example
FORCE_HTTPS=false

ENABLE_UPDATES=true
DEBUG=cache,presenters,events,emails,mailer,utils,multiplayer,server,services

# Third party signin credentials (at least one is required)
SLACK_KEY=--------------------------
SLACK_SECRET=--------------------------

# To configure Google auth, you'll need to create an OAuth Client ID at
# => https://console.cloud.google.com/apis/credentials
#
# When configuring the Client ID, add an Authorized redirect URI:
# https://<your Outline URL>/auth/google.callback
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# Comma separated list of domains to be allowed (optional)
# If not set, all Google apps domains are allowed by default
GOOGLE_ALLOWED_DOMAINS=

# Third party credentials (optional)
SLACK_VERIFICATION_TOKEN=PLxk6OlXXXXXVj3YYYY
SLACK_APP_ID=A0XXXXXXX
SLACK_MESSAGE_ACTIONS=true
GOOGLE_ANALYTICS_ID=
SENTRY_DSN=

# AWS credentials (optional in development)
AWS_ACCESS_KEY_ID=--------------------------
AWS_SECRET_ACCESS_KEY=--------------------------
AWS_REGION=eu-west-2
AWS_S3_UPLOAD_BUCKET_URL=http://s3:4569
AWS_S3_UPLOAD_BUCKET_NAME=--------------------------
AWS_S3_UPLOAD_MAX_SIZE=26214400
AWS_S3_FORCE_PATH_STYLE=true
# uploaded s3 objects permission level, default is private
# set to "public-read" to allow public access
AWS_S3_ACL=public-read

# Emails configuration (optional)
SMTP_HOST=--------------------------
SMTP_PORT=--------------------------
SMTP_USERNAME=--------------------------
SMTP_PASSWORD=--------------------------
SMTP_FROM_EMAIL=--------------------------
SMTP_REPLY_EMAIL=--------------------------

# Custom logo that displays on the authentication screen, scaled to height: 60px
# TEAM_LOGO=https://example.com/images/logo.png

# See translate.getoutline.com for a list of available language codes and their
# percentage translated.
DEFAULT_LANGUAGE=en_US
```

I skipped step **4** and tried step **5** by running following command:

```
NODE_ENV=production pm2 start ./build/server/index.js --name outline
```

Outline server ran successfully, but page was empty with no content in it.

**Comment by tommoor** [comment]
Seems like the codebase cannot establish a database connection, where is your database hosted? You'll have to check standard stuff like hostname, port, firewalls etc. This error is related to your networking, not the Outline codebase:
https://www.codingdefined.com/2015/06/nodejs-error-errno-eaiagain.html

**Comment by bejaneps** [comment]
Thanks for help, issue was in Postgresql password, it contained special characters which were giving this error ... 

Although, I'm getting another issue, after successfully starting outline server, page is blank with no contents, what can be the issue ?

Here is live link to check it: https://docs.nullidea.app

**Comment by tommoor** [comment]
It's an internal server error, you can see in the network inspector so the server-side logs should tell the tale

**Comment by axelsimon** [comment]
For anyone running into this issue (`getaddrinfo EAI_AGAIN www.googleapis.com` in our case, when trying to use Google login), EAI_AGAIN is "A temporary failure in name resolution occurred.", which in our case was correlated with cloud provider network issues.
Once those were resolved, the error went away and users were able to log in with Google login again.
