### ISSUE TITLE
Update hotkeys to use a hooks-based solution

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1856]
One of the items keeping us in a component-based world is usage of `react-hotkey`, we should remove it and update to something with a modern API like https://johannesklauss.github.io/react-hotkeys-hook/

There are only 5 components using this right now, so it should be a manageable PR to convert them to functional.

**Comment by iamsaumya** [comment]
Hey, Should I take over this or wait for my other PR to get resolved first?

**Comment by tommoor** [comment]
I'm unlikely to tackle this in the coming week 👍

**Comment by iamsaumya** [comment]
Great!, this is on my plate now :smile: .
