### ISSUE TITLE
Import md file gives error "r is not defined" or, nothing, depending on where you import from

### ISSUE THREAD

**Issue by RickCogley** [outline/outline#1874]
I cannot import markdown files to a collection. 

**To Reproduce**  

On the ellipsis button on the collection in the sidebar, if you select an md file and import document, it does nothing. If you use the ellipsis button on the upper right, if you select an md file and import document, an error appears on the lower left "r is not defined". 

I am using Firefox 85.0 (64-bit) on MacOS Big Sur 11.2.

**Expected behavior**

Importing md files should work, and the imported file should appear in the collection. 

**Screenshots**

The error disappears too quickly, sorry. It's a white text on black popup, that appears on the lower left. 

**Outline (please complete the following information):**
- Install: [getoutline.com]

**Desktop (please complete the following information):**
 - OS: [MacOS 11.2]
 - Browser [Firefox]
 - Version [85]

**Comment by tommoor** [comment]
Thanks @RickCogley – the issue has been addressed

**Comment by RickCogley** [comment]
I confirm it's working! Thanks!
