### ISSUE TITLE
Page reloads when choosing "Import document" in collection menu in Firefox

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1877]
**To Reproduce**
1. In Firefox only
1. Go to '...' on a collection in the sidebar
1. Click on "Import Document"
1. Page reloads

**Expected behavior**

- Import dialog shows and page does not reload, as chrome and safari

**Comment by tommoor** [comment]
Turns out this affects some of the other menu items too, a pattern isn't clear yet – or why it's only FF.

**Comment by iamsaumya** [comment]
I had no success debugging the issue. How do you usually approach to cross browsers bugs?
