### ISSUE TITLE
Not working "document updated" email notifications on v0.52.0

### ISSUE THREAD

**Issue by jay-lee-otsk** [outline/outline#1894]
**To Reproduce**

- Condition: outline-v0.52.0
- Deployment: k8 docker based (Referred to chsasank/outline-wiki-docker-compose for docker-compose.yml)
- All other email notifications are working fine except the "document updated" event. 
- No error logs are shown regarding this bug.
- When I used v0.51.0, "document updated" email notification worked! 

**Expected behavior**
Receive a notification when a document I created is edited

**Screenshots**
N/A

**Outline (please complete the following information):**
- Install: self-hosted in GKE
- Version: v0.52.0

**Comment by tommoor** [comment]
Hi, I'm not sure why this would be – the cloud service is using v0.52+ and these notifications have continued going out without issue. The change from 51->52 is that they are debounced by 5 minutes, are you accounting for that?

**Comment by jay-lee-otsk** [comment]
Hi tommoor. Thanks for your prompt response. 
I already checked the fact that emails for document updated notifications are debounced by 5 minutes when using v0.49+, but even though after 5 minutes the email for document updated is still not working. 
Still, I doubt whether it is only my environmental configuration issue or not, then could you please advise how I should configure differently. 

Below is what I performed so far: 
-. Checking in v0.51.0: Emails for document updated notifications worked well. 
-. Checking in v0.52.0: Other email notifications are working fine, but only "documents-update" event case is not working. 

When migrating from v0.51 to v0.52, is there anything to configure additionally? 
Please note that I am not questioning about database migrations, but about other architectural considerations(redis, minio, etc)

**Comment by tommoor** [comment]
I looked through the diff and can't see anything, v0.53.1 is publishing now – please give it a try once available and see if it resolves your issue.

**Comment by jay-lee-otsk** [comment]
Thanks for the release info of yesterday. I have tried v0.53.1, and it resolved the issue. 
Kindly let me close this ticket.
