### ISSUE TITLE
Home title improvements

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1898]
It would be nice to make the homepage a little friendlier, this plus "pin to home" documents beneath would be really quite nice. To achieve this we'd need to track when the user last hit the homepage, probably in localstorage and we can then compare this date against the first page of results – if the data is older than the first entire page then "20+ docs" would be fine.

### Mock

![image](https://user-images.githubusercontent.com/380914/108301443-da635080-7156-11eb-9668-9ec4aa2edd81.png)

**Comment by MDXDave** [comment]
How about the possibility to select an document that is shown as the homepage? 
It could be displayed with an additional tab or above the tab bar.

**Comment by tommoor** [comment]
I think we want to iterate the homepage towards being a useful dashboard rather than just another page of content, which is what the entire rest of the application is. But that doesn't mean there couldn't be an area for some custom text – first we'll implement documents that can be "pinned to home", I think this will cover 99% of use cases that overlap with having an actual document as the homepage.

**Comment by tommoor** [comment]
I tried this out (the above design) and realized that the "x docs updated" is potentially anxiety inducing, and on larger teams just isn't that important. I'm closing this out, we have separate issues for "pin to home" etc
