### ISSUE TITLE
"Invite People" button should be hidden in settings for non-admins

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1902]
Currently it's visible, also disable in API policies.

In the future we can have a setting for allowing any user to invite others

**Comment by matbrgz** [comment]
We should start to design a Role Based Acces, but in some cases public wiki will be awesome..

**Comment by tommoor** [comment]
> We should start to design a Role Based Access

Perhaps, I'll keep it simple as long as possible – every complication that's added to access control slows down the application too.
