### ISSUE TITLE
Cannot attach images. Error "Validation isIn on acl failed (acl)" on api/attachments.create

### ISSUE THREAD

**Issue by erickne** [outline/outline#1907]
**To Reproduce**
1. Go to document (new or editing)
2. Click on body text
3. Attach and image
4. See error **Sorry, an error occurred uploading image**

**Expected behavior**
We deployed Outline in out Docker Portainer with Plesk Hosting and Nginx Reverse Proxy.

Everything works fine, except attaching images in documents. But we can change our profile picture and company logo (seems the same API route).

**Screenshots**

![image](https://user-images.githubusercontent.com/1703652/108567496-1af1d400-72e7-11eb-9430-15330c5dc2a6.png)

Response
```json
{ok: false, error: "", message: "Validation isIn on acl failed (acl)"}
```
![image](https://user-images.githubusercontent.com/1703652/108567680-72903f80-72e7-11eb-969e-9250dd639404.png)

**Outline (please complete the following information):**
- Install: [self hosted]
- Version: [docker:latest]

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [88 x64]

**Comment by tommoor** [comment]
Looks like `AWS_S3_ACL` may be set to something other than `public-read` or `private`

**Comment by genotrance** [comment]
If you are running into this issue while using local storage and have done everything else, make sure `AWS_S3_ACL=private` in your environment. I blanked it out and uploads failed with this issue.
