### ISSUE TITLE
v0.53.0 breaks attachments url (Minio)

### ISSUE THREAD

**Issue by andrej-pavlov** [outline/outline#1910]
**To Reproduce**
- All images in documents are 404

If I put the image url directly into the browser address bar, it gets redirected to `s3.local.amazonaws.com/...` instead of my minio server url. Seems that AWS_S3_UPLOAD_BUCKET_URL isn't respected anymore. With rollback to 0.52.0 everything is working again. 

Thank you!

**Comment by tommoor** [comment]
Yes this is a known issue and why `v0.53.1` was released the same day 😄

**Comment by andrej-pavlov** [comment]
Oh sorry, didn't see it as it isn't labeled as latest release. my bad 😄
