### ISSUE TITLE
Profile Photo unable to display after upgrading to 0.53.1

### ISSUE THREAD

**Issue by themarketwizard** [outline/outline#1912]
Hello,
Profile Photo unable to display after upgrading to 0.53.1, from 0.52 version
![image](https://user-images.githubusercontent.com/69380915/108602121-40600a00-73db-11eb-95f2-05788103d052.png)
my upgrade steps:
* sequelize db:migrate
* yarn install
* yarn build
* restart pm2

Thanks

**Comment by tommoor** [comment]
Hi, I will need the redacted details of all the `AWS_` config in your installation and the error in the browser console to debug further

**Comment by themarketwizard** [comment]
Hi,
this is my AWS_ config:
```
# AWS credentials (optional in development)
AWS_ACCESS_KEY_ID=xxxxxxxxxx
AWS_SECRET_ACCESS_KEY=xxxxxxxxx
AWS_REGION=xx-xxxx-x
AWS_S3_UPLOAD_BUCKET_URL=https://s3.xxxxxxxx
AWS_S3_UPLOAD_BUCKET_NAME=wiki
AWS_S3_UPLOAD_MAX_SIZE=26214400
AWS_S3_FORCE_PATH_STYLE=true
# uploaded s3 objects permission level, default is private
# set to "public-read" to allow public access
AWS_S3_ACL=private
```
I run
```
yarn start
```
But no error log

**Comment by krhougs** [comment]
It occurs to me too, the generated s3 url for avatars doesn't include authentication parameters.

**Comment by Coderhypo** [comment]
Did you build using the develop branch?
I has same issue, until I rebuilt with the main branch

**Comment by themarketwizard** [comment]
0.53.1 in the main branch, but 0.52 in develop branch

**Comment by tommoor** [comment]
- `develop` is no longer active.
- the generated s3 url for avatars doesn't include authentication parameters. This is currently expected, so they can appear outside of the authenticated area.
- Are the profile images stored as private in minio somehow? This isn't a recent change they should always have been public

**Comment by krhougs** [comment]
We currently use GCE with minio as proxy, GCE seems doesn't allow public object read without being able to listing objects publicly when using behind minio.

**Comment by manojchandrashekar** [comment]
Not sure if this helps, but I had the same problem with minio as s3. I had to set the policy on the bucket to 'download' to enable public access.

https://docs.min.io/docs/minio-client-complete-guide.html#policy
