### ISSUE TITLE
hotkeys are fired when writing in image caption

### ISSUE THREAD

**Issue by PhilReinking** [outline/outline#1922]
Typing in an image caption does not prevent hotkeys from triggering.

**To Reproduce**
1. Insert Image
2. Type something in the caption
3. Hit `d` or `t` 
4. Hotkeys get triggered and you will go to dashboard or activate search

**Expected behavior**
The hotkeys should not fire, you should be able to keep typing the caption

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: self hosted
- Version: d277d80

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave (Chrome)

**Comment by tommoor** [comment]
Thanks Phil, this was identified and fixed – https://github.com/outline/outline/commit/a3e95023dcbe4f9759b4a8471dac55c8feb1f336 – the fix will be in the next release
