### ISSUE TITLE
Slack search integration only returns results from public collections

### ISSUE THREAD

**Issue by shinyshez** [outline/outline#1925]
**To Reproduce**
1. We have collections that are private to our team
2. We have google authentication 
3. We have slack integration enabled
4. we search with /outline <search term>
5. We only get results for collections that are public, e.g. the welcome collection.

**Expected behavior**
We'd hope to have our whole wiki searched

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by tommoor** [comment]
Hey @shinyshez, this is expected behavior - if you're using Google to sign in then there is no way to know which private collections the user in Slack has access to. I'd recommend signing in with Slack instead – if you contact support we can arrange moving over.
