### ISSUE TITLE
Email login input should be larger

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1932]
Email login input should extend up to the button here, with a padding matching that above

![image](https://user-images.githubusercontent.com/380914/109684131-d3641700-7b34-11eb-8378-5fc1c2bd59d5.png)

**Comment by mtwn105** [comment]
Hi @tommoor I would like to work on this

**Comment by sharmanilay** [comment]
@tommoor Can I work on this if it is open for others to work on?

**Comment by tommoor** [comment]
It is open indeed
