### ISSUE TITLE
Optimistically show new location when drag and drop in sidebar

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1956]
When dragging an item in the sidebar there is a delay between dropping and it appearing in the right location while the API request completes. It's _just_ long enough to be disconcerting, which is okay once you get used to it but it would feel much more solid if we can optimistically update the position.

**Comment by iamsaumya** [comment]
Will tackle this for both documents and collections once #1870  is merged.

**Comment by iamsaumya** [comment]
I will be working on this soon.

**Comment by iamsaumya** [comment]
For documents, What could be the approach? Is copying the `documents.move` code with other helper functions to `app` and removing their asynchronicity a possible approach.

**Comment by iamsaumya** [comment]
I don't know how I'll do this, but please keep it open.

**Comment by iamsaumya** [comment]
shush
