### ISSUE TITLE
Release v0.54.0 migrate authentication on Self hosted installation doesn't work 

### ISSUE THREAD

**Issue by enzolutions** [outline/outline#1972]
Hi folks, 

First I want to say thank you to the maintainers for Outline as a Product which is great and also for the rest of the community.

Let me explain my issue, I was trying to migrate from version 0.53.1 to 0.54.0

**Outline (please complete the following information):**
- Install: Self-hosted [Heroku]
- Version:v0.54.0

The deploy process works in Heroku, without problems, but the applications crash, and I can't go back because the structure change and the code for version 0.53.1 don't match or work with the new structure.

When I try to run the migrations script

```node /build/server/scripts/20210226232041-migrate-authentication.js``` I got the following errors from script https://github.com/outline/outline/blob/main/server/scripts/20210226232041-migrate-authentication.js#L82:

```
serviceId 106629815691052806096 exists, for user b96ac88d-4478-4f8c-922c-dd3e4923095a
serviceId 113585736485673695751 exists, for user 80957855-e3a4-4c79-befa-16ff7f537209
serviceId 107846379410345019507 exists, for user 5685d228-c1f5-4914-8d48-00fac4a5c39e
serviceId 108101704821184916968 exists, for user 31300843-4b11-4ab4-bbfc-920e94fe5e78
serviceId 108145562443761770376 exists, for user 445caffd-80b8-4fdb-8a42-d416e38b0669
serviceId 100191673069030564446 exists, for user 24366da3-bc7f-4668-8022-df07595a1f07
serviceId 100782390040942005075 exists, for user 2f06b39a-20c7-46c8-911c-1f07b6807cf1
serviceId 100040180475101280608 exists, for user f10248db-80d4-4fec-b42e-91114a8aa916
serviceId 101211108413811319250 exists, for user d8b8fcde-70cc-45e2-9f74-49a8944c63c5
serviceId 104915645889588925961 exists, for user b48ab57c-5c29-4cd0-96e3-bbcea570f193
serviceId 109491887471551654945 exists, for user 2b065672-d485-4283-9100-396f7d4c4e4f
serviceId 113869810578869235647 exists, for user ae2e095c-8a08-4e83-bb0f-c2503506c2e2
serviceId 115787818327594248153 exists, for user 6a599c20-c987-4b08-8e11-40add4c2aad9
serviceId 100773526721550001032 exists, for user d14f98bf-5ba1-4b95-bcd2-88c4f9e56532
serviceId 108691919391177770035 exists, for user c890e6ab-efff-447b-95f9-ccf9fdbd1992
serviceId 102633264003690699696 exists, for user c44b6b91-9a01-4b3c-9533-69ce1e255704
serviceId 100522360778330628641 exists, for user 89b94e69-c6f8-4224-b2d9-33b1c96d18e7
serviceId 118231132886780399171 exists, for user 028a5e25-5976-462f-821c-df65df2360b3
serviceId 103353208725638633085 exists, for user 4a48cf73-eb1e-4b22-8869-e37be93e6372
serviceId 112927085706118264879 exists, for user 98e97fed-e5d3-4269-8de9-1216cfacaf2e
serviceId 118041341268606120386 exists, for user af6fb909-712b-4b51-8737-67f1c1493559
serviceId U01162V8WP2 exists, for user e35eb779-7859-4338-a2b8-f77f71f2393a
serviceId 105438400528728289170 exists, for user 35cf2566-cef8-4cb4-b2bd-ca7ef7caee80
serviceId U010V4C0L90 exists, for user f1bb10dd-1974-455d-a1d9-c41ea7c5ea5f
serviceId 113526147248043396307 exists, for user 96915cbf-39c2-45c9-bd03-b4f5af76e36d
serviceId 112199957567161430754 exists, for user 7973193d-a830-4daf-b464-781c530d69ba
serviceId 105395398007756494254 exists, for user c1914b64-89b7-4bf0-9f7e-da78d63450bb
serviceId 113476596128161323892 exists, for user 5f5bf586-b5ee-4b0f-9061-db2607ebc70f
serviceId 114089765459615606253 exists, for user e24ce685-baaf-4218-a8b3-342701e01763
serviceId 102096236174812806449 exists, for user 61f05212-dea2-4afe-b643-3908f1eaf6ca
serviceId 111784240398498739232 exists, for user ef9810da-e78d-4cd3-81cb-59de249bc029
serviceId 116886058898576909921 exists, for user 28860a47-1b49-4657-9fd7-850b6db0c276
serviceId 108634152313243551967 exists, for user aed0895c-9c29-4fd7-9c1d-d41b7e5789c2
serviceId 115790323136424322263 exists, for user e69dd388-be62-4ad8-8cd1-fbe9a3c481fa
serviceId 109153449628150257705 exists, for user 7786f0f7-6f93-4939-b4fd-34b5a2fa1129
serviceId 109383022281266071816 exists, for user 27d36f05-2fe0-449e-b99a-96a192d6b083
serviceId U01ADL5CWKZ exists, for user cf27ada8-ca0d-4e11-8590-f9ed40a1550a
serviceId 116173797824765342008 exists, for user f512f2a6-5b46-41ed-9ea2-06870c983206
serviceId 117766188067413906761 exists, for user 772dd0f3-16bf-426c-8d84-fe1bf017e6fe
serviceId 105502235995801400102 exists, for user cbd9c2ea-29f8-4227-aecc-a58573960d84
serviceId 106425073990517401483 exists, for user a5ddd892-3811-47f3-8935-cba260e52ac2
serviceId 110597281146721635381 exists, for user 808ef35e-2932-4cd2-be0b-1a33be84692b
serviceId 101543505976130818404 exists, for user b8de24ca-1619-47e6-8160-19877eda2b24
serviceId 115072305537751910995 exists, for user 1cf67847-39b0-4e06-af5b-121ed7b1c00d
```

Checking the script code looks like, the migration wasn't completed and maybe that is why the app crash?

I am using Google authentication.

Any ideas about how I could push back the database structure or how to fix the issues with the services?

Thanks in advance for your help

**Comment by tommoor** [comment]
Depending on the state of your local data these messages could be considered warnings and not errors. When you look in the database is the `authentication_providers` table full of records and does the number of records map to the number of users you expect to be able to login?

**Comment by Freundschaft** [comment]
I'm also not able to sign in, and my user_authentications table is empty, no errors on logs, how can I increase the debug level?

**Comment by tommoor** [comment]
There is no increased debug level. If your `user_authentications` table is empty did you run the script?

**Comment by Freundschaft** [comment]
yes I did, btw theres a typo there, I think it should be

node build/server/scripts/20210226232041-migrate-authentication.js

or

node /opt/outline/build/server/scripts/20210226232041-migrate-authentication.js

(is this also necessary if not upgrading from previous versions?)

**Comment by tommoor** [comment]
> (is this also necessary if not upgrading from previous versions?)

It is not necessary if not upgrading, but it won't cause any harm either.

**Comment by enzolutions** [comment]
Weird enough, the problem was solved, after redeploying in Heroku, after executing the script manually even with errors. 

I will close this issue.

**Comment by Snuupy** [comment]
How did you execute the nodejs script in the docker container if it keeps exiting with error code 1 when it's brought up?

**Comment by tommoor** [comment]
If you're using docker you just pass the script to override the entry point with docker run, something like:

`docker-compose run -rm outline "node build/server/scripts/20210226232041-migrate-authentication.js"`
