### ISSUE TITLE
Upgrading to 0.54.0 breaks during auth migrations, fail to downgrade to 0.53.1

### ISSUE THREAD

**Issue by gempain** [outline/outline#1981]
Upgrading to 0.54.0 breaks my installation:

```
yarn run v1.22.5
$ sequelize db:migrate --env production-ssl-disabled

Sequelize CLI [Node: 14.16.0, CLI: 6.2.0, ORM: 6.3.5]

Loaded configuration file "server/config/database.json".
Using environment "production-ssl-disabled".
No migrations were executed, database schema was already up to date.
Done in 1.45s.
yarn run v1.22.5
$ node ./build/server/index.js

Running Outline in production mode.

This version of Outline cannot start until a data migration is complete.
Backup your database, run the database migrations and the following script:

$ node ./build/server/scripts/20210226232041-migrate-authentication.js

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Downgrading to 0.53.1 did not fix my problem, now I'm getting a `column user.slackData does not exist` error in the UI and nothing loads (see screenshot). Debug logs didn't show more information on the error.

![screenshot outline](https://user-images.githubusercontent.com/13135149/112220861-02971100-8c27-11eb-9ce3-119425134093.png)

**Outline (please complete the following information):**
- Install: self hosted, via Docker
- Version: outlinewiki/outline:version-0.54.0

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Comment by tommoor** [comment]
@gempain what is the error from the migration script?

You can still run the last release, you would need to do one of either:

- Restore your database from backup before migration
- Run `sequelize db:migrate:undo` to undo the last migration and restore the `user.slackData` column

**Comment by gempain** [comment]
Fixed by using `latest` (0.54.0) and running:

```
docker-compose run --rm outline_outline node ./build/server/scripts/20210226232041-migrate-authentication.js
```

I was expecting migrations to be run automatically. Is this an expected behavior ?

**Comment by tommoor** [comment]
> I was expecting migrations to be run automatically. Is this the expected behavior ?

Yes, I decided to err on the side of caution – it's generally good practice to separate changes to the database schema from moving the data itself as it allows for better disaster recovery. Asking self-hosters to run the single script seemed like a reasonable compromise for the extra safety.

**Comment by gempain** [comment]
It makes a lot of sense 😄  I guess you could add a quick note on upgrading with Docker, as I'm assuming most of your self hosters deploy with it.
