### ISSUE TITLE
Google Analytics for shared pages

### ISSUE THREAD

**Issue by skbly7** [outline/outline#1992]
We are trying to add Google Analytics with Outline but looks like the Analytics only sends updates for logged-in pages.

The shared pages i.e. Anyone with the link can view this document, don't load the Google Analytics component.

**To Reproduce**
1. Enable Google Analytics using UTM as env variable.
2. Go to `/share/{{id}}`
3. (not happening) Google Analytics script should be loaded and xhr call being made.

**Expected behavior**

Google Analytics should ideally send metrics for shared pages as well. 

**Screenshots**

(for logged-in pages)

![image](https://user-images.githubusercontent.com/3490586/112748564-071e4980-8fda-11eb-9db9-48bdc4f757e1.png)

(for shared pages)

![image](https://user-images.githubusercontent.com/3490586/112748574-2917cc00-8fda-11eb-9e07-1e2f8835492c.png)

**Outline (please complete the following information):**
- Install: self hosted
- Version: 2825df29de5800b62691f370fcb6badff19ac200

**Comment by skbly7** [comment]
_(browsed the outline codebase for the first time, so I can be wrong)_

I assume it is happening because `<Analytics />` is added in the `Layout` component [here](https://github.com/outline/outline/blob/main/app/components/Layout.js#L124). 

All the authenticated pages are derived from `Layout` components [here](https://github.com/outline/outline/blob/main/app/routes/authenticated.js#L37). While the shared pages are handled differently [here](https://github.com/outline/outline/blob/main/app/routes/index.js#L25) which doesn't have `<Analytics />` block.

I am not sure if `<Analytics />` should be added to the shared URLs component or there is some component that is parent for both authenticated and shared pages components. 😅

**Comment by tommoor** [comment]
Thanks, good spot! We could probably move it to the top of the index without issues, here:

https://github.com/outline/outline/blob/main/app/index.js#L45

Did you want to PR?
