### ISSUE TITLE
can't run docker container in development mode

### ISSUE THREAD

**Issue by Freundschaft** [outline/outline#1993]
When I set NODE_ENV to development on the latest docker container, I receive the following error:

> yarn run v1.22.5
> 
> $ node ./build/server/index.js
> 
> [33mRunning Outline in development mode with hot reloading. To run Outline in production mode set the NODE_ENV env variable to "production"[0m
> 
> internal/modules/cjs/loader.js:883
> 
>   throw err;
> 
>   ^
> 
> Error: Cannot find module 'koa-webpack-dev-middleware'
> 
> Require stack:
> 
> - /opt/outline/build/server/app.js
> 
> - /opt/outline/build/server/main.js
> 
> - /opt/outline/build/server/index.js
> 
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
> 
>     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
> 
>     at Module.require (internal/modules/cjs/loader.js:952:19)
> 
>     at require (internal/modules/cjs/helpers.js:88:18)
> 
>     at Object.<anonymous> (/opt/outline/build/server/app.js:78:25)
> 
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
> 
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> 
>     at Module.load (internal/modules/cjs/loader.js:928:32)
> 
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> 
>     at Module.require (internal/modules/cjs/loader.js:952:19)
> 
>     at require (internal/modules/cjs/helpers.js:88:18)
> 
>     at Object.<anonymous> (/opt/outline/build/server/main.js:16:35)
> 
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
> 
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> 
>     at Module.load (internal/modules/cjs/loader.js:928:32)
> 
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
> 
>   code: 'MODULE_NOT_FOUND',
> 
>   requireStack: [
> 
>     '/opt/outline/build/server/app.js',
> 
>     '/opt/outline/build/server/main.js',
> 
>     '/opt/outline/build/server/index.js'
> 
>   ]
> 
> }
> 
> error Command failed with exit code 1.
> 
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tommoor** [comment]
This makes sense, development dependencies are not included in the published container.

Development should be done by cloning the repository and running the project that way. (Instructions in readme)
