### ISSUE TITLE
when used with scaleway S3 compatible object storage, everything works, except image upload

### ISSUE THREAD

**Issue by Freundschaft** [outline/outline#1994]
on latest version 0.54 the following bug occurs when using scaleway s3 compatible object stoarge instead of amazon s3 object storage:

1. On Page view, upload a new image
2. image upload works without issues and concludes successfully.
3. but, /attachment.redirect redirects to the wrong URL, instead of "https://xxxx.s3.fr-par.scw.cloud/uploads/" the image is returned as https://s3.fr-par.amazonaws.com/uploads/xxxx so the image isnt rendered correctly

profile and team photo avatar upload work without issues.

envs are set as following:

> AWS_REGION=fr-par
> AWS_S3_ACL=private
> AWS_S3_UPLOAD_BUCKET_NAME=xxxx
> AWS_S3_UPLOAD_BUCKET_URL=https://xxxx.s3.fr-par.scw.cloud

**Comment by tommoor** [comment]
Try `AWS_S3_FORCE_PATH_STYLE=true`, generally needed for non-S3 hosts

**Comment by Freundschaft** [comment]
I tried that but didn't work so far, do I need to reset the DB after setting this flag?

**Comment by tommoor** [comment]
Not required to do a full reset, but there might be attachment records saved in there with the old url

**Comment by Freundschaft** [comment]
ok found the bug, the URL for endpoint cannot be a bucket endpoint, I changed it to service endpoint and it worked. Thanks a lot for the support!
