### ISSUE TITLE
Use friendly urls for collections

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1995]
We've been storing `urlId` in the database for collections since day 1, in the same way we do for documents – but we've never used it! It should be relatively simple to update the `findByPk` method to accept a urlId (basically copy and paste from the Document one) and then have the frontend use them.

This way we change urls from:

`https://app.getoutline.com/collections/8e6edb23-e4b7-474c-97b4-5e7fec49df56` ->
`https://app.getoutline.com/collections/product-97b4ih`

**Comment by iamsaumya** [comment]
I will work on this.

**Comment by iamsaumya** [comment]
Do we need backwards compatibility on this? we should redirect the user to the friendly URL if they visit a valid URL of the current type

**Comment by tommoor** [comment]
Yea, we do need compat and forward to canonical similar to how documents work.

If you start on this I'd recommend forking from https://github.com/outline/outline/pull/2005 – as I converted collection data loading inside a functional component.

**Comment by iamsaumya** [comment]
Todos - WIP

- [ ] Expose collection urlId to frontend.
- [ ] Update URL getterMethods to return new URL type.
- [ ] Add getByUrlId in collection store.
