### ISSUE TITLE
Recommend Flow language support extension in vscode 

### ISSUE THREAD

**Issue by iamsaumya** [outline/outline#2013]
We are using the flow type checker. It will be nice if we recommend [this](https://github.com/flowtype/flow-for-vscode) extension to developers for a better experience in vscode.

**Comment by tommoor** [comment]
I don't really want to make any assumptions about development environment, but a quick link somewhere in the README seems fine.

**Comment by iamsaumya** [comment]
Because we already have `.vscocde` folder, Don't you think it will be much better to add it there?
