### ISSUE TITLE
InputSelect uses a white background for options in dark mode.

### ISSUE THREAD

**Issue by iamsaumya** [outline/outline#2015]
InputSelect uses a white background for options in dark mode.

**To Reproduce**
Steps to reproduce the behaviour( in dark mode):
1. Open the modal for creating a collection
2. Click on the default access dropdown
3. Options have a white background

**Expected behaviour**
Use custom select input to show the options. 

Settings -> Members page
![Screenshot from 2021-06-07 00-40-13](https://user-images.githubusercontent.com/40148448/120937067-fea86480-c728-11eb-8605-5061c155c82f.png)

**Screenshots**
![Screenshot from 2021-04-07 17-40-48](https://user-images.githubusercontent.com/40148448/113864434-85dc6900-97c8-11eb-9adc-3f9efbb0d596.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Brave

**Comment by tommoor** [comment]
Interesting, we don't attempt to style this aspect of the select – on macOS it looks great in the system style

![image](https://user-images.githubusercontent.com/380914/114253292-8575d680-995e-11eb-9164-7ba32353ae99.png)

**Comment by iamsaumya** [comment]
Should I go ahead and make a PR? This issue is stranded for quite some time now.

**Comment by tommoor** [comment]
I wonder if the only way to properly solve this is to use a custom select input 😬

**Comment by iamsaumya** [comment]
Makes sense 👍🏻. I'll remove the "good first issue" label.
