### ISSUE TITLE
Lucidchart embeds do not work on new domain

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2017]
It looks like lucid changed their url's… again, there is a new format that looks like:

https://lucid.app/lucidchart/<uuid>/view

**Comment by ChuckJonas** [comment]
When I try to embed lucid chart, I get an error saying "link won't work for this type of embed".

My shared link looks like this:

https://lucid.app/lucidchart/6b21f6c1-4bd7-4d21-abef-097d97491f2c/edit?viewport_loc=-11%2C-11%2C1747%2C960%2C0_0&invitationId=inv_a49a4a0a-dfbf-44d3-9a16-3cee4f1abd4d

<img width="400" alt="Blank_diagram__Lucidchart" src="https://user-images.githubusercontent.com/5217568/150629779-422dda45-4a89-4b6a-b1ef-c87973e1e5ac.png">
