### ISSUE TITLE
Default Access dropdown menu is not clearly visible when I create  a new collection

### ISSUE THREAD

**Issue by jasbirrajrana** [outline/outline#2029]
**dropdown menu  items are not clearly visible when I create a new collection**
**To Reproduce**
1. Go to Sign up
2. Click on continue with slack
3. Select a new workspace & open it 
4. Click on **+Create new collection** in the sidebar

**Expected behavior**
On clicking the ***Default Access*** dropdown menu background color and font color of each menu item should be Change. 
So that each item must clearly visible.

**Screenshots**
<img src="https://res.cloudinary.com/dqxwlfqrs/image/upload/v1618307028/found-bug_kznkmk.png"/>

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [ 89.0.4389.114 (Official Build) (64-bit)]

**Comment by iamsaumya** [comment]
Thanks for reporting @jasbirrajrana. We're tracking the issue here #2015. Closing this issue for now.
