### ISSUE TITLE
Exporting documents with slashes cannot be imported

### ISSUE THREAD

**Issue by marksteve** [outline/outline#2036]
Exporting documents with slashes creates unwanted directories that causes errors on import.

**To Reproduce**
1. Create a document named "Test/Document"
2. Export to an archive file
3. Import that archive file
```
outline_1   | (node:28) UnhandledPromiseRejectionWarning: Invariant Violation: Document must exist for parent Test
outline_1   |     at invariant (/opt/outline/node_modules/invariant/invariant.js:40:15)
outline_1   |     at collectionImporter (/opt/outline/build/server/commands/collectionImporter.js:137:32)
outline_1   |     at async Importer.on (/opt/outline/build/server/services/importer.js:41:11)
```

**Expected behavior**
Document names are cleaned up to remove invalid characters like slashes.

**Screenshots**
N/A

**Outline (please complete the following information):**
- Install: [self hosted]
- Version: [200f25c4b2eb4a7178dad941574a0e48c1d077ad]

**Desktop (please complete the following information):**
N/A

**Mobile (please complete the following information):**
N/A

**Comment by tommoor** [comment]
Interesting, thanks for reporting – slashes in file names always seem to create wonderful edge cases
