### ISSUE TITLE
Add ability to permanently delete documents in trash

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2057]
- Currently when you first delete a document it is added to the trash section
- Deleted documents in trash are permanently deleted via a cron job after 30 days
- There is currently no way to delete prior to that

We would like to have a "Delete…" option in the "..." overflow menu for documents in the trash that immediately and permanently deletes the document before the 30 days after a confirm modal.

**Comment by rubenmoya** [comment]
Should this also add a new policy?

**Comment by tommoor** [comment]
My current thinking is that we can use the same policy as it's just an accelerated version of the same action. The policy will need changing though as it currently blocks delete when already deleted

**Comment by iamsaumya** [comment]
Do we want to make this action admin only?

**Comment by tommoor** [comment]
> Do we want to make this action admin only?

Original permissions for delete are fine. 

> Should we create an endpoint or pass a parameter in the body to signify permanent delete?

I like passing an extra parameter – `permanent: true`

**Comment by iamsaumya** [comment]
@rubenmoya, I feel you were interested in this issue. If you are working on this at your end, please do let us know here. Thanks!

**Comment by iamsaumya** [comment]
I

**Comment by iamsaumya** [comment]
Sorry, my laptop froze.

**Comment by iamsaumya** [comment]
I have assigned this issue to me as it is a priority to complete for v0.57.0. I hope that's okay. 🍻
