### ISSUE TITLE
Referenced doc hover displays under the 'Referenced by' component

### ISSUE THREAD

**Issue by JackLewisGit** [outline/outline#2062]
When a document reference is close enough to the bottom of the content, the document overview hover component renders under the 'Referenced by' component if it is present (see screenshot).

**To Reproduce**
1. Create a document that is just a link to another document.
2. Reference the newly created document from another document (doesn't matter which) so that the 'Referenced by' component is displayed.
3. Hover over the link in the document created in step 1
4. The hover component should be cutoff by the 'Referenced by' component

**Expected behavior**
The hover should render above the 'Referenced by' component so it is fully visible.

**Screenshots**
![Screen Shot 2021-04-23 at 4 37 26 pm](https://user-images.githubusercontent.com/6396235/115830452-a86eb300-a453-11eb-8e1e-e3f327fd486b.png)

**Outline (please complete the following information):**
- Install: getoutline.com
- Version: n/a

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.1
 - Browser: Chrome
 - Version: 90.0.4430.72

**Comment by tommoor** [comment]
Thanks for filing, will get this fixed up fast.
