### ISSUE TITLE
400 Bad Request when trying to upload images (using Minio for storage)

### ISSUE THREAD

**Issue by andreipoe** [outline/outline#2068]
I'm using a new self-hosted instance with Minio for S3-compatible storage. Everything works, except uploading images. None of the suggestions in similar issues or discussions seem to help.

**To Reproduce**
1. Crete a new self-hosted instance using the Outline Docker image and Minio instead of S3.
2. When first logging in, `InvalidAccessKeyId` errors will be shown in the logs:
    ```
    InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
    outline     |     at Request.extractError (/opt/outline/node_modules/aws-sdk/lib/services/s3.js:700:35)
    outline     |     at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    outline     |     at Request.emit (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    outline     |     at Request.emit (/opt/outline/node_modules/aws-sdk/lib/request.js:688:14)
    outline     |     at Request.transition (/opt/outline/node_modules/aws-sdk/lib/request.js:22:10)
    outline     |     at AcceptorStateMachine.runTo (/opt/outline/node_modules/aws-sdk/lib/state_machine.js:14:12)
    outline     |     at /opt/outline/node_modules/aws-sdk/lib/state_machine.js:26:10
    outline     |     at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:38:9)
    outline     |     at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:690:12)
    outline     |     at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    outline     |     at Request.emit (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    outline     |     at Request.emit (/opt/outline/node_modules/aws-sdk/lib/request.js:688:14)
    outline     |     at Request.transition (/opt/outline/node_modules/aws-sdk/lib/request.js:22:10)
    outline     |     at AcceptorStateMachine.runTo (/opt/outline/node_modules/aws-sdk/lib/state_machine.js:14:12)
    outline     |     at /opt/outline/node_modules/aws-sdk/lib/state_machine.js:26:10
    outline     |     at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:38:9) {
    outline     |   code: 'InvalidAccessKeyId',
    outline     |   region: null,
    outline     |   time: 2021-04-23T20:00:38.149Z,
    outline     |   requestId: 'SZ190QE24NHJH61F',
    outline     |   extendedRequestId: 'Y0LLbIfK4Cjlcm0bomBP/peQ/6NbieNL6aJjZh3h6Oy734hIHznQ5UdK6NLZrF/sQIqffWZSZvU=',
    outline     |   cfId: undefined,
    outline     |   statusCode: 403,
    outline     |   retryable: false,
    outline     |   retryDelay: 62.652781887165254
    outline     | }
    ```
3. At this point the application works, except for uploading images. 
4. Trying to upload an image produces a "Sorry" message and a `400 Bad Request` error in the browser console. Nothing is uploaded to Minio.

**Expected behavior**
Images should be able to upload successfully.

**What I've already ruled out:**
- The `InvalidAccessKeyId` errors only show up in the logs when a fresh instance is launched. There are no errors in the logs on subsequent launches. `DEBUG` is set.
- The Minio credentials are valid: they work both through the browser interface and using the `mc` command-line tool.
- There are no access denied or CORS errors.
- Setting `download` policy on the Minio bucket (#1912) does not fix the issue. Profile icons are shown ok.

**Outline:**
- Install: self-hosted, using the oficial Docker image and completed `env` file
- Version: 0.55.0

**Desktop:**
 - OS: Linux, Windows
 - Browser: Chrome 89, Firefox 87

**Comment by tommoor** [comment]
Please provide all of the `AWS_` environment variables that you have set currently, it could also be useful to look at the exact request that the browser is making when you try and upload an image – is the host, bucket, etc all correct?

**Comment by andreipoe** [comment]
These are my AWS variables (with secrets redacted):

```
AWS_ACCESS_KEY_ID=username
AWS_SECRET_ACCESS_KEY=mysecretaccesskey
AWS_REGION=us-east-1
AWS_S3_UPLOAD_BUCKET_URL=https://minio.mydomain.tld
AWS_S3_UPLOAD_BUCKET_NAME=outline
AWS_S3_UPLOAD_MAX_SIZE=26214400
AWS_S3_FORCE_PATH_STYLE=true
AWS_S3_ACL=private
```

I can use the URL to open Minio in the browser and the same login credentials to access the bucket. The `outline` bucket exists, and through the browser or `mc` I can upload files to it.

----

Here is a screenshot of the request from the Chrome developer tools:

![outline-minio-request](https://user-images.githubusercontent.com/6793243/115954437-bd058680-a4f9-11eb-891c-9a296c77de1d.png)

The following are redacted:

1. The Minio URL, which is the same as in `AWS_S3_UPLOAD_BUCKET_URL`.
2. My server's IP address followed by `:443`.
3. My Outline URL.
4. My `AWS_ACCESS_KEY`.

This is the response from the same developer console:

```
<Error>
  <Code>BadRequest</Code>
  <Message>An error occurred when parsing the HTTP request POST at '/'</Message>
  <Resource>/</Resource>
  <RequestId/>
  <HostId>73bfbd39-b324-4a68-xxxx-xxxxxxxxxxxx</HostId>
</Error>
```

**Comment by andreipoe** [comment]
Hi. I have an update on this issue.

I changed `AWS_S3_UPLOAD_BUCKET_URL` to `https://minio.mydomain.tld/outline`, i.e. I added the bucket name to the URL, and now images are uploaded, but not retrieved correctly in the document. The browser console shows a `403 Forbidden` request to `https://s3.amazonaws.com/outline/uploads/...`. If I take that URL and replace `s3.amazonaws.com` with `minio.mydomain.tld`, then I can see the file successfully uploaded through the Minion web interface. 

Could this be related to #1910?

**Comment by accesstechnology-mike** [comment]
Can confirm exact same behaviour. 

Appending "/outline" does fix the upload, but viewing image returns 403 from s3.amazonaws.com

**Comment by tommoor** [comment]
Sounds like you need to set AWS_S3_FORCE_PATH_STYLE=true otherwise the bucket name is considered to be part of the url (this is the recommended default for buckets on S3 now)

**Comment by andreipoe** [comment]
In my installation it is set. I posted all the `AWS` vars above if that helps.

**Comment by tommoor** [comment]
Is your bucket name contained in the url? There is a bug there I believe - could try changing the bucket name

**Comment by accesstechnology-mike** [comment]
Same here.

Also, that doesn't seem to account for the download link referring to
s3.amazonaws rather than the minio URL defined in the .env

**Comment by andreipoe** [comment]
That did it! My Minio URL was `data.outline.mydomain.tld` and my bucket name was `outline`. When I changed the bucket name to something unrelated, and removed it from `AWS_S3_UPLOAD_BUCKET_URL`, uploads started working fine.

It seems the real bug here is having your minio domain contain the string `outline` and naming your bucket `outline` too.

Thanks, @tommoor!

**Comment by accesstechnology-mike** [comment]
Can confirm. That works!

**Comment by Nicicalu** [comment]
For me it only worked when adding the bucket name to the URL and setting `AWS_S3_FORCE_PATH_STYLE=false`:
```
AWS_REGION=eu-east-1
AWS_S3_ACCELERATE_URL=https://minio.mydomain.com/docs
AWS_S3_UPLOAD_BUCKET_URL=https://minio.mydomain.com/docs
AWS_S3_UPLOAD_BUCKET_NAME=docs
AWS_S3_FORCE_PATH_STYLE=false
```

**Comment by stijn1989** [comment]
@Nicicalu thanks, just what I needed. Now it works.

**Comment by heyValdemar** [comment]
hey guys, I wrote [a detailed guide](https://www.heyvaldemar.com/install-outline-and-keycloak-using-docker-compose/) after I was able to configure Outline with MinIO and Keycloak.

Hopefully, it will help others.
