### ISSUE TITLE
Facepile sometimes displays +1

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2076]
**To Reproduce**
1. Have a facepile with exactly 7 users
2. The UI will display 6 avatars and a (+1)
3. This is clearly useless

**Expected behavior**
Never display (+1)

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

![image](https://user-images.githubusercontent.com/380914/116108823-1d670600-a669-11eb-9896-d994884e7770.png)

**Comment by sean-brydon** [comment]
I've just had a quick look at this issue and from what I see the value of overflow would need to be `overflow > 1 ` and this should fix the issue. 

I havent got time to clone the repo and test this out but this might be a good starting point
