### ISSUE TITLE
Images permissions are shared when document is moved 

### ISSUE THREAD

**Issue by Akhu** [outline/outline#2107]
User with lower access rights than in the original document cannot view image on a duplicated document.

**To Reproduce**
1. Create a document with images in it, inside a restricted access collection
2. Duplicate this document to another collection with wider / larger access or public
3. Open the duplicated document **as a user** that does not have access to the first and restricted collection where the  document were originally created.
4. You does not have access to the images (403)

**Expected behavior**
When a document is duplicated, image right should have their own access data. I suspect they share the same permissions data.

**Workaround** 
Re-upload images in the duplicated document.

**Screenshots**
![](https://i.imgur.com/T2hesAD.png)
You get a 403 for each image in the duplicated document :(

**Outline (please complete the following information):**
- Install: self hosted
- Version: [Docker Image 0.55.0](https://hub.docker.com/layers/outlinewiki/outline/version-0.55.0/images/sha256-1af6794e2a290e0c42b5272f2cd9cd08ca4b6f6d4e48e87070226750e8e2dddf?context=explore)
- We use Minio as image storage service

**Desktop (please complete the following information):**
 - Browser : Firefox (87.0), Chrome (90.0.4430.93)

**Comment by tommoor** [comment]
Great find.

To duplicate, you're using the inbuilt "duplicate" function and then moving the document afterwards?

**Comment by Akhu** [comment]
> Great find.
> 
> To duplicate, you're using the inbuilt "duplicate" function and then moving the document afterwards?

Exactly !
