### ISSUE TITLE
No indentation in bullet list within numbered list possible

### ISSUE THREAD

**Issue by Hans-Meiser** [outline/outline#2109]
There is no indentation of the bullet list within the numbered list possible.

**To Reproduce**
1. Create a numbered list and add a bullet list within the numbered list.

**Expected behavior**
The bullet list should have an indentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/83597906/116898562-d2378f00-ac36-11eb-9d6c-07d3b1ab25c8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by tommoor** [comment]
Hi, this is possible steps:

- you can create a numbered list
- hit **enter** at the end to create an empty item
- hit **delete** to remove the number
- type "- " to start a new bullet list
