### ISSUE TITLE
Creating a hyperlink to website/ file on drive doesn't work

### ISSUE THREAD

**Issue by Hans-Meiser** [outline/outline#2114]
You can't create a hyperlink to a website (https://www.google.de) that it works right away. Linking to a file doesn't work at all.

**To Reproduce**
1. Create a link to a website or a file on a drive, it doesn't work.

**Expected behavior**
Open the website or the file which is linked.

**Screenshots**
-

**Outline (please complete the following information):**
- Install: Linux?!
- Version: Current

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome

**Comment by tommoor** [comment]
Hi, this is expected behavior and is an inbuilt security restriction of all browsers I'm afraid.
