### ISSUE TITLE
Add translation hooks where missing

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2117]
There are quite a few spots still where English strings are hardcoded, these need moving to use `react-i18n` and (ideally but not required) functional components. A lot of the remaining spots are in confirmation dialogs, modals, toast messages etc.

Fixing several screens at a time and doing multiple smaller PR's seems like the best way to get these tackled in a manageable manner. These are the components I'm currently aware:

- [x] `ErrorBoundary`
- [x] `InputRich`
- [x] `CollectionDelete`
- [x] `CollectionExport`
- [x] `DocumentTemplatize`
- [x] `DocumentMove`
- [x] `DocumentNew`
- [x] `GroupDelete`
- [x] `GroupEdit`
- [x] `GroupNew`
- [x] `GroupMembers`
- [x] `Invite`
- [x] `UserDelete` 
- [x] `Settings/Details`
- [x] `Settings/Notifications`
- [x] `Settings/Security`
- [x] `Settings/Tokens`
- [x] `Settings/Zapier`

**Comment by iamsaumya** [comment]
I'm working on translating the settings page first.

**Comment by iamsaumya** [comment]
Are we translating all the statements in the app? If no, please help me with what type of statements to leave.

![Screenshot from 2021-07-09 00-09-27](https://user-images.githubusercontent.com/40148448/124974050-f43ffa00-e049-11eb-8882-b7efbaab667a.png)

**Comment by tommoor** [comment]
Yes, all of these can be translated 👍
