### ISSUE TITLE
Remove application/octet-stream as valid frontend mimetype

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2123]
Follow up to https://github.com/outline/outline/pull/2105

After further testing on Windows it seems that using this mimetype results in .bin, .com, .exe files showing as available options. Instead lets just whitelist .doc, .docx extensions explicitly. This is a frontend only change, all of the updated handling on the backend can remain the same.

**Comment by iamsaumya** [comment]
Adding `.doc` and `.docx` extensions to the `importFileTypes` array will show these files in available options and removing them from the array will not show these files in the available options. (tested for Linux, It should work for windows too I believe)  

I can't find `application/octet-stream` mimetype on the frontend. Could you please point me where it has been used?

**Comment by iamsaumya** [comment]
If you want to tackle this issue at your end, lemme know 😄

**Comment by tommoor** [comment]
> I can't find application/octet-stream mimetype on the frontend

This one, added in the previous PR :)

https://github.com/outline/outline/blob/69802cc9850a07fd986a9dcfda1b50549f81debd/app/stores/DocumentsStore.js#L32

**Comment by iamsaumya** [comment]
Foolish me! I didn't pull the latest main.
