### ISSUE TITLE
Refactor collection exports to not send email attachment

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2125]
Sending exports as an email attachment was perhaps a neat idea in the early days but we've reached the limit of what this can offer. Collections and their images regularly exceed the size that can be reliably sent over email. 

### User flow

- Generate the file on the event queue
- Upload the file to private storage bucket
- Email the user a link to download the export (The link should require a session)

### Considerations

As a security measure the emailed link should not be directly to the file, it should be to the web app which requires a session and forwards to a link generated to access storage.

In the future we may want to create a table to record exports, in this way we could immediately return an `export id` from the API when an export is requested and allow the end user to query the export progress

**Comment by iamsaumya** [comment]
Do you plan to tackle this? 

If not, Could you please help me with the web app and session flow? Is it going to be an endpoint to Outline to check if the user is logged in?

**Comment by tommoor** [comment]
I was thinking about this today, It would probably be worth a new database table / model to keep track of data exports and we can then list them in the admin under "Import / Export" and provide a link from the email that just goes to this correct admin page.

This would also create a nice visual history of the exports that have happened, who requested them, and when. The model schema would contain something like:

- `userId` – user who requested the export
- `teamId` – team who user belongs to (I've found it nice to denormalize this)
- `state` – enum (`creating`, `uploading`, `complete`, `error`)
- `collectionId` - optional, if exporting a specific collection
- `createdAt` - timestamp of export obvs
- `key` - s3 object key (same as attachments)
- `size` - s3 object size (same as attachments)

**Comment by iamsaumya** [comment]
Is there any design on how you want this to look?

**Comment by iamsaumya** [comment]
Do you think we should delete data exports older than 30 days?

**Comment by tommoor** [comment]
> Is there any design on how you want this to look?

Not yet, could use the standard `PaginatedList` and `List/Item` components in the meantime :)

> Do you think we should delete data exports older than 30 days?

Yes! This could be part of `utils.gc` and would necessitate another status – `expired` – that is set once the data in s3 is deleted?

**Comment by iamsaumya** [comment]
> Not yet, could use the standard PaginatedList and List/Item components in the meantime :)

Oh, I went ahead using tables. Not the best-looking design, but it helped get going.
