### ISSUE TITLE
Add access to document TOC on mobile

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2145]
Customer request through support, makes sense!

We can add the TOC button next to the menu button and have it trigger a context menu version of the table of contents on mobile which will slide up from the bottom.

**Comment by iamsaumya** [comment]
Assigning this to me. I hope that's okay!

**Comment by razor950** [comment]
Sorry if this should be its own issue but its related, the TOC on large MD files is pretty awkward to use design wise. It would make sense if the TOC was scrollable and allowed you to click on a topic but it would follow you on that side of the page as well, so the TOC allows you to find your way in a large document.

**Comment by tommoor** [comment]
It’s own issue would be great. If you have examples of the current behavior
in the form of screenshots or videos that would really help
