### ISSUE TITLE
Change of block type removes content

### ISSUE THREAD

**Issue by accesstechnology-mike** [outline/outline#2156]
Outline presumes we know the block type _before_ writing content. However it is often the case that content needs to be formatted after.

Highlighting text allows some changes (H1, H2, bold, italic etc), but doesn't allow for change to info box for example.

If an `/info` tag is typed at the front of a current paragraph, upon creation of the info box, the text is deleted.

Expected behaviour: adding an info tag at the beginning of a content block should put that content into the box.

**Comment by tommoor** [comment]
Thanks Mike, we didn't really design the slash commands to be used inside a paragraph that already contains content however this seems like a solid update to make :)
