### ISSUE TITLE
[Development OAuth] Cannot add `http://*` URL as redirect URL

### ISSUE THREAD

**Issue by Soyn** [outline/outline#2165]
**To Reproduce**
1. Follow the instruction in README file.
2. In Slack OAuth setting, cannot set redirect URL.

**Expected behavior**
* Need to update the development instruction.

**Screenshots**
![image](https://user-images.githubusercontent.com/7734046/120502555-1b752d00-c3f5-11eb-983e-96b31c8f43c9.png)

**Outline (please complete the following information):**
- Install: local development
- Version: `main` branch

**Comment by tommoor** [comment]
Hmm, I have `http` urls for development without issue – I think this is a regression on Slack's part that needs to be fixed.

**Comment by Soyn** [comment]
I'm curious about how to set the http URL. In current setting, the url starts with http cannot be saved. Maybe we can provide a fake Slack OAuth in dev env.

**Comment by tommoor** [comment]
I suggest contacting Slack, I think they broke it.

**Comment by BrenoBeierstedt** [comment]
same issue here, i'm using ngrok to make a https tunnel  for now.
