### ISSUE TITLE
[Local Development] The local dev env cannot be running in windows

### ISSUE THREAD

**Issue by Soyn** [outline/outline#2168]
**To Reproduce**
1.  Follow the local development setting in readme.
2.  When run the `make up`. The command  not founded. (It's the windows issue)
![image](https://user-images.githubusercontent.com/7734046/120579351-efd85e00-c459-11eb-8187-af51a5b1548a.png)
3. I copy the `make up` command to another shell file, and run in `git bash`. It works.
4. In the command executation, the error pops up
![image](https://user-images.githubusercontent.com/7734046/120579618-6aa17900-c45a-11eb-81c4-c3bdb5bb7688.png)
5. And this issue --> [Webpack Parse Error](https://github.com/outline/outline/issues/2026#issuecomment-827155396) is also related.

**Expected behavior**
I have done some research on these issues, it seems the dev setting just cares the *nix env. Maybe we need to add some code or instruction for Windows user.

If possible, i can send a pull request to fix this issue.

**Outline (please complete the following information):**
- Install: Local Development
- Version: `main` branch

**Comment by tommoor** [comment]
Hi @Soyn – if the PR is mainly changes to instructions that would be acceptable, if it requires code changes then the PR might not be accepted as the additional burden of maintaining the Windows development environment isn't something I want to take on as sole maintainer.

**Comment by Soyn** [comment]
Ok. I will work on this. And is it possible to provide another issue template. I cannot change the label of issue from bug template
