### ISSUE TITLE
Copying 'share' text, copies formatting

### ISSUE THREAD

**Issue by accesstechnology-mike** [outline/outline#2207]
When copying and pasting the share link, the font size, text colour and background colour (in dark mode) are pasted.

**Expected behavior**
Plain text, rather than styles

![image](https://user-images.githubusercontent.com/55278705/121502197-d72af380-c9d7-11eb-8d00-bab9c08713ff.png)

- Self hosted
- Version: 0.56
- Chrome

**Comment by tommoor** [comment]
This is copying from the text box in the flyover rather than clicking on the "Copy link" button, yea?

**Comment by accesstechnology-mike** [comment]
No, this is only when clicking the "Copy Link" button.

Highlighting and copying the text (Ctrl+C) behaves as expected.

**Comment by tommoor** [comment]
Note: This seems to be a bug in the [copy-to-clipboard](https://github.com/sudodoki/copy-to-clipboard) dependency
