### ISSUE TITLE
Allow searching of previous document titles

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2211]
It would be nice if it was possible to find a document by searching any of its previous titles. This would need the following:

- A new `previousTitles` column as an array of strings
- New column should be search indexed in the same way as title column
- Write previous title to new column whenever it changes in `api/documents.update`
- Include new column in search methods `searchForUser` and `searchForTeam`
- Include tests for above behavior

**Comment by iamsaumya** [comment]
While waiting for the designs from the team, I guess I will start tackling this. Thanks for the detailed issue 🙇🏻

**Comment by iamsaumya** [comment]
A suggestion - we can show that this doc appeared because of its previous titles.

**Comment by iamsaumya** [comment]
> Include new column in search methods searchForUser and searchForTeam

From my testing, we can already search the docs on their previous titles. I think we don't have to do this, if I am missing something please let me know.

**Comment by tommoor** [comment]
Not sure what behavior you're seeing but it certainly shouldn't be working right now

**Comment by iamsaumya** [comment]
I meant in my PR [here](https://github.com/outline/outline/pull/2326). 

Any thoughts on the suggestions above?

**Comment by tommoor** [comment]
> I meant in my PR

Aha, I see now re lack of migrations – even better! 

> we can show that this doc appeared because of its previous titles.

This might be neat, see if it's possible to expose a property to the frontend via the API response for this? We can consider the UI in the meantime.

> Considerations on storing only previous X titles.

I'd be fine keeping all of them I think, generally docs don't get renamed very often

**Comment by iamsaumya** [comment]
Thanks!

> see if it's possible to expose a property to the frontend via the API response for this?

I'll see what can be done here.

**Comment by tommoor** [comment]
This might be an approach, I'm currently undecided if actually including the previous title is important but I don't think so.

![Frame 1](https://user-images.githubusercontent.com/380914/125970165-f2fee92f-d7df-41ae-8198-df635474a7b6.png)

**Comment by iamsaumya** [comment]
I will look for a solution that works out without overcomplicating the API.
