### ISSUE TITLE
Collections import fails with custom S3 configuration

### ISSUE THREAD

**Issue by svallory** [outline/outline#2225]
`collections.import` is calling the wrong endpoint. I'm using digital ocean spaces and it works fine everywhere else but when trying to import a collection, a file is correctly uploaded but the import fails because it tries to get the file from `my_bucket.s3.sfo3.amazonaws.com`

**To Reproduce**
1. Setup to use an S3 compatible service other than AWS S3
2. Try to import a collection

**Expected behavior**
`collections.import` should use the configured `AWS_S3_UPLOAD_BUCKET_URL`

**Screenshots**
![image](https://user-images.githubusercontent.com/117560/121810996-405d7180-cc39-11eb-8dce-2b9031a6518c.png)

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.56.0

**Comment by tommoor** [comment]
You're able to upload a new profile picture, for example? Both places use the same AWS SDK configuration on the backend

**Comment by svallory** [comment]
Yep! I'm able to upload both the profile picture and logo. I don't think they use the same code as the import though as the upload seems to always be done in the browser. The bug on collections import happens on the server and uploads seem to go from the browser straight to S3 (or similar). The zip file is being uploaded correctly to digital ocean spaces in my case

**Comment by tommoor** [comment]
I understand 👍

**Comment by svallory** [comment]
@tommoor I really need this to work to finish my migration. I understand if you guys don't have time to fix it now. Could you point me to the place I should look to find the bug or give me any guidance? I'll be happy to make a PR

**Comment by tommoor** [comment]
My guess is that the error is from this `getObject` call, 

https://github.com/outline/outline/commit/76279902f989b7f4716332b6d79fe2cdb78ca1f1

However it should be using the same configuration as everything else as the `s3` object is the same. Perhaps you could confirm if this is indeed the place throwing the error

**Comment by svallory** [comment]
I just tried it again to catch the error and it showed me the files in the zip (which is weird because it wasn't doing that before), but when I tried to actually import, the import process failed with the same exception (I think, I'll compare later)

```
Aug 03 19:02:23 (node:1) UnhandledPromiseRejectionWarning: UnknownEndpoint: Inaccessible host: `toki-wiki.s3.sfo3.amazonaws.com'. This service may not be available in the `sfo3' region.
Aug 03 19:02:23 at Request.ENOTFOUND_ERROR (/app/code/node_modules/aws-sdk/lib/event_listeners.js:507:46)
Aug 03 19:02:23 at Request.callListeners (/app/code/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
Aug 03 19:02:23 at Request.emit (/app/code/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
Aug 03 19:02:23 at Request.emit (/app/code/node_modules/aws-sdk/lib/request.js:688:14)
Aug 03 19:02:23 at ClientRequest.error (/app/code/node_modules/aws-sdk/lib/event_listeners.js:339:22)
Aug 03 19:02:23 at ClientRequest.<anonymous> (/app/code/node_modules/aws-sdk/lib/http/node.js:96:19)
Aug 03 19:02:23 at ClientRequest.emit (events.js:315:20)
Aug 03 19:02:23 at ClientRequest.EventEmitter.emit (domain.js:467:12)
Aug 03 19:02:23 at TLSSocket.socketErrorListener (_http_client.js:469:9)
Aug 03 19:02:23 at TLSSocket.emit (events.js:315:20)
Aug 03 19:02:23 at TLSSocket.EventEmitter.emit (domain.js:467:12)
Aug 03 19:02:23 at emitErrorNT (internal/streams/destroy.js:106:8)
Aug 03 19:02:23 at emitErrorCloseNT (internal/streams/destroy.js:74:3)
Aug 03 19:02:23 at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by tommoor** [comment]
Updated the link, looks like I linked to the wrong spot

**Comment by svallory** [comment]
@tommoor I think the problem is in this condition: https://github.com/outline/outline/blob/1726006858c0178a186b04d13255ddcadb86476a/server/utils/s3.js#L22

I don't get why `endpoint` should be undefined if the url contains the bucket name, I'm testing replacing `undefined` by  `AWS_S3_UPLOAD_BUCKET_URL` I'll update this with the result

**Comment by tommoor** [comment]
It's not ideal, but we need to support both the old path-style buckets:

https://s3.Region.amazonaws.com/bucket-name

and virtual-host buckets:

https://bucket-name.s3.Region.amazonaws.com

It sounds like your edge case is using virtual-host style url, but with a non-aws host – the assumption inbuilt here was that virtual-host urls were only used with the default aws hostnames.

**Comment by tommoor** [comment]
My suggested fix is:

- Parse the `AWS_S3_UPLOAD_BUCKET_URL` into a `URL` object
- Remove the first subdomain if it matches `AWS_S3_UPLOAD_BUCKET_NAME`
- Pass the resulting url as `endpoint` always.

This _should_ support all scenarios

**Comment by svallory** [comment]
> It's not ideal, but we need to support both the old path-style buckets:
> 
> https://s3.Region.amazonaws.com/bucket-name
> 
> and virtual-host buckets:
> 
> https://bucket-name.s3.Region.amazonaws.com

which of those are you expecting to support when `AWS_S3_UPLOAD_BUCKET_URL.includes(AWS_S3_UPLOAD_BUCKET_NAME)` ?

**Comment by tommoor** [comment]
The later, virtual-host urls but on amazonaws.com currently.

**Comment by svallory** [comment]
I got it to work by removing the bucket name from `AWS_S3_UPLOAD_BUCKET_URL` which is kinda weird. I recommend adding some comments to the `.env.sample` explaining this is how these variables are supposed to be filled if you are not using AWS and the service's bucket url follows the virtual-host format

```
AWS_S3_UPLOAD_BUCKET_URL=https://sfo3.digitaloceanspaces.com
AWS_S3_UPLOAD_BUCKET_NAME=toki-wiki
```

**Comment by ahmadirsyad04** [comment]
I was problem when storage use GCS, when upload failed, this is the problem log inspect

Failed to load resource: the server responded with a status of 400 ()

Any idea for the our problem ?

**Comment by GeoXydias** [comment]
I was trying to deploy outline on Kubernetes and I had to configure the env variables as @svallory mentioned above. 

> I got it to work by removing the bucket name from `AWS_S3_UPLOAD_BUCKET_URL` which is kinda weird. I recommend adding some comments to the `.env.sample` explaining this is how these variables are supposed to be filled if you are not using AWS and the service's bucket url follows the virtual-host format
> 
> ```
> AWS_S3_UPLOAD_BUCKET_URL=https://sfo3.digitaloceanspaces.com
> AWS_S3_UPLOAD_BUCKET_NAME=toki-wiki
> ```
