### ISSUE TITLE
Freeze on enter billing info window for already created servers(Digital Ocean/ MacOs)

### ISSUE THREAD

**Issue by vaimer** [outline/outline#2227]
It happened after MacOs updating, OutlineManger and Outline ask to login again. 
1. Choose create Digital Ocean server in OutlineManger
2. Choose already created account on Digital Ocean
3. Outline manager wait billing info, but DO on home page with servers

**Expected behaviour** 
Outline Manager should find already created server for him

**Screenshots**
![image](https://user-images.githubusercontent.com/9077954/121925813-f7dfaa00-cd45-11eb-92bd-8d06456d1f82.png)
![image](https://user-images.githubusercontent.com/9077954/121925913-104fc480-cd46-11eb-8ef6-404361e187f1.png)

**Outline:**
- Install: getoutline.com / App store
- Version: 1.4.0

**Outline Manager:**
- Install: getoutline.com / App store
- Version: 1.8.1

**Desktop:**
 - OS: MacOs
 - Browser Big Sur
 - Version 11.4

**Comment by vaimer** [comment]
Workaround: destroy existing server on DO, Outline Manager will create a new one.

**Comment by tommoor** [comment]
This issue does not relate to this repo, try: https://github.com/Jigsaw-Code/outline-server
