### ISSUE TITLE
Highlight search term when loading document from search results

### ISSUE THREAD

**Issue by codehimanshu** [outline/outline#2238]
**To Reproduce**
1. Go to any of the documents
2. Click on `t` (search)
3. Type any keyword that exists somewhere in the document below
4. Now in the list of search results, the line appears. Click on it
5. It opens the document 

**Expected behavior**
On clicking any matches in the search results, the corresponding document should open and should scroll down to the search keyword, may be the keyword should even be highlighted.

**Screenshots**
Screenshot wont be of use here

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.55.0

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser Chrome
 - Version 91.0.4472.77 (Official Build) (arm64)

**Comment by tommoor** [comment]
To summarize – this seems like a feature request to scroll to and highlight the search term? That's not behavior that's been built yet.

**Comment by adelicato** [comment]
It would indeed be an interesting feature. If someone is looking for a particular string inside the document the search has to be performed twice (to find the document and later to find the string inside the document)

**Comment by jeremypatrickdahan** [comment]
Also very interested in this feature. I have literally tried 20 knowledge base solutions mainly in search for this.
