### ISSUE TITLE
Allow scrolling of TOC when larger than screen height

### ISSUE THREAD

**Issue by razor950** [outline/outline#2240]
If the TOC could be a bit more to the left and allows for separate scrolling, it would make sense to have one but the way it works now especially on large documents, it doesn't work as it likely should. The gif below shows the issue and the quote below is the initial report on another topic discussing the TOC on mobile.

https://files.catbox.moe/328ydg.gif

"Sorry if this should be its own issue but its related, the TOC on large MD files is pretty awkward to use design wise. It would make sense if the TOC was scrollable and allowed you to click on a topic but it would follow you on that side of the page as well, so the would TOC allow you to navigate throughout the document as it should."

**Comment by tommoor** [comment]
Yes, I guess it should scroll once it gets larger than the height of the page – seems like an easy enough improvement. By the way, this is by far the largest document I've ever seen in Outline 😆 consider splitting it up a little?
