### ISSUE TITLE
SMTP settings for mandrill result in SSL error when mail is sent out from Outline

### ISSUE THREAD

**Issue by chase-replicated** [outline/outline#2245]
**To Reproduce**
 56   SMTP_FROM_EMAIL: "communityemail@company.com"
 57   SMTP_HOST: "smtp.mandrillapp.com"
 58   SMTP_REPLY_EMAIL: "communityemail@company.com"
 59   SMTP_USERNAME: "owner@company.com"

SMTP_PASSWORD: xxxxxxxxxxxxx
SMTP_PORT: 587

Deployed on a Kubernetes cluster, all other features working. When I try to send an invite email out, I see this error in the pod logs: 
```
(node:59) UnhandledPromiseRejectionWarning: Error: 139671493037384:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

(Use node --trace-warnings ... to show where the warning was created)
(node:59) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:59) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Additionally, we've got other applications using node mailer with our mandrill setup fine, so I'm trying to pin down what's going wrong

**Expected behavior**
Mail is sent

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.57.0

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version Any

**Comment by tommoor** [comment]
It sounds like this will be addressed by the work here: 
https://github.com/outline/outline/pull/2217

**Comment by Sleepful** [comment]
you are using port 587 which implies STARTTLS, per this issue and my own experiments, Outline does not support STARTTLS https://github.com/outline/outline/discussions/2343#discussioncomment-1026572

Hopefully this gets looked at because some providers only offer STARTTLS 🤷
