### ISSUE TITLE
Document does not appear in sidebar after creation

### ISSUE THREAD

**Issue by tommoor** [outline/outline#226]
Need to refresh for new docs to appear for some reason. Guessing the collection model in the collection is not getting updated with the new structure or something…

**Comment by cadavre** [comment]
@tommoor this bug is still happening for `master`. As this issue was closed a day after creations – is there any status update for this?

**Comment by tommoor** [comment]
This isn't a known issue, the codebase has evolved considerably since this was closed.

- Can you reproduce on the hosted version at getoutline.com ?
- If not then the problem is with your configuration, perhaps websockets aren't enabled?

**Comment by cadavre** [comment]
Haven't tried to reproduce on getoutline.com, but in fact I cannot see any WS networking made on deployment.

Maybe due to the fact I'm in front of loadbalancer that terminates SSL and Outline running in Docker.

```
URL=https://wiki.mypage.com
PORT=3000
FORCE_HTTPS=false
DEPLOYMENT=self
ENABLE_UPDATES=true
SUBDOMAINS_ENABLED=false
WEBSOCKETS_ENABLED=true
```

I can see no WS networking in browser console and also no "WebSockets disabled" info in console. Any clues why?

**Comment by westong8** [comment]
@tommoor Hi! Currently have a self-hosted production and have ran into this issue as well. Upon the creation of a document, Postgres logs the attached error. Upon subsequent edits and publication, the newly created document does not appear on the sidebar. Any recommendations on a fix?
<img width="1271" alt="Screen Shot 2022-01-16 at 2 41 09 PM" src="https://user-images.githubusercontent.com/93536162/149683008-3c11e311-e0c6-4eeb-9474-dd2fda8c1505.png">

**Comment by tommoor** [comment]
I don't see a relevant error here - most likely you do not have websockets working / forwarding through proxy correctly.

**Comment by westong8** [comment]
@tommoor I see, thanks!

**Comment by freento-ab** [comment]
> @tommoor I see, thanks!

see
https://github.com/outline/outline/discussions/2885
