### ISSUE TITLE
Rich service embeds not working for Google docs

### ISSUE THREAD

**Issue by mjog** [outline/outline#2261]
**To Reproduce**
1. Enable rich service embeds
2. Paste a Google docs link into a document
3. Observe the following:

<img width="753" alt="image" src="https://user-images.githubusercontent.com/3745088/124048318-6a949900-da59-11eb-9a8c-05f136dcef70.png">

**Expected behavior**

The document is successfully displayed as embedded.

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.56.0 release

**Desktop (please complete the following information):**
 - OS: Mac Os 11.4.4
 - Browser Firefox
 - Version 89.0.1

**Mobile (please complete the following information):**

**Comment by tommoor** [comment]
Hi @mjog it seems like you need to enable third party cookies?

**Comment by tommoor** [comment]
closing as there is nothing we can do about blocked cookies
