### ISSUE TITLE
TypeError: Window.getComputedStyle: Argument 1 does not implement interface Element.

### ISSUE THREAD

**Issue by iamsaumya** [outline/outline#2277]
Unable to edit a document in development mode.

**To Reproduce**

Try to edit a document. 

**Screenshots**
![Screenshot from 2021-07-06 09-34-25](https://user-images.githubusercontent.com/40148448/124540667-87581480-de3d-11eb-8883-82d9fb7aae51.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox

**Comment by iamsaumya** [comment]
@tommoor, Is this reproducible at your end?

**Comment by iamsaumya** [comment]
I think this was because of my old node_modules folder. I am unable to reproduce this after reinstalling the packages.

**Comment by tommoor** [comment]
Yep, the textarea dependency was updated to allow for the inner ref to be accessed:
https://github.com/outline/outline/blame/9495ddba25c88e674ebc581c052058e1e34b7324/package.json#L126
