### ISSUE TITLE
Search box should be closed

### ISSUE THREAD

**Issue by Soyn** [outline/outline#2288]
**To Reproduce**
1. Go to 'Search'
2. When click on the area out of search box, search box doesn't close.

**Expected behavior**
When click on the area out of search box, it should be closed.

**Outline (please complete the following information):**
- Install: local development
- Version: b037ae5dc1297c9d0ea357c8e813961cba0bcd98

**Desktop (please complete the following information):**
 - OS: macOS Big Sur Version 11.2.3
 - Browser: Chrome
 - Version: 91.0.4472.114

**Comment by tommoor** [comment]
Hey, sorry I don't fully understand the problem – is it possible to upload a video?

**Comment by Soyn** [comment]
FYI.

https://user-images.githubusercontent.com/7734046/124777695-f97e4580-df72-11eb-8335-0ed4e16e7643.mov

**Comment by tommoor** [comment]
This is expected behavior currently – I think you're aiming for something like a quick jump menu where the search box appears ontop of the current screen like we have outlined here, is that correct? 

https://github.com/outline/outline/issues/2137

If so then the above ticket should cover it

**Comment by Soyn** [comment]
Yes, exactly.
