### ISSUE TITLE
Archive and trash a document by dropping in the sidebar

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2299]
### Discussed in https://github.com/outline/outline/discussions/2135

<div type='discussions-op-text'>

<sup>Originally posted by **iamsaumya** May 12, 2021</sup>
While testing for bugs, I find myself with a lot of documents at times. Now, I either have to delete or archive the documents. Both the option are taxing for a large number of documents. 

From the user's point of view, they too will find it tedious to archive each document through the menu. 

How about dropping the document on the archive menu item in the sidebar? It will be much faster in this case. 

Considering the fact we already have drag and drop implemented in the app, the users are already accustomed to the notion of drag and drop. </div>

**Comment by iamsaumya** [comment]
Hey Tom, Could you please verify if the open prop is handled? It is not working on my end.

**Comment by tommoor** [comment]
https://user-images.githubusercontent.com/380914/125660663-9f73585c-effe-4b6f-bfed-cd7666c65907.mp4

It certainly works in the Storybook

**Comment by iamsaumya** [comment]
This registry [url](https://registry.yarnpkg.com/outline-icons/-/outline-icons-1.27.1.tgz#2bd2127f551f99e8eb81d7a5e19944558a4e3f1d) for 1.27.1 does not have the conditional code for the open prop. 

Could it be a caching issue at yarn's end?

**Comment by tommoor** [comment]
I... don't know what happened, `build` is part of the prepublish command 🤷 

Just republished as `1.27.2` and checked the .tar 👍
