### ISSUE TITLE
Move editor into codebase

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2302]
See: https://github.com/outline/rich-markdown-editor/discussions/481

I plan to archive the editor project as unmaintained and move the code into the Outline codebase. This will allow much tighter integration, sharing of UI components, and speed up development. The editor is core to the Outline experience, it's important that it's recognizable and excellent.

Blocked by #1282

**Comment by soulteary** [comment]
Perhaps an protocol should be added to allow users to freely choose **editor** components, such as switching to tinymce, etc.

This can help outline team save a lot of development time, focus on legacy features and experience issues of current products.

**Comment by tommoor** [comment]
A highly integrated editor experience is key to Outline, we won't be making it swappable by the user 😄 . As a general rule this project is highly opinionated and doesn't try to please everyone like many OSS projects.

**Comment by soulteary** [comment]
> A highly integrated editor experience is key to Outline, we won't be making it swappable by the user 😄 . As a general rule this project is highly opinionated and doesn't try to please everyone like many OSS projects.

Maybe you are right.

Perhaps this is also one of the competitiveness of this project. 😄

**Comment by svallory** [comment]
Would it be acceptable to isolate the editor behind an interface so forks could be created replacing it? The reason I'm asking is that right now editing is kinda hard. I've encountered many small annoyances while editing :/

Also, MHO is that Outline offers a lot more than the editor and while the editor is in fact at the center of the outline experience, there are way more advanced opensource editors that could be used to save up time for other feature developments like smart tables, sharing of collections.

**Comment by tommoor** [comment]
Not really interested in this, we're proud of the editor and would rather use that time and effort to fix the small annoyances - please file issues for those.

The upcoming collab editing also makes switching editors much more difficult
