### ISSUE TITLE
Handle escape characters in the index string.

### ISSUE THREAD

**Issue by iamsaumya** [outline/outline#2315]
Escape characters are not handled in the index value. If and when it is present in the string, the string value changes when interpreted on the server.

For example

index  = `"\"P"` // here `\"P` is the index value which will be interpreted as "P.

**Comment by tommoor** [comment]
It seems like this should be encoded correctly on the client before sending to the server then?

**Comment by iamsaumya** [comment]
My bad. My further research reflects that they are being handled appropriately. Closing this for now.
