### ISSUE TITLE
Show tasks completion on document list items

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2320]
It would be neat to expose a preview of the completed checklist items on documents, see how it's done in a couple of other products:

#### Linear
![image](https://user-images.githubusercontent.com/380914/125662620-eb45191a-3a02-4859-b46b-7769e0ab1988.png)

#### GitHub
![image](https://user-images.githubusercontent.com/380914/125662656-0b7cec5e-a6b6-44a9-bf3b-504d49e4edde.png)

**Comment by iamsaumya** [comment]
Regex matching for `- [ ]` and `- [x]` will do here, right?

**Comment by tommoor** [comment]
I think that's the way to go for now, there's a starting point for that here:
https://github.com/outline/rich-markdown-editor/blob/main/src/lib/markdown/checkboxes.ts#L4

Thoughts on exposing this info via API? Eg a `tasks` key on the document response – could be kind of fun to have that information available to other API consumers 🤔

**Comment by iamsaumya** [comment]
Let's do it.

**Comment by iamsaumya** [comment]
Should we install [this](https://www.npmjs.com/package/react-circular-progressbar) package for the progress bar?

**Comment by tommoor** [comment]
I think it's a bit much, we can achieve this effect with quite a simple SVG component actually – here's an example:

https://dev.to/jackherizsmith/making-a-progress-circle-in-react-3o65
