### ISSUE TITLE
Unable to send out invites

### ISSUE THREAD

**Issue by martinl88** [outline/outline#2323]
While trying to send out invites, UI says "invites sent" but in reality nothing seems to happen. In docker logs I can see this:

```
outline     | (node:59) UnhandledPromiseRejectionWarning: Error: 140097387232584:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
outline     |
outline     | (node:59) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

I've tried with two different SMTP servers, with and without auth.

**To Reproduce**
1. Click on 'Invite people...'
2. Fill out the form
3. Click on 'Send invites'

**Expected behavior**
Invites should be sent out

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.57.0
- Docker image: outlinewiki/outline:latest

**Comment by tommoor** [comment]
Try setting `SMTP_TLS_CIPHERS=SSLv3`

**Comment by soulteary** [comment]
> Try setting the environment variable `SMTP_TLS_CIPHERS=SSLv3`

Perhaps supporting the use of the API Email service can solve many such problems.

For example, eg. mailgun, or a service unique to each user area.

**Comment by tommoor** [comment]
If there is a bug to fix here it would be that it would be nice to capture this specific error and display a friendly error message to modify the configuration.

**Comment by martinl88** [comment]
> Try setting the environment variable `SMTP_TLS_CIPHERS=SSLv3`
Sadly it didn't help. The same error is being spat out.

**Comment by martinl88** [comment]
OK. I'm getting somewhere. Turns out neither STARTTLS or sending without encryption isn't supported and result in the error stated above. When I used regular SSL/TLS, then the invites started moving.

So, the new question is, how can I configure the encryption part of the SMTP connection?
