### ISSUE TITLE
Sign-in broken via  google

### ISSUE THREAD

**Issue by kingassune** [outline/outline#2324]
My company switched domains and I added the new domain and I'm getting this when I try to login with the new SSO, when I revert back to the old domain I still can't log in. 
  exception: 'WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL;',
outline_1   |   hooks: true,
outline_1   |   validate: true,
outline_1   |   fields: [
outline_1   |     'id',                    'email',
outline_1   |     'username',              'name',
outline_1   |     'avatarUrl',             'isAdmin',
outline_1   |     'service',               'serviceId',
outline_1   |     'slackData',             'jwtSecret',
outline_1   |     'lastActiveAt',          'lastActiveIp',
outline_1   |     'lastSignedInAt',        'lastSignedInIp',
outline_1   |     'lastSigninEmailSentAt', 'suspendedAt',
outline_1   |     'suspendedById',         'createdAt',
outline_1   |     'updatedAt',             'deletedAt',
outline_1   |     'teamId'
outline_1   |   ],
outline_1   |   defaultFields: [
outline_1   |     'id',                    'email',
outline_1   |     'username',              'name',
outline_1   |     'avatarUrl',             'isAdmin',
outline_1   |     'service',               'serviceId',
outline_1   |     'slackData',             'jwtSecret',
outline_1   |     'lastActiveAt',          'lastActiveIp',
outline_1   |     'lastSignedInAt',        'lastSignedInIp',
outline_1   |     'lastSigninEmailSentAt', 'suspendedAt',
outline_1   |     'suspendedById',         'createdAt',
outline_1   |     'updatedAt',             'deletedAt',
outline_1   |     'teamId'
outline_1   |   ],
outline_1   |   returning: true,
outline_1   |   hasTrigger: undefined,
outline_1   |   dialect: 'postgres',
outline_1   |   dialectModule: null,
outline_1   |   dialectModulePath: null,
outline_1   |   host: 'postgres',
outline_1   |   protocol: 'tcp',
outline_1   |   define: {},
outline_1   |   query: {},
outline_1   |   sync: {},
outline_1   |   timezone: '+00:00',
outline_1   |   clientMinMessages: 'warning',
outline_1   |   standardConformingStrings: true,
outline_1   |   omitNull: false,
outline_1   |   native: false,
outline_1   |   replication: false,
outline_1   |   ssl: undefined,
outline_1   |   pool: {},
outline_1   |   quoteIdentifiers: true,
outline_1   |   retry: { max: 5, match: [ 'SQLITE_BUSY: database is locked' ] },
outline_1   |   transactionType: 'DEFERRED',
outline_1   |   isolationLevel: null,
outline_1   |   databaseVersion: '12.3.0',
outline_1   |   typeValidation: true,
outline_1   |   benchmark: false,
outline_1   |   minifyAliases: false,
outline_1   |   logQueryParameters: false,
outline_1   |   port: '5432',
outline_1   |   dialectOptions: [Object: null prototype] {},
outline_1   |   bindParam: false,
outline_1   |   type: 'INSERT',
outline_1   |   instance: user {
outline_1   |     dataValues: {
outline_1   |       id: '53f260ee-cea1-4f11-911e-8a44cdb3344a',
outline_1   |       service: 'google',
outline_1   |       serviceId: '101581470988840561260',
outline_1   |       name: 'Dontrail Cotlage',
outline_1   |       email: 'dontrail@unbanked.com',
outline_1   |       isAdmin: false,
outline_1   |       avatarUrl: 'https://lh3.googleusercontent.com/a-/AOh14GgT_AnF4qhAk4wncutxiYx1LVTzrSR26YVwMG_N=s96-c',
outline_1   |       teamId: '8fd59754-6402-4493-9e77-56ae6b8329e7',
outline_1   |       updatedAt: 2021-07-15T17:18:00.370Z,
outline_1   |       createdAt: 2021-07-15T17:18:00.370Z,
outline_1   |       jwtSecret: <Buffer 05 d6 da ce 5a c4 ae 3a ac e4 67 fd a7 8e 01 52 44 7c 5e 5f eb ca bf a2 e4 fd 1f 73 d4 84 8f 00 69 a9 f8 f8 40 31 42 b5 91 de c5 af f9 d7 9e de b7 78 ... 110 more bytes>
outline_1   |     },
outline_1   |     _previousDataValues: {
outline_1   |       service: undefined,
outline_1   |       serviceId: undefined,
outline_1   |       name: undefined,
outline_1   |       email: undefined,
outline_1   |       isAdmin: undefined,
outline_1   |       avatarUrl: undefined,
outline_1   |       teamId: undefined,
outline_1   |       jwtSecret: undefined
outline_1   |     },
outline_1   |     _changed: {
outline_1   |       service: true,
outline_1   |       serviceId: true,
outline_1   |       name: true,
outline_1   |       email: true,
outline_1   |       isAdmin: true,
outline_1   |       avatarUrl: true,
outline_1   |       teamId: true,
outline_1   |       jwtSecret: true
outline_1   |     },
outline_1   |     _modelOptions: {
outline_1   |       timestamps: true,
outline_1   |       validate: {},
outline_1   |       freezeTableName: false,
outline_1   |       underscored: false,
outline_1   |       paranoid: true,
outline_1   |       rejectOnEmpty: false,
outline_1   |       whereCollection: [Object],
outline_1   |       schema: null,
outline_1   |       schemaDelimiter: '',
outline_1   |       defaultScope: {},
outline_1   |       scopes: {},
outline_1   |       indexes: [],
outline_1   |       name: [Object],
outline_1   |       omitNull: false,
outline_1   |       getterMethods: [Object],
outline_1   |       sequelize: [Sequelize],
outline_1   |       hooks: [Object]
outline_1   |     },
outline_1   |     _options: {
outline_1   |       isNewRecord: true,
outline_1   |       _schema: null,
outline_1   |       _schemaDelimiter: '',
outline_1   |       attributes: undefined,
outline_1   |       include: undefined,
outline_1   |       raw: undefined,
outline_1   |       silent: undefined
outline_1   |     },
outline_1   |     isNewRecord: true
outline_1   |   },
outline_1   |   model: user
outline_1   | }
**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: [self hosted]
- Version: [How do I do that will add]

**Desktop (please complete the following information):**
 - OS: [Docker/unbuntu]

**Mobile (please complete the following information):**

**Comment by tommoor** [comment]
Switched Google domains?

**Comment by kingassune** [comment]
@tommoor yes I switched domains.

**Comment by tommoor** [comment]
You can change the domain name directly in the `authentication_providers` table, there will only be a couple of records in there and it's the only way to address an OAuth domain change at this time.

**Comment by kingassune** [comment]
@tommoor , could you point me to some decent documentation on how to do that. I'm running it in a docker container.
