### ISSUE TITLE
Document move: Move a document and its subdocuments to another collection

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#233]
- Right now limited by the API

**Comment by satyadeepk** [comment]
This will be pretty useful for organising documents!

**Comment by defunctzombie** [comment]
@jorilallo Where would one look to add the API to be able to do this?

**Comment by jorilallo** [comment]
@defunctzombie here's the current endpoint for moving documents around: https://github.com/outline/outline/blob/master/server/api/documents.js#L442 and here's the documentation: https://www.getoutline.com/developers#documents.move

I think I might have resisted earlier for access level control and the complexity of UI, but this would be a great addition.

**Comment by jorilallo** [comment]
And here's the UI component: https://github.com/outline/outline/blob/master/app/scenes/Document/components/DocumentMove.js

**Comment by nayatec** [comment]
Hi guys, any news on this ? Easily moving a document between collections is really something that would help a lot :-)
Regards and all the best for 2019 !

**Comment by teddychan** [comment]
Agree, we also want to move the wiki to another collection.
Any plan?

**Comment by pengzihe** [comment]
Hi:
Can I modify the DB to move a collection to another collection, If can, what should I do?

**Comment by tommoor** [comment]
Working on this functionality, in the meantime if anyone stumbles on this issue and wants to move a document between collections you need to "export" the document from one and "import" it into the other.

**Comment by tommoor** [comment]
This feature is now live, thanks for your patience everyone – every week the project gets better!

**Comment by defunctzombie** [comment]
Thank you! This project is amazing \o/
