### ISSUE TITLE
`auth.info` endpoint should check authentication provider access token validity

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2336]
- When requesting `/api/auth.info` the endpoint should make a request to load the users profile data from the SSO provider (if any)
- If the request fails with access denied then a `401` response should be returned to the client
- This will cause the local session to be cleared and forward the browser to the login screen. (This functionality already exists on `401` response)

**Comment by tommoor** [comment]
The tricky thing with this one is how to abstract the SSO provider request, I'd imagine the best thing to do would be to expose a method within all of the `auth/provider/x` files, `validateToken`, or similar.

**Comment by iamsaumya** [comment]
For slack the function is already there. For Google I have found an endpoint, but it doesn't seem to work for now.

**Comment by iamsaumya** [comment]
Do we have token rotation enabled for slack? 

For google - we need to handle generating the access token in `auth.info` because they are short-lived, and the user will be logged out every time if we don't handle this case.

**Comment by tommoor** [comment]
We store refresh tokens for Slack and it seems like _most_ Google accounts, for some reason they don't all have it – perhaps users are able to not allow offline access and that results in it not being returned 🤔

**Comment by iamsaumya** [comment]
I am not sure, I am using my college id, and It's even not returning for me.

**Comment by iamsaumya** [comment]
It seems we were not passing all the required fields to get offline access. 

This will work 

```js  
passport.authenticate(providerName, {
      accessType: "offline",
      prompt: "consent",
    })
```
