### ISSUE TITLE
Add icons to menu items

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2345]
I'm excited for this to make menus much more easily scannable, it will also enable the [quick menu](https://github.com/outline/outline/issues/2137) to be more visual for the same reasons and is considered a blocker for the completion of that PR.

### Rough steps

- [x] Add missing icons to `outline-icons` (design done, new version coming soon)
- [x] Publish new version of `outline-icons` (`outline-icons@1.28.0`)
- [x] Add `icon` as first class property on `MenuItem` rendered on the left hand side of the text
- [x] Convert the places where custom icons are currently used to use the `icon` prop, eg `NewDocumentMenu` shows collection icons and Appearance in `AccountMenu` has icons too
- [x] Add icons to existing menu items where missing

**Comment by iamsaumya** [comment]
Shall I take this forward?

**Comment by tommoor** [comment]
Yep, go for it! Maybe add the icons to just one or two menus first so we can check how it looks?

**Comment by iamsaumya** [comment]
Yeah sure 👍👍

**Comment by iamsaumya** [comment]
For permanent delete - Is it possible to have the trash icon with no space between the lid and trash can?

**Comment by tommoor** [comment]
Did you have another animation in mind? hah.

**Comment by iamsaumya** [comment]
haha, nop, this is it 😅
