### ISSUE TITLE
Heading uncollapses when toggling from editing -> read

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2357]
**To Reproduce**
1. Go to a document
2. Create heading
3. Collapse heading
4. Click "Done editing"
5. Heading uncollapses
6. Reload page
7. Heading is collapsed again

**Expected behavior**

Collapsed state should not reset when toggling `readOnly`

**Comment by iamsaumya** [comment]
I just want to check if this is expected behaviour from the info notice when the heading is collapsed. 

https://user-images.githubusercontent.com/40148448/126866415-529ba437-7768-4ee7-99b1-2a88b7d8e402.mp4

**Comment by tommoor** [comment]
Ideally not 😃

**Comment by tommoor** [comment]
> I just want to check if this is expected behaviour from the info notice when the heading is collapsed.

Fixed, css cascading order issue: https://github.com/outline/rich-markdown-editor/commit/15765bd27d8efc0cd88a605775cf350dc2a8bf27
