### ISSUE TITLE
Individual document sharing

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2359]
We are exploring enabling individual document sharing within the team, there are a couple of use-cases for this that have come up over time:

- Sharing a draft with a colleague to get feedback or help contributing (cc @matbrgz)
- Sharing an individual document from a private collection for a one-off purpose. For example, imagine there is a "founders" collection that contains sensitive information but you want to share a single document with an EA

The key UX consideration is that this does not become a go-to method of sharing information that should be managed through collection permissions. All too often on other platforms you'll find that you were individually shared a bunch of documents that should have been shared within context, this makes them difficult to find and makes access control auditing difficult.

### Suggested limitations

Documents that have been shared with you…

- will **not** appear in the sidebar. This is key for performance and preventing the above ^.
- will **not** expose their collection or parent document info
- can appear in search results
- can have `read` or `read_write` permissions when shared

### API design

TODO

### UI design

TODO

**Comment by Gwemox** [comment]
Good idea

**Comment by napest** [comment]
Hi! Is there an approximate timeline for this feature?

**Comment by Awoolyx** [comment]
Hey,

Individual document sharing seems very important to me personally. You might have a collection for a specific project where you have a few people working on. Here, you'd have a project lead and the project members. Things that you might want to limit is that not everyone can edit something like guidelines, which you'd want to be limited to the project lead.

Another example would be business operations, where you'd want to hide future business planning or strategy for safekeeping, while sharing something important for now.

Currently, you'd have to a separate collection for guidelines, future planning and current planning, even though it would be more reasonable to have this in the same place.

It seems a little overcomplicated needing a separate collection to manage who can edit or see what in larger teams or organizations.

**Comment by praveenaj** [comment]
I'd love to have this as well!

**Comment by tommoor** [comment]
This is the next “big feature” in the roadmap

**Comment by DataGoblin** [comment]
Are the suggest limitations above still relevant? 

I would love to give permissions to nested documents that will show in the sidebar if the individual or group has collection/parent access. This prevents massive overlap of topics where more privilege users need separate collections for the same topic. 

For a visual example. 

**Normal user:** 
```
Collection: 
    --Document
        --Nested Document 1
```

**Special user:**
```
Collection: 
    --Document 1
        --Nested Document 1
        --Nested Document 2

    -- Document 2
```

**Comment by tommoor** [comment]
> Are the suggest limitations above still relevant?

Not entirely, in the end we are exposing documents shared with you in the sidebar, but they appear in their own section out of context of the parent collection if you don't have access to the collection.

If you do have access to the collection and the permission just gives you _more_ access, such as editing rights then it will appear in the usual location.

**Comment by CKGrafico** [comment]
> This is the next “big feature” in the roadmap

We have finally updated our outline to have this feature and thank you very much is awesome! Are you planning to enable to share a document with a group not only individuals?

**Comment by tommoor** [comment]
You can follow the issue here:
https://github.com/outline/outline/issues/6639
