### ISSUE TITLE
Exports generate invalid links

### ISSUE THREAD

**Issue by pdxrlk** [outline/outline#2370]
Exports generate markdown links which do not resolve to the proper paths.  

In the export extraction below, for example, each link points to a `/doc` directory however there is no such directory, and no such file. 

```
* [Benefits](/doc/benefits-NRveSbzJ7x)
* [HR Policies and Resources](/doc/hr-policies-and-resources-jrEdwegbp7)
* [Vacation and Holidays](/doc/vacation-and-holidays-WJVgOQvXys)
```

**Expected behavior**

My expectation is that simple Markdown links would be generated, relative to the location of the referencing file.

```
* [Benefits](Benefits.md)
* [HR Policies and Resources](HR Policies and Resources.md)
* [Vacation and Holidays](Vacation and Holidays.md)
```

Extra special credit would be having an option to generate wiki-style links like [[Benefits]]

**Outline (please complete the following information):**
- Install: getoutline.com

**Comment by tommoor** [comment]
Links need to be remapped on import too, for example if you export a collection and then re-import it then any inter-document links will be incorrect.

I think it would make sense to tackle these as part of the same issue.

**Comment by AlessandroSpallina** [comment]
any update on that?
