### ISSUE TITLE
Slack auth callback timeout 

### ISSUE THREAD

**Issue by IgorWang** [outline/outline#2378]
![image](https://user-images.githubusercontent.com/10041387/127189699-a14048ab-6779-4509-be34-6039b2557103.png)

**Comment by tommoor** [comment]
Hi Igor, this timeout is an external service – there is no control over it. Did this error prevent login?

**Comment by IgorWang** [comment]
yes this error prevent  slack sso login, i guess it's cause by china GFW.

**Comment by IgorWang** [comment]
> Hi Igor, this timeout is an external service – there is no control over it. Did this error prevent login?

yes this error prevent slack sso login, i guess it's cause by china GFW.
