### ISSUE TITLE
Filter search by author does not work well with large teams

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2389]
**To Reproduce**
1. In a team with several hundred users
2. Search for a document
3. Access the "Author" filter
4. Note that not all authors appear and it's difficult to find authors

**Expected behavior**

- The author dropdown should include a filter input at the top
- The author dropdown should probably use `PaginatedList` component to automatically paginate on scroll
- We should hit the `users.list` API with a `query` parameter to get matching users when typing a search query in the filter input (this endpoint and parameter already exist)

**Comment by CuriousCorrelation** [comment]
@tommoor I'd like to take it on if nobody is working on this atm. Seems like a good issue to help me get further familiarized with the code base!
