### ISSUE TITLE
A code block at the beginning of a doc prevents inserting any line above it

### ISSUE THREAD

**Issue by h4x3rotab** [outline/outline#2402]
If we put a code block at the first line of a doc, then there's no way to insert a new line before it

**To Reproduce**
1. Create a new doc
2. Insert a code block at the first line
3. Click "Save Draft"
4. Click "Edit" and try to insert a line before the code block

**Expected behavior**
The cursor should be able to move before the code block in order to insert a line

**Screenshots**
![image](https://user-images.githubusercontent.com/1343470/127749486-ff2861f2-a328-421b-b173-f151bf6c1bde.png)

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.57.0 (429c5fba85927bb4ce3d5641ebd676bb78fb6af5)

**Desktop (please complete the following information):**
 - OS: MacOS 11.4
 - Browser: Chrome
 - Version: Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by tommoor** [comment]
Thanks for filing.

As a workaround put your cursor at the end of the title and type Enter to get a new line below the title.
