### ISSUE TITLE
Google Drive embed content stopped working

### ISSUE THREAD

**Issue by shmileee** [outline/outline#2405]
When inserting URLs to Google Drive documents - they do not get inserted as embed content. This looks like a regression after latest updates. Used to work flawlessly in the past.

**To Reproduce**
1. Upload video to Google Drive
2. Get shareable link
3. Paste it into article
4. Save

**Expected behavior**
Video should be visible as an embed content.

**Actual behavior**
Links are just regular hyperlinks, no embed visible.

**Screenshots**
N/A 

**Outline (please complete the following information):**
- Install: getoutline.com
- Version: latest

**Comment by tommoor** [comment]
Hi, which kind of content are you trying to embed from Google Drive?

**Comment by shmileee** [comment]
> Hi, which kind of content are you trying to embed from Google Drive?

Videos and presentations.

**Comment by tommoor** [comment]
Sorry, yes I see that detail now – should have read more carefully

**Comment by tommoor** [comment]
It seems as though the share link format Google generates changed slightly and now includes a `resourceKey` on the end – you can remove this to have it work again while I implement a fix

**Comment by tommoor** [comment]
Will be deployed to production within 24h, thanks for reporting

**Comment by shmileee** [comment]
@tommoor looks like it's still broken or am I being impatient? :-)

**Comment by tommoor** [comment]
My test cases are working, if you have a non-working link please provide – you can also email it privately to `tom@getoutline.com`

**Comment by shmileee** [comment]
@tommoor, our Outline looks like this after we paste in links to content from Google Drive. Previously we had embed content with preview available.
![Screenshot 2021-08-06 at 11 00 46](https://user-images.githubusercontent.com/9083008/128485897-f653eac0-05da-4ef7-8dac-1499d930b4f9.png)

**Comment by simion24** [comment]
Hi, kind of related to Google drive video links. Does anybody know how to make a video that's stored on google drive to stop at a certain time ? 

I tried using the "&?start=10&end=15" commands that work for Youtube videos, but they don't work for Google Drive videos. The only command that I found that works is just for starting a video at a specific time "?t=10m10s" for example, but I don't the command for stopping it after a certain time. 

If anyone knows it would be much appreciated ty.

**Comment by tommoor** [comment]
@simion24 I don't think it's possible unfortunately

**Comment by simion24** [comment]
@tommoor I see, well thanks anyway.

**Comment by shmileee** [comment]
@tommoor we have not seen any changes with regards to the Google Drive content not being showed as before. Perhaps I'm missing something? 
![Screenshot 2021-09-09 at 12 52 05](https://user-images.githubusercontent.com/9083008/132673247-1ef3760f-8286-46a0-8de1-8bbd33b12506.png)

**Comment by tommoor** [comment]
Could you paste the link here? I don't see any reason it wouldn't work now.

**Comment by shmileee** [comment]
@tommoor, try this: `https://docs.google.com/presentation/d/1xoHKL77-im7LvYdjZQsF6HXaScPKcVHfF0OzTjQ6jZI/edit?usp=sharing`
![Screenshot 2021-09-10 at 09 05 12](https://user-images.githubusercontent.com/9083008/132813857-2ef64045-6446-454d-8e8a-5498f9092785.png)

**Comment by tommoor** [comment]
The link you provided seems to work fine, are you sure you're testing on getoutline.com?

**Comment by shmileee** [comment]
Not sure what was causing the issue, but finally it got resolved and we can see the preview for embed content now on getoutline.com. Cheers!
