### ISSUE TITLE
Editor broken after upgrading to v0.58.1

### ISSUE THREAD

**Issue by MDXDave** [outline/outline#2416]
After upgrading from v0.57.0 to v0.58.1 the editor seems to be broken:

The icons for _all_ embeddable services are missing and i can not copy and paste formatted content like tables anymore:

**To Reproduce**
1. Upgrade the outline container(s) by pulling the new version from docker hub
2. run _docker-compose up -d_
3. See error

**Expected behavior**
Icons are visible and its still possible to copy-paste formatted content

**Screenshots**

Missing Icons:  
![Bildschirmfoto 2021-08-04 um 16 30 20 PM](https://user-images.githubusercontent.com/6099976/128199994-9268f695-f2d3-45fa-a97e-6b38b0b14bd1.png)

Pasting table after copied them:  
![Bildschirmfoto 2021-08-04 um 16 30 35 PM](https://user-images.githubusercontent.com/6099976/128199999-04c10e8b-8f74-4b80-9cdd-67e2610e0e06.png)

**Outline (please complete the following information):**
- Install: self-hosted
- Version: v0.58.1 / 99d74279cfbc

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Brave
 - Version: 1.26.74 (Chromium: 91.0.4472.124)

**Comment by tommoor** [comment]
Is the formatted content in Markdown or HTML? The paste behavior changed to default to html parser if html is on the clipboard and the content doesn't "look" like Markdown, but this detection isn't perfect.

**Comment by MDXDave** [comment]
@tommoor i copied the table that you can see on the bottom of the 2nd screenshot. 😄 
I think at least the content that is generated by outline itself should be copy- and pasteable.

**Comment by tommoor** [comment]
Indeed :) I think some of the characters in the table tricked it into using the Markdown parser in this case.

**Comment by tommoor** [comment]
If you're able to give the `outlinewiki/outline:0.58.2-0` prerelease a try that would be great, contains both fixes.

**Comment by MDXDave** [comment]
@tommoor Its working now - at least on desktop, on mobile it doesnt work, but i am not sure if it has worked on v0.57.0.

But i found another bug, i can not copy an header, i created a new issue for this: #2425
