### ISSUE TITLE
Local Development instructions are missing `.env` configuration of URL

### ISSUE THREAD

**Issue by johnoscott** [outline/outline#2422]
I found the Local Development instructions in the `README.md` to be incomplete. Since `ngrok` is recommended I went through the process of setting it up and found:

1. The `URL` key in `.env` needs to be configured to the public ngrok http address
2. We should show the exact `ngrok` command to run
3. Free `ngrok` accounts generate temporary public urls so the config needs to be updated each time.
4. Stopping the `make up` with ctrl-c does not stop the docker compose services

Here is my recommended additions to that section.

I am happy to create a PR if that helps.

---

## Local Development

For contributing features and fixes you can quickly get an environment running using Docker by following these steps:

1. Install these dependencies if you don't already have them
    1. [Docker for Desktop](https://www.docker.com)
    1. [Node.js](https://nodejs.org/) (v12 LTS preferred)
    1. [Yarn](https://yarnpkg.com)
1. Clone this repo
1. Register a Slack app at https://api.slack.com/apps
1. Copy the file `.env.sample` to `.env`
1. Fill out the following fields:
    1. `SECRET_KEY` (follow instructions in the comments at the top of `.env`)
    1. `SLACK_KEY` (this is called "Client ID" in Slack admin)
    1. `SLACK_SECRET` (this is called "Client Secret" in Slack admin)
    1. `URL` (set to your public ngrok `https` forwarding URL - see below)
1. Configure your Slack app's _Features/Oauth & Permissions_ settings:
    1. Slack recently prevented the use of `http` protocol for localhost. For local development, you can use a tool like [ngrok](https://ngrok.com) or a package like `mkcert`. ([How to use HTTPS for local development](https://web.dev/how-to-use-local-https/))
    1. For `ngrok` run the following command in a new terminal to start a public http/s tunnel to our local development server.
       ```
       ngrok http 3000
       ```
    1. Use the generated ngrok `https` forwarding url from terminal output to:
       * configure the `URL` in .env file mentioned above:
          ```
          URL=https://<my_host>.ngrok.io
          ``` 
       * In _Redirect URLs_, add an Oauth redirect URL to your Slack app configuration based on the forwarding url root.
          ```
          https://<my_host>.ngrok.io/auth/slack.callback
          ``` 
         **NOTE**: The free ngrok account generates a new random URL every time you run ngrok from the terminal,
         so you will also need to update the configuration above each time it changes.
    1. In your Slack app's _Bot Token Scopes_ add an OAuth Scope  `users:read`. 
1. Run `make up`. This will download dependencies, build and launch a development version of Outline. The required redis, posgres and a fake S3 service are started in a `docker-compose` app.
1. Open your browser to the configured URL (ie. if using ngrok, your public `https` forwarding URL )
1. You should be able to Login using the 'continue with Slack' authentication option which will progress through Slack's permission workflow.
1. To stop, type `Ctrl-c`. You can also stop the redis, postgres and fake S3 services with command `docker-compose stop`

**Comment by soulteary** [comment]
From the recent update of 0.59.0, in the future, local development only needs to connect to an oidc client, and it is no longer necessary to lock in the slack oauth solution.

https://github.com/outline/outline/issues/1881#issuecomment-912975706

**Comment by johnoscott** [comment]
@soulteary Is there documentation anywhere on how to do that (connect to an oidc client) for local development ?

**Comment by soulteary** [comment]
Very simple, just add a few environment variables.
https://github.com/outline/outline/commit/4b2bf28531a7b40c40496e9625188a62dc46f3c9

I wrote an article, you can also refer to the method in the article to quickly initialize a local outline. (Need Google to translate Chinese to English)
https://soulteary.com/2021/09/05/opensource-documentation-wiki-software-outline-part-1.html

If you want to completely use the container for development and debugging, the current outline of this part of the code is relatively old, and some adjustments are needed.

**Comment by soulteary** [comment]
If you are accustomed to using docker development, you can refer to this modification and use local SSO services instead of public services during the development process without ngork or slack.

https://github.com/outline/outline/pull/2549
