### ISSUE TITLE
Not possible to copy and paste a headline

### ISSUE THREAD

**Issue by MDXDave** [outline/outline#2425]
When copying a headline (e.g. `## July`) and pasting them, it does not copy the text, but only the Number sign (`#`)

**To Reproduce**
1. Enter a headline (e.g. `## July`)
2. Copy the headline
3. Paste the headline
4. You should see `#`instead of the title

**Expected behavior**
The copied title should be shown formatted (as headline 2 in this case)

**Screenshots**
https://user-images.githubusercontent.com/6099976/128325690-4fa9c4c0-faf7-452f-af44-aa58ff5c7451.mp4

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.58.2-0

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Brave
 - Version: 1.26.74 (Chromium: 91.0.4472.124)

**Comment by tommoor** [comment]
This will be fixe in the next release, thanks for filing
