### ISSUE TITLE
How to make hosted Outline app public/open for everyone?

### ISSUE THREAD

**Issue by shtefcs** [outline/outline#2426]
### Discussed in https://github.com/outline/outline/discussions/2412

<div type='discussions-op-text'>

<sup>Originally posted by **shtefcs** August  4, 2021</sup>
First of all, wonderful work. Simple, clean, and powerful. Exactly what I was looking for as an open-source project for a while.

We have self-hosted Outline, and I am using it to create documentation for our project Automatio.co. 

My question is how to make everything publicly available, and not locked under the registration gate? I mean on Collections and all documents under it?

We want to use Outline as public documentation, so everyone can access it and be indexable by search engines.

Is this possible with Outline? I can see its a perfect platform for such a thing, except I can't figure it out how to make everything public.</div>

**Comment by MDXDave** [comment]
Its not possible yet to share collections: #1160 

And as far as I know you can not make outline accessible without any authentication. 

A workaround is to share a document that has nested documents.

**Comment by shtefcs** [comment]
Thanks for the response. 

>A workaround is to share a document that has nested documents.
But what about collections? We have a collection to categorize the documents.

**Comment by shtefcs** [comment]
Honestly, it's really unfortunate that Outline is actually not made for public documents. It has everything it needs to be the great documentation software, where you can share documentation and wiki with a guess/users of your product.

**Comment by tommoor** [comment]
> @tommoor any plans to add this? I see multiple requests were made from early 2020.

Yes, there are plans to have this feature but it's further down the roadmap as we're focused on making a great product for internal documentation first and foremost. There are lot of tools on the market/OSS for public knowledge bases and very few for those behind authentication.

One option that I think could be pretty cool is to use Next.JS or something similar to grab documents from the Outline API at build-time, you could easily use it as a CRM for a static public site… just a thought :)

**Comment by tommoor** [comment]
Closing as a duplicate of #1160 to keep our issue board clean, but feel free to continue the discussion

**Comment by shtefcs** [comment]
>Yes, there are plans to have this feature but it's further down the roadmap as we're focused on making a great product for internal documentation first and foremost. There are lot of tools on the market/OSS for public knowledge bases and very few for those behind authentication.

>One option that I think could be pretty cool is to use Next.JS or something similar to grab documents from the Outline API at build-time, you could easily use it as a CRM for a static public site… just a thought :)

@tommoor Thanks for the prompt response and sorry for the bid delayed one from my side.

I totally get it now. Honestly, when I first saw Outline I said, how the heck we missed this great documentation?

![image](https://user-images.githubusercontent.com/1984909/129130686-f1b3aaf2-d761-4311-80c9-a1b5a9a3ce82.png)

And then my CTO deployed it and I started migrating our docs from the Ghost blogging platform to the Outline, without being aware it's just for internal docs. After I tried to make it public and dug a bit, I figured it out 🤦‍♂️.

Outline is really great, I love the simple UI, and the editor is so nice and smooth. In my opinion, everything is there except public docs. And I think you guys do need not much work to make it happen. 

By having the ability to create public Collections and docs, you would definitely expand your market by a lot. Because honestly, I was searching for a while good documentation software, especially Open Source, and I couldn't find the one which bought me as Outline.

Check this, there is at least 4,400 searches/month on Google for keyword **documentation software**.  And so many other combinations. It's really great market to enter, and I know you need just a little bit of work to make that.

![image](https://user-images.githubusercontent.com/1984909/129131885-0be1cb1a-a1e2-4541-a7fa-2aaf660c8bff.png)


> There are lot of tools on the market/OSS for public knowledge bases and very few for those behind authentication.

There are some solid, but Outline UI and UX seem way too better.

>One option that I think could be pretty cool is to use Next.JS or something similar to grab documents from the Outline API at build-time, you could easily use it as a CRM for a static public site… just a thought :)

But then we would need to rebuild this great UI from scratch, which would be overkill, right?

Anyway, great product, and I can't wait to see Outline move to public docs space soon.

Peace,

**Comment by aaptalking** [comment]
https://github.com/outline/outline/discussions/3533#discussion-4074952

**Comment by aaptalking** [comment]
HackMD, HedgeDoc, Outline - they all are 'closed' in their mindset and not recognising the trend and opportunities.

https://github.com/outline/outline/discussions/3533#discussion-4074952

**Comment by aaptalking** [comment]
They are all 'closed' as they are looking for Enterprise clients, they need to realize they have the potential to become new 'Wordpress' the world is looking for ..

HackMD has $4 per month plan .. if we ask them for domain .. they say, go for Enterprise plan.

**Comment by tommoor** [comment]
It was mentioned further up that this is on the roadmap

**Comment by Limezy** [comment]
Hi ! It's not ideal obviously, but meanwhile I was able to create a "visitor button" using passport.js req strategy. https://github.com/outline/outline/discussions/3143
The visitor user is a reader and has only access to some public collections.
Right now my main issue is that this reader can change his name, see the list of other users and when their last actions.
Hopefully I'll be able to set my "visitor" user as a guest once this will be done https://github.com/outline/outline/issues/2946

**Comment by jiinus** [comment]
"There are lot of tools on the market/OSS for public knowledge bases"

I need to disagree with this as I've been looking for two days now for an affordable solution for our small business. We would need multi-language and a custom domain, and haven't been able to find a hosted solution that would not cost north of 600$ / year, and I think that's a bit too much for a simple low-traffic knowledge base site (not looking for free, but affordable).

So I, for one, am in the queue waiting for the public access, otherwise Outline seems like a perfect solution for what we're looking for. :)

**Comment by serginho8** [comment]
Now it is possible to public share collections. Just click on the (...) and on "permissions". Great work!

**Comment by D1reW0lf** [comment]
Hi.

Did the option to share full collections on self-hosting get removed on the latest versions?
I can activate the option to share to the web on docs and sub-docs, but when trying to use it on the full collection, it doesn't allow to be selected. 

I'm self-hosting version 0.87.3 thru docker compose. 

Thank you.
