### ISSUE TITLE
firefox on android -> unreadable status bar

### ISSUE THREAD

**Issue by Snuupy** [outline/outline#2430]
On firefox on android in the home shortcut/install to home app, the statusbar is white and blocks the text from being read. For comparison, web apps such as [thelounge ](https://thelounge.chat/) have a [readable statusbar](https://i.imgur.com/heyh16z.png) at the top.

**To Reproduce**
1. open outline in firefox
2. install app to home
3. open installed app
4. see that the status bar is white

Please look at the top of the screenshots for the following:

firefox: https://i.imgur.com/LxZwLfn.png
chrome: https://i.imgur.com/NFsdXNF.png

**Expected behavior**

Statusbar should be black like in chrome (assuming dark mode in app and dark mode set for system). This bug does not apply when you visit outline in the browser via URL, it only shows up when the web app shortcut is added and "installed" as a PWA (progressive web app).

**Screenshots**

attached above

**Outline (please complete the following information):**
- Install: self-hosted
- Version: v0.58.2

**Mobile (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 11
 - Browser: Firefox stable and nightly both have this bug

**Comment by tommoor** [comment]
@iamsaumya don't suppose you have an android device?

**Comment by iamsaumya** [comment]
I don't manage a self-hosted outline yet 😅

**Comment by tommoor** [comment]
Invited you to a test instance incase it's useful

**Comment by iamsaumya** [comment]
I'm able to reproduce but only when the system is in light mode, and the app is in dark mode.

**Comment by Snuupy** [comment]
To clarify:

I always have outline theme setting selected to "system" to match the device.

I have taken screenshots of the various settings.

https://imgur.com/a/PdqerJd

The schema of the text in the screenshots is [device theme] + [outline theme].

`dark + system` means device theme is dark, outline theme is system.

`dark + dark` means device theme is dark, outline theme is dark

`light + light` means device theme is light, outline theme is light

device theme | outline theme | works in ff? | works in chrome?
-- | -- | -- | --
light | system | yes | yes
light | light | yes | yes
light | dark | yes | yes
dark | system | no | yes
dark | light | no | yes
dark | dark | no | yes

**Comment by iamsaumya** [comment]
Thank you so much for the details. In contrast, on my device (POCO X3) the results are quite opposite 😅 . Nonetheless, we at least know there is something going wrong here.  
 
device theme | outline theme | works in ff? | works in chrome?
-- | -- | -- | --
light | system | no | yes
light | light | no | yes
light | dark | no | yes
dark | system | yes | yes
dark | light | yes | yes
dark | dark | yes | yes

**Comment by iamsaumya** [comment]
@Snuupy Could you please check your firefox browser theme settings? 

The above results were when I had a dark theme selected for the browser. The status bar has become readable in PWAN after changing it to follow the device theme.

**Comment by Snuupy** [comment]
> @Snuupy Could you please check your firefox browser theme settings?
> 
> The above results were when I had a dark theme selected for the browser. The status bar has become readable in PWA after changing it to follow the device theme.

Whether I select "Follow device theme" or "Dark", the status bar is still white using the PWA.

**Comment by tommoor** [comment]
For future reference, search the codebase for `theme-color` to find places where we set the status bar color based on theme.

**Comment by Snuupy** [comment]
replyl

**Comment by Snuupy** [comment]
reply
