### ISSUE TITLE
Problem with youtube video embed

### ISSUE THREAD

**Issue by dabvastur** [outline/outline#2451]
**To Reproduce**
1. Create or edit a document
2. Embed youtube video

**Expected behavior**
Be able to see the videos but not

**Screenshots**
https://imgur.com/a/vgHyNqd

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: 0.58.0 (09b73401de14624c7f0928d0afef92f8f972fad8)

**Desktop (please complete the following information):**
 - OS: Linux CentOS
 - Browser: Chrome, Edge and Firefox tested
 - Version: Chrome: Versión 92.0.4515.131 (Build oficial) (64 bits)

**Mobile (please complete the following information):**

**Comment by tommoor** [comment]
Hi, this doesn't seem to be a problem with Outline – not all YouTube videos can be embedded, it's a setting per-video - this seems like the screen you'd see in that scenario
