### ISSUE TITLE
Ao tentar editar ou escrever novo documento no KB, aparece erro "Algo inesperado aconteceu"

### ISSUE THREAD

**Issue by FretonautaDanny** [outline/outline#2452]
Ao tentar editar ou escrever novo documento no KB, aparece erro "Algo inesperado aconteceu - Desculpe, ocorreu um erro irrecuperável - nossos engenheiros foram notificados . Tente recarregar a página, pode ter sido uma falha temporária."

Ao verificar detalhes indica: "NotFoundError: Falha ao executar 'removeChild' em 'Nó': O nó a ser removido não é filho deste nó."

Tentei limpar caches, sair e  entrar novamente, e nada. 

Para reproduzir as etapas para reproduzir o comportamento:
- Acesso qualquer pasta. Vou em "+ Novo doc". Ao tentar escrever, o sistema indica o erro. 

Segue captura de tela
![image](https://user-images.githubusercontent.com/89043119/129622214-c5f4f9f5-d161-413e-bf5c-a7389e27d03b.png)

Desktop:
Navegador: Crome

**Comment by tommoor** [comment]
Please fill out the bug report template. We would need to know which version of the software you are running and ideally get a stack trace for the error from the developer tools to action – thanks!

**Comment by matbrgz** [comment]
Olá como posso te ajudar? Vi que escreveu tudo em português, mas esse GitHub utilizamos como língua padrão o idioma inglês. Se quiser pode me chamar por email matbrgz@gmail.com que tento te ajudar.
