### ISSUE TITLE
Theme icon is not updated after changing the theme

### ISSUE THREAD

**Issue by iamsaumya** [outline/outline#2472]
While investigating #2430 I updated the theme of the app. It seems that the Icons and selected state of the menu are not updating after changing the theme of Outline. 

**To Reproduce**
1. Go to Account Menu
2. Change the theme from dark -> light or light -> dark
3. Open the Account menu again
4. See the prev state icon and theme submenu is not updated

**Expected behavior**
Icon and menu state should be updated.

Please note: I'm unable to repro this on localhost. 

**Screenshots**

https://user-images.githubusercontent.com/40148448/130438898-f78d6869-4b3c-4c82-bc8d-d0a2af7fc0f1.mp4

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Brave, firefox

**Comment by tommoor** [comment]
I found and fixed the same issue last night – d8ad2fc1a2894dadddd43fe9e960c01dcfb98c32 – just not deployed yet :)
