### ISSUE TITLE
Add button to delete team

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2476]
### Client

- At the bottom of "Settings -> Team -> Details" add a section "Delete Team" to match "Delete Account" on the profile screen
- Clicking the button should show a modal confirmation
- The modal confirmation should have a textarea input with the optional ability to add any suggestions to improve Outline, below that it should have a confirmation text input which requires entering the name of the team exactly to proceed.
- When confirmed the team should be marked as soft-deleted via the API
- The client should be signed out locally

### API

- New api endpoint `team.delete` (note, not plural)
- New `teamDeleter` command
- Command should soft delete (touch `deletedAt`) and store an event for the deletion with the note from the confirmation modal in the `data` object.

#### Design ref

This is what the "Cancel subscription" modal looks like in production, I'm imagining "delete team" to be very similar with adjusted text and the extra input for confirmation.

![image](https://user-images.githubusercontent.com/380914/130636800-ebdd787f-be00-479d-93fb-0632b8e3259f.png)

#### Github equivalent

![image](https://user-images.githubusercontent.com/380914/130637047-c848ae03-016e-45be-954b-7ea27d7d5cae.png)

**Comment by iamsaumya** [comment]
You have explained the solution so well that I feel this could be a good first issue 🙈
