### ISSUE TITLE
Collection cover images

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2478]
Many similar products in the space allow adding banner or cover images to make areas of the knowledge base feel more unique and branded. It would be nice to explore this as a possibility.

**Comment by michaelhofer** [comment]
That's a very nice idea indeed and help to better distinguish the different areas better.

**Comment by rvk86** [comment]
Wondering if there's been any progress made on this topic? We've recently started using outline as our internal knowledge sharing tool, and I received feedback from some colleagues that this would make the tool much more fun to use. Not only at the "collection" level, but also for individual documents. The banner image could then also be use for pinned documents.

**Comment by KumailP** [comment]
Hi, is anyone working on this?

**Comment by SaadBazaz** [comment]
Would love to have cover photos/banners on pages.
