### ISSUE TITLE
Show collection / parent document in editor

### ISSUE THREAD

**Issue by tommoor** [outline/outline#248]
- Display the collection or parent document in the top left
- Clicking should show a variant of the move dialog that would let you choose where it will be saved.

**Comment by tommoor** [comment]
![3 1 document - default](https://user-images.githubusercontent.com/380914/32998404-a456acde-cd4f-11e7-889b-1f588b82c646.png)

**Comment by jorilallo** [comment]
I think clicking on the path items should open them. Maybe leave the move on hover action?

**Comment by tommoor** [comment]
Yea, with this design I agree.
