### ISSUE TITLE
Sidebar links should not reserve space for "..." menu

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2486]
Currently a large space is reserved to the right of every link in the sidebar for the "..." menu to appear when you hover. Instead it should overlay ontop of the content to allow for another ~24px of horizontal space before the text wraps.

![image](https://user-images.githubusercontent.com/380914/130713378-a5ce4f28-98e8-465a-a3ae-c4f5b99c21b6.png)

**Comment by charlesharries** [comment]
I'd like to take a swing at this one, if that's alright? I've spotted #2695 as well so I can take that into account while I build this one out.

It looks like Notion appends the `[...] [+]` buttons to the document title on `mouseover`:

![ellipsis-over](https://user-images.githubusercontent.com/20623195/139528237-63b3c75a-b72b-479b-99ac-dd757e76b0a2.gif)

But I don't see why toggling a `display: none` on CSS `:hover` wouldn't work just as well. I'll have a test across browsers and see what I can come up with.

**Comment by tommoor** [comment]
By all means, give it a go 👍
