### ISSUE TITLE
Send all emails in worker process

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2505]
Follow on to #2495 – currently some emails are sent from the web process, originally due to them needing database models to construct the email.

We should refactor the `Mailer` setup so that there is a queue/processor combo that has a single job of taking email content and delivering it, currently the queue takes a "template" and some parameters which the email is then constructed with. It seems like the queue should be moved until later in the process for higher reliability. We usually have the needed models in the web process anyway.

Refactors as part of this:

`/server/mailer` -> `server/emails/index.js`
`/server/emails/*` -> `server/emails/templates/*`
`/server/queues/processors/emails.js` should contain SMTP sending logic.

Depends on #2460

**Comment by soulteary** [comment]
Considering flexibility and stability, perhaps the mail function should be split out to support the use of API calls to reduce the complexity of the mail function design.

There are already many mature, stable, and low-cost alternatives to public cloud or SaaS services.

**Comment by tommoor** [comment]
SMTP is the most compatible email API ;)

**Comment by soulteary** [comment]
> SMTP is the most compatible email API ;)

Hahaha you are right

What I wrote above is not clear enough, I am referring to this type of service:

- https://aws.amazon.com/ses/
- https://www.alibabacloud.com/product/directmail
- https://www.mailgun.com/email-api/

**Comment by almereyda** [comment]
A self-hostable alternative to commercial transactional APIs, for those working from this requirement, is https://github.com/postalserver/postal
