### ISSUE TITLE
Move code under `/src` directory

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2511]
After https://github.com/outline/outline/pull/1660 is merged It would be nice to make this large code move.

`/app` -> `/src/frontend`
`/server` -> `/src/backend/`
`/shared` -> `/src/shared`
`/public` -> `/src/public`

ref: https://github.com/outline/outline/discussions/1269

**Comment by tommoor** [comment]
I think it would make sense to add some root aliases at the same time for each of these folders to undo some of the `../../../` mess in server directories as things become less flat.

.e.g `../../../utils/slack` can become `~/backend/utils/slack`, or `@backend/utils/slack`

**Comment by soulteary** [comment]
It is necessary to adjust the existing catalog. In addition, the package.json used by the organization project should be split.
