### ISSUE TITLE
Translation not updated

### ISSUE THREAD

**Issue by Sylvenas** [outline/outline#2533]
**To Reproduce**

0. Switch language to Chinese(zh_CN)
1. Go to 'https://xxxx.getoutline.com/settings/import-export'
2. See error

**Expected behavior**
Import section is correctly translated，but the export section shows English.

**Screenshots**
![](https://p6.music.126.net/obj/wo3DlcOGw6DClTvDisK1/10696900362/b644/f592/c0ef/3b1082f2d49b285f0d06b1d98e187c77.png)

**Comment by Sylvenas** [comment]
I checked the source code and found the reason for the bug; 

The `defaults` property of the [`Trans` component](https://github.com/outline/outline/blob/main/app/scenes/Settings/ImportExport.js#L187s) in the source code has been modified, but the corresponding key in the [`translation.json`](https://github.com/outline/outline/blob/main/shared/i18n/locales/zh_CN/translation.json#L499) file has not been modified, so they don't match up.

This is just one example of a translation mismatch, there should be many [other mismatches](https://github.com/outline/outline/blob/main/app/scenes/Settings/Tokens.js#L48).

As a native Chinese speaker and fluent English/Japanese speaker, I am happy to provide translation assistance，is there any batch processing tool?

**Comment by tommoor** [comment]
Hi, it is expected - we support many languages and not every string is translated in all languages. Your translation contributions are welcomed, see this doc:

TRANSLATION.md
