### ISSUE TITLE
`/_health` endpoint no longer working in v0.59.0

### ISSUE THREAD

**Issue by syphernl** [outline/outline#2536]
Since `v0.59.0` the `/_health` endpoint no longer works. Initially it returned `OK` but since `v0.59.0` this seems to be broken.

**To Reproduce**
1. Go to '/_health'
2. Do not see `OK`

**Expected behavior**
A plain-text page with `OK`

**Outline (please complete the following information):**
- Install: self-hosted
- Version: v0.59.0

**Misc**
- We are using `WEB_CONCURRENCY=1`

**Comment by tommoor** [comment]
What are you getting instead, the app?

**Comment by syphernl** [comment]
Yes. In case I am not logged in (e.g. incognito mode) it seems to redirect me to `/` instead (showing the login buttons). 
Going to `/_health` while logged in shows just the sidebar and no content on the right.
