### ISSUE TITLE
urlId does not work for the documents.info API endpoint

### ISSUE THREAD

**Issue by linushstge** [outline/outline#2537]
In the API docs the urlId is documented for an alternative to the id (uuid).
https://www.getoutline.com/developers#tag/Documents/paths/~1documents.info/post

**To Reproduce**
if the API is called with the urlId instead of the id it returns a 404.

**Expected behavior**
document resource should be returned

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.58.1

**Comment by tommoor** [comment]
Hi @linushstge – you would still pass the urlId string as the `id` parameter, is that what you're doing?

**Comment by linushstge** [comment]
> Hi @linushstge – you would still pass the urlId string as the `id` parameter, is that what you're doing?

Yes exactly as you described. tested with multiple correct documents and always getting a 404.

**Comment by tommoor** [comment]
The production application uses this functionality so the endpoint is for sure working, please provide an example of your code.

**Comment by linushstge** [comment]
Example Document:
```
ID: a9a9ec1d-d087-4bf5-a3d6-754598f32949
UrlId: WBts8grboq
```

Retrieve document by ID:
![documents-info-id](https://user-images.githubusercontent.com/2674751/132585039-c9c284da-e676-4bd4-97fb-850abe648fa0.png)

Retrieve document by UrlId:
![documents-info-urlid](https://user-images.githubusercontent.com/2674751/132585052-61925ada-7450-4d2a-a9ee-dc10cd19eb26.png)

**Comment by tommoor** [comment]
Discussed in DM, the key is to include the slug portion of the `urlId`, e.g. `my-doc-title-WBts8grboq`
