### ISSUE TITLE
Unable to login by using OIDC provider, KeyCloak and VMI

### ISSUE THREAD

**Issue by mzch** [outline/outline#2542]
Refer to #2535

I run OIDC provider, [KeyCloak](https://github.com/keycloak/keycloak) and [Verify My Identity](https://github.com/videntity/vmi) and try to login to Outline by using them, but fail.
When using KeyCloak, KeyCloak shows login form and I can login successfully but Outline shows login screen again, never show app home. KeyCloak and Outline has no trouble log.
When using VMI, it reported an error as below in getting OIDC token:
```
TypeError: Object of type 'bytes' is not JSON serializable
```
The VMI developer told me that Outline would probably have an encoding trouble. I googled it, and found this issue seemed to be around utf-8 encoding.

When using Google OAuth or Slack OAuth, I can login successfully and see app home.

**To Reproduce**
1. Set OIDC provider into `.env`
2. `npm start`
3. Go to login screen
4. Click `Contine with OpenID Connect` and  login

**Expected behavior**
Login successfully and show app home.

**Screenshots**
When using VMI, an error message shows as below:
<img width="1497" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/132623861-f1c6cc85-7dc7-4a19-99c2-beb6d7cc35cf.png">

**Outline (please complete the following information):**
- Install: self hosted
- Version: `0.59.0` (`commit 2f5cf90cb7b340fa1e8d7758fea1e3bf702b7fa5`)

**Comment by tommoor** [comment]
There are no error messages in the server logs? You're the first one to try it with KeyCloak, so it's not overly surprising there might be teething issues. For Google OIDC I had to set the following:

```bash
OIDC_CLIENT_ID=REDACTED
OIDC_CLIENT_SECRET=REDACTED
OIDC_AUTH_URI=https://accounts.google.com/o/oauth2/v2/auth
OIDC_TOKEN_URI=https://oauth2.googleapis.com/token
OIDC_USERINFO_URI=https://openidconnect.googleapis.com/v1/userinfo
OIDC_DISPLAY_NAME=OpenID Connect
OIDC_SCOPES=openid email profile
```

**Comment by mzch** [comment]
Yes. KeyCloak outputs no log. My config is as below:

```
OIDC_CLIENT_ID=[client_id]
OIDC_CLIENT_SECRET=[secret]
OIDC_AUTH_URI=https://oidcc.com/auth/realms/letlive/protocol/openid-connect/auth
OIDC_TOKEN_URI=https://oidcc.com/auth/realms/letlive/protocol/openid-connect/token
OIDC_USERINFO_URI=https://oidcc.com/auth/realms/letlive/protocol/openid-connect/userinfo
OIDC_DISPLAY_NAME=OpenID
OIDC_SCOPES=openid profile email
```

oidcc.com is my KeyCloak instance.

**Comment by jok2** [comment]
I've got it running with Keycloak. 
The OIDC_Settings are like mine. Perhaps something on the Keycloak side?
Client ID, Enabled, Standard Flow enabled, Direct Access Grants enabled, Root URL and the Valid Redirection URL, Admin URL and Web Origins point to the Outline URL, Client Scopes include email and profile.

**Comment by mzch** [comment]
I missed the following messages:
```
Sep 10 19:17:59 n25 yarn[1007729]: 2021-09-11T02:17:59.518Z http   <-- GET /auth/oidc.callback?state=xbxrc5&session_state=48331820-21cc-462c-854f-c7fa9806cfa4&code=5c8b54cd-15d2-4b04-9cc3-b408349dabcf.48331820-21cc-462c-854f-c7fa9806cfa4.091aec03-9f94-45fb-b832-7639117df90c
Sep 10 19:17:59 n25 yarn[1007729]: 2021-09-11T02:17:59.606Z http   <-- GET /static/vendors~authenticated-routes~keyed-document.7b1d601669c644fc32ca.js.LICENSE.txt
Sep 10 19:17:59 n25 yarn[1007729]: 2021-09-11T02:17:59.616Z http   --> GET /static/vendors~authenticated-routes~keyed-document.7b1d601669c644fc32ca.js.LICENSE.txt 200 10ms 938b
Sep 10 19:17:59 n25 yarn[1007729]: ClientError [UnauthorizedError]: The maximum number of teams has been reached
Sep 10 19:17:59 n25 yarn[1007729]:     at new AuthenticationError (/srv/outline/outline/build/server/errors.js:32:34)
Sep 10 19:17:59 n25 yarn[1007729]:     at accountProvisioner (/srv/outline/outline/build/server/commands/accountProvisione
r.js:42:11)
Sep 10 19:17:59 n25 yarn[1007729]:     at runMicrotasks (<anonymous>)
Sep 10 19:17:59 n25 yarn[1007729]:     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
Sep 10 19:17:59 n25 yarn[1007729]:   redirectUrl: 'https://letlive.jp',
Sep 10 19:17:59 n25 yarn[1007729]:   id: 'authentication_required'
Sep 10 19:17:59 n25 yarn[1007729]: }
Sep 10 19:17:59 n25 yarn[1007729]: 2021-09-11T02:17:59.650Z http   --> POST /auth/oidc.callback?state=xbxrc5&session_state
=48331820-21cc-462c-854f-c7fa9806cfa4&code=5c8b54cd-15d2-4b04-9cc3-b408349dabcf.48331820-21cc-462c-854f-c7fa9806cfa4.091ae
c03-9f94-45fb-b832-7639117df90c 302 132ms 129b
```
Is this related?

**Comment by mzch** [comment]
I found this cause. An undocumented(?) environment variable `DEPLOYMENT` was not set.
I set `DEPLOYMENT=hosted` in `.env`, then I can login successfully. Thanks!

**Comment by tommoor** [comment]
Hi @mzch – it's undocumented because you shouldn't use it, the variable sets options for the cloud hosted environment. It was failing because you already had a team and the OSS edition should only host one team. The best thing to do is unset the env variable and reset your database.

**Comment by mzch** [comment]
I know. Perhaps that's why KeyCloak and Google has the same email account. Is it impossible to resolve. such a case?
