### ISSUE TITLE
Printing documents in Firefox produces blank output

### ISSUE THREAD

**Issue by ktvoelker** [outline/outline#2543]
When I try to print a document in Firefox, it comes out blank. It works in Chrome.

**To Reproduce**
1. Go to any document.
2. Ask Firefox to print the document.
3. See that the print preview shows a blank page except for the headers and footers added by Firefox itself.
4. Save to PDF and open the PDF - see that it matches the blank preview.

Note: longer documents seem to produce multiple blank pages.

**Expected behavior**
When printing a document in Firefox, the content of the document should be printed.

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: macOS 11.5.1
 - Browser: Firefox
 - Version: 92.0

**Comment by tommoor** [comment]
Hi @ktvoelker – unfortunately I'm unable to reproduce on the same setup – could I ask where are you triggering print from? `cmd`+`p` and from the file menu seem to work here.

**Comment by ktvoelker** [comment]
@tommoor Well...I haven't changed anything on my end, but I can't reproduce it anymore either.

It had been reliably failing on every document, every time. I used both the keyboard shortcut and the menu.

**Comment by ktvoelker** [comment]
Wait a minute! I think my memory was bad (or I was prone to suggestibility from your comment about ways of launching print).

It fails when using the ... menu *in the Outline UI* and selecting Print from there. But it works when hitting the keyboard shortcut or selecting Print from the browser's own menu.

**Comment by ktvoelker** [comment]
Sorry my original description was not very accurate in that regard.
