### ISSUE TITLE
Local development environment issues

### ISSUE THREAD

**Issue by soulteary** [outline/outline#2548]
**To Reproduce**

0. I've test it on macos 11.4 with node 14 / node 16, docker node14-alpine, node14
1. git clone a clean copy.
2. run `npm run build` or `npm run build:webpack`
3. trigger build error, regardless of whether you set `NODE_ENV=production`

```bash
yarn build:webpack
yarn run v1.22.11
$ webpack --config webpack.config.prod.js
Hash: f9489632113e5b6e87c9
Version: webpack 4.44.1
Time: 635ms
Built at: 2021/09/11 上午1:33:54
 4 assets
Entrypoint main = runtime.329aa36197b1b7ec6528.js runtime.329aa36197b1b7ec6528.js.map main.061a07767b3c1a3c197e.js main.061a07767b3c1a3c197e.js.map
[0] multi ./app/index 28 bytes {main} [built]
[xATA] ./app/index.js 143 bytes {main} [built] [failed] [1 error]

ERROR in ./app/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: EISDIR: illegal operation on a directory, read
 @ multi ./app/index main[0]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [YuTi] (webpack)/buildin/module.js 497 bytes {0} [built]
    [la58] ./node_modules/html-webpack-plugin/lib/loader.js!./server/static/index.html 1.87 KiB {0} [built]
    [yLpj] (webpack)/buildin/global.js 472 bytes {0} [built]
        + 1 hidden module
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Outline code branch: `main`, https://github.com/outline/outline/commit/231ab2da03b81c13110e8b09aaaea632c06430fc

**Comment by soulteary** [comment]
In fact, I originally planned to provide a clean and quick-start local environment for problems like [#2422](https://github.com/outline/outline/issues/2422), and then discovered this problem.

But I see that the CI environment is normal. After repeated testing, I think it is necessary to inform the development team about this, because it may prevent the intervention of general developers unless they directly conduct secondary development based on the ancient docker image.

**Comment by soulteary** [comment]
I found the problem. The outline in the docker-compose.yml configuration used in the project is because the way of mapping local and docker files is a bit outdated.

After the docker container is started, `npm run dev` will create a package.json folder by mistake, causing the above problems.

I will create a pr later to fix the outdated docker-compose.yml configuration file to make local development easier.

**Comment by tommoor** [comment]
Honestly the `outline` inside that docker-compose file should just be removed entirely, it's not used in dev.

**Comment by soulteary** [comment]
> Honestly the `outline` inside that docker-compose file should just be removed entirely, it's not used in dev as the nodejs app is not run inside docker for development.

Hi 👋, @tommoor .

I submitted a new pr, which describes why I want to add, rather than delete or modify the currently used compose file and dockerfile.

https://github.com/outline/outline/pull/2549

Hope it is useful.
