### ISSUE TITLE
Slack integrations are offered, even when no Slack secrets are provided

### ISSUE THREAD

**Issue by almereyda** [outline/outline#2553]
**To Reproduce**

1. Create a Slack-independent Outline instance by using one of the other authentication providers and log in to it.
  Do not provide `SLACK_KEY` and `SLACK_SECRET`
2. Click on 'Settings'
3. Scroll down to 'Integrations'
4. See Slack offered and click it
5. Click on the 'Add to Slack' or 'Connect' buttons

**Expected behavior**

Slack is not offered as an integration.

**Outline:**

- Install: self hosted
- Version: 2aca760

**Comment by bosmak** [comment]
@almereyda I found this issue when I was looking at how to disable the integration as well.

I tried this on a docker container at my machine and found that commenting out all the `SLACK` env variables disables the Slack button. The example comes with some placeholders in the keys, allowing the default values to remove the switch.

Now I only see the OIDC integration (that I configured) and log in with an e-mail button (which I will look at how to remove).
