### ISSUE TITLE
Collaboration state not shared between windows of the same user session

### ISSUE THREAD

**Issue by almereyda** [outline/outline#2554]
**To Reproduce**

1. Create a new document
2. Open it in a second window
  The presence indicator will show that you are connected to the document session, and the Websocket stream of events will indicate the presence of both sessions with separate UUIDs
3. Type in the first window
  The changes are not reflected in the second
4. Type in the second window
  The changes are not reflected in the first

**Expected behavior**

I am able to use my own user account to create multiple editing sessions on the same document. This is useful for presentations, where one input screen is on the laptop, and the other on a projector.

**Outline (please complete the following information):**
- Install: self hosted
- Version: 2aca760

**Comment by almereyda** [comment]
Incidentally, the editing state would be shared with a passive, view-only session observing the document.

**Comment by tommoor** [comment]
Please see #811 – this feature is in progress.

**Comment by almereyda** [comment]
Thank you, sorry for the noise.
