### ISSUE TITLE
Ordered list starts with 0 when importing Word document

### ISSUE THREAD

**Issue by lemker** [outline/outline#2563]
**To Reproduce**
1. Import Word document with ordered list
2. Observe that Outline parses the list and starts it at 0

**Expected behavior**
Ordered list should start with 1 (or the original starting number in the Word document).

**Screenshots**
![image](https://user-images.githubusercontent.com/31901553/133169957-52939463-ff88-4f6a-aaa0-aa57996fb40b.png)

![image](https://user-images.githubusercontent.com/31901553/133169840-e177a3a6-d5c3-4e88-ad3c-eeacf9ff059d.png)

**Outline:**
- Install: getoutline.com

**Desktop:**
 - OS: Windows 10 Pro
 - Browser: Microsoft Edge
 - Version: 93.0.961.47

**Comment by tommoor** [comment]
Hi @lemker if you're able to upload an example file that this problem reproduces with that would be useful. I don't have access to word and a docx exported from Google Docs doesn't seem to have the issue.

**Comment by lemker** [comment]
Please find a test file attached. I tested this file again, and on first import the list ordering was fine. When I edited, then saved the page in Outline, it reset the list starting at 0.

[Ordered Lists.docx](https://github.com/outline/outline/files/7163651/Ordered.Lists.docx)

**Comment by tommoor** [comment]
Thanks, this has been fixed and deployed
