### ISSUE TITLE
Unable to migrate the database in docker

### ISSUE THREAD

**Issue by Misly16** [outline/outline#2570]
When running `npm run sequelize:migrate --env production-ssl-disabled` an error is returned: The server does not support SSL connections.

**To Reproduce**
run the command `npm run sequelize:migrate --env production-ssl-disabled` inside the container.
The error will be returned.

**Expected behavior**
The database to migrate

**Outline**
- Install: docker outlinewiki/outline:0.59.0
- Version: docker tag: 0.59.0

**Comment by tommoor** [comment]
Do you have env `PGSSLMODE=disable` set?

**Comment by Misly16** [comment]
Yep

**Comment by tommoor** [comment]
I'd make sure your `DATABASE_URL` doesn't include any ssl flags, beyond that I'm at a loss.

**Comment by Misly16** [comment]
I can confirm there's no ssl flags on the db url, initially after setting PGSSLMODE to disable it fixed the errors on the server itself but obviously can't migrate. Also I'm currently on 0.41 which works if that helps in anyway.

**Comment by Misly16** [comment]
Managed to fix this by setting the env value NODE_ENV=production-ssl-disabled
