### ISSUE TITLE
Delete collection exports

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2585]
### Discussed in https://github.com/outline/outline/discussions/2574

<div type='discussions-op-text'>

<sup>Originally posted by **adelicato** September 15, 2021</sup>
It could be interesting to have the ability to delete an exported collection (in order to clean up space on the storage). Thank you in advance</div>

**Comment by iamsaumya** [comment]
I have almost implemented this. Do we want to show the new state `Deleted` and the person's name who deleted the export?

**Comment by tommoor** [comment]
I don't think it's needed, we can create an `event` for this and it will show up in the event history.

**Comment by iamsaumya** [comment]
@tommoor, I just saw you had added the `migration required` tag. Does that mean we need `deletedById`?

**Comment by tommoor** [comment]
I had originally thought that but with an audit event it seems unnecessary for this particular entity 🤷
