### ISSUE TITLE
No email sent, no logs when inviting via email, but UI says it was successful

### ISSUE THREAD

**Issue by chase-replicated** [outline/outline#2603]
I've set up my SMTP settings from Mandrill in the .env. I was getting an error that I believe went away after setting the new flag "SMTP_SECURE" to false, but now there are no logs regarding mail. I set DEBUG=emails,mailer  but the only logs I see are 

Sequelize CLI [Node: 14.17.6, CLI: 6.2.0, ORM: 6.3.5]

Loaded configuration file "server/config/database.json".
Using environment "production".
No migrations were executed, database schema was already up to date.
Done in 0.80s.
yarn run v1.22.5
$ node ./build/server/index.js

Is your team enjoying Outline? Consider supporting future development by sponsoring the project:

https://github.com/sponsors/outline

**To Reproduce**
1. Set:
SMTP_HOST=company.com
SMTP_PORT=587
SMTP_USERNAME=value@domain.com
SMTP_PASSWORD=XXXXXXX
SMTP_FROM_EMAIL=noreply@domain.com
SMTP_REPLY_EMAIL=noreply@domain.com
SMTP_SECURE=true
DEBUG=emails,mailer
2. Run outline
3. Invite a new member
4. view stdout / system logs of container
5. View Mandrill statistics, no email received.

**Expected behavior**
See logs of some sort, have the mail go through and reach Mandrill

**Outline (please complete the following information):**
- Install: self hosted
- Version: latest(0.59.0)

**Desktop (please complete the following information):**
 - OS: Docker image outlinewiki/outline:latest
 - Browser Firefox
 - Version 92.0

**Comment by tommoor** [comment]
Are you sure you're running the latest docker image unedited? I ask because it looks like migrations are attempting to run which wouldn't be the case typically.
