### ISSUE TITLE
Trying to Delete user via API since he can't log in but can't generate API token

### ISSUE THREAD

**Issue by chase-replicated** [outline/outline#2604]
We have a user that when they log in, they see the screenshot I've attached. I was going to try and delete the user and recreate, but when I try to create an API token, nothing is present on the screen afterwards. (screenshot 2)

**To Reproduce**
1. Settings
2. Account | API Tokens
3. Click "New Token"

**Expected behavior**
A token is generated that I can use to delete users

**Screenshots**
<img width="462" alt="image" src="https://user-images.githubusercontent.com/82064318/134431429-10ec0184-aa48-4f60-a0a8-d0d3870cf816.png">

![image](https://user-images.githubusercontent.com/82064318/134431500-2e5bd89d-cb4b-4a28-96de-2caa085f246c.png)

Outline (please complete the following information):

    Install: self hosted
    Version: latest(0.59.0)

Desktop (please complete the following information):

    OS: Docker image outlinewiki/outline:latest
    Browser Firefox
    Version 92.0

**Comment by tommoor** [comment]
When/where does the "Looks like something broke!" error appear?

**Comment by chase-replicated** [comment]
Happened after the user signed in via Google SSO. I was able to manually connect to the database and delete the user, which allowed him to log in, but I'm still not able to generate an API key.

> When/where does the "Looks like something broke!" error appear?
