### ISSUE TITLE
Per-group visibility settings

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2616]
### Discussed in https://github.com/outline/outline/discussions/2614

<div type='discussions-op-text'>

<sup>Originally posted by **dmezh** September 27, 2021</sup>
Currently, Outline only lets non-admins see groups that they are themselves members of (commit 43493fcbbdf89d38b37cb0eb82b49ef1027c193b).

Per-group visibility settings would be great, because then users could use groups to more effectively share private collections. A toggle that makes the group 'private' or 'public' would accomplish this.</div>

**Comment by iamsaumya** [comment]
I need your advice here - What should when a public group is made private? Someone who is not present in the group has already used the group to access their private collection. Should we let it be or remove the group from the collection? 

Personally - I would remove the group from accessing the collection.

**Comment by tommoor** [comment]
I think that the complexity of calculating which collections the group would need to be removed from is hard to grasp, it wouldn't be easy to explain those knock-on effects in the UI either. For that reason I'd say the group should stay and there should be an exception that enables always viewing groups that are added to collections you can manage.

**Comment by iamsaumya** [comment]
What if we only change the group collection membership to `view only` if the collection is `private` or `view only`. Any thoughts?  

Btw the more I think about the intent of changing the visibility of a group and I think there is no harm in keeping the `collection-group` memberships as it is even if the group visibility changes. What's the harm? Somebody had added the group purposely.

**Comment by tommoor** [comment]
> keeping the collection-group memberships as it is even if the group visibility changes

Yes definitely, shouldn't touch memberships at all
