### ISSUE TITLE
User-facing error with "SQLite database connection is busy"

### ISSUE THREAD

**Issue by dmezh** [outline/outline#2624]
Have not been able to reproduce, but we got the Something Unexpected Happened page with this (domain name replaced and random string replaced):

```
[Exception... "SQLite database connection is busy"  nsresult: "0x80630001 (NS_ERROR_STORAGE_BUSY)"  location: "JS frame :: https://[self-hosted Outline instance]/static/authenticated-routes.[random hex string].js :: Starred/< :: line 1"  data: no]
```

This happened right after being prompted to sign in and signing in with OIDC. The error does not go away by reloading the page, but Outline overall is working fine, including in a private browsing window on the same machine for the same user.

Nothing out of the ordinary seems to be in the Outline logs. After clicking reload, a bunch of normal-looking GETs and POSTs appear, but the Something Unexpected page does not go away.

```
...
2021-10-03T01:01:23.125Z http   --> POST /api/documents.list 200 76ms 137b
2021-10-03T01:01:23.136Z http   <-- POST /api/documents.starred
2021-10-03T01:01:23.138Z http   <-- POST /api/collections.list
2021-10-03T01:01:23.164Z http   --> POST /api/documents.starred 200 28ms 140b
2021-10-03T01:01:23.168Z http   --> POST /api/collections.list 200 30ms 1.79kb
```

**Comment by tommoor** [comment]
Seems to be a very esoteric browser issue accessing local storage, i'd try restarting your browser. I think in this instance a "something went wrong" might be the best we can do.

**Comment by tommoor** [comment]
Seems to be a very esoteric browser issue accessing local storage, i'd try restarting your browser. I think in this instance a "something went wrong" might be the best we can do.

**Comment by dmezh** [comment]
Ah, seeing as this is a browser-side problem, I'll close the issue. Thanks @tommoor; I agree the "something went wrong" is probably the best we can do here.
