### ISSUE TITLE
Syntax highlighing disappears after changing language

### ISSUE THREAD

**Issue by dmezh** [outline/outline#2628]
Syntax highlighing disappears after changing language of code block and saving page. Highlighting also does not change after selecting a different language, saving the page, and refreshing.

**To Reproduce**
1. Go to any populated code block
2. Click on language dropdown in upper right corner, choose a different language
3. Save the document
4. Syntax highlighting disappears
5. Refresh page -> syntax highlighting comes back

**Expected behavior**
Syntax highlighting should not disappear when saving page, and changes should be reflected without saving and refreshing page.

Self-hosted Outline 0.59.0
*Note: I can't reproduce this behavior on app.getoutline.com*

 - OS: Windows 10
 - Browser: Chrome
 - Version: 94.0.4606.61

**Comment by tommoor** [comment]
If you can't reproduce on getoutline.com then it's likely fixed since the last OSS release, there have been several editor fixes. It's also fixed if your team has collaborative editing enabled.
