### ISSUE TITLE
Custom colors for collection icons don't show up in desktop browser

### ISSUE THREAD

**Issue by bjj** [outline/outline#2658]
You can choose and save a hex value for a collection icon, but it doesn't display on desktop.

You can load the same notebook on Android mobile and it does show up.

**To Reproduce**
1. Change the icon color to a hex value
2. Observe the icon is the default color in the collection list

**Expected behavior**
Icon is desired hex color

**Outline (please complete the following information):**
- Install: self host, but also reproduces on getoutline
- Version: 0.59.0 docker image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox, Chrome

**Mobile (please complete the following information):**
(works!)
 - Device: Pixel 2XL
 - OS: Android 11
 - Browser Stock? using "installed"

**Comment by tommoor** [comment]
Are you in dark mode? Dark colors are changed to white to ensure they are visible when in dark mode.

**Comment by bjj** [comment]
Yes, that's probably it, since the phone version chose a light theme. It shows up if I choose a lighter color. The rule is probably too sensitive: `964B00` is perfectly visible in the preview against a dark screen. I'd never use it for text, but it's fine as an icon.

It is confusing that it showed me the preview and I accepted it (in my selected theme) and it didn't show up.
