### ISSUE TITLE
Request parameter 'state' is not long enough for some OIDC server

### ISSUE THREAD

**Issue by Crownor** [outline/outline#2663]
I build a self-host outline and a self-host OIDC server authelia through docker. But when trying to login through OIDC, it returns auth-error for the reason:
  `AuthorizationError: The state is missing or does not have enough characters and is therefore considered too weak. Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy.`
   It seems the 'state'  parameter is 6, not long enough

**To Reproduce**
1. Go to  login page
2. Click on login through sso
3. Scroll down to network content in safari 

**Screenshots**
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/19185508/137364923-5d91f0f5-0055-48c0-968d-87ecabb88fd3.png">

**Outline (please complete the following information):**
- Install: [self hosted]
- Version: [docker image ver outlinewiki/outline:0.59.0]

**Desktop (please complete the following information):**
 - OS: [macOS ]
 - Browser [chrome, safari]

**Comment by stanthewizzard** [comment]
The bug returned

self hosted docker authelia
self hosted wiki js

The state is missing or does not have enough characters and is therefore considered too weak. Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy.

Thanks for help
