### ISSUE TITLE
Lose access to collection. 

### ISSUE THREAD

**Issue by iamsaumya** [outline/outline#2668]
There is a possibility to lose access to a collection. Can't even delete it. 

**To Reproduce**

Two users `1` and `2` 

1. User `1` creates a `no access` collection `C1` 
2. Adds a group to the collection with `view and edit` permission, the group will have two members `1` and `2`.
2. User `2` makes the user `1` view-only in the collection and change the group permission to `view-only`
3. Boom!

**Comment by tommoor** [comment]
I think it's hard to account for all the possible cases where this could happen, I'm sure there are other ways too :) 

One thing that's come up before that could solve this is to have a listing of all collections somewhere in the settings available only to admins (think similar to the members screen) – they wouldn't be able to see content but would be able to add themselves as a member to any collection.

**Comment by CaneTLOTW** [comment]
Looks like these topics are related to a certain degree. At least this would be a solution:
[https://github.com/outline/outline/discussions/1428](url)

**Comment by danwad** [comment]
As an admin I would like to be able to take ownership of a collection so that I can fix orphaned content - e.g. through an owner being on holiday or leaving the company.
