### ISSUE TITLE
There's no escape from "Document has changed since last revision"

### ISSUE THREAD

**Issue by bjj** [outline/outline#2675]
If you are editing a document and Outline decides "Document has changed since last revision", there is no helpful way out.

My install is self-hosted and single-user, so I have never actually caused this problem by actually editing the document twice. Instead, I suspect that it happens when I do two things in quick succession (such as duplicate a document and edit the duplicate) where some asynchronous update step completes after the edit starts. Possibly what is updating is only metadata, and the "document has changed" test should be relaxed to only consider text changes.

However, independent of the underlying bug which gets me into this state, for any user in "Document has changed since last revision" there should be some useful way of escaping.

**To Reproduce**
Of course you can get into this state by editing twice and saving in one editor. But I don't know the repro for the case where it happens due to internal outline action.

**Expected behavior**
Some method of exiting the editor while retaining my work:

* Offer to let me overwrite the "other edit" (in the cases I hit, I suspect the "other edit" was metadata, so there should be no harm in saving my document changes). Make it clear that the document history can access the overwritten version.
* Offer to insert the document in the edit history, but not as the active version. Not sure if this is really better than the first idea.
* Offer to let me save it as a conflicting document next to the original
* Offer to export the document so I can re-import it if I need it

For all of these it would be nice to see information about the conflicting edit (basically the history view)

**Outline (please complete the following information):**
- Install: selfhosted
- Version: docker v0.59.0

**Comment by tommoor** [comment]
This is fixed by using `v0.60.2` and enabling the collaborative editing feature.
