### ISSUE TITLE
Hitting backspace at the end of a list unexpectedly creates a list item (bullet, checkbox, number)

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#2702]
**To Reproduce**
put the cursor after a checkbox list and hit backspace
![image](https://user-images.githubusercontent.com/427579/139378797-067c423b-ebff-4abb-8c17-ae5fe7dac8f8.png)
it will create a new checkbox
![image](https://user-images.githubusercontent.com/427579/139378828-55ee9fbc-d09e-4f24-9988-ba74890f633f.png)

**Expected behavior**
It should probably move the cursor to the previous line (the last existing checkbox item), like hitting backspace at the beginning of a line usually does

**Comment by iamsaumya** [comment]
Tom, Is it something that prosemirror does on its own? I couldn't find handling for this is codebase. Btw this is also reproducible on Blockquote, Notices, and List.

**Comment by tommoor** [comment]
Honestly not sure where the behavior comes from, I'd have to step through it. I will note that the behavior is the same on the Prosemirror demo though:

https://prosemirror.net/examples/basic/

I do agree with Nan that it would be preferable to just jump up to the beginning of the last list item.

**Comment by iamsaumya** [comment]
up
