### ISSUE TITLE
On mobile left gutter items markers are cut off

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#2715]
![image](https://user-images.githubusercontent.com/427579/139592578-1548097a-7959-4f4d-96ba-d6a11e075ccd.jpeg)

**Expected behavior**

Possible options
- Increase left margin to make room; possibly reduce size of markers
- Put items in the right margin on mobile
- Remove margin items altogether

**Comment by tommoor** [comment]
Having a look at some other apps I think we can increase the gutter.
Somewhat needed for “+” button on empty lines too.
