### ISSUE TITLE
Cannot create API tokens

### ISSUE THREAD

**Issue by oakbrad** [outline/outline#2717]
Users are unable to create API tokens. 

**To Reproduce**
1. Go to Settings -> API Tokens
2. Click on "New Token...", type in name, submit
3. Page refreshes and is empty, no API keys listed
4. See error: None that I see, but the apiKeys table is empty in database

**Expected behavior**
API Token created

**Screenshots**
![Screen Shot 2021-10-31 at 11 17 05 AM](https://user-images.githubusercontent.com/24882215/139596549-29088e23-7f2b-48a3-a547-e950fd0bd955.png)

![Screen Shot 2021-10-31 at 11 13 13 AM](https://user-images.githubusercontent.com/24882215/139596455-def30316-5bf5-4e1d-bb5a-52ed1aa1ea9f.png)

**Outline (please complete the following information):**
- Install: selfhosted via outline docker container
- Version: 0.59.0 

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Firefox  92.0.1

**Comment by tommoor** [comment]
Hi, this issue has been resolved on `main` recently and will be included as a fix in the next release.
