### ISSUE TITLE
Ctrl + Esc opens the Start Menu on windows instead of canceling editing

### ISSUE THREAD

**Issue by minijaws** [outline/outline#2733]
Ctrl + Esc, the shortcut to cancel editing opens the start menu on windows

**To Reproduce**
1. Go to editor
2. press Ctrl + esc
3. the start menu will open and the document will not close

**Expected behavior**
The shortcut should be rebound to some other key combination

**Outline (please complete the following information):**
- Install: [getoutline.com]

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 95

**Comment by tommoor** [comment]
Thanks for reporting, we'll actually soon be removing edit mode in favor of always being able to edit if you have permission – this will resolve the issue in a roundabout way 😆

**Comment by norstbox** [comment]
> removing edit mode in favor of always being able to edit

Do you mean "always edit" in combination with additional "Lock" functionality?

BTW seems like a collision exits between "Table of contents" shortcut (`ctrl+alt+h`) and undocumented(?) "Open history" shortcut.

**Comment by biminion** [comment]
> > removing edit mode in favor of always being able to edit
> 
> Do you mean "always edit" in combination with additional "Lock" functionality?
> 
> BTW seems like a collision exits between "Table of contents" shortcut (`ctrl+alt+h`) and undocumented(?) "Open history" shortcut.

Hi there, 

the thumbs up are confusing. Will it be possible to have a view mode even if the user is able to edit? Always edit mode does not seem a good solution if an owner just wants to view the content.

**Comment by tommoor** [comment]
> Will it be possible to have a view mode even if the user is able to edit? 

Most likely it will be kept as a preference for those that really prefer a separate edit mode
