### ISSUE TITLE
Use of info tag forces all subsequent lines to be in info tags nested with code block.

### ISSUE THREAD

**Issue by DesBlock** [outline/outline#2735]
When attempting to use a nested info tag all following lines of text get added to the info tag and nested within a non-existent code block.

**To Reproduce**
1. create H3 header text
2. create bulleted list
3. include info tag and text (this one will be fine)
4. continue bulleted list
5. indent bullet, remove and replace with indented number 
6. input text for indented number
7. go to next line, remove number and create info tag
8. continue bulleted list
9. click save

**Expected behavior**
Info tags should not propagate down through all other lines of code. 

**Screenshots**
Before saving:
![BeforeSaving](https://user-images.githubusercontent.com/7647070/140570739-8d7c7679-1555-4059-8d70-6cbcc3346c77.png)

After saving:
![AfterSaving](https://user-images.githubusercontent.com/7647070/140570760-9f6c3f72-78a8-4d4b-affb-ea8957f2783c.png)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.59.0 (sha unavailable) 

**Desktop (please complete the following information):**
 - OS: OSX and Windows 10
 - Browser Chrome on OSX, Firefox on Windows 10
 - Version Chrome 95.0.4638.69 (Official Build)(x86_64) , Firefox 93.0 (64-bit)

**Mobile (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A

**Comment by tommoor** [comment]
This is addressed by enabling the collaborative editing feature in `v0.60.3`
