### ISSUE TITLE
"Share this document" UI state may become incorrect

### ISSUE THREAD

**Issue by norstbox** [outline/outline#2743]
"Share this document" UI state may become incorrect when certain conditions were met.

**To Reproduce**
1. Create collection with enabled "Public document sharing"
2. Create document (_A_) and nested document (_B_)
3. Share _A_, select both "Publish to internet" and "Share nested documents"
4. Open (click on) _B_
5. Open (click on) _A_
6. Click on "Share" button

**Expected behavior**
Share UI for collections with enabled "Public document sharing"

**Actual behavior**
Share UI for collections with disabled "Public document sharing"

**Outline:**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95.0.4638.69

**Comment by tommoor** [comment]
Confirmed, thanks for reporting this

**Comment by tommoor** [comment]
closed by 3ac7a839ad009f6d5ca741e7fc78a32f0f409470
