### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by dkkb** [outline/outline#2745]
Actually, the node server process works well for several hours, I don't know why it terminates without warning, the web page displays the error below.
By the way, I don't use websocket.

![image](https://user-images.githubusercontent.com/82504881/140697319-86a5be6a-c4fb-40a2-aaa1-651089f69347.png)

How can I get the stack trace? I can't see it in log.

**Outline (please complete the following information):**
- Install: [self hosted]
- Version: [70ec8c551eb7910f23c8ba834cdb90c443d16bcd]

**Comment by tommoor** [comment]
You can see the error in your server logs or you can configure Sentry to track errors, without that this issue is unactionable.

closing for now, feel free to reopen if you have more details.

**Comment by dkkb** [comment]
> You can see the error in your server logs or you can configure Sentry to track errors, without that this issue is unactionable.
> 
> closing for now, feel free to reopen if you have more details.

Sorry, but I don't know where the server log is. I runt this program with `nohup yarn start&`.
And the output log is below: 

```
➜  outline git:(dev) ✗ tail nohup.out
info: [http]   --> POST /api/views.create 200 23ms 539b
info: [processor] backlinks processing views.create
info: [processor] debouncer processing views.create
info: [processor] imports processing views.create
info: [processor] exports processing views.create
info: [processor] notifications processing views.create
info: [processor] revisions processing views.create
info: [processor] slack processing views.create
info: [http]   <-- GET /static/main.48bd61e54d9daee1b868.js
info: [http]   --> GET /static/main.48bd61e54d9daee1b868.js 200 524ms 4.11mb
```
Am I missing something?

**Comment by tommoor** [comment]
Where does the process terminate?

**Comment by dkkb** [comment]
> Where does the process terminate?

I think it may be caused by Systemd, logging out of the system will kill the process. Do you use systemd or pm2 to manage your services in production?

**Comment by dkkb** [comment]
![image](https://user-images.githubusercontent.com/82504881/141036099-a8c0296f-0efd-436e-bfcd-b1b8f2adb392.png)

**Comment by tommoor** [comment]
These are development errors, you're running the app in development mode. Set `NODE_ENV=production`
