### ISSUE TITLE
suddenly can't connect the server on windows 10 

### ISSUE THREAD

**Issue by hijason1301** [outline/outline#2746]
can't connect the server when the network is stable. Other vpn works.

**To Reproduce**
1.  it works fine before.
2.  it works fine on mobile in the same network.
3.  I can ping the server IP normally
4.  download the latest software form the website and reinstall. It works again and the next day it doesn't work again.
5. outline manager always can connect the server but the client can't 

**Outline (please complete the following information):**
- Install:  self hosted
- Version:  outline manager: 1,9 outline 1.6

**Desktop (please complete the following information):**
 - OS:  windows 
 - Browser: any
 - Version 20H2

**Comment by MarcoBorrini99** [comment]
Wrong "Outline"... No vpn here :-)
