### ISSUE TITLE
Miro embed is not working on both Outline cloud and self host

### ISSUE THREAD

**Issue by jagyas** [outline/outline#2756]
Outline embed is not working even with publicly accessible board URLs.

**To Reproduce**
1. Go to any page.
2. Press slash and select miro to embed.
3. Go to Miro and click "share" button and get public accessible URL
4. Paste Miro board URL in miro embed on page. It will give below error on both Outline cloud and on self host:
![image](https://user-images.githubusercontent.com/6293136/141148627-2ea1d3dc-56ce-433d-8f5e-ae4b117dc8e0.png)

**Expected behavior**
An embed Miro board should be visible in outline document.

**Screenshots**
![image](https://user-images.githubusercontent.com/6293136/141148719-a358a311-e90b-4eb9-a475-77ef303b4dd3.png)

**Outline (please complete the following information):**
- Install: getoutline.com and self host both
- Version: Release v0.59.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 95.0.4638.69

**Comment by tommoor** [comment]
Hi, I have been unable to reproduce with a fresh shared board from Miro – you probably need to post an example link where the error happens, it could be that there are several different sharing formats.

**Comment by jagyas** [comment]
Hello @tommoor ,
Please try with below link:
https://miro.com/app/board/o9J_kq22mmY=/

Please find below snapshot on Outline cloud:
![image](https://user-images.githubusercontent.com/6293136/141408743-90995507-dd3d-4657-bfaf-9b43cadd1c8f.png)

**Comment by tommoor** [comment]
Unfortunately it works fine for me and I have a fairly locked down setup in Brave Browser. Could you check…

- Errors in the console
- Disable any adblock/chrome extensions

**Comment by jagyas** [comment]
Hello @tommoor ,
I tried on Fresh Firefox and Edge too, same issue. Please find below console logs:
![image](https://user-images.githubusercontent.com/6293136/141670308-66a7192a-7743-435f-81bf-3087c731c058.png)

Below are Network logs:
![image](https://user-images.githubusercontent.com/6293136/141670325-d136b204-2c03-4178-9ede-a010333829d2.png)

![image](https://user-images.githubusercontent.com/6293136/141670365-9df515cb-190f-42a6-9047-ab8b1106a19e.png)

**Comment by jagyas** [comment]
And below errors are on Firefox:
![image](https://user-images.githubusercontent.com/6293136/141670474-5ada59c8-c682-4121-a2d9-c54fbe6d8bf9.png)

![image](https://user-images.githubusercontent.com/6293136/141670488-0630f73f-1c59-4d65-919f-60b39e7b3235.png)

**Comment by tommoor** [comment]
Unfortunately I've never been able to reproduce this issue with the links provided, I suspect this is somehow related to your account or blocking of third party cookies.

**Comment by jagyas** [comment]
Okay Thank you for your help. I am closing this ticket for now.
