### ISSUE TITLE
Duplicate slack notification when creating new document

### ISSUE THREAD

**Issue by rvk86** [outline/outline#2757]
Whenever I *create* a new document in a collection that has Slack notification turned on, I get both the "published a new document" and "updated a document" notification in the channel.

Thanks in advance!

**To Reproduce**
1. Turn on slack notifications for a collection
2. Create a new document in that collection
3. See two notifications in slack instead of one

**Expected behavior**
I think only the "published" notification should be sent to slack.

**Screenshots**
<img width="389" alt="image" src="https://user-images.githubusercontent.com/8648388/141284477-87592202-ddaa-489d-912d-6e8505a46c0b.png">

**Comment by tommoor** [comment]
Thanks for filing, do you know if you have the collaborative beta enabled?

**Comment by rvk86** [comment]
@tommoor thanks for your response. I don't this we have this enabled, still on a free trial for now.

**Comment by rvk86** [comment]
@tommoor sorry for being impatient, but is there any news on this? My company will start using the hosted version of outline soon, and the slack integration is one of the features we'll be using a lot.

Thanks a bunch!

**Comment by accesstechnology-mike** [comment]
v0.59.0 this is happening to me too
