### ISSUE TITLE
Empty SMTP_USERNAME env variable prevents Outline to detect SMTP setup

### ISSUE THREAD

**Issue by Limezy** [outline/outline#2767]
In my environnement I use the below configuration for SMTP :
```
SMTP_HOST='localhost'
SMTP_PORT='25'
SMTP_USERNAME=''
SMTP_PASSWORD=''
SMTP_FROM_EMAIL='outline@myoutlinedomain.fr'
SMTP_REPLY_EMAIL='webmaster@myoutlinedomain.fr'
SMTP_TLS_CIPHERS=
SMTP_SECURE='false'
```

As you can see, my `SMTP_USERNAME` env variable is empty, and **this is normal in my case**.
However, I discovered that this prevented Outline detecting that my SMTP server was indeed setup.

- It doesn't send emails anymore (and was perfectly working until v0.59
- I can't modify the "Allow email authentification" setting under the security tab

**To Reproduce**
1. Go to '.env' config file
2. Setup SMTP with an empty string for `SMTP_USERNAME` 
3. Go to youroutline.com/settings/security
4. See "The server must have SMTP configured to enable this setting" under "Allow email authentification"

**Expected behavior**
SMTP setup should be detected even if `SMTP_USERNAME`  string is empty.

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.60.1

**Comment by Limezy** [comment]
Temporarily solved on my server with this small patch https://github.com/Limezy/outline_ynh/blob/v0.60.1/sources/patches/app-02-email2.patch 
However of course I would like that issue to be solved "officially".
Thanks !

**Comment by Limezy** [comment]
Thanks @tommoor !

**Comment by tgy** [comment]
@Limezy Did you manage to make it work? I have the same setup as you and Outline is trying to send the email through port 465 for some reason `Error: connect ECONNREFUSED 127.0.0.1:465`.

My setup

```
SMTP_HOST=localhost
SMTP_PORT=25
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_FROM_EMAIL=noreply@domain.tld
SMTP_REPLY_EMAIL=postmaster@domain.tld
SMTP_TLS_CIPHERS=
SMTP_SECURE=false
```
