### ISSUE TITLE
Outline is incompatible with "Block All Public Access" on the S3 bucket.

### ISSUE THREAD

**Issue by netik** [outline/outline#2769]
There's been a lot of back and forth in the issue reporting about how outline should handle images.  Some people are okay with private attachments and public avatars, but that's a bad security model in general. 

It's very desirable to have block all public access on your amazon account for all of S3, as well as on individual buckets for security purposes. #1337 fixes most of this problem and was merged back in Feb 2020 but no one took the team logo or avatars into account.

The current fix of adding TEAM_LOGO only fixes the image on the logged out page (which is a bit of a hack) but does not fix the logo on the team's name once logged in (why even have TEAM_LOGO if this is the case?)

Attachments work perfectly fine with S3 signing and Block All Public Access enabled, because the signing is correct and objects are private. When BPA is on, you can't have **any** public objects at all in your account, and this is good for security-focused installations

Outline should sign every image and treat avatars as private if AWS_S3_ACL is set to private (or if some other flag is set to force private avatars). Currently they are hardcoded as "public". When this happens and Block All Public Access is enabled, _uploads and downloads will silently fail_.

Further compounding this problem is the fact that some sites cannot disable BPA. It can be set on an account-wide basis by administrators and individual buckets cannot bet set public after that policy decision has been made.

**To Reproduce**
1. Enable Block Public access on a bucket.
1. Set AWS_S3_ACL to the default of private.
1. Attempt to upload attachments in a new post, it will work.
1. Try the same thing for TEAM or USER Avatars. It will fail.

**Expected behavior**
Consistent behavior across all attachments and images. Proper signing used on uploads and downloads of Avatars,

Get rid of TEAM_LOGO entirely and sign the request for that image even for logged out users.

**Outline (please complete the following information):**
- Install: self hosted
- Version: latest (b616292fce719bf9acdc2cba6cad4d3aa68db34b)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome 95.0.x
 - Version: any

**Comment by jongomes** [comment]
same problem

**Comment by jongomes** [comment]
![image](https://user-images.githubusercontent.com/57728651/144492984-be8203dd-c0b6-4c1f-9c03-d337a734d121.png)

**Comment by romeupalos** [comment]
Public access to AWS buckets are not acceptable in current industry standard for security.
Please, use signed URLs.

**Comment by tommoor** [comment]
If someone wants to work on it we would accept the PR. The downside is slower loading avatar images

**Comment by netik** [comment]
I might have some time to explore this. It's not slower to load images at all. The signing is pretty fast and once cached by the browser even faster.

**Comment by netik** [comment]
I believe that #3694 fixes this issue so I'm going to close it. reopen if needed.

**Comment by netik** [comment]
Wait, no, on #3694 they say it's not a bug. It most certainly is a problem for people using authenticated s3 endpoints.

**Comment by nrukavkov** [comment]
The same problem. We have a private s3. And outline tries to get images uploaded via settings page without authorization. And it gets access problem.

**Comment by nrukavkov** [comment]
Why just not save all public images in database? It is really will make all easy. For example add field in users table 'avatar' and save in binary format. And add in general settings logo of wiki. That is it

**Comment by netik** [comment]
> Why just not save all public images in database? 

Because storing large binary blobs in a relational database is an improper use of a database.

It leads to opaque, unmanageable storage and difficult to access "files."

Everyone who has ever tried to
store lots of images in a db has had problems in the end.

**Comment by haivp3010** [comment]
I would prefer the current approach where the `public` folder is considered public. What we could do to improve this is better documenting the behavior, and providing some examples regarding how this could be achieved in a private bucket.

In my case, I have added a policy for the public folder and it works just fine.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::outline-bucket/public/*"
            ]
        }
    ]
}
```

**Comment by haivp3010** [comment]
> @haivp3010 for security reason, use public S3 buckets is a bad practice. The best approach is to use presigned url returned by the API, who have the proper rights with S3 service : https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html
> 
> But I don't know if it's planned by current outlined API

Yes, I agree. What I meant is while we should set the whole S3 bucket as private, some parts of it may still act as public storage via policies, i.e. particularly in this case, a folder named `public`. I personally think avatars is a fit use case for this. Other sensitive files should never be be uploaded into those folders though.

**Comment by netik** [comment]
that doesn't work when BPA is enabled -- the policy is ignored afaik

**Comment by haivp3010** [comment]
@netik yeah you're right, if all four options of S3's BPA, 2 of which block the use of policies, are enabled, then it's not possible to use policies.

**Comment by martinounap** [comment]
Please reopen this issue. It is still a problem and today's industry standards won't accept public object storages.
It would be nice, if it would be downloaded/uploaded with signed URL.
