### ISSUE TITLE
Allow saving of untitled documents in drafts

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#2774]
Sometimes it's not so easy to name a thing before you begin writing about it. It's understandable that you wouldn't want published untitled documents, but as long as outline has a draft feature, this might be a decent way to lean into that.

Untitled drafts display as "Untitled Document" in list views (they never show up in the sidebar).

![image](https://user-images.githubusercontent.com/427579/141874487-dd0de073-cffc-491d-9508-b5d4176e4012.png)

**Comment by tommoor** [comment]
This actually works, but with collaborative editing enabled if you hit `cmd`+`s` then you do see an error toast that "title" or "text" is required. Is this what you're referring to?

**Comment by tommoor** [comment]
This was addressed
