### ISSUE TITLE
Carriage return after a heading should return to body copy level

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#2775]
Currently when a user presses `return` on a heading line, the new line remains at the same heading level. This feels quite unconventional and unexpected. 

I think the expectation is that the editor returns to body copy level of text style. This is the behavior in Dropbox Paper, Notion, and Google Docs

**Comment by tommoor** [comment]
It all seems to work as expected for me. If you hit `return` in the middle of a heading then the heading is split. If at the end of the heading then you get a new paragraph?

**Comment by thenanyu** [comment]
I can still reproduce. Will make a video of it later

**Comment by tommoor** [comment]
closing as unreproducible at this point 🤷
