### ISSUE TITLE
Breadcrumbs should be visible on shared docs on mobile

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2801]
Currently, they are not

![image](https://user-images.githubusercontent.com/380914/143932401-2abba2ae-aa69-4e7c-b752-8b352db9c515.png)

**Comment by iamsaumya** [comment]
We should also adjust the trademark somewhere else in mobile. Where do you suggest? 

<img width="339" alt="Screenshot 2021-12-11 at 4 09 24 PM" src="https://user-images.githubusercontent.com/40148448/145673592-31cc13f7-ee3b-40ed-8177-7d1ba9c3fd12.png">

**Comment by tommoor** [comment]
The bottom is probably OK, but we should reserve some space on mobile. I thought It could do with some space at the bottom even on non-shared pages

**Comment by thenanyu** [comment]
playing around with some of this positioning

I think on mobile it wants to be centered...

![image](https://user-images.githubusercontent.com/427579/150895186-cb97aec5-34b6-4865-9c8b-cadc9d23edbd.png)
![image](https://user-images.githubusercontent.com/427579/150895213-2181244c-8ff9-4ab2-a3a0-222fd72c1731.png)
![image](https://user-images.githubusercontent.com/427579/150895248-8a411344-dfbb-43bb-94ef-87338a7c24c9.png)

**Comment by tommoor** [comment]
Centered looks good
