### ISSUE TITLE
Public parent documents lose content when navigating back

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2802]
**To Reproduce**
1. Go to https://wiki.generaloutline.com/share/13dec265-c002-4c73-8025-75981f29b0d0/doc/aws-NfelJ2WRAj
2. Click on a subdocument
3. Go back

**Comment by tommoor** [comment]
Ah, interestingly seems like you have to be signed in for this to happen.

**Comment by iamsaumya** [comment]
By content - Do you mean the subtree and breadcrumbs?
