### ISSUE TITLE
The bug with billing after the card data changes 

### ISSUE THREAD

**Issue by audit1251** [outline/outline#2828]
Hello, 
I've changed the card data and now have this notifications – https://take.ms/mr8v0 
could you please let me know what I did wrong? 
Or let me know if it's everything fine with our account 

Have a nice day

**Comment by tommoor** [comment]
Hi, the charge was retried successfully – you're all good now. Please note that this is a public space in case that wasn't clear – best avenue for support is hello@getoutline.com.
