### ISSUE TITLE
Moving to inner pages inside shared document causes cyclic redirects

### ISSUE THREAD

**Issue by Vladislao** [outline/outline#2867]
Moving to inner pages inside shared document causes cyclic redirects

**To Reproduce**
1. Go to https://tenderplan.getoutline.com/share/5ee09e1e-4f4a-4287-8972-79894d3b30ad
2. Click on inner page
3. See error (browser navigates back and forth)

**Expected behavior**
Inner page is displayed properly, without redirects

**Screenshots**
https://www.awesomescreenshot.com/video/6492859?key=d1c9f894842fb9146498dd437dc208c3

**Outline (please complete the following information):**
- Install: getoutline.com
- Version: -

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Chrome 
 - Version: 96.0.4664.93

**Comment by Vladislao** [comment]
@tommoor Thanks a lot! Any idea on when fix will be published? This bug is kinda affecting part of our team on cloud version.

**Comment by tommoor** [comment]
Thanks for your patience, this fix is in production now
