### ISSUE TITLE
Some claims may not exist in non-standard OpenID userinfo response so creating user would fail

### ISSUE THREAD

**Issue by haogeek** [outline/outline#2876]
Currently, `server/routes/auth/providers/oidc.ts` has code as below:

```javascript
user: {
    name: profile.name,
    email: profile.email,
    avatarUrl: profile.picture,
    // Claim name can be overriden using an env variable.
    // Default is 'preferred_username' as per OIDC spec.
    username: get(profile, OIDC_USERNAME_CLAIM),
 },
```

Although both `name` and `picture` are standard profile claims in the official specification, but some non-standard providers may return userinfo response which doesn't include these claims, then the application would raise error. It is exactly what I met in my situation, so I have to manually change this source code to:

```javascript
user: {
    name: profile.nickname,
    email: profile.email,
    avatarUrl: "",
    // Claim name can be overriden using an env variable.
    // Default is 'preferred_username' as per OIDC spec.
    username: get(profile, OIDC_USERNAME_CLAIM),
 },
```

I think a better solution is like what the `username` key did, using environment variable to define which claim should be used, or even user could define the whole userinfo fields mapping.

**Comment by tommoor** [comment]
Hi @haogeek – thanks for filing. If your provider is not conforming to the standard then I would raise the issue with the OIDC provider. The point of a standard is that we do not need to make it endlessly configurable with all of the additional maintenance burden that entails for the core team.
