### ISSUE TITLE
Erro ao colocar imagem

### ISSUE THREAD

**Issue by isabelavitorianosousa** [outline/outline#2879]
**To Reproduce**
1. Go to 'https://wiki.gobots.com.br/doc/'
2. Click on '+'
3. Scroll down to 'Imagem'
4. Try to upload image
5. See error

**Expected behavior**
Deveria conseguir colocar imagem.

**Desktop (please complete the following information):**
 - Browser [chrome]

**Mobile (please complete the following information):**

**Comment by tommoor** [comment]
Hi, we cannot provide support for self-hosted installations – you should contact your IT team to debug
