### ISSUE TITLE
Copy link to highlight (browser feature) not working

### ISSUE THREAD

**Issue by kmanojkumar** [outline/outline#2896]
Copy link to highlight is a feature offered by most browsers, which allows you to highlight text in a webpage and share the link or store the link in a doc. When such a link is added to Outline doc, it doesn't seem to work when clicked, maybe Outline is altering the link or something?

Top open Copy Link to Highlight in a browser, select text in a web page and right-click.

**Copy Link to Highlight in action:** https://www.getoutline.com/#:~:text=Lost%20in%20a%20mess%20of%20Docs%3F%20Never%20quite%20sure%20who%20has%20access%3F

**To Reproduce**
Steps to reproduce the behaviour:
Create a doc in Outline and save such Highlight link in a doc. Click on the link, the highlight text behaviour doesn't seem to work.

**Expected behaviour**
Clicking on a Copy to Highlight link, should open a page with text highlighted in the webpage. 

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.60.3

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1
 - Browser Chrome and Edge
 - Version Latest

**Comment by tommoor** [comment]
I'm not sure it's fair to call this a bug in Outline, it's a browser feature that only works in some Chromium browsers – and apparently not very reliably? 😆

**Comment by kmanojkumar** [comment]
Completely agree, this issue belongs to the `is-it-a-bug?` label 😅. 

But please check at your end once, maybe you may find something. It just works in different other apps we use like GitHub, Teams, Docs so never questioned the reliability. But, yes I read about it online, some people do have issues.
