### ISSUE TITLE
Add context menu triggers for menus on list items

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2907]
In testing users often try to right click on documents in lists to perform actions, but this reveals the standard browser menu. It would be better if our context menu showed up in these scenarios and would remove the need to move the mouse specifically to the "..." overflow button.

**Comment by max-mykhailenko** [comment]
Also please do something for touch devices. On iPad I can't add sub document because can't hover. Long tap or something similar would help

**Comment by tommoor** [comment]
> I can't add sub document because can't hover.

The hover states are just shortcuts, all of the actions should also be accessible from document header on mobile. Just want to make sure you're aware.
