### ISSUE TITLE
Add ability to choose "Home" collection

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2912]

**Comment by iamsaumya** [comment]
Just to confirm, Do we need to add double-clicking on `Home` in the sidebar to edit its name?

**Comment by tommoor** [comment]
We do not, an editable title just for the admin makes sense. I'm wondering if there should be a "pencil" icon to trigger edit mode considering it'll be a rare action to take.

**Comment by iamsaumya** [comment]
If it's just for admins, Thoughts on keeping it on the team settings page? We can go with showing "pencil" icon onHover approach.

**Comment by tommoor** [comment]
The problem with that approach is that the context is somewhat important in terms of how long the title is, I worry that it wouldn't be clear on the settings page what you're editing.

However, this brings me to another preference I was thinking of adding that perhaps would kill two birds with one stone here – a preference (on the team settings page) that the admin could choose which collection is the "default", aka where you get redirected to after login. Perhaps we implement that instead, and of course collection titles are already editable.

**Comment by iamsaumya** [comment]
Agree, the context of how the new title would look in the sidebar is important. 

Sounds good to me. A preference for collection on admin page 💯

**Comment by iamsaumya** [comment]
Implementation details - 

We will show all the collections that the admin had access to in the dropdown. We will redirect the users to /home if they don't have permission. Essentially, it will be the admin's responsibility to ensure the collection is public. 

For the users who `!hasViewedDocuments` any documents, the admin preferred collection(if set) will override the existing behaviour of redirecting to the first collection.

**Comment by tommoor** [comment]
Devil is in the detail.

- Lets only show collections accessible to all team members in the dropdown
- Yes on override the existing behaviour of redirecting to the first collection
- If the collection changes permission to no longer be public we probably need to clear the team setting
- If the collection is deleted we need to clear the team setting
- "Home" needs to remain as an option in the picker on the team settings screen
