### ISSUE TITLE
Allow custom theme

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2916]
We've had a lot of requests for custom css – this doesn't seem like a wise thing to add, for one because all of our classnames are generated at build time but also it would continuously break as the app evolves irregardless of this.

However, the app is built on styled-components themes and as such the majority of the colors and font faces can be easily changed, we just need to expose some UI and storage for this. It feels like a team-level setting.

**Comment by dkkb** [comment]
That's nice.

**Comment by michaelkarrer81** [comment]
+1

**Comment by ChuckJonas** [comment]
I'd also add font sizes and maybe even whitespace to that list.  The files I've migrated so far do seem to suffer from a "wall of text" vibe that wasn't nearly as bad in our previous solution.

**Comment by matbrgz** [comment]
In my use case, I need to change the application font to help people who have dyslexia, so in my opinion the ability to change some configuration through the admin panel will be outstanding.

**Comment by Danita** [comment]
Any news on this?

**Comment by nr-plaxon** [comment]
How about adding an option to inject custom JavaScript and CSS on each page in the header?
Bookstack does this (https://www.bookstackapp.com/docs/admin/hacking-bookstack/#custom-html-head-option) and it allows for lots of customizations and theming.

**Comment by denizbinay** [comment]
still a good idea!
