### ISSUE TITLE
Emoji shifts over ToC

### ISSUE THREAD

**Issue by max-mykhailenko** [outline/outline#2920]
Some emoji shifts to the left.

**To Reproduce**
1. Go to any document
2. Click on title
3. Add emoji 1️⃣ as first char
4. Set focus to the main content part
4. See the error

**Expected behavior**
Emoji shifted, but not over ToC

**Screenshots**
<img width="368" alt="image" src="https://user-images.githubusercontent.com/1213198/148677604-ceb32b3a-5ed9-4b72-b1f4-9f9731ab922a.png">

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.61.0 based on outline/outline:latest

**Desktop (please complete the following information):**
 - OS: mac OS
 - Browser Safari 
 - Version 15.3

**Comment by tommoor** [comment]
This is by design - it moves so that the text is aligned and the emoji hangs, although it looks like it's not appointed in this case as that emoji is wider than typical 😔

**Comment by max-mykhailenko** [comment]
Some emojis doesn't shift, for example here
<img width="414" alt="image" src="https://user-images.githubusercontent.com/1213198/148690971-f02b5601-2cbc-4210-ac13-27f2c81577ac.png">

**Comment by max-mykhailenko** [comment]
> This is by design - it moves so that the text is aligned and the emoji hangs

I like this design approach, really good typography
