### ISSUE TITLE
The Diagrams.net integration only allows using the public Diagrams.net-Viewer

### ISSUE THREAD

**Issue by cisoLKT** [outline/outline#2923]
The Diagrams.net integration only allows using the public Diagrams.net-Viewer.

**To Reproduce**
1. Create a diagrams.net graphic on a self-hosted Diagrams.net-Instance
2. Get the embed link as described in [PR #2464](https://github.com/outline/outline/pull/2464)
3. insert the embed link pointing to a local diagrams.net instance (e.g. draw.test.local) in the diagrams.net integration/viewer in Outline
4. Error: "Sorry, that link won't work for this embed type"
![image](https://user-images.githubusercontent.com/77791554/148774324-e80ac8a7-820d-441e-b18a-9b30d5eac231.png)

**--> Outline checks, that the specified Diagrams.net URL matches the public Diagrams.net-Viewer:**
https://github.com/outline/outline/blob/19e85c63c2d5c77d63705480a903870125b03902/shared/embeds/Diagrams.tsx#L6

**Expected behavior**
The Outline Diagrams.net integration should also support self-hosted Diagrams.net viewers.

**Screenshots**
see above

**Outline (please complete the following information):**
 - Install: self hosted
 - Version: docker outlinewiki/outline v0.61.0

**Comment by cisoLKT** [comment]
**Proposed Fix**
Allow specifying a custom Diagrams.net URL in Outline Settings / docker-compose.yml.

**Comment by tommoor** [comment]
Happy to provide guidance if anyone wants to build this.

**Comment by routerino** [comment]
https://github.com/outline/outline/issues/2831 would supersede this issue if implemented, as it would replace the existing diagrams.net integration. That said, the referenced issue would require a rewrite of the diagrams.net implementation.
