### ISSUE TITLE
Expanding/collapsing headers is slow on Firefox v96.0

### ISSUE THREAD

**Issue by aam1r** [outline/outline#2928]
**To Reproduce**

1. Go to a page with a header  that has a large codeblock
2. Collapse the header

**Expected behavior**

The header should collapse and expand quickly

**What happens**

It takes 5 seconds on Firefox v96.0 to collapse/expand the header. On Chrome, it takes <1s.

**Outline:**
- Install: Self-hosted
- Version: v0.61.1

**Desktop:**
 - OS: macOS

**Comment by mihalyr** [comment]
Same on Firefox 95.0.2
