### ISSUE TITLE
"Pin" icons are different colored to the rest

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2939]
Small oversight, it's much less noticeable in light theme.

![image](https://user-images.githubusercontent.com/380914/149470178-1ac149e1-8994-4606-b69f-a14f69f64998.png)

**Comment by tommoor** [comment]
I'm also tempted to turn this into a submenu `Pin -> To Home` – thoughts @thenanyu ?

**Comment by thenanyu** [comment]
submenu seems like a good starting place, I like it
