### ISSUE TITLE
ctrl-k Mistakenly Triggers the "Link" Command (⌘-K), and ctrl-n "New Document" (n)

### ISSUE THREAD

**Issue by jonioni** [outline/outline#2941]
(On macOS) `ctrl-k` triggers the "Link" command (the shortcut map shows it should be `⌘-k`). And `ctrl-n` triggers the "New Document" command (`n`).

These override the common editor actions which cause significantly friction during edit.

**To Reproduce**
1. Go to a document and enter edit mode.
2. Press `ctrl-k` to kill the line, yet the link menu is opened.
3. Press `ctrl-n` to go to next line, yet it suddenly jumps to a new document.

**Expected behavior**
`ctrl-k` / `ctrl-n` (and potentially other basic ctrl commands) are common editor shortcuts and should better not be used as application shortcuts.

Also it would be much better to provide an option to disable keyboard shortcuts for edit mode (#1307).

**Screenshots**

<img width="860" alt="Screen Shot 2022-01-15 at 2 07 34 AM" src="https://user-images.githubusercontent.com/31494475/149613063-82b4db92-ffc4-4d81-9230-0d77e1aec3b8.png">

**Outline (please complete the following information):**
- Install: getoutline.com/self-hosted
- Version: `latest` (dockerhub digest `2048ed0e0b7c`)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: Chrome
 - Version: 97.0.4692

**Comment by tommoor** [comment]
Related: https://github.com/timc1/kbar/pull/156
