### ISSUE TITLE
Guest role with restricted permissions

### ISSUE THREAD

**Issue by M6Ka7** [outline/outline#2946]
If I invite several external users to my outline installation, everyone could see other users who have viewed / edited an article. When you invite external users from company A and from company B they can see each other 
 - on articles viewed in the past
 - on articles edited
 - on articles viewed at the moment
 - in the settings menu (groups/members)
 - maybe other pages

which would be an GDPR incident.

**To Reproduce**
1. Create an external user by inviting per mail 
2. Give the user minimal access (viewer)
3. Login with "magic link"
4. Visit settings page and then members or groups
5. Visit an arbitrary page and click the avatar button to see
    - who is online (now)
    - who viewed this page
    - who edited this page

**Expected behavior**
External users must not see others to avoid GDPR penalties. There should also be an feature to disable the avatar - button on 
- user
- role
- login type
- global

level and forbid access to settings menu. 

If the disabling is not possible, the information should be anonymized e.g. 
- 3 people are watching this article now (instead of User A, User B, User C)
- 24 people viewed/edited this article.

**Screenshots**
<img width="634" alt="image" src="https://user-images.githubusercontent.com/97874931/149734507-ce97a07a-ea7c-4e0b-a0f8-ed7cb3b3cfb5.png">
The screenshot is made from an external user which can see other (external users) marked with red rectangle.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/97874931/149735615-f7e1b9a0-2337-49e8-bf33-7f78d2343c90.png">

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.61.1

**Comment by Shide** [comment]
I was testing Outline for my company and I've found the same issue here.

MT-167 @moduon

**Comment by michaelkarrer81** [comment]
+1 This may be a blocking issue to use outline in my company.

**Comment by rafaelbn** [comment]
👍 This is a blocking issue

**Comment by tommoor** [comment]
It sounds like the ask here is for a "guest" role which is being conflated with viewer.

Guests would have much more restricted data access, potentially only being able to access collections that they are explicitly added to and not have access to settings screens. Does this sound right?

**Comment by M6Ka7** [comment]
The guest role seems to be the right direction for me. But does not cover it 100%.

> The background is: The **G**eneral **D**ata **P**rotection **R**egulation, which applies across the EU, threatens up to €20 million (about $22 million USD) for exposure of sensitive (identifying) data. 

I would suggest a global switch analogous to `FORCE_HTTPS` which can (only) be set in the `docker-compose.yml` file.
This switch removes the User viewing / viewed menu (<img width="62" alt="image" src="https://user-images.githubusercontent.com/97874931/150923169-e027f1a6-fda9-4aa8-9caf-98d4071cbeaa.png">). For any non administrator users.

The switch should also remove the member settings view for non administator users

Maybe there are further pages I have not discovered yet.

**Comment by Shide** [comment]
> It sounds like the ask here is for a "guest" role which is being conflated with viewer.

Yes.

In my case (I'm evaluation 25 kwnoledge platforms), I have assumed that the _Viewer_ role is the _Guest_ role because all of the other platforms treats "Viewers" as "Guests".

Just for clarify the meaning of _Guest_ for me: _An invited "user" that can view/comment content for which they have been invited._

**Comment by DioneMentis** [comment]
@tommoor  Form this comment above: https://github.com/outline/outline/issues/2946#issuecomment-1020805356

>Guests would have much more restricted data access, potentially only being able to access collections that they are explicitly added to and not have access to settings screens. Does this sound right?

Not having this is a limitation for our team. We have some collections that contain information for our team only. Equally we need to create collections that can have external editors and viewers. 

We think Outline is a really great tool! But this limitation and the inability to share just one doc in a collection with an team member or guest will probably turn out to be deal breakers for us.

**Comment by almereyda** [comment]
Maybe an alternative convention can be to hide member email addresses for any user but admins?

This should be much easier to implement than a new role.

The display of the email address fields must be conditional on a permission in both cases.

**Comment by tommoor** [comment]
> Maybe an alternative convention can be to hide member email addresses for any user but admins?

This is already the case, the policy is defined here: 
https://github.com/outline/outline/blob/20d85e3d3a4292a19c29ecdae98e36b592e10f5b/server/policies/user.ts#L63

**Comment by tommoor** [comment]
This feature is now released in `v0.76.0` Business + Enterprise editions.

**Comment by ldpl-shrey** [comment]
> This feature is now released in `v0.76.0` Business + Enterprise editions, as well as cloud hosted Outline.

@tommoor 
Are there any plans to enable this feature in the Self-Hosted version also?
If yes, by when?
