### ISSUE TITLE
Support running without reverse proxy

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2958]
The most complex part of self hosting Outline seems to be the requirement of a reverse proxy, we could perhaps simplify this by allowing those with a valid cert to make it available to the application and handle the SSL termination internally.

**Comment by scott-dunt** [comment]
Just My $.02. I personally prefer to use Nginx or similar as a proxy in front of ALL of my self hosted apps. I think its more industrial strength and lets the Outline Developers focus on what they do best, not focus on reverse proxy stuff.

A working Nginx config for outline is documented in: https://github.com/outline/outline/discussions/2383

**Comment by tommoor** [comment]
@scott-dunt reverse proxy will still remain as the default and best option. Problem is we get so much support around this one issue it's actually easier to just maintain the small amount of code 😅

**Comment by danielslyman** [comment]
well its there a work around? I am running Nginx Proxy Manager and proxying several other services on the same machine. So far acme will fail if I do not give the outline https-portal 80 and 443. However, I need to those ports for Nginx Proxy Manager, any ideas?
