### ISSUE TITLE
Unable to add space character when editing Collection name

### ISSUE THREAD

**Issue by Shide** [outline/outline#2960]
Editing the name of the collection via `tree dots > Edit...`, doesn't allow using spaces at first time.
You need to enter all the text without spaces and then add the spaces where you want.

If I `double click` on the collection name, allow using spaces.

**To Reproduce:**
1. Create a collection named 'Test spaces'
2. Click on the 'tree dots' to display collection options and clic on 'Edit...'
3. Change the name to 'Another test'
4. See that doesn't allow to use spaces
5. Change the name to 'Anothertest', and back with the cursor to add the space needed.
6. See that allow to use the space

Video reproducing the steps: https://www.loom.com/share/2cdb7346313c4b6f906b68ea2f5fafea

**Expected behavior**
The ability to change collection name with spaces

**Outline:**
- Install: getoutline.com

**Desktop:**
- PWA
- Browser: Chrome 97.0.4692.71 (Official build) (64 bits)

MT-167 @moduon

**Comment by tommoor** [comment]
Thanks for filing, weird bug!

**Comment by thenanyu** [comment]
I think it's the validation trimming leading and trailing whitespace too aggressively — you can still add spaces in the middle of the string. 

I'll take a look
