### ISSUE TITLE
Cannot Unnest document

### ISSUE THREAD

**Issue by ChuckJonas** [outline/outline#2974]
**To Reproduce**
1. Create a collection called `testing`
2. Create 2 documents called `A` and `B` under the `testing` collection
2. Drag `B` on top of `A`.  `B` is now a child of `A`
3. Drag `B` back to the `testing` collection
4. `B` will remain nested under `A`

**Expected behavior**
I would expect this would put it back in the collection root.  I also tried dragging it "along side" (in between) other top level documents, but it's not possible)

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser brave
 - Version V1.34.81

**Comment by ChuckJonas** [comment]
The only way I can figure out how to unnest the document is to drag it to a different collection, then drag it back

**Comment by tommoor** [comment]
Interesting, I think I can imagine what is happening here – I think it sounds like alphabetic sorting is turned on? Change this option to manual and then you will be able to drag between top level items

![image](https://user-images.githubusercontent.com/380914/150626805-f7a6ca54-7788-4a9f-b4d3-27972491f995.png)

**Comment by ChuckJonas** [comment]
ya that was it!  Seems like you should still be able to drag in between items even with alphabetical search on (it would just auto-sort after).

As a new user, I didn't even know I had Alphabetical search was on.

**Comment by ChuckJonas** [comment]
Can you confirm this is the line which results in no change when dropping the nested item on its own collection?

https://github.com/outline/outline/blob/main/app/components/Sidebar/components/CollectionLink.tsx#L84

I'm evaluating this library for our team.  Only spent about 4m scanning the codebase but it seems very easy to follow 👍 .

**Comment by tommoor** [comment]
That seems like that spot, yep!

**Comment by ChuckJonas** [comment]
@tommoor I spent a minute to see if I could get the app running and fix the issue.  Not sure if simply checking the depth here is actually sufficient, but it seems to work as expected.

Didn't have a chance to look at the test suite yet either, but wanted to confirm:

A: this change is desired
B: this approach is correct

before I continue any further.  

If tests are required and you'd like me to move forward, it would be great if you could point me to the approach spec.

Thanks!

**Comment by ChuckJonas** [comment]
PS: I noticed a `no-op` error when testing the following scenario:

```
collection 1
   A
       B
           C
collection 2
```
-->
```
collection 1
   A
       
collection 2
   B
       C
```

Confirmed it exists before my change.

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at ContextMenu (webpack-internal:///./app/components/ContextMenu/index.tsx:54:23)
    at wrappedComponent (webpack-internal:///./node_modules/mobx-react-lite/es/observer.js:29:88)
    at span
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19623)
    at span
    at EventBoundary (webpack-internal:///./app/components/EventBoundary.tsx:9:23)
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19623)
    at SidebarLink (webpack-internal:///./app/components/Sidebar/components/SidebarLink.tsx:73:19)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19623)
    at eval (webpack-internal:///./node_modules/react-dropzone/dist/es/index.js:59:23)
    at wrappedComponent (webpack-internal:///./node_modules/mobx-react-lite/es/observer.js:29:88)
    at div
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19623)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19623)
    at ObserverComponent (webpack-internal:///./node_modules/mobx-react-lite/es/ObserverComponent.js:5:23)
    at ObserverForwardRef
    at ObserverComponent (webpack-internal:///./node_modules/mobx-react-lite/es/ObserverComponent.js:5:23)
    at ObserverForwardRef
overrideMethod @ react_devtools_backend.js:4045
printWarning @ react-dom.development.js?61bb:67
error @ react-dom.development.js?61bb:43
warnAboutUpdateOnUnmountedFiberInDEV @ react-dom.development.js?61bb:23914
scheduleUpdateOnFiber @ react-dom.development.js?61bb:21840
dispatchAction @ react-dom.development.js?61bb:16139
eval @ useWindowSize.ts?2bf2:14
invokeFunc @ debounce.js?b047:95
trailingEdge @ debounce.js?b047:144
timerExpired @ debounce.js?b047:132
setTimeout (async)
leadingEdge @ debounce.js?b047:103
debounced @ debounce.js?b047:172
eval @ useWindowSize.ts?2bf2:24
invokePassiveEffectCreate @ react-dom.development.js?61bb:23487
callCallback @ react-dom.development.js?61bb:3945
invokeGuardedCallbackDev @ react-dom.development.js?61bb:3994
invokeGuardedCallback @ react-dom.development.js?61bb:4056
flushPassiveEffectsImpl @ react-dom.development.js?61bb:23574
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushPassiveEffects @ react-dom.development.js?61bb:23447
flushDiscreteUpdates @ react-dom.development.js?61bb:22356
flushDiscreteUpdatesIfNeeded @ react-dom.development.js?61bb:3768
dispatchDiscreteEvent @ react-dom.development.js?61bb:5886
...
```

**Comment by tommoor** [comment]
> A: this change is desired

Yep

> B: this approach is correct

Somewhat – I think instead of checking the `depth` we can check if the existing document has a `parentDocumentId` – if it does then allow the drag to happen. I'm not sure if there might be additional guards beyond the one you already modified that might need update to allow the move operation to complete successfully.

> If tests are required and you'd like me to move forward

Tests only required if an API endpoint ends up needing changing

**Comment by ChuckJonas** [comment]
Updated the PR based on the above suggestion. 

https://github.com/outline/outline/pull/2975/files#diff-c87536209932b0e88c617e7f5b44afd93643791e7eeaa146256b8a961ca38575R85
