### ISSUE TITLE
History cannot be viewed for trashed documents

### ISSUE THREAD

**Issue by treasuretron** [outline/outline#2995]
**To Reproduce**
1. Go to a document in the trash
2. Click on ellipsis, then History
3. Click on any of the history events where the file was edited
4. Page changes from the title of the page to:
"Not found

We were unable to find the page you’re looking for. Go to the homepage?
"

**Expected behavior**
I would expect to see the old versions and be able to restore them

**Screenshots**
can post if helpful

**Outline (please complete the following information):**
- Install: self hosted 60.1 (waiting for OIDC code to be merged into a release to upgrade)
- Version: can post sha when I get back to other computer

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Browser: Firefox
 - Version 96.0.1

**Comment by tommoor** [comment]
Hi, can you reproduce this for documents that are not in the trash.

The expectation would be that you cannot do anything with trashed documents without restoring them, so the UI should probably be disabled here
