### ISSUE TITLE
Move to sending JSON rather than Markdown to client

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3000]
### Problem

Currently when you request documents from the server we send a Markdown representation to the client which is rendered immediately. For collaborative editing we also render this while waiting for the collaborative connection to start to make the document appear faster.

This worked well up until now as every type of node could be serialized to Markdown in a reversible fashion – going forward this restriction should be removed so we can have items in the doc that cannot be represented in Markdown. For example fancy new node types, file attachments, comments etc.

### Solution

Markdown will be used as an import/export type and markdown shortcuts will continue to work in the editor as today, however it will not be used to render in the app and may not be sent from the server at all unless requested explicitly for a download.

To migrate we'll need to convert all the existing docs in the database and store the JSON representation alongside the markdown.

**Comment by therajumandapati** [comment]
@tommoor Do you have any ideas in mind for coming up with a JSON structure for transforming markdown?

**Comment by tommoor** [comment]
The format already exists, it's what the Markdown gets parsed into. It also exists inside the CRDT in the database which contains the collaborative state of any given document… eg.

```
import { parser } from "@server/editor"
const json = parser.parse(markdown)
```

**Comment by tommoor** [comment]
Work has begun on this, now that collaborative editing is the default it makes things easier. Some features that this potentially unlocks:

- Different highlighting colors
- Resizing tables/rows/columns, more content support in table cells
- Multi-column layouts
- Arbitrary embed support, resizing embeds

**Comment by almereyda** [comment]
🙏🏽
