### ISSUE TITLE
Public shared doc trees should have search

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3004]
### Discussed in https://github.com/outline/outline/discussions/3003

<div type='discussions-op-text'>

<sup>Originally posted by **Yajo** January 25, 2022</sup>
If you share a document (and maybe subdocuments) publicly, the public users cannot search. Search is a powerful feature in any knowledge base, so it should be available for that shared document and children.</div>

**Comment by tommoor** [comment]
In the interests of transparency, some notes from our discussion on this earlier:

- Search box will be at the top of sidebar, will use a popover design similar to other docs platforms rather than a separate page like we have in the main product.
- Use the existing endpoint `api/documents.search`, pass shareId through, see `documents.info` for example of mixed auth like this.
- Might be able to reuse `DocumentListItem` component for search results
- Reference `searchForUser` and `searchForTeam` static Document methods

**Comment by Shide** [comment]
Is this issue merged or refused?

**Comment by tommoor** [comment]
It's done and live
