### ISSUE TITLE
Sidebar actions not showing on hover in Firefox on Windows 11

### ISSUE THREAD

**Issue by v-marinkov** [outline/outline#3005]
The sidebar actions icons are not showing on hover in Firefox on Windows 11 (release and dev). It works on Chromium browsers and on Firefox MacOS.

Here it how looks correctly in Edge
![image](https://user-images.githubusercontent.com/7135724/151079182-d72ffdf9-eb6a-413e-a368-57075acd434c.png)

**Expected behavior**
On hover the sidebar icon should show next to the collection title

**Outline (please complete the following information):**
- Install: self-hosted in Docker
- Version: v0.61.1

**Comment by tommoor** [comment]
This is just CSS hover, so I'm quite sure it's either:

a) A bug with Firefox
b) You're signed in with an account that does not have permission to see these actions

**Comment by v-marinkov** [comment]
Definitely not B. I suspect it has something to do with Firefox and the media :hover query which dictates the display: flex on hover for these display:none icons but I can’t  be sure. Isn’t opacity the safer transition for when hiding elements?

**Comment by tommoor** [comment]
I don't think any of the maintainers have a Windows machine, if you wanted to PR a change that works for you on FF+Windows then we can test on other platforms.

**Comment by v-marinkov** [comment]
It seems to work now. Could have been something with my Firefox, Windows, etc. Safe to close it now I think
