### ISSUE TITLE
Quick Links should show document full path

### ISSUE THREAD

**Issue by abunet** [outline/outline#3007]
HI,
I've two collection that have nested documents with the same title (install)
![image](https://user-images.githubusercontent.com/804576/151135455-c7eb04ca-342f-49a9-9172-84c560b61a0d.png)

now I've another collection called Meetings.
when I create a new meeting document I want to add an internal link to _install_ document of _outline_ collection

The problem is that the quick link only shows the title and not the full document path.
![image](https://user-images.githubusercontent.com/804576/151136148-e54c48e4-517b-461e-811d-743f3c5e0472.png)

For a user is impossible to determine wich is the correct document to link

I know that it seems an enhancement but it's a big Issue for everyday usage

**Comment by tommoor** [comment]
Absolutely.
