### ISSUE TITLE
Cannot view historical version for documents in "View only" collection

### ISSUE THREAD

**Issue by rvk86** [outline/outline#3016]
When I click a previous version in the "History" overview of a document in a collection that I have "View only" rights for, the url briefly changes to `.../history/{some_id}`, but then I get immediately redirected back to the latest version of the document.

**To Reproduce**
1. Go to a document in a collection with "View only" permissions
2. Go to the "History" of that document
3. Click on a previous version of the document

**Expected behavior**
I expect to get a preview of the historical version of the document I clicked.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: hosted (getoutline.com)

**Desktop (please complete the following information):**
 - OS: Macos
 - Firefox
 - Version 96.0.2

**Comment by rvk86** [comment]
Additional info: I just realized this is only happening when the collaborative editing is enabled.

**Comment by tommoor** [comment]
Confirmed, thank you
