### ISSUE TITLE
Links revert to markdown if document is saved  with ctrl + enter (Edge)

### ISSUE THREAD

**Issue by kaloyankostov** [outline/outline#3019]
Hello, I recently started evaluating outline. Love the product and its simplicity. 

I noticed something in Edge while playing around earlier that I wasn't sure is a bug or if it had been reported after doing a bit of searching through issues. Essentially if you are inserting links in one document to another **(ctrl + k)** everything works fine if you exit the document using the **Done Editing** button. If you instead use a keyboard shortcut such as **(ctrl + ent)** to save and close the document the inserted link automatically reverts back to markdown and the interpreter/editor no longer shows it as an interactable link. This only happend for me in Edge and not in Chrome.

**To Reproduce**

1. Open any document
2. Insert a link to another document **(ctrl + k)**
3. After the link has been inserted, use **(ctrl + ent)** to save and exit document
4. Link reverts to raw markdown forever and is no longer interactable when vieweing the document

**Expected behavior**
Link should remain interactable regardless of the mechanism used to save and exit the document.

**Screenshots**
![image](https://user-images.githubusercontent.com/17098455/151377402-9201772e-de38-4330-94a9-8fe00a0c5c98.png)

**Outline:**
- Install: getoutline.com

**Desktop:**
 - OS: Windows 11
 - Browser: Edge
 - Version:  97.0.1072.69

**Comment by kaloyankostov** [comment]
Hi, is there a specific area I can clarify further, happy to provide more info. I did notice this happen once when clicking the done editing button as well, but I have not been able to repeat it.

**Comment by tommoor** [comment]
Could you check under **Settings -> Features** if your team has collaborative editing enabled?

**Comment by kaloyankostov** [comment]
Had a look, collaborative editing was **not** enabled. For completeness I turned it on and the problem no longer persist however I have also lost the ability to save and exit and the document stays in a perpetual editing mode. I haven't tried collab editing yet so I'm assuming that's the intended way it works? Thanks!

**Comment by tommoor** [comment]
> I haven't tried collab editing yet so I'm assuming that's the intended way it works? 

It is. We may introduce an optional "Edit" mode for collaborative editing but at this time we're experimenting with the seamless approach!
