### ISSUE TITLE
Note should wrap as usual in the filteritem.

### ISSUE THREAD

**Issue by iamsaumya** [outline/outline#3030]
<img width="446" alt="Screenshot 2022-01-29 at 6 21 00 PM" src="https://user-images.githubusercontent.com/40148448/151661687-218ae00e-51ca-4f7e-bc33-2809650dc4ab.png">

**Comment by tommoor** [comment]
arghhhh

**Comment by louisphn** [comment]
May I help with this?

**Comment by tommoor** [comment]
All yours
