### ISSUE TITLE
Unable to update document vía API

### ISSUE THREAD

**Issue by Shide** [outline/outline#3035]
Updating a document vía API does not work. 
Response is 200 but the text is the same as the creation text, but nothing is appended (if using `append=true`) or replaced. 
Document policies has `update=true`.

**To Reproduce**
1. Create a document via API
2. Update the document via API (with document Id instead urlId to avoid 403 invalid token error)
3. The document is not updated

**Expected behavior**
The document must be updated or the information must be appended.

**Outline:**
- Install: getoutline.com

MT-208 @moduon

**Comment by tommoor** [comment]
Hi @Shide – this functionality was removed as part of moving to collaborative editing. You can currently disable this feature to re-enable updating via API but the two do not work together and possibly may never.
