### ISSUE TITLE
Difficult to "exit" bulleted list, when writing bulleted list with multiple levels

### ISSUE THREAD

**Issue by jonatcb** [outline/outline#3039]
If you're editing a document and using a bulleted list with more than one level (i.e. indentation), it's difficult to end the list because the bullets continue (get added) upon hitting return key. Also seemingly difficult to delete those additional bullets via the keyboard.

**To Reproduce**
1. Go to edit a post
2. Begin a bulleted list
3. Indent one of the bullets, e.g.
```
- Here is a primary bullet
  - Here is a secondary bullet
 ```
4. After typing the secondary bullet, hit return a few times (to try to end the bulleted list and return to typing normal text).
5. The bulleted list continues, and does not end upon hitting backspace either.

**Expected behavior**
After hitting return a couple of time at the end of the bulleted list, you'd expect the bulleted list to end and go back to typing normal paragraph text.

**Screenshots**
Hard to show something not being deleted, but this is the result of the bug:
![Screen Shot 2022-01-31 at 2 04 21 PM](https://user-images.githubusercontent.com/98782569/151882155-cba0d8d3-cf46-4513-bf19-85306078b6e5.png)

**Outline (please complete the following information):**
- Install: getoutline.com
- Version: n/a

**Desktop (please complete the following information):**
 - OS:  macOS 12.1
 - Browser: Firefox
 - Version:  96.0.2

**Comment by tommoor** [comment]
Thank you for filing, this seems like a recent regression

**Comment by jonatcb** [comment]
Happy to do so -- thanks for fix!
