### ISSUE TITLE
Pasted text has some characters replaced with emoticons

### ISSUE THREAD

**Issue by PlkMarudny** [outline/outline#3045]
**To Reproduce**
1 . Open a new document
2. Try to paste the following into the editor: 
 ```ffmpeg.exe -err_detect ignore_err -i "udp://@239.128.2.2:5400?overrun_nonfatal=1&fifo_size=50000000" -filter_complex "[0:v]split=2[v2][v3]; [v2]scale=w=1280:h=720[v2out]; [v3]scale=w=640:h=360[v3out]" -map [v2out] -c:v:1 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:1 3M -maxrate:v:1 3M -minrate:v:1 3M -bufsize:v:1 3M -preset ultrafast -g 48 -sc_threshold 0 -keyint_min 48  -map [v3out] -c:v:2 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:2 1M -maxrate:v:2 1M -minrate:v:2 1M -bufsize:v:2 1M -preset ultrafast -g 48 -sc_threshold 0 -keyint_min 48 -map a:0 -c:a:0 aac -b:a:0 96k -ac 2 -map a:0 -c:a:1 aac -b:a:1 96k -ac 2 -map a:0 -c:a:2 aac -b:a:2 48k -ac 2 -f hls -hls_playlist_type event -hls_time 0.3 -hls_init_time 0.3 -hls_flags independent_segments delete_segments -hls_delete_threshold 1 -hls_segment_type fmp4 -hls_list_size 2 -sc_threshold 0 -g 8  -attempt_recovery 1 -recovery_wait_time 1 stream.m3u8```

**Expected behavior**
Would like to see the unchanged text, it is filled with emoticons instead

**Screenshots**
![image](https://user-images.githubusercontent.com/4361591/152106126-09385ec4-ce93-4087-b11b-81d28bb04428.png)

**Outline (please complete the following information):**
- Install: [getoutline.com]

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [firefox]
 - Version [97]

**Comment by tommoor** [comment]
If you paste into a code block then the emoji conversion won't happen, a code block is probably more appropriate for this type of content.

…however, agreed the behavior needs changing here 👍

**Comment by PlkMarudny** [comment]
But the code block is a single line only? And formatting the emoticonized
as a code does not remove those emoticons as well.

**Comment by tommoor** [comment]
The code block respects line breaks but there are none in this text.

If you create the code block and then paste into it that should work rather than formatting as code afterwards, Just trying to give you a work around until the problem is fixed
