### ISSUE TITLE
Outline Crashes when hovering above an internal link

### ISSUE THREAD

**Issue by antiq** [outline/outline#3046]
When I add a new document and save it with a link to another document (more specifically link to a collections page), the whole site crashes with a "NotFoundError".

Version: we use the cloud version using custom domains (https://internal-wiki.cloudtalk.io/)

Screenshot of the error an info from console:
<img width="1680" alt="Screenshot 2022-02-02 at 09 22 33" src="https://user-images.githubusercontent.com/10398434/152119150-ae880793-f1f2-4d5d-98ba-6b7135be2676.png">

**Comment by tommoor** [comment]
This is a development warning - you are running in development mode and should be running in production mode
