### ISSUE TITLE
Pasting from spreadsheets

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3058]
There is currently no good experience when pasting formatted spreadsheet-like data from outside sources

- Pasting from Google Sheets results in a single paragraph of spaced content.
- Pasting from Excel (desktop) results in an image of the pasted content. 
- Pasting from Excel (web) needs testing

**Comment by Toxminn** [comment]
this feature would greatly improve the user experience imo :)

**Comment by Toxminn** [comment]
@tommoor can you reopen this issue ?

**Comment by Toxminn** [comment]
+1
