### ISSUE TITLE
Clicking publish on Document asks: You have unsaved changes. Are you sure you want to discard them?

### ISSUE THREAD

**Issue by sebastian-ruiz** [outline/outline#3073]
I create a new document, type some text, then hit 'Publish'. I am then given the alert message:

```
You have unsaved changes.
Are you sure you want to discard them?

<Cancel> <OK>
```
![Screenshot 2022-02-07 at 10 58 52](https://user-images.githubusercontent.com/2012398/152766536-61615e56-9ca9-494f-9504-ed6da1bed0da.png)

It seems related to #746 but this one was closed a few years ago

I am running 

**To Reproduce**
1. Create new document
2. Write some text
3. Click Publish
4. See alert

**Expected behavior**
I don't expect to get this alert

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: self-hosted
- Version: outlinewiki/outline@sha256:e1746492002f12df429b440a74e033ce87d6c16ee06639884fe922c2953d9fb5
- (latest version as of time of writing)

**Desktop (please complete the following information):**
 - OS: Mac OS 11.6
 - Browser Firefox
 - Version 96.0.3 (64-bit)
also tested on (and same problem):
- Browser Chrome
- Version 98.0.4758.80

**Comment by tommoor** [comment]
See https://github.com/outline/outline/issues/2949 for details – the fix will be out in the next release
