### ISSUE TITLE
Right border of contents is overlapping with emoji prefixed document title

### ISSUE THREAD

**Issue by PhilReinking** [outline/outline#3088]
If an emoji is placed at the beginning of a document title, the title gets shifted to the left, so the start of the real title aligns correctly with the rest of the document. This is correct behavior.

But there is the issue that the emoji is then placed behind the right border of the Table of Contents component.

I think the table of contents needs adjustment in its position to solve that. I attach a screenshot here for reference.

**To Reproduce**
1. Create a new document
2. Put an emoji first in the title followed by some text
3. add a heading
4. save & view the document

**Expected behavior**
- the border of the contents component does not overlap with emoji

**Screenshots**
<img width="759" alt="CleanShot 2022-02-10 at 14 17 41@2x" src="https://user-images.githubusercontent.com/2592996/153416721-b1be115a-210f-4c9e-9423-cef09a63f237.png">

**Outline (please complete the following information):**
- Install: self-hosted
- Version: v0.61.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome/Brave
 - Version latest

**Comment by tommoor** [comment]
Hi @PhilReinking – thanks for filing, this is already fixed on `main` and will be included in the next release

**Comment by Nicicalu** [comment]
> Hi @PhilReinking – thanks for filing, this is already fixed on `main` and will be included in the next release

I have exactly that bug on the current version. Is it possible, that that fix didn't work properly?

My Info

**Outline:**
- Install: Self hosted
- Version: v.0.65.2 

**Desktop:**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 103.0.5060.114

**Comment by tommoor** [comment]
Please post a screenshot

**Comment by Nicicalu** [comment]
> Please post a screenshot

Sure, I noticed it only happens when there is a space between the emoji and the title:
![](https://i.imgur.com/n8L3wuP.png)
![](https://i.imgur.com/O8NhnPo.png)

**Comment by Nicicalu** [comment]
Sorry, here's an example where it actually goes over the line:
![](https://i.imgur.com/pajvZRt.png)

**Comment by tommoor** [comment]
Yea, that's unfortunately wide… I'm not sure we can keep making this gutter larger and larger 😆

**Comment by Nicicalu** [comment]
> Yea, that's unfortunately wide… I'm not sure we can keep making this gutter larger and larger 😆

Yea, that's fine. Was just FYI. I have bigger problems in life than 2px of the emoji ^^
Thanks though. Outline is an awesome project!

**Comment by tommoor** [comment]
Thanks, the long term plan here is to make the icon it's own field and separate from the rest of the title somehow… that should help to resolve these situations too.

**Comment by Nicicalu** [comment]
👌
