### ISSUE TITLE
Add `mod`+`enter` to exit code block

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3089]
### Discussed in https://github.com/outline/outline/discussions/3087

<div type='discussions-op-text'>

<sup>Originally posted by **Yajo** February 10, 2022</sup>
1. Create a tip.
2. Insert a code block inside.
3. How to exit the block and continue writing in the tip?

https://user-images.githubusercontent.com/973709/153396642-66c30d99-8f63-40db-9a12-110169d098fe.mp4

I tried clicking in between the block and tip, hitting enter multiple times, alt+enter, ctrl+enter... Can't do it!
</div>

**Comment by mikew** [comment]
I'm using Edge on macOS and this seems like it's gone back to being impossible. CMD+Enter has just published my draft, CTRL+Enter, Option+Enter, Shift+Enter, and any combination of those 4 buttons does nothing.

**Comment by tommoor** [comment]
Hmm, still working fine here and the fix remains. Cmd+Enter is still the hook for this on macOS.

**Comment by tommoor** [comment]
Ah, I see the issue – only occurs with seamless editing disabled

**Comment by tommoor** [comment]
Fixed 9b811c999
