### ISSUE TITLE
Add user preference to remember previous location

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3091]
We'd like to add a user preference to remember the last route you were looking at and redirect there upon reloading the app. This would take precedence over the team default collection if set.

**Comment by iamsaumya** [comment]
To make sure I understood correctly, A preference for users to override the default collection when they hit outline.getoutline.com and sign in again. Essentially just like it was previously. 

I'm confused, on which page should we add this preference? I believe it will be a toggle.
