### ISSUE TITLE
Full Tables Support

### ISSUE THREAD

**Issue by tommoor** [outline/outline#310]
Following on from https://github.com/jorilallo/atlas/issues/308

**Comment by jorilallo** [comment]
Got a ping about this at work

**Comment by ShiroYacha** [comment]
Hey,
I'm interested in working on this feature this weekend. Can I work on it in the rich-markdown-editor repo? since it's solely related to the editor...
Best

**Comment by ShiroYacha** [comment]
https://github.com/GitbookIO/slate-edit-table seems like a good candidate to integrate with. However, it does not support the concept of table headers as reported [here](https://github.com/GitbookIO/slate-edit-table/issues/25). Since we are using markdown, we will need to deal with it both at rendering and serialisation if we preserve its roll-only concept. Another solution is to add table header support to it.

I was able to get it working by override some of it's schema and validation logic and modify the block structure a bit. But for the long run, it's better to fork it and create a variant that supports table headers?

**Comment by tommoor** [comment]
Hey @ShiroYacha ! Headings are an interesting one, especially as both gitbook and dropbox paper seem to do without and just allow the user to bold the contents to signify a heading.

I wonder if would be good for a first pass to simply have the serializer output headings as standard table cells with bolded content? We could then use the `slate-edit-table` plugin as it stands. I don't doubt it would still need forking for other reasons though…

**Comment by ShiroYacha** [comment]
@tommoor that is a valid proposition 😄 I thought the header is necessary for a valid markdown table, but you mentioned gitbook did that it must be valid to just use table rows.. I'll try that later to see if how to do that.

**Comment by tommoor** [comment]
> I thought the header is necessary for a valid markdown table

It's possible it is. Would need to dig further

**Comment by glaand** [comment]
What is the status of this issue?

**Comment by peiying16** [comment]
I think table is important for all documents.

**Comment by gopeter** [comment]
I'm currently working on an integration of https://github.com/GitbookIO/slate-edit-table into the core of  https://github.com/outline/rich-markdown-editor.

But at the moment I'm struggling with the UI. @tommoor, this is the way I would go:

1. Adding the "add table" icon to the toolbar:

![image](https://user-images.githubusercontent.com/1242960/57439431-4b699a80-7246-11e9-8dca-21521c88a1b8.png)

2. If the cursor is inside the table (but did not selected any text), show an extra toolbar above the table with the following icons:
- Insert Column
- Insert Row
- Remove Column
- Remove Row
- Remove Table
- Set align left
- Set align center
- Set align right
- Toggle Header

Do you think that you could add these icons to https://github.com/outline/outline-icons?

3. If the users selects text inside the table, a reduced version of the formatting toolbar will appear:
- Bold
- Italic
- Deleted
- Code 
- Link

And that's the way I'm gonna do it right now. What do you think? 😄

**Comment by gopeter** [comment]
Oh no, I didn't recognized the `table-editing` branch 🙈🙈🙈OK, nevermind ... 😄

**Comment by tommoor** [comment]
Hey @gopeter – thanks for the notes, I think we're very much in-line – and like you noticed I recently started work on this in the past week 👏

**Comment by gopeter** [comment]
Great to see so much progress on this! And since my code actually looks *exactly* like your branch,  I can't contribute anything more 😄

**Comment by tommoor** [comment]
If anyone wants to give it tables a test the editor . work is available on this branch, I'm looking for folks to find bugs as it's quite a complicated project 😄 

https://github.com/outline/rich-markdown-editor/pull/84
