### ISSUE TITLE
Align subtext on toggle links in settings

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3109]
![image](https://user-images.githubusercontent.com/380914/153732762-da15fbb6-faf2-465f-9129-991025a1e2f3.png)

**Comment by iamsaumya** [comment]
Is this what Brian meant? 

<img width="713" alt="Screenshot 2022-02-19 at 1 00 58 PM" src="https://user-images.githubusercontent.com/40148448/154791537-be55a81e-707e-4816-9707-52460d322161.png">

**Comment by tommoor** [comment]
yep yep

**Comment by iamsaumya** [comment]
I think we have the same UI on security page too. We need to update it as well.

**Comment by iamsaumya** [comment]
Could you please review a possible implementation [here](https://github.com/outline/outline/compare/fix/switch?expand=1)? I cound put the label and note in a container because of `htmlFor` attribute.

**Comment by tommoor** [comment]
It looks right, but I'm not sure If I agree with the feedback anymore 😆

**Comment by iamsaumya** [comment]
Hehe, Shall we close this now? 

Btw I liked brian's idea of keylines. It will ensure a text doesn't make the positioning of icons unpredictable. Useful in components like DocumentListItem.

**Comment by tommoor** [comment]
Found this shot on Dribbble, I'm quite liking this two column layout – wondering if this might make sense for these type of settings pages

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/380914/155830468-749422fe-9291-47d5-a69b-d4a8d49d28b8.png">

<img width="516" alt="image" src="https://user-images.githubusercontent.com/380914/155830477-4d461208-823e-4d6a-99b4-cfe8e76953b8.png">
