### ISSUE TITLE
Delete/resync users when google email is the same but account has changed

### ISSUE THREAD

**Issue by ibonelli** [outline/outline#3123]
**To Reproduce**
1. Create a user which will have SSO access
2. Login, associate to a group or something and make sure it can access outline
3. Suspend the account in Outline
4. Delete the account in Google
5. Create a new account in Google with same email
6. Try to login to Outline using SSO
5. See error (won't be possible)

**Expected behavior**
In my head the system should detect the account change and resync using the chosen unique ID (email) instead of relying on the Google's SSO hash.

**Screenshots**
I'm sorry, do not have screenshots. But I hope description works.

**Outline (please complete the following information):**
- Install: We are using a self hosted version (in Heroku)
- Version: v0.60.3 (ad96961)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser chrome
 - Version 97.0.4692.71 (Official Build) (64-bit)

**Mobile (please complete the following information):**
Did not try in mobile, wasn't needed. Problem is not related to browser.

By the way I tried to fix this using the API [users.delete](https://www.getoutline.com/developers#tag/Users/paths/~1users.delete/post) but couldn't as it needs and admin token to be able to work and couldn't find a way to give admin role to that token. So I end it up fixing by getting into the DB and deleting the associated records to the user so I could create it again without prior associations.

Hope this helps. Cheers!

**Comment by tommoor** [comment]
This sounds like expected behavior, the unique identifier is the Google account id and we won't be changing it to a simple match on email. Do you have more details on what the error in step (7) is?

**Comment by tommoor** [comment]
I think if you had the error logs we could take a look and keep this open. It sounds most likely that Google retained the unique id for the new account, which would be surprising but without those logs there's not much to do here.

Thanks for filing and the blog post certainly might be useful to anyone that hits this in the future

**Comment by ibonelli** [comment]
Link to the article with the simple solution https://weknowinc.com/blog/outline-wiki-and-googles-sso-integration
