### ISSUE TITLE
Google form embed option

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3129]
### Discussed in https://github.com/outline/outline/discussions/3128

<div type='discussions-op-text'>

<sup>Originally posted by **jenningsb2** February 16, 2022</sup>
Hey team! 

I have a google form that I would love to use to capture feedback and interest on my documentation. I see that Google Docs/Sheets/Slides have an embedded option. 

**Would an embedded Google Form be an option?**

Since my company uses Google Workspace, it would be great to be able to stay in their ecosystem.</div>

**Comment by matbrgz** [comment]
My first try to do that https://github.com/outline/outline/pull/2291

**Comment by jordanaxani** [comment]
Would love this. We use Jotform so would love that too, one day, or alternatively an iframe embed option.

**Comment by matbrgz** [comment]
@jordanaxani could you please help me here?

**Comment by apoorv-mishra** [comment]
Duplicate of #3923
