### ISSUE TITLE
Sidebar updates

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3131]
Brian identified some nice usability improvements for the sidebar in his crit, particularly around hover states for different interactive elements, tweaking heading style and separating the team/user menus.

[Figma Designs](https://www.figma.com/file/QQYFeeSt39vfDwcdyIxb6Q/Outline?node-id=19%3A803)

**Comment by iamsaumya** [comment]
Neat. I'm curious. How are we handling disclosures in the new design?

**Comment by tommoor** [comment]
Blocked by https://github.com/outline/outline/pull/3102

**Comment by tommoor** [comment]
We'll incorporate your work first @iamsaumya – won't take these designs 1-1, just some aspects.
