### ISSUE TITLE
Add team preference to enable "Edit" button with collaborative editing

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3132]
Currently collaborative editing also means seamless editing, there is a read-heavy usecase for Outline where teams prefer to have an explicit edit mode but retain collaborative editing within that. This isn't a big deal to support and feels like a setting that will also ease the transition of the remaining customers to collaborative editing.

**Comment by acrob0t** [comment]
@tommoor On the topic of team options, would it be possible to also add a team option to disable display of profile pictures in the document? These documents can last a long time, in many cases they can even last longer than a team member that may have viewed them. 

As a work around, I have duplicated and then deleted documents to clear the pictures. However, the downside to this is that it breaks all of the internal links throughout Outline.

**Comment by Limezy** [comment]
I think there is currently a PR or an tracking issue for the pictures stack to be refreshed and remove deleted users

**Comment by tommoor** [comment]
Yep, merged just now: https://github.com/outline/outline/pull/3497

Suspended users will no longer appear. I don't think we'll add an option to remove the collaborators altogether though…

**Comment by ChetanGoti** [comment]
@tommoor Is this feature removed from the implementation planning? (I saw it as closed on 0.65.0 milestone but didn't see any commit/PR)

**Comment by tommoor** [comment]
I honestly don't know how this got closed.

**Comment by tommoor** [comment]
This is now deployed to cloud-hosted Outline. Seamless editing remains the default, but you can optionally enable an "Edit" button for your team under **Settings -> Features**.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/380914/193464428-0794be38-4ac0-4152-898b-6e84a0bfbe14.png">

**Comment by bmm-alc** [comment]
> This is now deployed to cloud-hosted Outline. Seamless editing remains the default, but you can optionally enable an "Edit" button for your team under **Settings -> Features**

great addition. 
Thanks for the feature Tom
