### ISSUE TITLE
Archive collections

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3141]
### Discussed in https://github.com/outline/outline/discussions/3138

<div type='discussions-op-text'>

<sup>Originally posted by **michaelkarrer81** February 16, 2022</sup>
We use collections often as a "Project Wiki". After a project is done we would like to archive the full collectrion with all of it's content. It might be used as a reference in the future but only in very rare occasions. </div>

**Comment by truongdo** [comment]
@tommoor  is there any update on this issue? It is a very useful feature in my opinion.

**Comment by tommoor** [comment]
It's a no-brainer feature, just one of many that need to be built 😭 . How are you imagining archived collections would work for your usecase?

**Comment by truongdo** [comment]
We are using outline for project documentation, and as many projects are processed per year, we need to archive them as they are completed to make the site clean.

**Comment by tommoor** [comment]
I think there is just a question of quite what archived collections look like/where do they live. Can you still navigate through them?

**Comment by mortbauer** [comment]
Would probably be great to still navigate it, but move into the "archive collection", i mean just treat the Archive in the sidebar as top level collection (would probably need sub collections then).

**Comment by tommoor** [comment]
Archive becomes a collapsible heading…

**Comment by max-mykhailenko** [comment]
I use a collection to manage projects, and once a project is completed, I need to archive the collection. Alternatively, I can delete the collection if I can restore it later when work resumes.

**Comment by AlexShku** [comment]
It would be great to have possibility to  Archive collection with saving all nested structure.

**Comment by almereyda** [comment]
Maybe a slight variation of the theme could be to group collections into sections. In this case collections could optionally inherit their permissions from the section.
