### ISSUE TITLE
SequelizeValidationError: Validation error: Validation isIn on language failed

### ISSUE THREAD

**Issue by PHClement** [outline/outline#3156]
When I log in with Slack : 
`{"error":"Validation error: Validation isIn on language failed","stack":"SequelizeValidationError: Validation error: Validation isIn on language failed\n `

**To Reproduce**
1. Go to Login Page
2. Click on Login with Slack
3. See error

**Expected behavior**
{"error":"Validation error: Validation isIn on language failed","stack":"SequelizeValidationError: Validation error: Validation isIn on language failed\n 

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome

**Comment by tommoor** [comment]
Self hosted or getoutline.com?

**Comment by PHClement** [comment]
> Self hosted or getoutline.com?

Self hosted

**Comment by tommoor** [comment]
Then your `DEFAULT_LANGUAGE` environment variable contains an invalid value, best be one of: 
https://github.com/outline/outline/tree/main/shared/i18n/locales
