### ISSUE TITLE
New nested document converts to "Untitled" and cannot be edited

### ISSUE THREAD

**Issue by victordariovera** [outline/outline#3158]
When you create a new nested document, it appears on the tree of contents but when you click on it transform into "unititled" and cannot be edited.

**To Reproduce**
1. Create a new nesterd document
2. Save
3. Search it on tree and click on them
4. It transforms into "untitled" document and cannot be edited.

**Expected behavior**
Edit the new nested document

**Screenshots**

**Outline (please complete the following information):**
- Install: selfhosted
- Version: v0.61.1 , I'm using docker image outlinewiki/outline:latest

**Comment by victordariovera** [comment]
Rollback to DockerHub image tagged outlinewiki/outline:0.60.3 seems to be ok.

**Comment by tommoor** [comment]
I can't reproduce this behavior on `main` or `getoutline.com`, I suspect it was fixed in the last month of work.

**Comment by tommoor** [comment]
Please try `v0.62.0` and let us know if you still see the issue
