### ISSUE TITLE
title field does not get focused when a launching "new document" in a collection coming from the home view

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#3178]
video demo https://www.loom.com/share/697d762c20714a53bfdbbebe8e72f906

**Comment by tommoor** [comment]
Looks like this is solved by updating React:
https://github.com/facebook/react/issues/14536#issuecomment-861980492

The problem is the focus hook is fired while the component is still `display: none` by React Suspense. The new behavior is to delay the hook firing
