### ISSUE TITLE
Allow admins to list collections in settings

### ISSUE THREAD

**Issue by 0ff** [outline/outline#3188]
**To Reproduce**
1. Create a new team with 2 users
2. Create a new collection, set is as default read-only, remove one user's write-access from the collection, leave one user as editor
3. Remove the editor user
4. There is no way for anyone else to edit this collection in the future

**Expected behavior**
Upon removing the user from the team, Outline should check if there are any collections where that user is the **only** editor and then grant edit rights to the teams administrators.

**Outline (please complete the following information):**
- Install: getoutline.com

**Comment by tommoor** [comment]
If this happens on Outline cloud-hosted then please reach out to support.

An alternative fix here that also covers some other usecases is to allow admins to see a list of which collections exist in the team and they can add themselves as a member to any collection to gain access to content.
