### ISSUE TITLE
Update twitter link in email notifications

### ISSUE THREAD

**Issue by jdaviescoates** [outline/outline#3193]
This is a small thing, but the twitter link included in email notifications on self-hosted Outline links to https://twitter.com/outlinewiki instead of https://twitter.com/getoutline

**Comment by Limezy** [comment]
@jdaviescoates which version are you currently using ?
I have checked and it looks like this is no longer an issue.
https://github.com/outline/outline/blob/175857753e73407d6c3cda8c5f2e7057d87b6a94/shared/utils/urlHelpers.ts#L35
