### ISSUE TITLE
XMLParserError: Unexpected close tag when exporting collection.

### ISSUE THREAD

**Issue by leo020588** [outline/outline#3209]
Exporting a collection gives an error. Checking the logs whit `docker-compose logs` I found the following error:

```json
{
	"error": "Unexpected close tag\nLine: 5\nColumn: 7\nChar: >",
	"stack": "XMLParserError: Unexpected close tag\nLine: 5\nColumn: 7\nChar: >\n    at error (/opt/outline/node_modules/sax/lib/sax.js:651:10)\n    at strictFail (/opt/outline/node_modules/sax/lib/sax.js:677:7)\n    at closeTag (/opt/outline/node_modules/sax/lib/sax.js:871:9)\n    at SAXParser.write (/opt/outline/node_modules/sax/lib/sax.js:1436:13)\n    at Parser.exports.Parser.Parser.parseString (/opt/outline/node_modules/xml2js/lib/parser.js:322:31)\n    at Parser.parseString (/opt/outline/node_modules/xml2js/lib/parser.js:5:59)\n    at NodeXmlParser.parse (/opt/outline/node_modules/aws-sdk/lib/xml/node_parser.js:31:10)\n    at Request.extractError (/opt/outline/node_modules/aws-sdk/lib/services/s3.js:696:39)\n    at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/opt/outline/node_modules/aws-sdk/lib/request.js:686:14)\n    at Request.transition (/opt/outline/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/opt/outline/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /opt/outline/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:688:12)\n    at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at Request.emit (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/opt/outline/node_modules/aws-sdk/lib/request.js:686:14)\n    at Request.transition (/opt/outline/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/opt/outline/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /opt/outline/node_modules/aws-sdk/lib/state_machine.js:26:10",
	"level": "error",
	"message": "Error exporting collection data"
}
```

**Outline:**
- Install: self hosted
- Version: 0.62.0

**Desktop:**
 - OS: Windows 10 x64
 - Browser: Chrome
 - Version: 99.0.4844.51 (Official Build) (64-bit)

**Comment by leo020588** [comment]
I still experience this issue update after update till the current version 0.65.1.
Is there any news on this?

**Comment by tommoor** [comment]
It was closed due to inactivity and being unable to reproduce. Im confident this is a configuration error, seems to be some problem uploading to storage?

**Comment by leo020588** [comment]
Yes, I can upload images without problems.

I use the docker setup: outline and minio as containers, postgress and redis are setup externally.

Everything works as expected for what I have seen.

I can publish my configuration files I that could help.

**Comment by tommoor** [comment]
Got for it

**Comment by leo020588** [comment]
Here it is
https://gist.github.com/leo020588/334beba4f05ab7497a77c0ddabfb0bc4

**Comment by luistar15** [comment]
Hi @tommoor, perhaps did you had the chance to check my setup? I'm hopping that there is some misconfiguration to fix that can solve my problem.

**Comment by brubellizzi** [comment]
Hi there, I have the exact same problem exporting in v0.65.2, so I cannot backup my documents at the moment! How are you guys taking backups of your documentation without this feature?

My configuration is VERY similar to the one shared by @leo020588 earlier (Minio as S3 backed)

**Comment by tommoor** [comment]
This is not an error in Outline, it's the result of Minio responding with an error. The error should be in Minio logs, my guess is it's disk space or memory limit of some kind

**Comment by leo020588** [comment]
> This is not an error in Outline, it's the result of Minio responding with an error. The error should be in Minio logs, my guess is it's disk space or memory limit of some kind

I didn't see any operations in minio logs or trace (in minio console) regarding the zip upload.
I also setup a webhook for All fileOperation events which isn't working either (even for regular images in the  wiki pages).

If the error isn't in outline and I could not find the error in minio logs, then the error is in somewhere else.
So I check the nginx proxy logs and I found the error:

```log
[error] 5122#5122: *248094 client intended to send too large body: 64746905 bytes, client: 100.100.100.100, server: wiki-minio.app.mydomain.com, request: "PUT /outline-bucket/uploads/6df18ccd-8627-4e0a-9429-a93401c392dc/d460efc4-2936-40bf-8878-77f0079b09cf/Attach-export.zip HTTP/1.1", host: "wiki-minio.app.mydomain.com"
```

So the problem was trying to upload 62MB file when the nginx max upload limit was 10MB.

I have left 10MB upload limit for the wiki and incremented to 200MB for minio server and now the export is working as expected.

I also updated [my setup](https://gist.github.com/leo020588/334beba4f05ab7497a77c0ddabfb0bc4) with the mentioned modifications.

**Comment by tommoor** [comment]
Thanks for adding the comment, I’m sure this will be useful to others in the future

**Comment by brubellizzi** [comment]
Worked for me too. Thank you for sharing @leo020588

**Comment by leo020588** [comment]
It would be useful if outline could also log http status codes and reason phrases in case of http related errors.
Such data would have easily helped to identify the problem in this case.

**Comment by leo020588** [comment]
>How are you guys taking backups of your documentation without this feature?

Hi, we have not launched the wiki yet. But we were planning program a task to backup the database, the minio volume (./data/minio_root) and the minio bucket/user configuration. I don't known if this last part is even possible.

**Comment by sumadark** [comment]
Hello @leo020588 ,

I have just reached this page because I am encoutering the exact same error on my server, and I am not able to resolve it following your explanation. Could you take a look at my case please ?

Here is my docker file :
`version: "2"
services:
  outline_redis:
    image: redis
    restart: always
    container_name: outline_redis
    networks:
      - outline-internal

  outline_postgres:
    image: postgres:latest
    restart: always
    container_name: outline_postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=XXX
      - POSTGRES_DB=XXX
    networks:
      - outline-internal
    volumes:
      - /home/XXX/outline/container-data/db:/var/lib/postgresql/data:Z

  outline_minio:
    image: minio/minio
    restart: always
    container_name: outline_minio
    volumes:
      - /home/XXX/outline/container-data/data:/data:Z
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
  ports:
      - 9000:9000
      - 9001:9001
    networks:
      - reverseproxy-nw
    command: "server /data --console-address :9001"

  outline:
    image: outlinewiki/outline:latest
    user: root
    restart: always
    container_name: outline
    command: sh -c "yarn db:migrate --env=production-ssl-disabled && yarn start --env=production-ssl-disabled"
    depends_on:
      - outline_postgres
      - outline_redis
      - outline_minio
    environment:
      - PGSSLMODE=disable
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - DATABASE_URL=postgres://outline:${POSTGRES_PASSWORD}@outline_postgres:5432/outline
      - REDIS_URL=redis://outline_redis:6379
      - URL=${WIKI_URL}
      - PORT=443
      - AWS_ACCESS_KEY_ID=minio
      - AWS_REGION=eu-west-3
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_S3_UPLOAD_BUCKET_URL=${WIKIDATA_URL}
      - AWS_S3_UPLOAD_BUCKET_NAME=outline
      - AWS_S3_UPLOAD_MAX_SIZE=26214400
      - AWS_S3_FORCE_PATH_STYLE=true
      - AWS_S3_ACL=private
      - OIDC_CLIENT_ID=outline
      - OIDC_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
      - OIDC_AUTH_URI=XXX
      - OIDC_TOKEN_URI=XXX
      - OIDC_USERINFO_URI=XXX
      - OIDC_USERNAME_CLAIM=email
      - OIDC_DISPLAY_NAME=Keycloak
      - OIDC_SCOPES=email
  ports:
      - 7443:443
    networks:
      - outline-internal
      - reverseproxy-nw

networks:
  outline-internal:
  reverseproxy-nw:
    external: true`


I am using Nginx Proxy Manager in docker too, with mariadb.
I have looked in NPM to make the modifications about Upload Size but ut does not seem to change anything.

Hope you'll have more ideas than me :-) 

Thanks for the help !


Suma

**Comment by sumadark** [comment]
@leo020588 : well, I don't know how exactly I have solved the problem, but maybe it seems it was related to Cloudflare Proxy and 100Mo upload limit... anyway I have resolved the case so do not need support anymore, thank you for the inspiration !
