### ISSUE TITLE
Changes lost in collaboration mode with certain character combinations

### ISSUE THREAD

**Issue by 0ff** [outline/outline#3230]
Today I've noticed that Outline would not save a document I had open, in fact I wasn't able to save any changes in this document until I exited my browser and reloaded the whole page.

I cannot reproduce it, but I have noticed in the past that pages seem to load with old content, then refresh the instant they are rendered. I believe there is a discrepancy between my local state (indexDB?) and the servers ("api server" and "collaboration server") that, in this case, lead to loss of quite a lot of work.

As we want to use outline as our main knowledge-base, this is of course a very big deal. I see how this bug-report is rather limited in information-content, but maybe you can re-evaluate showing an indicator of any kind if server and client don't match.
Also, in my video below, please note that the response of manual save (cmd+s) actually **differs from the text shown**. I did not capture that on video, but the server actually told the client that and old state was saved - this must be indicated to the user!

**Expected behavior**
Outline should show a clear indicator if the states of any of the backends does not match what is saved locally.

**Screenshots**
Here's a video of the bug, note how I change the emoji, then hit cmd+s (just to be very sure it saved) then reload.
I can provide an uncensored video on request if needed.

https://user-images.githubusercontent.com/1755213/157867398-ca467bb0-07be-4416-983f-77f87ed4febf.mp4

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version Latest (Version 15.3 (17612.4.9.1.8))

**Comment by tommoor** [comment]
Sorry to hear you lost work, this is very unusual as the architecture keeps a local copy, a remote copy, and a text cache.

> Also, in my video below, please note that the response of manual save (cmd+s) actually differs from the text shown. I did not capture that on video, but the server actually told the client that and old state was saved - this must be indicated to the user!

It's not as simple as this, the text content received from the API is the cache. CMD+S also doesn't save the text state in the way you're thinking as every key stroke of collaborative state goes through a websocket connection. My guess is that there may have been an editor error which prevented edits after the error from saving in this case although there aren't any matching error logs. Will investigate further and get back to you – are you seeing this issue on other docs?

**Comment by tommoor** [comment]
It looks like collaborative editing is turned off now, you should be aware that if you re-enable documents will revert to how they were when you last had it turned on as the state is stored separately. It's not really meant to be toggled off once enabled, we should make this irreversible

**Comment by 0ff** [comment]
> you should be aware that when you re-enable again documents will revert to how they were when you last had it turned on

That is a terrible, terrible user-experience. Please make that abundantly clear, not only when trying to disable collaboration, but also **before** enabling. I fully understand (and don't want to question) the technical reasoning, but as a user I did not expect that - both when enabling and now that I've disabled that.

> CMD+S also doesn't save the text state in the way you're thinking as every key stroke of collaborative state goes through a websocket connection.

I'd like to argue that it *should*. I mean I can see a post-request (separate from the websocket) so it is doing _something_, and also the blue loading-bar appears on the top. So again, as a user I totally expected this to be some kind of last-resort-manual-save thing. Please also make that clear _somewhere_, ideally, of course, right as I press `cmd+s`.

> Will investigate further and get back to you – are you seeing this issue on other docs?

Please do that. As for the other question, to be honest I don't know. However, I am very sure I saw a somewhat-related situation on the document `648650fc-23ec-4cb5-9917-3ab7fce055de` - here, on March 10 around 14.31 (CET) I noticed the following:
1. I saved the document hours (maybe days) before that time and checked some of the checkboxes
2. A colleague of mine opened the document at that time and saw the boxes un-checked
3. I opened the document after him, **didn't change anything** and the document updated for the both of us (this was also reflected in the status, i.e. `You saved less than a minute ago`

So after your explanation, it seems to me that I had an error saving earlier (in 1.) (which I don't remember seeing displayed anywhere), my colleague saw an old version stored in the collaboration server (in 2.) and that it updated from my local state only when I visited that exact page (in 3.) - is that correct?

1. Is there any way for you to detect and tell the user that there was an error?
2. Can you sync all the local states regardless of what page I'm on **only if I was the last editor** so I don't overwrite any else's work?

**Comment by tommoor** [comment]
Upon investigation you hit this bug https://github.com/yjs/yjs/issues/303 in the underling sync library, it's very rare and only happens with certain emoji combinations. I was able to reproduce it by doing the same emoji replacement… while it can't be immediately fixed we'll put in a catch to notify in the event that this happens

**Comment by 0ff** [comment]
Wow, that's a very surprising result - thank you for the investigation! I strongly believe that this would explain my observations, from memory all of the pages I've noticed this on were using some combination of emojis so showing a warning would most certainly avoid this situation in the future.
