### ISSUE TITLE
(German) magic link login notice lacks a space after email address

### ISSUE THREAD

**Issue by almereyda** [outline/outline#3241]
**To Reproduce**

1. Activate login via email.
2. Login via email.
3. Read the notice and find the email address glued to the following text.

**Expected behavior**

The email address is separated from flowing text.

**Screenshots**

![Check your email - Outline](https://user-images.githubusercontent.com/1645308/158215673-ff14a47c-fab3-4fcf-8ed7-2a77126bd90d.png)

**Outline:**
- Install: self hosted
- Version: 0.62.0

**Comment by tommoor** [comment]
Thanks, addressed in next i18n pull: https://github.com/outline/outline/pull/3233
