### ISSUE TITLE
Magic link login notice assumes a user had been invited prior trying to login.

### ISSUE THREAD

**Issue by almereyda** [outline/outline#3242]
When logging in through the magic link option, a message is shown which is the same for users with email addresses being present for (invited) users, and those that are not.

The message makes you expect an email, even if it may not arrive, due to an inexisting user.

**To Reproduce**

1. Login via an email address not previously invited to the instance.
2. Read the login notice message.
3. Expect a message arriving, even if it doesn't.

**Expected behavior**

In my expectation, the magic login is right in not revealing any information about the presence of a given user account.

Yet its message could indicate a hint to users who don't know if they have been invited already. The message could state something like:

> A magic login link has been sent to the provided address, in case you had previously been invited here. No password will be required to complete.

> A login link will be sent to your email address, if present in user directory.

> If you already have an account here, a login link has been sent to your address.

Something like this. My English is not so well today.

**Outline:**
- Install: self hosted
- Version: v0.62.0

**Comment by tommoor** [comment]
Mostly agreed, I can change in English but it'll take time for the individual translations to be updated.

**Comment by almereyda** [comment]
Thanks. I'll see if I manage to join the Crowdin work and to contribute for my mother tongue.
