### ISSUE TITLE
Cannot see embedded private google drive documents

### ISSUE THREAD

**Issue by Yajo** [outline/outline#3247]
If you embed something from google drive that isn't shared publicly, Firefox will refuse to load the iframe. In the case of Chrome, Google will refuse to let it load.

**To Reproduce**
1. Upload one video to google drive.
3. Do not make it public.
4. Copy its share URL.
5. Embed it in an outline document.

**Expected behavior**
Google drive page loaded. If logged in, it should display the document. Otherwise, it should somehow let you log in.

**Screenshots**
Firefox:
![image](https://user-images.githubusercontent.com/973709/158328236-bfe0b9fb-0564-4bf4-b49e-38af005b8c9b.png)

Clicking on "learn more" leads to https://support.mozilla.org/en-US/kb/xframe-neterror-page.

Chrome:
![image](https://user-images.githubusercontent.com/973709/158328842-491a4137-2419-4264-857b-e47dc2f3ebba.png)

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: Fedora 35 Silverblue
 - Browser Firefox / Chromium
 - Version 98.0 / 99.0.4844.51 (Official Build, ungoogled-chromium)

@moduon MT-390

**Comment by tommoor** [comment]
Hi @Yajo – It could be that the link isn't valid or isn't being converted to an embed correctly, but we'd need the link to verify. You can send to hello@getoutline.com instead of posting publicly.

**Comment by tommoor** [comment]
There is nothing wrong with the link you sent, it is as expected. I suspect this is due to blocked third-party cookies – how to change this depends on your browser.

**Comment by Yajo** [comment]
Actually I can see the iframe sends this header:

    

    content-security-policy: script-src  'report-sample' 'nonce-iXZsBabcy5HBhpHygkdQYg' 'unsafe-inline'  'unsafe-eval' 'strict-dynamic' https: http:;object-src 'none';base-uri  'self';report-uri https://csp.withgoogle.com/csp/viewer/

According to what I see in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy, it seems like it's Google itself blocking iframe usage, is it? 🤔

**Comment by yajo** [comment]
FWIW I managed to get the site working by disabling strict security in the outline website:
![imagen](https://user-images.githubusercontent.com/973709/198284009-f84c67ae-d064-4b69-9981-c6d92d4e9691.png)
