### ISSUE TITLE
Google Documents embed Cookie Warning on Safari

### ISSUE THREAD

**Issue by willblackmore** [outline/outline#3263]
**To Reproduce**
1. Embed a Google Doc (one stored in Google Drive within an organisation workspace) on a page
2. Visit the page using the latest Safari web browser
3. An error will show stating "Cookie Access Failed"
4. The link below the message is non functional so the error persists

**Expected behavior**
The Google Doc is embedded and viewable within the page.

**Screenshots**
![example](https://user-images.githubusercontent.com/1260445/158848194-f3ef721f-a73a-4d97-ae93-c6d1bfaa46cb.png)

**Outline (please complete the following information):**
- Install: engageinteractive.getoutline.com

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari (latest stable)
 - Version 15

**Comment by tommoor** [comment]
I don't think there is anything we can do here, if you're blocking third-party cookies in the browser then there is no way for Google to check your signed in session. 😢

**Comment by tommoor** [comment]
Merging with #3247
