### ISSUE TITLE
Chinese texts with links cannot get bold font

### ISSUE THREAD

**Issue by wohenbushuang** [outline/outline#3289]
Texts in English with links will automatically get bold, but not in Chinese

**To Reproduce**
Paste these into document as an example
```md
设置 Slack 集成

设置 [Slack 集成](/integrations/slack)

**设置 Slack 集成**
```

**Expected behavior**
Texts in Chinese with links should also get bold for attentions

**Screenshots**
![image](https://user-images.githubusercontent.com/15613184/160252446-9a0ee830-f9e6-4582-8949-8e9d6aae6c57.png)

The first line is the regular display. The second line is with link, where English text gets bold but Chinese text doesn't changed. Text is set to be bold font in the third line.

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.62.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version v99

**Comment by tommoor** [comment]
I should note that links are weight 500 and bold is 600 weight, so there _is_ a display difference between the two. The CSS is correct so this is a function of the Windows typeface not rendering 500 weight particularly well with Chinese characters.

**Comment by wohenbushuang** [comment]
What about mark the link texts with a different color instead of font weight? e.g. as [Github](/) does.
