### ISSUE TITLE
[bug] Copy + Paste won't keep markdown formatting

### ISSUE THREAD

**Issue by lowercase00** [outline/outline#3298]
Copy paste to/from Outline not supported

**To Reproduce**
1. Write markdown in any other editor (VScode / Bear tested)
2. Copy from editor
3. Paste to Outline

Result will be raw text with the markdown code.
 
**Expected behavior**
It would be expected that Outline understand the code and would format the markdown
If copying a text written in Outline to VSCode it also doesn't keep the markdown format.

**Outline (please complete the following information):**
- Install: self hosted
- Version: (can't find the version on the UI, will check the server latter on)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Brave (Chrome)

**Comment by tommoor** [comment]
Markdown detection is on a best-effort basis, there is no way of knowing if you're pasting markdown or plain text short of guessing based on the contents. Because of this if you have an example of the clipboard content that isn't detected as Markdown that could be more actionable.

**Comment by lowercase00** [comment]
@tommoor it's actually pretty simple texts.

I mostly write in VSCode and Bear (macOS), Bear is actually pretty good in detecting it, so in my mind it was something trivial (just found it is not). I indeed tested a copy paste on SlateJS (I guess you guys use it also if I'm not mistaken), and indeed is not very accurate. SimpleMarkdownEditor seems to work a bit better in that sense.

Would it be possible to always interpret the input as Markdown? Or maybe have an option for that?
Or maybe a "paste special" funcionality or something in which the user would define what it's pasting (I would favor the "this is always markdown approach").

My experience writing with Bear is the best I've had so far (just a suggestion as a benchmark, not directly comparable since I guess is Swift or something), Zettlr also has nice functionalities: I personally like the option to render (or not render) the markdown symbols.

Thanks for the quick response!

**Comment by tommoor** [comment]
> it's actually pretty simple texts.

In some ways this may be the issue, the more Markdown you paste the more likely to detect it is.

>  I indeed tested a copy paste on SlateJS (I guess you guys use it also if I'm not mistaken)

We do not. The paste detection code is custom – the logic is here:
https://github.com/outline/outline/blob/main/shared/editor/plugins/PasteHandler.ts#L145

**Comment by FetchFast** [comment]
There should at least be a workaround, such as some markdown to include in the paste to get it to recognise, or a way to paste it manually. I'm going to look now to try and find a website to convert the format for me

**Comment by tommoor** [comment]
<img width="236" alt="image" src="https://github.com/user-attachments/assets/fed8e1a7-f0f9-4985-ba96-7d42ca3f5d76">

This is the way

**Comment by FetchFast** [comment]
I appreciate it, but it didn't work for me so far, keeping the *** headers etc

Here's a website that can do it. Have to use select all:
https://www.switchlabs.dev/markdown-to-richtext
