### ISSUE TITLE
Triple click in code block should highlight line

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3304]
- 1 click place cursor
- 2 click highlight word
- 3 click highlight line
- 4 click highlight entire block

**Comment by CuriousCorrelation** [comment]
@tommoor I think we can do this by handling `mousedown` event - maybe something like "on triple click, select line".

Simplest implementation that I could think of was adding this functionality as a plugin

``` jsx
// outline/shared/editor/plugins/CodeBlockClick.tsx
...
...
  const { selection: { $from, $to } } = view.state;
  return $from.sameParent($to) && event.detail === 3;
...
...
```
I can do some research and write PR if you'd like to test this out

**Comment by tommoor** [comment]
You don't need a separate plugin, could be implemented within the existing `CodeFence` node – the approach is worth a try

**Comment by CuriousCorrelation** [comment]
Just tested it out and... the logic works :partying_face: 

>could be implemented within the existing CodeFence node

Would you mind pointing out where I should move this code in `CodeFence`?

**Comment by tommoor** [comment]
Add an inline Plugin here: 
https://github.com/outline/outline/blob/9fef7fc5ecd5d19bf676a03d455d2d9f0450b2d5/shared/editor/nodes/CodeFence.ts#L286

Similar to:
https://github.com/outline/outline/blob/c5a11fe17b6d2ae2f40c6d1c221d13e531321fbe/shared/editor/marks/Placeholder.ts#L38

**Comment by CuriousCorrelation** [comment]
Thank you.

So plugins in `outline/shared/editor/plugins/` are reusable but if it's applicable to only one specific type of node, then it should be in-lined.

**Comment by tommoor** [comment]
As a rule. Some of the larger, more complex, plugins have been pulled out even though they’re not reused for clarity though
