### ISSUE TITLE
Pasting text from Google doc will automatically underline text

### ISSUE THREAD

**Issue by rvk86** [outline/outline#3320]
Whenever copy/pasting test from a Google doc, all pasted text will be underlined. This doesn't seem to be a problem when pasting from Word. Thanks for looking into it!

**To Reproduce**
1. Open a new document in Outline
2. Copy some text from a Google doc
3. Paste into Outline document

**Expected behavior**
I would expect the styling to be the same as styling in the Google doc.

**Screenshots**
<img width="552" alt="image" src="https://user-images.githubusercontent.com/8648388/161259939-584afc30-59ea-424b-b231-8fb3927e7d82.png">

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: firefox
 - Version: latest

**Comment by tommoor** [comment]
Strange, I can reproduce in Chrome too. It's not immediately clear why this would be the case but it shouldn't be too tricky to solve.
