### ISSUE TITLE
There should be a separator between notice containers and integrations

### ISSUE THREAD

**Issue by Limezy** [outline/outline#3330]
This is **really** a small issue that could be solved with one line code... But anyway, Outline feeling is all about details !
As per my title : I think there should be a separation between "Tip notice" and "Airtable".
Tip notice is hardcoded into the editor, whereas Airtable is an optional integration.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/24638389/161418566-05286d49-5624-40db-bad0-b256a688140b.png">

**Comment by tommoor** [comment]
This actually turned out to be a bug after all – there _should_ have been a separator 😆
