### ISSUE TITLE
Collection can not be deleted?

### ISSUE THREAD

**Issue by michaelkarrer81** [outline/outline#3331]
We created a collection and there are no documents in it. Now we can not delete or rename it.
As you may see in the following screenshot even an account with administrator rights has only two options in the menu of the collection?!

![image](https://user-images.githubusercontent.com/6480630/161485539-f6591ffe-6ea7-4a5a-aed4-e894b29c3ec2.png)

**Comment by tommoor** [comment]
Hi Michael, currently even admins can have write permission removed for individual collections. It looks like that's what has happened here - you can email hello@getoutline.com for more support.

We should look at increasing the permissions for admins here though.

**Comment by michaelkarrer81** [comment]
Hi @tommoor thanks for your answser! I did write to hello@getoutline.com two or three weeks ago - since we got no reaction i tried it this way... I will send an other mail.
