### ISSUE TITLE
below line is temporary duplicated when typing a dead-key for first letter of a line

### ISSUE THREAD

**Issue by bmm-alc** [outline/outline#3371]
funny minor bug

**To Reproduce**
1. Use a keyboard mapping International US (I think this matters as I had strange bug on other software because of that)
2. Have a line of text written
3. Insert a line above, and start the line by typing a dead-key (like `, ~, ', ^, ...) (for instance to type É) 
4. Until you typed the letter following the dead-key, you'll see the below line is duplicated

**Expected behavior**

**Screenshots**
https://user-images.githubusercontent.com/80455946/163213352-23f49737-e860-45fc-bdba-f45f356cf82c.mp4

**Outline (please complete the following information):**
- Install: self hosted
- Version: tag 0.63.0-1

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 98

**Comment by bmm-alc** [comment]
> That will establish if the bug is in the framework or our editor code

I cannot reproduce the bug on the editor widget.

**Comment by Limezy** [comment]
I can't reproduce that bug, even though I'm also using US International.
I'm not sure it's linked to the layout ?

**Comment by tommoor** [comment]
I have reproduced and narrowed it down to the BlockTrigger widget decoration rendered here, removing this resolves the issue:

https://github.com/outline/outline/blob/main/shared/editor/plugins/BlockMenuTrigger.tsx#L129-L142

However there is nothing special about it, so really seems like an internal Prosemirror bug.

**Comment by tommoor** [comment]
Filed as ProseMirror issue 1289 (I don't want to create a relationship in GitHub at this time, hence no link)

**Comment by Limezy** [comment]
Thanks. Do you think this could have sine kind of link with issue #3210 ?

**Comment by tommoor** [comment]
Unlikely I think 😞

**Comment by tommoor** [comment]
A fix was made in prosemirror thanks to this report, just waiting for a release to be made now 👍

**Comment by bmm-alc** [comment]
thanks for the info
