### ISSUE TITLE
The state of the app is confusing after the user chooses to "templatize"

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#3396]
Even though it's non-destructive, it seems like I'm editing the same document as before, now converted to a template. The title of the new template and the title of the source doc are the same.
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/427579/163653157-bd7316f4-f17e-4c83-8aae-5d8523788f47.png">

I think we should prepend something like "template from " to help disambiguate, so we end up with something like this
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/427579/163653213-f8ef06a3-9a4e-468b-909e-23a0e1065926.png">

**Comment by tommoor** [comment]
Seems reasonable, I'm not sure the [] are even needed, just "Template from <original title>"
