### ISSUE TITLE
Add an obvious banner and explanation to drafts

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#3397]
It's really easy to forget that you're editing a draft. A similar treatment to Templates might be very helpful to make it super obvious that the document is in a draft state.

There's real value in making drafts more highly differentiated in the authorship process too — when a draft gets shared, it's part of the communication that this is not yet published.

Mockup
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/427579/163653434-326e252e-1300-4125-81ad-f8d90f851616.png">

**Comment by tommoor** [comment]
I think the banner is a bit much while drafts are the default for new documents, if that were to change then I'd be more open to it. We also have the `draft` badge which shows on list items, we could place it next to the title 🤔
