### ISSUE TITLE
collaborative mode has bug on persistence hook 

### ISSUE THREAD

**Issue by solirpa** [outline/outline#3400]
https://github.com/outline/outline/blob/1a8f2c3bb08df1ac3fa9cea5a2a7491757b7cf28/server/collaboration/persistence.ts#L54

This debounce is for nodes, not for documents，so B document debounce may overwrite A document onChange event.

**Comment by tommoor** [comment]
Great find, were you able to reproduce the bug or just scouting the code?

**Comment by tommoor** [comment]
I think the best way to address this would be to update Hocuspocus to the latest version which includes an `onStoreDocument` hook which is ready-debounced
