### ISSUE TITLE
Image alignment only formats right when centered.

### ISSUE THREAD

**Issue by jayb323** [outline/outline#3403]
I don't know if this is a bug or user issue, because it seems like a basic thing someone else would have picked up on if it was a bug.

If I insert an image, it centers by default and formats correctly. If I left-align the image (which is what I want to do), it messes the formatting.

No matter how much I try to space, page break or whatever, the image doesn't seem to be able to align anything but default (center) without messing up the formatting.

### Centered (default)

![image](https://user-images.githubusercontent.com/73043168/163696067-a716163a-9130-47c2-b78f-3146cc220dde.png)

### Left Aligned

![image](https://user-images.githubusercontent.com/73043168/163696042-0d861c08-0efa-4075-9e5d-f43ed1015ab2.png)

### Info

- Install: getoutline.com
- OS: Windows 11
- Browser: Chrome
- Version: 100.0.4896.127 (Official Build) (64-bit)

**Comment by florian-obradovic** [comment]
I have the same issue v0.73.1.

![CleanShot 2023-11-16 at 19 41 41@2x](https://github.com/outline/outline/assets/57985125/0712ed48-111d-458b-8856-b893f73174a7)

**Comment by florian-obradovic** [comment]
Please re-open. I still have this on 0.74.0

**Comment by threema-danilo** [comment]
It's probably best to upvote this feature request if you're affected by this: https://github.com/outline/outline/discussions/5112

**Comment by florian-obradovic** [comment]
Thanks @threema-danilo, I already did.

**Comment by florian-obradovic** [comment]
It got much better with #6350
Thanks a lot.

**Comment by florian-obradovic** [comment]
Picking this up again because it's still an issue for me:
https://github.com/outline/outline/discussions/11430
