### ISSUE TITLE
Team settings

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#341]
- Slack command
- Admin management
- Inviting new users via email

**Comment by tommoor** [comment]
Mocking out settings UI: https://share.goabstract.com/55dfa3c7-0396-4a2d-a7e0-795f96a09e47

(Ignore iconography)

I definitely want to move this out of the modal so it's easily routeable. I like this approach of having it take over the main navigation and will allow us to separate concerns nicely. I also like having integrations nested like this, not something you see a lot of but it maps well to collections / documents and scales nicely.

![image](https://user-images.githubusercontent.com/380914/32996820-e4b2d0ea-cd3c-11e7-9afb-1c1b659a8f67.png)

**Comment by tommoor** [comment]
@jorilallo thoughts?
