### ISSUE TITLE
Add user domain restriction to team settings

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3412]
Currently domain restriction is only possible for self hosted installations through the `ALLOWED_DOMAINS` env variable. We'd like to move this to a team level setting which will have some affects: 

- It can enable account creation via email without first receiving an invite.
- Restrict SSO access within a larger organization to a subset of the SSO group
- One less env var to configure, (we should use the env as the default during migration though)
- An extra layer of security

**Comment by coreyja** [comment]
Started working on this! Wanted to ask some questions to make sure I was on the right track!

1. This setting would only apply AFTER a Team was created, correct? When creating a new team we'd want to allow any domain to register, and let them restrict it after that via the setting. 

2. If number 1 is correct, how would you like this allowed domain restriction to work. From what I can tell from the code, each 'domain' that auths with Google or OIDC gets its own Team created for it: https://github.com/outline/outline/blob/main/server/routes/auth/providers/oidc.ts#L95-L100
If that is the case it might not make as much sense to check the allowed domains in those code paths.
I _have_ started to apply this to the self hosted code path where we attach new Auth Providers to the existing team that exists. Is this the primary use case for this feature?

3. There will be a migration here that you mention. Is that a migration that is done automatically through code? Or more like an Upgrade guide style? Happy to help with either just wasn't sure what you had in mind

**Comment by tommoor** [comment]
**- This setting would only apply AFTER a Team was created, correct?**

Yep, the experience should be that in Settings -> Security there is a new section where you can add domains to restrict signups to.

**- If number 1 is correct, how would you like this allowed domain restriction to work.**

The restriction itself should be part of accountProvisioner, we can check the email domain of the user being provisioned as the email is always trusted/verified at this point. This [recent similar PR](https://github.com/outline/outline/pull/3381) may provide some guidance in this respect. Anything in the accountProvisioner code path is applied to all versions of the product.

**- There will be a migration here that you mention. Is that a migration that is done automatically through code?**

Yes, in fact there is a branch where I already put that together which I'd encourage you to use: https://github.com/outline/outline/compare/tom/domain-restrictions?expand=1

**Comment by tommoor** [comment]
One detail – if the user has an explicit invite in the database and the invite was created by an admin then this should bypass the domain restriction.

**Comment by coreyja** [comment]
> Yes, in fact there is a branch where I already put that together which I'd encourage you to use:

Yes thank you! I have branched off that for the DB migration. 

I was trying to ask more about the migration from the environment variable to the DB table. Is that something you would like to provide a code/script for? Or something that you would like to mention in a Readme/Upgrade Guide?
Just thinking through what this will look like for self hosted users who upgrade!

Thanks for all your help and guidance here!

**Comment by tommoor** [comment]
> I was trying to ask more about the migration from the environment variable to the DB table.

Gotcha, typically we'd run a query within the migration itself. So once the new table is created try and see if there is a value in the env and write the associated rows.
