### ISSUE TITLE
Enable `documents.update` endpoint when collaborative editing is enabled

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3424]
Currently this is not enabled as it was previously not possible to update the CRDT reliably from the server. With the move to a fork of `y-prosemirror` we can use `updateYFragment` to do so, it's not simple though – the full flow would look something like:

- POST request to `/api/documents.update` with Markdown
- Request is forwarded to a collaboration server
- Collaboration server loads CRDT state or uses in-memory copy if it has one
- Markdown converted to Prosemirror JSON
- ProsemirrorJSON mapped onto CRDT with `updateYFragment`
- Persist state to db and remove from memory if no-one else is connected still

**Comment by max-mykhailenko** [comment]
Waiting this a lot, want to build automatization that should prepare daily meetings notes

**Comment by tommoor** [comment]
documents.create still works, add daily notes as child documents?

**Comment by max-mykhailenko** [comment]
Yea, thank you, thinking about this workaround as temporary solution, but after month we will have 30+ nested documents... or I'll need organise some docs rotation, but it is additional logic.
