### ISSUE TITLE
Improved horizontal scaling of collaborative servers

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3425]
I spent a lot of time working on the [scaling extension for Hocuspocus](https://github.com/ueberdosis/hocuspocus/tree/main/packages/extension-redis), it is time to implement it in the backend.

**Comment by almereyda** [comment]
A note for us other mortals in the public, watching here from outside: This link leads to a private repository, and intentionally reports to us: "This is not the web page you are looking for."

**Comment by tommoor** [comment]
Hopefully it will be public soon enough, unfortunately i am just a collaborator on that project.
