### ISSUE TITLE
Members are sent to a blank page when accessing Account -> Settings

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3432]
Because they do not have permission to view this screen it is blank. We should instead send to account details

**Comment by gemathus** [comment]
Hey @tommoor , I noticed that the settings page is still accesible to members if they navigate to their profile using the AccountMenu component (bottom left corner). Not sure if this is supposed to be possible.

**Comment by tommoor** [comment]
It's supposed to be possible to get to your profile, is that what you mean?

**Comment by gemathus** [comment]
I'm logged in as a Member, and I have access to API keys, Users, Groups and Share Links. I had understood that users were only meant to see their profile and no other settings. I guess I got it wrong. 

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/10574406/170809655-e084a2ff-e10b-498d-bf25-cb46d62d199c.png">
