### ISSUE TITLE
On Firefox, themes are not switching according to system settings

### ISSUE THREAD

**Issue by amauryhubault** [outline/outline#3435]
Hi guys,
First, thanks for the incredible work you're doing, love the product and the direction where it's heading. Just a small bug I noticed along the way

**To Reproduce**
1. Using Firefox, go to any outline doc
2. Click on Profile name>Display>Choose System
3. Change the setting on your computer between light and dark mode
4. Refresh the Firefox tab just in case

**Expected behavior**
The theme should match the computer settings, as Chrome does for example

**Screenshots**
I'm adding a screenshot of the same page with the same computer settings with Firefox in background, Chrome in foreground
![Screenshot 2022-04-22 at 12 05 46](https://user-images.githubusercontent.com/6259850/164685938-19d70466-f8da-4357-8498-9dc8a8c00d00.png)

**Outline (please complete the following information):**
- Install: [self hosted]
- Version: [0.63.0-1]

**Desktop (please complete the following information):**
 - OS: [macOS 12.3.1 (21E258)]
 - Browser [Firefox]
 - Version [100.0]

**Comment by tommoor** [comment]
I can't reproduce unfortunately. But your Firefox UI looks quite different to mine – is it a standard install? Mine is v99 and says it's up-to-date though.

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/380914/164788759-e3d0f6fc-9529-4949-ba8d-17966dc6d2c8.png">

**Comment by bmm-alc** [comment]
On Linux (GNOME 41) with Firefox 99.0.1 I confirm it works fine.

**Comment by amauryhubault** [comment]
I checked again, now it works. Don't understand why it didn't work at first 🤷🏻‍♂️
