### ISSUE TITLE
Fail to change user email with a different domain

### ISSUE THREAD

**Issue by wohenbushuang** [outline/outline#3438]
Fail to change user email with a different domain

**To Reproduce**
Use SSO authentication. The user was originally registered with original email `a@a.com`.
1. According to the tip on the user notification page, email changes should be done in SSO.
2. Change the email address to `b@b.com`, a different domain, in SSO.
3. Fail to login with auth error.
4. Backend log:
```json
{"error":"User authentication AAAAAAAA-4311-43ce-99ed-85fb9c41fb22 already exists for BBBBBBBB-a2a8-4522-835f-e20c095db2f4, tried to assign to CCCCCCCC-d097-4232-b2fa-59eba9ad2aff",
"stack":"Error: User authentication AAAAAAAA-4311-43ce-99ed-85fb9c41fb22 already exists for BBBBBBBB-a2a8-4522-835f-e20c095db2f4, tried to assign to CCCCCCCC-d097-4232-b2fa-59eba9ad2aff
    at userCreator (/opt/outline/build/server/commands/userCreator.js:47:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:59:20)
    at async OAuth2Strategy._verify (/opt/outline/build/server/routes/auth/providers/oidc.js:93:22)",
"level":"error",
"message":"Error during authentication"}
```
where `AAAAAAAA-*` is the outline user ID, `BBBBBBBB-*` is the original ID in database table `authentication_providers`, and `CCCCCCCC-*` is a newly created.
5. The login problem get solved after manually update database table `user_authentications`.

**Expected behavior**
For the same OAuth provider and user ID, the login should treat them as a same user, and the user email can be updated.

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.63.0

**Comment by tommoor** [comment]
Addressed in the next release, v0.66.0
