### ISSUE TITLE
File attachment not deleted after remove it from the document

### ISSUE THREAD

**Issue by liccowee** [outline/outline#3449]
**To Reproduce**
1. Open or create any new document
2. Upload any file attachment and save
3. Edit the same document and remove the file attachment
4. File is removed from document but still persist on the file storage

**Expected behavior**
File should be get delete as well after the file is remove from the document

**Outline (please complete the following information):**
- Install: [self hosted]
- Version: v.0.63.0

**Comment by tommoor** [comment]
This is by design as attachments and images remain available in previous revisions of the document.


We could definitely entertain some cleanup if the file is added AND removed before a revision is written.

**Comment by 1itt1eB0y** [comment]
I noticed this problem too. And it will be deleted when you totally remove a page from outline.
BUT, the team LOGO and user picture won't be deleted when you use a new one to change the old one.
