### ISSUE TITLE
Clicking on a "recent search" term does not add the text to the search input

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3457]
This is due to the input not being controlled – it only updates on mount and when the user types.

**To Reproduce**
1. Go to "Search" in left sidebar
2. Click on a recent search term (you have to have at least one)
3. The url updates, the results update, but the search bar remains empty

**Expected behavior**

- The search term is also added to the search input

**Comment by IsaacNoga** [comment]
Hi :D
I will like to try to solve this issue, hope it's still in need.

**Comment by PabloYG** [comment]
Hey @CuriousCorrelation @IsaacNoga I'd like to contribute to this repo. Is this still a good first issue or are you already on it?

**Comment by tommoor** [comment]
It's currently open, the functional refactor unfortunately failed due to a number of bugs that weren't easy to work out.

**Comment by PabloYG** [comment]
I am not able to reproduce the issue. The input field displays the search term correctly after clicking on it. I am running on development mode though, if that changes anything.

**Comment by bmm-alc** [comment]
I can't reproduce it either, I'm using Firefox 103 on Linux

**Comment by elidrissidev** [comment]
Can't reproduce using Chrome 108 on macOS.

**Comment by tommoor** [comment]
Closed as unreproducible
