### ISSUE TITLE
Move `sortNavigationNodes` out of presenter

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3466]
Currently `sortNavigationNodes` is ran in the collection presenter every time the collection is rendered, for larger collections this is actually quite the performance drag – that thing is deburring, running multiple regex for natural sort and emoji stripping. Ideally we'd run on write – _but_ that's the way that manual sorting is stored.

I think this could be a reasonable change to make, we'll gain performance on every read at the cost of losing the previous manual sort order when changing to alphabetical sort on a collection. cc @thenanyu 

For context, the lime green on these request spans is the time spent in the presenter in these particularly slow examples:

<img width="635" alt="image" src="https://user-images.githubusercontent.com/380914/165788399-7e1034d0-b656-47d9-83e6-785c3823544f.png">

**Comment by tommoor** [comment]
Additionally, because much of the slowness here is caused by running regex these long requests _do_ actually block other requests

**Comment by thenanyu** [comment]
Is the suggestion to store the alphabetical sort order on rename, move, and insert of documents? If so, can we just add another column that stores the A-Z order in addition to the manual column?

**Comment by tommoor** [comment]
The suggestion is to store the same order the user sees, yea. Having two structures in the db feels bad though
