### ISSUE TITLE
Reduce email notifications when a document is modified multiple times

### ISSUE THREAD

**Issue by bmm-alc** [outline/outline#3467]
Someone has modified a page I modified previously, so I received a mail notification.
Another person modified the same page again few minutes later and I've got a second notification.

The second notification is useless (imho) because I did not visit or modified the page since I've received the first notification.

**To Reproduce**
1. Someone modify a page I previously modified
2. I receive a notification mail
3. Another person edits the same page
4. step 2. happen again

**Expected behavior**
Just being notified once.

**Screenshots**
null

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 0.63.0

**Desktop (please complete the following information):**
 - OS: N/a
 - Browser [e.g. chrome, safari]: N/a
 - Version [e.g. 22]: N/a

**Mobile (please complete the following information):**
 - Device: [e.g. iPhone6] N/a
 - OS: [e.g. iOS8.1] N/a
 - Browser [e.g. stock browser, safari] N/a

**Comment by Limezy** [comment]
When a diff view of the changes will be provided in the email, we may want to receive both ?

**Comment by bmm-alc** [comment]
> When a diff view of the changes will be provided in the email, we may want to receive both ?

indeed, that may be more valuable; or perhaps, avoid send repetitive emails, and send only one mail with a link that would generate a diff on the application since the last visit ? I genuinely don't know what is the best.

**Comment by tommoor** [comment]
One on the first edit and then no more until the end of the day might be a nice middle ground. In order to achieve this we'd need to start storing in the database when an email notification is sent for a user+document combo.

**Comment by tommoor** [comment]
A first version of a notification model would probably look like the following – this will form the basis of in-app notifications in the future too.

### Notification

- `id`
- `type` – A string mapping to the type of notification
- `teamId` – Team relationship
- `actorId` – User relationship to actor, _nullable_
- `userId` – User relationship to user notif is sent to
- `documentId` – Document relationship to associated doc, _nullable_
- `viewedAt` - Date time, _nullable_
- `emailedAt` - Date time, _nullable_

**Comment by tommoor** [comment]
I would build this ontop of the https://github.com/outline/outline/pull/3834 which is almost ready to merge, just some data backfilling to figure out.

**Comment by tommoor** [comment]
https://github.com/outline/outline/pull/3834 is merged, I noticed that there is already a `notifications` table but it's totally unused. Might be easiest to just drop it to create the above schema

**Comment by apoorv-mishra** [comment]
I see that currently `notification_settings` is used for _notifications_.
