### ISSUE TITLE
Page break element breaks page 'Print' (Firefox)

### ISSUE THREAD

**Issue by HumbleCow** [outline/outline#3494]
**To Reproduce**
1. Go to your document and add a 'Page Break' element, then another 'Page Break' element.
2. Then, try to print the page.
3. You will see that everything on page one works as expected, but then everything after the page break gets squashed to a single character per line - spreading the document out over dozens of pages.
<img width="1373" alt="Screenshot 2022-05-04 at 10 26 09" src="https://user-images.githubusercontent.com/88387302/166655440-6a1f3407-ad4b-4089-9085-50f0c03d75f0.png">
<img width="1373" alt="Screenshot 2022-05-04 at 10 26 13" src="https://user-images.githubusercontent.com/88387302/166655452-9ea80a21-c87c-41c3-bfd6-e5bdd0bc6886.png">

**Expected behavior**
I expected the page to print normally, and then everything after the page break to print on a new page.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: https://theturmericco.getoutline.com/home
- Version:  v0.63.0 Latest

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Firefox
 - Version: 100

**Mobile (please complete the following information):**

**Comment by tommoor** [comment]
Unfortunately Firefox's handling of page breaks differs from all the other browsers, I haven't found a way for it to behave reliably 😠

**Comment by matbgn** [comment]
Is there a possible fix that emerged in the meantime?

**Comment by tommoor** [comment]
Not really, many hours were spent investigating this – it seems like a bug in the Firefox browser

**Comment by matbgn** [comment]
Still need to ne fixed
