### ISSUE TITLE
Locales in i18n directory missing 

### ISSUE THREAD

**Issue by wojiaozhangyang** [outline/outline#3499]
**To Reproduce**
In the new outline version, run the "make up" command and the locales directory is missing in the build directory  

**Expected behavior**

**Screenshots**
DIR: outline/build/shared/i18n
![image](https://user-images.githubusercontent.com/26091105/167079158-239c3e61-cfa4-464b-b111-a9c36138994d.png)
DIR: outline/shared/i18n
![image](https://user-images.githubusercontent.com/26091105/167079054-7a152b33-85dd-478a-835a-e1207ed05eeb.png)

**Outline (please complete the following information):**
- Install:  self hosted
- Version: eeb8008927e81330299652a4addec6be2ca4b2bb

**Desktop (please complete the following information):**
 - OS:  ubuntu 20.04
 - Browser  chrome
 - Version     commit    eeb8008927e81330299652a4addec6be2ca4b2bb

**Comment by tommoor** [comment]
This is expected behavior, `make up` runs a development server and no longer compiles translations. `yarn build:server` compiles the server code for production.
