### ISSUE TITLE
Unable to download embedded images from published documents

### ISSUE THREAD

**Issue by yuhanvogt** [outline/outline#3515]
Embedded images in public documents cannot be downloaded by clicking on the "download" button by guests. Option/alt-click to save as works per usual, but since the button is visible guests may also expect it to work like any other file attachments.

**To Reproduce**
1. Embed an image in a document
2. Publish to internet
3. View published page as a guest (not logged in)
4. Download button appears on embedded images but clicking doesn't yield a response

**Expected behavior**
- Same as when downloaded file attachments in publish documents as a guest

**Outline**
- Install: [getoutline.com]

**Desktop**
 - OS: [Mac OS]
 - Browser [safari]
 - Version [15.4]

**Mobile**
 - Device: [OnePlus 6]
 - OS: [Android 11]
 - Browser [Chrome]

**Comment by tanvirraj** [comment]
@tommoor , i investigated the issue, but as i don't have s3 bucket account, i can't upload the image. but after my investigation i think the solution around will be this code  this code 
`pointer-events: ${(props) => (props.readOnly ? "initial" : "none")};` 
in this file `outline/app/editor/components/Styles.ts` 

https://github.com/outline/outline/blob/main/app/editor/components/Styles.ts#L139
