### ISSUE TITLE
How to Disable Collaborative Editing Feature?

### ISSUE THREAD

**Issue by pranaykotas** [outline/outline#3519]
Hi, I checked this issue and I want to turn the collaborative editing feature off in order to test if the "server connection lost" error goes away. But I'm unable to turn this feature off. What am I doing wrong?

### Discussed in https://github.com/outline/outline/discussions/3316

<div type='discussions-op-text'>

<sup>Originally posted by **dveretennikov1** March 31, 2022</sup>
I've got very strange error, when I'm trying to edit any doc 
![Screenshot 2022-03-31 195557](https://user-images.githubusercontent.com/102303381/161109400-96b81d5b-7ed8-45b4-b108-822a0f03f5dc.png)
I have no idea what that meaning

Logs
{"level":"warn","message":"Enforced https was disabled with FORCE_HTTPS env variable"}
{"label":"lifecycle","level":"info","message":"Listening on http://localhost:3000"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"backlinks processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"debouncer processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"imports processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"exports processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"notifications processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"revisions processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"slack processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"backlinks processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"debouncer processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"imports processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"exports processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"notifications processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"revisions processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"slack processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"backlinks processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"debouncer processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"imports processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"exports processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"notifications processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"revisions processing views.create"}
{"name":"views.create","modelId":null,"label":"processor","level":"info","message":"slack processing views.create"}

</div>

**Comment by tommoor** [comment]
Please search for issues before creating new ones :)

https://github.com/outline/outline/issues?q=is%3Aissue+Disable+Collaborative+Editing
