### ISSUE TITLE
/settings/details has display problem.

### ISSUE THREAD

**Issue by 1itt1eB0y** [outline/outline#3531]
**To Reproduce**
1. Login as a `NoAdmin`.
2. Go to `http://host/settings/details`.
3. It is just a blank page, when the display width smaller than `737` pixels.

**Expected behavior**
There should be a button or jump to other page to make it work properly.
It looks like CSS and permission control should be the cause of the problem.

**Screenshots**
`It says '管理员' in the pictuer but this user is NOT an Admin role in db`
![图片](https://user-images.githubusercontent.com/29831189/168437973-83e38cb9-6d00-4db8-9795-28ef8ca45267.png)
![图片](https://user-images.githubusercontent.com/29831189/168438248-32e3684b-c061-44c9-9435-b4d62db9af12.png)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.63.0 Docker

**Desktop (please complete the following information):**
 - OS: Android and Windows
 - Browser: Firefox`v100.0 x64`, Edge`101.0.1210.39 x64`

**Mobile (please complete the following information):**
 - Device: Samsung S22Ultra
 - OS: OneUI 4.1
 - Browser: Firefox and Edge

**Comment by tommoor** [comment]
The underlying issue was that there was a link to this page from the settings menu that shouldn't have existed for non-admins, this is no longer the case on `main`.

It would be nice if it showed a not-found screen in this case too.
