### ISSUE TITLE
Images in tables are too big

### ISSUE THREAD

**Issue by alix2018** [outline/outline#3537]
After a recent release, images in the tables are really big. There is no way to resize them and the table becomes unreadable.

**To Reproduce**
1. Create a table
2. Paste an image in one of the block

**Expected behavior**
The images in a table should have a maximum size or we should be able to resize them

**Screenshots**
<img width="734" alt="Screenshot 2022-05-13 at 18 58 34" src="https://user-images.githubusercontent.com/23335579/168334187-d74c7000-8122-4c15-9ad4-a61411046665.png">

**Desktop**
 - OS: MacOS
 - Browser: Chrome
 - Version: 100.0.4896.127 (Official Build) (arm64)

**Comment by tommoor** [comment]
Which version of Outline are you using? Is this an SVG graphic?

Yes, image resizing is very needed – in the meantime you could insert a smaller image…

**Comment by alix2018** [comment]
We use the last version [v0.63.0](https://github.com/outline/outline/releases/tag/v0.63.0). We can indeed manually upload new resized images but it changed from one release to another and now all our tables with images looks like the screenshot above. That's why I created this bug.

The images are usually PNGs.

**Comment by mikew** [comment]
Since there's no width set on the table cells, `max-width: 100%` on the image won't do anything. Maybe something like ``<td width={`${1 / numberOfColumnsInTable * 100}%`}>`` would help?
