### ISSUE TITLE
Links with anchors are broken when pages are renamed

### ISSUE THREAD

**Issue by daladim** [outline/outline#3553]
Not sure whether that's a bug or a feature request

## The bug part

If that matters, I am using a self-hosted Outline instance at version 0.63.0-1 (and I am using Firefox on Linux)

1. Create a link (by manually pasting a URL) to `https://wiki.example.net/doc/other-page-X0GtFXBaqJ#anchor` note the `#anchor` at the end
2. This link correctly jumps to the `anchor` of the other page when clicked
3. Rename the `Other page` to `Renamed page`
4. As expected, the link is automatically translated to `https://wiki.example.net/doc/renamed-page-X0GtFXBaqJ`. **But the `#anchor` part is lost** :-(

## The feature request part

It looks you already did a good job supporting anchored-links (cf https://github.com/outline/outline/issues/739#issuecomment-410547781).
But this could be made even better by supporting them as first-class links by:
* fixing the bug above
* having a way in the UI to create such links. Currently, creating a link (ctrl-K) prompts for a link, and autocompletes page names in the current wiki (which is great). But it may also provide the ability to point to a specific anchor when it detects it points at the current wiki.
* such links to a sub-section should be automatically "fixed" when the sub-section is renamed, the same way links to pages are "fixed" when the page is renamed

Tell me if you want me to split this issue and create a separate feature request

I'm sorry for not being a webdev, and I'm afraid I won't be able to fix this myself

Thanks!

**Comment by daladim** [comment]
Maybe my link to #739 does not make sense. Here, I'm having trouble with links to a sub-paragraph of _another_ page, not the current one

**Comment by Limezy** [comment]
Indeed, I agree both with the bug and feature request part ! I use links to header a lot and it's painful to create by hand (+ repair when it's broken)

**Comment by tommoor** [comment]
The bug is fixed, I think the feature request should be filed separately 😄

**Comment by daladim** [comment]
Thanks a lot. See https://github.com/outline/outline/discussions/3562 for the feature request

**Comment by Limezy** [comment]
Great, thanks @tommoor
