### ISSUE TITLE
Bug with collapsed headers on full width

### ISSUE THREAD

**Issue by napest** [outline/outline#3558]
### Discussed in https://github.com/outline/outline/discussions/3557

<div type='discussions-op-text'>

<sup>Originally posted by **napest** May 19, 2022</sup>
Hi!

If I select Full width option collapsed headers no longer expand. I'm using Chrome 100.0.4896.127 on macos and 0.63.0 version, but I see the same behavior in cloud version as well

https://user-images.githubusercontent.com/18447985/169378453-616b6267-a27e-4ca9-ae94-70c4dc22fe30.mov

</div>

**Comment by tommoor** [comment]
This is still an issue sometimes 😢
