### ISSUE TITLE
Slack integration pointing to wrong Outline instance/url

### ISSUE THREAD

**Issue by jonatcb** [outline/outline#3560]
When I turn on the Slack integration, and try to use the /outline command in Slack, Slack looks at abett1.outline.com instead of abett.outline.com (where our wiki actually lives). I don't understand where abett1 is coming from and what Slack would point to it.

**To Reproduce**
1. Go to https://abett.getoutline.com/settings/integrations/slack
2. Click on Add to Slack
3. Go to Slack
4. Try to search for content using /outline command
5. Mostly, returns no results (because it's pointing at a mostly empty wiki)
6. If I do search for something that exists within the default Outline pages (i.e. the tutorial pages), and click on the link to those results from within Slack, I am taken to abett1.outline.com -- but our wiki is hosted on abett.outline.com

**Expected behavior**
Should point to / search abett.outline.com

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

<img width="599" alt="Screen Shot 2022-05-19 at 3 54 19 PM" src="https://user-images.githubusercontent.com/98782569/169417376-a45631ef-5031-4d23-8afa-b5a21c20e650.png">

<img width="1083" alt="Screen Shot 2022-05-19 at 3 54 30 PM" src="https://user-images.githubusercontent.com/98782569/169417383-8367f489-66cf-47e4-900d-4c54f75bfe03.png">

**Outline (please complete the following information):**
- Install: getoutline.com
- Version: 

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser firefox
 - Version 100.0.1

Thanks!!

**Comment by tommoor** [comment]
Hey, please contact hello@getoutline.com – this is not a bug, you've just created two workspaces by accident. Support can merge them or disable the extra one.
