### ISSUE TITLE
Env variables error with v0.64.1 update

### ISSUE THREAD

**Issue by Limezy** [outline/outline#3578]
Hi, I have tried to update to v0.64.1 and got the below errors
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! outline@0.64.1 start: `node ./build/server/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the outline@0.64.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/outline/.npm/_logs/2022-05-23T19_01_52_560Z-debug.log

> outline@0.64.1 start /var/www/outline
> node ./build/server/index.js

{"level":"warn","message":"Environment configuration is invalid, please check the following:\n\n"}
{"level":"warn","message":"- CDN_URL must be an URL address"}
{"level":"warn","message":"- COLLABORATION_URL must be an URL address"}
{"level":"warn","message":"- SENTRY_DSN must be an URL address"}
{"level":"warn","message":"- GOOGLE_ANALYTICS_ID must contain a UA- string"}
```

**Comment by rtsp** [comment]
I faced the same problem. Workaround by comment out all blank variables from .env file.

**Comment by tommoor** [comment]
Please see the notes on the release – https://github.com/outline/outline/releases/tag/v0.64.0 – we're now validating environment variables that are passed to the server, this is considered a breaking change but not a bug.

**Comment by rtsp** [comment]
@tommoor Thanks for clarification!

I've check [this commit](https://github.com/outline/outline/commit/3c002f82ccb552e135021b983ba4c12680e27721#diff-088d9f35d23a4347d221d71dd49b02b95001dff4abe637a40fe0bc04d502049cL69) it seems that Slack's variables also renamed too but doesn't cause any error log. May be noting this changes on the release note too?

**Comment by tommoor** [comment]
> Slack's variables also renamed too but doesn't cause any error log

The old ones are still supported for now 👍
