### ISSUE TITLE
0.64.2 fails to start in docker network with OIDC URL env variables error

### ISSUE THREAD

**Issue by wohenbushuang** [outline/outline#3582]
I put outline and OIDC provider in a same docker network.
The OIDC provider can be reached using the server name, that its internal IP will be automatically resolved by docker network.
Things work fine for outline 0.63 and earlier.
When I tried to upgrade to latest 0.64.2, outline fails to start.

Log:
```json
$ node ./build/server/index.js
{"level":"warn","message":"Environment configuration is invalid, please check the following:\n\n"}
{"level":"warn","message":"- OIDC_TOKEN_URI must be an URL address"}
{"level":"warn","message":"- OIDC_USERINFO_URI must be an URL address"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My env settings:
```
OIDC_TOKEN_URI=http://OIDC_OIDC_1:[PORT]/api/login/oauth/access_token
OIDC_USERINFO_URI=http://OIDC_OIDC_1:[PORT]/api/userinfo
```

I believe that this error might result from the missing options when performing url validation

https://github.com/outline/outline/blob/62bb13047a90fe5c6e473ef8fe753f7e51ed5476/server/env.ts#L447-L468

**Comment by wohenbushuang** [comment]
oh it seems similar to #3574 for OIDC URL

**Comment by tommoor** [comment]
Sigh. I expected _some_ configurations would throw errors but it's certainly been more than expected. Can't promise a patch release for this one, you might want to wait on 0.63 until the next minor.
