### ISSUE TITLE
Cannot read properties of null (reading 'replace')

### ISSUE THREAD

**Issue by mahoob3** [outline/outline#3586]
Hello, I'm trying to install a fresh version of the project but when I try to do `yarn start` it gives me this error

![image](https://user-images.githubusercontent.com/106234588/170221216-bafd248f-f574-4ff7-a5ff-af5a470a613d.png)

Note: I did the DB migrations and installed all the required services

--
- Outline: 0.64.2
- Node 16.15.0
 - OS: ubunntu 20.04

**Comment by tommoor** [comment]
What does your `DATABASE_URL` look like?

**Comment by mahoob3** [comment]
@tommoor my
`DATABASE_URL=postgres://postgres:PASS@IP_ADDR:5433/outline`
Note: I already changed my postgresql port to 5433

**Comment by mahoob3** [comment]
sorry, the issue was with my local postgresql server

**Comment by tommoor** [comment]
Are there any clues you can leave for the next person?

**Comment by cejuo** [comment]
> 

Same issue here. How did you solve it?

**Comment by cejuo** [comment]
> @tommoor `DATABASE_URL=postgres://postgres:PASS@IP_ADDR:5433/outline` Note: I already changed my postgresql port to 5433

Same issue here. How did you solve it?

**Comment by cejuo** [comment]
> sorry, the issue was with my local postgresql server

Same issue here. How did you solve it?

**Comment by razerbeans** [comment]
In my case, the environment file wasn't loading correctly. Once I added it to my docker-compose.yaml, everything went fine for me. Hope this helps someone!
