### ISSUE TITLE
Can't scroll through headings on mobile web

### ISSUE THREAD

**Issue by jenningsb2** [outline/outline#3588]
Platform: iOS
Browser: Safari

I am unable to swipe through the headings list on mobile on a public url.

I have a number of headings that are below the fold, but unaccessible.

![image](https://user-images.githubusercontent.com/29644050/170376900-b265012c-95c1-4ead-8142-8e64e5ff7815.png)

**Comment by tommoor** [comment]
Looks like this is a bug in the underlying library that was recently addressed:
https://github.com/ariakit/ariakit/pull/1271
