### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by zuozhe527** [outline/outline#3592]
The "outline manager" software has a very serious glitch, at least I think it is a serious glitch. After I changed my digitalocean account and started using a new username and password, I had no way to update the digitalocean information in the "outline manager" software, whenever I clicked the "create server" button, the system would tell me:" Not authenticated by DigitalOcean", I couldn't find any way to circumvent this problem; I tried: 1, clean system folders; 2, uninstall software and reinstall; 3, shut down my windows computer and restart; 4, clean My chrome browser cookie and my digitalocean information is deleted from the browser; 5. Migrate the installation directory of the "outline manager" software and replace it with a new installation folder. But none of these actions have any effect, it still tells me: "Not authenticated by DigitalOcean"; this is very frustrating, I've spent two days on this problem, but I still can't find any solution, So I want to ask for your help, thank you for making such good software for us Chinese, thank you from the bottom of my heart

**Comment by zuozhe527** [comment]
https://www.dropbox.com/s/hxgwsov1olow3jn/Outline%20Manger%20question.jpg?dl=0

**Comment by tommoor** [comment]
Wrong project, this is a different Outline.
