### ISSUE TITLE
Multiple environment validation issues

### ISSUE THREAD

**Issue by heilerich** [outline/outline#3593]
**To Reproduce**
Set the following environment variables 
1. `DATABASE_URL` to a string starting with `postgresql://something`
2. `REDIS_URL` to `ioredis://<base64-encoded-json>`

**Expected behavior**
Both are perfectly fine values and should pass validation.

**Additional insights**
The first value fails because the only allowed schema here https://github.com/outline/outline/blob/2a6d6f58042b477b0c175a95b554066fced6a572/server/env.ts#L66

is `postgres`, but I think `postgresql` is at least as common and should be okay to. In our case, it is also not trivial to change the environment variable because it is injected by the cloud's database operator and it uses the `postgresql` scheme.

The second error is more complex. In this case the `isURL` function of `validator.js` is not applicable at all because of the new `ioredis` schema. We do not use URL safe base64, because it is not in the standard library and it is also not really necessary. Also it seems like the isURL function has some kind of length cap on the host part.

**Proposed fixes***

1. Just add the additional scheme.

2. I think the only real viable fix that does not require changing the Redis client code again is to use a [custom validation decorator](https://github.com/typestack/class-validator#custom-validation-decorators)

Does that sound reasonable?

**Comment by tommoor** [comment]
Yes, totally reasonable!
