### ISSUE TITLE
[editor] can't get cursor after an emoji on firefox

### ISSUE THREAD

**Issue by bmm-alc** [outline/outline#3603]
I get a bug with Firefox when I add an emoji, the cursor does not appear or get positioned after it

**To Reproduce**
1. create or edit a document
2. create a line, insert some test then insert an emoji (I use `:cat` for instance) 
3. your cursor reappear after the emoji and even if you click after it on the line to position it, it never appears. 

If I put an emoji betweem 2 existing words, I don't have this issue.
I've tested with Epiphany which is webkit based and it works fine.

**Expected behavior**
the cursor to appear

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: self hosted
- Version: `0.64.2`

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 100

**Comment by tommoor** [comment]
Hi, please provide a video/loom of this one – it could be interpreted in several ways.
