### ISSUE TITLE
Delete User via API not possible

### ISSUE THREAD

**Issue by blaugrau90** [outline/outline#3604]
**To Reproduce**
API Request List Users:
https://outline.domain.xyz/api/users.list
--> works

API Request Deleting User by ID
https://outline.domain.xyz/api/users.delete?id=c0f749ae-81a4-4f4c-a6bf-5363b931ee80
--> does not work

{
    "ok": false,
    "error": "param_required",
    "status": 400,
    "message": "confirmation is required"
}

**Expected behavior**
User deletion should work as in the API documentation

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.64.3
https://github.com/outline/outline/commit/8a29a3523aecc778c31f27a28cf47cb1cda200ec

**Comment by tommoor** [comment]
This endpoint requires `confirmation=true`, I can't remember why – we can probably remove this.

**Comment by blaugrau90** [comment]
I just tried to delete the user with the "confirmation" parameter. now the output tells me that an administrator is needed for this? I am administrator.

{
    "ok": false,
    "error": "admin_required",
    "status": 403,
    "message": "An admin role is required to access this resource"
}
