### ISSUE TITLE
write DEFAULT_AVATAR_HOST in .env but  it didn't work

### ISSUE THREAD

**Issue by dislazy** [outline/outline#3610]
I couldn't access https://tiley.herokuapp.com, so I wrote DEFAULT_AVATAR_HOST to .env and found that it didn't work

**Comment by tommoor** [comment]
What didn't work? Please provide more details

**Comment by dislazy** [comment]
A clear and concise description of what the bug is.

Then I deployed a set of my own tiley, read the source code of the outline, and found that I could configure DEFAULT_AVATAR_HOST to modify the original https://tiley.herokuapp.com domain name to my own domain name: https://abc.abc.com

**To Reproduce**
Steps to reproduce the behavior:
1. cp env.example  .env
2. set DEFAULT_AVATAR_HOST= https://abc.abc.com  in .env
3. docker-compose stop &&  docker-compose up -d
4. But the url address of the final generated avatar still hasn't changed, it's still https://tiley.herokuapp.com

**Expected behavior**

https://tiley.herokuapp.com/avatar/e4fb6f131f43645ccf3e32f2fd73d2f1/A.png?c=2BC2FF

**Screenshots**

GET https://tiley.herokuapp.com/avatar/e4fb6f131f43645ccf3e32f2fd73d2f1/A.png?c=2BC2FF net::ERR_TIMED_OUT

I want to replace https://tiley.herokuapp.com/ with something like https://abc.abc.com

**Outline (please complete the following information):**
- Install: self hosted
- Version: [v0.64.3](https://github.com/outline/outline/releases/tag/v0.64.3)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version [100]

**Comment by tommoor** [comment]
Avatars are stored in the database so any existing user records won't be updated, you'll need to edit the database either manually or with a script to update the existing URLs. This is expected behavior.

If you find that the new url is not applied to _new_ signups that happen since the configuration was updated please re-open the ticket.
