### ISSUE TITLE
SLACK login is not appear in login page 

### ISSUE THREAD

**Issue by rockman88v** [outline/outline#3621]
I've created Slack apps and configure the redirect URL.
In the docker.env file, I set value of both SLACK and GOOGLE for sigin option.
But only google signin appear. How can I user slack for signin option?

I attached my docker-compose file and docker.env file here
Thanks 
![docker env](https://user-images.githubusercontent.com/63487262/171700019-6f93105b-7e5a-424e-aaf7-9220c8c3dbc3.png)
![docker-compose](https://user-images.githubusercontent.com/63487262/171700028-cde4f957-36f5-4743-8332-fe7ed8dff839.png)

**Comment by rockman88v** [comment]
This is login page
![login](https://user-images.githubusercontent.com/63487262/171700413-02a3aa32-20e0-4a13-b33e-0cca1ac90bf3.PNG)

**Comment by tommoor** [comment]
Hi, this is known limitation – it is currently slated to be removed in the next release, 0.65 with this pr:
https://github.com/outline/outline/pull/2986

Closing as a duplicate for now as we already have a couple of issues tracking this
