### ISSUE TITLE
Issue with markdown lists and codeblock

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#363]
Following markdown breaks the editor:

<img width="374" alt="screen shot 2017-10-23 at 7 55 17 pm" src="https://user-images.githubusercontent.com/31465/31922830-24076358-b82c-11e7-9884-32f6aacbee77.png">

**Comment by tommoor** [comment]
Need to test this in the `update-slate` branch, it might be fixed with the new normalization rules.

**Comment by tommoor** [comment]
Confirmed this is no longer an issue.
