### ISSUE TITLE
Import from Notion - zip file mimetype and filesize issue

### ISSUE THREAD

**Issue by ZorgeR** [outline/outline#3632]
**To Reproduce**
1. Go to 'https://outline.tld/settings/import'
2. Click on 'Notion Import'
3. Drag and drop Notion exported ZIP file.
4. Outline show error "File not supported. Select accepatable file."

**Expected behavior**
File import success.

**Outline**
- Install: self hosted
- Version: v0.64.3

After some research found that page has variable "MAXIMUM_IMPORT_SIZE" and it set to 5120000 (5MB)

But my export from Notion is 168 MB.

I think Outline need to say "File to large. Maximum file size for import is 5MB." Becase "File not supported. Select accepatable file." does not give me any understanding of what is wrong and who is to blame. Maybe it's translation issue. I use Russian translation.

**Comment by ZorgeR** [comment]
change MAXIMUM_IMPORT_SIZE to 512000000 not helping. need research.
When file droped in upload area no data transfer or any network activity from page. It immediately say "File not supported. Select accepatable file."

**Comment by tommoor** [comment]
This would mean that it's not recognized as an `application/zip` mimetype file by your browser.

**Comment by ZorgeR** [comment]
I try to unpack and zip it again. No help. Try different browser, no help.
Windows 11, latest chrome, vivaldi, edge.

**Comment by ZorgeR** [comment]
Checked archive to correct header in hex
![image](https://user-images.githubusercontent.com/925105/172024750-ef64b91e-121d-4b4c-8534-d435f8e6118a.png)

Try to repack it with 7zip. Same issue. Not worked.

**Comment by ZorgeR** [comment]
I go to debugger, Chrome recognize this file as application/x-zip-compressed
![image](https://user-images.githubusercontent.com/925105/172025275-48eb977b-5c7d-4f91-a950-12a081416781.png)

**Comment by tommoor** [comment]
Good debugging – In the meantime you can remove the requirement on the frontend <input> and it should let you upload.

**Comment by ZorgeR** [comment]
I make local workspace in chrome and override **DropToImport.tsx** script and **authenticated-routes.*.js**, than clear cache.


![image](https://user-images.githubusercontent.com/925105/172026256-78e693c3-826b-4030-95b2-cd7bff5f34a9.png)
override to  application/x-zip-compressed

Now it handle file, but size limited to 21 MB


![image](https://user-images.githubusercontent.com/925105/172026215-30741868-c6b9-407d-87a8-044bcfecdbe7.png)

Where is file limit stored?

**Comment by tommoor** [comment]
`AWS_S3_UPLOAD_MAX_SIZE` – definitely some kinks that need ironing out here…

**Comment by ZorgeR** [comment]
And now finally uploaded under chrome. File parsing issue there, but i think it's not in current issue thread discussing.
![image](https://user-images.githubusercontent.com/925105/172026744-a54c5266-6a44-4386-8271-f1a30d88a8a1.png)

**Comment by tommoor** [comment]
We can continue debugging here. It might be easiest if you're able to send your zip file to support email.

**Comment by tommoor** [comment]
I still can't understand why your operating system is returning the mimetype as `x-zip-compressed`, we can add it to the list but it's weird. The `x-` means non-standard and obviously zip files have been standardised for decades.

**Comment by ZorgeR** [comment]
Can't share zip file directly, because of sensetive data, but if repack any different data to zip has some issue. Think it is can be environment based issue.

More detail about environment:
OS - Windows 11 Enterprise 21H2 build 22000.675
Chrome - 102.0.5005.63

Thanks for fix commit!

**Comment by tommoor** [comment]
> Think it is can be environment based issue.

Most likely, we've had no complaints on the cloud-hosted version. Without some reproduction data we won't really be able to debug this further though.

**Comment by cwirz** [comment]
Seems its fixed on the latest version 0.66.0

**Comment by mmuenker** [comment]
@cwirz I can confirm this. In version 0.65.2 the import was broken, but after an update to 0.66.0 this works.

The error message `Can't read the data of 'the loaded zip file'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?` is not present anymore.
