### ISSUE TITLE
Cannot restore a first version of a document when it was imported in markdown.

### ISSUE THREAD

**Issue by bmm-alc** [outline/outline#3656]
All the documents that were created by an import of markdown cannot be restored in this version 

**To Reproduce**
1. Do a drag-n-drop of a markdown file to outline and check it is imported.
2. Select all text and delete it from the document.
3. Go on the history, and verify you have two 2 revisions
4. You cannot select the first version, so you cannot restore the first version

**Expected behavior**
Be able to restore the version of the file the moment it was imported.
When the markdown files were imported, the installation was running the version 0.61
The instance running has collaborative editing activated.

**Screenshots**
I cannot select the first revision
![outline_history](https://user-images.githubusercontent.com/80455946/173389765-e567e944-966d-4663-a04f-8a80971f85bd.png)

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 0.63.4

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 100

**Comment by tommoor** [comment]
Specifically, it was fixed here: https://github.com/outline/outline/commit/ec1bc801a4e391e7528d706d5855b464a1b27093

**Comment by bmm-alc** [comment]
> Specifically, it was fixed here: [ec1bc80](https://github.com/outline/outline/commit/ec1bc801a4e391e7528d706d5855b464a1b27093)

thanks
