### ISSUE TITLE
when you hit return after a completed todo item, it makes a completed item instead of incomplete

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#3663]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/427579/173860807-018baad6-5839-4db9-8566-4ff8a33e73dc.png">

I don't think it makes sense to ever create completed todo items automatically

**Comment by tommoor** [comment]
One of those long standing Prosemirror frustrations:
https://discuss.prosemirror.net/t/how-to-use-default-listitem-attributes-when-splitting-a-listitem/354/8

Although I'm sure there are smart workarounds

**Comment by thenanyu** [comment]
Ugh. Probably would need to do some gross imperative stuff.

**Comment by tommoor** [comment]
I think we need to implement our own version of `splitListItem` similar to how TipTap has, here:
https://github.com/ueberdosis/tiptap/blob/e2f8747e2b10f98d49798b15d64db5f0a36a3427/packages/core/src/commands/splitListItem.ts#L25
