### ISSUE TITLE
Webhook signing

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3699]
We'd like to add an additional and expected layer of security to webhooks by signing the request body and including the signature in a header as originally included in the [RFC](https://wiki.generaloutline.com/share/47305ccd-9f29-4edf-b48a-21c239bd625e) and is a follow on from https://github.com/outline/outline/pull/3691.

### Requirements

- Add a `secret` BYTEA column to `webhook_subscriptions`
- This column should contain an optional encrypted secret chosen by the webhook creator
- The "secret" field should appear on the webhook create/edit form and be user editable and nullable
- If the secret is present then generate a `Outline-Signature` header which is a signature of the request body, something like:

```
return require("crypto")
    .createHmac("sha256", secretKey)
    .update(JSON.stringify(req.body))
    .digest("hex");
```

**Comment by apoorv-mishra** [comment]
> The "secret" field should appear on the webhook create/edit form and be user editable and nullable

How about restricting it to just _random generation_ as opposed to being editable like regular text form fields? Just a button to generate a random secret?

**Comment by tommoor** [comment]
We could do that but you need to be able to rotate it in the case of a leak. So either it would be the same implementation on the backend with the random gen on the frontend or you'd need an API endpoint to perform the rotation

**Comment by apoorv-mishra** [comment]
True!

As for the approaches, I can't think of any particular reasons to prefer one over the other. Although, I'd like to leave a note on one particular edge case here. The webhook calls are async in nature, triggered via some event. It'd be desirable to ensure that the rotation _doesn't happen while the calls are inflight_, which implies that the rotation should itself happen in async manner, post the processing of inflight calls and to extend it to the other side, the dequeuing should too be paused while the rotation is in progress. That being said, I'm also in favor of ignoring this edge case to start with. We can certainly iterate.

**Comment by tommoor** [comment]
If the new signature applies to any webhooks that are sent from the moment the new secret is saved that seems like reasonable and somewhat expected behavior

**Comment by apoorv-mishra** [comment]
Yes, but what if the secret changed while some of the requests with old signature were inflight? Those would fail the verification upon arrival, right? Very very edgy kind of case but might happen.

**Comment by tommoor** [comment]
If you're actively changing the secret some requests failing is inevitable, as long as the receiving service responds with an error code correctly then the requests will be retried automatically.

**Comment by apoorv-mishra** [comment]
Ahh, retries can help mitigate here. Makes sense provided we attach the modified signature before retry.
