### ISSUE TITLE
Slash command no workie

### ISSUE THREAD

**Issue by tommoor** [outline/outline#370]
I don't see any matching errors on the server though 🤔 

![image](https://user-images.githubusercontent.com/380914/31981430-1c641c40-b908-11e7-8051-ab21d0500a5d.png)

**Comment by tommoor** [comment]
@jorilallo you able to look at this one? I'm actually pretty unclear how this command should work…

**Comment by jorilallo** [comment]
I'll check it out...

**Comment by jorilallo** [comment]
I think this is due to old domain and slash command. I just re-installed and `/outline <query>` works fine
