### ISSUE TITLE
View of webhook deliveries

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3702]
### Requirements

We are already recording webhook deliveries in the database, we need to create an endpoint or two to expose these via the API and enable debugging of failing deliveries.

Open to UX suggestions but I'd probably change the webhook list items to have a menu instead of buttons and then add a "Recent deliveries" item or similar in the menu to open a view similar to below…

### Inspiration

It's nice that both GitHub and Stripe let you Redeliver/Resend an individual delivery on-demand for testing. Stripe also lets you filter by success / failure deliveries. We have some existing patterns to achieve similar, eg the tabs on the Home / Collection screens that load a list endpoint based on different filters.

#### GitHub

<img width="793" alt="image" src="https://user-images.githubusercontent.com/380914/176379947-164c225d-cfde-4384-ad42-3dc769d7d4cc.png">

#### Stripe

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/380914/176380427-7eed3352-ec05-44dc-b94a-582be2b151da.png">

Related https://github.com/outline/outline/pull/3691

**Comment by coreyja** [comment]
Getting started on this, this evening!
