### ISSUE TITLE
Provide a global setting for Share buttons to return normal doc URL instead of creating Share link

### ISSUE THREAD

**Issue by tmvy** [outline/outline#3708]
## Context
- Instance/account is on getoutline.com account (not self-hosted)
- _Public document sharing_ under Security settings is disabled
- We use Outline as an internal wiki only and do not wish to share docs publicly
- After publishing a document, users click _Share > Copy link_, which is the most intuitive option to obtain a link to share (e.g. in Slack) with colleagues

## Current behavior

- While the minimal view of documents provided via the _Share_ link are suitable for external sharing, for internal use, using _Share_ links results in an experience that lacks important features that are needed for internal use, and is inconsistent with the ordinary browsing experience
- When viewing a share link, users cannot navigate back to the rest of Outline via menus, they become confused
- Additional context such as the document location, authors/editors/views, are unavailable
- No menu pops out to the left, as users would normally expect
- As the Outline/wiki maintainer for my organisation, I find that the _Share_ feature is actively undermining user confidence with Outline and most do not understand why this behaviour is occurring.
- I do not want to discourage users from clicking on the most intuitive option available (the _Share_ button), because doing so would harm efforts to generally encourage contributions to our wiki, and non-technical users may have difficulty understanding that the alternative is to copy the URL from the address bar

![outline_share](https://user-images.githubusercontent.com/61309188/176400686-6243cefc-3c3f-403b-8cc6-6316dd0d543d.png)

## Expected behavior

- There should be a toggle in the admin settings which, when enabled, changes the _Share_ button behaviour to return the normal document URL, instead of creating and returning a share link. This option should become available to select when _Public document sharing_ setting is disabled.
- This would require a small front-end change only
- This would allow organisations, who are using Outline only for internal use, to guarantee a consistent experience for their users

**Comment by tommoor** [comment]
Thank you for the thorough ticket, in this case it seems like we could make copying the doc link the default behavior for teams that have external sharing entirely disabled.

As you say, the separate view is only adding confusion in this scenario.
