### ISSUE TITLE
Autolink urls in document

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#371]
<img width="441" alt="screen shot 2017-10-29 at 2 39 27 pm" src="https://user-images.githubusercontent.com/31465/32148615-ff5f952c-bcb6-11e7-9614-8d2c253010b4.png">

**Comment by mikew** [comment]
When does the autolink actually .. link automatically?


https://github.com/outline/outline/assets/4729/7b340b49-ddb6-44f2-a25d-c03f45c4137e

**Comment by tommoor** [comment]
Generally on pasted content, folks don't tend to type out urls – although it would be a good improvement to autolink when it has an obvious protocol like this. Just seems pretty unlikely in real use?

**Comment by mikew** [comment]
Probably the case, was just a frustrating experience writing the link, linking the link to itself, then realizing I was missing an `o`, adding that, selecting the new link+adjacent unlinked character, finally linking that to itself
