### ISSUE TITLE
Sidebar version link opens in the same browser page.

### ISSUE THREAD

**Issue by almereyda** [outline/outline#3737]
When clicking the releases notification in the preferences sidebar, the link is opened in the current browser page.

**To Reproduce**
1. Go to your wiki's preferences.
2. Click on the version indicator.
3. Be redirected to GitHub from within your wiki editing session.

**Expected behavior**

It is expected of this link to open in a new browser tab. Some `target="_blank" parameter could help here, if it was an `<a />` tag, but it isn't. The current implementation is found in these files:

* https://github.com/outline/outline/blob/5658090d7ee9c4e3f102948ec61647596efdb28d/app/components/Sidebar/components/Version.tsx
* https://github.com/outline/outline/blob/5658090d7ee9c4e3f102948ec61647596efdb28d/app/components/Sidebar/components/SidebarLink.tsx

**Outline:**
- Install: self hosted
- Version: v0.64.0

**Desktop:**
 - OS: Ubuntu 22.04
 - Browser Firefox
 - Version 102.0

**Comment by tommoor** [comment]
`target` prop exists but the typings aren't correct here, they need fixing

**Comment by almereyda** [comment]
Many thanks!
