### ISSUE TITLE
unable to create a link on inline code text

### ISSUE THREAD

**Issue by domanchi** [outline/outline#3742]
Outline refuses to allow me to create a hyperlink on inline text (denoted by single back-ticks in markdown, `like this`). However, if the highlighted text includes any other non-whitespace letter that isn't part of the inline text, it works.

**To Reproduce**

1. Create a new document.
2. Type in the following example:

    ```
    inline `text`.
    ```
3. Highlight the `text` snippet, and notice the toolbar pop up. Try clicking the "Create Link" button, and observe nothing happens.
4. Highlight the `text.` snippet (notice the trailing period). Try creating a link, and see that it succeeds.
5. Highlight the ` text` snippet (notice the prefixed whitespace). Try creating a link, and see observe nothing happens as well.
6. Highlight the entire example, and create a link. This works.

For all above steps, instead of clicking the button, you can also press the shortcut (cmd+k on a mac), and it will also not do anything.

**Expected behavior**

Inline code should be able to be hyperlinked (preferably, like the version SHA below).

**Outline (please complete the following information):**
- Install: Self-hosted
- Version: v0.64.3 ([`8a29a3523aecc778c31f27a28cf47cb1cda200ec`](https://github.com/outline/outline/tree/8a29a3523aecc778c31f27a28cf47cb1cda200ec))

**Desktop (please complete the following information):**
 - OS: Windows / MacOSX
 - Browser: Chrome
 - Version: 102 / 103

**Comment by tommoor** [comment]
Hi, this is by design – although the _option_ to add formatting to inline code shouldn't be shown ideally, so there is definitely a bug there.
