### ISSUE TITLE
Visiting an unpublished share link should show login screen

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3745]
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/380914/177759222-38680177-82ab-47c5-8dd9-c1343921b6e3.png">

### Problem
Currently we just show "Not found" page which is a bit of a rude dead end.

### Solution
It would be better to show a login screen and then once the user has logged in/created an account we can forward them back to the original document they wanted to visit. We already do this for non-share links.

**Comment by tommoor** [comment]
For part I – could you investigate rendering the login page instead of redirecting, so that it would keep the url context with the login screen. We might want to customize the text a little for this case afterwards.

For part II we actually already have a cookie for this that you can set – `postLoginRedirectPath`:
https://github.com/outline/outline/blob/f36f5f13f4b10657a5d53a46b4895e86b6a5e817/app/stores/AuthStore.ts#L269

**Comment by CuriousCorrelation** [comment]
Sorry for the delay! Still getting used to the new schedule. 

Thanks for the pointer on setting cookie.

Rendering `Login` seems to be working with a simple import into the if statement. Let me know if this is what you were looking for.

Here's the diff

``` jsx
+  17 import Login from "../Login";
+  18 import { setCookie } from "tiny-cookie";

[...]

  109 │ if (error) {
  110 │ │ if (error instanceof OfflineError) {
  111 │ │ │ return <ErrorOffline />;
  112 │ │ } else if (error instanceof AuthorizationError) {
= 113 │ │ │ setCookie("postLoginRedirectPath", props.location.pathname);
= 114 │ │ │ return <Login />;
  115 │ │ } else {
  116 │ │ │ return <Error404 />;
  117 │ │ }
  118 │ }
  119
```
Also a quick question

> customize the text a little for this case afterwards

I assume what you are referring to here is the login screen text - "Login to Outline" which could be set to "Login to view unpublished shared document". Would that be correct?

**Comment by tommoor** [comment]
> customize the text a little for this case afterwards

I think we can inject a paragraph of <Text> below the title, something like "<Company Name> is using Outline to collaborate on documents, login to continue"

**Comment by CuriousCorrelation** [comment]
Makes sense. Thanks for clarifying 

> paragraph of <Text> below the title

Maybe we could repurpose 

https://github.com/outline/outline/blob/32b7a7df00c267d9bf3e38e51da1104a1995238f/app/scenes/Login/index.tsx#L183

add the message in `scenes/Login/Notices` like 

https://github.com/outline/outline/blob/32b7a7df00c267d9bf3e38e51da1104a1995238f/app/scenes/Login/Notices.tsx#L10-L20

and use cookie to append something like

https://github.com/outline/outline/blob/32b7a7df00c267d9bf3e38e51da1104a1995238f/server/routes/auth/providers/email.ts#L99-L101

---

This seems to work exactly as outlined above

``` jsx
  109 │ if (error) {
  110 │ │ if (error instanceof OfflineError) {
  111 │ │ │ return <ErrorOffline />;
  112 │ │ } else if (error instanceof AuthorizationError) {
= 113 │ │ │ setCookie("postLoginRedirectPath", props.location.pathname);
= 114 │ │ │ return <Redirect to="/?notice=email-auth-ratelimit" />;
  115 │ │ } else {
  116 │ │ │ return <Error404 />;
  117 │ │ }
  118 │ }

```

**Comment by tommoor** [comment]
It's not neccessary to use Notices, that is for server-sent messages. This would be easier to discuss on an actual PR though

**Comment by CuriousCorrelation** [comment]
> Notices, that is for server-sent messages

Took a bit of exploring but on the same page right now. I also think perhaps notices isn't  the best options for UX reasons, especially if this is going to be the first time someone might experience Outline.

I'll make a PR from the previous version and go from there.
