### ISSUE TITLE
Clicking in empty space in self-hosted doesn't focus

### ISSUE THREAD

**Issue by andersmmg** [outline/outline#3748]
In the hosted version on getoutline.com, clicking in the empty space below the text will focus the lowest text field and allow me to edit or add stuff quickly. This doesn't seem to work for me when I'm hosting it locally. I have to click on the actual text and add a new line manually which turns out to be very frustrating

**To Reproduce**
1. Open the app
2. Select a document
3. Click in the space below where the text ends

**Expected behavior**
It should focus the text field to allow adding and editing text.

**Outline (please complete the following information):**
- Install: self-hosted
- Version: v0.64.4

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser Google Chrome
 - Version 103.0.5060.53

**Comment by tommoor** [comment]
Perhaps you can breakpoint the click event and see where it's getting lost

**Comment by tommoor** [comment]
While I don't know what causes this it might be addressed with a refactor for #3373

**Comment by vgwidt** [comment]
I had the same issue using the Docker image, but it was resolved after building from source.  I just built my own local docker image using the Dockerfile.base file.  Maybe whatever the fix was will be included in the next release.

**Comment by tommoor** [comment]
Closing as fixed in the next releases
