### ISSUE TITLE
Official Document has a mistake

### ISSUE THREAD

**Issue by 1itt1eB0y** [outline/outline#3762]
In the OIDC section of the Document, there is a mistake
Link: https://app.getoutline.com/share/770a97da-13e5-401e-9f8a-37949c19f97e/doc/oidc-8CPBm6uC0I

![图片](https://user-images.githubusercontent.com/29831189/178133140-39bcd696-88eb-4817-b0b8-4861c10b4748.png)

Apparently, it should be `OIDC_CLIENT_SECRET`, not `OIDC_CLIENT_ID` 🤣

**Comment by tommoor** [comment]
Thanks, fixed!
