### ISSUE TITLE
Port Search scene to functional style

### ISSUE THREAD

**Issue by CuriousCorrelation** [outline/outline#3781]
While working on `UserFilter` I noticed that Search scene

https://github.com/outline/outline/blob/c3e149eb86e71f121fb8595575863b6395893391/app/scenes/Search/Search.tsx#L47

seems to be one of the few remaining class styled components, unlike its neighbors  

https://github.com/outline/outline/blob/c3e149eb86e71f121fb8595575863b6395893391/app/scenes/Document/index.tsx#L24

https://github.com/outline/outline/blob/c3e149eb86e71f121fb8595575863b6395893391/app/scenes/Login/index.tsx#L52

https://github.com/outline/outline/blob/c3e149eb86e71f121fb8595575863b6395893391/app/scenes/GroupMembers/GroupMembers.tsx#L24

https://github.com/outline/outline/blob/c3e149eb86e71f121fb8595575863b6395893391/app/scenes/GroupNew.tsx#L18

---

We could potentially look into porting it to functional style for readability and consistency

**Comment by tommoor** [comment]
Related issue https://github.com/outline/outline/issues/3457

**Comment by CuriousCorrelation** [comment]
@tommoor Would you mind if I self-assign this issue? Totally fine if not because tag shows that you typically work on techdebt issues.
