### ISSUE TITLE
Moving an image to empty space results in endless upload

### ISSUE THREAD

**Issue by vgwidt** [outline/outline#3794]
If you drag an image that is already in a document to unused space in the editor, it will result in an attempt to upload an image, but the upload does not end.  If you click another page it will ask if you want to interrupt the upload.  This happens on both the online and self-hosted version.

**To Reproduce**
1. Add an image to a document or use document with existing image
2. Try to drag and drop that image to unused space in the editor past the last element
4. Confirm that upload is being attempted by observing the blue load bar at the top of the page or by clicking a new page and receiving the upload in progress dialog box

**Expected behavior**
It should at least not initialize an upload when dragged into unused space.  Perhaps even better, when dragged below the last element, the cursor should remain at the end of that element and the dragged content should be moved there (however, this doesn't happen for normal text either).

**Screenshots**
![](https://i.imgur.com/EJAn15c.gif)

**Outline**
- Install: Both getoutline.com and self-hosted
- Version: self-hosted: c3e149eb86e71f121fb8595575863b6395893391

**Desktop**
 - OS: Windows 10 21H2
 - Browser: Edge
 - Version: 103.0.1264.49

**Comment by vgwidt** [comment]
I think this bug was made apparent by the change that fixed #3748.  I tested the Docker image for release 64.4 where #3748 is still an issue and I was not able to drag an image past the last element to cause the bug described in this topic.

**Comment by tommoor** [comment]
Oh nice, we've been seeing the associated javascript error in our error tracker and had no idea how it was triggered in the editor.
