### ISSUE TITLE
[FR] Collapsible Spoiler

### ISSUE THREAD

**Issue by dl-lim** [outline/outline#3803]
Feature request for a collapsible spoiler like this in outline:

<details><summary>Spoiler</summary>
secrets
</details>

I tried using the `<details>` tag, which usually works with most Markdown readers but didn't work in outline. 

Not sure if there's currently a way to do this.

**Comment by vgwidt** [comment]
I think spoiler has the distinct feature of being hidden by default, used for displaying optional, noisey content that may need to be referenced in the doc from time to time.  I used it quite a bit in Confluence for unwieldy lists such as network address tables or logs.

**Comment by tommoor** [comment]
Not really high priority as you can use collapsed headings for this today, eg create a small heading (H4) by typing "#### " and then collapse it to hide the content below.

**Comment by krawallo666** [comment]
As @vgwidt stated before the spoiler is hidden by default and requires no manual action to close. We have several pages in our actual wiki with big code blocks in spoiler tags. To close them all before reading the page would not be very handy.

This feature is a default in all wiki-distributions i know and i guess in the silent majority there are lots of people who would appreciate this being implemented.

**Comment by krawallo666** [comment]
This feature is now implemented in the way, that you can collapse a heading in the edit-mode and it stays collapsed in the view mode - like the original markdown "detail".

@dl-lim issue could be closed?
