### ISSUE TITLE
Error: the server does not support SSL connections

### ISSUE THREAD

**Issue by MDXDave** [outline/outline#3810]
After upgraded Outline to v0.65.0 and try to restart the docker Container, the outline container stops with the error message:

"Error: the server does not support SSL connections" 

When downgrade to v0.64.4 everything works as expected. 

**Outline (please complete the following information):**
- Install: self-hosted
- Version: v0.65.0

**Comment by pidnee** [comment]
Same here even though I have - PGSSLMODE=disable set in the compose file

**Comment by razor950** [comment]
The issue is with https://github.com/outline/outline/blob/746dc30aebd5ec42bfad050f8e8e3aae70435873/server/utils/startup.ts#L9 it doesn't check if you ssl disable and run this command instead 
'yarn sequelize db:migrate:status --env=production-ssl-disabled'

**Comment by aariacarterweir** [comment]
Temporary fix:

Overwrite the database.json file in your deployment and remove the dialectOptions from the production section. I've just got it in a Dockerfile like so:

```
FROM outlinewiki/outline:0.65.0

# Set workdir
ARG APP_PATH=/opt/outline
WORKDIR $APP_PATH

# COPY BASE ENV FILE
COPY src/outline-wiki.env .env
COPY src/database.json server/config/database.json

# Set system wide env
ENV PGSSLMODE disable

# Set cmd
CMD yarn sequelize:migrate --env=production-ssl-disabled && node ./build/server/index.js
```

and in src/database.json:

```
{
  "development": {
    "use_env_variable": "DATABASE_URL",
    "dialect": "postgres"
  },
  "test": {
    "use_env_variable": "DATABASE_URL_TEST",
    "dialect": "postgres"
  },
  "production": {
    "use_env_variable": "DATABASE_URL",
    "dialect": "postgres"
  },
  "production-ssl-disabled": {
    "use_env_variable": "DATABASE_URL",
    "dialect": "postgres"
  }
}
```

**Comment by aariacarterweir** [comment]
> Same here even though I have - PGSSLMODE=disable set in the compose file

sequelize won't pick that up, it goes off the database.json file in server/config/database.json and uses the production env. See my comment above for a quick fix

**Comment by Edll** [comment]
I still get this error in new docker Version:

Install: self-hosted
Version: outlinewiki/outline:0.67.2

```
ERROR: The server does not support SSL connections

error Command failed with exit code 1.

WRN Command failed: yarn sequelize db:migrate:status
[31mERROR:[39m The server does not support SSL connections
error Command failed with exit code 1.
```
