### ISSUE TITLE
Import from Notion - RangeError  The argument 'size' is invalid

### ISSUE THREAD

**Issue by Pashaflayt** [outline/outline#3829]
In continuation of this [issue](https://github.com/outline/outline/issues/3632)
I'm trying to import a 4 GB backup from Notion to Outline and get Error.
If you need an example of a backup, I will try to depersonalize, reduce and post it.

**To Reproduce**
1. upload a .zip backup approximately larger than 150mb .zip (html or markdown it doesn't matter)
2. After download get error: Can't read the data of 'the loaded zip file'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) 

**Expected behavior**
Successful import 

**Screenshots**
<img width="713" alt="screenshot" src="https://user-images.githubusercontent.com/48829241/180245563-1e3b31e9-98d6-42f4-a6d8-9cdd23e34a7c.png">

**Logs**
https://sentry.io/share/issue/ecf81e9118db485db7c79b722e6a24ec/
https://sentry.io/share/issue/aa6f8d880e8b48258d346e2feb88d7e4/

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.65.2

**Desktop (please complete the following information):**
 - OS: MacOS 11.6.7
 - Browser Chrome
 - Version 103.0.5060.114 (arm64)

**Comment by tommoor** [comment]
Related https://github.com/Stuk/jszip/issues/765

**Comment by tommoor** [comment]
#3849 may have helped, but honestly an import of this size is never going to work reliably – you should split into multiple smaller files.

**Comment by Pashaflayt** [comment]
> may have helped, but honestly an import of this size is never going to work reliably – you should split into multiple smaller files.

Thanks a lot. It would be great to split the file into blocks of at least 500 mb. But In the current situation, files less than 100mb are needed, I want to cry.
