### ISSUE TITLE
Remove option to templatize trashed document 

### ISSUE THREAD

**Issue by vn-ncvinh** [outline/outline#3831]
Templates cannot be created from the trash.

**To Reproduce**
1. Go to `Trash`
2. Click the `ellipses` next to any document.
3. Select `Templatize`

**Screenshots**
![Error](https://i.ibb.co/Pw86xrm/Error.png "Error")

**Outline:**
- Install: getoutline.com

**Comment by tommoor** [comment]
The UI should not be visible for trashed documents 👍 It's probably not checking the policy correctly

**Comment by asheerrizvi** [comment]
@tommoor I would like to take this up. Can I have some more context?

**Comment by apoorv-mishra** [comment]
Are you working on this @asheerrizvi ? If not, mind if I pick it up?

**Comment by asheerrizvi** [comment]
Didn't start. You can have it @apoorv-mishra

**Comment by apoorv-mishra** [comment]
**Actual**
![Screenshot from 2022-07-28 10-39-08](https://user-images.githubusercontent.com/15694566/181429957-6074a3e0-5c01-4d3e-a5b9-da48c31e6326.png)

**Expected**
![Screenshot from 2022-07-28 10-47-51](https://user-images.githubusercontent.com/15694566/181429967-6053507b-eeca-44ac-83c0-53541a382650.png)

Looks good @tommoor ?
