### ISSUE TITLE
Logout leads to infinite reload

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#384]

**Comment by tommoor** [comment]
Hmmm, I just saw this again.

**Comment by jorilallo** [comment]
I should have a fix for this

**Comment by enzolutions** [comment]
@tommoor @jorilallo I can confirm that the issue is still happening in a self-hosting environment using Google Auth.

I am testing using this Heroku environment https://elements.heroku.com/buttons/outline/outline

Maybe we could re=open this issue?
