### ISSUE TITLE
Improve delete document confirmation modal

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3843]
After some customer mistakes it's become apparent that this confirmation dialog wording needs tweaking – we should include a count of how many nested documents will also be deleted in the message.

**Comment by asheerrizvi** [comment]
@tommoor what needs to be changed here? I can take this up if you can give a general overview of what needs to be changed.

**Comment by apoorv-mishra** [comment]
![Screenshot from 2022-07-26 15-01-48](https://user-images.githubusercontent.com/15694566/180974597-9f9a3e98-f126-4df6-9bea-701c97fc5024.png)

How does the message in :point_up: look? @tommoor
