### ISSUE TITLE
Add rate limiting middleware across all API endpoints

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3845]
Can start with a high rate limit across all endpoints and throttle down individually as required.

Will need some research into if any existing middleware packages are capable enough.

**Comment by apoorv-mishra** [comment]
> throttle down individually as required.

How do we wish to do this? By pushing the API specific middleware code changes on ad-hoc basis or via some separate web interface? I'm in favor of the former for now.

**Comment by tommoor** [comment]
Not a web interface, just individually configured on potentially problematic endpoints.

**Comment by apoorv-mishra** [comment]
[Here](https://github.com/koajs/koa/wiki#rate-limiting) is a list of rate limiting middlewares for Koa. A quick search revealed [this](https://github.com/koajs/koa/wiki#rate-limiting) as another.

**Comment by apoorv-mishra** [comment]
https://github.com/animir/node-rate-limiter-flexible seems to be a popular one and also actively maintained. Besides, it also supports Koa v2 as per [this](https://github.com/koajs/koa/wiki#rate-limiting). What remains to evaluate is whether it suits aforementioned requirements. Mind if I go ahead and play around with this a bit?

**Comment by tommoor** [comment]
Go for it, I think we'd prefer to use the redis interface for rate limit storage 😄
