### ISSUE TITLE
Notion import does not support images with `(` `)` characters in the url image path

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3852]
**To Reproduce**
1. Upload an image with brackets to Notion
2. Create a HTML export of the space
3. Import to Outline
4. Imported document will contain a broken image.

**Comment by tanvirraj** [comment]
@tommoor by reading this `Upload an image with brackets to Notion` I understand uploading image like this video , am i correct what you mean 

https://user-images.githubusercontent.com/3768120/181778423-9f6d5395-3d5b-435f-8774-2752d44ce90d.mov

**Comment by tommoor** [comment]
The filename of the image should contain brackets

**Comment by tanvirraj** [comment]
@tommoor , without file name contain brackets, import html still broken .
i want to work on it, can you give me a pointer where i can start looking from codebase 


https://user-images.githubusercontent.com/3768120/182119155-6f16e00c-cc4e-48c2-ad11-c71dbdedd8ed.mov

**Comment by tommoor** [comment]
I guess there are two separate bugs here then, I was actually referring to the bulk import function through **Settings -> Import -> Notion**. The case you have raised seems like it's something else, I wonder in the exported HTML where does the image point to?

**Comment by tanvirraj** [comment]
> I wonder in the exported HTML where does the image point to?
image and html file are in the same folder but I will debug to find out. 
And It seems like 2 bug then.

I wants to work on this. can you give me pointer where i can start to look first from codebase

**Comment by tommoor** [comment]
https://github.com/outline/outline/blob/main/server/commands/documentImporter.ts

**Comment by tanvirraj** [comment]
Thanks

**Comment by tanvirraj** [comment]
@tommoor, 
after working i found that, when notion export html , it export a html file and a folder with containing the image, so when we import html file the image is not imported. this is one reason that import html document not working 

do you have any idea, what can i do to solve this issue 


<img width="747" alt="Screenshot 2022-08-23 at 8 00 43 PM" src="https://user-images.githubusercontent.com/3768120/186178294-61aec458-2e04-4ecd-b1a1-d7e20284f46a.png">
