### ISSUE TITLE
Unable to download images generated by markdown.

### ISSUE THREAD

**Issue by vn-ncvinh** [outline/outline#3853]
Unable to download images generated by markdown.

**To Reproduce**
1. Go to any document
2. Write markdown to display images:
```
![](https://demo.com/abc.jpg)
```
3. Now the image will appear, but when we click the download button, nothing happens. Checking the console log, there is an error that cannot connect to the image url we entered.

**Outline:**
- Install: getoutline.com

**Comment by tommoor** [comment]
Related #3515

**Comment by elidrissidev** [comment]
This issue is caused by CORS if you're embedding images from a different origin. The linked issue has to do with the button not being clickable I think.
