### ISSUE TITLE
[minor] version not updated

### ISSUE THREAD

**Issue by frankli0324** [outline/outline#3860]
https://github.com/outline/outline/blob/30190866f8c2c6189105d34cb6b508f4917b4564/package.json#L343

![image](https://user-images.githubusercontent.com/20221896/180777186-0cdeeda7-e11c-4cd6-9b72-f8815857690c.png)

confused me for a couple of minutes

**Comment by tommoor** [comment]
closed by 9b837763e64d3788fb98f2ba3558abf72e449bd7
