### ISSUE TITLE
Add team preference to disable drafts

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3880]
### Discussed in https://github.com/outline/outline/discussions/3824

<div type='discussions-op-text'>

<sup>Originally posted by **looeee** July 20, 2022</sup>
Is there any way to automatically publish new documents? 

I am migrating a team from Notion to Outline and generally it's going smoothly. This is great software. 

Weirdly though, the biggest blocker for users is getting used to the fact that new documents are not automatically published. 

I would like to disable the draft feature and have new documents show up immediately for all users no matter who creates them. Besides causing confusion it's just not something we need. </div>

**Comment by tommoor** [comment]
@thenanyu thoughts on making this a column `defaultDocumentStatus` with enum type ("draft" | "published")? Feels like it opens up opportunity for "approval" or similar in the future without compromising much right now.

**Comment by alanfrigo** [comment]
Was this feature included? If so, how can I enable it?
