### ISSUE TITLE
Regex for some embeds are not escaped

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3899]
Potentially allows domains which are not supported to be embedded, more details on report on huntr:
https://huntr.dev/bounties/b37145c7-796b-4b1d-994e-d0d007b426df/

**Comment by apoorv-mishra** [comment]
Assuming that we just need to escape a bunch of _dots_ in regexps, I can pick this up.

Or, is there something else we're thinking of to fix this problem?

**Comment by tommoor** [comment]
Yes, just escaping to close this out!
