### ISSUE TITLE
api/documents.info returned 404 on self hosted version

### ISSUE THREAD

**Issue by mr-bantsevich** [outline/outline#3913]
We use self hosted version more then one year and regular upgrade to latest version.
After upgrade outline can't see, edit the pages. Getting 404 on api/documents.info URL. After downgrade to minor versions the same.
It reproduce when I go straight to the link (ex: /doc/organizaciya-proekta-pered-startom-IIoshIoAPd), but not on all pages.

Example where this doesn't work:
Console with request:
<img width="869" alt="Снимок экрана 2022-08-03 в 09 15 57" src="https://user-images.githubusercontent.com/12588034/182537341-d7616958-4476-4266-99ed-b66143072354.png">

Console with response:
<img width="704" alt="Снимок экрана 2022-08-03 в 09 16 50" src="https://user-images.githubusercontent.com/12588034/182537458-70337ee6-5406-408a-88c5-253056985fb0.png">

Example where it works:
<img width="650" alt="Снимок экрана 2022-08-03 в 09 26 32" src="https://user-images.githubusercontent.com/12588034/182538971-1dd0d115-f952-4895-a94f-d15f52697773.png">

Maybe it depends on length of URL, I don't understand

But if I will go throw the link in navigation bar or links in documents always will be work:
<img width="644" alt="Снимок экрана 2022-08-03 в 09 21 14" src="https://user-images.githubusercontent.com/12588034/182538142-226896e9-737a-4bd8-998a-52642668780c.png">

I see different request

**Comment by mr-bantsevich** [comment]
This request work:
```
curl --request GET \
  --url 'https://***/api/documents.info?apiVersion=2&id=test-0Mjh8gXMyt' \
  --header 'Authorization: Bearer ***' \
```

This not:
```
curl --request GET \
  --url 'https://***/api/documents.info?apiVersion=2&id=oglavlenie-PK9Jyz0J8C' \
  --header 'Authorization: Bearer ***'
```

**Comment by tommoor** [comment]
What software versions? Are you sure the documents aren't deleted?

**Comment by mr-bantsevich** [comment]
> What software versions? Are you sure the documents aren't deleted?

We installed v0.65.2.
Yes. I'm sure.

This request return page:
```
curl --request GET \
  --url 'https:// ***/api/documents.info?id=5a871dfd-7657-4789-bdfc-5ed77ebf1312' \
  --header 'Authorization: Bearer ***'
```
Part with response:
```
{
	"data": {
		"id": "5a871dfd-7657-4789-bdfc-5ed77ebf1312",
		"url": "/doc/oglavlenie-PK9Jyz0J8C",
		"urlId": "PK9Jyz0J8C",
```

But after I press cmd + r (refresh page) in safari, outline call method
```
curl --request GET \
  --url 'https://***/api/documents.info?apiVersion=2&id=oglavlenie-PK9Jyz0J8C' \
  --header 'Authorization: Bearer  ***'
```
which return 404. response:
```
{
	"ok": false,
	"error": "not_found",
	"status": 404,
	"message": "Resource not found"
}
```

**Comment by apoorv-mishra** [comment]
>```
>curl --request GET \
>  --url 'https://***/api/documents.info?apiVersion=2&id=oglavlenie-PK9Jyz0J8C' \
>  --header 'Authorization: Bearer  ***'
>```

Is it so that this request is _always_ failing? Or does it fail at random?

> But after I press cmd + r (refresh page) in safari, outline call method

Also, regarding :point_up: , are you sure that the browser makes a `GET` request instead of a `POST`?

**Comment by mr-bantsevich** [comment]
> > But after I press cmd + r (refresh page) in safari, outline call method
> 
> Also, regarding ☝️ , are you sure that the browser makes a `GET` request instead of a `POST`?

Sorry, yes, here you are right, I did mistake in query, bit in not solve problem.



> > ```
> > curl --request GET \
> >  --url 'https://***/api/documents.info?apiVersion=2&id=oglavlenie-PK9Jyz0J8C' \
> >  --header 'Authorization: Bearer  ***'
> > ```
> 
> 
> Is it so that this particular request _always_ fails? Or, does it fail at random?

Random page, I don't understand which page work, which not. But if page return 404 - this page always return 404 error

**Comment by apoorv-mishra** [comment]
Could you run :point_down: in **your server's `node` console** and share the output?

```js
"oglavlenie-PK9Jyz0J8C".match(/^(?:[0-9a-zA-Z-_~]*-)?([a-zA-Z0-9]{10,15})$/)
```
Make sure that **console's `node` version matches with that of the version used by outline**.

Although, it's unlikely that the regex behaves differently but still taking a shot. It'll just rule out a possibility, at the least :smile:

**Comment by mr-bantsevich** [comment]
```
/opt/outline $ node
Welcome to Node.js v16.14.2.
Type ".help" for more information.
> "oglavlenie-PK9Jyz0J8C".match(/^(?:[0-9a-zA-Z-_~]*-)?([a-zA-Z0-9]{10,15})$/)
[
  'oglavlenie-PK9Jyz0J8C',
  'PK9Jyz0J8C',
  index: 0,
  input: 'oglavlenie-PK9Jyz0J8C',
  groups: undefined
]
```

**Comment by tommoor** [comment]
I created the exact same document slug + urlId combo locally and wasn't able to reproduce unfortunately, for that reason we can probably take the naming out of the equation. It would be good to know exactly which version you were on before where it loaded correctly.

**Comment by b1nks** [comment]
I had the same problem. I think that the reason may be related to migrations, because the solution to the problem was to reindex the documents table. 

```
REINDEX TABLE documents;
```

Otherwise, the search by "urlId" did not give a result, although the desired "urlId" could be observed with one's own eyes by finding the same string in the "Id" field. 

I noticed this because going to the internal document using a link from the collection worked fine, because in this case the "Id" of the document was used in the API. 

```
// using the example data from this discussion
{id: "5a871dfd-7657-4789-bdfc-5ed77ebf1312"}
```

But when the page was refreshed, the content disappeared and the error "not_found" was given, because the search went on "urlId”. The same behavior occurs when following a direct link to a document.

```
{id: "oglavlenie-PK9Jyz0J8C", apiVersion: 2}
// PK9Jyz0J8C is an "urlId" that exists but was not found
```

In my case the update of Outline was from version 0.66.2 to 0.69.2.
