### ISSUE TITLE
Users in future timezones cannot login via OAuth

### ISSUE THREAD

**Issue by roddux** [outline/outline#3915]
The following code adds a `state` cookie as part of the login flow: https://github.com/outline/outline/blob/6fe4b1cba19cb884f4d2c38ba0232d9d5eb8f485/server/utils/passport.ts#L25-L29

The expiry is set as 10 minutes in the future of the sever's current time, as gathered by `new Date()`. This is sent by the server to the user as follows:
`Set-Cookie: state=outline.test|blahblah; path=/; expires=Wed, 03 Aug 2022 16:01:48 GMT; domain=outline.test`

If the user is in a timezone far enough in the future, relative to the server, then the cookie will immediately expire. This renders the user unable to login.

A better method would be to set the `max-age` property on the cookie, rather than specifying a timezone-specific date.

**Comment by tommoor** [comment]
This is surprising, are you sure this is the issue you're seeing? – the timestamp includes the server timezone so it represents the same time anywhere irregardless of the clients timezone.

**Comment by roddux** [comment]
Hmmm, it was the conclusion I reached after brief testing. I confirmed that setting my _local_ timezone back a few hours fixed the issue.

My mistake, however, is not realising that _all_ `expires` flags use the GMT timezone. I suspect my issue is elsewhere, and that this is a false positive. Sorry to bother you :)

**Comment by tommoor** [comment]
Your change still may be a reasonable improvement as the change perhaps better reflects the intent of the expiry than a timestamp, but I'm also trying to understand what's going wrong in your case.

**Comment by roddux** [comment]
After discussion with colleagues, it seems the fault was that the Outline server clock was adrift— by several hours. Setting my local clock to fit the time difference of the cookie expiry fixed the issue, but not for the reason I suspected.
