### ISSUE TITLE
Public share using minio missing images

### ISSUE THREAD

**Issue by virusbear** [outline/outline#3924]
When using a public share without authentication the default `s3.amazonaws.com` URL is used for images instead of the `AWS_S3_UPLOAD_BUCKET_URL` environment variable.

**Sidenote**
This issue does not occur when an authenticated user is viewing the share link. In this case the correct image is displayed.

I am currently hosting MinIO and Outline on two separate subdomains as running both on the same domain with paths does not seem to work correctly. 
Both services are configured to use https.
The MinIO user configured in Outline has readwrite access.
The bucket used is configured to be public access.

**To Reproduce**
1. Setup MinIO as S3 storage
2. Upload any image to any document
3. Create a public share link accessible without authentication
4. Open the share link (best in private browser)

**Expected behavior**
The image in the document will be loaded from the configures MinIO storage.

**Screenshots**
![image](https://user-images.githubusercontent.com/23473248/182833982-44f0431a-276b-400b-a0d8-a7c7d209322c.png)

**Outline (please complete the following information):**
- Install: self hosted
- Version: 039cc8a3b3ed2a0a2b28e96797b51b372f794234

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version multiple

**Comment by mamazary** [comment]
I also came to this issue, I am using digitalocean spaces
