### ISSUE TITLE
Memory leak in `test:server`

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3939]
Have not yet figured out how, but running jest with `yarn test:server --logHeapUsage` shows increasing memory usage over time, starting from low hundreds of Mb's to Gb's.

This is on the verge of causing OOM issues on the CI instances and will likely make your machine run out of memory if running the test suite locally.

**Comment by tommoor** [comment]
It may have been this way for a long time and it just wasn't noticeable unless you were looking for it, then it hit a critical tipping point. If I had to guess it's probably the move to Typescript or the move to sequelize-typesceipt as it changed so much of the underlying architecture

**Comment by tommoor** [comment]
Caught a couple of things, it's now able to pass locally on my machine but memory is still _very_ leaky somewhere.

**Comment by apoorv-mishra** [comment]
![Screenshot from 2022-08-08 16-30-28](https://user-images.githubusercontent.com/15694566/183403558-3cd8f821-c814-435d-b94f-6a9818e6659b.png)

I attempted `yarn test:server --logHeapUsage` on `node@16.10.0` multiple times after spotting [this issue](https://github.com/facebook/jest/issues/11956) and it succeeded. It failed again after switching back to `16.16.0`.

**Comment by tommoor** [comment]
Interesting. What was the heap usage like on the lower node version?

**Comment by apoorv-mishra** [comment]
> Interesting. What was the heap usage like on the lower node version?

Went up to ~1600MB. But it wasn't monotonically increasing as was the case with `16.16.01. GC was indeed able to sweep and bring down the usage at various instances visibly.

**Comment by tommoor** [comment]
CI servers are currently set at Node 14, so while it may have gotten worse when ran locally it's not the entirety of the issue unfortunately

**Comment by apoorv-mishra** [comment]
I found some potential leaks as well and attempted to fix :)

**Before**
![Screenshot from 2022-08-09 12-47-37](https://user-images.githubusercontent.com/15694566/183588635-49e30386-887f-47a9-901a-228a9d047030.png)

**After**
![Screenshot from 2022-08-09 12-48-25](https://user-images.githubusercontent.com/15694566/183588775-74cdadb8-a4ee-481e-bda0-4b0901deb5a6.png)

I covered `server/` so far. `shared/editor/embeds/` are still problematic. I guess I know why. Will raise a draft PR after trying that out.

**Comment by tommoor** [comment]
Feel free to submit individual fixes, much easier to review 😄
