### ISSUE TITLE
Logout via OIDC not working/not implemented?

### ISSUE THREAD

**Issue by gabriel-gfs** [outline/outline#3954]
When I logout from Wiki it doesnt remove the OIDC(in this case Keycloak) Token -> I can just click sign in again and be logged in automatically.

**To Reproduce**
1. Click on Sign in
2. Click on Sign out
3. Click on Sign in again
4. You are signed in without logging in

**Expected behavior**
I expect Outline to log me out via the logout endpoint of the OIDC provider.
This could be implemented via the logout endpoint provided by the OIDC provider which can be found by querying the .wellknown endpoint which is defined in the OIDC spec. 

**Outline:**
- Install: self hosted
- Version: 
https://github.com/outline/outline/tree/v0.65.2
https://github.com/outline/outline/commit/039cc8a3b3ed2a0a2b28e96797b51b372f794234

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by deibertf** [comment]
I would also appreciate this being implemented!

**Comment by helmut72** [comment]
Same for me. It even login with `user1` when `user2` is authenticated on my OIDC provider (Authelia) in the meantime.

**Comment by jeffshead** [comment]
Same for me. Wish they would implement a fix.

**Comment by tommoor** [comment]
Open to PR's that implement this, low priority for maintenance team

**Comment by deibertf** [comment]
Will try to create a PR for this, give me a few days 👨🏼‍💻

**Comment by HanadaLee** [comment]
> Will try to create a PR for this, give me a few days 👨🏼‍💻

Is there any progress? Looking forward to your PR.

**Comment by helmut72** [comment]
For me this is an important feature. There are some little features left like this one.

**Comment by Spacelord09** [comment]
Any updates to this? #3672 states that an "OIDC_LOGOUT_URI" parmeter exists. But I cant find any proof for that.

**Comment by tommoor** [comment]
It doesn't exist yet – this hasn't been tackled yet

**Comment by HanadaLee** [comment]
Any update?

**Comment by kekersdev** [comment]
![image](https://github.com/outline/outline/assets/27924939/5b1c68a9-03ec-4c27-9e8c-e84963df507d)

**Comment by museghost** [comment]
The outline is the greatest knowledge management solution.
For security aspect, if this feature is implemented, the outline is getting closer to the perfection.

**Comment by helmut72** [comment]
My user now logs out from Keycloak (no sessions), but Outline still accept the user after re-open Outline. Do I need to send anything back to Outline?
