### ISSUE TITLE
Update `documents.export` endpoint

### ISSUE THREAD

**Issue by Nicicalu** [outline/outline#3972]
The download button downloads the state of the file when the page was loaded, not the current one. When you make changes they will not be in the downloaded markdown file. You need to reload the page and then download again, to donwload the current state of the document.

**To Reproduce**
1. Go to any document
2. Edit something
3. Download the document as a markdown file
4. Changes aren't in the file
5. Reload the page
6. Download again
7. Changes are in the file

**Expected behavior**
The download button should download the current state of the file

**Outline:**
- Install: Self hosted
- Version: v.0.65.2 

**Desktop:**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 103.0.5060.114

**Comment by tommoor** [comment]
This doesn't seem to be too reproducible, is it possible that you are making changes and downloading the document very fast? Changes are not persisted to the database until a minimum of 3 seconds after they are made so a download in this time period might catch the old state…

**Comment by Nicicalu** [comment]
Hmm, I just tested that again and I typed for more than a minute before downloading...
When I hit `CTRL + S` I can see the `document.update` requests in the network tab and I can download the current state.

I'ts not problem for me. I just figured I wasn't the only one. The error could be on my installation.

**Comment by tommoor** [comment]
I'm going to keep this open as in order to unblock #3000 we need to move the download function to an API call anyway, it may help the issue.
