### ISSUE TITLE
Flash of "Untitled" in tab when loading a share link

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3985]
Load this link - pay close attention to the title:
https://wiki.generaloutline.com/share/770a97da-13e5-401e-9f8a-37949c19f97e/doc/aws-s3-N4M0T6Ypu7

You'll see "Untitled" flash, it shouldn't.

**Comment by JATIN2111999** [comment]
i want to work on this what you want me to print instead of Untitled as page is loading on this stage

**Comment by tommoor** [comment]
The correct page title is already rendered by the server in the html, it should not be replace with Untitled.

<img width="667" alt="image" src="https://user-images.githubusercontent.com/380914/186100513-8d3b4be7-e42e-4808-8edd-0e75c53a5342.png">

**Comment by JATIN2111999** [comment]
```
    <Container column auto>
      <PageTitle
        title={location.state ? location.state.title : t("Untitled")}
      />
      <CenteredContent>
        <PlaceholderDocument />
      </CenteredContent>
    </Container>
```

do i remove the title like this 

```
    <Container column auto>
      <CenteredContent>
        <PlaceholderDocument />
      </CenteredContent>
    </Container>
```

**Comment by tommoor** [comment]
No, this covers other cases within the authenticated app. The likely best move is to hydrate `location.state.title` from the one rendered in the HTML title tag on first load.

**Comment by JATIN2111999** [comment]
> No, this covers other cases within the authenticated app. The likely best move is to hydrate `location.state.title` from the one rendered in the HTML title tag on first load.

like this
```
    <Container column auto>
         {location.state && <PageTitle title={location.state.title} />}
      <CenteredContent>
        <PlaceholderDocument />
      </CenteredContent>
    </Container>

```

**Comment by apoorv-mishra** [comment]
> like this
> 
> ```
>     <Container column auto>
>          {location.state && <PageTitle title={location.state.title} />}
>       <CenteredContent>
>         <PlaceholderDocument />
>       </CenteredContent>
>     </Container>
> ```
 
Not here! As pointed out before, it has to be hydrated somewhere _up_. Probably :point_down:  https://github.com/outline/outline/blob/68f24fce219c6ffc499e407e60756c33c9385d95/app/scenes/Document/Shared.tsx#L140

**Comment by JATIN2111999** [comment]
> > like this
> > ```
> >     <Container column auto>
> >          {location.state && <PageTitle title={location.state.title} />}
> >       <CenteredContent>
> >         <PlaceholderDocument />
> >       </CenteredContent>
> >     </Container>
> > ```
> 
> Not here! As pointed out before, it has to be hydrated somewhere _up_. Probably point_down
> 
> https://github.com/outline/outline/blob/68f24fce219c6ffc499e407e60756c33c9385d95/app/scenes/Document/Shared.tsx#L140

thanks @apoorv-mishra now i understand where to edit 
but i am confusion regarding what to display 

```
if (!response) {
    if (props.location.state)
      return <Loading location={props.location} />;
    else
      return <Loading location={**?**}/>
  }
```

what to display if the `props.location.state` is undefined
