### ISSUE TITLE
Drafts

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#40]
This would be killer but needs scoping. Probably should be in user's global state over individual collections. I imagine we could make this work very similarly to Medium's Save/Publish

**Comment by tommoor** [comment]
I think this would be a good quick win. The main thing it enables is us to have automatic saving which we can't really do right now because saving for the first time is also publishing.

**Comment by jorilallo** [comment]
I like the idea. What are you thinking for the implementation, a new backend model with simple APIs only scoped to the user? Feels pretty simple in my mind, and useful

**Comment by tommoor** [comment]
I was thinking we'd add a `publishedAt` column to documents, migrate all the current documents so that `publishedAt` = `createdAt` and add a default scope to all queries so they only return published documents etc some new endpoints for drafts.

**Comment by jorilallo** [comment]
Sounds good
