### ISSUE TITLE
Migrate users from google provider to oidc

### ISSUE THREAD

**Issue by RoboNET** [outline/outline#4021]
It looks like I found the problem.
Previously, our accounts were created with the Google provider from google workspace (user@our.domain).
And now if I try to create a new user from Keycloak "test@our.domain" we will have a validation error like in my post.
If I change the test user's domain to "test@example.com" and add example.com to the allowed domains, the user logs in successfully.
If I change the user's email address to "user@example.com", he also logs in successfully, but a new user is created.

Changing the Keycloak address or settings will result in other errors like fields not found or an access token error, so I think the problem is somewhere inside the user creation logic in outline

_Originally posted by @RoboNET in https://github.com/outline/outline/discussions/3994#discussioncomment-3487398_

**Comment by tommoor** [comment]
The behavior was changed to allow for your usecase in https://github.com/outline/outline/pull/3813 – the work is merged and will be included in the next release
