### ISSUE TITLE
I don't have any of the offered SEO accounts

### ISSUE THREAD

**Issue by dosch** [outline/outline#4028]
I'd love to try Outline, but you require me to register with MS, Google or slack. 
I do not have an account on any of them. 

Could I register with my email address?

 
<img width="457" alt="Screenshot 2022-08-30 at 11 39 20" src="https://user-images.githubusercontent.com/5372610/187404507-36a84c32-c476-4f8d-b1d7-3703f8fc8797.png">

**Comment by tommoor** [comment]
Only the listed methods are supported at this time.
