### ISSUE TITLE
Request functions used with POST can be used with GET

### ISSUE THREAD

**Issue by vn-ncvinh** [outline/outline#4038]
The functions were designed to use use with POST, but for some reason it didn't work correctly.

Example: At the `Logout function` (`https://[youdomain].getoutline.com/api/auth.delete`), in design it is necessary to use the POST method, but in fact it still works with GET.

**To Reproduce**
1. Login
2. Visit the link `https://[youdomain].getoutline.com/api/auth.delete` 
3. Go back to the outline, and see that you have been logged out.

**Impact**
If the attacker embeds the link in the img tag, whenever the user sees the image, they will be logged out. Interestingly, Outline also has the same function (image markdown, avatarUrl). This slightly affects the availability of the application.

**Screenshots**
![image](https://user-images.githubusercontent.com/80946737/187615454-5e96dfa4-b8de-4f5d-9395-220a940bbba8.png)

**Outline:**
- Install: getoutline.com

**Comment by tommoor** [comment]
This was originally by design in the very early days of the project, but agreed it should be removed now as a security risk. I just did analysis on the last weeks worth of requests to our production deployment and there isn't a single valid use of an API endpoint with `GET`, only folks probing.
