### ISSUE TITLE
400 error when creating an attachment via the API with a size smaller than allowed

### ISSUE THREAD

**Issue by plvskiy** [outline/outline#4047]
When creating an attachment, accessing the API, it is not possible to create an attachment. I am sending a POST request to:
```
https://<domain>/api/attachments.create
```

With such data:
```
DATA = {
            'name': 'file.png',
            'documentId': collection_id,
            'contentType': 'image/png',
            'size': os.stat(file_name).st_size
        }
```

The final dictionary looks like this:
```
DATA: {'name': 'file.png', 'documentId': '<collection_id >', 'contentType': 'image/png', 'size': 216232}
```
When sending a request, I get an error:
```
{'ok': False, 'error': 'validation_error', 'status': 400, 'message': 'Sorry, this file is too large – the maximum size is 100 MB'}
```
Looking into the database, I can see that there are larger attachments. For example, the size of one of the files is 436591 bytes. And this is with a limit of 100 MB

**Comment by tommoor** [comment]
Seems like it would work, the code is a simple check against the passed size to the configured size. ([ref](https://github.com/outline/outline/blob/main/server/routes/api/attachments.ts#L40-L49)) What are you using to create the API request?

**Comment by plvskiy** [comment]
> Seems like it would work, the code is a simple check against the passed size to the configured size. ([ref](https://github.com/outline/outline/blob/main/server/routes/api/attachments.ts#L40-L49)) What are you using to create the API request?

The piece of code with which I send the file looks like this:

```
file_name = 'file.png'

DATA = {
    'name': file_name,
    'documentId': collection_id,
    'contentType': 'image/png',
    'size': os.stat(file_name).st_size
}

requests.post('https://domain/api/attachments.create', headers=HEADERS, data=DATA)
```

**Comment by tommoor** [comment]
I suspect user error somehow, there is really nothing going on in the code here except a single check to see if the passed `size` value is larger than the value configured in `process.env.AWS_S3_UPLOAD_MAX_SIZE` – it's an if statement and both sides of the equation are in your control :)

**Comment by plvskiy** [comment]
The directive is larger than the file size - 100 MB:
`AWS_S3_UPLOAD_MAX_SIZE=100000000`
