### ISSUE TITLE
A full export results in a 404 Error

### ISSUE THREAD

**Issue by mmuenker** [outline/outline#4059]
A full export results in a 404 Error

## To Reproduce
1. Go to 'Settings -> Export'
2. Click on 'Export Data'
3. Click on 'Download'

## Expected behavior
The archive with all collections should be downloaded

## Actual behavior

**Http Response**
Error: 404
Url: https://[org].getoutline.com/api/fileOperations.redirect?id=[uuid]

```json
{"ok":false,"error":"not_found","status":404,"message":"Resource not found"}
```

## Outline (please complete the following information):
- Install: getoutline.com

## Desktop (please complete the following information):
 - OS: Pop_OS
 - Browser Firefox
 - Version 103.0

**Comment by dongyu-shen** [comment]
same error

**Comment by dream10201** [comment]
It seems this bug has appeared again.

**Comment by dream10201** [comment]
Using the curl command with the -L option does not directly download the file; it returns {"ok":false,"error":"not_found","status":404,"message":"Resource not found"}. Because of this, I have to remove the -L option and obtain the redirect URL separately to download the file.
