### ISSUE TITLE
Add team preference to show logo on login screen

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4060]
In the OSS we have a relatively unused env variable called `TEAM_LOGO` which when set will show the image on the login screen. I've never liked this solution, it feels hacky and disconnected from the main product – we can just show the same logo that shows inside the app on the login screen.

For cloud hosted login pages we show the Outline logo, which is fine but it would be much clearer to show the company logo.

### Implementation
Add a team preference, `publicLogo` or similar which enables the data to be included in the `auth.config` payload for the team and rendered on the login screen.

Depends on #3990

**Comment by apoorv-mishra** [comment]
What should `teamLogo` be in `preferences`? URL?

**Comment by tommoor** [comment]
How about `publicBranding: boolean` – we'll use the existing logo image that's already uploaded for now, if we need to have a custom image in the future then that can be an additional property.

**Comment by Limezy** [comment]
Would be nice to allow a svg, as this is gonna be the icon for PWA also, I guess ?

**Comment by tommoor** [comment]
Solid maybe, the problem is SVG allows JavaScript embedded and it causes all sorts of security gotchas

**Comment by tommoor** [comment]
To be clear we should remove `TEAM_LOGO` as part of this.
