### ISSUE TITLE
Starred list did not load when Collection is collapsed on Start PWA

### ISSUE THREAD

**Issue by saggafarsyad** [outline/outline#4073]
Starred list did not load when Collection is collapsed on Start PWA

**To Reproduce**
1. Collapse Collection list
2. Collapse Starred list
3. Exit app
4. Open app
5. Starred list shows empty list
6. Expand Collection
7. Starred list shows list

**Expected behavior**
Starred list will be loaded even Collection list is collapsed on Start app

**Screenshots**
![Screenshot 2022-09-07 at 07 18 35](https://user-images.githubusercontent.com/102730003/188762139-52c0a3e4-4a0e-4153-9534-d07e9a1f5faa.png)

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: `commit 09b2d0babe17269ec6d4878f618de9860156c9b6 (HEAD, tag: v0.66.0)`

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave Browser / Chromium
 - Version: Brave Browser 1.43.89 Chromium: 105.0.5195.102 (Official Build)

**Mobile (please complete the following information):**
 - Device: -
 - OS: -
 - Browser: -

**Comment by Nicicalu** [comment]
It works perfectly fine for me. I'm on Windows with Google Chrome `103.0.5060.114`.

**Comment by tommoor** [comment]
It seems the bug relates to starred _collections_

**Comment by Nicicalu** [comment]
> It seems the bug relates to starred _collections_

You're right. When testing it with a starred collection it doesn't work.
