### ISSUE TITLE
Allow clicking "external link" decoration to open link

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4076]
I've seen users try this a couple of times, might as well turn it into a teeny button.

**Comment by SincerelyBrittany** [comment]
Hi @tommoor, I am interested in creating this button/ working on this issue. May I have some guidance on where the "external link" is located in the codebase?

**Comment by tommoor** [comment]
https://github.com/outline/outline/blob/main/shared/editor/marks/Link.tsx#L138

**Comment by SincerelyBrittany** [comment]
Hi @tommoor, I have been having a hard time with set up, when I run `make up`, I get `docker-compose up -d redis postgres s3`. I downloaded both docker and postgres. Neither has worked. I know it has been a few days so if you want to give this issue to someone else, I wont mind.
