### ISSUE TITLE
Export of collections fail with error message

### ISSUE THREAD

**Issue by brianvess** [outline/outline#4089]
After the upgrade to v.0.66.0, the export of collections no longer works. When I click on download,
 I get the below error. 

{"ok":false,"error":"not_found","status":404,"message":"Resource not found"}

<img width="1113" alt="Screen Shot 2022-09-08 at 10 54 00 PM" src="https://user-images.githubusercontent.com/53948675/189280887-0ed34986-5f17-446e-8c9c-507356832d8b.png">

<img width="1187" alt="Screen Shot 2022-09-08 at 10 54 20 PM" src="https://user-images.githubusercontent.com/53948675/189280886-d3a11f7e-390b-4edb-bc3d-9efdf3b6625b.png">

**Comment by tommoor** [comment]
Fixed in 34b586724b9570cc8912725d717135c28da2bc66
