### ISSUE TITLE
Document without latest revision

### ISSUE THREAD

**Issue by Limezy** [outline/outline#4090]
While testing the latest history & diff feature (just merged), I came up to some documents that have no "latest" revision. It looks like a bug, even if I'm not quite sure !

**To Reproduce**
I don't know how to reproduce yet - will edit if I can find a process

**Expected behavior**
See the "Latest" revision on history bar

**Screenshots**
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/24638389/189383077-e9b3ea4b-eb60-40f9-babf-9264c8081847.png">

**Outline (please complete the following information):**
- Install: self hosted
- Version: b44aa6243231e2c14f8c4af4cfd7a5e2123ee2d5

**Comment by tommoor** [comment]
Latest is shown if there are edits that have not yet been moved into a
revision. Revisions are created at a maximum of every 5 mins.

**Comment by Limezy** [comment]
OK I understand, but in that case, I would say that the "restore" button shouldn't be shown, no ?

**Comment by tommoor** [comment]
Leaving this open because ideally you'd always be able to see a diff even if a revision has not yet been created then it should be able to diff between the live version and last reivions.

**Comment by Limezy** [comment]
Definitely yes. When testing your latest commits I was confused at first, then understood that I had to wait for the diff to be processed before I could see it. 
Anyway thank you so much for that feature, one of the two I needed the most (together with the comments 😅😎)

**Comment by pztrn** [comment]
Please reopen, this is at least an UX bug. My colleagues flooding me with question "where is latest revision in history log?".
