### ISSUE TITLE
Aesthetic minor issues with history bar

### ISSUE THREAD

**Issue by Limezy** [outline/outline#4091]
1. When the history is void, the "no history yet" mention shouldn't be so close to the vertical bar 
<img width="1257" alt="Capture d’écran 2022-09-09 à 20 26 28" src="https://user-images.githubusercontent.com/24638389/189385222-b23a8661-77a4-415b-a6cc-e16d462c728f.png">

2. When history bar is opened, if you click to another document there is a strange effect (Safari and Orion browsers only)

https://user-images.githubusercontent.com/24638389/189384958-6c09f8f4-823f-4c3c-bfef-41e11eb350a5.mov

3. History bar should be resizable (and persist size)

**Outline (please complete the following information):**
- Install: self hosted
- Version: b44aa6243231e2c14f8c4af4cfd7a5e2123ee2d5

**Comment by tommoor** [comment]
Thanks, definitely released this at 99% instead of 100 just because it was already so much better 😆
