### ISSUE TITLE
Subscribe/Unsubscribe state in document menu is incorrect before document has been viewed

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4103]
The data for this is loaded when you view the doc, meaning if you go to a document menu before it's loaded it will always show "Subscribe" – even when you already are.

**Comment by PabloYG** [comment]
I have solved this a bit bluntly by adding the following to the `DocumentMenu` component:

```
  React.useEffect(() => {
    async function fetchSubscription() {
      if (document?.id) {
        try {
          await subscriptions.fetchPage({
            documentId: document.id,
            event: "documents.update",
          });
        } catch (err) {
          Logger.error("Failed to fetch subscriptions", err);
        }
      }
    }
    fetchSubscription();
  }, [subscriptions]);
```
It works as intended but maybe not the best approach. Suggestions welcome.

**Comment by tommoor** [comment]
I think something like this can work, we'd just want to make sure it's only triggered when the menu is opened and only if subscriptions have not been loaded already for that document.
