### ISSUE TITLE
Custom domain logo still showing

### ISSUE THREAD

**Issue by nayrwex** [outline/outline#4121]
Hi,

I am currently self hosting Outline and trying to hide the Outline logo when a document is being shared.

There was an commit that allowed this but I am trying to understand the logic behind it. https://github.com/outline/outline/issues/1629

https://github.com/outline/outline/blob/ce410c4bf3cd3827e09c9a8f3007f92d22778651/shared/utils/domains.ts#L42

Can i enquire why when the window.location.origin differs from the env.URL, then it is a custom domain? From my understanding, a lot of things such as share link, auth redirect, uses this env.URL variable, and if I were to change it to a random domain to force the above check to be true, the branding logo is gone, but it breaks a lot of functionality in Outline.

May I ask when will window.location.origin differ from the env.URL? Is it when the share link is in a iframe that the window.location.origin of the actual website does not match env.url?

Also, can we remove the following hardcoded link ```www.getoutline.com?ref=sharelink```, as by default it already inherits from the env.URL

https://github.com/outline/outline/blob/ce410c4bf3cd3827e09c9a8f3007f92d22778651/app/scenes/Document/components/Document.tsx#L633

https://github.com/outline/outline/blob/ce410c4bf3cd3827e09c9a8f3007f92d22778651/app/components/Branding.tsx#L12

**Comment by Limezy** [comment]
The branding on shared links is enabled by default for self-hosted instances I think. 

I guess it's designed to be a kind of minor trade off for community users, just like the non existing SAML login option for instance. 

If you compile the app yourself and provided you don't make any money self hosting Outline for clients, I guess it's not against the licence to monkey patch that branding thing.

**Comment by tommoor** [comment]
What Limezy said, this small amount of branding is not removable in the community edition. The enterprise edition has no branding.
