### ISSUE TITLE
Page "flickering" due to repeated forced up scroll when document contains an image in macOS safari

### ISSUE THREAD

**Issue by fuomag9** [outline/outline#4147]
**To Reproduce**
1. Create a Document
2. Add an image

**Expected behavior**
Page should be rendered normally, like it happens on iPhone safari, and other desktop browsers

**Screenshots**

https://user-images.githubusercontent.com/1580624/191308410-e71f3f07-da3a-4566-93c8-93f5cd11b8ed.mp4

**Outline (please complete the following information):**
- Install: self hosted
- Version: outlinewiki/outline with sha256 `4b1c0deabea151fcb2d918319cf463c5390255e1db8f9d5e7b445798e532fb97`

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser safari
 - Version Version 16.0 (17614.1.25.9.10, 17614)

**Comment by tommoor** [comment]
Never seen anything like this, I'm not really clear what's happening here in terms of "forced scroll"…

**Comment by fuomag9** [comment]
> Never seen anything like this, I'm not really clear what's happening here in terms of "forced scroll"…

As you can see from myself trying to scroll down and from the page doing itself, the page is constantly trying to go up (and doing the "flickering" animation)

**Comment by fuomag9** [comment]
The issue seems to have fixed itself, I think it was Cloudflare messing with javascript (but I cannot confirm this)
