### ISSUE TITLE
Pasting YT URL shouldn't use widget in list

### ISSUE THREAD

**Issue by SystemZ** [outline/outline#4154]
Pasting youtube URL in editor breaks list formatting by widget. Kinda similar to #4138 

**To Reproduce**
1. Go to any editable page and use `-` to create list
2. Paste URL `https://www.youtube.com/watch?v=dQw4w9WgXcQ`
3. See widget between two elements of list

**Expected behavior**
I expected to paste raw URL to YT
```markdown
- test1
- test2
- test3a
- https://www.youtube.com/watch?v=dQw4w9WgXcQtest3c
- test3c
```
Maybe option to show rich service embeds should be edited or we should get similar one to totally turn off widgets?
In my case I make a lot of URLs list to show hierarchy of them and my workflow with widgets is kinda slow with constantly adding space character in domain name to prevent widgets.

Ideally there should be toggle of completely enabling/disabling widgets per document maybe?

**Screenshots**
![image](https://user-images.githubusercontent.com/1836094/191606289-ee18240b-9688-41e3-91da-f663de02d646.png)
![image](https://user-images.githubusercontent.com/1836094/191606980-7e81a194-c2ef-4a9a-b5a4-93907cd70818.png)
![image](https://user-images.githubusercontent.com/1836094/191607073-541f9bf6-401b-41f8-a93d-ab06c0c2a103.png)
![image](https://user-images.githubusercontent.com/1836094/191607488-07213e86-6359-4e5c-8d78-87972c23705f.png)

**Outline (please complete the following information):**
- Install: self hosted v0.66.1
- Version: docker image `outlinewiki/outline:0.66.1`

**Desktop (please complete the following information):**
 - OS: MacOS 12.6
 - Browser: Firefox 
 - Version: 105

**Comment by adityash1** [comment]
@tommoor as he suggested we should build a toggle for embeds. default is no embed. and each embed should have something like a floating button to enable embed. What you think?

**Comment by tommoor** [comment]
That's the ideal end scenario, right now we're still reliant on encoding all state in a reversible way in markdown so it's either dependent on #3000 or there needs to be encoded in the markdown a way of differentiating between an embed and a plain link, perhaps using the title attribute.
