### ISSUE TITLE
Add search option to "Only search titles"

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4192]
Sometimes you know you're looking for something in the title and it's useful to quickly whittle down the search results.

**Comment by adityash1** [comment]
I would like to work on this issue.

Should i make a toggle like this ?
![2022-11-15_00-20](https://user-images.githubusercontent.com/65771169/201742015-033b3767-7938-4993-92a0-d3e59292198f.png)

**Comment by tommoor** [comment]
Could try that approach, yep. I think the default Switch size is a bit large for this location though so probably want to shrink it a little.

**Comment by adityash1** [comment]
> Could try that approach, yep. I think the default Switch size is a bit large for this location though so probably want to shrink it a little.

if we just pass a one more prop to the component something like `searchOnlyTitle` and our document showing component will show results accordingly. It'll still fetch all results, but will show only those with query in title... .  is this approach okay ?

**Comment by tommoor** [comment]
We should build this properly with the filtering happening on the backend. There is already an api endpoint for this `documents.search_titles` so the main change is to hit the other endpoint.
