### ISSUE TITLE
Add user avatars in author search dropdown

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4193]
When users have similar names the avatars are useful to quickly distinguish, we use them everywhere else so they should be here too.

**Comment by adityash1** [comment]
@tommoor can I work on this issue as my first open source contribution ?

**Comment by tommoor** [comment]
Go for it

**Comment by adityash1** [comment]
> Go for it
![2022-11-04_19-48](https://user-images.githubusercontent.com/65771169/199997735-a70f232a-dbfe-4257-9733-0e289956c088.png)

is this ok ?

**Comment by tommoor** [comment]
You should create a pull request, I can't comment on random branches 😄
