### ISSUE TITLE
Mermaid.js diagrams don't work with the dark theme

### ISSUE THREAD

**Issue by not7cd** [outline/outline#4195]
**To Reproduce**
1. Create mermaid diagram
2. Select dark theme for outline

**Expected behavior**
Mermaid diagram changes the text color to white

**Screenshots**
![image](https://user-images.githubusercontent.com/4332632/193075907-52bf428f-d8d7-4dcd-8dfc-6217797736d3.png)
![image](https://user-images.githubusercontent.com/4332632/193076004-6963cc04-4774-43e5-84dc-9ca95473ff93.png)

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.66.1

**Desktop (please complete the following information):**
 - OS: linux
 - Browser Firefox
 - Version 103

**Comment by not7cd** [comment]
How hard it would be to pick this up @tommoor?

**Comment by tommoor** [comment]
Should be straightforward – most likely just CSS rules
