### ISSUE TITLE
Onboarding document

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#420]
Right now users land into an empty Outline without any content. We could at least include a sample document with some guiding content on how to use the product and for what.

Stuff to include:

- Lists
- Markdown
- Image uploads (drag&drop)
- Code blocks (e.g. sample API calls)

**Comment by tommoor** [comment]
I'd also like to change the default collection name from being the team name which doesn't really set the right expectations. Even just "general" the same as Slack would probably be better.

Thoughts?

**Comment by jorilallo** [comment]
I'm ok with "general"

**Comment by tommoor** [comment]
Or we could make it explicitly "Onboarding" and have more than one doc in there 💁 ?
