### ISSUE TITLE
Dark theme should have different strikethrough text background

### ISSUE THREAD

**Issue by vgwidt** [outline/outline#4200]
Dark theme uses the same text background on strikethrough text as light mode.  Dark mode should have its own background color to reduce contrast.

As of now, strikethrough text looks like this, with the background set as "slateLight" whether in light or dark mode:
![image](https://user-images.githubusercontent.com/49006240/193380257-9d271147-fefe-4d9c-b695-b5b368305ea1.png)

I think it should look more like this, using slateDark as the text background when in dark mode:
![image](https://user-images.githubusercontent.com/49006240/193380834-ae8ea7cc-830e-43b8-8861-86003dfcd311.png)

**Comment by tommoor** [comment]
Oh, there should be no background at all in either – that's a recent regression.

**Comment by vgwidt** [comment]
Oh I see, I do vaguely remember it looking different but assumed the background was a new stylistic choice.  If that's not the case, no background sounds great to me.

**Comment by vgwidt** [comment]
Oh I see, I do vaguely remember it looking different but assumed the background was a new stylistic choice.  If that’s not the case, no background sounds great to me.



2022/10/01 12:05、Tom Moor ***@***.***>のメール:

﻿

Oh, there should be no background at all in either – that's a recent regression.
