### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#423]
Slack style webhooks would be cool for getting updates on new and updated documents. I think we could use the types we have on the API to push these with the API payload. Would probably need task queue to be added so that we don't slow down the application.

**Comment by tommoor** [comment]
Started collecting thoughts: https://www.getoutline.com/doc/webhooks-4yJ8H6zPkx

**Comment by MatheusRV** [comment]
This was cancelled?

**Comment by tommoor** [comment]
Yes. The issue has been here for 3 years and has garnered little interest, so it's cancelled for now.

**Comment by maurxce** [comment]
Are there any updates to this?

**Comment by tommoor** [comment]
Webhook support was added 1.5y ago https://github.com/outline/outline/releases/tag/v0.65.0

**Comment by maurxce** [comment]
But does that include slack style webhooks? I couldn't get it to work myself ([see my discussion](https://github.com/outline/outline/discussions/6133))

**Comment by tommoor** [comment]
The webhook payloads are unique to Outline so they cannot be used with another product without a specific integration I'm afraid. This is very typical of any products' webhooks.
