### ISSUE TITLE
[dev-env] Starting from scratch fails due to sequelize migrations not evaluating PGSSLMODE

### ISSUE THREAD

**Issue by jovelromeo** [outline/outline#4236]
When running the development environment for the first time the migrations fail due to 

**To Reproduce**
1. clone the repo
2. copy .env.example to .env
3. change SECRET_KEY and UTILS_SECRET with valid values
4. Uncomment `# PGSSLMODE=disable`
5. Run `make up`

**Expected behavior**
The project should start

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: fresh git clone
- Version:  https://github.com/outline/outline/commit/1a88cb9d086c1486d7699f81a8230ff1d29ae1d5

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser N/A
 - Version N/A

**Mobile (please complete the following information):**
 - Device:N/A
 - OS: N/A
 - Browser N/A

Changes proposed are the following:
1. Change server/config/database.json to server/config/database.js
2. Adjust database.js to be a js and evaluate env variable just as the original connection.
3. Change .sequelizerc  `[..]'config' = path.resolve('s[..]` to use database.js instead of database.json

```
diff --git a/.sequelizerc b/.sequelizerc
index aa05bd02..90cb13ff 100644
--- a/.sequelizerc
+++ b/.sequelizerc
@@ -3,7 +3,7 @@ require('dotenv').config({ silent: true });
 var path = require('path');
 
 module.exports = {
-  'config': path.resolve('server/config', 'database.json'),
+  'config': path.resolve('server/config', 'database.js'),
   'migrations-path': path.resolve('server', 'migrations'),
   'models-path': path.resolve('server', 'models'),
   'seeders-path': path.resolve('server/models', 'fixtures'),
diff --git a/server/config/database.json b/server/config/database.json
deleted file mode 100644
index c9ad6e63..00000000
--- a/server/config/database.json
+++ /dev/null
@@ -1,23 +0,0 @@
-{
-  "development": {
-    "use_env_variable": "DATABASE_URL",
-    "dialect": "postgres"
-  },
-  "test": {
-    "use_env_variable": "DATABASE_URL_TEST",
-    "dialect": "postgres"
-  },
-  "production": {
-    "use_env_variable": "DATABASE_URL",
-    "dialect": "postgres",
-    "dialectOptions": {
-      "ssl": {
-        "rejectUnauthorized": false
-      }
-    }
-  },
-  "production-ssl-disabled": {
-    "use_env_variable": "DATABASE_URL",
-    "dialect": "postgres"
-  }
-}
\ No newline at end of file

```

**Comment by tommoor** [comment]
Did you want to submit a PR for this?
