### ISSUE TITLE
Ability to duplicate documents into a different collection

### ISSUE THREAD

**Issue by apoorv-mishra** [outline/outline#4244]
Currently, a document can't be duplicated into a collection different than the one it's already in. This capability needs to be supported for top level documents(non-nested docs).

**Comment by thenanyu** [comment]
Offering a strong opinion here — I know we're working on personal drafts. So any clone action should clone to that zone and the user can subsequently move it wherever they have permission to.

**Comment by apoorv-mishra** [comment]
Makes sense. I believe asking to clone into a collection right away might leave users with a mild frustration by _getting in the way_. Better to clone it as a personal draft and once the user feels like it's ready to be published/moved into a collection, they could do it. Also, technically, it won't require any UX shifts in the duplication flow, which is even better!

Thoughts @tommoor ?

**Comment by tommoor** [comment]
Definitely down for less UI here, makes this issue very easy once collection-less drafts is merged too

**Comment by tommoor** [comment]
Closed in favor of #4708
