### ISSUE TITLE
PDF Export

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4270]
Tracking issue for implementing PDF export, we now have many more foundations in place to build ontop of – including generating HTML with CSS on the server for documents/revisions already.

**Comment by tommoor** [comment]
PDF export for individual documents is now implemented for Outline cloud, this issue will be closed once bulk export is in place as well.

**Comment by ovizii** [comment]
It would have been nice to state this somewhere in the changelog. https://www.getoutline.com/changelog 

I read that PDF export is available and couldn't find it on my self-hosted instance. Anyway, I can print to a PDF printer, just wanted to point out that the fact that it is only available for enterprise + cloud instances should be pointed out to avoid people wasting time or opening issues about this.

**Comment by tommoor** [comment]
Thanks for the feedback. The changelog on getoutline.com is only relevant for the cloud hosted version, for the community changelog it's best to look at https://github.com/outline/outline/releases

**Comment by OctumSven** [comment]
> PDF export for individual documents is now implemented for Outline cloud, this issue will be closed once bulk export is in place as well.

I couldn't find any information about bulk export in the release notes or the change log (2 MAY 2023). Was this already implemented but not mentioned anywhere, or is this feature tracked somewhere else?

Thanks for the information :-)
