### ISSUE TITLE
Add emoji picker for document title

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4274]
Currently we have a hidden feature where you can give a document an emoji that will appear in the favicon and elsewhere by adding it as the first character in the title followed by a space. This is too hidden – we should convert it to an actual emoji picker, probably [Emoji Mart](https://missiveapp.com/open/emoji-mart) with a subtle button next to the title on hover to choose an emoji when there isn't one.

To make the migration easier we could continue to store the emoji character in the title and strip it when displayed .e.g in the document itself.

**Comment by AdrianFahrbach** [comment]
Would be great if this also applies to the collection icons.
The uniform look of the outline icon pack is great, but I think it is missing a lot of "topics" that are covered by regular emojis.

**Comment by tommoor** [comment]
Feels like a natural follow up

**Comment by patzm** [comment]
Don't put me in a ⚰️ please 😉 🙏

**Comment by patzm** [comment]
still sounds like a great idea.

**Comment by tommoor** [comment]
Urgh, yea totally – we really got stuck with the migration on this one, it was a gnarly beast particularly for cloud-hosted Outline 😢
