### ISSUE TITLE
Allowed Domains troubles in self-hosted

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4275]
### Discussed in https://github.com/outline/outline/discussions/4083

<div type='discussions-op-text'>

<sup>Originally posted by **Dan6erbond** September  7, 2022</sup>
I have Outline hosted in a Kubernetes cluster, and configured with Authentik OIDC for SSO. So far this has worked well with @gmail.com Users, until I noticed that some colleagues who wanted to access with @gmx.ch, etc. were out of luck. Based on my research I then tried to add those domains to the Allowed Domains setting in Outline, but logging in with those users still doesn't work. Is this expected behavior as Outline's SSO might not cover custom OIDC providers or something else?</div>

**Comment by not7cd** [comment]
Maybe in the next patch more verbose logging could be added? Because it is currently unknown to me, why those errors are being thrown. In my case, I'm running a small operation for a student club and we have logging through authentik.io + discord.

**Comment by af2005** [comment]
This has troubled us for the last 5 hours, as well.  If you invite those new emails (email smtp not required), they can login. You can invite them under settings -> members -> top right "invite"

They won't receive an email, but can login from that point in time, as outline now recognises them as part of the "team" (at least that is what we think is happening)

**Comment by tommoor** [comment]
Take a look at `outlinewiki/outline:0.67.0-pre.1` and see if it resolves your issue.

**Comment by not7cd** [comment]
I can confirm that it works
