### ISSUE TITLE
Change styling on completed tasks

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4283]
The strike-through is actually kind of annoying in usage as it makes it very hard to read. We either need to remove or _ideally_ draw it in a fainter way.

<img width="426" alt="image" src="https://user-images.githubusercontent.com/380914/195499912-0ccc58d1-4802-49a9-bc26-7b703da14808.png">

**Comment by Nicicalu** [comment]
I agree, it can make it hard to read

**Comment by Nicicalu** [comment]
I think I'd prefer something like this:
![](https://i.imgur.com/3lsrT6e.png)
Most markdown editors I've used didn't change the text of checked tasks, but I think it's better like this than without any changes.
