### ISSUE TITLE
Refine server side validations

### ISSUE THREAD

**Issue by apoorv-mishra** [outline/outline#4284]
Currently, different types of validations for a given API are scattered within the handlers as a bunch of assertions, added on ad-hoc basis. This ends up making handlers _fat_ and cluttered. It'd be good if validations could be pulled out and be handled more _declaratively_, in one place, possibly through a middleware. It'd be worth exploring [Zod](https://github.com/colinhacks/zod) for this purpose.

**Comment by tommoor** [comment]
Now we're talkin'. 

I think we should write our own middleware based on zod, as you say – but this express one might provide some inspiration:
https://github.com/andrewkeig/express-validation
