### ISSUE TITLE
no keyboard operation possible to choose an item a recent search term list

### ISSUE THREAD

**Issue by bmm-alc** [outline/outline#4286]
**To Reproduce**
1. press `/` or `t` to trigger the redirect to page `/search` from any page
2. press key ⬇️ on the keyboard to choose an item from the recent search term list under the search field
3. nothing happens and I need to use my pointer to click on an item :)

**Expected behavior**
* It should be possible to navigate through the item, using keys ⬇️ and ⬆️ and there should be a visual hint to show the selected item
* Pressing key enter on a selected item should trigger the search
* From the top entry it should be possible to go back the search bar if I press ⬆️
* I don't know what would be the sensible behaviour when there is already some text in the field, should it be selected, and where the cursor should be (beginning or end of the string)

**Screenshots**
n/a

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 0.63

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: firefox
 - Version: 103

**Comment by MihirGH** [comment]
Hi, I would like to help with the issue. I saw the code in `app/scenes/Search/Search.tsx` file and we are using `ArrowKeyNavigation` component to handle the arrow key navigation when user has entered the query and presses the arrow down for the first time on search input but I am not able to visualise how same thing can be done for recent searches. Any input will be appreciated -  @tommoor  @thenanyu

**Comment by dkoosis** [comment]
Looking for a _good first issue_ and found this, which I think works as designed and can be closed.

If I understand, @bmm-alc, you are describing this starting state:
![outline-searches](https://user-images.githubusercontent.com/1538542/235038264-78320d2f-4dd3-4fce-a305-1a1610d9fe32.png)

You expect that it should be possible to navigate between the search input field and the recent searches using the arrow keys (⬇️ and ⬆️), but that does not work. 

That makes sense. The usual way to change focus is by pressing the **tab** key. In the example above, I can change focus from the search field to **my most recent search** by pressing **tab**.  I can execute the search by pressing the space bar. This works correctly for me on Windows/Chrome and Linux/Chrome, but I did not test it on your configuration of Linux/Firefox.

Does that sound correct?  If so, this issue can be closed.

**Comment by tommoor** [comment]
You're not wrong, however I think the expectation here was that up/down arrows would work also – similar to how they do on the search results page. We have a `ArrowKeyNavigation` component to help with this.

**Comment by dkoosis** [comment]
I see. Like this:
![outline-search-results](https://user-images.githubusercontent.com/1538542/235324881-ca2c3b7c-3218-4c31-95ba-c3cda33fa71e.png)

I'll take a peak.

**Comment by mghlb** [comment]
I wanted to get started on this, but I get this error, should this migration be done on my end?

![Screenshot from 2023-08-29 23-38-02](https://github.com/outline/outline/assets/79663822/98cc90e6-1d98-41cf-bd97-8205c8d24584)

**Comment by tommoor** [comment]
It’s related to the last change that was merged on main - they should run automatically in development. Best thing to do is just run an earlier commit first so the migrations run.

**Comment by mghlb** [comment]
Both frontend and backend compiled fine:

![Screenshot from 2023-08-30 01-53-43](https://github.com/outline/outline/assets/79663822/14e33f00-59ad-48a0-a711-bb25ec5a7626)
![Screenshot from 2023-08-30 01-54-26](https://github.com/outline/outline/assets/79663822/ecf879ad-ccf3-4a40-bc55-49a4215090c9)

But I can't access any of these URLs.
