### ISSUE TITLE
Show team logo on shared documents

### ISSUE THREAD

**Issue by apoorv-mishra** [outline/outline#4291]
> Can be a follow up PR but I want to use this to also show the logo at the top of the left sidebar on shared documents such as: https://wiki.generaloutline.com/s/770a97da-13e5-401e-9f8a-37949c19f97e

[Ref](https://github.com/outline/outline/pull/4285#discussion_r996248531)

**Comment by apoorv-mishra** [comment]
Where to put the logo? Currently, looks like there isn't any space to accommodate it.

![Screenshot from 2022-10-15 11-08-51](https://user-images.githubusercontent.com/15694566/195970907-ec5dd960-a61f-486a-b53b-1f99bf221318.png)

**Comment by tommoor** [comment]
Above the search in the same manner as when logged in initially with the team name, sound good @thenanyu ?
