### ISSUE TITLE
Preload bundles to improve first load perf

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#430]
We could prefetch main bundles from the SSR marketing pages. Not sure what's the best way to pull filenames but at least [manifest plugin](https://www.npmjs.com/package/webpack-manifest-plugin) could be used.

https://css-tricks.com/prefetching-preloading-prebrowsing/#article-header-id-2

**Comment by tommoor** [comment]
closed by https://github.com/outline/outline/pull/519
