### ISSUE TITLE
Just Opening documents is causing them to be updated (to an old version)

### ISSUE THREAD

**Issue by ChuckJonas** [outline/outline#4306]
I setup outline for my team a few months ago (we are paying for the hosting).  I imported a bunch of documents from our old system (markdown files).

Since then, I have no really spent much time in outline.  However, the other day, I was browsing our content and about 50% of the time I open a file, it reverts any changes that other have made.   It says that I have "saved" it, even though I absolutely did not click the save button!

<img width="248" alt="Client_Check-in_Meeting_Procedure_-_Callaway_Cloud_Consulting" src="https://user-images.githubusercontent.com/5217568/196201860-c2993e6a-94ab-4feb-833a-371ef232e06d.png">

My hunch is that this is only happening on the files that I imported (doesn't happen on every file), but it extremely unacceptable that I cannot browse the teams documentation without overwriting there changes!

**Comment by tommoor** [comment]
> it reverts any changes that other have made

This is particularly concerning, are you confident that changes are being reverted upon opening the document?

**Comment by ChuckJonas** [comment]
99.9%...  I reproduced it about 8 times in a row, but it seems to happen in the background after opening the doc and only on some documents.

My initial hunch was that maybe I had some pending changes staged, and then the act of opening the document likely triggers some DB transaction (in the form of view tracking?), and those pending changes were getting applied...

However, my "Drafts" collection is empty...

I'm not sure how many more times I will be able to reproduce (seems to be based on some very specific state), but I'm happy to jump on a call to debug if that's helpful...

**Comment by ChuckJonas** [comment]
@tommoor seems like this issue is more widespread than I first thought... We're seeing similar behavior with other users.   Do you have a second to chat?  This is a pretty critical issue

**Comment by tommoor** [comment]
Spoke with @ChuckJonas and we got to the bottom of this, there are no code changes to make.

**Comment by JustDoItSascha** [comment]
@tommoor What was the outcome of this? Because I think my issue is maybe related to this -> #5770 .
