### ISSUE TITLE
"malformed URI sequence" prevents saving

### ISSUE THREAD

**Issue by DDoerner** [outline/outline#4318]
I've lost work multiple times due to this. An erroneous state is reached and afterwards no further changes are saved. The user however receives no notice about this and I only saw the problem after looking into the console.

**To Reproduce**
1. Create a new page
2. Add a list with multiple levels and have each entry start with an emoji
3. Replace an emoji on a lower level (not first) with another emoji (either from the web or an emoji in the doc)
4. The following error pops up in the console only
5. No changes from now on will be saved in this document

`Uncaught URIError: malformed URI sequence`

**Expected behavior**
At least a message informing the user that the file can't be saved any longer

**Screenshots**
![image](https://user-images.githubusercontent.com/18138239/196981282-7861146c-b643-41e2-83a5-aa9f5d6b5e32.png)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.66.1

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 105.0.3

**Comment by tommoor** [comment]
Will check it out, there is an upstream error that needs fixing but previously we had a handler that would warn and force a page reload when this occurred. Perhaps that's not longer working for some reason

[#character ](https://github.com/outline/outline/pull/3250)

**Comment by tommoor** [comment]
Testing, this always produces the expected toast error…
 
![image](https://user-images.githubusercontent.com/380914/197398271-6f22de5a-0d52-4155-9274-30e712f8cf8c.png)

**Comment by DDoerner** [comment]
Just tested and it might be due to the browser. The toast error appeared when testing in Chrome, but not in Firefox.

**Comment by tommoor** [comment]
Another temporary workaround is to insert emoji through the `:` popup menu, it won't trigger the error.

**Comment by tommoor** [comment]
Looks like a fix might _finally_ have landed upstream for this today https://github.com/dmonad/lib0/releases/tag/v0.2.69

**Comment by tommoor** [comment]
Upon testing the upgrade does not in fact fix this issue
