### ISSUE TITLE
Submit to Slack Application Directory

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#432]
Not preventing OAuth login but should do sooner than later for deeper integration and notifications (#63)

**Comment by tommoor** [comment]
Blocked by https://github.com/outline/outline/issues/63

**Comment by tommoor** [comment]
@jorilallo would you be able to resubmit some time this week or pass the baton to me somehow so I can take care of it? 😄

**Comment by tommoor** [comment]
Resubmitted 🤞

**Comment by tommoor** [comment]
We're live.
