### ISSUE TITLE
Highlight correct heading in Contents sidebar of a document

### ISSUE THREAD

**Issue by ChristinaTromp** [outline/outline#4333]
In a document in a collection, the Contents sidebar within the document often highlights in blue the previous section rather than the one I'm currently in. In the case of very short documents with 3 headings, the Contents sidebar often even highlights the first section when I'm in the third. 

In long documents where placement of text matters, this could cause confusion as to where I am, and make me think that my text is placed in the wrong section. 

**To Reproduce**
1. Create any document with 3 headings and some text below each heading
2. Click on the Third heading in the Contents sidebar
3. Notice that although you are taken to the third heading section in the document, the previous heading is highlighted in the Contents sidebar

**Expected behavior**
I expect the Contents sidebar to highlight the heading of the section I'm in, when I am at the heading or in the content below that heading. 

**Screenshots**
![Screen Shot 2022-10-25 at 10 49 27](https://user-images.githubusercontent.com/25814064/197729427-d41f0844-3cb5-4644-a76e-f8657efa81d7.png)
![Screen Shot 2022-10-25 at 10 48 58](https://user-images.githubusercontent.com/25814064/197729452-13310344-e9bf-443b-b77a-d146e5fb498f.png)

**Outline:**
- Install: self hosted
- Version: not sure, but was created two weeks ago.

**Desktop:**
 - OS: Mac 10.12.6 
 - Browser Chrome
 - Version 103.0.5060.134

**Comment by tommoor** [comment]
The behavior looks correct based on your screenshots, the section that is highlighted is the top-most heading that is visible on screen.

**Comment by ChristinaTromp** [comment]
Hi @tommoor 

Thanks for the response and clarifying. I logged it as a bug because I and my team assumed this was a mistake. Based on your feedback, it should be a feature request or design improvement suggestion. 

If you use Google Docs or other editing tools, they highlight the section that you're in, and the section you're in is defined by where your cursor is. I find that intuitive and really useful. 

For another screenshot for context, in Outline, even if the previous heading is not visible on the page anymore, it is still highlighted when I'm in the next section:

![Screen Shot 2022-10-25 at 14 10 06](https://user-images.githubusercontent.com/25814064/197769709-1d9e85b1-09bb-4cf5-b7f9-3f4c25fce554.png)

**Comment by tommoor** [comment]
I must admit, this behavior would be an improvement 😄

**Comment by adityash1** [comment]
@tommoor we're using `getBoundingClientRect()`  in `app/scenes/Document/components/Contents.tsx` to set our activeslug until a heading section goes off completely from viewport. but i can't figure out how can we override/set our activeslug when user is editing a heading section. any suggestions?
