### ISSUE TITLE
Older exports stuck/hanging & can't delete

### ISSUE THREAD

**Issue by ReessKennedy** [outline/outline#4344]
I think the screenshot explains it. I just successfully downloaded a backup of my wiki but noticed that the requests I made months ago never completed & there is no method for me to stop these requests or delete them from the UI. Any ideas? 

<img width="456" alt="Screen Shot 2022-10-26 at 12 11 28 PM" src="https://user-images.githubusercontent.com/3970267/198078941-f5e172be-14a1-462c-a14a-8cdb201f040f.png">

**Comment by tommoor** [comment]
Your best bet is to just delete these rows from the database. Some fixes have been made to better handle errors in file export and prevent the app getting into this state in the future.
