### ISSUE TITLE
API calls to append text to a document fail if the document is being edited, but API returns 200

### ISSUE THREAD

**Issue by tsb-adrian** [outline/outline#4353]
As mentioned in https://github.com/outline/outline/pull/3647 we can't update collaborative documents with the API. This means critical data can be lost in a black hole without anyone realising. Would it be possible for a fix, or at the very least an error for when it fails to update?

**To Reproduce**
1. Edit a document via the UI.
2. Append text to the same document via the API.

**Expected behavior**
The text should be appended.

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: Ubuntu and Windows
 - Browser: Vivaldi, Chrome, Firefox

**Comment by max-mykhailenko** [comment]
This problem is relevant for me
