### ISSUE TITLE
Data directory incompatible with Postgres 15

### ISSUE THREAD

**Issue by thomasgriffin** [outline/outline#4388]
I regularly check my Outline install to ensure to [details from my tutorial on self installing and hosting Outline](https://thomasgriffin.com/how-to-install-the-outline-knowledge-base-wiki-on-ubuntu/) work properly. In the most recent automatic update to my self-hosted Outline install, I noticed a 502 error afterward. As I inspected the logs, I noticed this error being output:

```
postgres_1  | 2022-11-06 12:47:05.372 UTC [1] FATAL:  database files are incompatible with server
postgres_1  | 2022-11-06 12:47:05.372 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 14, which is not compatible with this version 15.0 (Debian 15.0-1.pgdg110+1).
```

I made a couple of simple fixes for this, such as pegging the Postgres image to a specific tag in my `docker-compose.yml` file:

```
postgres:
    image: postgres:14
```

But, I thought it might be good to report this in the event someone updates Postgres to another version in the future, and it breaks the Outline install.

**To Reproduce**
1. Shut Docker down and attempt to update the Outline install, e.g. `docker pull postgres`
2. Boot Docker back up, and notice the errors for connecting with Postgres in the Docker logs.
3. Peg Postgres to a specific version based on what is in the Docker logs, e.g. `docker pull postgres:14`
4. Boot Docker back up, and notice the errors have now gone away and the Outline install is working again.

**Expected behavior**
Outline should work on the latest version of Postgres.

**Screenshots**
https://a.supportally.com/i/sAJDe9

**Outline:**
- Install: self hosted
- Version: v0.66.2

**Comment by tommoor** [comment]
Hi Thomas, Outline is compatible with Postgres 15 but you’d need to go through some sort of migration process if you wish to move data between major Postgres versions. 

That’s out of scope for the Outline project.

**Comment by thomasgriffin** [comment]
@tommoor Do you have any recommendations for this or any resources to point to? I can't imagine it to be a good thing for people to be forever stuck on a specific version of Postgres once they have Outline installed and setup.

**Comment by tommoor** [comment]
I would use the official utilities https://www.postgresql.org/docs/current/pgupgrade.html
