### ISSUE TITLE
Outline is marking viewed pages as being edited

### ISSUE THREAD

**Issue by matjaz-creatim** [outline/outline#4404]
As Outline administrator in our organization, I'm getting lots of strange notices lately, that some documents have been changed (which should not be). Upon investigation, I found that pages are being "edited" just by opening them, without modifiying them in any way. 
No edit button has been pressed, neither has the document been moved anywhere in the structure.

This has been happening for the last couple of days, not all views result in an edit, but many do.

This "editing" has been initiated by many different users in the organization, not just one.

**Comment by matjaz-creatim** [comment]
This bug does not fit the template.

**Comment by tommoor** [comment]
We have applied a fix to your account, I recommend contacting hello@getoutline.com for hosted issues in the future 🙏
