### ISSUE TITLE
Profile photo URL in the top left corner doesn't change after uploading new profile photo.

### ISSUE THREAD

**Issue by dom6770** [outline/outline#4410]
After uploading a new profile photo in the profile section and heading back to the main page, the new profile photo is only shown in the bottom left spot. In the top left title spot, it's still showing the old profile picture (html img src still showing old URL). Recreating the docker container or flushing browser cache didn't solve the issue.

**To Reproduce**
1. Upload profile photo
2. Go to main page
3. Top left URL for profile photo is still old URL & Bottom left URL for profile photo is new URL

**Expected behavior**
After uploading a new profile photo, the <img src=$URL> in the <div class=SidebarButton__Title-sc-1z06wfn-0"> (top left of the webpage) should point to the new URL.

**Screenshots**
![image](https://user-images.githubusercontent.com/11932291/201390549-94d6f2cb-51a9-47cf-8b45-fd06fe2c43d0.png)

**Outline (please complete the following information):**
- Install: self hosted w/ MinIO
- Version: 0.66.3

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser Google Chrome 107 & Firefox 106

**Mobile (please complete the following information):**

**Comment by tommoor** [comment]
Hi Dominik, this is the team logo in the top left, not the profile picture – you update through **Settings -> Team -> Details**

**Comment by cchord001** [comment]
I have the same problem version as 0.66.1
