### ISSUE TITLE
Viewed by pop up shows under an image

### ISSUE THREAD

**Issue by not7cd** [outline/outline#4425]
Viewed by is hidden by a picture on hover.

**To Reproduce**
1.Create an image in the first line of the document
2. Hover over "read by"

**Expected behavior**
Pop up _viewed by_ over the image

**Screenshots**
![image](https://user-images.githubusercontent.com/4332632/201553779-7cb9f562-464a-4ce9-ac89-1ac911c04490.png)

**Outline (please complete the following information):**
- Install: self hosted
- Version: [v0.67.0-pre.1](https://github.com/outline/outline/releases/tag/v0.67.0-pre.1)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 103

**Comment by tommoor** [comment]
Ah, this popover will no longer exist in the next version but I'll check the others 👍

**Comment by tommoor** [comment]
Double checked, fixed in the next release as this popover no longer exists and the rest work okay.

**Comment by not7cd** [comment]
Thanks!
