### ISSUE TITLE
Problems with combination of italic and bold

### ISSUE THREAD

**Issue by tommoor** [outline/outline#443]
Noticed that if you have italic and then bold in the same paragraph the formatting gets broken on save. Amazed I haven't seen this before. Likely because italic uses * and bold **

**Comment by jorilallo** [comment]
Interesting. I made changes to this some time ago but it was just to check for trailing/leading whitespace

**Comment by tommoor** [comment]
Ah, that probably broke it actually italic + bold = `***blah***`

**Comment by jorilallo** [comment]
hmms, is that even markdown?

**Comment by tommoor** [comment]
I was thinking a quick fix would be to use the underline syntax for italic instead. However that would still fail because of the white space rule: `_**blah**_` 

I'm not sure how valid it is technically but we probably want to allow it rather than forcing only one formatting style at a time?

**Comment by jorilallo** [comment]
I always used `**` for bold and `_` for italic to make it easier for myself. I think it would be ok to do that in serialization. For markdown shortcuts, I highly doubt anyone does `***`, I never seen that

**Comment by tommoor** [comment]
Should have taken stalebot more seriously 😆

**Comment by tommoor** [comment]
Fixed as part of https://github.com/outline/rich-markdown-editor/pull/150
