### ISSUE TITLE
Line numbering issue for code blocks

### ISSUE THREAD

**Issue by NPCDW** [outline/outline#4440]
When editing a code block, the line numbers of another code block disappear

**To Reproduce**
1. Click on 'Edit'
2. Edit a code block, type 'Space' and 'Backspace'

**Expected behavior**
Type in one place, and the content in other places will not change

**Screenshots**
![msedge_pP1y8yLQQu](https://user-images.githubusercontent.com/32638459/202395982-249f3d50-0c93-487d-af27-b142e51cc848.gif)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.67.0-pre.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 107.0.1418.42

**Comment by tommoor** [comment]
Thanks, you can disable line numbers in the preferences until this is fixed

**Comment by tommoor** [comment]
Trying to reproduce and unable to at this time 😢

**Comment by NPCDW** [comment]
I upgraded from version 0.66.2 to version 0.67-pre, and version 0.66.2 is still displayed, but it already has the function of displaying line numbers. I don’t know if it has something to do with it

![image](https://user-images.githubusercontent.com/32638459/202885477-b86dbbe4-48ae-4fd6-a346-ce1e3a031ab6.png)

![image](https://user-images.githubusercontent.com/32638459/202885669-0247f418-7fd0-40fe-84c6-4719d7559498.png)
