### ISSUE TITLE
Can't log with gitlab groups-scoped App

### ISSUE THREAD

**Issue by loranger** [outline/outline#4441]
I try to use Gitlab OIDC auth on my company's groups-scoped gitlab, but fail.
It's not clear what urls I am supposed to use in the .env ([doc](https://app.getoutline.com/s/770a97da-13e5-401e-9f8a-37949c19f97e/doc/gitlab-GjNVvyv7vW) does not cover gitlab groups) and waht url I'm supposed to configure my gitlab group Applications.

I tried to get help [from discussion](https://github.com/outline/outline/discussions/4436) but my issue seems uninteresting

I did follow [the doc](https://app.getoutline.com/s/770a97da-13e5-401e-9f8a-37949c19f97e/doc/gitlab-GjNVvyv7vW) and setup my env like this:

```
# GITLAB Auth

OIDC_CLIENT_ID=12xxxxxxxxxxx34
OIDC_CLIENT_SECRET=56xxxxxxxxxxxxxx78
OIDC_AUTH_URI=https://gitlab.com/oauth/authorize
OIDC_TOKEN_URI=https://gitlab.com/oauth/token
OIDC_USERINFO_URI=https://gitlab.com/oauth/userinfo
OIDC_USERNAME_CLAIM=username
OIDC_DISPLAY_NAME=GitLab
OIDC_SCOPES=openid email
```

I also added a [new Application in our gitlab](https://docs.gitlab.com/ee/integration/oauth_provider.html#group-owned-applications) as found out in https://github.com/outline/outline/discussions/3450

![](https://user-images.githubusercontent.com/6014/202177047-db02b0ce-6769-4874-a592-ee950fa2642a.png)

But I can't make it work.
Whatever I use as callback url or OIDC_USERNAME_CLAIM, I always end up with a The redirect URI included is not valid. error.

![](https://user-images.githubusercontent.com/6014/202178834-4dfc9612-cc87-4a8e-b349-ac78f7b5ac0f.png)

It may be a gitlab group issue, but I can't figure out what I miss.
Can I get some clue regarding the way to use gitlab groups-scoped auth with outline, please ?

**Outline (please complete the following information):**
- Install: self hosted
- Version: docker `outlinewiki/outline`

**Desktop (please complete the following information):**
 - OS: macOS 13.0.1
 - Browser Firefox
 - Version 109

**Comment by MDXDave** [comment]
What redirect uri is included in the url?

**Comment by loranger** [comment]
It's the one specified as the callback url from the Application page :
`https://gitlab.com/oauth/authorize?response_type=code&redirect_uri=http%3A%2F%2Foutline.xxxxxxxx.yyyyy%2Fauth%2Foidc.callback&scope=openid%20email&state=e306250de8aeba1234567890&client_id=fe06f2a554e09bec5e1234567890a135f087233221234567890`

**Comment by MDXDave** [comment]
The redirect uri in the url starts with http instead of http**S**.

**Comment by loranger** [comment]
You're right, I changed the URL variable from the .env file to match the url declared in gitlab and everything works fine.
As simple as this.

Thank you so much ! 👍🏻
