### ISSUE TITLE
Image upload failed (Minio) if Minio password contains symbol

### ISSUE THREAD

**Issue by thammawat-s** [outline/outline#4444]
When having symbol in  Minio password , image upload will fail.

**To Reproduce**

1. set Minio's password and AWS_SECRET_ACCESS_KEY  to contain symbol, for example,   minio#9999
2. try to upload an image.
3. Firebox Web Develop Tools (under network section) shows error response as "SignatureDoesNotMatch"

**Note**
I haven't tested Amazon S3, or others.

**Comment by tommoor** [comment]
I don't think we'll change anything here, best to change your secret key in this case.
