### ISSUE TITLE
Frontend should request updated user / team on load

### ISSUE THREAD

**Issue by tommoor** [outline/outline#448]
It's possible the team or user data will have been updated for a variety of reasons. We should make sure to load it fresh from the server on load of the app.

**Comment by jorilallo** [comment]
You mean from Slack's API?

**Comment by tommoor** [comment]
Just from our API. For example, you changed your profile on another machine or an admin updates the team details - right now you have to sign out and back in again for that information to be updated.

Just became apparent while working on the settings pages.

**Comment by jorilallo** [comment]
Ah, sounds good
