### ISSUE TITLE
Docker: "outlinewiki/outline:latest" pulls an installation of 0.66.2 even though the latest is outlinewiki/outline:0.67.0-pre.1"

### ISSUE THREAD

**Issue by nickk024** [outline/outline#4483]
I have the outline install up and running and in the preferences, it says I am two commits behind. I have also tried to use outlinewiki/outline:0.67.0-pre.1 as my image but that will also show 0.66.2 in preferences. Am i doing something wrong? Thank you!

**Comment by tommoor** [comment]
Nope, the version is wrong in prefs on this pre-release.
