### ISSUE TITLE
Allow using `/slash` commands anywhere on a line

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4487]
Changing the trigger is somewhat easy, we already have emoji insert for example that can be used anywhere on a line.

We need to also make sure that blocks can only be inserted where it will not break the schema, for example many things are not supported inside table cells currently. This may mean disabling/hiding some items depending on the current selection which previously was always a new blank paragraph.

**Comment by Mag1cByt3s** [comment]
this is something i am missing for some time already

**Comment by almereyda** [comment]
The case with nested blocks inside table cells is eventually eased by #5553 now.
