### ISSUE TITLE
Wrong versioning updating with docker compose

### ISSUE THREAD

**Issue by AlessandroSpallina** [outline/outline#4498]
Today I changed image version in my self-hosted docker-compose-based deploy, I stepped from v0.66.1 to v0.67.0-pre.1

After recreating the outline container I see that docker downloaded the correct image version, as follows: 
```bash
$ sudo docker images
REPOSITORY                  TAG            IMAGE ID       CREATED         SIZE
outlinewiki/outline         0.67.0-pre.1   31d5119b4296   2 weeks ago     501MB
```
and I can check that the outline container is using precisely that image, but when I go to check the version in the outline profile page I see a version mismatch, like the image 
![image](https://user-images.githubusercontent.com/10786872/204368014-d206497d-ea8a-429f-b31e-56650765f26a.png)

I also verified to have a brand new feature contained in the latest version, such as the history diff highlighting; for that reason, I'm pretty sure I have the right updated image version, have you forgotten the wrong version in the code you used to build the latest image? @tommoor

**Comment by tommoor** [comment]
Thanks, the internal version was incorrect on the pre-release – this cannot be addressed now it's out but the version will be correct in the real release.
