### ISSUE TITLE
open vulnerabilities

### ISSUE THREAD

**Issue by nbryant42** [outline/outline#4512]
There are a number of open vulnerabilities. Any chance you can simply run `npm_config_yes=true npx yarn-audit-fix`, this should hopefully not cause any issues

See https://github.com/antongolub/yarn-audit-fix

**Comment by nbryant42** [comment]
@tommoor, we're not done with this conversation yet.

**Comment by tommoor** [comment]
Updates for _specific_ dependencies are warranted and appreciated, general "please update dependencies" issues are not helpful to keeping the project on track. Thanks for understanding.
