### ISSUE TITLE
CSS class "active" sometimes missing for opened page in starred collection

### ISSUE THREAD

**Issue by af2005** [outline/outline#4513]
The css class "active" is not always added for an opened document.

**To Reproduce**
1. Create a collection (let's name it MYCOLLECTION)
2. Create a page inside the collection (let's name it NEWPAGE)
3. (optional) Create a child page of NEWPAGE (let's name it CHILDPAGE)
4. Star the collection
5. Close the "collection tree" in the sidebar 
6. Leave the "starred collections" open. 
7. Also make sure to expand the collection inside the starred collections (maybe it's also a bug, that it does not open the tree inside starred collections, see below)
8. (optional) Close the page tree of NEWPAGE, so CHILDPAGE is not shown anymore
9. Go to "HOME" (not the homepage of the collection), but the home on the very top in the sidebar
10. On HOME, click on NEWPAGE (e.g. in recently updated)

**Expected behavior**

_Possibility A: The tree of MYCOLLECTION was already expanded inside "starred collections". _
I expect the entry NEWPAGE being highlighted (css class "active" on the <a>), but it is not.
Curiously, the tree of NEWPAGE is now expanded, meaning the entry of CHILDPAGE is visible

_Possibility B:  The tree of MYCOLLECTION was NOT expanded inside "starred collections".
I expect the tree of MYCOLLECTION inside starred collections to open, alongside with a css highlight of NEWPAGE
Similar to above, after manually opening MYCOLLECTION, the tree of NEWPAGE has been expanded.

**Outline (please complete the following information):**
- Install: self hosted
- Version: [v0.67.0-pre.1](https://github.com/outline/outline/releases/tag/v0.67.0-pre.1)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome

**Comment by tommoor** [comment]
Hi, this sounds like expected behavior – it will be highlighted if you access it from starred, otherwise the regular location will be highlighted.
