### ISSUE TITLE
Why does Outline limit the subdomain length to 32 characters when AuthProviders allow > 32?

### ISSUE THREAD

**Issue by everettmorgan** [outline/outline#4524]
https://github.com/outline/outline/blob/fc9d685ef53b7863189e764796be863c86085fd3/server/models/Team.ts#L70

Long story short, when I created my default directory in Azure, it created a (pretty lengthy) subdomain for me automatically: `firstnamelastnamemaileprovider-onmicrosoft`. This prevented me from signing into Outline using my default tenant since y'all limit the subdomain length to 32 and Microsoft prevents changing it after initial creation.

I had to create an entirely new tenant with a shorter subdomain/domain combo, and BOOM, I could sign in.

Now, the question becomes, why does Outline limit the subdomain field to 32 characters when AuthProviders allow more? Seems like an arbitrary limit since the ceiling is 255. Any reason not to bump the limit up to the maximumm?

**Comment by tommoor** [comment]
This is aimed at the cloud hosted version, we don't want folks creating long subdomains. The limit could be limited in self-hosted, and this seems like a reasonable reason to do so 👍
