### ISSUE TITLE
Users with long names is outfit dropdown list

### ISSUE THREAD

**Issue by deolive** [outline/outline#4530]
Users with long names is outfit dropdown list

**To Reproduce**
1. Go to Settings->Members
2. Try change role user with very long name

**Screenshots**
<img width="803" alt="image" src="https://user-images.githubusercontent.com/7079517/205436878-720a12e8-7ff3-425a-9d75-6c313b7a43cf.png">

**Outline (please complete the following information):**
- Install:  self hosted
- Version: latest

**Desktop (please complete the following information):**
 - OS: MaxOs
 - Browser Chrome
 - Version 108

I think user name indropdown list is unnecessary

**Comment by tommoor** [comment]
Yea, these are super duper old – also have a very old confirm dialog. Will fix
