### ISSUE TITLE
Indent/Tab Not Supported -- Replacing With Spaces Causes Unexpected Formatting

### ISSUE THREAD

**Issue by mweth** [outline/outline#4534]
Similar posts:
https://github.com/outline/outline/issues/1750
https://github.com/outline/outline/discussions/2189

Background reading:  
https://daringfireball.net/projects/markdown/syntax#precode (Explaining why four spaces generates code)
https://bookdown.org/yihui/rmarkdown-cookbook/indent-text.html (showing potential solution using `|`.

When importing a document containing tabs, Outline will first attempt to disregard the formatting.  As a workaround, I have converted tabs to spaces.  This results in either disregarding the spaces or converting them to code blocks and code sections. 

To reproduce, import any markdown file containing spaces, such as:

Note: spaces converted to '.' below to make it easier to read.
(2) “Agency” means:
.....(A) When used with respect to the state government, any department, commission, committee, authority, board, or bureau thereof; and
.....(B) When used with respect to any political subdivision of the state government, any department, commission, committee, authority, board, or bureau thereof.
..........(i) This code section may be revised.
(3) “Another” means a person or persons other than the accused.

Outline will convert the above to a code block as follows:
2) “Agency” means:
```
(A) When used with respect to the state government, any department, commission, committee, authority, board, or bureau thereof; and
(B) When used with respect to any political subdivision of the state government, any department, commission, committee, authority, board, or bureau thereof.
(i) This code section may be revised.
```
(3) “Another” means a person or persons other than the accused.

A potential workaround is to convert the text section to a list, but that is not practical when working with statutes, industry standards, and similar technical documents that have their own numeric system built in, i.e. (A)-(1)-(a)-(i).  Copy/Paste of the same section _sometimes_ results in an accurate layout.  However, reposting the same section multiple times will result in seemingly random outputs -- some with tabbing, some without.  Here are some examples of pasting the exact same block into multiple documents:
![image](https://user-images.githubusercontent.com/20465873/205513260-4dc37758-2e37-49fd-87c2-9ce71029c892.png)
![image](https://user-images.githubusercontent.com/20465873/205513310-bdfa75f5-c728-40b3-b239-b3816c378c06.png)

**Comment by mweth** [comment]
Further testing.
One space =disregarded
Two space =disregarded
Three space =disregarded
Four space+ =code block

![image](https://user-images.githubusercontent.com/20465873/205479845-b31b1013-dc0c-4042-a57d-2b4f3fbb2826.png)

**Comment by mweth** [comment]
Additional observation.  When manually adding the spaces in outline, exporting, then uploading back into outline, the spaces will again convert to code blocks.  It seems that simply not converting four spaces to code blocks would resolve this issue.

![image](https://user-images.githubusercontent.com/20465873/205512608-30746111-4633-4475-ab02-f48fb68114da.png)
![image](https://user-images.githubusercontent.com/20465873/205512616-c518bbf8-de8b-4100-b7d3-91c0d78e6fd1.png)

**Comment by mweth** [comment]
Update:  This is a care feature of markdown and is -- for better or worse -- working as intended.  I do not think it is possible to introduce appropriate spacing into outline, but am willing to be surprised.  What I have done is replace all tab characters in my imported documents to &nbsb;&nbsb;&nbsb;&nbsb;&nbsb;

For now, that is working.

**Comment by tommoor** [comment]
👍  Thanks – as you say this is expected behavior of the way Markdown works
