### ISSUE TITLE
Friendly error message when .env not set

### ISSUE THREAD

**Issue by anchepiece** [outline/outline#459]
yarn start returns this:
```
Running Outline in development mode with React hot reloading. To run Outline in production mode, use `yarn start`
buffer.js:183
    throw new TypeError(kFromErrorMsg);
    ^
....
```

Tests fail like this:
```
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
      
      at Function.Buffer.from (buffer.js:183:11)
      at new Buffer (buffer.js:158:17)
      at new EncryptedField (node_modules/sequelize-encrypted/index.js:9:16)
      at EncryptedField (node_modules/sequelize-encrypted/index.js:5:16)
      at Object.<anonymous> (server/sequelize.js:8:82)
      at Object.<anonymous> (server/test/helper.js:9:17)

```

I suggest duplicating the .env.sample file as a default .env as you are already checking for a default secret key.  

Maybe a good idea is to build a getting started/installer process for development?

**Comment by anchepiece** [comment]
A second place to check is in sequelize.js, and maybe for testing a default could be allowed.

**Comment by tommoor** [comment]
@anchepiece thanks for filing! I think a friendly error message in this scenario would be a great step

**Comment by anchepiece** [comment]
@tommoor is there a reason you don't want to leave a default .env in the repo? I'll create a PR for that scenario but if you disagree with the idea just close it :smile:

**Comment by tommoor** [comment]
Yea, It's good practice to have the `.env` in `.gitignore` ([like we have](https://github.com/outline/outline/blob/master/.gitignore#L3)) to ensure that secret keys are never accidentally committed to the repo.

**Comment by anchepiece** [comment]
Ok I'll skip that PR. Thanks for the quick replies!
