### ISSUE TITLE
Mermaid Gantt chart doesn't render properly

### ISSUE THREAD

**Issue by jensschaerer** [outline/outline#4594]
Mermaid Gantt charts aren't rendered properly when using examples from Mermaid.js:

Code used:
```
gantt
    title A Gantt Diagram
    dateFormat  YYYY-MM-DD
    section Section
    A task           :a1, 2014-01-01, 30d
    Another task     :after a1  , 20d
    section Another
    Task in sec      :2014-01-12  , 12d
    another task      : 24d
```

Screenshot:
![image](https://user-images.githubusercontent.com/1929590/208738852-fb832e14-39ba-4af0-b2ca-5ad7c57fbcc2.png)

**Outline (please complete the following information):**
- Version: 0.67.0-pre.1

**Browser:**
- Google Chrome

**Comment by tommoor** [comment]
It's possible something was fixed in more recent versions of Mermaid, I can't see anything we're doing explicitly which would result in such poor rendering. Unfortunately upgrading is blocked as Mermaid changed their built code to an esmodule which is currently incompatible with Outline's built process.

**Comment by jensschaerer** [comment]
Ok, so I think discussion at https://github.com/outline/outline/discussions/4593 is same problem as well. Any chance to fix this soon or is this a longer lasting todo?

**Comment by jensschaerer** [comment]
One workarround is to use fixed width for gantt charts:

```
%%{
  
  init: {
    'gantt': {
      'useWidth': 800
    }
  }
}%%

gantt
    title A Gantt Diagram
    dateFormat  YYYY-MM-DD
    section Section
    A task           :a1, 2014-01-01, 30d
    Another task     :after a1  , 20d
    section Another
    Task in sec      :2014-01-12  , 12d
    another task      : 24d
```

![image](https://user-images.githubusercontent.com/1929590/208859341-8d55ccf7-8994-40e2-b743-a6b53eadb666.png)

Maybe this can be defined as a default global setting? See https://mermaid.js.org/config/setup/modules/defaultConfig.html for details about the default config and how to overwrite
