### ISSUE TITLE
SSO URL in wrong format causes redirection problems

### ISSUE THREAD

**Issue by florian-sabonchi** [outline/outline#4609]
As soon as OIDC omits the HTTPS in the URL, the redirection to the SSO provider does not work properly anymore see video

The configuration then looks accordingly as follows
```

    - "OIDC_CLIENT_ID=wiki.example.de"
     - "OIDC_CLIENT_SECRET=example"
     - "OIDC_AUTH_URI=id.example.de/auth/realms/master/protocol/openid-connect/auth"
     - "OIDC_TOKEN_URI=id.example.de/auth/realms/master/protocol/openid-connect/token"
     - "OIDC_USERINFO_URI=id.example.de/auth/realms/master/protocol/openid-connect/userinfo"
     - "OIDC_USERNAME_CLAIM=email"
     - "OIDC_DISPLAY_NAME=Keycloak"
     - "OIDC_SCOPES=email"
     - "FORCE_HTTPS=false"
```

https://user-images.githubusercontent.com/54689374/209473664-0477f26c-ac54-48d2-8498-aa26503423a8.mp4

**Comment by tommoor** [comment]
I’m not really sure why this is filed as a bug? If config is in the wrong format then yes, the behavior will be unexpected.

**Comment by florian-sabonchi** [comment]
Hi thanks for the feedback. I think it is an error, as soon as OIDC_AUTH_URI is specified without https or http the redirect does not work anymore, either HTTP or HTTPS should be appended or the button should not appear. I am already working on a fix
