### ISSUE TITLE
Unexpected spaces inserted on save

### ISSUE THREAD

**Issue by bb-intercom** [outline/outline#4616]
**To Reproduce**
1. edit a document by inserting a few lines using "crtl-enter" ( **important** )
2. you will find a **extra** space inserted at the beginning and at the end of the lines, after the first one
3. this **extra** insertion affects the whole document, for every new-line created using "ctrl-enter"

**Expected behavior**
no insertion of extra spaces expected

**Outline Version: v0.66.2**

**Client used**
client OS: Ubuntu 22.04.1 LTS
client Browser: chrome
version 108.0.5359.124 (Official Build) (64-bit)

**Comment by tommoor** [comment]
Could you provide a video, `Ctrl+Enter` shouldn't do anything special.

**Comment by bb-intercom** [comment]
Hi, I've recorded a sample video, as requested.
Thank you in advance for pay attention.

https://user-images.githubusercontent.com/121499485/210180762-90dd64d4-432d-4feb-9465-e317003a06a2.mov
