### ISSUE TITLE
Markdown serialization with percentages

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#464]
Found another nasty Kibana url: `https://kibana.example.com/app/kibana#/visualize/edit/Requests-%`. This breaks as `%` isn't converted to `%25`. While Chrome might think it's a invalid URI, we should handle cases when user inputs bs URLs. There's some code below that would convert the `%` in to `%25` and return rest in user inputted format. What do you think @tommoor? I didn't want to push a PR to MD serialization due to Slate upgrade and I can't really test :/

https://stackoverflow.com/questions/7449588/why-does-decodeuricomponent-lock-up-my-browser

```js
// to ensure markdown compatability we need to specifically encode some characters
export function encode(href: string) {
  return href
    .trim()
    .replace(/ /g, '%20')
    .replace(/'/g, '%27')
    .replace(/\(/g, '%28')
    .replace(/\)/g, '%29');
}

export function decode(href: string) {
  try {
    return decodeURI(href);
  } catch (e) {
    return decodeSafe(href);
  }
}

export function decodeSafe(uri) {
  const components = uri.split(/(%(?:d0|d1)%.{2})/);
  return components
    .map(component => {
      try {
        return decodeURIComponent(component);
      } catch (e) {
        return component.replace(/%(?!\d+)/g, '%25');
      }
    })
    .join('');
}
```

**Comment by tommoor** [comment]
Trying to understand this. From what I can gather I don't think the fix is needed on the decode side as long as it's encoded correctly to begin with when the user enters it, so it would need an exception in the encode that would find any "%" not followed by two numbers and encode it as "%25"?
