### ISSUE TITLE
Add translation hooks to transactional emails

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4645]
Things like invites, export emails, etc should be translated correctly. If there is a user context then we can use the language for that user, if not then fall back to the installations `env.DEFAULT_LANGUAGE`.

See #4657 for examples.

**Comment by matmair** [comment]
@tommoor would you be open for PRs regarding this? We need this in my org so I would be open to invest some time into it.

**Comment by tommoor** [comment]
Yes, open for PR's that allow emails to be translated. I would do one email first as an example of the approach
