### ISSUE TITLE
Mixed content error, unable to edit

### ISSUE THREAD

**Issue by lumoe** [outline/outline#4658]
Using Chrome throws this error message: `Mixed Content: The page at '<URL>' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://example.com/collaboration/document.55b150ff-b807-497f-8877-..'. This request has been blocked; this endpoint must be available over WSS.`

The second Websocket is connecting using `wss://` and works. It is the `wss://example.com/realtime/?EIO=4&transport=websocket` websocket. 

The upgrade to secure works for the second socket and is correctly configured in the reverse proxy. 

**Expected behavior**
The WebSocket should connect via `wss://` and not `ws://` if there is HTTPS available. 

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.66.2

**Desktop:**
All Browsers block mixed content.

**Mobile (please complete the following information):**
All Browsers block mixed content.

**Comment by tommoor** [comment]
What is your `URL` env variable set to?

**Comment by lumoe** [comment]
You are absolutely right, that was the mistake. The scheme was set to `http://` instead of `https://`. Thank you! 

The behaviour that one WS was able to connect and the second not confused me, hence the issue.
