### ISSUE TITLE
User unable to login via SSO after modifying profile details

### ISSUE THREAD

**Issue by mind-overflow** [outline/outline#4668]
**To Reproduce**
Using OpenID (Keycloak in this case)...
1. Modify any number of details of a user profile (email, first name, enable 2FA... in this case, all said things were done to this user)
2. Try to log into Outline
3. The login page reloads without letting you in, and an error appears in console.

I'm guessing that Outline tries to register this as a new user, since e.g. the email has changed, but the user already exists, so it throws an error.

This looks similar to #3212 and #3438, but I can't seem to find a fix in either of those issues. #3438 claims that it has been fixed in `v0.66.0`, but I'm running `v0.66.2` and the issue persists.

**Expected behavior**
The user is able to log in, and any change that has happened to their profile should be reflected in Outline. The user should be able to log in.

**Screenshots**
```json
{"error":"User authentication 064760dd-db2f-47b9-ac18-f4e6612dcbcd already exists for f565921a-7b47-4377-a23a-e406fdc35adb, tried to assign to b7c28117-dbd8-4ab3-814c-29e134fc5c9c",
"stack":"UnauthorizedError: User authentication 064760dd-db2f-47b9-ac18-f4e6612dcbcd already exists for f565921a-7b47-4377-a23a-e406fdc35adb, tried to assign to b7c28117-dbd8-4ab3-814c-29e134fc5c9c\n    at AuthenticationError (/opt/outline/build/server/errors.js:41:34)\n    at accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:135:43)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async OAuth2Strategy._verify (/opt/outline/build/server/routes/auth/providers/oidc.js:87:22)",
"level":"error",
"message":"Error during authentication"}
```

**Outline**
- Install: self-hosted
- Version: Docker, `v0.66.2` (tag: `latest`)  
  
**Edit**: I also tried manually setting the tag to `v0.66.3` but the behavior doesn't change.

**Comment by patzm** [comment]
I think I ran into the same issue. I am running outline on `v0.66.3`. Maybe it is noteworthy that my keycloak server reported the following error when trying to log in:
```
09:43:57,219 WARN  [org.keycloak.events] (default task-257) type=REFRESH_TOKEN_ERROR, realmId=REALM_ID, clientId=CLIENT_ID, userId=null, ipAddress=<my-ip>, error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret
```
Note that I redacted the IP, `REALM_ID`, and `CLIENT_ID`.

I then restarted Keycloak, and arrived at this situation.

**Comment by jberggg** [comment]
I ran into the same issue with outline 0.68.1. Deleting the "affected" session from the `user_authentications` table in the DB seems to fix it.

**Comment by artem-khromov** [comment]
Issue remains in 0.73.1 
I'm using Zitadel instead of Keycloak, but context is the same.
