### ISSUE TITLE
Cannot get all documents when using sort: "index" via the API.

### ISSUE THREAD

**Issue by kornarakis** [outline/outline#4672]
I have a document list like the following one

```
├── first document
├── second document
│    ├── nested document
│    │    ├── nested document
│    │    ├── nested document
│    │    ├── nested document
│    │    └── nested document
│    └── nested document
│         ├── nested document
│         ├── nested document
│         └── nested document
└── third document
     ├── nested document
     │    ├── nested document
     │    ├── nested document 
     │    ├── nested document
     │    └── nested document
     └── nested document
          ├── nested document
          ├── nested document
          └── nested document
```

I'm trying to get a collection list using the API calling the `documents.list` using the following params

```json
{
  "offset": 0,
  "collectionId": "....",
  "limit":50,
  "direction": "DESC"
}
```
With that options everything works fine, I can get all the documents and the nested ones. 

The sorting it's not the ideal, I want the manual sorting I already have, so I am trying to use the sort by index option like this

```json
{
  "offset": 0,
  "sort": "index",
  "collectionId": "....",
  "limit":50,
  "direction": "DESC"
}
```
But when I do this I am getting only the 3 top level documents and the nested ones are missing.

Am I missing something ? 🤔

Thank you in advance :)

**Comment by tommoor** [comment]
This is the way it's designed to work at the moment, the sort="index" is used for the collection home and I don't think has really been used by third-parties. It's possible to update the endpoint but it would require an extra parameter, like `deep` or `recursive` to return all documents

In the meantime you can get the order of documents by reading the `collection.documents` tree.

**Comment by kornarakis** [comment]
Thank you @tommoor :) 

With `collections.info` I can get the real order and then combine with the result set of `documents.list` .

But it would awesome the `sort: index` to return the nested docs also :)

**Comment by adityash1** [comment]
@tommoor I would like to work on this. Can you give me some suggestions, how should I approach this?

**Comment by tommoor** [comment]
The order is contained only in `collection.documentStructure` – most likely best approach would be to flatten this tree and then slice it at the offset/limit parameters and query for documents with the ids in that array.
