### ISSUE TITLE
after migration to 0.67.0 get an infinite redirect to outline.mycorp.com/

### ISSUE THREAD

**Issue by bmm-alc** [outline/outline#4673]
I upgraded from 0.66.3 to 0.67.0 (including the database migration), started the services then I went on https://outline.mycorp.com/ and got an error about infinite redirect

**To Reproduce**
1. Go to https://outline.mycorp.com/ 
2. Receive from the server HTTP 301 with header Location:  https://outline.mycorp.com/ 
3. step 2.
4. again

**Outline (please complete the following information):**
- Install: self-hosted docker
- Version: 0.67.0

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 108.0.1

docker.env
```
SECRET_KEY=xxxxxxxxxxxxxxxxxxxxxxx
DATABASE_URL=postgres://outline-user:xxxxxx@postgres:5432/outline
PGSSLMODE=disable
REDIS_URL=redis://redis:6379
URL=https://outline.mycorp.com
AWS_ACCESS_KEY_ID=xxxxxxxx
AWS_REGION=xx-xxx
GOOGLE_CLIENT_SECRET=xxxxxxx
OIDC_USERNAME_CLAIM=preferred_username
OIDC_DISPLAY_NAME=OpenID
OIDC_SCOPES=openid profile email
FORCE_HTTPS=true
ENABLE_UPDATES=true
DEBUG=http,emails,mailer
ALLOWED_DOMAINS=mycorp.com
SMTP_HOST=email
SMTP_FROM_EMAIL=xxx
SMTP_REPLY_EMAIL=xxxx
SMTP_SECURE=false
DEFAULT_LANGUAGE=en_US
```

**Comment by tommoor** [comment]
Unclear why the behavior would have changed in this release, but you can set `FORCE_HTTPS=false` to work around it for now

**Comment by bmm-alc** [comment]
thanks, did that and it fixed the problem for now.

**Comment by tommoor** [comment]
Through the upgrade of dependencies the behavior of proxy-forwarded HTTPS detection seems to have changed. You should ensure that `x-forwarded-proto` header is present in the requests from your proxy, this will resolve the issue.

Will add a note in this respect to the release notes which are being written.

**Comment by bmm-alc** [comment]
Hi @tommoor 
 
is commit a1cefa9771875c9380426af20e70fc287044345f a fix for this bug 

thanks ?
