### ISSUE TITLE
Attachments uploaded via API doesn't appear in the document

### ISSUE THREAD

**Issue by max-mykhailenko** [outline/outline#4675]
Can't upload attachment to document with API. Attachment doesn't appear in the document

**To Reproduce**
1. Call api method attachment.create https://www.getoutline.com/developers#tag/Attachments/paths/~1attachments.create/post with payload
```json
{
      "documentId": "UUID here",
      "contentType": "text/csv",
      "name": "filename.csv",
      "size": 3446
}
```
2. Receive 200 OK

**Expected behavior**
Get the attachment In the document with passed UUID. All works fine if I drag and drop the same file in the interface. Payload from browser API request and payload from node API request are the same.

**Outline:**
- Install:self hosted
- Version: 0.66.2

**Comment by tommoor** [comment]
This is expected behavior, uploading an attachment just creates the attachment in storage it does not edit the document in any way.

**Comment by max-mykhailenko** [comment]
@tommoor ok, got it, but how I can append attachment to the document after creating and uploading to AWS?
Thank you

**Comment by tommoor** [comment]
You can use the `documents.update` endpoint with the `append=true` parameter, pass the image as markdown eg:

`![my image](/api/attachments.redirect?id=<attachmentId>)`

https://www.getoutline.com/developers#tag/Documents/paths/~1documents.update/post
