### ISSUE TITLE
After upgrade to 0.67.0 getting error on startup

### ISSUE THREAD

**Issue by sarg3nt** [outline/outline#4677]
I unfortunately was using the latest tag for the docker container as I'd just gotten Outline installed a few days ago and it upgraded with the release of 0.67.0.
I ran the DB migrations manually as it asks (why aren't these done automatically on startup?)
On restart after the db migrations were ran it now throws the following error and exits.  This happens each time I start the container.

```
yarn run v1.22.18
$ node ./build/server/index.js
{"label":"lifecycle","level":"info","message":"\nIs your team enjoying Outline? Consider supporting future development by sponsoring the project:\n\nhttps://github.com/sponsors/outline\n"}
/opt/outline/node_modules/redis-parser/lib/parser.js:179
    return new ReplyError(string)
           ^

ReplyError: EXECABORT Transaction discarded because of: NOAUTH Authentication required.
    at parseError (/opt/outline/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/opt/outline/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'exec', args: [] },
  previousErrors: [
    ReplyError: NOAUTH Authentication required.
        at parseError (/opt/outline/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/opt/outline/node_modules/redis-parser/lib/parser.js:302:14) {
      command: { name: 'multi', args: [] }
    },
    ReplyError: NOAUTH Authentication required.
        at parseError (/opt/outline/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/opt/outline/node_modules/redis-parser/lib/parser.js:302:14) {
      command: { name: 'llen', args: [ 'bull:globalEvents:wait' ] }
    },
    ReplyError: NOAUTH Authentication required.
        at parseError (/opt/outline/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/opt/outline/node_modules/redis-parser/lib/parser.js:302:14) {
      command: { name: 'llen', args: [ 'bull:globalEvents:paused' ] }
    },
    ReplyError: NOAUTH Authentication required.
        at parseError (/opt/outline/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/opt/outline/node_modules/redis-parser/lib/parser.js:302:14) {
      command: { name: 'zcard', args: [ 'bull:globalEvents:delayed' ] }
    }
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Edit: I meant to add, I do have the Redis password in the env variable. Example (Password redacted but original was 64 alpha numeric with no specials)
`"REDIS_URL=redis://user:password-redacted@outline-redis:6379/0",`

**To Reproduce**
I don't know if this is reproducible or not

**Expected behavior**
The upgrade should succeed and the product work.

**Outline (please complete the following information):**
- Install: Self hosted in Docker on Unraid
- Version: 0.27.0 as of 10.45 AM on 1/11/23  
  "Image": "sha256:35a1488d3f68e1a6deb2a99a398663ca081f06d9aab61d57a83f4c157e90329f",

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 108.0.2

**Mobile (please complete the following information):**
NA

**Comment by tommoor** [comment]
In this release the `user` is passed through to Redis, this was previously not the case. You likely need to update your `REDIS_URL` to remove any fake user that might have been added. e.g.

`"REDIS_URL=redis://:password-redacted@outline-redis:6379/0",`

Will add this to the release notes which are currently being written. Reopen if this doesn't solve it.
