### ISSUE TITLE
Unable to load images in documents after migrating to 0.67.0

### ISSUE THREAD

**Issue by bconfais** [outline/outline#4678]
After migrating to 0.67.0, removed the "node_modules" directory, installed the dependencies (yarn install --frozen-lockfile && yarn build) and migrated the database (yarn sequelize db:migrate --env=production-ssl-disabled),
the image included in documents are not displayed.

The request to the attachment file returns a 500 error with the following error on the server:

```
{"label":"http","level":"info","message":"  xxx GET /api/attachments.redirect?id=a7080e74-003c-4062-be13-15f7a595a77e 500 34ms -"}
TypeError: Cannot read properties of undefined (reading 'teamId')
     at handleAttachmentsRedirect (/srv/outline/build/server/routes/api/attachments.js:167:58)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async apiWrapperMiddleware (/srv/outline/build/server/routes/api/middlewares/apiWrapper.js:14:5)
     at async userAgent (/srv/outline/node_modules/koa-useragent/dist/index.js:12:5)
     at async /srv/outline/node_modules/koa-mount/index.js:58:5
     at async /srv/outline/node_modules/koa-mount/index.js:52:26
     at async logger (/srv/outline/node_modules/koa-logger/index.js:67:7) {
   status: 500
 }
```

Nodejs version: v16.19.0
Outline version: commit d5158f0a3466c1e4ca7a31dae758ffd5eb395bba

It works perfectly if I roll back on the 0.66.3 version

**Comment by tommoor** [comment]
You should remove the `build` directory and run `yarn build` again – the file referenced in the stack trace no longer exists in the latest version so it's running a mixture of old and new code.

Consider running the official docker container instead to avoid this type of issue
