### ISSUE TITLE
Embed view counts in document API responses

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#468]
Right now we're embedding revisions counts with documents but not views. Total view count would be useful for ranking content but not critical.

**Comment by tsl8r** [comment]
It looks like the Views table is already tracking everything and it just needs to be fetched and passed down to the client. I got that working last night but wanted to make sure this is what you had in mind. 
![screen shot 2018-05-17 at 9 46 04 am](https://user-images.githubusercontent.com/6257209/40188577-7c8d2a8a-59b7-11e8-9c04-22143bd11b96.png)

**Comment by tommoor** [comment]
Hey @tsl8r , very cool to see!

I'm not sure if we actually want to display the view count in the UI or not as it kind of harks of view counters from the 90's… It's more about being able to use it as a signal for relevance. Are you doing an additional join to achieve that?

**Comment by tommoor** [comment]
Perhaps we could reduce it down to some sort of "popularity" icon like a cellphone signal.

**Comment by tsl8r** [comment]
I definitely agree with that, especially because the relevance is in relation to other docs. 

Right now I did a join by modifying the `defaultScope` on the document to include `{ model: models.View, as: 'views' },`. 

Is this a common feature request though? I took this because it seemed like a good first task but I could understand if there are other things that are way higher priority.

**Comment by tommoor** [comment]
> Is this a common feature request though? I took this because it seemed like a good first task but I could understand if there are other things that are way higher priority.

Yea, to be honest it was just an idea that Jori through in here rather than a true required feature. Outline is focused on speed so I'd rather not include an additional join if unnecessary. Perhaps we should close this out as won't implement for now – really appreciate you taking a look though 🙏

**Comment by tsl8r** [comment]
Sounds good. It was a good way to get familiar with the repo. I agree that closing is best for now.
