### ISSUE TITLE
Link with hashtag of a copied link from a H2 tag is not working

### ISSUE THREAD

**Issue by RudyBussieres** [outline/outline#4686]
The hashtag of a copied link from a **_H2_** tag is not working.

**To reproduce**
1. Simply copy a link from a **_H2_** tag that you need to scroll the page to see it.
2. Copy and paste the link that contains the hashtag in your web browser (ex: Chrome on a Windows 11 desktop)
3. The page seems to be trying to scroll to the tag but does not succeed

**Expected behavior**
I expect the page to be scrolling to the tag just like it's working with a link copied from a **_H3_** tag.

**Outline (please complete the following information):**
- Install: getoutline.com

**Comment by tommoor** [comment]
Unfortunately I'm not able to reproduce – you should provide more details such as the browser you're using. A video would be great.

**Comment by RudyBussieres** [comment]
I created a simple page with H1, H2 and H3 links and now it's the link from the **_H3_** tag that won't work. So It seems it would depend on the content of the page. In Firefox it's working fine but in Chrome and Edge I have the problem. I made a video: https://www.youtube.com/watch?v=3NfEg3fKGvs

**Comment by tommoor** [comment]
Great, thanks!
