### ISSUE TITLE
Share dialog for a nested shared document improves

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4699]
In this dialog that is shown on a nested document within a publicly shared document we should have some way of getting to the top-level share. It warns you that a parent is publicly shared but doesn't provide a way to copy a link from that share.

<img width="401" alt="image" src="https://user-images.githubusercontent.com/380914/212477369-5ee94214-68d0-4f0b-95be-b4b7e68bf3fd.png">

**Comment by adityash1** [comment]
Should we make the parent document name clickable so that it redirects to the top level shared doc?

And what should be the better way to provide a copy link ? 
Another button on the left corner when we expand the menu?

**Comment by tommoor** [comment]
We can make it clickable yes, although it doesn't completely solve it. I still feel the need for a button here that allows copying the link to this document within the shared parent.

I'm tempted to move "Publish to internet" into "More options" in this specific scenario and have "Copy link" copy the link within the shared parent. Wanting to share a sub-document separately is going to be quite rare.

**Comment by adityash1** [comment]
As you said in this specific scenario we should make "copy link" copy the shared parent link instead. what should be the appropriate button text for this or "copy link" is fine? 

And what if someone wants to copy the subdocument link ?

**Comment by tommoor** [comment]
I think that "copy link" should link to the same document in this scenario, but within the shared parent. The same link that you would get if you were to open the shared parent link and navigate to the nested document.
