### ISSUE TITLE
JSON Import / Export

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4703]
We have had a number of requests to move data between self hosted <-> cloud hosted and visa versa. The current export system based on Markdown is not high fidelity enough for this and results in the loss of a lot of data.

**Comment by MaxValue** [comment]
Is there a reason that the edit history is not included in these JSON exports?

**Comment by tommoor** [comment]
No one particular reason, though the size would be much larger and history is more sensitive as you are essentially recreating an audit trail in a way that could be easily manipulated.
