### ISSUE TITLE
Change "Duplicate" to place the new document in users drafts

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4708]
Blocked by https://github.com/outline/outline/pull/4582

Once the above lands we can change duplicate functionality to place the duplicated document in your drafts instead of next to the original. This will be a more natural flow as discussed elsewhere (I can't remember where!)

**Comment by apoorv-mishra** [comment]
> This will be a more natural flow as discussed elsewhere (I can't remember where!)

[Here](https://github.com/outline/outline/issues/4244#issuecomment-1279992333).
