### ISSUE TITLE
Deleting text at beginning of a line in a code block has weird behavior

### ISSUE THREAD

**Issue by sarg3nt** [outline/outline#4727]
When deleting text with the (delete) key at the beginning of a line the carrot sometimes will move to the end of the previous line for no reason.  When the cursor jumps to the end of the previous line (delete) no longer works.
I think I've seen similar behavior when deleting or backspacing at the end of a line, but I can't replicate it now.

**To Reproduce**
1. Create a code block and select Bash
2. Add a few lines of comments
3. Place cursor and beginning of one of the middle lines 
4. Press (delete) to delete the characters from the line, continue until bug occurs

**Expected behavior**
Cursor should not jump to previous line when deleting text.

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: 0.67.1  "Image": "sha256:d27f8826eb5e72b61434cf1fd7d8ed9692ac1cffe6cfaf92721ffb30d267342c",

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version 108.0.2

**Comment by tommoor** [comment]
I'm not sure I understand the request here, this sounds like standard text editor behavior – that the cursor would jump to the line above when there is nothing left to delete on the current line? What do the crossed out parts of your issue represent?

**Comment by sarg3nt** [comment]
Hey @tommoor , sorry about that, I hit submit and had to run and didn't proof the post.  I was using a sequence of characters for the (delete) key that appears to have caused markdown to cross out lines.  (shrug)
Anyway, I fixed it above.
It's the delete key on the keyboard which on the PC should only ever delete text to the right of the cursor and does this most of the time in a code block but will randomly just move up to the end of the previous line, even when there is more text to delete, and then freeze.
There's a lot of other weird and spurious behavior in a large code block I ran into alter that night but can't really remember all of right now.  If I run into them tonight I'll update this post.  I'm writing technical docs for my homelab as I'm deploying Kubernetes on Pi's so there should be more code blocks in my future.  :)

**Comment by tommoor** [comment]
> It's the delete key on the keyboard which on the PC should only ever delete text to the right of the cursor 

Do you mean to the left? I think you need to post a screencapture of the behavior

**Comment by sarg3nt** [comment]
Hey @tommoor , sorry, life got busy and I forgot about this.
So, you must be a Mac user I assume?
Most standard keyboards (that does not include mac keyboards and laptops) there are two keys for doing deletes.  The Backspace key up on the far right of the home number row and a delete key in the cluster of six keys above the arrow keys.  The backspace key (which is typically the delete key on a Mac, silly apple) deletes characters to the left of the while the delete key deletes them to the right.  Most macs have a function key, if you hold that down and press delete it will delete chars to the right.
If this still is not clear, let me know and I'll fine and install some screen recording software and get that to you somehow.

**Comment by tommoor** [comment]
You're right that the delete-to-the-right behavior can be reproduced with `fn` key on Mac, in my testing the way this works is the same as other editors though eg Visual Studio Code.

**Comment by sarg3nt** [comment]
Apparently, you aren't seeing the bug.  
Here's a screen2gif recording I just made.  
I place the carrot at the beginning of a line of code and start pressing delete, a few characters in the carrot jumps to the end of the previous line which it should not do.
I'm continuing to press delete but nothing is happening. 
![delete_issues](https://user-images.githubusercontent.com/3372486/215301705-2689eece-7a16-4705-b42b-464b207b738c.gif)

**Comment by sarg3nt** [comment]
And just so we are on the same page, here's the same code in VS Code, holding down the delete key, notice the carrot never goes to the previous line.
![vscode](https://user-images.githubusercontent.com/3372486/215301936-45151de1-08fd-45b7-b254-a6123c67773d.gif)

**Comment by sarg3nt** [comment]
Hi @tommoor .  This is still marked as closed.  Do you intend on reopening it or is there a defect that got logged?

**Comment by jannschu** [comment]
I also stumbled upon this I think, here is screencapture with a minimal example and on the current HEAD.


https://user-images.githubusercontent.com/17914/234881351-3e47477b-558c-4d33-9973-4abfe80333a6.mov

**Comment by tommoor** [comment]
Closed by https://github.com/outline/outline/pull/5366
