### ISSUE TITLE
not starting after upgrade to v0.67.2

### ISSUE THREAD

**Issue by CHUYKOPS** [outline/outline#4729]
yarn run v1.22.18
error Command "sequelize:migrate" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tommoor** [comment]
`sequelize:migrate` is no longer included as a command, use `db:migrate` instead.

**Comment by dannykorpan** [comment]
Same problem here with docker image. How to use "db:migrate" within the docker image?

**Comment by CHUYKOPS** [comment]
Hey. Check your docker compose file for line "command" and change it like
`  outline:
    image: outlinewiki/outline:latest
    user: root
    restart: always
    container_name: outline
    command: sh -c "yarn db:migrate"`

**Comment by CHUYKOPS** [comment]
> Same problem here with docker image. How to use "db:migrate" within the docker image?

Hey!
You need to change command line like:

    command: sh -c "yarn db:migrate --env=production-ssl-disabled && yarn start --env=production-ssl-disabled"

**Comment by dannykorpan** [comment]
Works, thanks!
