### ISSUE TITLE
Bug: 0.67 broke API document.export with shareId

### ISSUE THREAD

**Issue by tvarsis** [outline/outline#4732]
In version 0.66 you could POST to document.export with payload shareId. After 0.67 that call now gives error saying id is required. If I then add id to the payload as well as shareId it says authentication or shareId is missing. So it does not seem possible to use this endpoint for public docs anymore. 

- Install: self hosted
- Version: 0.67.2

**Comment by tommoor** [comment]
Hi @tvarsis exporting a document with a `shareId` was purposefully removed in `>0.67`. Could you share more about your usecase?

**Comment by tvarsis** [comment]
We used that endpoint to display and render the markdown document in an other app. What was the reasoning for removing a feature that already worked? It was not part of the breaking changes in the release notes, not even mentioned at all as far as I can tell.

**Comment by tommoor** [comment]
Will add as a breaking change, fair to say that was an oversight.

In terms of reasoning, we added additional HTML and PDF export options which are much heavier in terms of server processing - with this addition export using a shareId became a potential point of abuse and wasn’t used by the app directly.

**Comment by tvarsis** [comment]
@tommoor Thanks for your reply! I understand. What would be the recommended migration path for this? Is it possible to get the HTML export the same way to render it, or is the only way to use the authenticated flow to get the document.export, or is all options deprecated?

**Comment by tommoor** [comment]
The API isn't designed to be used for embedding like this, but if you want to continue to do so you would need to call the endpoint with an API key and the document ID instead of the shareID. It would be wise to make sure that the API key has limited permissions, I'd recommend creating a user just for this purpose.
