### ISSUE TITLE
Visual bug Tip + code

### ISSUE THREAD

**Issue by CHUYKOPS** [outline/outline#4733]
1. Create tip, insert code inside
2. Try to change tip to warning

**Screenshots**
![image](https://user-images.githubusercontent.com/88129934/212950627-37a6cc66-3261-48e7-aa7d-272ea6da6d2a.png)

**Outline (please complete the following information):**
- Install: self hosted
- Version: 67.2

**Comment by tommoor** [comment]
Code blocks within notices wasn't really a usecase I thought of, I'm interested in the kind of content that would make sense for? The solution for fixing this one isn't really clear.
