### ISSUE TITLE
Clicking hyperlink in Google Sheets to pdf on Outline gives 401 error, pasting link in browser does not

### ISSUE THREAD

**Issue by Arne-B93** [outline/outline#4737]
Clicking hyperlink in Google Sheets to a pdf file uploaded to Outline gives a 401 authentication error. The bug was first reported as a consistent issue for all users on November 22nd. Before that the hyperlink functionality worked for most (not clear if the bug occurred for some users before that). 

Notes: 
- Pasting the same URL in the browser or accessing from MS Word does op the link to the PDF file correctly by downloading it.
- This error occurs throughout the organization, on different systems (iOS / Windows) and both in Chrome and Firefox
- Error occurs also when logged in

**To Reproduce**
1. Drag a pdf file to Outline page
2. Right click the file -> Copy link address
3. In Google sheets, hyperlink some text using the link address
4. Click hyperlink in Google Sheets
5. 401 authentication error occurs

**Expected behavior**
Download the PDF file by following the link. This already happens correctly when pasting the link, but not when clicking a hyperlink in Google Sheets (401 error). 

**Screenshots**
![image](https://user-images.githubusercontent.com/33360432/213146884-77d681b7-efde-4822-880e-26d96709eaf5.png)

**Outline (please complete the following information):**
- Install: getoutline.com (Land Life Company)

**Desktop (please complete the following information):**
 - Windows 11 Version 21H2 (Build 22000.1455)
 - Chrome 108.0.5359.126 (Official Build) (64-bit) (cohort: 108_control_126)
 - Firefox 108.0.2 (64-bit)

**Comment by Arne-B93** [comment]
Thank you for response! Unfortunately, I'm testing in Google Slides and Google Sheets and problems persist (401 authentication error). In addition to clearing cache and cookies and restarting system, are there any additional steps I should take to align our Outline version with main branch?

Thank you.

**Comment by tommoor** [comment]
Users must logout and in again to get the new cookie policy which allows this fix to work

**Comment by Arne-B93** [comment]
Thank you, bug confirmed fixed on my system!
