### ISSUE TITLE
Cannot update profile picture

### ISSUE THREAD

**Issue by eroji** [outline/outline#4738]
- Navigate to Profile -> Photo -> Upload
- Upload a picture, crop the image
- UI indicates uploaded successful but no picture shown
I can validate that the picture was uploaded to Minio correctly. Logs for the Outline container also shows no issues. Regular file attachments also uploads fine and can be viewed in document pages.

```
{"label":"http","level":"info","message":"  <-- GET /api/attachments.redirect?id=c420de33-e3cf-4108-afd7-0f42b0af4ef1"}
{"label":"http","level":"info","message":"  --> GET /api/attachments.redirect?id=c420de33-e3cf-4108-afd7-0f42b0af4ef1 302 16ms 939b"}
{"userId":"7939aaee-41c5-4da6-9d49-e7ebad9a8d4c","label":"multiplayer","level":"info","message":"Closed connection to \"document.10a463b2-da46-4cf2-a9cc-fdb647e3afb8\""}
{"label":"http","level":"info","message":"  <-- POST /api/attachments.create"}
{"label":"http","level":"info","message":"  --> POST /api/attachments.create 200 117ms 1.56kb"}
{"name":"attachments.create","modelId":"625d1d8b-9f7d-48c0-822d-0f7b76291630","attempt":0,"label":"worker","level":"info","message":"Processing attachments.create"}
{"name":"attachments.create","modelId":"625d1d8b-9f7d-48c0-822d-0f7b76291630","label":"worker","level":"info","message":"WebhookProcessor running attachments.create"}
{"label":"http","level":"info","message":"  <-- POST /api/users.update"}
{"attachmentId":"a72a7d9b-936b-4d12-b9bf-b421adc3a9fe","teamId":"7939aaee-41c5-4da6-9d49-e7ebad9a8d4c","label":"worker","level":"info","message":"DeleteAttachmentTask running"}
{"label":"http","level":"info","message":"  --> POST /api/users.update 200 108ms 515b"}
{"name":"users.update","modelId":null,"attempt":0,"label":"worker","level":"info","message":"Processing users.update"}
{"name":"users.update","modelId":null,"label":"worker","level":"info","message":"WebhookProcessor running users.update"}
```

**Expected behavior**
The picture should be showing in UI

**Screenshots**
![image](https://user-images.githubusercontent.com/13228540/213269791-b9add91f-fa85-4d15-ba03-59baa2062792.png)
![image](https://user-images.githubusercontent.com/13228540/213270169-1c7b1e63-d202-4e9d-b7af-55719e0115cb.png)

**Outline (please complete the following information):**
- Install: self-hosted with docker-compose
- Version: 0.67.2
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 108.0.5359.126

**Comment by tommoor** [comment]
Is the network request for the image in the browser console erroring?

**Comment by eroji** [comment]
Actually looks like it is. It's getting a 403. The bucket access policy is configured at private.

![image](https://user-images.githubusercontent.com/13228540/213277791-e784cb22-4020-44e7-8811-16198e569e5e.png)
![image](https://user-images.githubusercontent.com/13228540/213278020-6e41837a-afd4-4dc3-85a0-dbedf3d28c39.png)

**Comment by eroji** [comment]
I'm assuming I need to change the bucket policy to allow read to `outline-bucket/public`?

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowPublicRead",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::outline-bucket/public/*"
            ]
        }
    ]
}
```
The above policy seems to work.

**Comment by tommoor** [comment]
Yep that’s correct

**Comment by eroji** [comment]
Perfect. Thank you.

**Comment by MetaBliss** [comment]
Hi Eroji, could you advise how you changed the bucket policy in Minio? How would I do that using the GUI? Please and thank you so much,

> I'm assuming I need to change the bucket policy to allow read to `outline-bucket/public`?
> 
> ```
> 
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Sid": "AllowPublicRead",
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": [
>                     "*"
>                 ]
>             },
>             "Action": [
>                 "s3:GetObject"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::outline-bucket/public/*"
>             ]
>         }
>     ]
> }
> ```
> 
> The above policy seems to work.

**Comment by eroji** [comment]
Here is what I have
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "BucketAccessForUser",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::outline-bucket/*",
                "arn:aws:s3:::outline-bucket"
            ]
        }
    ]
}
```

**Comment by eroji** [comment]
Under `Policies` create it then apply it to the user your instance is connecting to Minio with.

**Comment by broken-wheel** [comment]
I ran into the same issue. I thought that setting `AWS_S3_ACL=private` would apply to any and all bucket usage. So, I am curious why the profile picture uses `public-read`. What's the rationale?

For added context, I can't change the bucket acl to `public-read` because of organizational policy. So, is there any way to update the profile pic under this situation?
