### ISSUE TITLE
Authentication providers cannot be disabled in db when self-hosting

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4743]
### Discussed in https://github.com/outline/outline/discussions/4735

<div type='discussions-op-text'>

<sup>Originally posted by **yoramshai** January 17, 2023</sup>
Is there an option to remove the slack auth without removing slack integration?</div>

**Comment by DimitriDR** [comment]
Yes. I just did it. Just put in comments everything about slack in your .env file.

From lines 67-70:
```
# When configuring the Client ID, add a redirect URL under "OAuth & Permissions":
# https://<URL>/auth/slack.callback
# SLACK_CLIENT_ID=get_a_key_from_slack
# SLACK_CLIENT_SECRET=get_the_secret_of_above_key
```

From lines 141-147:
```
# For a complete Slack integration with search and posting to channels the
# following configs are also needed, some more details
# => https://wiki.generaloutline.com/share/be25efd1-b3ef-4450-b8e5-c4a4fc11e02a
#
# SLACK_VERIFICATION_TOKEN=your_token
# SLACK_APP_ID=A0XXXXXXX
# SLACK_MESSAGE_ACTIONS=false
```

That's all 😃

**Comment by elidrissidev** [comment]
Seems that this issue may be originating from the condition added in https://github.com/outline/outline/pull/2986#discussion_r791398491, once I comment that line the disabled provider is no longer showing on the login page.

**Comment by yoramshai** [comment]
To add more info on this.
I can see the slack disable radio button in the security tab, but it is not clickable. 

<img width="473" alt="image" src="https://user-images.githubusercontent.com/11707803/215209871-5440173b-a3f4-4a77-b0ea-81ab6f375cd2.png">
