### ISSUE TITLE
High number of list items slow down rendering performance

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#475]
I noticed that a document with large amount of links is really slow to render. Example markdown:

https://github.com/reactjs/redux/blob/master/docs/introduction/Ecosystem.md

**Comment by tommoor** [comment]
It looks like the React 16 work scheduling stuff __might__ be causing this, when I profile the mount I see `deserialize` getting called over and over again within react's `workLoop` method - the Editor component itself is definitely only mounted once by our app.

![image](https://user-images.githubusercontent.com/380914/33793336-0b5d0dc2-dc6b-11e7-8e74-8039d2b87e97.png)

**Comment by tommoor** [comment]
I tried moving the deserialization down to the model which helped a little but the underling problem remains. Interestingly this doesn't seem to be the time spent to actually mount React components (300ms), 10x that is spent in the Editor… this seems to be a Slate issue

![image](https://user-images.githubusercontent.com/380914/33798815-68b69948-dcd4-11e7-8d92-4dc5b9689979.png)

**Comment by tommoor** [comment]
More debugging: It seems like the links aren't the problem - the list items are, removing the list items brings this back to acceptable performance. Likely the `slate-edit-list` schema is the cause.
