### ISSUE TITLE
Cannot search for existing pages from floating toolbar

### ISSUE THREAD

**Issue by fabiansiegel** [outline/outline#4757]
Since the update from [v0.66.3](https://github.com/outline/outline/releases/tag/v0.66.3), the "Create Link" Popup is unable to search in the wiki. Creation of Links is not affected. There is nothing in the logs.

**To Reproduce**
1. Go to a page
2. Edit the page
3. press CTRL-K
4. Type a title of an existing page
5. no search functionality is displayed

**Expected behavior**
Existing pages are being displayed that match the search parameters

**Screenshots**
![image](https://user-images.githubusercontent.com/4614435/214154746-acde46e9-b0c4-4520-a11e-fd99bba4468f.png)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.67.2 sha: 21ce145

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 108.0.2

**Mobile (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 16.1
 - Browser stock browser, safari

**Comment by tommoor** [comment]
Please post the logs in the browser console, what network requests are made? I cannot reproduce currently

**Comment by fabiansiegel** [comment]
Thanks a lot!

There are - strangely - no requests being made while typing:

![image](https://user-images.githubusercontent.com/4614435/214249054-2cc488d5-e0a2-4483-bafa-18b5cd32161b.png)


> GETwss://outline.example.example.com/collaboration/document.00272346-2ad0-4946-a185-ba1f51c9c590
> [HTTP/1.1 101 Switching Protocols 91ms]
> 
> GEThttps://outline.example.example.com/doc/tesst-vmTOmyx66K/edit
> [HTTP/1.1 200 OK 80ms]`
> 
> GEThttps://outline.example.example.com/static/runtime.0c57674ed5a72fe40ad5.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/main.c82fcb230e43c2e75e78.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/preload-authenticated.eee8674eade6898ada7f.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/0.199ce3cb8a77f8cdacc6.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/2.6d901cb11cfe009fbad1.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/1.ec6328bb8c70ff506134.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/defaultVendors~preload-authenticated-routes~shared-document.61e34553279dbade6925.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/defaultVendors~preload-authenticated-routes~preload-multiplayer-editor.5fc968dd126f10e22c36.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/defaultVendors~preload-authenticated-routes.1f33d703cf832ed8eb31.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/default~login~preload-authenticated-routes~shared-document.a302760a884ba189799c.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/default~preload-authenticated-routes~shared-document.f07d0438d4e70c596416.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/preload-authenticated-routes.9019e1c4c3a948e87f9a.js
> [HTTP/1.1 200 OK 0ms]
> 
> SingleFile is hooking the IntersectionObserver API to detect and load deferred images. single-file-hooks-frames.js:1:531
> GETwss://outline.example.example.com/realtime/?EIO=4&transport=websocket
> [HTTP/1.1 101 Switching Protocols 72ms]
> 
> GEThttps://outline.example.example.com/static/defaultVendors~preload-document~preload-shared-editor~shared-document.7b614e410c64104b4e20.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/defaultVendors~collection~preload-document~shared-document.495506e34b869fc7beee.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/default~preload-document~preload-shared-editor~shared-document.a676f228008bc591956b.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/default~collection~preload-document~shared-document.365d60bbcd1b1f255ddc.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/default~preload-document~shared-document.3710085a733d6a7526dc.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/preload-document.9c061118d8c52c605a55.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/command-bar.e3bc31e8a8b9d21abe87.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://secure.gravatar.com/avatar/f2661755c0717db4f330c1fde5562b63?s=80&d=identicon
> [HTTP/2 200 OK 27ms]
> 
> GEThttps://outline-data.example.example.com/outline-bucket/public/c05e9cae-9a1b-4dfb-8430-cb439261ff2b/5f774d8c-b60c-4651-8661-c004792f2f5e/DBMI_Logo.png
> [HTTP/1.1 200 OK 60ms]
> 
> GEThttps://outline.example.example.com/images/apple-touch-icon.png
> [HTTP/1.1 200 OK 25ms]
> 
> GEThttps://outline.example.example.com/images/favicon-32.png
> [HTTP/1.1 200 OK 25ms]
> 
> GEThttps://outline.example.example.com/static/locale-time.f3b851ffe38b22bbface.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/defaultVendors~preload-multiplayer-editor~preload-shared-editor.24dabf075e26451f3639.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/defaultVendors~preload-multiplayer-editor.27284c28ffc012ae14e4.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/preload-shared-editor.8d28c8dbf3b304c572e4.js
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttps://outline.example.example.com/static/preload-multiplayer-editor.7babbee5b450c9888632.js
> [HTTP/1.1 200 OK 0ms]
> 
> GETwss://outline.example.example.com/collaboration/document.00272346-2ad0-4946-a185-ba1f51c9c590
> [HTTP/1.1 101 Switching Protocols 75ms]
> 
> GEThttps://outline.example.example.com/images/mermaidjs.png
> [HTTP/1.1 200 OK 182ms]
> 
> GEThttps://outline.example.example.com/images/airtable.png
> [HTTP/1.1 200 OK 216ms]
> 
> GEThttps://outline.example.example.com/images/codepen.png
> [HTTP/1.1 200 OK 224ms]
> 
> GEThttps://outline.example.example.com/images/clickup.png
> [HTTP/1.1 200 OK 241ms]
> 
> GEThttps://outline.example.example.com/images/descript.png
> [HTTP/1.1 200 OK 229ms]
> 
> GEThttps://outline.example.example.com/images/dbdiagram.png
> [HTTP/1.1 200 OK 228ms]
> 
> GEThttps://outline.example.example.com/images/framer.png
> [HTTP/1.1 200 OK 229ms]
> 
> GEThttps://outline.example.example.com/images/figma.png
> [HTTP/1.1 200 OK 229ms]
> 
> GEThttps://outline.example.example.com/images/gliffy.png
> [HTTP/1.1 200 OK 250ms]
> 
> GEThttps://outline.example.example.com/images/github-gist.png
> [HTTP/1.1 200 OK 242ms]
> 
> GEThttps://outline.example.example.com/images/google-drawings.png
> [HTTP/1.1 200 OK 253ms]
> 
> GEThttps://outline.example.example.com/images/diagrams.png
> [HTTP/1.1 200 OK 252ms]
> 
> GEThttps://outline.example.example.com/images/google-docs.png
> [HTTP/1.1 200 OK 259ms]
> 
> GEThttps://outline.example.example.com/images/google-drive.png
> [HTTP/1.1 200 OK 254ms]
> 
> GEThttps://outline.example.example.com/images/google-slides.png
> [HTTP/1.1 200 OK 266ms]
> 
> GEThttps://outline.example.example.com/images/google-sheets.png
> [HTTP/1.1 200 OK 260ms]
> 
> GEThttps://outline.example.example.com/images/google-forms.png
> [HTTP/1.1 200 OK 272ms]
> 
> GEThttps://outline.example.example.com/images/google-datastudio.png
> [HTTP/1.1 200 OK 271ms]
> 
> GEThttps://outline.example.example.com/images/google-calendar.png
> [HTTP/1.1 200 OK 273ms]
> 
> GEThttps://outline.example.example.com/images/loom.png
> [HTTP/1.1 200 OK 287ms]
> 
> GEThttps://outline.example.example.com/images/grist.png
> [HTTP/1.1 200 OK 288ms]
> 
> GEThttps://outline.example.example.com/images/lucidchart.png
> [HTTP/1.1 200 OK 288ms]
> 
> GEThttps://outline.example.example.com/images/marvel.png
> [HTTP/1.1 200 OK 293ms]
> 
> GEThttps://outline.example.example.com/images/mindmeister.png
> [HTTP/1.1 200 OK 295ms]
> 
> GEThttps://outline.example.example.com/images/miro.png
> [HTTP/1.1 200 OK 292ms]
> 
> GEThttps://outline.example.example.com/images/prezi.png
> [HTTP/1.1 200 OK 305ms]
> 
> GEThttps://outline.example.example.com/images/scribe.png
> [HTTP/1.1 200 OK 303ms]
> 
> GEThttps://outline.example.example.com/images/spotify.png
> [HTTP/1.1 200 OK 252ms]
> 
> GEThttps://outline.example.example.com/images/trello.png
> [HTTP/1.1 200 OK 253ms]
> 
> GEThttps://outline.example.example.com/images/whimsical.png
> [HTTP/1.1 200 OK 284ms]
> 
> GEThttps://outline.example.example.com/images/vimeo.png
> [HTTP/1.1 200 OK 285ms]
> 
> GEThttps://outline.example.example.com/images/typeform.png
> [HTTP/1.1 200 OK 284ms]
> 
> GEThttps://outline.example.example.com/images/youtube.png
> [HTTP/1.1 200 OK 286ms]
> 
> GEThttps://secure.gravatar.com/avatar/f2661755c0717db4f330c1fde5562b63?s=80&d=identicon
> GEThttps://outline.example.example.com/images/favicon-32.png
> [HTTP/1.1 200 OK 21ms]

```

**Comment by tommoor** [comment]
It seems like there was a regression but it works correctly when some text is selected first
