### ISSUE TITLE
Command "sequelize:migrate" not found.

### ISSUE THREAD

**Issue by florian-sabonchi** [outline/outline#4772]
updating outline wiki to version [0.67.2](https://hub.docker.com/layers/outlinewiki/outline/0.67.2/images/sha256-1c18ac3b2b2b841f0211b940ece531f13e564c8d0bca51249d0c9e137ef1629f?context=explore)  occurs in following error  yarn run v1.22.18
outline  | error Command "sequelize:migrate" not found.

**Comment by florian-sabonchi** [comment]
![image](https://user-images.githubusercontent.com/54689374/214548238-d93cfe47-81c7-4750-9f62-0059e61dad2a.png)

**Comment by florian-sabonchi** [comment]
outline  | yarn run v1.22.18
outline  | error Command "sequelize:migrate" not found.
outline  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
outline  | yarn run v1.22.18
outline  | error Command "sequelize:migrate" not found.
outline  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
outline  | yarn run v1.22.18
outline  | error Command "sequelize:migrate" not found.
outline  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
outline  | yarn run v1.22.18
outline  | error Command "sequelize:migrate" not found.
outline  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
outline  | yarn run v1.22.18
outline  | error Command "sequelize:migrate" not found.
outline  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
outline  | yarn run v1.22.18
outline  | error Command "sequelize:migrate" not found.
outline  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tommoor** [comment]
`sequelize:migrate` is no longer included, `db:migrate` is still available
