### ISSUE TITLE
Email notification: A wrong team member is identified as the one who edited a document 

### ISSUE THREAD

**Issue by BK-Countly** [outline/outline#4779]
**The issue appears in email notifications.** 

**What happens:** 
The email states a member (who only has VIEWING rights) recently edited a document. 
The member is a person who has been recently added to Outline. 
While in reality, the person who edited the document is either myself or someone else from the team who has editing rights. 

**Expected behavior**
The correct member of the team is identified in the email notifications as the person who recently edited a doc.

**Outline** 
- Install: getoutline.com

**Desktop**
 - macOS 12.6
 - Browser Chrome

**Comment by tommoor** [comment]
Please email hello@getoutline.com with more details on the document and user so we can investigate.
