### ISSUE TITLE
Some UX improvements to the document explorer

### ISSUE THREAD

**Issue by apoorv-mishra** [outline/outline#4785]
Now that we've [factored out document explorer](https://github.com/outline/outline/pull/4763) from publish modal, some possible UX improvements to it could be:

- [x] ~Smoothly~ scroll children into view as an item is expanded
- [ ] Prioritize recently viewed items in search results
- [x] ~Highlight matches in bold, in search results~

**Comment by tommoor** [comment]
I'm not sold on the last one, on a small list like this lots of highlights in the results is more distracting than useful

**Comment by tommoor** [comment]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/380914/215338812-50381932-9a2d-4302-bb25-5c58b4970962.png">

I don't think we need to display the document name twice, can lose the last part of the breadcrumb.
