### ISSUE TITLE
Serious bug with editing

### ISSUE THREAD

**Issue by gkozyrev** [outline/outline#4789]
**To Reproduce**
1. Create a new doc
2. Type the title
3. Click on white space, you won't see a cursor
4. Use "e" hotkey to edit document
5. Try to input the document content, no content is visible
6. Re-open the document and you'll see the text you typed

**Expected behavior**
Text is visible on input.

**Outline (please complete the following information):**
- Install: getoutline.com and self-hosted
- Version: [v0.67.2](https://github.com/outline/outline/releases/tag/v0.67.2)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome and Safari

<img width="999" alt="image" src="https://user-images.githubusercontent.com/27163035/215217718-8d5b9604-61ad-4af7-9735-007d81630d01.png">

**Comment by tommoor** [comment]
It would be useful if you post a video of the behavior you're seeing, where are you clicking that you don't see a cursor? There is no need to press "e" to edit if you're already typing the title then you're already editing so the report is a bit confusing.

**Comment by gkozyrev** [comment]
Sure, here is the video
Sorry about quality, Github has 10 Mb limit

https://user-images.githubusercontent.com/27163035/215222867-acddfafb-d366-4ea7-a66b-cb84040846af.mov

**Comment by tommoor** [comment]
Interesting, I suspect that your server does not have a websocket connection to the collaboration server which would be a configuration issue with the reverse proxy you're running (search discussions) – that wouldn't explain if you're able to reproduce this on getoutline.com though

**Comment by gkozyrev** [comment]
On getoutline.con I have the same behaviour, but getoutline workspace is old, I created a new one and it works fine

**Comment by tommoor** [comment]
If it's old the trial would have finished and it would be read-only, this might look like the same behavior

**Comment by gkozyrev** [comment]
It might be a Websocket issue then.
I have a WEBSOCKET=True flag in https-portal, what else should I check?

**Comment by gkozyrev** [comment]
<img width="537" alt="image" src="https://user-images.githubusercontent.com/27163035/215316714-78e2887a-7898-4904-a9c9-ce16d05019e4.png">
I've cheked a browser log, looks like page is loaded over HTTPS and edit tries to use insecure WS

**Comment by gkozyrev** [comment]
Found a solution here #4658 
Added HTTPS to URL
<img width="773" alt="image" src="https://user-images.githubusercontent.com/27163035/215317826-5890803d-9523-47c9-a6d3-fd693d4bb47b.png">

**Comment by gkozyrev** [comment]
Found a solution here #4658
Added HTTPS to URL

![](https://user-images.githubusercontent.com/27163035/215317826-5890803d-9523-47c9-a6d3-fd693d4bb47b.png)
