### ISSUE TITLE
Subscription for members

### ISSUE THREAD

**Issue by himself1985** [outline/outline#4801]
Hey,

a member has no possibility to receive an eMail via a subscription if something has changed.

![grafik](https://user-images.githubusercontent.com/32921808/215420211-98600322-932f-4cb7-8f59-6852696285a7.png)

**Outline:**
- Install: selfhosted
- Version: 0.67.2

**Desktop:**
 - OS: Windows
 - Browser Chrome, Firefox
 - Version: latest

**Comment by tommoor** [comment]
@apoorv-mishra take a look at this one? Should be something fairly straightforward with policies. I believe the reporter means that "viewer" role cannot subscribe/unsubscribe to documents

**Comment by apoorv-mishra** [comment]
Sure, will take a look sometime later today.

**Comment by himself1985** [comment]
No, I already mean the default user "member". They have no role. Don't know if this is a bug. 
But the "viewer" has the same problem.

![grafik](https://user-images.githubusercontent.com/32921808/215690358-b8d22260-e334-4cce-839a-b3f4cfe81c4b.png)

**Comment by apoorv-mishra** [comment]
But the screenshot that you just shared implies that this particular user is a "viewer", at least at the time the screenshot was taken. Did you change the role to member and then try? It'd be great if you list out the exact steps as outlined in the PR template. Although as part of this issue, one thing is clear that the "subscribe/unsubscribe" options are missing for the "viewer" - which surely is a bug as I understand.

**Comment by himself1985** [comment]
Sorry for the confusion. tommoor wrote that I would mean the role viewer. However, this is not the case. The problem exists both in the role member and in the role viewer. 

However, no member role is displayed in the user overview. Only viewer and administrator is displayed as role. In my opinion, this is also a bug.

**Comment by tommoor** [comment]
Please share more details about the document then, is this every document or just this document? And you said the problem exists with all user roles?

You cannot subscribe to archived, deleted, or draft documents – could it be one of those?

**Comment by apoorv-mishra** [comment]
Meanwhile, "viewer" should be able to subscribe/unsubscribe @tommoor ?
