### ISSUE TITLE
Multiple Mermaid diagrams on a page make it deadly slow

### ISSUE THREAD

**Issue by chimit** [outline/outline#4802]
Multiple Mermaid diagrams on a page make it deadly slow. Scrolling lags, and any typing in the code has huge delays (a few seconds between a keyboard press and a letter appearing on the page).

**To Reproduce**
1. Create multiple Mermaid diagrams on a page

**Expected behavior**
It should be fast.

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 0.66.2

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 16.2

**Comment by tommoor** [comment]
I put 8 diagrams on a page and it seems just fine, keypresses are rendered within 10ms – perhaps some diagrams are much slower than others? If you can export the problematic document as Markdown then we can investigate from there

**Comment by chimit** [comment]
@tommoor, here is an [example](https://gist.github.com/chimit/195c187d4c39f9a6e74fc00bc5f071aa). Just paste it into a new document, save, reopen, and try to edit any chart. You will see very long reaction on any key press.

**Comment by cocoonkid** [comment]
I just tried this out and can confirm as soon as you edit the source the typing reaction times become incredible slow.

**Comment by chimit** [comment]
This is still relevant.
