### ISSUE TITLE
Was removing the sequelize:migrate command intentional?

### ISSUE THREAD

**Issue by thomasgriffin** [outline/outline#4803]
In my [tutorial on self installing Outline on Ubuntu](https://thomasgriffin.com/how-to-install-the-outline-knowledge-base-wiki-on-ubuntu/), someone recently left a comment with this error:

```
yarn run v1.22.18
error Command “sequelize:migrate” not found.
```

I went back through the logs and saw that a couple of weeks ago, a change was made to replace the `sequelize:migrate` command: https://github.com/outline/outline/commit/0d53e5a7ba109c855f5f48bd392e1bb8d9011146

Specifically, this line was the one impacted: https://github.com/outline/outline/commit/0d53e5a7ba109c855f5f48bd392e1bb8d9011146#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L21

I assume that if this was intentional, it should be replaced with the `yarn db:migrate` command instead?

**Comment by tommoor** [comment]
Yes, that's correct – the line was a duplicate and it doesn't make sense to expose the ORM the app happens to use to end-users 👍

**Comment by thomasgriffin** [comment]
> Yes, that's correct – the line was a duplicate and it doesn't make sense to expose the ORM the app happens to use to end-users 👍

Agree, makes sense! Thanks for confirming. I've updated the tutorial to reflect the change.
