### ISSUE TITLE
cannot move a document using keyboard shortcut 'm'

### ISSUE THREAD

**Issue by bmm-alc** [outline/outline#4831]
Pressing key `m` on a page does not present the UI to move the page, where using the right-menu does.

**To Reproduce**
1. Go to any webpage
2. Press key `m`
3. nothing happens

I can see in the URL bar the text `/move` is appended to the current URL during few tens of seconds then disappears

**Expected behavior**
have the move dialog to appear

**Screenshots**
n/a

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 0.67.2

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 109.1

**Comment by apoorv-mishra** [comment]
Fixed as part of #4787 , will probably be shipped in the upcoming release.
