### ISSUE TITLE
Workspace Switch ?

### ISSUE THREAD

**Issue by Winniepoom** [outline/outline#4843]
Hello I'm new here, I just want to create another workspace for my team but I can't see that feature in my self host outline, And I checking turn out you have to Send an API Request to switch/create to another team right ?, I'm not sure that I'm doing right or wrong here please correct me.
```
curl -X 'POST' \
  'https://myweb.com/api/auth.info' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer API_TOKEN' \
  -d '"availableTeams": [
      {
        "id": "348cdb53-1359-4e07-a271-1e5c3da9c1b3",
        "name": "Team2",
        "avatarUrl": "https://avatars.slack-edge.com/2018-08-23/425852290820_ce39c81f910fdd0d929f_230.png",
        "url": "https://team2web.com",
        "isSignedIn": true
      }
    ]'
```

**Comment by tommoor** [comment]
Hi, this feature is not currently available in self hosted edition. It has not been built
