### ISSUE TITLE
File Attachments Converted to Links

### ISSUE THREAD

**Issue by alxjsn** [outline/outline#4853]
I'm not quite sure when this started happening, but after I upload a file attachment it gets converted to a link instead of a button. Previous file uploads still look like this:

![image](https://user-images.githubusercontent.com/3642823/217957148-8ce1b37a-e998-455c-b9df-832db147505f.png)

Now when I upload a file it shows a button, but as soon as I click on "Done Editing" it shows up like this:

![image](https://user-images.githubusercontent.com/3642823/217957308-d92c88fc-c3d9-42af-a889-253d30026676.png)

This behavior (attachment getting converted to a link) combined with the fact that my bucket is on the same domain means I never see a network request and instead get soft-redirected to a not found page when clicking on a file attachment.

![image](https://user-images.githubusercontent.com/3642823/217957562-72a83988-e399-4023-8bc2-2deeed830b07.png)

I can still visit the direct link in another tab and it works, but within the application it just leads me to a not found message.

I am self-hosting Outline with Minio as the backend. So for my setup it looks like

**App**: https://wiki.example.com/

**Bucket**: https://wiki.example.com/outline-bucket/public/edff02bb-a53a-46f3-83aa-a74fb981910e/012b1a0e-86ba-4adf-8d71-84480099e135/doc.pdf

Previously uploaded files still work fine.

**Outline (please complete the following information):**
- Install: self hosted
- Version: 9cb85ddfc3ea

**Comment by tommoor** [comment]
weird, what is the exact content of the link href?

**Comment by alxjsn** [comment]
Here is an example:

```<a href="https://wiki.example.com/outline-bucket/public/edff02bb-a53a-46f3-83aa-a73fb981910e/dd971252-bc60-4dae-3222-ea6b5221a714/quote.pdf" rel="noopener noreferrer nofollow">quote.pdf 730122</a>```

**Comment by tommoor** [comment]
What is the value of `AWS_S3_ACL` in your configuration?

**Comment by alxjsn** [comment]
It's set to `AWS_S3_ACL=public-read`. I am able to download the file by accessing the URL directly in another tab.

I noticed that the hrefs for previous file attachments used an `attachments.redirect` parameter instead of using the direct file URL.
