### ISSUE TITLE
Can't delete/unpublish documents from admin API key

### ISSUE THREAD

**Issue by kerberjg** [outline/outline#4857]
When attempting to delete/unpublish a document via the API, I receive the following error:
`{"ok":false,"error":"authorization_error","status":403,"message":"Authorization error"}`
...however read operations work just fine.

**To Reproduce**
1. Create API token with admin account
2. 
```bash
curl --fail-with-body -s -H 'Accept: application/json' -H 'Content-Type: application/json' -H "Authorization: Bearer ${TOKEN}" -X POST "${ENDPOINT}/api/documents.archive" -d "{ \"id\": \"$DOCUMENT_ID)\"}"
```

**Expected behavior**
A HTTP 200 response.

**Outline (please complete the following information):**
- Install: Docker, self-hosted
- Version: 0.67.2

If it helps, here's the result of `/api/auth.info`:
```json
{
  "data": {
    "user": {
      "id": "[REDACTED]",
      "name": "James Kerber",
      "avatarUrl": "[REDACTED]",
      "color": "#9E5CF7",
      "isAdmin": true,
      "isSuspended": false,
      "isViewer": false,
      "createdAt": "2022-08-09T14:02:29.993Z",
      "updatedAt": "2023-02-10T14:39:14.230Z",
      "lastActiveAt": "2023-02-10T14:39:14.227Z",
      "email": "[REDACTED]",
      "language": "en_US",
      "preferences": null
    },
    "team": {
      "id": "[REDACTED]",
      "name": "Wiki",
      "avatarUrl": "[REDACTED]",
      "sharing": true,
      "memberCollectionCreate": true,
      "collaborativeEditing": true,
      "defaultCollectionId": null,
      "documentEmbeds": true,
      "guestSignin": false,
      "subdomain": "[REDACTED]",
      "domain": null,
      "url": "[REDACTED]",
      "defaultUserRole": "member",
      "inviteRequired": false,
      "allowedDomains": [],
      "preferences": null
    },
    "availableTeams": [
      {
        "id": "[REDACTED]",
        "name": "Wiki",
        "avatarUrl": "[REDACTED]",
        "url": "[REDACTED]",
        "isSignedIn": true
      }
    ]
  },
  "policies": [
    {
      "id": "[REDACTED]",
      "abilities": {
        "createApiKey": true,
        "createAttachment": true,
        "createAuthenticationProvider": true,
        "createCollection": true,
        "importCollection": true,
        "createDocument": true,
        "createFileOperation": true,
        "createImport": true,
        "createExport": true,
        "createIntegration": true,
        "createNotificationSetting": true,
        "inviteUser": true,
        "read": true,
        "share": true,
        "createTeam": false,
        "update": true,
        "manage": true,
        "createGroup": true,
        "listWebhookSubscription": true,
        "createWebhookSubscription": true
      }
    }
  ],
  "status": 200,
  "ok": true
}
```

**Comment by tommoor** [comment]
You cannot archive a draft, deleted, or already archived document. Can you check this isn't the case

**Comment by kerberjg** [comment]
Yes, I can confirm: not a draft, not deleted, not archived.
...however they also appear to be non-existent either?

I obtain their list with:
`curl --fail-with-body -s -H 'Accept: application/json' -H 'Content-Type: application/json' -H "Authorization: Bearer ${TOKEN}" -X POST "${ENDPOINT}/api/documents.list" -d "{ \"limit\": 100, \"offset\": 0, \"parentDocumentId\": \"${PARENT_UUID}\"}" | jq -r '.data[].id'`

and then proceed to:
```bash
for i in $(curl --fail-with-body -s -H 'Accept: application/json' -H 'Content-Type: application/json' -H "Authorization: Bearer ${TOKEN}" -X POST "${ENDPOINT}/api/documents.list" -d "{ \"limit\": 100, \"offset\": 0, \"parentDocumentId\": \"${PARENT_UUID}\"}" | jq -r '.data[].id'); do
    echo ${i}
    curl --fail-with-body -s -H 'Accept: application/json' -H 'Content-Type: application/json' -H "Authorization: Bearer ${TOKEN}" -X POST "${ENDPOINT}/api/documents.info" -d "{ \"id\": \"$i)\"}"
done
```

which seems to yield `{"ok":false,"error":"not_found","status":404,"message":"Resource not found"}`

**Comment by kerberjg** [comment]
Ok, solved the mystery: it appears they won't be found unless I specify the `parentDocumentId` in the request.

Is this expected behavior for nested documents? If so, the error messages are a bit unclear: I get a 404 for read operations, 403 for update/delete

**Comment by tommoor** [comment]
Not expected behavior, in fact `parentDocumentId` is not used in the lookup at all – quite the mystery!

**Comment by elidrissidev** [comment]
> You cannot archive a draft, deleted, or already archived document. Can you check this isn't the case

I also get `403` when I try to archive a document, but I found an additional condition in policies that prevents from archiving if document is not published. So maybe that's the explanation for the first issue.

**Comment by ZorgeR** [comment]
Can't delete 2 unpublished document from frontend.

https://outline.z-lab.me/api/documents.delete
return
{"success":true,"status":200,"ok":true}

but document still in unpublished.

Also can't publish this document.
https://outline.z-lab.me/api/documents.info
say
{"ok":false,"error":"not_found","status":404,"message":"Resource not found"}

**Comment by ZorgeR** [comment]
Can't delete unpublished drafts documents
![image](https://user-images.githubusercontent.com/925105/220932301-358b3225-4887-4e11-b1bc-d6aed97ea7e4.png)

Also if try to create new documents it converted to drafts un has Untitled header

**Comment by KMakowsky** [comment]
I have nearly the same problem as @kerberjg, I have a draft document and it cannot be deleted, published or moved. The document is Untitled and title changes are not persistent, but content changes are. The document gets listed via documents.drafts and documents.delete requests answer with 200 success, but the documents stays where it is.

**Comment by ZorgeR** [comment]
@KMakowsky same here.

**Comment by apoorv-mishra** [comment]
Spent some time investigating this and here are the minimum reproducible steps,

1. Create a new collection.
2. Create a doc within the new collection and add a title or some text(so that the system doesn't auto-delete it).
3. Delete the new collection.
4. Click on "Trash" section and then navigate to "Drafts". Notice that the document created in (2) above appears under "Drafts".
5. Attempt to delete the document.

The `documents.delete` call is successful but document isn't actually removed. So, apparently there are two problems here. Firstly, collection deletion should've moved the document under it to "Trash". Secondly, the document should've been deleted via the `documents.delete` call anyway.

**Comment by ZorgeR** [comment]
Issue is not fixed yeat:
![image](https://github.com/outline/outline/assets/925105/386e8627-1e9f-41c0-a808-177f424b9c50)

**Comment by ZorgeR** [comment]
Can't delete drafts.
