### ISSUE TITLE
"Disregard changes" warning when saving the document

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#488]
This seems to be pretty broken now.

**Comment by tommoor** [comment]
I've not really pinned down exactly when this happens - it definitely does sometimes, but not all the time.

**Comment by jorilallo** [comment]
I noticed that reloading a document in edit view, it brings the warning up once loading the document

**Comment by jorilallo** [comment]
<img width="1177" alt="screen shot 2018-01-01 at 5 35 29 pm" src="https://user-images.githubusercontent.com/31465/34472594-30f29086-ef1a-11e7-803f-c88295775d11.png">

The following document content causes prompt to be shown when I reload the content. I think this is due to trailing newlines on the codeblock that are not shown in the document and maybe that's why the editor think they differ?

    # Blockquote testing
    > Every man regards his own life as the New Year's Eve of time.
    
    Some subpar quote from the interwebs
    
    ```
    well hello
    another
    vcvc
    :)
    
    
    ```

**Comment by tommoor** [comment]
I can't reproduce with this markdown unfortunately, I think it's a function of your local cache.
