### ISSUE TITLE
v0.68 - Self-Hosted - Displaying Slack login Option

### ISSUE THREAD

**Issue by flyingfishflash** [outline/outline#4880]
Hi, I'm self hosting outline - appreciate the wonderful software!

Since updating to 0.68, the Slack login option is being displayed despite it not being configured?

Login:
![screen_print](https://user-images.githubusercontent.com/75092045/219073416-e07c642c-a93a-4c9a-8f11-086f2cebed09.png)

Security Configuration:
![screen_print](https://user-images.githubusercontent.com/75092045/219076858-97d02b59-6f9c-4ea8-992d-648dae60a16d.png)

Container Initialization:
```
podman create \
 --pod=outline \
 --name=outline-app \
 -e AWS_ACCESS_KEY_ID=redacted \
 -e AWS_SECRET_ACCESS_KEY=redacted \
 -e AWS_REGION=us-east-1 \
 -e AWS_S3_UPLOAD_BUCKET_URL=https://redacted \
 -e AWS_S3_UPLOAD_BUCKET_NAME=outline \
 -e AWS_S3_UPLOAD_MAX_SIZE=26214400 \
 -e AWS_S3_FORCE_PATH_STYLE=true \
 -e AWS_S3_ACL=private \
 -e DATABASE_URL=postgres://outline:outline@outline-postgresql:5432/outline \
 -e FORCE_HTTPS=false \
 -e NODE_ENV=production \
 -e OIDC_AUTH_URI=https://redacted/oauth/v2/authorize \
 -e OIDC_TOKEN_URI=https://redacted/oauth/v2/token \
 -e OIDC_USERINFO_URI=https://redacted/oidc/v1/userinfo \
 -e OIDC_USERNAME_CLAIM=redacted \
 -e OIDC_DISPLAY_NAME=Zitadel \
 -e OIDC_SCOPES="openid profile email" \
 -e OIDC_CLIENT_ID=redacted \
 -e OIDC_CLIENT_SECRET=redacted \
 -e PGSSLMODE=disable \
 -e PORT=3000 \
 -e REDIS_URL=redis://redacted \
 -e SECRET_KEY=redacted\
 -e URL=https://redacted \
 -e UTILS_SECRET=redacted \
 --label io.containers.autoupdate=registry \
 --log-driver=journald \
 --log-opt=tag=podman/outline-app \
 --net outline \
 --network-alias outline-app \
 -p 53451:3000 \
 --pull=newer \
 registry.redacted/docker.io/outlinewiki/outline:latest sh -c "yarn db:migrate --env production-ssl-disabled && yarn start"
```

**Comment by tommoor** [comment]
Do you know did you have Slack setup at one point in time?

**Comment by danielslyman** [comment]
Hey there, I also thank you for this wonderful option. I can report the same issue, the button switches place with other auth method when clicked. I never setup Slack before.

Grateful for any help!

**Comment by flyingfishflash** [comment]
I can export my content and import it to a new instance, and probably this would fix it, but I just wanted to report it otherwise. Maybe it's related to PR #4794 

I can also peruse the db when I have a chance, to see if config shows any old slack related entries.

**Comment by tommoor** [comment]
Yes I’m sure it’s related and most likely a bug, just not sure of the particular data that causes it to happen yet

**Comment by BlackIPS** [comment]
Hey there,

I'm sorry to tell you, that I'm running into the same issue as mentioned before. I'm self-hosting outline through docker-compose with the suggested docker-compose.yml except https-portal service as I'm using NGiNX as reverse proxy.

Before creating the container I'd removed all slack related env variables from the provided .env file but still got Slack as a authentication provider.

**Comment by alxjsn** [comment]
I'm also experiencing this issue. Never set up Slack auth before and it started showing up now in my self-hosted setup.

**Comment by lordpayder** [comment]
Hi, same issue here.
Initial and working setup with keycloak, slack button still showing.

**Comment by DimitriDR** [comment]
Hi. Same here.
IIRC, It reappeared because there was a problem with Slack not appearing with specific conditions, so I'm pretty sure, they re-enabled it to fix this problem. Can't find the issue and/or the PR about it, but It's linked.

**Comment by tommoor** [comment]
The change was made to show all authentication options that are configured in the env.

Unfortunately with Slack specifically it's the same config options for auth as it is for the Slack integration, so anyone that has added the `SLACK_` variables to set up the Slack integration will now see the auth option too. The way forward on this one isn't clear yet

**Comment by tommoor** [comment]
closed in 66b5dd0a2

**Comment by ovizii** [comment]
I still can't get rid of the “login with slack” option in the backend. On the frontend I only see the option to log in with email as expected though.
Is nobody else bothered by this?

![image](https://user-images.githubusercontent.com/837902/230120065-6ebf8751-e3ea-437a-bb76-666a4ca26de8.png)

![image](https://user-images.githubusercontent.com/837902/230120210-1ea4f2b2-822a-4eb0-b76d-1fa93982aa31.png)

**Comment by DimitriDR** [comment]
> I still can't get rid of the “login with slack” option in the backend. On the frontend I only see the option to log in with email as expected though. Is nobody else bothered by this?
> 
> ![image](https://user-images.githubusercontent.com/837902/230120065-6ebf8751-e3ea-437a-bb76-666a4ca26de8.png)
> 
> ![image](https://user-images.githubusercontent.com/837902/230120210-1ea4f2b2-822a-4eb0-b76d-1fa93982aa31.png)

I don't see it. I only see my SSO.

**Comment by nmapx** [comment]
@ovizii make sure to remove all `SLACK_*` env vars
then it won't show up

**Comment by ovizii** [comment]
Thanks but I guess I'm giving up. I have all SLACK_* variables commented out in docker-compose.yml as well as in .env I did a docker compose down and docker compose up -d and the option is still there :-( 
I guess my OCD has to live with this issue seeing that it works for everyone else except me.
