### ISSUE TITLE
0.68.0 is not the version being pulled during install or upgrade docker. 

### ISSUE THREAD

**Issue by brianvess** [outline/outline#4884]
I tried to update 0.67.2 to version 0.68.0 and the outline pod just kept restarting. I set up outline on a new docker server and was able to get logged in but the version shows 0.60.3. 20 versions behind. I have verified I have stated the latest tag and also tagged with version 0.68.0.

**Comment by brianvess** [comment]
<img width="990" alt="Screenshot 2023-02-15 at 9 14 04 PM" src="https://user-images.githubusercontent.com/53948675/219275678-4940bcaa-b0e9-4ca9-8ebf-acf44ae48bce.png">

**Comment by vgwidt** [comment]
You should check the logs on the the container that keeps restarting, it should give a hint as to why.  As for the new Docker server, what do you get with `docker pull outlinewiki/outline`?
