### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by wojiaozhangyang** [outline/outline#4886]
The following problem occurred when I exported data in a self-managed knowledge base

Export data on the page    "/settings/export"

This is the error I got when I looked at the system log after starting the project through pm2
{"error":"File size (3760230340) is greater than 2 GB","stack":"RangeError [ERR_FS_FILE_TOO_LARGE]: File size (3760230340) is greater than 2 GB\n    at new NodeError (node:internal/errors:363:5)\n     at readFileHandle (node:internal/fs/promises:325:11)\n    
 at async ExportMarkdownZipTask.perform (/data/code/outline/build/server/queues/tasks/ExportMarkdownZipTask.js:73:26)\n    
 at async Queue.<anonymous> (/data/code/outline/build/server/services/worker.js:132:7)","level":"error",  "message":"Error processing task in ExportMarkdownZipTask"}
{"name":"fileOperations.update","modelId":"046344e0-b4e1-432b-917b-74ecb0b7e777","attempt":0,"label":"worker","level":"info","message":"Processing fileOperations.update"}

**Desktop (please complete the following information):**
 - OS:  ubuntu20.0    CPU:8      RAM:16
 - Browser [chrome]
 - Version [0.65.0]

**Comment by tommoor** [comment]
2gb is the maximum size of a file in node, it seems like you've hit that. You should export individual collections separately instead

**Comment by brianvess** [comment]
export for json export stuck at processing for three hours and continuing  

<img width="1037" alt="Screenshot 2023-02-16 at 10 02 13 PM" src="https://user-images.githubusercontent.com/53948675/219564750-f4a43b49-b296-4c93-8705-9730bb5108c0.png">

**Comment by brianvess** [comment]
I can’t do any exports. They all hang. Brian VessOn Feb 17, 2023, at 3:17 PM, Tom Moor ***@***.***> wrote:﻿
Closed #4886 as completed.

**Comment by brianvess** [comment]
I don't understand why this keeps getting closed. I can revert back to the previous version of the application and export. When I upgrade 0.68.1 I cannot export the collection. Export now has been processing for one month. If you can point me to how to gather logs that I do not see I will provide them. 
![Screen Shot 2023-03-27 at 10 18 22 AM](https://user-images.githubusercontent.com/53948675/228017539-3eba2e87-c18d-4a7e-bc2c-3e0c6589b4a4.png)
