### ISSUE TITLE
error Command "sequelize:migrate" not found.

### ISSUE THREAD

**Issue by wdfxl** [outline/outline#4887]
Im upgrade version outline

docker-compose pull
docker-compose down && docker-compose up 

docker logs outlinewiki/outline:latest

yarn run v1.22.18
error Command "sequelize:migrate" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by JensSpanier** [comment]
See note here: https://github.com/outline/outline/releases/tag/v0.67.2

> Note: `sequelize:migrate` is no longer included as a command, if you were using this then use `db:migrate` instead.
