### ISSUE TITLE
pull  0.68.0 error

### ISSUE THREAD

**Issue by wojiaozhangyang** [outline/outline#4889]
I pulled yesterday's submission without changing any code

From the version that runs properly to the version that runs incorrectly

INFO  git : SHA:  490d05b68b8412c97d581f39d31f73ac600660d5
1: git pull origin main
INFO  git : SHA:  2cd5d0e6245e27cf2e8b323b9576caff74e90b5b
2: yarn  build
3: yarn  dev:watch

The following error is displayed in the Google Browser console.

![image](https://user-images.githubusercontent.com/26091105/219566967-58583130-8860-4d06-a060-2ae936369db5.png)

The home page shows nothing, only three error messages

OS: ubuntu20.0 CPU:8 RAM:16
Browser [chrome]
Version [ latest ]

**Comment by tommoor** [comment]
It looks like you're running in development mode, you should be running in production mode – NODE_ENV=production

**Comment by wojiaozhangyang** [comment]
When I tried to run yarn start, it worked properly. But when I run yarn dev:watch, the above error is reported. How can it run properly in the development mode
