### ISSUE TITLE
Article display exception when sharing

### ISSUE THREAD

**Issue by zyifan** [outline/outline#4890]
Article editing mode display is normal
![image](https://user-images.githubusercontent.com/19355902/219568119-97fae2d3-b899-4a57-a695-779fefd2b5ac.png)

sharing is abnormal
![image](https://user-images.githubusercontent.com/19355902/219568403-9f3b869d-5b11-4977-8c10-adbda8b44640.png)

**Comment by tommoor** [comment]
Wrapping this into #3000 as it's the only way it'll be fixed
