### ISSUE TITLE
Export for JSON stuck processing after upgrade to .067.3 to 0.68.0

### ISSUE THREAD

**Issue by brianvess** [outline/outline#4891]
<img width="1037" alt="Screenshot 2023-02-16 at 10 02 13 PM" src="https://user-images.githubusercontent.com/53948675/219570075-29a2351f-2055-4f15-9ce5-00ba43331b80.png">

Troubleshooting setups
rolled back to the previous version and upgraded again. 
shell to the pod and looked for processes to possibly kill and could not find anything. 
The load on the pod is low.

**Comment by tommoor** [comment]
Export to JSON is a new feature, please check the server logs for any errors after triggering an export.

**Comment by brianvess** [comment]
Exporting any export either as HTML, markdown hangs and never completes.

**Comment by brianvess** [comment]
what other details are needed?

**Comment by tommoor** [comment]
As mentioned before, the server logs would contain any errors.

**Comment by brianvess** [comment]
I am running outline in docker. I shelled into the container and could not find the logs. Can u give me a location that you would like me to pull logs?  I also followed the the docker container logs with no info. Brian VessOn Feb 18, 2023, at 7:43 AM, Tom Moor ***@***.***> wrote:﻿
As mentioned before, the server logs would contain any errors.

**Comment by tommoor** [comment]
The logs are written to `stdout` and `stderr`.

**Comment by ZorgeR** [comment]
Also has issue with export / import

3 month of importing - in processing state
![image](https://user-images.githubusercontent.com/925105/220933156-dc8046d3-8a14-4b3b-a726-3c84cfaa12c0.png)

restart / reload / nothing help...

**Comment by brianvess** [comment]
I have upgraded to the latest version 0.69. I am still not able to export any collection. I have attached logs

{"label":"http","level":"info","message":"  --> GET /static/images/whimsical.png 200 3ms 10.54kb"}
{"label":"http","level":"info","message":"  <-- GET /static/images/youtube.png"}
{"label":"http","level":"info","message":"  --> GET /static/images/youtube.png 200 3ms 1.38kb"}
{"label":"http","level":"info","message":"  <-- GET /static/images/zapier.png"}
{"label":"http","level":"info","message":"  --> GET /static/images/zapier.png 200 3ms 2.34kb"}
{"label":"http","level":"info","message":"  <-- GET /static/manifest.webmanifest"}
{"label":"http","level":"info","message":"  --> GET /static/manifest.webmanifest 200 2ms 412b"}
{"userId":"936214a6-40bc-4c5e-b77f-558e2fc04335","label":"worker","level":"info","message":"ValidateSSOAccessTask running"}
{"id":"69ae17f1-dcd2-4044-8c04-4263ff8c510b","userId":"936214a6-40bc-4c5e-b77f-558e2fc04335","label":"utils","level":"info","message":"Refreshing expiring access token"}
{"error":"Authentication required","stack":"UnauthorizedError: Authentication required\n    at AuthenticationError (/opt/outline/build/server/errors.js:38:34)\n    at OIDCClient.rotateToken (/opt/outline/build/server/utils/oauth.js:65:47)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async UserAuthentication.refreshAccessTokenIfNeeded (/opt/outline/build/server/models/UserAuthentication.js:122:24)\n    at async UserAuthentication.validateAccess (/opt/outline/build/server/models/UserAuthentication.js:79:7)\n    at async Promise.all (index 0)\n    at async /opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:31:21\n    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:507:18\n    at async ValidateSSOAccessTask.perform (/opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:18:5)\n    at async Queue.<anonymous> (/opt/outline/build/server/services/worker.js:109:7)","level":"error","message":"Error processing task in ValidateSSOAccessTask"}
{"userId":"936214a6-40bc-4c5e-b77f-558e2fc04335","label":"worker","level":"info","message":"ValidateSSOAccessTask running"}
{"id":"69ae17f1-dcd2-4044-8c04-4263ff8c510b","userId":"936214a6-40bc-4c5e-b77f-558e2fc04335","label":"utils","level":"info","message":"Refreshing expiring access token"}
{"error":"Authentication required","stack":"UnauthorizedError: Authentication required\n    at AuthenticationError (/opt/outline/build/server/errors.js:38:34)\n    at OIDCClient.rotateToken (/opt/outline/build/server/utils/oauth.js:65:47)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async UserAuthentication.refreshAccessTokenIfNeeded (/opt/outline/build/server/models/UserAuthentication.js:122:24)\n    at async UserAuthentication.validateAccess (/opt/outline/build/server/models/UserAuthentication.js:79:7)\n    at async Promise.all (index 0)\n    at async /opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:31:21\n    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:507:18\n    at async ValidateSSOAccessTask.perform (/opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:18:5)\n    at async Queue.<anonymous> (/opt/outline/build/server/services/worker.js:109:7)","level":"error","message":"Error processing task in ValidateSSOAccessTask"}
{"label":"http","level":"info","message":"  <-- POST /api/fileOperations.list"}
{"label":"http","level":"info","message":"  --> POST /api/fileOperations.list 200 153ms 885b"}
{"label":"http","level":"info","message":"  <-- POST /api/collections.export_all"}
{"label":"http","level":"info","message":"  --> POST /api/collections.export_all 200 120ms 824b"}
{"event":{"id":"dc858288-27a4-4a32-804a-19e626e7cb7d","name":"fileOperations.create","teamId":"1ebe5319-0bb9-4fcc-801b-d22bdfca125b","actorId":"936214a6-40bc-4c5e-b77f-558e2fc04335","modelId":"058e1554-f3a3-4a40-acd9-f482891afaae","collectionId":null,"ip":"199.87.14.15","data":{"type":"export","format":"outline-markdown"},"createdAt":"2023-04-24T16:57:49.988Z","userId":null,"documentId":null},"attempt":0,"label":"worker","level":"info","message":"Processing fileOperations.create"}
{"event":{"id":"dc858288-27a4-4a32-804a-19e626e7cb7d","name":"fileOperations.create","teamId":"1ebe5319-0bb9-4fcc-801b-d22bdfca125b","actorId":"936214a6-40bc-4c5e-b77f-558e2fc04335","modelId":"058e1554-f3a3-4a40-acd9-f482891afaae","collectionId":null,"ip":"199.87.14.15","data":{"type":"export","format":"outline-markdown"},"createdAt":"2023-04-24T16:57:49.988Z","userId":null,"documentId":null},"label":"worker","level":"info","message":"FileOperationsProcessor running fileOperations.create"}
{"fileOperationId":"058e1554-f3a3-4a40-acd9-f482891afaae","label":"worker","level":"info","message":"ExportMarkdownZipTask running"}
{"label":"task","level":"info","message":"ExportTask fetching data for 058e1554-f3a3-4a40-acd9-f482891afaae"}
{"event":{"id":"dc858288-27a4-4a32-804a-19e626e7cb7d","name":"fileOperations.create","teamId":"1ebe5319-0bb9-4fcc-801b-d22bdfca125b","actorId":"936214a6-40bc-4c5e-b77f-558e2fc04335","modelId":"058e1554-f3a3-4a40-acd9-f482891afaae","collectionId":null,"ip":"199.87.14.15","data":{"type":"export","format":"outline-markdown"},"createdAt":"2023-04-24T16:57:49.988Z","userId":null,"documentId":null},"label":"worker","level":"info","message":"WebhookProcessor running fileOperations.create"}
{"label":"task","level":"info","message":"ExportTask processing data for 058e1554-f3a3-4a40-acd9-f482891afaae"}
{"event":{"id":"e07a84b5-74b1-439c-b0dc-fdcf9baf52ba","createdAt":"2023-04-24T16:57:50.243Z","name":"fileOperations.update","modelId":"058e1554-f3a3-4a40-acd9-f482891afaae","teamId":"1ebe5319-0bb9-4fcc-801b-d22bdfca125b","actorId":"936214a6-40bc-4c5e-b77f-558e2fc04335","data":{"id":"058e1554-f3a3-4a40-acd9-f482891afaae","type":"export","format":"outline-markdown","name":"WebsoftPC-export.zip","state":"creating","error":null,"size":"0","collectionId":null,"user":{"id":"936214a6-40bc-4c5e-b77f-558e2fc04335","name":"Brian Vess","avatarUrl":"https://minio.websoftpc.com/outline/public/936214a6-40bc-4c5e-b77f-558e2fc04335/4d1b4295-7872-4002-ab7d-f61f3a96242a/kisspng-yoda-luke-skywalker-jedi-computer-icons-children-chair-5addf50a871355.1139938815244956265533.png","color":"#9E5CF7","isAdmin":true,"isSuspended":false,"isViewer":false,"createdAt":"2022-09-30T22:19:05.219Z","updatedAt":"2023-04-24T16:57:20.798Z","lastActiveAt":"2023-04-24T16:57:20.796Z"},"createdAt":"2023-04-24T16:57:49.974Z","updatedAt":"2023-04-24T16:57:49.974Z"}},"attempt":0,"label":"worker","level":"info","message":"Processing fileOperations.update"}
{"event":{"id":"e07a84b5-74b1-439c-b0dc-fdcf9baf52ba","createdAt":"2023-04-24T16:57:50.243Z","name":"fileOperations.update","modelId":"058e1554-f3a3-4a40-acd9-f482891afaae","teamId":"1ebe5319-0bb9-4fcc-801b-d22bdfca125b","actorId":"936214a6-40bc-4c5e-b77f-558e2fc04335","data":{"id":"058e1554-f3a3-4a40-acd9-f482891afaae","type":"export","format":"outline-markdown","name":"WebsoftPC-export.zip","state":"creating","error":null,"size":"0","collectionId":null,"user":{"id":"936214a6-40bc-4c5e-b77f-558e2fc04335","name":"Brian Vess","avatarUrl":"https://minio.websoftpc.com/outline/public/936214a6-40bc-4c5e-b77f-558e2fc04335/4d1b4295-7872-4002-ab7d-f61f3a96242a/kisspng-yoda-luke-skywalker-jedi-computer-icons-children-chair-5addf50a871355.1139938815244956265533.png","color":"#9E5CF7","isAdmin":true,"isSuspended":false,"isViewer":false,"createdAt":"2022-09-30T22:19:05.219Z","updatedAt":"2023-04-24T16:57:20.798Z","lastActiveAt":"2023-04-24T16:57:20.796Z"},"createdAt":"2023-04-24T16:57:49.974Z","updatedAt":"2023-04-24T16:57:49.974Z"}},"label":"worker","level":"info","message":"WebhookProcessor running fileOperations.update"}
{"label":"http","level":"info","message":"  <-- GET /settings/export"}
{"label":"http","level":"info","message":"  --> GET /settings/export 200 41ms 1.2kb"}
{"label":"http","level":"info","message":"  <-- GET /static/manifest.webmanifest"}
{"label":"http","level":"info","message":"  --> GET /static/manifest.webmanifest 200 3ms 412b"}
{"label":"http","level":"info","message":"  <-- POST /api/auth.info"}
{"label":"http","level":"info","message":"  <-- GET /locales/en_US.json"}
{"label":"http","level":"info","message":"  --> POST /api/auth.info 200 19ms 2.35kb"}
{"label":"http","level":"info","message":"  --> GET /locales/en_US.json 200 164ms 10.95kb"}
{"label":"http","level":"info","message":"  <-- GET /opensearch.xml"}
{"label":"http","level":"info","message":"  --> GET /opensearch.xml 200 3ms 567b"}
{"label":"http","level":"info","message":"  <-- POST /api/fileOperations.list"}
{"label":"http","level":"info","message":"  --> POST /api/fileOperations.list 200 31ms 1.61kb"}
{"label":"http","level":"info","message":"  <-- GET /"}
{"label":"http","level":"info","message":"  --> GET / 200 85ms 7.04kb"}
{"label":"http","level":"info","message":"  <-- GET /"}
{"label":"http","level":"info","message":"  --> GET / 200 125ms 7.04kb"}
{"label":"http","level":"info","message":"  <-- GET /"}
{"label":"http","level":"info","message":"  --> GET / 200 238ms 7.04kb"}
{"label":"multiplayer","level":"info","message":"New connection to \"document.cd952795-9231-4d32-ba63-00d361bb73ba\""}
{"label":"database","level":"info","message":"Document cd952795-9231-4d32-ba63-00d361bb73ba is in database state"}
{"userId":"d513857d-2f1d-4bd9-a89f-01761b1b7da5","label":"multiplayer","level":"info","message":"Loaded document \"document.cd952795-9231-4d32-ba63-00d361bb73ba\""}
{"label":"http","level":"info","message":"  <-- GET /"}
{"label":"http","level":"info","message":"  --> GET / 200 75ms 7.04kb"}
{"label":"http","level":"info","message":"  <-- GET /settings/export"}
{"label":"http","level":"info","message":"  --> GET /settings/export 200 69ms 1.2kb"}
{"label":"http","level":"info","message":"  <-- GET /static/manifest.webmanifest"}
{"label":"http","level":"info","message":"  --> GET /static/manifest.webmanifest 200 5ms 412b"}
{"label":"http","level":"info","message":"  <-- GET /locales/en_US.json"}
{"label":"http","level":"info","message":"  <-- POST /api/auth.info"}
{"label":"http","level":"info","message":"  --> GET /locales/en_US.json 200 260ms 10.95kb"}
{"label":"http","level":"info","message":"  --> POST /api/auth.info 200 313ms 2.35kb"}
{"label":"http","level":"info","message":"  <-- GET /opensearch.xml"}
{"label":"http","level":"info","message":"  --> GET /opensearch.xml 200 2ms 567b"}
{"label":"http","level":"info","message":"  <-- POST /api/fileOperations.list"}
{"label":"http","level":"info","message":"  --> POST /api/fileOperations.list 200 69ms 1.61kb"}
{"label":"http","level":"info","message":"  <-- POST /api/documents.drafts"}
{"label":"http","level":"info","message":"  <-- POST /api/documents.list"}
{"label":"http","level":"info","message":"  <-- POST /api/collections.list"}
{"label":"http","level":"info","message":"  <-- POST /api/stars.list"}
{"label":"http","level":"info","message":"  <-- POST /api/documents.viewed"}
--
{"label":"http","level":"info","message":"  --> GET / 200 104ms 7.04kb"}
{"label":"http","level":"info","message":"  <-- GET /"}
{"label":"http","level":"info","message":"  --> GET / 200 100ms 7.04kb"}
{"label":"http","level":"info","message":"  <-- POST /api/documents.drafts"}
{"label":"http","level":"info","message":"  <-- POST /api/pins.list"}
{"label":"http","level":"info","message":"  <-- POST /api/documents.viewed"}
{"label":"http","level":"info","message":"  <-- POST /api/documents.list"}
{"label":"http","level":"info","message":"  <-- POST /api/collections.list"}
{"label":"http","level":"info","message":"  <-- POST /api/stars.list"}
{"label":"http","level":"info","message":"  --> POST /api/pins.list 200 551ms 156b"}
{"label":"http","level":"info","message":"  --> POST /api/stars.list 200 287ms 158b"}
{"label":"http","level":"info","message":"  --> POST /api/documents.list 200 678ms 5.04kb"}
{"label":"http","level":"info","message":"  --> POST /api/documents.drafts 200 741ms 30.16kb"}
{"label":"http","level":"info","message":"  --> POST /api/collections.list 200 404ms 78.52kb"}
{"label":"http","level":"info","message":"  --> POST /api/documents.viewed 200 807ms 138.67kb"}
{"label":"http","level":"info","message":"  <-- POST /api/collections.export"}
{"label":"http","level":"info","message":"  --> POST /api/collections.export 200 167ms 841b"}
{"event":{"id":"365f74bb-cee4-4723-9fcf-1bcb97585950","name":"fileOperations.create","teamId":"1ebe5319-0bb9-4fcc-801b-d22bdfca125b","actorId":"936214a6-40bc-4c5e-b77f-558e2fc04335","modelId":"f018c6a9-ebf9-4bd1-9dda-e5be0799b3fb","collectionId":"827975cf-901c-4b1e-b94d-8a30b933f141","ip":"199.87.14.15","data":{"type":"export","format":"outline-markdown"},"createdAt":"2023-04-24T17:19:35.531Z","userId":null,"documentId":null},"attempt":0,"label":"worker","level":"info","message":"Processing fileOperations.create"}
{"event":{"id":"365f74bb-cee4-4723-9fcf-1bcb97585950","name":"fileOperations.create","teamId":"1ebe5319-0bb9-4fcc-801b-d22bdfca125b","actorId":"936214a6-40bc-4c5e-b77f-558e2fc04335","modelId":"f018c6a9-ebf9-4bd1-9dda-e5be0799b3fb","collectionId":"827975cf-901c-4b1e-b94d-8a30b933f141","ip":"199.87.14.15","data":{"type":"export","format":"outline-markdown"},"createdAt":"2023-04-24T17:19:35.531Z","userId":null,"documentId":null},"label":"worker","level":"info","message":"FileOperationsProcessor running fileOperations.create"}
{"event":{"id":"365f74bb-cee4-4723-9fcf-1bcb97585950","name":"fileOperations.create","teamId":"1ebe5319-0bb9-4fcc-801b-d22bdfca125b","actorId":"936214a6-40bc-4c5e-b77f-558e2fc04335","modelId":"f018c6a9-ebf9-4bd1-9dda-e5be0799b3fb","collectionId":"827975cf-901c-4b1e-b94d-8a30b933f141","ip":"199.87.14.15","data":{"type":"export","format":"outline-markdown"},"createdAt":"2023-04-24T17:19:35.531Z","userId":null,"documentId":null},"label":"worker","level":"info","message":"WebhookProcessor running fileOperations.create"}
{"label":"http","level":"info","message":"  <-- POST /api/fileOperations.list"}
{"label":"http","level":"info","message":"  --> POST /api/fileOperations.list 200 59ms 2.37kb"}
{"label":"http","level":"info","message":"  <-- GET /"}
{"label":"http","level":"info","message":"  --> GET / 200 109ms 7.04kb"}
{"label":"http","level":"info","message":"  <-- GET /"}
{"label":"http","level":"info","message":"  --> GET / 200 70ms 7.04kb"}

**Comment by tommoor** [comment]
I would check the memory and network usage on the box during the export, there are no related errors listed in your logs. It could be that the generated zip file is just too large for the server to construct
