### ISSUE TITLE
AWS_S3_UPLOAD_MAX_SIZE variable ignored when importing existing documents

### ISSUE THREAD

**Issue by Alex-Orsholits** [outline/outline#4899]
When attempting to import data via the JSON or Notion importer (I have tested only these two), I receive the error that the file size exceeds 5.12MB. This is despite my environment variable being set to just under 5GB. It also fails to work with the default variable value of 26214400. Files beyond 5.12MB uploaded to documents do not have the same issue. 

**To Reproduce**
1. Go to Preferences - Import
2. Click on one of the data import methods
3. Select a valid file beyond 5.12MB
4. See HTTP 400 error claiming file larger than upload limit

**Expected behavior**
File is uploaded according to AWS_S3_UPLOAD_MAX_SIZE variable set in docker.env

**Screenshots**

**Outline (please complete the following information):**
- Install: self hosted
- Version: [5c6475f](https://github.com/outline/outline/commit/5c6475f776d8c36fc8d3aef8063980743d8dd1da) (v0.68.1)

**Desktop (please complete the following information):**

**Mobile (please complete the following information):**
 - Device: Desktop Computer
 - OS: Windows 10 
 - Browser: Chrome

**Comment by tommoor** [comment]
Ah yea, the import limit is separate as these files are temporary by nature. You can update it with `MAXIMUM_IMPORT_SIZE` – I'll change this to use the larger of the two values though if `AWS_S3_UPLOAD_MAX_SIZE` is set to a larger size.
