### ISSUE TITLE
Linenumbering in code blocks are broken (Linux)

### ISSUE THREAD

**Issue by quickstar** [outline/outline#4901]
The line numbering is displayed horizontally instead of vertically

**Expected behavior**
The line numbering should be vertically

**Screenshots**
![image](https://user-images.githubusercontent.com/1195919/220056168-130728f7-f5e8-46c1-8905-8aead8a6fb03.png)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.68.1

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - Firefox (109.0.1), Chrome (110.0.5481.100)

**Comment by tommoor** [comment]
Which browser? Why didn’t you fill out the bug report template…

**Comment by quickstar** [comment]
> Which browser? Why didn’t you fill out the bug report template…

You're right, sorry my bad! Done 👍🏽
