### ISSUE TITLE
Space key with image selected should zoom the image

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4913]
Currently it replaces the image with a space character 😄

**Comment by adityash1** [comment]
I would like to work on this. Do you have any suggestions before I look into it ?

**Comment by adityash1** [comment]
there are two files outline/shared/editor/nodes/SimpleImage.tsx

**Comment by adityash1** [comment]
I've been trying for some time to fix this.

**Comment by adityash1** [comment]
I've been trying to fix this.

I've tried to add event listeners for keydown the imagezoom's implementation but didn't work
`shared/editor/components/ImageZoom`

Do i need to do something in `/shared/editor/components/Image.tsx` ?
I've tried many things but nothing worked. can you help a bit ?

**Comment by tommoor** [comment]
The `Space` key needs to be handled inside an editor plugin, see Mention or Placeholder for some examples of keyboard handling:
https://github.com/apoorv-mishra/outline/blob/de031b365c4d8ac38bdc9080d8a9fead8a31c4d0/shared/editor/nodes/Mention.ts#L79

Here, you can intercept the event, check that the focused node is an image node, zoom in and `return true` to indicate to Prosemirror (the editor framework) that the event was handled and it shouldn't perform default behavior.
