### ISSUE TITLE
Images attachments no longer work v0.68.1

### ISSUE THREAD

**Issue by C8opmBM** [outline/outline#4914]
All image uploads are 404

I get a 404 every time I try to upload an image.
Seems that AWS_S3_UPLOAD_BUCKET_URL isn't respected anymore, it readirect to main web instead of my minio bucket.
so from` wiki.domain.com` to `wiki.domain.com/outline` (thus 404) instead of `wikidata.domain.com/outline` where my bucket is.

It used to work just fine.

Thanks!

**Comment by tommoor** [comment]
Going to need more details here, nothing really changed regarding the behavior of S3 in the last release. A video or logs would be great

**Comment by C8opmBM** [comment]
I'm really sorry for the trouble, I doubled check all my envs, and it seems that during migrating to envs in separate file,  I somehow copied the `AWS_S3_UPLOAD_BUCKET_URL` with a missing L in the end, causing all this mess.
It works as expected now, thank you for your reply and have a great day!
