### ISSUE TITLE
Docker: MAXIMUM_IMPORT_SIZE not working

### ISSUE THREAD

**Issue by philiplorenz-code** [outline/outline#4915]
I use outlinewiki/outline:0.68.1 and want to import data from another instance. When trying to import the data I get following error:

{
    "ok": false,
    "error": "validation_error",
    "status": 400,
    "message": "Sorry, this file is too large – the maximum size is 5.12 MB"
}

![image](https://user-images.githubusercontent.com/84645793/220740220-80e32d39-59e5-43db-9112-1964d6eacd11.jpeg)

I already modified the .env-file:
MAXIMUM_IMPORT_SIZE=81920000

I do not know what else I could do. Is there any way to manual import data?

 

**To Reproduce**
-

**Expected behavior**
Should upload the zip-file.

**Screenshots**
![image](https://user-images.githubusercontent.com/84645793/220740234-b7ec9d61-4b77-437e-b50e-6db456062849.jpeg)

**Outline (please complete the following information):**
- Install: selfhosted docker compose
- Version: 0.68.1

**Comment by tommoor** [comment]
You can set `AWS_S3_UPLOAD_MAX_SIZE` to the larger size, this was addressed recently in https://github.com/outline/outline/commit/667ffdeaf112bed7e3d1e169dd20c3e70f97220d and will be fixed in the next release.

**Comment by philiplorenz-code** [comment]
> You can set `AWS_S3_UPLOAD_MAX_SIZE` to the larger size, this was addressed recently in [667ffde](https://github.com/outline/outline/commit/667ffdeaf112bed7e3d1e169dd20c3e70f97220d) and will be fixed in the next release.

Thanks a lot! I just added this to the .env-file:
AWS_S3_UPLOAD_MAX_SIZE=81920000

Afterwards I recreated the container, but I runs into the same error still. Is there anything I have to reset for this to work?

**Comment by TomTom101** [comment]
Same here, can't figure out what variable to change in order to allow uploads larger than 1Mb (attaching images are allowed up to exactly 1Mb in 0.74.0). All available env variables like AWS_S3_UPLOAD_MAX_SIZE, MAXIMUM_IMPORT_SIZE, FILE_STORAGE_UPLOAD_MAX_SIZE are set to much larger values to no avail.

**Comment by tommoor** [comment]
In that case Outline isn't the issue. Are you using Clouldflare? There is a 100mb limit on their free plan

**Comment by TomTom101** [comment]
It's locally hosted (proxmox). Uploads fail for images larger than 1Mb (not 100Mb).
