### ISSUE TITLE
Google https://datastudio.google.com links changed to https://lookerstudio.google.com

### ISSUE THREAD

**Issue by phaethon** [outline/outline#4952]
Google has rebranded Data Studio to Looker Studio and as part of that URL has changed. If I try to use feature to embed Datastudio into Outline, I get `Sorry, that link won't work for this embed type` When I manually change beginning of URL from https://lookerstudio.google.com/... to https://datastudio.google.com/... embedding works.

**Comment by Limezy** [comment]
You should be able to propose a very simple corrective PR by correcting this regex : 
https://github.com/outline/outline/blob/bb21fa725cc58bc7d397981483926df5837ed9f3/shared/editor/embeds/GoogleDataStudio.tsx#L28

**Comment by Limezy** [comment]
OK let me try to do that one
