### ISSUE TITLE
Line numbers shown in share mode

### ISSUE THREAD

**Issue by Limezy** [outline/outline#4954]
**To Reproduce**
1. Go to settings
2. Choose not to display line numbers in code blocks
3. Publish and share a document including a code block
4. Line numbers are shown in the public link

**Expected behavior**
No line number shown

**Outline (please complete the following information):**
- Install: self hosted
- Version: 18905535d36176a0058e54905d3d3daebf3bfbfc

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Safari, Orion
 - Version 16.1

**Comment by tommoor** [comment]
This is considered to be expected behavior, the line number setting is a personal preference, and the default is always to show them

**Comment by Limezy** [comment]
Makes sense !
A simple patch on my instance should do the trick
Thanks
