### ISSUE TITLE
Markdown editor license clarification

### ISSUE THREAD

**Issue by yasoob** [outline/outline#4965]
Hi team! Amazing work with this software. I had a question regarding the markdown editor. 

The original separate repo for the markdown editor has been archived. But this repo contains updated code for the editor. Can you share if the editor code is also under the same business license? What if someone wants to use it in a commercial software that doesn’t operate in the same domain as Outline?

Thanks 😊

**Comment by tommoor** [comment]
> Can you share if the editor code is also under the same business license?

Yes, everything in this repository is covered by the BSL.

> What if someone wants to use it in a commercial software that doesn’t operate in the same domain as Outline?

That would be considered a breach of the license. I recommend using a true open source solution such as https://tiptap.dev/ which is licensed under MIT.

**Comment by yasoob** [comment]
Thanks for the speedy clarification! Appreciate it 😊
