### ISSUE TITLE
[BUG] Block of code line number display error

### ISSUE THREAD

**Issue by fangzhengjin** [outline/outline#5003]
**Screenshots**
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/12680972/223395618-c24d09d0-fdcd-4df7-95e5-f023b7aab0e4.png">

**Example**
 [example.md](https://github.com/outline/outline/files/10908411/example.md)

**Outline (please complete the following information):**
- Version: 0.68.1

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Edge
 - Version 110.0.1587.63

**Comment by tommoor** [comment]
Closed in https://github.com/outline/outline/commit/f0484c84179c0b3dd21468e6532aa40040a6fcad, will be in next release
