### ISSUE TITLE
The data is inconsistent after being exported and then imported on the Settings page

### ISSUE THREAD

**Issue by wojiaozhangyang** [outline/outline#5019]
1: I exported the data in the system Settings interface.

2: Replace the database with a new one with the same table structure

3: Import markdown on the page

problem

1: The image is inconsistent. The markdown format is /pubilc/ team id/ file name

After the import, it is not displayed

2: '** *' bold will be displayed in the page directly as a string, rather than the effect of bold

3: There are other formatting issues.

**Comment by tommoor** [comment]
Unfortunately Markdown is a lossy format, you should use the JSON import/export to ensure full fidelity.
