### ISSUE TITLE
Improve code formatting for PHP

### ISSUE THREAD

**Issue by binaryfire** [outline/outline#5021]
Hey Tom

The colorization of PHP code is a bit weird. Everything is blue. Strings should be a different color to variables. Any chance that this could be tweaked? Perhaps the wrong preset is being applied to the PHP option?

<img width="680" alt="image" src="https://user-images.githubusercontent.com/5361908/224532911-ae057c75-f6ea-4ea6-85ed-3ecff94e4180.png">

Thanks again for open sourcing such a great project.

**Comment by tommoor** [comment]
It does look particularly bad, could you screenshot the same code in your own editor?

**Comment by binaryfire** [comment]
Sure thing, here you go:

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/5361908/224606866-f1d2fd35-893b-43a7-a64f-d083e58f1683.png">

**Comment by binaryfire** [comment]
@tommoor Here's another example. The main issue is that strings and variables are the same color. Although the overall color choices could do with some tweaking if it's not too much hassle.

<img width="645" alt="image" src="https://user-images.githubusercontent.com/5361908/224607680-d94c6edf-9b84-493e-a72b-345ca7775d28.png">

vs

<img width="671" alt="image" src="https://user-images.githubusercontent.com/5361908/224607828-a749ce5c-54b1-47c9-aa81-b55a753fb91d.png">
