### ISSUE TITLE
Saving a document wipes code blocks clean

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#503]
Steps to repro:

1. Compose a document with a code block
2. Save
3. Code block is now empty

**Comment by jorilallo** [comment]
Seems to be due to Prism plugin

**Comment by tommoor** [comment]
I can't reproduce this 😬 - could you provide the markdown that reproduces it on your side?

**Comment by jorilallo** [comment]
derp, I think this was actually due to my dev branch 🤦‍♂️
