### ISSUE TITLE
@mentions shows users without access to the collection

### ISSUE THREAD

**Issue by tommoor** [outline/outline#5032]
**To Reproduce**
1. Make a collection "No access"
2. Go to a document within the collection
3. Type "@"
4. Users will appear that do not have access to the document / collection

**Expected behavior**
You should only be able to mention users with access

**Comment by tommoor** [comment]
The solve for this isn't exactly clear, we don't currently have an endpoint that you can search users within a collection (`collections.memberships` is close, but wouldn't include users that have access through a group), so we need to create that first.

Perhaps `collections.memberships` gains an option to include users in groups?

**Comment by apoorv-mishra** [comment]
Ideally, `collections.memberships` should include both collection users and users via collection groups? If this isn't happening currently, then it's an existing bug? If yes, then we're required to modify the `collections.memberships` endpoint itself to correct this behavior.

**Comment by tommoor** [comment]
It could _optionally_ as mentioned, but we don't want to change the default behavior here as this endpoint is used to list users that have been explicitly given access to a collection on the permissions screen
