### ISSUE TITLE
Prevent member to download/export in view permission Collections

### ISSUE THREAD

**Issue by vngvng** [outline/outline#5035]
go to Preferences > Security, Disable "Viewer document exports"

go to Collections Permission,
1. Default access: No access
2. Additional access: Add people to View Only

Result: Those member still can download Document to HTML / Markdown

**Comment by tommoor** [comment]
Interesting, this setting was designed originally to restrict those with "viewer" user accounts – not "member" users that are given viewer access to a specific collection. 

Agreed that it would be good to change this though
