### ISSUE TITLE
Upload failed when domain for s3 include word 'outline'

### ISSUE THREAD

**Issue by Suchyy** [outline/outline#5038]
**To Reproduce**
1. Use local minio as S3 provider.
2. Set domain with word 'outline' to point to S3 endpoint.
3. Try to upload a file.
4. Check dev console in browser - error POST 400.
5. Check network tab, endpoint for S3 not include bucket name after slash, only domain.

Example:
Endpoint for S3 - s3.minio.outline.example.com
Bucket - outline
ENV VAR AWS_S3_UPLOAD_BUCKET_URL=https://s3.minio.outline.example.com
ENV VAR AWS_S3_UPLOAD_BUCKET_NAME=outline

Solution:
Delete word 'outline' (create subdomain that not include this word) from s3 domain. I think this is the problem, after domain name change upload was successfull.

**Expected behavior**
Succesfull upload of file.

The newest versions from yesterday, both minio and outline.

**Comment by ohemelaar** [comment]
Is `outline` the name of your bucket? I think there is a weird specificity to S3 settings where the bucket endpoint should not contain the bucket name, which made me struggle a few months ago.
