### ISSUE TITLE
@mentions not updating when profile name is changed

### ISSUE THREAD

**Issue by Limezy** [outline/outline#5039]
**To Reproduce**
1. Include a @mention inside a document or a comment
2. Change profile name
3. @mention is not updated accordingly

**Expected behavior**
@mention should match the profile name, even retroactively

**Outline (please complete the following information):**
- Install: self hosted
- Version: d663b92

**Comment by tommoor** [comment]
This is by design to increase performance, the trade off is that the old names are embedded in documents and comments – but it should be a rare event that someone changes their name – particularly as we don't have usernames.

**Comment by Limezy** [comment]
Well noted, and indeed performance is big part of what makes Outline a joy to use !
