### ISSUE TITLE
Workspaces where no workspaces should be.

### ISSUE THREAD

**Issue by nullsumme** [outline/outline#5041]
Version: outlinewiki/outline:0.68.1

As fas as I know workspaces are not a feature for selfhosted solutions. Ok. But wait. What is that?

![image](https://user-images.githubusercontent.com/369577/225310054-48c6bb3f-edb7-4ceb-99a7-4c6d83a81fbf.png)

Workspaces! But they don't work. Instead they are making a mess:

1. Once a workspace is created I can't switch back. I'm stuck in the newly created workspace. Forever.
2. Sometimes new users login with our SSO and they get a new workspace. I don't know why and it is not possible for me to move them in our main workspace.

Thats kinda frustrating as it completely disrupt our work.

**Comment by tommoor** [comment]
Sounds like you have `DEPLOYMENT=hosted` set in your environment which will result in a lot of strange behavior, you should remove it

**Comment by nullsumme** [comment]
Sound correct. I removed this settings. Not sure why I put it there. I also fixed the team-missmatch directly in the database. 

Looks like it works. Thanks.

**Comment by tommoor** [comment]
If you know where it came from it would be good to find out, should be basically undocumented for this reason 😄
