### ISSUE TITLE
Code in list breaks the line number

### ISSUE THREAD

**Issue by oxodao** [outline/outline#5044]
When creating a code block while in a numbered list, the line number of the code block breaks

**To Reproduce**
1. Create a document
2. Type `1. Something <CR>` to create a numbered list
3. Use backspace to remove the `2.` while keeping the indent
4. Create a block code with multiple lines in it

**Expected behavior**
The line number should be on each line correctly

**Screenshots**
![Demo](https://i.imgur.com/AFAqu1l.png)

**Outline (please complete the following information):**
- Install: Self hosted
- Version: 5c6475f776d8c36fc8d3aef8063980743d8dd1da

**Comment by tommoor** [comment]
I'm unable to reproduce, browser and OS?
