### ISSUE TITLE
Drop `user.username` column

### ISSUE THREAD

**Issue by tommoor** [outline/outline#5050]
It has never been used for anything

**Comment by 98h398hrpohpoai** [comment]
Is this the case?
I'm running into the following on a new docker installation using both Authentik and Keycloak:

ERR Error during authentication | error=column user.username does not exist stack=UnauthorizedError: column user.username does not exist
    at AuthenticationError (/opt/outline/build/server/errors.js:38:34)
    at accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:118:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by ve7mjc** [comment]
Likewise. My install with ~15,000 documents is broken with the same error. Keycloak was provider. Investigating.

**Comment by ve7mjc** [comment]
Well - I believe the OIDC efforts in one or more of the latest releases seems to have resolved my issue. I was following rabbit-holes, determined that it was the interaction between my Keycloak instance (client config) and the existing authentication provider info in the database but alas, upgrading straight to 0.70.1 with the migrations has fixed my install. Thanks guys!
