### ISSUE TITLE
Free trial notice stops you moving the window properly on macOS

### ISSUE THREAD

**Issue by jfi** [outline/outline#5060]
**To Reproduce**
1. Don't pay for your trial to the point where you get a blue bar in the Outline macOS application stating "Your free trial is almost over, there are just 3 days left – please [add payment details](https://your-subdomain-here.getoutline.com/settings/billing) to avoid interruption for your team."
2. Attempt to move the window by dragging in the top band of pixels.
3. You can't move the window. You can move the window by clicking _below_ the blue bar and dragging.

Further fun: The blue bar _does_ respond to double click to expand the window.

**Expected behavior**
The blue bar acts like the top of the screen normally would.

**Screenshots**
![Screenshot 2023-03-18 at 16 42 07](https://user-images.githubusercontent.com/663625/226120762-42671592-5ead-4476-a835-757c6d73189b.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.0.1 (221204n5bjdkfng)

**Comment by tommoor** [comment]
We'll get this fixed up today, in the meantime you should be able to drag the area of the titlebar that's in the sidebar as a workaround.
