### ISSUE TITLE
Link typeahead not working

### ISSUE THREAD

**Issue by willblackmore** [outline/outline#5077]
When creating a link, the tooltip where you enter the URL used to search existing pages within Outline and suggest documents which could be linked to. This no longer works.

**To Reproduce**
1. Go to any page
2. Enter some text, highlight it and press CMD+K
3. Start entering the name of a page you know exists
4. The typeahead will not recommend that page (or any)

**Expected behavior**
The typeahead should recommend pages which match the string entered.

**Outline (please complete the following information):**
- Install: engageinteractive.getoutline.com

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 110

**Comment by tommoor** [comment]
Thanks Will, resolved now.
