### ISSUE TITLE
Resolving comments

### ISSUE THREAD

**Issue by tommoor** [outline/outline#5078]
Add support for counting a comment as resolved, this should:

- Hide it from the sidebar under resolved comments
- Send a notification to those in the thread

**Comment by aravinda0** [comment]
After introducing Outline to my team, this is the single biggest comment that I receive from newly onboarded users. Eagerly awaiting this feature.

**Comment by tommoor** [comment]
Currently planning this as a paid feature.

**Comment by Limezy** [comment]
A bit sad about this decision... Would you by chance consider a "sponsoring" licence that would have some features such as that one ?

**Comment by almereyda** [comment]
GitLab have this model where you're entitled to some premium features outside of their open core, if you are willing to send extended telemetry about your instance usage.

**Comment by almereyda** [comment]
Thanks for removing the *paid license* label.

Our users drowning in outdated open conversation threads scattered all over the place will appreciate it.

**Comment by thumDer** [comment]
I have just noticed it is available on outline.com, and rushed here to say thank you! :)

**Comment by tommoor** [comment]
Now released in https://github.com/outline/outline/releases/tag/v0.78.0
