### ISSUE TITLE
Clicking on the highlight should focus the associated comment

### ISSUE THREAD

**Issue by Limezy** [outline/outline#5081]
**To Reproduce**
1. Go to a document that has inline comments and open the comment side bar
2. Click on one of the blue highlights
3. The comment panel will scroll to the relevant associated comment
4. The scroll is not enough as the UX doesn't show clearly which comment is involved

**Expected behavior**
Fortunately, you have already built-in a focus mode for comments, shown when we click on one comment.
I believe that when clicking on a inline highlight in the document, there should be : 
* If not already, opening the comment side bar (already implemented)
* Scroll to the relevant comment (already implemented)
* Focus the relevant comment (expected additionnal behaviour)

**Outline (please complete the following information):**
- Install: self hosted
- Version: 68640860fb9cf584f155348ae06e4536226bef16

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser safari

**Comment by tommoor** [comment]
Yes, this worked at one point in development – I'm sure it's an easy fix 😄

**Comment by Limezy** [comment]
Thanks
