### ISSUE TITLE
Heading anchors are not stable

### ISSUE THREAD

**Issue by tommoor** [outline/outline#510]
The heading anchors include the node key which is not stable between reloads. This was added as an attempt to create a unique heading id for when headings appear multiple times in a document, so we'll need another strategy

**Comment by jorilallo** [comment]
Slug + index (if more than one) would probably do just fine

**Comment by tommoor** [comment]
Yea, the key was originally supposed to be a proxy for that. The problem is it's not necessarily easy to get the index of the heading from the render method… I'm sure there's a way though.
