### ISSUE TITLE
Images in document should have defined height to reserve space without reflow

### ISSUE THREAD

**Issue by Limezy** [outline/outline#5114]
**To Reproduce**
1. Create a page with a lot of images
2. Go to a link to one header of that page, such as https://yourdomain.com/s/yourdoc/#your-header
3. The page will scroll before it finishes to load all images, and will end up scrolled at a location higher than it should after images would load and "push down" the content

**Expected behavior**
Link to a header should scroll exactly to that header

**Outline (please complete the following information):**
- Install: self hosted
- Version: 68640860fb9cf584f155348ae06e4536226bef16

**Comment by tommoor** [comment]
I think the solution here is to properly reserve the space the correct height for loading images, rather than wait to scroll.

**Comment by Limezy** [comment]
That's right, I was wrongly assuming a solution instead of just presenting the problem - sorry !

**Comment by Limezy** [comment]
@tommoor unfortunately it still doesn't work on my instance. Freshly built on the latest commit at main branch

**Comment by tommoor** [comment]
Could it be that the docs your testing with have old images from before we introduced image resizing? These didn't have width and height dimensions stored, so it's not possible to create the placeholder there. Or are you also seeing issues with new uploaded and resized images?

**Comment by Limezy** [comment]
I think it's something about the old documents indeed ! Is there a way to "re-upload" the images automatically ?

**Comment by tommoor** [comment]
You can just resize the images and resize them back again, that should trigger the width and height to be stored in the document.

**Comment by Limezy** [comment]
Great ! Unfortunately I have tried with a document started yesterday, so under the new image resize internal scheme, and I still get an issue

**Comment by tommoor** [comment]
I'll take a look at Safari

**Comment by tommoor** [comment]
On further inspection the fix only works for resized images.
