### ISSUE TITLE
Zip import fails on windows zip files

### ISSUE THREAD

**Issue by thumDer** [outline/outline#5117]
Zip files created from folder structure of markdown files using native windows utility (file explorer - send to - compressed folder) cannot be imported via preferences - import - zip file, throws invalid collection error.

Zip files created from the same folder structure with **winrar** can be uploaded succesfully.

**Expected behavior**
All zip files should be processed, regardless of which tool it was created by.

Background: https://github.com/outline/outline/discussions/5092

**Screenshots**
![kép](https://user-images.githubusercontent.com/54556708/228496925-f8aa6a0d-c440-4548-8156-3f030d3b9df5.png)

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2
 - Browser Firefox
 - Version 11.0.1

**Comment by tommoor** [comment]
Are you able to upload a sample of the non-working zip?

**Comment by thumDer** [comment]
Sure, I've added it to the discussion but I'll put the here as well:
[outline-import-win.zip](https://github.com/outline/outline/files/11100584/outline-import-win.zip)
[outline-import-winrar.zip](https://github.com/outline/outline/files/11100585/outline-import-winrar.zip)
