### ISSUE TITLE
styling inconsistency

### ISSUE THREAD

**Issue by thumDer** [outline/outline#5126]
Accent color gets applied on Headings with links in light mode as per the workspace preferences.
Switching to dark mode the color of Headings with links turns to the default blue.
Links in paragraphs have no color applied at all

**Expected behavior**
Headings should keep their accented color in both appearance setting.
Links in paragraphs could be also accented

**Screenshots**
![kép](https://user-images.githubusercontent.com/54556708/228898968-848de819-cd46-42da-8c2e-091b2189225f.png)

![kép](https://user-images.githubusercontent.com/54556708/228898990-4c4dc935-aa27-4241-959c-6e5dbcf46f46.png)

**Outline (please complete the following information):**
- Install: getoutline.com 

**Desktop (please complete the following information):**
 - OS: Win11 Pro 22H2
 - Browser Firefox
 - Version 111.0.1

**Comment by tommoor** [comment]
Links in the text not being colored is a purposeful design decision, this difference on headings is a bug though.

**Comment by thumDer** [comment]
Okay, understood. Might there be an option in the future to use custom styling via an uploaded css on the cloud version?
