### ISSUE TITLE
Unfurling non-document links

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#513]
I shared Outline root in Slack and it didn't unfurl the link, which I think is due to Slack unfurling. @tommoor; you know if we can target this in Slack settings or do we need to do it in code?

**Comment by tommoor** [comment]
Boo. Slack settings only lets you choose per domain. We should just have a 'default' unfurl for any unknown link that can show the outline logo / name / description?

**Comment by tommoor** [comment]
For future reference, I pinged Slack about the ability to do this here: https://twitter.com/tommoor/status/956762160108994568

**Comment by tommoor** [comment]
Closing as #wontfix.
