### ISSUE TITLE
Bold text rendering inconsistencies between shared mode and member mode

### ISSUE THREAD

**Issue by Limezy** [outline/outline#5135]
For some of my document, strange artefacts will appear for viewers accessing through a public share link.
I'm not very sure about how to reproduce, but this seems to be mainly about how the bold or italic function is managed around emoticons.

**To Reproduce**
Steps to reproduce the behavior (EDIT: Managed to make a MWE)
1. Create a document
2. Write `HI(😀)` in it
3. Change only "HI" to be bold (but not the parenthesis)
4. Share that document
5. Access the public link through incognito browser mode
6. See the stars around the parenthesis

**Expected behavior**
Document should appear exactly the same whether it's viewed from a public shared link or by a member

**Screenshots**
Example. On the left, the member view. On the right, the public share view (Chrome browser)
<img width="1433" alt="Capture d’écran 2023-03-31 à 11 48 24" src="https://user-images.githubusercontent.com/24638389/229025503-6fdd88a4-9287-4216-b3b3-adc16503b0a7.png">

**Outline (please complete the following information):**
- Install: self hosted
- Version: ec3ebb91c08a7b03034e49e308dbce0a014ebc79

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome

**Comment by tommoor** [comment]
Unfortunately I can't reproduce with your example, could you paste the text of the exact couple of paragraphs here?
