### ISSUE TITLE
Allow search to filter by parent document

### ISSUE THREAD

**Issue by tommoor** [outline/outline#5139]
We also feel that it might be sometimes necessary to filter down the results to pages under a specific page, but afaik it is not yet possible. Could it be a feature request?
Like in confluence:
![kép](https://user-images.githubusercontent.com/54556708/229169662-de7ddd8c-2066-416d-9c4b-4794a30dcbd1.png)

_Originally posted by @thumDer in https://github.com/outline/outline/discussions/4902#discussioncomment-5490965_

**Comment by thumDer** [comment]
don't :(

**Comment by tommoor** [comment]
Huh?

**Comment by thumDer** [comment]
I've just tried to express my disappointment about the issue being closed by a bot due to inactivity, hoped to bump it.

**Comment by zombie0378** [comment]
reopen. please.
