### ISSUE TITLE
Outline Slack integration selfhosted results in eternal redirect

### ISSUE THREAD

**Issue by katlol** [outline/outline#5146]
**To Reproduce**
1. Go to <https://outline.example.com/settings/integrations/slack>
2. Click on Add to Slack
3. Get redirected to <https://example.slack.com/oauth?client_id=xxx&scope=commands+links%3Aread+links%3Awrite&user_scope=&redirect_uri=https%3A%2F%2Foutline.example.com%2Fauth%2Fslack.commands&state=f5980d7c-xxx-fc4b657be5fb&granular_bot_scope=0&single_channel=0&install_redirect=&tracked=1&team=> (see screenshot)

4. Click Allow
5. Redirect loop: https://outline.example.com/auth/slack.commands?code=xxxc5a757004c7c72b7&state=f5980d7c-xxx-fc4b657be5fb

**Expected behavior**

Slack Integration works

**Perhaps related to**
<https://github.com/outline/outline/blob/2e28a631b699cd7b29c896b6372118004bdc1412/plugins/slack/server/auth/slack.ts#L145-L157>

This code tries to redirect to a team subdomain. But those do not exist in selfhosted.

**Screenshots**
<img width="607" alt="image" src="https://user-images.githubusercontent.com/1695469/229503785-071f25cc-b3fd-480c-9cdb-2a438bd95e4b.png">

**Outline (please complete the following information):**
- Install: self hosted
- Version: docker image 

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome, Firefox Developer Edition
 - Version Chrome 111.0.5563.146, Firefox 112.0b9

**Comment by tommoor** [comment]
There is a redirect on client because with strict cookies the redirect back from Slack isn't able to access the currently authenticated session, so we basically refresh the page from the clientside to get the auth cookie.

If this is happening eternally then the auth cookie is not available to the server for some reason… it could be you're not forwarding through a proxy for example.

**Comment by katlol** [comment]
@tommoor Thank you for your reply. Outline is behind ingress-nginx and nothing special is happening wrt. cookies. How would I go about debugging this? Outline auth works well otherwise.

**Comment by tommoor** [comment]
Perhaps nginx has some logs as to which headers are being forwarded on the requests to Outline backend?

**Comment by katlol** [comment]
Thanks @tommoor. what headers does outline expect?

**Comment by tommoor** [comment]
In this case I'm referring specifically to cookie headers which the server uses to know if you're logged in

**Comment by tommoor** [comment]
closed in 3e5cd9eb3c98350981f41e2ffe3a0d9e222290a8
