### ISSUE TITLE
UX of Images with link

### ISSUE THREAD

**Issue by thumDer** [outline/outline#5156]
If there is a link pasted on an image, the context menu functions for the image are no longer available (alignment, replace image, etc). One has to remove the link to be able to access those functions again.
Also, it is a bit misleading, that hovering over an image with link results in the magnifier cursor, suggesting it will zoom in on the image, but it will navigate to the link.

**To Reproduce**
1. Insert an image
2. Highlight it
3. Paste an url link on it

**Expected behavior**
- Keep the original context menu functions accessible, but also let the user mannipulate the url.
- Show the hand cursor for images with links

**Screenshots**

With link:
![kép](https://user-images.githubusercontent.com/54556708/230168962-18965da1-57e0-4124-bdf6-8762f90fcc0c.png)

Without link:
![kép](https://user-images.githubusercontent.com/54556708/230168991-9d962aec-428b-47f5-b0c8-32d40a4f032e.png)

**Outline (please complete the following information):**
- Install: getoutline.com

**Comment by tommoor** [comment]
Interesting, it's not immediately clear what the best way forward is here – will need some thought to combine these two toolbars

**Comment by thumDer** [comment]
Here are my two ideas:
![kép](https://user-images.githubusercontent.com/54556708/230343405-4d399060-407c-487e-a083-4f64990e6336.png)

![kép](https://user-images.githubusercontent.com/54556708/230343440-2f6c73e5-aaf7-4553-bfca-803c112f857a.png)

**Comment by thumDer** [comment]
any updates on this?

**Comment by wuwei-yu** [comment]
I also encountered this problem. Outline is not very friendly to inserting markdown images.
