### ISSUE TITLE
Domain without www prefix doesn't work

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#516]

**Comment by tommoor** [comment]
Hmm, weird it's redirecting correctly for me. Is there a specific deep link that isn't working?

**Comment by jorilallo** [comment]
I think it might be your browser. I tried on mobile chrome and doesn't work. I have a simple redirect on DNSimple but that doesn't seem to be working so I'll just move it as part of the application

**Comment by jorilallo** [comment]
hmms looks like `http://` works but not `https://`

**Comment by jorilallo** [comment]
TIL https://support.dnsimple.com/articles/redirect-heroku/#redirect-https

**Comment by tommoor** [comment]
closed? Definitely makes sense to fix this in code
