### ISSUE TITLE
Make default order of documents in a collection alphabetical

### ISSUE THREAD

**Issue by tommoor** [outline/outline#517]
The order of documents can seem kind of arbitrary right now. It might be nice to:

- Have some preset orders (date / alphabetical)
- Allow manual reordering

Interested in your thoughts @jorilallo 
Suggested here https://spectrum.chat/notifications?thread=89f0bf35-3729-4c08-aca0-a9822ec48f3b

**Comment by jorilallo** [comment]
Right now it's roughly date based, or if moved, stuff goes ends up being the last one. There's backend support for ordering them but I don't know how we would do the UI for it (or what trade-off we should take there).

I'm kind of leaning towards alphabetical ordering which would give easy hacks for users to use numbers for re-ordering without much investment at this point until we know more about usage patterns.

**Comment by jasonquiz** [comment]
I would personally take alphabetical as a first step over it being ordered by last edit date.
