### ISSUE TITLE
Headings not automatically bold for Chinese characters

### ISSUE THREAD

**Issue by kingfungdesign** [outline/outline#5171]
As title suggested. True for both Traditional and Simplified Chinese.

**To Reproduce**
1. Writes heading in Chinese. (eg. 中文標題)

**Expected behavior**
Chinese headings should also show as bold.

**Screenshots**
![image](https://user-images.githubusercontent.com/52369186/230768403-83a7be04-6bc9-4f16-8dbf-8ccecd46505d.png)

**Outline (please complete the following information):**
- Install: getoutline.com

**Comment by tommoor** [comment]
This looks fine on Mac, I suspect this is an issue with the Windows typeface

**Comment by kingfungdesign** [comment]
![image](https://user-images.githubusercontent.com/52369186/231218073-e940071e-3c6f-4580-a057-c4e42e962f3e.png)
FWIW, this is how it looks on Firefox on Linux.

On Windows, the weight for English headings with or without Bold looks the same to me but on Linux the English headings are clearly different with and without bold. I suppose this behavior on Linux is the expected behavior.

**Comment by tommoor** [comment]
>  I suppose this behavior on Linux is the expected behavior.

If the above screenshot is with and without bolt it looks mostly correct, although I would prefer it if that top one was a little bolder. Linux is not exactly known for having great typography, of course.

I'm not sure there is anything actionable here, the issue seems to be at an OS level

**Comment by kingfungdesign** [comment]
![image](https://user-images.githubusercontent.com/52369186/231496686-dd492f28-05bb-4184-882a-c662c143b7d5.png)

fwiw, this is Notion on Windows which has a correct weighting for the headings.

**Comment by shanyan-wcx** [comment]
Not only the headings, but also all English default bold items such as links.
