### ISSUE TITLE
SSO Provider not working with new alias / secondary domain (Google Workspaces)

### ISSUE THREAD

**Issue by Jamira40** [outline/outline#5188]
**To Reproduce**
1. Added secondary Alias for few accounts. For example originaldomain.com and we added newdomain.com to our Google Workspace.
2. Whitelisted domain at Outline Administration. Currently have two domains.
3. Tried to login to Outline with Google Account that was previously registered with user@originaldomain.com but now its user@newdomain.com but same Workspace Account (ID is same)

**Error Logs**
`{"error":"User authentication 1051**********484 already exists for 931**********-54**-46**-86f3-5**********103, tried to assign to c88**********-ac**-4d**-8096-c**********a70","stack":"UnauthorizedError: User authentication 1051**********484 already exists for 931**********-54**-46**-86f3-5**********103, tried to assign to c88**********-ac**-4d**-8096-c**********a70\n    at AuthenticationError (/opt/outline/build/server/errors.js:38:34)\n    at accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:118:43)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","level":"error","message":"Error during authentication"}`

**Expected behavior**
Able to access same account and assign new email.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: Docker 0.68.0

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 110.0.5481.100

**Comment by Jamira40** [comment]
Looks similar to https://github.com/outline/outline/issues/4668

**Comment by tommoor** [comment]
Currently to overcome this you would need to manually add a new row to the `authentication_providers` table in the database with the new domain. There isn't any functionality in the UI built yet for this case.

**Comment by tommoor** [comment]
Merging into #1945
