### ISSUE TITLE
Issue with Drafts - can't correctly publish, stay as draft

### ISSUE THREAD

**Issue by ZorgeR** [outline/outline#5190]
**To Reproduce**
1. Try to create new document 
2. Fill the text of documents, and wait 1 minutes
3. Fill documents name
5. Press publish
6. .... And it's not published , also if press publish another time you will see many copy of unpublished documents in navigation
7.  This draft also can't be deleted

**Expected behavior**
Document has published with selected name

**Screenshots**
![image](https://user-images.githubusercontent.com/925105/231431684-25f0f8c9-207b-451d-984b-aa1c5eba2259.png)
![image](https://user-images.githubusercontent.com/925105/231431999-d22cad62-7fd8-4070-b849-e4ad32f9a1ac.png)

**Outline (please complete the following information):**
- Install: [self hosted]
- Version: [v0.68.1]

**Desktop:**
 - OS: Windows
 - Browser : Any

**Mobile (please complete the following information):**
 - Device: iPad
 - OS: [iOS14]
 - Browser [safari]

**Comment by tommoor** [comment]
This is pretty terrible, I've never seen this behavior before. Can you check that websockets are connecting correctly in the browser?

**Comment by denisinla** [comment]
@tommoor is there a threshold for running Outline on iOS versions older than v16? I am seeing said issue happen when testing on iOS14 as reported.

**Comment by tommoor** [comment]
None that I'm aware of, this is the first time such an issue has been reported.

**Comment by OLOrz996** [comment]
I have the same problem. 
![image](https://user-images.githubusercontent.com/11268446/232958537-f2017746-1f95-4621-bb19-9d699fd90f86.png)

**Comment by tommoor** [comment]
Still no idea what's going on here, I'd suggest trying the latest build `v0.69.1`
