### ISSUE TITLE
Cursor jumps at the end and title no longer remains editable

### ISSUE THREAD

**Issue by apoorv-mishra** [outline/outline#5198]
**To Reproduce**
1. Create a new document
2. Click on empty title field
3. Cursor jumps to the end of title input field and title can no longer be edited

**Expected behavior**
Cursor should remain at the start of title input field and input field should remain editable

**Outline (please complete the following information):**
- Install: self hosted
- Version: 7c44e116
- Browser: Firefox 111.0.1
- OS: Ubuntu 22.04.2

**Comment by apoorv-mishra** [comment]
Tried in Firefox?

https://user-images.githubusercontent.com/15694566/231942696-9485073d-a5b8-4b9b-8e77-de2a207816b7.mp4

**Comment by tommoor** [comment]
Yes, Firefox-specific 🙈

**Comment by thumDer** [comment]
happens here too, already wanted to post is, but I was too slow 🤐

**Comment by tommoor** [comment]
Firefox really is the worst… https://bugzilla.mozilla.org/show_bug.cgi?id=904846 (Bug open for 10 years)
