### ISSUE TITLE
Can't create a seed for existing users with seed.js

### ISSUE THREAD

**Issue by CaledoniaProject** [outline/outline#5200]
Can you update the seed.js to support existing users? I would like to generate a sign link when the user already exists, instead of prompting `Team already exists, aborting`

**Comment by tommoor** [comment]
You can use the in-app invite functionality for this

**Comment by CaledoniaProject** [comment]
@tommoor I need this for the local development environment (without slack), can you point out how to do that?

**Comment by 3-w-c** [comment]
@CaledoniaProject it might work to insert a new user into the database (`INSERT INTO users...`), or you could try making a copy of `seed.ts` without the [checking-for-and-creating a team part](https://github.com/outline/outline/blob/main/server/scripts/seed.ts#L10-L19).
