### ISSUE TITLE
Line numbers display horizontally when code block is under bullet point

### ISSUE THREAD

**Issue by binaryfire** [outline/outline#5202]
When I add a code block directly under a bullet point (i.e. indented) the line numbers are shown horizontally:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/5361908/232010242-0a7cebff-0639-43c1-a141-c604b6162fe3.png">

- Outline version: 0.68.1
- Browsers: Chrome (latest) and FF Developer Ed (latest)
- OS: Windows 11

**Comment by tommoor** [comment]
This has been addressed on `main` and will be fixed in the next release
