### ISSUE TITLE
No way to indent on mobile

### ISSUE THREAD

**Issue by andersmmg** [outline/outline#5204]
On the mobile website, there seems to be no way to indent bullets or lists.

**To Reproduce**
1. Open Outline on a mobile browser
2. Create a bulleted list
3. No way to indent

**Expected behavior**
A command or shortcut to indent should be available. I've seen some apps do it when 4 or 2 spaces are at the start, or maybe a button or drag action to pull it to indent

**Outline**
- Install: self hosted
- Version: v0.68.1

**Mobile**
 - Device: OnePlus 6T
 - OS: Android 13
 - Browser Chrome

**Comment by tommoor** [comment]
As a funny workaround you can use dictation to say “Tab key” to indent
