### ISSUE TITLE
Multiline code block inside list item is showing lines incorrectly

### ISSUE THREAD

**Issue by pauloelr** [outline/outline#5217]
When you edit or create a page and include a multiline code block inside list item it should display the line number before each new line of the code block, but instead it is showing multiple line number all in the first line of code

**To Reproduce**

1. Create a list item with any text
2. Break the line without creating a new list item (ctrl + enter or cmd + return)
3. Create a multiline code block
4. Insert any code with more than one line

**Expected behavior**
Line numbers in the beggining of each line

**Screenshots**
<img width="771" alt="image" src="https://user-images.githubusercontent.com/1790910/232783232-c2438f5a-2b7d-4c4a-abd6-a74a4bf43e78.png">

**Outline (please complete the following information):**
- Install: sel-hosted
- Version: Don't know, I am just the client, not from SRE Team

**Desktop (please complete the following information):**
 - OS: MacOS 12.4
 - Browser Chrome or Firefox (tested on both)
 - Version Last version

**Comment by tommoor** [comment]
This has already been addressed on main and will be fixed in the next release

**Comment by wohenbushuang** [comment]
@tommoor  After upgraded to v0.69.0, this problem still exist for multiple digit line number:

![image](https://user-images.githubusercontent.com/15613184/233908977-d79f6d83-2bf0-4a00-83cc-9951ccb92c84.png)

**Comment by tommoor** [comment]
Which browser, which operating system?

**Comment by wohenbushuang** [comment]
Chrome v112 & Windows 10

**Comment by WarlockFish** [comment]
![图片](https://user-images.githubusercontent.com/30708115/235042689-78ed74e9-d810-4cfd-919a-b0416fc6538b.png)

the  Indenting still has this issue 。you can see https://outline.warlockfish.xyz/s/mouse-kdb

**Comment by tommoor** [comment]
I guess it's related to being in the nested list in this case, tricky to get this right 😞
