### ISSUE TITLE
Access can be changed by anyone

### ISSUE THREAD

**Issue by TaoChan1005** [outline/outline#5226]
I need some help with submitting a bug report. I recently encountered an issue where a user (A) creates a collection with open access (both edit and view), but another user (B) can change it to be private, resulting in A losing access to their own collection. I'm not sure if this is a known issue or if there is a workaround for it.

Could you please provide some guidance on how to submit a bug report for this issue? Specifically, what information should I include, and how can I provide steps to reproduce the issue? Additionally, it would be helpful to know if there are any known workarounds or solutions to this issue.

Thank you for your help!

**Comment by tommoor** [comment]
This is by design, in the future we may have the concept of collection admins/maintainers but today team members are equally powerful.
