### ISSUE TITLE
Heading link inconsistency

### ISSUE THREAD

**Issue by thumDer** [outline/outline#5230]
Opening a page via a heading link sometimes shows the heading at the top of the page, sometimes in the middle, sometimes it is completely offscreen. Haven't been able to find a pattern in the behaviour, but usually the first few operations will show the heading at the top, and after a few repeats is tarts to put it in the middle.

In the attached video only the 2. and 3. option is happening.

https://user-images.githubusercontent.com/54556708/233321612-ff6faf40-16cb-4a85-8402-99d393d2c124.mp4

We are using getoutline.com in Firefox 111.0.1

**Comment by tommoor** [comment]
I suspect this is due to the loading of images changing the height of the page after the scroll location has been determined. I'm going to merge this into https://github.com/outline/outline/issues/5114
