### ISSUE TITLE
(Some) Shortcuts not working for Windows

### ISSUE THREAD

**Issue by ankushjindal** [outline/outline#525]
The shortcuts that use the command (Mac) key does not seem to have an alternate in Windows. I tried using Ctrl, Win, Alt and Shift key as a replacement for ⌘, but didn't work. Eg: ⌘+b for bold, ⌘+/ for shortcuts guide.
As an alternative, I suggest the use of the Ctrl key for Windows. Ctrl is used for all formatting shortcuts in Windows.

My setup: Windows 10 (64 bit), Chrome v63.

**Comment by jorilallo** [comment]
Looks like we rely on `metaKey` and on Windows it's mapped to Windows key. Thanks for the report @ankushjindal
