### ISSUE TITLE
Upload files: 400 Missing required header for this request: Content-MD5 on Oracle S3 compatibility API

### ISSUE THREAD

**Issue by ikaruswill** [outline/outline#5255]
Unable to upload files when using Oracle Object Storage S3 Compatibility API due to missing `Content-MD5` header.

Based on my understanding of the code and observations in devtools:
- It appears that the request is first constructed in the backend via a call to `/attachments.create`
  - a presigned POST request is created here as well
- The pre-constructed request passed to the frontend via the response under the `data.attachment` and `data.form` fields
- The frontend makes the actual POST to the S3 endpoint

The logic is sound, but for some reason, Oracle Object Storage requires `Content-MD5` header to be set.

I understand this is more of a feature request, but I believe there are benefits in including logic for `Content-MD5` header inclusion, the biggest being data integrity.

Quoting the docs:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property
>To ensure that data is not corrupted traversing the network, use the Content-MD5 header. When you use this header, Amazon S3 checks the object against the provided MD5 value and, if they do not match, returns an error. Additionally, you can calculate the MD5 while putting an object to Amazon S3 and compare the returned ETag to the calculated MD5 value.

Can we add a `Content-MD5` header for the S3 requests?
- For the purpose of ensuring data integrity
- For Oracle Object Storage support (despite their strangeness)

Adding this header should not impact existing functionality. I have tested locally that `aws-sdk` calls does include the `Content-MD5` header implicitly. 

Headers pulled from `AWS.HttpRequest` when using `AWS.S3.putObject()`
```
 _header: 'PUT /outline/upload.txt HTTP/1.1\r\n' +
      'User-Agent: aws-sdk-nodejs/2.1290.0 linux/v20.0.0 callback\r\n' +
      'x-amz-acl: private\r\n' +
      'Content-Disposition: attachment\r\n' +
      'Content-Length: 19\r\n' +
      'Content-Type: text/plain\r\n' +
      'Content-MD5: r80vSQNSHOwuJodDrOLeBQ==\r\n' +
      'Host: asdasdaasdasd.compat.objectstorage.ap-singapore-1.oraclecloud.com\r\n' +
      'X-Amz-Content-Sha256: UNSIGNED-PAYLOAD\r\n' +
      'X-Amz-Date: 20230425T160011Z\r\n' +
      'Authorization: AWS4-HMAC-SHA256 Credential=asdfasdasdasdsdasda/20230425/ap-singapore-1/s3/aws4_request, SignedHeaders=content-disposition;content-md5;host;x-amz-acl;x-amz-content-sha256;x-amz-date, Signature=asdasdasdasdasdasdas\r\n' +
      'Connection: keep-alive\r\n' +
      '\r\n',
```

**To Reproduce**
1. Configure `AWS` environment variables according to [guide](https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm)
2. Create a note
3. Open dev tools
4. Upload a file
5. See error in network request
6. No files are present in Oracle Object Storage bucket

**Expected behavior**
File uploads successfully with 200 status code, and file present in bucket

**Outline (please complete the following information):**
- Install: self hosted
- Version: d4da028527f056e196d172c6ff6f023c747b592d

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 112.0.5615.137

**Comment by mohamedkassem23** [comment]
Hi

did you find any workaround to fix this issue?

**Comment by ikaruswill** [comment]
I'm afraid not. I've gone without object storage for the meantime as I do not want to host minio (a can of worms in its own right) and I don't have an S3 bucket.

**Comment by hibare** [comment]
Similar issue with Storj, receiving 400 error.

**Comment by DheerajParmar22** [comment]
Is the issue still open?

**Comment by lng2020** [comment]
I think an env called `OBJECT_LOCK` can be introduced for those who want to use the `content-md5` field. I will do more investigation later and probably raise a PR.

**Comment by mohamedkassem23** [comment]
@lng2020 did you find the env `OBJECT_LOCK`
