### ISSUE TITLE
When editing a page cursor navigation with arrow keys is inconsistent with respect to inline code

### ISSUE THREAD

**Issue by jannschu** [outline/outline#5267]
Usually the arrow keys move the cursor one character, but for inline code the behavior is inconsistent.

**To Reproduce**
I made a small screenshot that contains written instructions on what is happening.

https://user-images.githubusercontent.com/17914/234877668-4d0556e1-de43-4b9a-a612-3685365740ec.mov

Similar issues show up when the cursor is at the beginning of inline code.

**Expected behavior**
Since moving around elsewhere is also possible with a single arrow key stroke, the expectation is that leaving inline code also takes only one keystroke. Or at least consistent behavior, or visual indication.

**Outline (please complete the following information):**
- Install: self hosted
- Version: 4f019b7

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 112.0.1

**Comment by jannschu** [comment]
Quick addition, character after code block is also skipped. Screencapture:

https://user-images.githubusercontent.com/17914/234885409-9dbaf219-7c16-4a20-bf57-27b27ea8b939.mov

**Comment by jannschu** [comment]
Tried to find workaround and found another weird behavior. Dropping this screencapture here because I am not sure if it is the same issue. Sorry for being a little spammy :-(

https://user-images.githubusercontent.com/17914/234888364-f8540e5f-60fd-4f05-a338-b8a5bae9dc39.mov

**Comment by fuzyll** [comment]
This is maybe related, maybe not, can make a different ticket for it if necessary.

If:

* Two users are editing a file
* You start typing in a code block
* You end that code block by typing the final backtick
* The other user types something that causes the document to change
* You start typing again

...the thing you type in the final bulletpoint will actually be formatted as code, as if you had never closed the code block. You can't use any of the little tricks (like using the right-arrow to skip "outside" the code block) mentioned/alluded to above to get out of the situation, either.
