### ISSUE TITLE
curl missing in final container image

### ISSUE THREAD

**Issue by matt-laird** [outline/outline#5277]
In release 0.69.0 `curl` was added to the base container image, however `curl` doesn't seem to be in the final production image.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter Outline Server container with shell.
2. Type `curl`.
3. Observe error `sh: curl: not found`.

**Expected behaviour**
`curl` to be present in final image.

**Screenshots**
n/a

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 4b810bcdb71b660fc7b7b0cd95bb59a4fa78c814 - v0.69.1

**Comment by tommoor** [comment]
Seems right, I'm not sure I understand why though
