### ISSUE TITLE
subdomain: Expected string, received null

### ISSUE THREAD

**Issue by muuvmuuv** [outline/outline#5287]
**To Reproduce**

1. self-host via docker
2. go to settings and change theme color
3. press save

**Expected behavior**

Subdomain is only on cloud hosted so it should be ignored on self-hosted.

**Screenshots**

```json
{
    "name": "entergon",
    "subdomain": null,
    "defaultCollectionId": null,
    "preferences": {
        "publicBranding": true,
        "customTheme": {}
    }
}
```
```json
{
    "ok": false,
    "error": "validation_error",
    "status": 400,
    "message": "subdomain: Expected string, received null"
}
```

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.69.1

**Desktop (please complete the following information):**

**Mobile (please complete the following information):**

**Comment by muuvmuuv** [comment]
Yes, it blocks saving it completely. Guess not all are updating Outline that frequently as we do nor update their team settings. :D

**Comment by almereyda** [comment]
This was a nice catch.

To note: For securing the cookie context, it is recommended practice to host web applications under a sub-domain, in so a cookie mapped onto the context of an SLD could not be forged by new, possibly unknown subdomains of it.
