### ISSUE TITLE
Outline doesn't open pages in Google Chrome (72.0.3626.121)

### ISSUE THREAD

**Issue by emichrist** [outline/outline#5290]
Hi! We are using self hosted version of outline and it is perfect but after one of the upgrades (i can't say which one) outline stopped work in Google Chrome. When users are try to open any pages they got message: "Something unexpected happened " and in detailed view: "TypeError: object.fromentries is not a function". In other  browsers (such as Microsoft Edge (version 112.0.1722.58) or Firefox (version 112.0.2)) everything is work fine. 

We are using: outline 0.69.1, Google Chome: 72.0.3626.121 64bit, and most of PCs are running on Windows 10  Corporate  Version 1809 (Build 17763.4252). Is it problem with old Chrome version?

**Comment by routerino** [comment]
Chrome 72 came out in january 2019. is it reasonable to expect outline to support a 4.5 year old version of a browser? That's a millenia in browser history, I can't imagine the amount of unresolved vulnerabilities you are opening yourself too. Go to one wrong site, and boom.

**Comment by tommoor** [comment]
Hi, the officially supported browsers are here:

https://github.com/outline/outline/blob/main/package.json#L46

Basically, a browser must have larger than 0.25% market share. The main reasoning behind this is it allows us to ship modern code without bloating the application size to support very outdated browsers. As the previous poster mentioned, it is advisable to update in this case.
