### ISSUE TITLE
Using code blocks in a list results in bad rendering of line numbers

### ISSUE THREAD

**Issue by NikosTsiligaridis** [outline/outline#5291]
What the title says :)

**To Reproduce**
1. Type - <space> to start a list, type anything, <enter>
2. <backspace> to delete bullet, ``` to start code block
3. Type more than 1 lines of text, lines are rendered on top of element

**Expected behavior**
Lines appearing in the gutter

**Screenshots**
![image](https://user-images.githubusercontent.com/34250462/235718765-173dd691-ab5b-47bc-b78c-4cdf24e117d6.png)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.68.1

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Browser Chrome, Vivaldi
 - Version Latest

**Comment by tommoor** [comment]
Fixed in df1c360b2a7664c22bdf5cdf466f4055dd99081d
