### ISSUE TITLE
images broken in markdown export

### ISSUE THREAD

**Issue by psifertex** [outline/outline#5293]
Exporting a page with images to markdown results in code like:

```
 ![](/api/attachments.redirect?id=$GUID)
```

Obviously that won't work basically anywhere else.

**To Reproduce**
1. Make a page
2. Drag an image into the page
3. Use the three dot menu to export to markdown
4. Open file, no image

**Expected behavior**
Either the URL should be converted to a full URL that points to the outline server itself so the image will still render, or the image itself should be included in the export and linked locally (preferred since this makes it more portable!)

HTML export currently does the former, though I suppose a second request would be the later behavior -- I'll start a discussion though about that as a new feature

**Outline (please complete the following information):**
- Install: self hosted
- Version: Image ID: 8f65321c7079 (from docker hub -- incidentally, is there an easier way to find out the commit hash from within the UI itself)

Don't think client info here is relevant since this is purely server behavior.

**Comment by tommoor** [comment]
Definitely not great that they are broken in this circumstance, but it's somewhat a limitation of the Markdown format – there is no way to embed the images, and if we put a fully qualified url there it still wouldn't work because of authentication.

The best thing to do is download the collection, which will create a zip file which includes all of the attachments.

**Comment by routerino** [comment]
easiest option I could see is a download compiles a zip of the markdown and resolves any images in the same page. Which is essentially want the collection does, just at a page level.

**Comment by psifertex** [comment]
Yup! This would be fantastic. For what it's worth, my use-case is to use outline as an internal draft for collaborative editing of markdown based blog posts. Being able to easily export the images already linked in the appropriate relative path way (like the collection export) without having to restructure my entire setup so the blog post is in a more minimal collection would be great.
