### ISSUE TITLE
Add support for embedding Microsoft Suite

### ISSUE THREAD

**Issue by tommoor** [outline/outline#5299]
We support most of the Google Suite, I'd like to add the equivalents for Microsoft if they allow public embedding

**Comment by vasyciuban** [comment]
Hi
Any news about embedding Microsoft?
It would be great to have at least Sharepoint to Microsoft Power BI

**Comment by josselingranger** [comment]
It would be a great addition to the app !
I believe the viewing rights will depend on your tenant preferences.
But when you access a Stream video, you do have an "integration code" in the sharing options, generating an iframe.
