### ISSUE TITLE
Markdown export keeps smart quotes instead of replacing them

### ISSUE THREAD

**Issue by fuzyll** [outline/outline#5303]
Markdown export gives you a document that still has smart quotes in it. This actually breaks some workflows, because not all markdown parsers can handle this correctly and will break. It's also not expected, because raw markdown isn't a situation where smart quotes make sense from a typographic perspective.

**To Reproduce**
1. Write a new document that has quotes in it
2. Click on '...' in the top right
3. Click Download -> Markdown
4. Observe that the fancy smart quotes (which look great in the wiki) are still in the markdown output
5. (Optional) Use the Markdown output in something like Jekyll, which can break in some cases because of the smart quotes

**Expected behavior**
I expected the things I typed in (e.g. actual quotes) to be what I got back out when I exported a raw, textual representation of the page. I completely understand why Outline uses smart quotes, and prefer them from a typographic perspective. I just expected this to be part of a presentation layer transformation, rather than a data entry transformation.

From a technical perspective, I understand that storing the original data and needing to transform it every time you show a page is slower. It makes sense to optimize for the thing people are doing most of the time (viewing pages) instead of the thing people rarely do (export as markdown). But, I think having smart quotes in a text format that might be used in a variety of ways is strange since there's no typographic benefit to having them in that context.

**Outline (please complete the following information):**
- Install: Self-Hosted
- Version: v0.68.1

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 13.3.1

**Comment by tommoor** [comment]
> But, I think having smart quotes in a text format that might be used in a variety of ways is strange since there's no typographic benefit to having them in that context.

I'm not sure what you mean by no typographic benefit – isn't the benefit the same?

**Comment by fuzyll** [comment]
My perspective is that markdown deserves the correct characters _in the appropriate context_.

If the document is meant for human consumption as a formatted document (e.g. in Outline, or some other application), I _much_ prefer Outline's current behavior. The smart/curly quotes are an improvement over straight quotes for readability. They're also the actually correct thing to do from a typesetting perspective.

If, however, the document is meant for computer consumption (or human consumption in a code editor), I do not want smart quotes. This [has been a problem for years](https://devblogs.microsoft.com/oldnewthing/20090225-00/?p=19033) in far more applications than just Outline. A large number of programs do not expect them as input, and the behavior ranges from "it just looks funny" to actually crashing. The smart quotes also don't look good or function as well, from a typographic perspective, in monospaced font in an editor.

I'm asking for raw export of the document to cater to the lowest common denominator because I believe the average use-case will be to feed the output to some non-human process. And, if I'm wrong, I would expect those other applications to convert back to smart quotes if they support them (e.g. how Outline behaves). Half the point of markdown is that I can chuck a whole bunch of ASCII characters into a document and a renderer can make it look like an appropriately formatted document. (The other half, of course, is that it's far easier to do than the alternatives.)

If you don't agree, feel free to close the issue as `wontfix`. This isn't some hill I want to die on, and I'm sure there are other issues more worthy of your time. But, it's really annoying to need to post-process everything we're exporting from Outline (which is fantastic as a collaborative editor on markdown - better for us than Google Docs), and I thought it was a reasonable request to make with pretty straightforward rationale.

**Comment by fuzyll** [comment]
I took a stab at trying to implement this myself, just want to make sure I'm on the right track (and if you won't merge a PR because you don't want the change, let me know so I can stop looking at this).

I haven't worked in JavaScript in quite some time (and I have never used React or TypeScript), but as I understand it, the menu action is [here](https://github.com/outline/outline/blob/main/app/actions/definitions/documents.tsx#L324), which calls `download` from [here](https://github.com/outline/outline/blob/main/app/models/Document.ts#L388), which makes a POST request. It _looks_ like I could change `download` to `false` and get back a JSON blob from [here](https://github.com/outline/outline/blob/main/app/utils/ApiClient.ts#LL145C30-L145C30).

The plan would then be to do something like:

```typescript
const content = blob.replace(/[\u2018\u2019]/g, "'").replace(/[\u201C\u201D]/g, '"');  // normalize smart quotes
const filename = // process JSON to find content-disposition header and get "filename=" value here
download(content, filename);  // use function from utils/download.ts
```

What's not clear to me at the moment is how to actually _get_ the `blob` since, if we don't take the `options.download && success` path in `ApiClient.ts`, we don't do `await response.blob()`. And, since I no longer have a `response` object (I have JSON), it's not clear to me if the data is actually present or not.

If someone could give me a gentle nudge in the right direction, or let me know if this is a fool's errand because Outline would prefer the current behavior, that'd be appreciated either way.

Thanks!

**Comment by tommoor** [comment]
You'd want to make the change in `toMarkdown` on the API (https://github.com/outline/outline/blob/d096ba486f4c616a139ccf8ee355463c9fa3ba04/server/models/helpers/DocumentHelper.tsx#L85), not the client.

The problem is this method is used for export <-> import between instances when you do a bulk export as markodnw, so it would mean losing those characters in that scenario too. You could pass an option and only do the normalization when downloading an individual document, but it starts to feel a bit weird to me.

**Comment by tommoor** [comment]
Yes, would accept a PR – 6 months ago this wouldn't be possible as the primary way to migrate data between instances was Markdown but we now have HTML and JSON options for lossless transfer.

**Comment by fuzyll** [comment]
I lost track of this at some point after we needed it last, but it just came up again last week (and then the bot posted its reminder). I'll see where I was at tomorrow when I get back from travel and see if I can give an update and/or ask questions.
