### ISSUE TITLE
Drafts can be confusing, add ability to disable or rethink

### ISSUE THREAD

**Issue by tommoor** [outline/outline#5310]
Is there any way to automatically publish new documents? 

I am migrating a team from Notion to Outline and generally it's going smoothly. This is great software. 

Weirdly though, the biggest blocker for users is getting used to the fact that new documents are not automatically published. 

I would like to disable the draft feature and have new documents show up immediately for all users no matter who creates them. Besides causing confusion it's just not something we need.

_Originally posted by @looeee in https://github.com/outline/outline/discussions/3824_

**Comment by anthony-crystalpeak** [comment]
Seems like setting the publishedAt field may trigger the existing publish flow to work with minimal change? https://github.com/outline/outline/blob/33e67a11ed3810092547edb0973b5f9d0030145a/server/routes/api/documents/documents.ts#L356

**Comment by DaniFoldi** [comment]
I generally disagree with "stale" bots that auto-close issues. I didn't open an issue for this, since there was one already open. Had it been closed, the general expectation would be for me to open another one - even if this doesn't get implemented soon, it's something that I'm sure some people would be interested in.

**Comment by almereyda** [comment]
This may also touch the overall workflow around collaborative versioning then including a review stage, as proposed in

- #1084

and also prior discussions around

* #835

which might help distinguishing which user role is allowed to put a document in which kind of state (draft, published, suggested edit, public, archived, deleted, …)

**Comment by almereyda** [comment]
It's implementation also has unknown side-effects in very few circumstances.

- https://github.com/outline/outline/issues/5948

**Comment by EduNetEurope** [comment]
Not being able to see drafts in their proper place within a collection can be extremely confusing. We would prefer to have the option to decide for each document within a collection whether it should be shared or not. The approach used by Archbee in handling this matter is considered perfect by us.

**Comment by ChuckJonas** [comment]
The behavior where new document in draft status disappear from the collection is so confusing and painful.  Please keep the drafts in the navigator, but maybe just show an icon to indicate it's a draft

**Comment by aeris-alex** [comment]
New user here and just spent hours looking at this thinking there was a problem with my configuration. Not for a second did I think this was by design. 

A quick fix like adding a toast with a "moved to drafts" message  would be better than nothing but I'm not sure why the drafts don't simply display inline with the other documents with a "draft" tag next to the name of the document in the sidebar? 

Would a PR be considered for either of these?

**Comment by EduNetEurope** [comment]
There are at least two related discussions:

- https://github.com/outline/outline/discussions/3824
- https://github.com/outline/outline/discussions/6728

**Comment by tommoor** [comment]
> I'm not sure why the drafts don't simply display inline with the other documents

To defend the decision somewhat, the point of a draft is to have somewhere to write before other users see it – everything in the sidebar structure is visible to other team members.

If you're working on a team (the usecase Outline is designed for) I'd be most interested in hearing feedback on how acceptable this feels. I suspect most confused folks are those that are just using Outline on their own – while that's fine it's not what we're designing for.

**Comment by EduNetEurope** [comment]
Since all other wikis seem to show drafts in the sidebar structure (just marked as drafts), it seems to be acceptable to most teams?
We would not mind. Isn't the original idea behind wikis that they are co-creative?

**Comment by tommoor** [comment]
This behavior was changed in [v0.78.0 (release)](https://github.com/outline/outline/releases/tag/v0.78.0) – documents created in a collection will be automatically published. You can still create drafts from the command menu or drafts tab.
