### ISSUE TITLE
AI powered Search

### ISSUE THREAD

**Issue by roovyshapiro** [outline/outline#5337]
I'm updating this issue to request an AI powered search instead of a generative AI integration. An AI powered search like Slite's ASK would be an incredibly helpful feature. It would allow users to ask questions in their outline search bar using comfortable language and getting tailored answers trained on their data.

https://slite.com/ask
_How is Ask different from NotionAI?
Ask is about making use of knowledge you already have. It makes it easier to find clear answers and unlock insights from in your team's existing docs.
NotionAI, on the other hand, is focused on the content creation side. It can be called on to help draft content, get ideas, or generate content._

Here's the original issue request:

_Notion recently released "Notion AI" https://www.notion.so/product/ai which seems to be a direct integration with GPT or some other kind of Large Language Model.
It allows for generating text like brainstorming ideas, editing existing text, explain content better, reframe existing content with a different context or voice, reduce the complexity of the vocabulary etc.
I'm not sure if Notion built their own AI model for this, but it would be neat for Outline to integrate with some existing models out there.
This could even be a paid service that Outline provides.
Alternatively, the feature set could be integrated while the user has to purchase API credit from OpenAI and just import their API key into outline: https://platform.openai.com/account/api-keys_

**Comment by problem** [comment]
Cohere is also another great alternative to OpenAI -- still a solid LLM

**Comment by m-akrami** [comment]
I'd prefer it if the administrator of the service could import OpenAI's API key and select what users are allowed to access it, or this to be a selectable option - this gives us greater flexibility as the organisation can pay if the key is provided or the user can

**Comment by m-akrami** [comment]
> Cohere is also another great alternative to OpenAI -- still a solid LLM

And many local LLMs can still emulate OpenAI's API functionality so this still allows us to tie in our own backend AI system

**Comment by ivorsmorenburg** [comment]
https://github.com/imartinez/privateGPTAn interesting integration i think

**Comment by roovyshapiro** [comment]
After some review, I much prefer Slite's ASK over Notion's AI. It is basically an ai-assisted search feature so it lets you ask questions to your knowledge base. https://slite.com/ask
This is much better

How is Ask different from NotionAI?
Ask is about making use of knowledge you already have. It makes it easier to find clear answers and unlock insights from in your team's existing docs.

NotionAI, on the other hand, is focused on the content creation side. It can be called on to help draft content, get ideas, or generate content.

**Comment by m-akrami** [comment]
> After some review, I much prefer Slite's ASK over Notion's AI. It is basically an ai-assisted search feature so it lets you ask questions to your knowledge base. https://slite.com/ask
> 
> This is much better
> 
> 
> 
> How is Ask different from NotionAI?
> 
> Ask is about making use of knowledge you already have. It makes it easier to find clear answers and unlock insights from in your team's existing docs.
> 
> 
> 
> NotionAI, on the other hand, is focused on the content creation side. It can be called on to help draft content, get ideas, or generate content.

I second this, but having a generative style AI within the app would also be nice, as there’s nothing stopping both features coexisting.

If I had to pick one over the other, it would be the search option. I think there’s a project that does exactly this based off ingested documents, if I find it I’ll update this comment with a link.

**Comment by therajumandapati** [comment]
Love this suggestion. There's also a place for generative AI integration to help remove writers block in drafting documentation for existing documentation (for ex: There could be a doc in Outline with title: How does our team create wireframes?, and the appropriate team can use generative AI to get a first draft and modify to make it fit).

**Comment by tommoor** [comment]
This feature is in beta for cloud-hosted customers, if you're interested in testing please email support.

**Comment by tommoor** [comment]
This feature is now available for all cloud-hosted customers, and can be enabled in **Settings -> Features**.

I'll leave this issue open until there are formal plans for how to bring this to on-premise.

**Comment by matbgn** [comment]
Many thanks to keep it open. In facts it's quiet annoying that a simple search containing words with diacritics could not be addressed on-premise.

**Comment by rubentrf** [comment]
Comment also for the cloud-hosted: it would be really nice that Azure OpenAI would be supported. Normally in Outline we document quite sensitive information that not all companies are willing to share with the public OpenAI API (I know their privacy policy, but in some parts is quite vague and I'd rather connect to my Azure OpenAI models).

Do you know if that's in the roadmap / has been requested previously?

**Comment by tommoor** [comment]
Hi @rubentrf – it's unlikely we'll provide alternative models in cloud-hosted. The licensed self-hosted edition will have the ability to specify a url for the model, so could be used with Azure OpenAI in this way

**Comment by almereyda** [comment]
This sentence

> In facts it's quiet annoying that a simple search containing words with diacritics could not be addressed on-premise.

by @matbgn reminded me of

- #3207

which holds an epic discussion of ways to implement supporting other languages.

In the field of internationalisation we witness very clearly how the dominant hegemony of the English language imposes its cultural narrative onto the world and is less likely to assimilate other cultural practices, because of said hegemony. If you never encounter yourself living in a multi-lingual world, you have maybe fewer understanding of and empathy towards the needs other language cultures.

Having said this, searching the issues for diacritics now only shows that and this issue.

Should we maybe file a separate discussion about a lower-hanging fruit than CJK languages, that are languages using latin script with diacritics? UTF-8 and Unicode have been quite powerful in moving the internationalisation train forward and, admittedly, we'd do good in nodding our heads towards this direction, before onboarding more robots to the platform.

Now it is on us, the users, to demand its application for equal representation of the needs of international user bases in an application that is marketed globally at getoutline.com.

**Comment by matbgn** [comment]
Even if I agree with the principle of UTF-8, this project is open-source and I'd rather propose a Pull Request that solves the problem than sign a petition, even if both aspects are perhaps necessary...

However, I have more of a problem with @tommoor's sentence "The *licensed* self-hosted edition will have the ability to specify a url (...)" licensed? What does this mean in concrete terms? Before continuing to plan a possible future PR it would be good to know the legal/licensing future of this project.

Translated with DeepL.com (free version)

**Comment by almereyda** [comment]
The licensed self-hosted edition is also known as on-premise enterprise version.

For us the BSL is no hindrance to cooperation, since we are working strictly not-for-profit (and there's no CLA).

And commercial ventures should be able to afford commercial enterprise licenses.

**Comment by hosimaz** [comment]
Is there any plan to release AI Search/Ask for the community edition?

**Comment by tommoor** [comment]
To clarify where this ended up – this feature is available in Cloud Hosted and in the latest Business and Enterprise editions for on-premise, though it requires both an OpenAI api-key and a pgvector compatible installation of postgres to function in on-premise environment ([docs](https://docs.getoutline.com/s/hosting/doc/openai-iiTYCN9Nct)).

There is no plan to release this in the community edition.

**Comment by dvkolesnikov** [comment]
@tommoor is the situation still the same? No plans to make this functionality available in the community edition?

**Comment by akib1689** [comment]
Is there any plan to release this integration in community edition?
