### ISSUE TITLE
TypeError "cannot read property push of undefined"

### ISSUE THREAD

**Issue by tommoor** [outline/outline#537]
## Error in Outline

**TypeError** in **/collections/ffeaa0ce-fb0d-4d12-9140-3589ad961d73**
Uncaught TypeError: Cannot read property 'push' of undefined

[View on Bugsnag](https://app.bugsnag.com/atlas-1/outline/errors/5a6cf784a7e8c60018dfc1c8?event_id=5a6f207568b330001c92764f&i=gh&m=ci)

## Stacktrace

    webpack:///app/menus/CollectionMenu.js:26 - r.onNewDocument

[View full stacktrace](https://app.bugsnag.com/atlas-1/outline/errors/5a6cf784a7e8c60018dfc1c8?event_id=5a6f207568b330001c92764f&i=gh&m=ci)

*Created by Tom Moor via Bugsnag*

**Comment by tommoor** [comment]
I found the cause of this, taking care of it. PR later on this evening.

**Comment by jorilallo** [comment]
__drumroll__
