### ISSUE TITLE
Notion > outline migration - Corrupted zip error

### ISSUE THREAD

**Issue by eugen-korentsov** [outline/outline#5383]
**To Reproduce**
1. Go to 'notion > settings > workspace > export all workspace content as html'
2. Import zip file exported from Notion to Otline, go to  > Import > Notion

**Expected behavior**
Successfully imported documents

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.69.2

During import I get error:
Failed • End of data reached (data length = 2795021195, asked index = -1499946223). Corrupted zip ? • You requested  2 hours ago • 2.79 GB

In outline logs:

ror":"End of data reached (data length = 2795021195, asked index = -1499946223). Corrupted zip ?","level":"error","message":"Error processing task in ImportNotionTask","stack":"Error: End of data reached (data length = 2795021195, asked index = -1499946223). Corrupted zip ?\n    at NodeBufferReader.checkIndex (/opt/outline/node_modules/jszip/lib/reader/DataReader.js:26:19)\n    at NodeBufferReader.setIndex (/opt/outline/node_modules/jszip/lib/reader/DataReader.js:35:14)\n    at ZipEntries.readCentralDir (/opt/outline/node_modules/jszip/lib/zipEntries.js:132:21)\n    at ZipEntries.load (/opt/outline/node_modules/jszip/lib/zipEntries.js:256:14)\n    at /opt/outline/node_modules/jszip/lib/load.js:48:24\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ImportNotionTask.parseData (/opt/outline/build/server/queues/tasks/ImportNotionTask.js:39:17)\n    at async ImportNotionTask.perform (/opt/outline/build/server/queues/tasks/ImportTask.js:44:22)\n    at async Queue.<anonymous> (/opt/outline/build/server/services/worker.js:109:7)"}

I tried export in both ways with enabled "Create folders for subpages" and disabled, error is the same.

**Comment by eugen-korentsov** [comment]
Which limit exactly do you mean? What is the max size of zip file I can use ?

**Comment by tommoor** [comment]
Literally the limits of the programming language. I suggest keeping your imports under 1Gb in size for safety and memory usage.

**Comment by eugen-korentsov** [comment]
Okay, I tried to repack and import by parts, 2 archives were imported successfully, but 1 failed:

1.zip
Completed • You requested  1 hour ago • 268.47 MB

2.zip
Failed • Sorry, an internal error occurred during import • You requested  11 hours ago • 291.89 MB

3.zip
Completed • You requested  12 hours ago • 363.69 MB

Found this error, what is mean here by description ? And can I increase this limit ? 

{"error":"Validation error: description must be 1000 characters or less","level":"error","message":"ImportTask failed to persist data for bf9b7b7a-23d6-46f7-b5c7-9971b5701710","stack":"SequelizeValidationError: Validation error: description must be 1000 characters or less\n    at InstanceValidator._validate (/opt/outline/node_modules/sequelize/lib/instance-validator.js:50:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async InstanceValidator._validateAndRunHooks (/opt/outline/node_modules/sequelize/lib/instance-validator.js:60:7)\n    at async InstanceValidator.validate (/opt/outline/node_modules/sequelize/lib/instance-validator.js:54:12)\n    at async Collection.save (/opt/outline/node_modules/sequelize/lib/model.js:2368:7)\n    at async collection.create (/opt/outline/node_modules/sequelize/lib/model.js:1344:12)\n    at async /opt/outline/build/server/queues/tasks/ImportTask.js:222:26\n    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:507:18\n    at async ImportNotionTask.persistData (/opt/outline/build/server/queues/tasks/ImportTask.js:130:14)\n    at async ImportNotionTask.perform (/opt/outline/build/server/queues/tasks/ImportTask.js:54:18)\n    at async Queue.<anonymous> (/opt/outline/build/server/services/worker.js:109:7)"}
--

**Comment by eugen-korentsov** [comment]
And another zip with 433 mb in size, failed with timeout according to the logs:

{"event":{"actorId":"bda70877-9df1-4446-b2ae-db3b1b0198dc","collectionId":"3e41f17f-5c4d-463d-85ab-4c70a9a0ad22","createdAt":"2023-05-25T07:22:54.328Z","data":{"source":"import","title":"Untitled"},"documentId":"7e87be8a-8527-4068-a615-0a265729f938","id":"99fb0645-2aa7-4e97-b7b5-bfb54639541f","ip":"81.193.67.71","modelId":null,"name":"documents.create","teamId":"1872fd76-0283-4a44-b17a-fa206546ba64","userId":null},"label":"worker","level":"info","message":"WebhookProcessor running documents.create"}
ConnectionAcquireTimeoutError [SequelizeConnectionAcquireTimeoutError]: Operation timeout
    at ConnectionManager.getConnection (/opt/outline/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:204:15)
    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:305:26
    at async PostgresQueryInterface.select (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async user.findAll (/opt/outline/node_modules/sequelize/lib/model.js:1134:21)
    at async user.findOne (/opt/outline/node_modules/sequelize/lib/model.js:1228:12)
    at async user.findByPk (/opt/outline/node_modules/sequelize/lib/model.js:1215:12)
    at async getUserForJWT (/opt/outline/build/server/utils/jwt.js:38:16)
    at async authMiddleware (/opt/outline/build/server/middlewares/authentication.js:72:16)
    at async apiWrapperMiddleware (/opt/outline/build/server/routes/api/middlewares/apiWrapper.js:11:5)
    at async userAgent (/opt/outline/node_modules/koa-useragent/dist/index.js:12:5)
    at async /opt/outline/node_modules/koa-mount/index.js:58:5
    at async /opt/outline/node_modules/koa-mount/index.js:52:26 {
  parent: TimeoutError: Operation timeout
      at Timeout.<anonymous> (/opt/outline/node_modules/sequelize-pool/lib/Deferred.js:17:25)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7),
  original: TimeoutError: Operation timeout
      at Timeout.<anonymous> (/opt/outline/node_modules/sequelize-pool/lib/Deferred.js:17:25)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7),
  status: 500
}
{"attempt":0,"event":{"actorId":"bda70877-9df1-4446-b2ae-db3b1b0198dc","collectionId":"3e41f17f-5c4d-463d-85ab-4c70a9a0ad22","createdAt":"2023-05-25T07:22:57.313Z","data":{"source":"import","title":"Untitled"},"documentId":"3c2e93c1-cb8b-4ede-85b2-0d4e81ff9271","id":"1d2e19ab-4b30-43dc-993d-0f30b1faacd6","ip":"81.193.67.71","modelId":null,"name":"documents.create","teamId":"1872fd76-0283-4a44-b17a-fa206546ba64","userId":null},"label":"worker","level":"info","message":"Processing documents.create"}
{"event":{"actorId":"bda70877-9df1-4446-b2ae-db3b1b0198dc","collectionId":"3e41f17f-5c4d-463d-85ab-4c70a9a0ad22","createdAt":"2023-05-25T07:22:54.328Z","data":{"source":"import","title":"Untitled"},"documentId":"7e87be8a-8527-4068-a615-0a265729f938","id":"99fb0645-2aa7-4e97-b7b5-bfb54639541f","ip":"81.193.67.71","modelId":null,"name":"documents.create","teamId":"1872fd76-0283-4a44-b17a-fa206546ba64","userId":null},"label":"worker","level":"info","message":"WebhookProcessor running documents.create"}


Can I adjust timeout value ?
