### ISSUE TITLE
Outline autonomously opens page in new browser tabs, over and over again

### ISSUE THREAD

**Issue by maknotavailable** [outline/outline#5384]
After leaving a page open in the outline application (installed desktop app), it started opening that same page in my default browser over night. This has happened 2-3 times already, over the past couple of weeks. 

**To Reproduce**
Not able to reproduce this. 

**Expected behavior**
Outline should not open pages in new browser tabs, without explicit user input. 

**Screenshots**
Occurrence from the 8th of May
<img width="1109" alt="Screenshot 2023-05-08 at 09 25 48" src="https://github.com/outline/outline/assets/9056896/30de7389-a51b-482e-b0ed-dd56a1d65d81">

Occurrence from the 25th of May
<img width="1511" alt="Screenshot 2023-05-25 at 08 37 39" src="https://github.com/outline/outline/assets/9056896/4c93b444-b76e-4d80-8269-48da2da978c7">

<img width="1510" alt="Screenshot 2023-05-25 at 08 37 25" src="https://github.com/outline/outline/assets/9056896/3cf504d8-793b-4cb5-884d-5ea48133cc94">

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: macOS Venutera 13.3.1 (a) 
 - Browser: Microsoft Edge
 - Version: Version 113.0.1774.50 (Official build) (arm64)

**Comment by tommoor** [comment]
Have you seen this again?

**Comment by routerino** [comment]
> Have you seen this again?

Could be notepad-on-keyboard syndrome.

**Comment by macgate** [comment]
For help, the app has done this to me also twice. During the night, when i com back in the morning in my default navigator, "Firefox" all tabs open. So now i leave the app closed for the night and no problem since. So for me, it happens only in the night, and I'm in France.

**Comment by tommoor** [comment]
Perhaps something to do with the internet disconnecting or wake sleep of the computer, but nothing in the code makes sense for this so far…

**Comment by tommoor** [comment]
Any more reproductions here folks? 🤔

**Comment by macgate** [comment]
I just have now a reproduction. 
I leave open outline since yesterday and noting happen overnight.
Then 2 m ago 10am for me, I was on my browser Firefox reading an article and suddenly a new tab open and load outline from nowhere.
Can't explain why the app did it.

**Comment by macgate** [comment]
Ok I just have 10 new open, will I'm on the mac working, so nothing to do with sleep time of the mac.
The launch time of the app is of 1 day exactly since it's start doing it, the app is open since :
Launch Time:     2023-06-27 10:32:32.811
So for me, it starts doing it again 1 day after the launch.
At first, I think it was each time I had a notification in the notification center. But after even with no notification it continues, so it was maybe just a coincidence.

**Comment by tommoor** [comment]
It must be this code that reloads the app every 24 hours if it's in the background

https://github.com/outline/outline/blob/main/app/hooks/useAutoRefresh.ts#L30

I'm not able to find any way in which `reload()` would create a new tab though, it would have to be a browser extension or bug.

**Comment by tommoor** [comment]
With no possible other suspects I added a guard within the auto-refresh logic and a debugging error to see if it's ever triggered.
