### ISSUE TITLE
UI bug on Spotify embedded link in dark mode 

### ISSUE THREAD

**Issue by tuxiblo** [outline/outline#5390]
**To Reproduce**
1. Add a block with a embedded Spotify link.
2. Select darkmode
3. Corners are still in light mode 

**Expected behavior**
All corners should be dark too

**Screenshots**
In dark mode: 
![dark_mode](https://github.com/outline/outline/assets/68853119/a4a642b1-7528-4f03-a6c5-6362ab21118a)

In light mode:
![light_mode](https://github.com/outline/outline/assets/68853119/51ebbb91-b41b-48c6-b192-865f3e634aa9)

**Outline (please complete the following information):**
- Install: self hosted
- Version: [v0.69.2](https://github.com/outline/outline/releases/tag/v0.69.2)

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1
 - Browser safari Version 16.4 (18615.1.26.110.1)

**Comment by tommoor** [comment]
closed by e9ec31e5b
