### ISSUE TITLE
UX issue: reference to draft disappears from sidebar

### ISSUE THREAD

**Issue by johannesmutter** [outline/outline#5405]
When following the steps to create a new document in any collection, making changes (optional), and navigating to a different page without publishing the document, **the reference to the newly created document disappears** from the collection navigation in the sidebar. 

This behavior is confusing for new users, who may think that their document is lost. Instead, the reference to the document should be persisted in the sidebar, indicating that it is a draft and only visible to the author. To address this issue, the look of the reference link could be changed or an icon could be added to signify its draft status. Resolving this bug is important to prevent new users from being alarmed and ensure they understand that the document is still accessible in the drafts section.

**To Reproduce**
1. Go to any collection
2. Click on create new doc
3. Make some changes (optional)
4. Navigate to a different page (without publishing the doc)

**What happens:**
The reference to the newly created doc disappears from the die sidebar's collection navigation.

**What should happen instead:**
The reference to the doc should be persisted in the sidebar.
Do indicate it's a draft and that it's only visible to the author change the look of the reference link and/or add an icon.

**Why it matters**
It scares the hell out of new users to Outline, as they might think their newly created doc is list.
They don't know that they have to hit publish to persist the reference or that the doc is still accessible in the drafts.

**Screenshots**
![reference to draft disappears](https://github.com/outline/outline/assets/9489658/65966a98-290f-437a-af46-8665d630ac01)

**Comment by johannesmutter** [comment]
An alternative pattern could be an animation that visualizes how the document reference is moved into drafts.

![transition unpublished reference to drafts](https://github.com/outline/outline/assets/9489658/f83235cb-c22f-47fc-9095-387bfca969c4)

**Comment by tommoor** [comment]
This is by design currently, it's not considered a bug. We'll continue evolving how drafts and personal documents are handled that will improve this
