### ISSUE TITLE
when writing a long page title the cursor goes back to the beginning when reaching the end of line

### ISSUE THREAD

**Issue by bmm-alc** [outline/outline#5425]
**To Reproduce**
1. Create a new page
2. On the title part, write a very long title
3. When reaching the end of the line, the cursor is brought back to the beginning of the line.

**Expected behavior**
[Screencast from 2023-06-08 08-10-22.webm](https://github.com/outline/outline/assets/80455946/a51417f7-8752-4cb6-8fde-1672f732d53d)

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 0.69.2

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 113

**Comment by tommoor** [comment]
This does seem to be Firefox specific
