### ISSUE TITLE
Cannot Add Collection - Error : index must 50 characters or less (index)

### ISSUE THREAD

**Issue by robyjuliansyah** [outline/outline#5426]
**To Reproduce**
1. Go to 'New Collection'
2. Input a Collection
3. get error message : index must 50 characters or less (index)

**Expected behavior**
New Collection add to Database

**Screenshots**
<img width="1800" alt="image" src="https://github.com/outline/outline/assets/8702575/db7517c4-290f-4d58-b949-6d1058751516">

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: 0.68.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 113.0.5672.126

**Comment by tommoor** [comment]
Can you post a screenshot of the payload tab? How many collections do you have?

**Comment by robyjuliansyah** [comment]
i think it reach maximum collection items
i was input 350 collection

**Comment by tommoor** [comment]
Mmm yea, you're going to hit all sorts of problems with that many collections – the reasonable maximum is like 50. How can you manage 350 collections? 🤔

**Comment by robyjuliansyah** [comment]
i try to make template for multiorganizational (40++) and 1000++ user =D
