### ISSUE TITLE
Visual bug on home view when there are untitled documents in recent history

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#546]
https://www.dropbox.com/s/054ymx2g8xmc7z1/Screenshot%202018-01-30%2011.17.46.png?dl=0

**Comment by tommoor** [comment]
As mention in person - the weird thing here is that you were able to create a doc without a title 😱

Any chance the title is just a space?

**Comment by lex111** [comment]
> Any chance the title is just a space?

Yes, indeed it's, you can add one space and this title will be saved without errors, so need validation?

**Comment by thenanyu** [comment]
Even weirder, I had typed `# ` (hash and space) which shows up as empty-no-space in the edit mode UI. All it does is put the editor into title mode.
