### ISSUE TITLE
Unpin Docs in Collection - Issues

### ISSUE THREAD

**Issue by edwarddarrah** [outline/outline#5501]
I am unable to unpin Docs in Collections. When clicking on a pinned Doc in a Collection Section, I can't close it (when selecting x). Pinned Docs can not be unpinned from the Doc settings menu. Docs continue to stay pinned even if achieved. 

The issue can be seen in this [screenshot and video](https://dropover.cloud/e41ed7). 

**Desktop**
 - OS: macOS
 - Browser: Chrome

**Comment by tommoor** [comment]
Is this self-hosted or cloud hosted? If self hosted what version? Are there are any errors in the console or server logs?

**Comment by edwarddarrah** [comment]
This is the cloud version. I am using Chrome.

**Comment by tommoor** [comment]
closed by c952dfa0656ae3ad4cde9fe888d42ca4ca91273a
