### ISSUE TITLE
Unable to use of self-hosted grist

### ISSUE THREAD

**Issue by not7cd** [outline/outline#5510]
As it is possible to point to a self hosted embed with #3980 and support of grist via  #3914, it should be possible to embed it via links to self hosted URL.

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.69.2

**Comment by tommoor** [comment]
I'm closing this out because it's not a bug, we don't support self-hosted Grist at this time

**Comment by tommoor** [comment]
Support has since been added, this is already in the latest versions
