### ISSUE TITLE
Applying template should not clear the existing doc without confirmation

### ISSUE THREAD

**Issue by dennisschaaf** [outline/outline#5533]
**To Reproduce**
1. Go to 'an existing page with content'
2. Click on 'template dropdown'
3. Click on 'My Template'

**Expected behavior**
A modal dialog:

    Apply template 'My Template'
    --------------------------------
    Do you want to replace the existing content or
    create a new page

    [Cancel]    [Replace current page]    [Create new page]

**Actual behaviour**

Page content gets overridden and is lost

**Desktop (please complete the following information):**
 - OS: Firefox

**Comment by tommoor** [comment]
Hey @dennisschaaf – right now it takes 2 clicks to apply a template, we'd rather not add a third confirmation. If you replace the page with a template accidentally then it can be easily undone with cmd+z

**Comment by dennisschaaf** [comment]
I agree that it should be easy. But normally you would only apply a template on a new document, right?

So there are two distinct modes and use-cases:

1) You have a new/empty page. 

In this case selecting a template is not destructive and can happen without any confirmation. This is probably the 99% use-case where users select templates.

2) You have an old page with existing content

In this case selecting a template is most likely a destructive action and should have a confirmation. I cannot think of many use-cases where a user would want to override their existing page with a template.
