### ISSUE TITLE
Display issues with Notices during load and in history when used in checklists

### ISSUE THREAD

**Issue by vgwidt** [outline/outline#5536]
Notices do not render correctly when loading a page or when viewing history when used in a checklist.  It also consequently distorts update e-mails where content is changed.

**To Reproduce**
1. Create a numbered list and enter something
2. Hit enter, backspace, then create a check list item with `[ ]` and enter something
3. Hit enter, backspace, and create a notice with `:::` and enter
4. Reload page, or view the current revision and the coverage should be unusual and a code block should appear with `:::` in the notice.

**Screenshots**
View after loading complete:
![image](https://github.com/outline/outline/assets/49006240/263663fe-fdad-40ed-b131-814dd2e8a6cf)

Same page during load:
![image](https://github.com/outline/outline/assets/49006240/ab6a315a-ff30-4a03-ab48-2dcac8e528bd)

Same page in history (current revision): 
![image](https://github.com/outline/outline/assets/49006240/b3dde38a-5d84-460b-abff-155a7d7723cd)

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.70.1

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Edge
 - Version: 114.0.1823.67

**Comment by tommoor** [comment]
Thanks, I'm merging this into #3000 as it's the only possible way it will be fixed
