### ISSUE TITLE
internal error occurred during import.

### ISSUE THREAD

**Issue by DestinyJazz** [outline/outline#5560]
Export from existing collections on Outline in MD format, then import the zip file to Outline, and the error occurs.
Steps:
1. Click Export on the existing collections.
2. Download the zip file.
3. Import the zip file to Outline.
4. Error occurs.

**Expected behavior**
Expect to import successfully and a new collection with all the nested documents ready.

**Screenshots**
![Screenshot_1](https://github.com/outline/outline/assets/97715301/2ccf6f8a-60ae-4237-99fd-c828df63e56b)

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 0.69.2

**Comment by tommoor** [comment]
Please provide server logs at the time of the import, it will contain more information on the error that occurred, without that it won't be possible to debug ruther.
