### ISSUE TITLE
Add "Full Width" as a user configurable option

### ISSUE THREAD

**Issue by ssenior45** [outline/outline#5562]
### Discussed in https://github.com/outline/outline/discussions/5413

<div type='discussions-op-text'>

<sup>Originally posted by **ssenior45** June  5, 2023</sup>
Unless I am mistaken as of now the "Full width" option is on a per-page basis.

Personally, I want every page to be full width by default and have to remember to check this option on each page I create.

It would be nice if this boolean option could be in a user profile and the default value is taken from there. It can still be overriden on a per page basis.</div>

**Comment by tommoor** [comment]
I don't think we'll add a user preference for this, but we'll have it remember the setting from "last time" – the first change for this just landed, when creating a child document it will now use the setting from the parent.
