### ISSUE TITLE
Outline fails to refresh token for OIDC

### ISSUE THREAD

**Issue by routerino** [outline/outline#5564]
Opening from #5532 as the issue looks very similar to that issue, but affecting the generic OIDC provider as opposed to the microsoft SSO provider.

Generic OIDC (set up as [per this guide](https://blog.gurucomputing.com.au/Knowledgebases%20with%20Outline/Installing%20Outline%20Knowledgebase/)) with keycloak (and presumably other OIDC providers) will force log out after a short period and require reauthentication.

```
outline             | {"label":"database","level":"debug","message":"Executing (default): UPDATE \"users\" SET \"lastActiveAt\"=$1,\"updatedAt\"=$2 WHERE \"id\" = $3"}
outline             | {"label":"worker","level":"info","message":"ValidateSSOAccessTask running","userId":"acdcc812-abbb-4284-b385-b65eb6f7368b"}
outline             | {"label":"database","level":"debug","message":"Executing (67144fb7-851d-4ef0-be8d-19582cba9898): START TRANSACTION;"}
outline             | {"label":"database","level":"debug","message":"Executing (67144fb7-851d-4ef0-be8d-19582cba9898): SELECT \"id\", \"scopes\", \"accessToken\", \"refreshToken\", \"providerId\", \"expiresAt\", \"lastValidatedAt\", \"userId\", \"authenticationProviderId\", \"createdAt\", \"updatedAt\" FROM \"user_authentications\" AS \"user_authentication\" WHERE \"user_authentication\".\"userId\" = 'acdcc812-abbb-4284-b385-b65eb6f7368b' FOR UPDATE;"}
outline             | {"label":"database","level":"debug","message":"Executing (67144fb7-851d-4ef0-be8d-19582cba9898): SELECT \"id\", \"name\", \"enabled\", \"providerId\", \"teamId\", \"createdAt\" FROM \"authentication_providers\" AS \"authentication_provider\" WHERE \"authentication_provider\".\"id\" = 'da8bdc10-4382-40ee-975e-b7341017d51e';"}
outline             | {"label":"database","level":"debug","message":"Executing (67144fb7-851d-4ef0-be8d-19582cba9898): SELECT \"id\", \"name\", \"enabled\", \"providerId\", \"teamId\", \"createdAt\" FROM \"authentication_providers\" AS \"authentication_provider\" WHERE \"authentication_provider\".\"id\" = 'da8bdc10-4382-40ee-975e-b7341017d51e';"}
outline             | {"label":"database","level":"debug","message":"Executing (67144fb7-851d-4ef0-be8d-19582cba9898): SELECT \"id\", \"name\", \"enabled\", \"providerId\", \"teamId\", \"createdAt\" FROM \"authentication_providers\" AS \"authentication_provider\" WHERE \"authentication_provider\".\"id\" = 'da8bdc10-4382-40ee-975e-b7341017d51e';"}
outline             | {"id":"817d1c18-b304-4b76-8b1a-e792d772b48e","label":"utils","level":"info","message":"Refreshing expiring access token","userId":"acdcc812-abbb-4284-b385-b65eb6f7368b"}
outline             | {"endpoint":"[Filtered]","label":"utils","level":"debug","message":"Rotating token"}
outline             | {"id":"d8a378e1-8fd2-4fcf-9eba-6ccf83156292","label":"utils","level":"info","message":"Refreshing expiring access token","userId":"acdcc812-abbb-4284-b385-b65eb6f7368b"}
outline             | {"endpoint":"[Filtered]","label":"utils","level":"debug","message":"Rotating token"}
outline             | {"id":"496ccc59-980b-474f-b3e8-3b8c1ddb5359","label":"utils","level":"info","message":"Refreshing expiring access token","userId":"acdcc812-abbb-4284-b385-b65eb6f7368b"}
outline             | {"endpoint":"[Filtered]","label":"utils","level":"debug","message":"Rotating token"}
outline             | {"label":"database","level":"debug","message":"Executing (67144fb7-851d-4ef0-be8d-19582cba9898): SELECT \"id\", \"email\", \"name\", \"isAdmin\", \"isViewer\", \"jwtSecret\", \"lastActiveAt\", \"lastActiveIp\", \"lastSignedInAt\", \"lastSignedInIp\", \"lastSigninEmailSentAt\", \"suspendedAt\", \"flags\", \"preferences\", \"notificationSettings\", \"language\", \"avatarUrl\", \"suspendedById\", \"invitedById\", \"teamId\", \"createdAt\", \"updatedAt\", \"deletedAt\" FROM \"users\" AS \"user\" WHERE (\"user\".\"deletedAt\" IS NULL AND \"user\".\"id\" = 'acdcc812-abbb-4284-b385-b65eb6f7368b') FOR UPDATE;"}
```

_Originally posted by @routerino in https://github.com/outline/outline/issues/5532#issuecomment-1631863475_

**Comment by tommoor** [comment]
Do you have any actual errors in the logs?

**Comment by routerino** [comment]
> Do you have any actual errors in the logs?

No errors in the log, logs are as per the post (which is in debug mode). Can confirm that the issue also occured at the same time as #5532, was functioning before that period.

Closest I got is `"Authentication token no longer valid for acdcc812-abbb-4284-b385-b65eb6f7368b`, which isn't an error as such (though no idea why it is now considered invalid)

**Comment by routerino** [comment]
keycloak logs shed a bit more light:

```
023-07-15 01:47:38,640 WARN  [org.keycloak.events] (executor-thread-29) type=REFRESH_TOKEN_ERROR, realmId=8f60ba3a-4351-4c7f-bb5c-d3595f1f3841, clientId=kb.gurucomputing.com, userId=null, ipAddress=172.21.0.1, error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret
2023-07-15 01:47:38,647 WARN  [org.keycloak.events] (executor-thread-29) type=REFRESH_TOKEN_ERROR, realmId=8f60ba3a-4351-4c7f-bb5c-d3595f1f3841, clientId=kb.gurucomputing.com, userId=null, ipAddress=172.21.0.1, error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret
2023-07-15 01:47:38,654 WARN  [org.keycloak.events] (executor-thread-29) type=REFRESH_TOKEN_ERROR, realmId=8f60ba3a-4351-4c7f-bb5c-d3595f1f3841, clientId=kb.gurucomputing.com, userId=null, ipAddress=172.21.0.1, error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret
```

`userId=null` probably isn't right.

**Comment by tommoor** [comment]
I don't know about that, it's weird that everything is happening 3 times though.

**Comment by routerino** [comment]
could be keycloak just warns in three locations, the request may only be happening once.

**Comment by routerino** [comment]
Happens three times in outline too.
```
{"id":"817d1c18-b304-4b76-8b1a-e792d772b48e","label":"utils","level":"info","message":"Refreshing expiring access token","userId":"acdcc812-abbb-4284-b385-b65eb6f7368b"}
{"id":"d8a378e1-8fd2-4fcf-9eba-6ccf83156292","label":"utils","level":"info","message":"Refreshing expiring access token","userId":"acdcc812-abbb-4284-b385-b65eb6f7368b"}
{"id":"496ccc59-980b-474f-b3e8-3b8c1ddb5359","label":"utils","level":"info","message":"Refreshing expiring access token","userId":"acdcc812-abbb-4284-b385-b65eb6f7368b"}
```
I suspect it's because on a `401` the user gets knocked back to the login page, so the refresh function is likely firing multiple times.

**Comment by henriks** [comment]
I'm seeing frequent logouts with Authelia as OIDC provider also; Authelia's logs complain about invalid refresh tokens

```authelia_1           | time="2023-07-10T13:06:45+03:00" level=error msg="Access Request failed with error: The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client. invalid_token" method=POST path=/api/oidc/token remote_ip=192.168.10.1 stack="github.com/authelia/authelia/v4/internal/handlers/handler_oidc_token.go:27                   OpenIDConnectTokenPOST\ngithub.com/authelia/authelia/v4/internal/middlewares/http_to_authelia_handler_adaptor.go:113 NewHTTPToAutheliaHandlerAdaptor.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54                            (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35                           SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25                           SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16                           SecurityHeaders.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/cors.go:216                             (*CORSPolicy).Middleware.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:414                                             (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                                              (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                                           (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                                        (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                                        (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                                                     goexit"
```

**Comment by santiagobiali** [comment]
I'm having the same problem. Currently authenticating in Keycloak.
Outline v0.70.2 running on docker.

**Comment by VaalaCat** [comment]
I also have the same issue, I'm using Authentik, the login expires soon after upgrading to version 0.70, upgrading to 0.70.2 didn't fix the issue

**Comment by tommoor** [comment]
What are the expiry times of your access token and refresh token respectively?

**Comment by routerino** [comment]
> What are the expiry lengths of your access token and refresh token respectively?

Would I be looking for this information within keycloak or outline? Eitherway they'll be set to whatever the default is.

If it helps, I can also set up a remote browser-based dev environment with the problem present, if there is a problem recreating the issue. Would just need an e-mail to onboard.

![image](https://github.com/outline/outline/assets/45954722/6d7bd3a1-0b9d-4aff-8bce-8e71e476d11a)

**Comment by routerino** [comment]
Ah, digging into it a bit deeper this seems like intended behavior. Keycloak wants the session expiry to reflect a single session duration.

There is an option to enable an optional "remember me" checkbox which will let you set up longer durations for timeouts. I suspect if I set "remember me" and set the idle/max to 30 days it'll resolve the problem.

**Comment by tommoor** [comment]
Still looking for definitive proof, but while this is a behavior change due in the 0.70 release I’m not thinking of it as a bug currently

**Comment by routerino** [comment]
As an update, the "remember me" function affects keycloak login but not refresh token duration. This is actually probably fine (it means you get re-prompted to log in a lot but you don't need to re-enter credentials), but I'll experiment with increasing the SSO session duration instead and see if that solves the issue.

**Comment by routerino** [comment]
Increasing session time did not help. It appears that the refresh token request is actually malformed, keycloak throws an error regardless.

```
2023-07-26 18:56:49,778 WARN  [org.keycloak.events] (executor-thread-85) type=REFRESH_TOKEN_ERROR, realmId=8f60ba3a-4351-4c7f-bb5c-d3595f1f3841, clientId=[redacted], userId=null, ipAddress=172.21.0.1, error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret
```

**Comment by routerino** [comment]
Hooray, removing the race condition fixes the issue! 🎉 

Bit of a fun (read: setting up a whole dev environment for testing) troubleshooting process, but got there. Combination of race condition issues and default session timeouts for auth providers being too low.

**Comment by santiagobiali** [comment]
@routerino how you fixed it?

**Comment by routerino** [comment]
> @routerino how you fixed it?

Increasing session timeout (for keycloak at least) and testing with the development branch. You'd have to wait until the next release to see a fix.

**Comment by HanadaLee** [comment]
> > @routerino how you fixed it?
> 
> Increasing session timeout (for keycloak at least) and testing with the development branch. You'd have to wait until the next release to see a fix.

Is there a release date for the next version? During this period of time, I was very uncomfortable after upgrading, and even wanted to go back to the old version

**Comment by tommoor** [comment]
I haven't seen the fix @routerino is referring to yet.

**Comment by routerino** [comment]
> I haven't seen the fix @routerino is referring to yet.

https://github.com/outline/outline/commit/64b2718673d39a16744e45836af78762a3deebb1

**Comment by henriks** [comment]
For my part it seems I had just misconfigured OIDC on Authelia, but it happened to work before 0.70. I increased the refresh token lifespan, and added an `outline` value for the `audience` parameter, and am no longer having to frequently reauthenticate.

**Comment by tommoor** [comment]
**I'm closing this issue as "work as expected".**

Prior to `v.0.70.0` we were keeping users logged in beyond the expiry of the SSO token which was a _bug_. Now that this value is being respected a lot of folks are finding out that their token expiry was set to a very short value in the auth provider.

If you're having this problem the fix is to increase the session timeout, or token expiry (language depends on auth provider).

**Comment by Lauri-L** [comment]
I wonder if I can still add to this topic. What I've noticed so far, is that starting from v0.70.0, the outline app does not try to validate or go get a new access token, using the refresh token. So, in my case

- I'm using the on-prem docker along with keycloak as the generic OIDC provider.
- The application logs pre v0.70.0 always showed when there was a successful refresh, now I see no such logs.
```
{"id":" **** ","label":"utils","level":"info","message":"Successfully refreshed expired access token","userId":" *** "}
```
- Keycloak config for the access token lifetime is by default 5 minutes, and for better security it is recommended to be this short in the keycloak docs. The refresh token lifetime combined with the (SSO) session between the user and keycloak should be the thing that decides the session length.
- The access token lifetime is correctly indicated in the  'expiresAt' column of user_authentications
- The user_authentications table 'lastValidatedAt' , 'updatedAt', 'expiresAt', 'accessToken' and 'refreshToken' values do not get updated after the 'expiresAt' time is reached. In v0.69.0 these values get updated once 'expiresAt' time is reached, but only when the user reloads the webpage. Simply navigating the app doesn't seem to trigger the validation.
- The keycloak server logs tell the same story, I see no requests anymore from the application to the token endpoint to refresh. The only time I see tokens issued from keycloak is during login.

**Comment by tommoor** [comment]
Do you see `Refreshing expiring access token` in the logs? It would be good to get the server logs before the logout occurs.

**Comment by routerino** [comment]
Noting that I had this as a persistent issue until I exported the wiki, blew it away and re-imported. Suggesting that one of the version upgrades didn't migrate across correctly.

**Comment by Lauri-L** [comment]
Actually, I have to correct what I wrote in my last post - I can now see that the access token refresh is done, if I wait long enough. I probably do not understand when and in which conditions should the refresh take place. I assumed that it should be refreshed soon after the time saved in user_authentications 'expiresAt' has passed.

The reason why I started looking into this, is because my instance logs people out at seemingly random times. And in some conditions I see the same invalid refresh token errors in keycloak logs. And the reason why it is invalid, is because the 'iat' and 'exp' values in the refresh token posted to keycloak are 2 weeks in the past ..
```
{
  "exp": 1694803200,
  "iat": 1694768873,
  ....
 }
```

**Comment by Lauri-L** [comment]
Clearing the extra row for a user(s) in `user_authentications` definitely helped in my case. No more random logouts from the app. What I think might have happened:
Somehow, maybe during the version upgrade, the `authenticationProviderId` changed, or maybe it was because me changing the oidc configuration.
The extra row had an old `refreshToken` saved, with which the app randomly tried to request a new token from keycloak. When the app attempts to refresh with an expired token, it gets a 400 "Invalid refresh token", and correctly kicks the user out in order to conform with keycloak's idle timeout settings.

**Comment by MorganReid** [comment]
I use the 0.71.0 self-deployed outline service and integrate it with `keycloak`.

Now **users are randomly logged out.** At this time, sometimes they can directly log in successfully when they visit the outline (click` continue with login`). Sometimes, after clicking `continue with login`, they will jump to `keycloak`, and they need to manually enter the user name and password to successfully log in.
![mmexport1697700084903](https://github.com/outline/outline/assets/52235796/65374e3a-cfb4-4e00-aa13-54406e66a1bc)
How is this random exit triggered?

As [Lauri-L](https://github.com/Lauri-L) mentioned,I checked the related tables of the database.
Each user has only one record in `user_authentications`, but  `authentication_providers` table has 2 records.
![image](https://github.com/outline/outline/assets/52235796/91463647-a1ee-47d7-af08-81ff546680f5)
![image](https://github.com/outline/outline/assets/52235796/d4b8d97b-22f4-4d68-b286-511d7084ff24)

  Keycloak's` /token` interface will return `access token `and `refresh token`. However, the outline service log cannot see `Refreshing expiring access token `or `Successfully refreshed expired access token`.
![image](https://github.com/outline/outline/assets/52235796/c9d06472-79e0-4e83-a84d-267830a74358)
 
@Lauri-L @tommoor @routerino

**Comment by MorganReid** [comment]
`ValidateSSOAccessTask` will verify the user's information. If all are invalid then need to revoke the users Outline sessions (actually updating the `users` table `jwtSecret` to random). Is this what causes users to be automatically logged out?
`UserAuthentication'` `validateAccess` method Validates that the tokens within this authentication record are still valid.,Will update the record with a new access token if it is expired.
What scenarios trigger `ValidateSSOAccessTask` or how often does it execute?If I want to set the outline to stay logged in for 3 days, how should I set it?

**Comment by Lauri-L** [comment]
For me it was also a key thing to understand what is called what in keycloak.

SSO idle timeout determines how long is the refresh token valid. In my case, I configured it as realm level.
How long do you need your users logged in to the app while not interacting with the app ?

SSO max is the lifetime of the end user session with keycloak. After SSO max expires, the refresh token provided by the app will not be accepted any longer, even if it is valid (otherwise you would have infinite access). SSO max lifetime should be longer than the idle timeout.
Here you should ask how long would you like before keycloak logs the user out from keycloak and the app ? 

As long as you have answers to the first 2 questions, the access token lifetime can be 5 minutes no problem (default).

**Comment by MorganReid** [comment]
> Outline will stay logged in for as long as the authentication token or refresh token it is given – `ValidateSSOAccessTask` is triggered when a user loads the app after a period of inactivity. The answer is to have your OIDC service issue longer tokens or refresh tokens.
`a period of inactivity` How long is it specifically? It depends on the configuration?

**Comment by MorganReid** [comment]
> For me it was also a key thing to understand what is called what in keycloak.
> 
> SSO idle timeout determines how long is the refresh token valid. In my case, I configured it as realm level. How long do you need your users logged in to the app while not interacting with the app ?
> 
> SSO max is the lifetime of the end user session with keycloak. After SSO max expires, the refresh token provided by the app will not be accepted any longer, even if it is valid (otherwise you would have infinite access). SSO max lifetime should be longer than the idle timeout. Here you should ask how long would you like before keycloak logs the user out from keycloak and the app ?
> 
> As long as you have answers to the first 2 questions, the access token lifetime can be 5 minutes no problem (default).

The requirements are: after the user accesses the outline and logs in using keycloak, he does not need to log in again within 3 days and can directly access the outline. After 3 days, he exits the outline and needs to log in again using keycloak.

My keycloak configuration:
_**Sessions setting**_

![image](https://github.com/outline/outline/assets/52235796/30763ef2-c07f-490b-a14c-427ba1d6a10b)

_**Tokens setting**_

![image](https://github.com/outline/outline/assets/52235796/6d4c5584-0867-487e-a5f5-ec65944d2013)

Now users are randomly logged out, not the expected 3 days. a period of inactivity outline sometimes several hours, sometimes one  day or other period.

Four outline mirrors are started on a server, and each mirror will be restarted regularly to perform load balancing on the nginx . Will this have any impact?
![企业微信截图_16977660769249](https://github.com/outline/outline/assets/52235796/5e658652-9bbd-4f9f-99a0-7aef093e3ecf)
![image](https://github.com/outline/outline/assets/52235796/98a7ee29-23af-466e-9bce-0927b80b20f2)

**Comment by mpflanzer** [comment]
I noticed the same behavior of constantly being logged out even when using the wiki almost continuously. I think narrowed it down to this:

- Access token expires after 5 minutes
- Refresh token expires after 30 minutes

But these lines prevent outline from actually refreshing anything in the first hour after login: https://github.com/outline/outline/commit/92c8eff61d55e435d792ac8fea59acdd19508eb7

So, first, outline keeps the session active for longer than the token allows, and, second, after 1 hour I'm definitely logged out as the refresh token expired by then even if I was constantly using the wiki during that time.

Does my reasoning make sense? Why was this grace period of 1 hour after login introduced? Why not check the validity on every request as it would be the case after the first hour of login?

**Comment by tommoor** [comment]
I really don't know why folks are insisting on setting such short lifetimes on tokens, Google's refresh token lasts 200 days.

Outline will only validate the token with SSO when you reload the app, so if you don't reload the app within 35 minutes with those settings then you'll be logged out.

**Comment by mpflanzer** [comment]
I agree that the 30 minutes are very short. But that's the default in Keycloak. :shrug: I increased it now to are more reasonable duration.

But still, outline would currently allow access for longer than the access/refresh token intended. And the 1 hour threshold feels as random to me as the 30 minute lifetime. Reading the comment that says "_just_ signed in" I expected something like 5 minutes maybe. An hour doesn't really feel like "just" to me.

Just my 2 cents and I thought it might help people running into the same kind of problem.

**Comment by tommoor** [comment]
> But still, outline would currently allow access for longer than the access/refresh token intended. 

Outline has its own session system that works independently of the many SSO providers we support. If you log out of Google, for example, there is not an expectation that you are then logged out of every other service that you signed into using Google. The authenticated sessions are separate.

Really the token validation in Outline is provided as a convenience so that if a user is deleted or suspended in the authentication provider they are logged out on Outline automatically within a reasonable timeframe.

**Comment by MorganReid** [comment]
> > But still, outline would currently allow access for longer than the access/refresh token intended.
> 
> Outline has its own session system that works independently of the many SSO providers we support. If you log out of Google, for example, there is not an expectation that you are then logged out of every other service that you signed into using Google. The authenticated sessions are separate.
> 
> Really the token validation in Outline is provided as a convenience so that if a user is deleted or suspended in the authentication provider they are logged out on Outline automatically within a reasonable timeframe.

Accessing the outline will cache an `accessToken` valid for 3 months in the browser's cookies. Is this the outline's own session system?
Then `ValidateSSOAccessTask` fails to execute, and the user's `jwtSecret` is set to a random value. In this way, the `accessToken` carried during access will fail to be verified, resulting in exit.

As @tommoor  said, `ValidateSSOAccessTask` is triggered when a user loads the app after a period of inactivity, but now some customers will not be exited, and some will be exited randomly. The customers who were exited randomly should have an exception when executing `validateAccess`. What is the specific period of inactivity?

Is `accessToken` verification failure the reason for automatic exit? Are there other reasons that may cause automatic exit?

**Comment by wildsylvan** [comment]
>  after 1 hour I'm definitely logged out as the refresh token expired by then even if I was constantly using the wiki during that time.
it's happening to us as well when using logto with oidc...

**Comment by tommoor** [comment]
The configuration is on your OIDC provider, you must increase the session timeout there

**Comment by wildsylvan** [comment]
![image](https://github.com/outline/outline/assets/19886441/281e1408-6ec7-4f5d-8ecb-4998372a285a)
these seem to be the only settings we can configure...

---

Directly changing access token expiration in Logto isn't possible. Logto prioritizes security and focuses on refresh token rotation for access token management.

Here's why:

Security: Short-lived access tokens minimize damage if compromised.
Refresh Tokens: Handle long-term access needs. Logto automatically rotates refresh tokens to mitigate risk.

**Comment by tommoor** [comment]
It looks like always issue refresh tokens will resolve your issue? Outline expects one in this case

**Comment by wildsylvan** [comment]
ok i was wondering about that. ill try it. thanks!

**Comment by wildsylvan** [comment]
from logto audit logs i see that now it includes a refresh token:

![image](https://github.com/outline/outline/assets/19886441/f52df58f-d732-40b2-9249-ce0bbdbbcc65)

shouldn't outline ask for a refresh token explicitly tho? it looks a bit of a hack enabling this...

**Comment by tommoor** [comment]
🤷 Every IDP is different.

**Comment by wildsylvan** [comment]
ok... because it said:
> However, this practice is discouraged unless necessary, as it is not compatible with OpenID Connect and may potentially cause issues.
