### ISSUE TITLE
Capture potential users that don't use Slack

### ISSUE THREAD

**Issue by tommoor** [outline/outline#557]
I was thinking it would be a good idea to put a note under the "Sign in with Slack" button, where we can try and capture users that would rather use email / google auth etc... maybe have them enter details into a Google Form or something similar?

Thoughts @jorilallo ?

**Comment by krrisztian** [comment]
I would personally love to look into/use this wiki by myself as there are basically no great wikis out there.
It keeps me out however that I can only use or even test it with Slack.

**Comment by ggamel** [comment]
Additional auth options (e.g. email, Google) would be great.

**Comment by zbhoy** [comment]
Agreed with above. Company is very small and doesn't use slack and won't for the foreseeable future. A simple email signup would be best

**Comment by tommoor** [comment]
Hey @zbhoy just a quick note – we're going to avoid simple email signup because unfortunately it's anything but simple, with it comes:

- Password management and reset
- Email invites and invite management
- Easily duplicated teams
- Inability to use your email across multiple accounts (this is possible with Slack signin)
- And many more edge case issues…

**Comment by ggamel** [comment]
Spectacular, @tommoor! 👏 🍾
