### ISSUE TITLE
Synchronized scrolling outside of observer mode

### ISSUE THREAD

**Issue by cimboe** [outline/outline#5570]
We're currently experiencing an issue where whenever two people are viewing the same page, observer mode seems to be enabled automatically for one of the two, and scrolling is kind of janky for the other. This behavior is reproducible with the latest versions of Chrome and Firefox on Windows.

We're using a self-hosted instance.

**Comment by tommoor** [comment]
Please use the bug template, there's not enough information here.

**Comment by cimboe** [comment]
Thank you!

**Comment by askzhangbo** [comment]
Is is possible to disable Observer Mode globally in Outline?

**Comment by askzhangbo** [comment]
Is it possible to disable Observer Mode globally in Outline? 

It's really frustrating that the page keeps scrolling while multiple users are viewing it, even when they're  not in Observer Mode.😒

This issue can be reproduced when specific users, like 10, open a page. 😕

**Comment by tommoor** [comment]
No, but this fix isn’t in a release yet so it will be resolved at that point

**Comment by NangeGao** [comment]
Could a fix version be released as soon as possible? When we have a meeting, multiple people view the same document. This bug prevents us from using it normally.

**Comment by tommoor** [comment]
https://github.com/outline/outline/releases/tag/v0.71.0
