### ISSUE TITLE
I can't login on Mac M1

### ISSUE THREAD

**Issue by ctwhome** [outline/outline#5577]
The interface keeps blinking and I can't log in. 

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

![Jul-18-2023 11-32-45](https://github.com/outline/outline/assets/4195550/e44ec2cb-3b6b-4ca9-97c2-1f9ddd8a1087)

**Outline (please complete the following information):**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 13.4.1 (22F82)

**Comment by tommoor** [comment]
Please quit and restart and the app, this looks like a bug that was addressed and you just need the latest code

**Comment by docbobo** [comment]
Just having the same issue. Restarting the app has not effect. Seems that the official 1.1.0 has this problem. Is there any place, where I can get a newer version with the latest code?

**Comment by tommoor** [comment]
Hey guys, looking into it now.

**Comment by tommoor** [comment]
Okay, a fix was pushed to production – you don't need a new download, just reload the app to get the latest code bundle.
