### ISSUE TITLE
embedding file inside table breaks table

### ISSUE THREAD

**Issue by fabiansiegel** [outline/outline#5586]
When embedding a file inside a table, the table breaks, because the file-display-bar is too wide

**To Reproduce**
1. edit a document
2. create a table
3. enter a cell
4. attach a file
5. See broken table

**Expected behavior**
inside a table, the file-embed should be confined to the cell size. I tried this by editing the css of the embed, and it would work if the box was: `display: inline-block;` instead of `display:block;`
I was however unable to write a pull request.

**Screenshots**
![outline_attach_file_in_table](https://github.com/outline/outline/assets/4614435/6437e84c-8619-40d1-9376-3032af8bc9c5)

with: display:inline-block;
![image](https://github.com/outline/outline/assets/4614435/ef770755-0b4c-4adc-beb9-c1e5c0c3a8db)

**Outline (please complete the following information):**
- Install: self hosted
- Version: b9fc301

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version any

**Comment by tommoor** [comment]
Blocked by #3000
