### ISSUE TITLE
Localhost Parameter in docker.env seems to be ignored

### ISSUE THREAD

**Issue by craftzneko** [outline/outline#5610]
I need to set the URL that outline listens on to http://0.0.0.0:3000. Changing the URL parameter in docker.env based on the env sample file doesnt seem to work it still says its listening on http://localhost:3000. Am i missing something?

**Comment by tommoor** [comment]
`URL` is the publicly accessible url, the server listens on `0.0.0.0` automatically in an IP4 environment.

**Comment by craftzneko** [comment]
thanks @tommoor i had issues getting the cotnainer to stay up and azure support said to make sure it listens on 0.0.0.0 and not localhost. Does outline automatically listen on port 3000 and is that changeable via the PORT setting in the environment file?

**Comment by SirEdvin** [comment]
This is not possible right now , you need to manually change [this](https://github.com/outline/outline/blob/main/server/index.ts#L135) line and pass "0.0.0.0" as second argument

**Comment by tommoor** [comment]
`0.0.0.0` is the default value for the second argument so it's not required. [See docs](https://nodejs.org/api/net.html#serverlistenport-host-backlog-callback)
