### ISSUE TITLE
Emoji feature is really annoying when writing french

### ISSUE THREAD

**Issue by mont5piques** [outline/outline#5611]
In french, colon character is widely used and in french typography, there is a space before and after the colon caracter.
That conflicts with the emoji feature since it is triggered by space + colon combo.

It is specially annoying in french because it's very commonly used in line ends to introdruce a list for example. We end up then with an emoji when typing colon + carriage return.

There may be a way to disable emoji feature.

**To Reproduce**
Open an editor on any page and type a space followed by a colon character

**Expected behavior**
A way to disable emojis.

**Screenshots**
N/A

**Outline (please complete the following information):**
- Install: getoutline.com
- Version: ?

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 111

**Comment by tommoor** [comment]
While we have made a [change here before](https://github.com/outline/outline/issues/5387) so that typing a space directly after the colon will close the menu I do understand your usecase, I think it's worth an exception for languages that use colon in this way.

Question – is your system/browser language set to French?

**Comment by josselinonduty** [comment]
I am facing the same QOL issue ;

My browser is set to System default, system being French. And my outline language preference is set to french.

**Comment by mont5piques** [comment]
Same, both my browser and outline preferences are set to french.

**Comment by nickorr** [comment]
Is there any way to turn off the emoji thing for the rest of us that don't speak French?  I've tried blocking the two js files but that breaks the whole site.

**Comment by tommoor** [comment]
There isn't, it's very much built in
