### ISSUE TITLE
code line number display out of order when adjust minimum font size to a bit larger

### ISSUE THREAD

**Issue by wenqvip** [outline/outline#5612]
**To Reproduce**
1. Go to setting of the brower, adjust the minimum font size to a bit larger.
2. Go to outline and see the line number of code segment display out of order.

**Expected behavior**
the line number should display correctly when adjust minimum font size to a bit larger

**Screenshots**
![image](https://github.com/outline/outline/assets/3266967/03598813-d272-4f91-8ecc-e0726009cb3a)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.70.1

**Desktop (please complete the following information):**
 - OS: windows11
 - Browser edge and chrome
 - Version newest version of browers

**Comment by tommoor** [comment]
Could you take a screenshot of the specific setting that has been changed? Changing this setting or the zoom setting in Edge I am currently unable to reproduce

<img width="856" alt="image" src="https://github.com/outline/outline/assets/380914/4099ca74-753e-40d4-8f67-90afd8870d4c">

**Comment by wenqvip** [comment]
first step:
![image](https://github.com/outline/outline/assets/3266967/34849a86-e5ab-45c2-bace-ce4f397bdf32)
second, set font size to the pic shows:
![image](https://github.com/outline/outline/assets/3266967/3c32539b-fce4-480f-8b43-f3ee81beff00)
then go to the document and look the code line number. note that it is easy to reproduce when line number count less than 5.
