### ISSUE TITLE
Page deletion dialog buttons mildly confusing

### ISSUE THREAD

**Issue by vijfhoek** [outline/outline#5613]
_Note: I wasn't quite sure if this would be a bug report ("The buttons aren't great like this"), or a feature request ("Please add this button"). Decided it's better off as a bug report, so here we go._

When deleting a collection, a dialog pops up allowing the user to pick between truly deleting or archiving the page. This, however, looks a lot like an "Are you sure you want to delete this?" dialog, for which the intuition is that the non-red button would mean canceling deletion. Clicking this button too hastily will result in the page getting archived, which may not be the user's intention.

**To Reproduce**
1. Accidentally press the 'Delete' option in the overflow menu of a page
2. Skim over the dialog's content
3. Hit the 'Archive' button, expecting it to cancel the deletion
4. Page disappears

**Expected behavior**
One solution would be adding a Cancel button to the right of the Archive button. I know hitting the X button cancels deletion, but also adding a (redundant) Cancel button feels more natural

**Screenshots**

Current situation:

![A screenshot showing Outline's page deletion dialog, with a red, primary "I'm sure - delete" and secondary "Archive" button](https://github.com/outline/outline/assets/345785/58a8ee58-f3e1-4281-acd8-76150fc0faa2)

Proposed solution:

![Same as the previous screenshot, but with an added Cancel button](https://github.com/outline/outline/assets/345785/97a4cee5-dc0e-4169-999d-98cd70ae6bf2)

**Outline (please complete the following information):**
- Install: Self-hosted
- Version: 0.70.2 (b9fc301)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 38
 - Browser: Firefox 115.0.2 (64-bit)

**Comment by tommoor** [comment]
I don’t know, three buttons is a lot of mental overhead and archive is totally reversible

**Comment by tommoor** [comment]
Will take it under advisement for future modal improvements, but not actioning right now
