### ISSUE TITLE
authentication with azure works but outline rejects

### ISSUE THREAD

**Issue by craftzneko** [outline/outline#5618]
![image](https://github.com/outline/outline/assets/662108/fac2b3ba-8ea7-404f-bf28-fd5db128656d)

Originally logged as discussion but feels like a bug as using postman to generate correct authentication requests to app service works and indeed the logs show the request is valid and the repsonse looks valid but outline rejects

This is a fresh docker compose build is there some kind of intial user that needs to be created or something first. I followed the guide exactly for Azure authentication. Error appears as 

2023-07-27T12:53:45.565917060Z {"error":"Validation error: Validation isIP on ip failed","level":"error","message":"Error during authentication","stack":"UnauthorizedError: Validation error: Validation isIP on ip failed\n    at InvalidAuthenticationError (/opt/outline/build/server/errors.js:44:34)\n    at accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:59:54)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}

I have set LOG_LEVEL to debug but this is the most i get from it

**Comment by craftzneko** [comment]
Anyone have any ideas on issue? I wouldnt mind it generating more logs to explain exactly where its failed but even setting DEBUG=silly doesnt generate anything more

**Comment by craftzneko** [comment]
@tommoor  I could be on the wrong tack here but it seems that CTX is the context created by KOA and then ctx.ip is passed to the accountProvisioner inside azure plugin

![image](https://github.com/outline/outline/assets/662108/7360c86b-0db4-4a8b-9595-b6e38ca25e68).

As this is handled by a proxy i believe that KOA is using that value as its IP and there is an old issue (going back to 2016) that shows the port is being passed along with the IP https://github.com/koajs/koa/issues/827

The fact the bug has been there since 2016 suggests its not likely to be fixed soon, would it be possible for outline to handle the formatting of the CTX.ip by stripping the port out if it is in there? I would be happy to have a go at creating some code to do that but i am inexperienced so forgive my errors.

The advantages to doing this would mean it could be hosted inside azure app service and use azure authentication. We are keen to trial the product and if it fits for us we want to take out support

**Comment by tommoor** [comment]
Hi @craftzneko – you should update `x-forwarded-for` header to not include the IP address, while it's not strictly standardized this is expected behavior from almost every implementation.

I don't think we want to introduce code in Outline to work around this.

**Comment by craftzneko** [comment]
I think you may have misunderstood what I meant or I am not understanding your reply. Kua is using X-forwarded-for header as the IP address in the context, azure and indeed other proxy services do sometimes include the port along with the IP, because its not standardised format so there is zero requirement for providers to stick to any kind of format. I would prefer that KOA use the forwarded header as that is a standard. If you format the response inside outline you are ensuring the data that is collected meets the format for the object. So currently outline records the IP and I am guessing you use an expression to check it is a valid IP and if it isn't you just fail the request. I am suggesting that rather than failing it you check if it has a port appended to it and strip it out. One point of failure handled.

Justification for making the change would be that control of the proxy is not always possible in every circumstance such as azure app service and as Microsoft are a large provider in this space it would make sense to make it compatible to increase the exposure of your app and potentially clients paying you for support services.

On our specific case, we are trialing this software for use and we have to host it on our own infrastructure so taking out your hosted plan is not an option for us, however we do want support if we decide to go ahead. So it does help you gain at least one customer if that's at all valuable to you

**Comment by tommoor** [comment]
I understand the issue, if you wish to pursue a well tested PR for removing the port I'd be open to accepting the contribution. It would need to work with ipv6 as well.

**Comment by craftzneko** [comment]
Thanks @tommoor, not being a native developer the chances of me learning typescript and the associated steps to create a pull request are pretty much zero. While i really wish i had the luxury of time to do this i need to focus on the objective of why i even came to look at outline in the first place. Time for us to move on. I wish everybody the best of luck trying to get outline working outside of the native outline hosting especially if using azure app service
