### ISSUE TITLE
S3 bucket URL can't contain bucket name, results in HTTP 400

### ISSUE THREAD

**Issue by wouter-deen** [outline/outline#5645]
Using MinIO S3-compatible storage, the hostname in the URL isn't allowed to contain the name of the bucket.

**To Reproduce**
I have a bucket called "outline" and I'm using Nginx to route my MinIO docker container (the API endpoint, not the console) to outline-files.[...].com. This results in a 400 error in the browser when Outline makes a POST request to my bucket to upload a file. Changing the hostname to something that does not contain "outline" (the bucket name), as pointed out by @tommoor a couple of years ago in [this issue](https://github.com/outline/outline/issues/2068), solves this issue. In my case, I simply changed my subdomain from outline-files.[...].com to ol-files.[...].com. Note that I have the environment variable `AWS_S3_FORCE_PATH_STYLE` set to `true`, so this should not confuse the URL.

**Expected behavior**
It should have just worked with the bucket name in the hostname / domain name.

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 0.70.2 (latest version as of posting)

**Desktop (please complete the following information):**
 - OS: Windows, Mac, Linux
 - Browser: Chromium-based (Brave (Windows) and Arc (Mac))
 - Version: 115.0.5790.114

Edit: faulty markdown formatting.

**Comment by wouter-deen** [comment]
> I've been using Outline with a bucket named 'outline' on a minIO server for quite some time now, without any issues (`AWS_S3_FORCE_PATH_STYLE` was set to `true`, as well).

Hmm that's very interesting to hear. What version of Outline and Minio are you running on? During my testing, the name was clearly the problem (changing back and forth would break/unbreak it).

**Comment by tommoor** [comment]
Yea this has been a long standing issue due to backwards compatibility- we should probably just make a breaking change

**Comment by herzkerl** [comment]
> Hmm that's very interesting to hear. What version of Outline and Minio are you running on? During my testing, the name was clearly the problem (changing back and forth would break/unbreak it).

I created the Outline bucket on Sep 06 2022, and there seem to be objects in the bucket with that date, so for almost a year...
Currently running minio version RELEASE.2023-07-11T21-29-34Z
