### ISSUE TITLE
Issues with Word Document Import and Image Loss in Outline v0.70.2

### ISSUE THREAD

**Issue by zombie0378** [outline/outline#5653]
Title: Issues with Word Document Import and Image Loss in Outline v0.70.2

Issue 1:
When attempting to import a Word document of approximately 4MB in size, I encountered the following error: "documents.import failed in 10838." It appears to be a timeout issue with the interface. Is there a configuration setting available to adjust the timeout duration?

Issue 2:
After refreshing the page, the document was successfully imported. However, I noticed that some images located at the top of each page in the Word document are missing and appear as blank images.

Outline Version: v0.70.2

Description:
I encountered two issues while working with Outline version v0.70.2. Firstly, when importing a Word document of around 4MB, the import process fails with the error message "documents.import failed in 10838." It seems to be related to a timeout issue. I would like to know if there is a way to adjust the timeout configuration to resolve this problem.

Secondly, even though the document imports successfully after refreshing the page, I observed that certain images positioned at the top of each page in the Word document are not displayed properly. Instead, they appear as blank images.

It would be greatly appreciated if these issues could be addressed and resolved in a future update of Outline.

<img width="347" alt="企业微信截图_16913888392157" src="https://github.com/outline/outline/assets/37998603/f0b219e1-8daf-4856-a5d0-43cd17e6b52b">

![image](https://github.com/outline/outline/assets/37998603/15da8add-d745-4908-9bc4-f7e2f4237f70)

**Comment by tommoor** [comment]
Did any images import at all? If not most likely the issue is with your storage configuration and it's not possible for the server to reach the storage for image upload.

**Comment by zombie0378** [comment]
> 

Not all images, only some of the images. I can reproduce this bug with the outline hosted on [www.getoutline.com](http://www.getoutline.com/) as well. You can use Word document like this.
![image](https://github.com/outline/outline/assets/37998603/6ff585bc-e269-489b-951a-a633e58a1547)
![image](https://github.com/outline/outline/assets/37998603/98737283-63ca-4597-bb91-45f36a435e9c)

**Comment by zombie0378** [comment]
> Did any images import at all? If not most likely the issue is with your storage configuration and it's not possible for the server to reach the storage for image upload.
> 
> Often this is an issue with DNS resolution. If _some_ images uploaded fine, then it's a different matter.

Not all images, only some of the images. I can reproduce this bug with the outline hosted on [www.getoutline.com](http://www.getoutline.com/) as well. You can use Word document like this.
![image](https://github.com/outline/outline/assets/37998603/851cbd68-96bb-423d-95b9-a3e083fe21e8)
![image](https://github.com/outline/outline/assets/37998603/851cbd68-96bb-423d-95b9-a3e083fe21e8)

**Comment by zombie0378** [comment]
> Did any images import at all? If not most likely the issue is with your storage configuration and it's not possible for the server to reach the storage for image upload.
> 
> Often this is an issue with DNS resolution. If _some_ images uploaded fine, then it's a different matter.

Not all images, only some of the images. I can reproduce this bug with the outline hosted on [www.getoutline.com](http://www.getoutline.com/) as well. You can use Word document like this.
![image](https://github.com/outline/outline/assets/37998603/69b502f2-c09d-4a31-b4ff-79a1b17c5c68)

![image](https://github.com/outline/outline/assets/37998603/faf955ab-465a-4f23-af74-5d26cb085296)

**Comment by Nedved-liao** [comment]
I had the same problem
with Outline version v0.70.2

Create a new page and insert an image
![Screenshot 2023-08-10 150613](https://github.com/outline/outline/assets/35453327/ed7e2c6a-2e0b-4a30-b670-262a48e6bbbd)

The picture disappeared after the page was published
![Screenshot 2023-08-10 150638](https://github.com/outline/outline/assets/35453327/18135b95-fb04-4916-ac6d-f334e39f3ee7)

with chrmoe F12 console , i found MinIO the upload url an extra layer of stitching

AWS_S3_UPLOAD_BUCKET_URL=https://minio.com

in  chrmoe F12 console

 https://outline.minio.com/uploads/xxxxxx

**Comment by Nedved-liao** [comment]
> 

slove
this configuration item must be enabled;
> AWS_S3_FORCE_PATH_STYLE=true

**Comment by tommoor** [comment]
@zombie0378 can you upload the word document you tested with? I do not have a copy of word and want to make sure the reproduction works

**Comment by zombie0378** [comment]
> @zombie0378 can you upload the word document you tested with? I do not have a copy of word and want to make sure the reproduction works

https://w1690179507-l8p405798.getoutline.com/s/f39c4246-1f7a-4b68-a511-6de4d4631867
1111.docx
I have uploaded the file to this website. The area below the file contains the image and the blank space, which represents the result after uploading.

**Comment by tommoor** [comment]
Perfect, the key is that that images must be identical.
