### ISSUE TITLE
Outline leaks private minio URL to public web pages

### ISSUE THREAD

**Issue by dmikushin** [outline/outline#5654]
Dear Outline community,

I've been trying to understand why self-hosted minio is unable to serve the self-hosted Outline **v0.70.2** [installation in the Docker container](https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t). Any image upload fails without with "Upload failed" popup in the Outline web interface. No errors in the minio trace. None of the releated suggestions [1](https://github.com/outline/outline/discussions/3366#discussioncomment-3077478) and [2](https://github.com/outline/outline/discussions/3437) solve the problem.

**I've concluded that the reason is that Outline apparently leaks the used minio URL to the public web pages.**

![Screenshot from 2023-08-07 15-55-16](https://github.com/outline/outline/assets/5672874/dc117be0-90ac-4bbf-b0e1-94b77fe413c0)

As you can see in the attached screenshot, the user profile webpage tries to access http://storage:9000/outline-bucket This fact is in the total disagreement with the Docker container setting that minio service is accessible to outline service **privately only within the container**.

I know of other similar projects that are able to maintain proper internal use of minio in a similar docker container environment.

Therefore, I kindly ask you to apply your best skills towards solving this issue, as it also looks like a vulnerability.

**Comment by dmikushin** [comment]
My current workaround is to have minio storage as a public HTTPS service. You can keep minio within the `docker-compose.yml`, but expose it to a public network interface. Then, get a HTTPS redirection for it with Nginx and Let's Encrypt. Finally, follow @Nicicalu 's [settings](https://github.com/outline/outline/discussions/3366#discussioncomment-3077478) to set up the proper `docker.env` settings. After all these steps, Outline minio works.

I'm not an expert in this field, but I'll share a reference to another project, who have managed to keep minio within their own proxy environment, which works much smoothly in Docker: https://github.com/makeplane/plane/blob/develop/docker-compose.yml Maybe this could give you an idea how to implement this...

**Comment by tommoor** [comment]
Hi @dmikushin – this is by design, Minio is used as a replacement for Amazon S3 which is public facing – uploads are performed from the browser directly to the storage layer.

**Comment by Nicicalu** [comment]
Hi @dmikushin 
Why is it bad that Minio is public facing? The Amazon S3 is also public facing and Minio is basically just a self hosted replacement for Amazon S3 Storage.

**Comment by dmikushin** [comment]
> Hi @dmikushin Why is it bad that Minio is public facing? The Amazon S3 is also public facing and Minio is basically just a self hosted replacement for Amazon S3 Storage.

It is orthogonal to the Docker containers design. Unlike S3, docker services should be private within one composition, and expose to the public the frontend only.

> Hi @dmikushin – this is by design, Minio is used as a replacement for Amazon S3 which is public facing – uploads are performed from the browser directly to the storage layer.

Even if you say that Amazon S3 is your main goal, @tommoor , there are ways to proxy connections within the self-hosted nginx server to make a universal solution for both Docker and S3. Please don't be lazy and look into the link above before prematurely closing the issue.

**Comment by Nicicalu** [comment]
@dmikushin Personally I've installed Minio seperatly. That way I can use it for other services aswell and it has it's own docker network. Then it is exactly like AWS S3 storage because it's seperatly hosted. Then Outline is just a service that has a bucket in minio

**Comment by dmikushin** [comment]
> @dmikushin Personally I've installed Minio seperatly. That way I can use it for other services aswell and it has it's own docker network. Then it is exactly like AWS S3 storage because it's seperatly hosted. Then Outline is just a service that has a bucket in minio

This makes sense, but the Docker setup offered by Outline is broken, and this argument does not help it. If Outline is willing to provide a Docker setup, this behavior is not compatible with how Docker services usually work. Consider for example postgresql. A Docker setup, which owns a private postgresql database is very very common. Of course, if you don't want it, you CAN have a separate postgresql database. But both methods are possible. Do you agree that the same should hold true for minio/S3 as well?

**Comment by Nicicalu** [comment]
> @Nicicalu Not exposing to public things that are not necessary to be exposed is essentially the best practice of secure development, isn't it?

Can't argue with that. Like I said, it would be a good feature.
