### ISSUE TITLE
Kindle Scribe Integration

### ISSUE THREAD

**Issue by CarlesLlobet** [outline/outline#5663]
Hey there!

First of all thanks for this amazing product, can't wait for more amazing features to come (Kanban/Canva, predefined templates, etc).

However I haven't seen any request such as mine:
With the (not so much anymore) recent release of Kindle Scribe, I think it'd be awesome to write an integration for it that allowed to easily sync / grab any E-Notes into outline.

[Obsidian](https://obsidian.md/) for example has had for some time a [Kindle plugin](https://github.com/hadynz/obsidian-kindle-plugin) that allows to sync all highlights and notes. Many people has already written about it (e.g: [Medium](https://mattgiaro.medium.com/how-to-sync-your-kindle-highlights-into-obsidian-for-free-e49a2b7179c0))

I didn't see this integration much useful (except for book reviewers / etc), but now that the new kindle E-Notebook (Scribe) has come into play, an integration like this would allow to take the best of both worlds:
1. Handwrite all your daily notes into your Kindle Scribe.
2. Go into your outline and sync them to continue typing your thoughts.

This could be implemented in many ways, and it can improve over time, but at least being able to sync content into a page would be great.

However in future it would even be more awesome that the integration created a separate collection, and synced all your notes there (folders as pages and notes as subpages), and always was synced automatically.
This way you'd just open outline and continue your work there.

WDYT ?

[This implementation for Obsidian](https://github.com/obsidianmd/obsidian-sample-plugin) is also in TypeScript so probably most of the sync code could be directly reused.

**Comment by CarlesLlobet** [comment]
Note: Probably #enhancement and #integrations labels would be suit better but I don't seem to be able to change them

**Comment by tommoor** [comment]
Hi Carles, I don' think this makes sense for Outline as we're staying focus on being a store of _team_ knowledge, not an individual note taking tool – for that there are lots of other projects including Obsidian itself.

**Comment by CarlesLlobet** [comment]
Hi @tommoor,

There's also a huge community using outline as a self-hosted documentation/notes personal base, similar to how Notion serves both purposes perfectly (enterprise & personal).

However I do understand the focus of outline right now is on enterprise knowledge base.

Do you see the integration viable though? 
If so, I'd love to contribute myself with this integration if the team's focus is elsewhere, since I think it'd be of great use to all the community using outline as a self-hosted Notion.

**Comment by tommoor** [comment]
It seems viable within the current plugin system if you want to give it a go. I think there will be some questions that come up that I'm happy to answer.

**Comment by CarlesLlobet** [comment]
Closing to Archive it, but still pretending to look for the time to implement it 👍
