### ISSUE TITLE
The state of the Header sections is not independent for readers.

### ISSUE THREAD

**Issue by zeekhuge** [outline/outline#5664]
The state of the Header sections (Collapsed vs Open) is shared among all the readers.

**To Reproduce**
1. Create a document & open it in edit mode
2. Add following lines :
   - Add `H1` heading `Header 1`
   - Add a line of random text
3. Exit the edit mode
4. Try opening / collapsing the `Header 1` section along with other readers. 

**Observed behavior**
If any of the reader opens up / collapses the `Header 1` section, it opens up / collapses for all other readers.

**Expected behavior**
1. The state in which editor of the document leaves a particular header, should be taken as the default state
2. The open/collapsed state should be temporary for each and every reader and should be independent of other readers.

Solving this might also eliminate the need of `Tabs` as a feature as [mentioned here](https://github.com/outline/outline/discussions/5503) 

**Outline (please complete the following information):**
- Install: self hosted
- Version:  v0.70.2

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 113.0.2

**Comment by zeekhuge** [comment]
Ah, OK. So, is there a small patch that can be applied to a personal build which would disable this feature ? Or is it just too intertwined with the core of Outline ?

**Comment by routerino** [comment]
I would suggest that good UI should never allow for a collective decision about how information is presented.

There needs to be a 'default' of course, but the preference should never be allowed to be overridden.
