### ISSUE TITLE
SIGSEGV error after creating some docs/templates with attachments.

### ISSUE THREAD

**Issue by cairoHy** [outline/outline#5666]
The outline cannot be started after several usage.

**To Reproduce**
1. Deploy the dockers,  modify the configs so the system works well.
2. Create some docs/templates with different attachments, such as .gif, .jpg or .docx.
3. See error image below.

**Expected behavior**
It works well, as it was.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
![image](https://github.com/outline/outline/assets/3580577/26d946f5-7865-46ea-baf7-97d79a03b4d6)
![image](https://github.com/outline/outline/assets/3580577/cdbfbbc6-69ba-4c32-ad6c-d420ac14de03)

**Outline (please complete the following information):**
- Install: [self hosted using docker, storage service is minio docker]
- Version: [The docker image SHA commit  is uploaded via image]

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04.03, Kernel 6.2.0]
 - Browser [chrome]
 - Version [22.04.03]

**Comment by cairoHy** [comment]
![image](https://github.com/outline/outline/assets/3580577/b5284f11-7618-4150-b0c9-e0ec7beb7561)
Sometimes the above error message shows.

**Comment by tommoor** [comment]
This isn't in our code, it's part of the package manager `yarn`. Honestly It looks like the image has gotten corrupted during download somehow as that's a syntax error and this image has been in use without issues for over a month.

**Comment by tommoor** [comment]
Try re-downloading the image.
