### ISSUE TITLE
Add go-to actions to transactional emails

### ISSUE THREAD

**Issue by tommoor** [outline/outline#5671]
It would be nice to have "Open document" and "Open comment" as one-click actions in our notification emails, should be straightforward to add the markup to trigger it wherever we have a CTA in the email itself.

https://developers.google.com/gmail/markup/reference/one-click-action

Could also have this for the login email.

**Comment by apoorv-mishra** [comment]
I believe you meant [_Go-To Action_](https://developers.google.com/gmail/markup/reference/go-to-action) instead of _One-Click Action_?

**Comment by tommoor** [comment]
Ah yep, didn't realize there were two different types here 👍
