### ISSUE TITLE
Copy & Pasting Markdown results in blank page

### ISSUE THREAD

**Issue by jasonquiz** [outline/outline#568]
I am copying some text from one page on my wiki (while in edit mode on that page) and pasting it into a new page (in another chrome window also in edit mode).

When I pasted the content, the whole window goes white, causing all new and previously saved content to disappear. 

When I refreshed the page, the previously saved content reappears, and I am still in edit mode.

![outline wiki - paste glitch](https://user-images.githubusercontent.com/961853/35823460-73665f8c-0a64-11e8-80c8-a684b39374bb.gif)
 
NOTE:  Copy and pasting from the preview version of a wiki page works, but it does not retain the markdown formatting.

---
Mac OS 10.13.2
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by tommoor** [comment]
Almost definitely the same issue as https://github.com/outline/outline/issues/536 – I'll keep this open as potential repro steps though, thanks for the report.

**Comment by tommoor** [comment]
Closing as resolved. Please reopen if you're still able to reproduce.
