### ISSUE TITLE
Upgrade AWS SDK to v3

### ISSUE THREAD

**Issue by tommoor** [outline/outline#5683]
```
[backend] [api] (node:8956) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
[backend] [api]
[backend] [api] Please migrate your code to use AWS SDK for JavaScript (v3).
[backend] [api] For more information, check the migration guide at https://a.co/7PzMCcy
```

**Comment by adityabisht02** [comment]
I believe 2 things need to be done here, 
1. Removing the old aws-sdk v2 package and installing the v3 one
2. Changing the imports in server -> storage -> files-> S3Storage.ts, which can be done with the aws-sdk codemod package (https://www.npmjs.com/package/aws-sdk-js-codemod).
3. Changing the jest mock as well?

**Comment by tommoor** [comment]
That sounds right, there might be a "gotcha" somewhere, perhaps a breaking change – I'm not sure.

**Comment by adityabisht02** [comment]
Yeah, I'll try working on this
