### ISSUE TITLE
Redirect without error message for pages without access

### ISSUE THREAD

**Issue by sorvis** [outline/outline#5690]
When a user who does not have permissions to a collect is sent a link to a document in read-only mode that user is redirected to the last page they viewed. There is not warning and no indication. This is very confusing for end users. 

It appears that pages in edit mode when sent to a person will result in a not found message as would be expected.

**To Reproduce**
1. Got to a page within a collection the other user does not have access to
2. When viewing the page and not in edit mode (or use the share feature) get the URL of the page
3. Open URL with user without access
4. Notice they are directed to the last page they viewed without warning

**Expected behavior**
Users without access should be either told they do not have access or that the page does not exist.

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Firefox

**Comment by tommoor** [comment]
Unfortunately I haven't been able to reproduce this. With a user with viewer permissions navigate to a shared link in a private collection I'm seeing the "Not found" screen.
