### ISSUE TITLE
Toolbar stuck in the bottom left corner

### ISSUE THREAD

**Issue by msklywenn** [outline/outline#5703]
Anytime I select text or click a link, the toolbar that's supposed to be above the text is actually displayed in the bottom left corner. I have no clue why it's there. Other users of our self hosted instance don't have the issue. I'm the administrator.

Did I click on something by mistake that moves it? If so, I can't find where to reset it.

**To Reproduce**
I have absolutely no clue. I just know it happened after upgrading a while back, 0.69.0 I think, I'm not sure. I never bothered checking why since I was the only one affected. It's still a bit annoying though...

**Expected behavior**
The menu toolbar should be above the text.

**Screenshots**
![image](https://github.com/outline/outline/assets/1546678/72005bc4-efc6-420a-b1f6-6e37c3b58374)

**Outline:**
- Install: Self Hosted v0.70.2
- Version: b9fc3015892fa4a59a8d89244d85f0716efce9f9

**Desktop:**
 - OS: both Windows 10 and macOS
 - Browser Firefox
 - Version 116.0.2

**Comment by tommoor** [comment]
Is your computer a touch screen? It seems like the mobile detection is the problem here.

**Comment by msklywenn** [comment]
All windows computers are desktop. The macOS one is a laptop.
I tried using the website once on my iPhone. Would the setting stuck from there? It wasn't a pleasant experience, I completely butchered the page I was working on... I don't think outline liked my SE's 4" screen.

**Comment by tommoor** [comment]
It's not a setting, the bottom floating menu should just be shown on touch-screen devices. I'm adding an additional check for mobile viewport.

**Comment by msklywenn** [comment]
I thought I had tried with different browsers but I may have dreamed that. I don't have the bug with Safari or Edge, only with Firefox. Maybe yet another case of Firefox passing weird settings to websites and getting them confused? There's that funny one where it sends the UTC timezone instead of the real one. I arrived quite early to a meetup once...
