### ISSUE TITLE
Google Maps Embed not accepting iframe code

### ISSUE THREAD

**Issue by lampy255** [outline/outline#5708]
The Google Maps embed feature doesn't seem to accept pasting of an iframe straight from Google Maps.

**To Reproduce**
1. Enter Edit Mode
2. Insert a Google Maps Embed Element
3. Paste a full iframe payload from the share tab of Google Maps
4. Nothing Happens

**Expected behavior**
Expect the iframe parsing logic to extract the src attribute from the iframe and use this as the source for the embed element.  

Note that the embed feature does accept the src url on its own. This requires the user to manually extract the src url from the iframe payload themselves.

**Screenshots**
<img width="814" alt="Screenshot 2023-08-20 at 11 37 12 AM" src="https://github.com/outline/outline/assets/67034721/204caa53-7c83-4078-a346-746b27d4df11">

**Outline 0.71.0:**
- Install: Self Hosted - Docker
- Version: 5e7ea165b4f76552a06f806fa163a1aab77070b4

**Desktop:**
 - OS: OSX Ventura 13.4.1
 - Browser Safari and Chrome

**Comment by lampy255** [comment]
The original Regex in GoogleMaps.tsx in [this commit](https://github.com/outline/outline/pull/5673/commits/bf5e8c587b356552d6022a0dbf041b850e433ea6) was successfully matching and extracting the src from a google maps iframe. With the flexibility of also matching a src url on its own if a user was to provide one.  

Working Regex:
/https:\/\/www\.google\.com\/maps\/embed\?[^"]*/

**Comment by tommoor** [comment]
You can just paste the iframe into the page directly but it should be made to work in this input too

**Comment by lampy255** [comment]
Ok I didn't realise this functionality existed. 
Yes we should allow the user to paste into the embed input

**Comment by tommoor** [comment]
Agreed it would be a good improvement, I'm going to close this for now as it's more of a misunderstanding than a bug – the input does say to paste a URL.
