### ISSUE TITLE
Webhooks cannot have destination in local network

### ISSUE THREAD

**Issue by Floppy012** [outline/outline#5709]
A webhook cannot have its destination on a private IP-Address. Webhooks with a hostname that resolves into an IP-Address of a private network or even with a private IP provided directly will not be triggered, because they are filtered by the `request-filtering-agent` module.

```
request to https://172.29.0.6:1880/hook failed, reason: DNS lookup 172.29.0.6(family:undefined, host:undefined) is not allowed. Because, It is private IP address.
```

Since `request-filtering-agent` is probably used for good reason, it harms installations in private networks. One should be able to disable this security measure to be able to have webhooks call internal APIs. Either by providing an allow-list through a configuration/environment variable or by allowing access to all private IPs (see https://github.com/azu/request-filtering-agent#api)

**To Reproduce**
1. Add a webhook that leads to a private IP
2. Trigger the webhook
3. See error

**Expected behavior**
The webhook should be called.

**Outline (please complete the following information):**
- Install: self hosted
- Version: `docker.getoutline.com/outlinewiki/outline:0.71.0`

**Comment by tommoor** [comment]
Yep, it would be easy enough to have a configuration to disable this security.

**Comment by darionco** [comment]
maybe you should think about reopening this issue, commit 5c07694f6b29e0140a8b1e391fe756b350228a02 reverted the fix

**Comment by tommoor** [comment]
The filtering agent is only used in cloud hosted environment, the fix wasn't reverted.

**Comment by darionco** [comment]
ohhh I see! thank you for the clarification!

**Comment by sircthulhu** [comment]
@tommoor Hi!
It looks as if there's a regression in version 0.87.4 with the same error message and steps.

**Comment by tommoor** [comment]
Hi @sircthulhu , in `0.87.4` you should use the `ALLOWED_PRIVATE_IP_ADDRESSES` environment variable to explicitly set which local IPs can be accessed.

**Comment by sircthulhu** [comment]
@tommoor is it possible to specify ips as subnets? We run outline in k8s, so I'd like to have `ALLOWED_PRIVATE_IP_ADDRESSES: "10.0.0.0/8"`, but it does not work now

**Comment by tommoor** [comment]
Unfortunately not currently, it looks like this is a [feature request](https://github.com/azu/request-filtering-agent/issues/24) in the upstream library.

**Comment by MintyRoma** [comment]
Is there any solution for using webhook apps within the same Docker Compose file? Docker assigns CIDRs dynamically, so I can't whitelist specific container IPs (unless I heavily customize the Compose networking). The problem still reproduces in version 1.0.1

**Comment by jmunoz-neurored** [comment]
> Unfortunately not currently, it looks like this is a [feature request](https://github.com/azu/request-filtering-agent/issues/24) in the upstream library.

Hi @tommoor 
The feature request is recently integrated in the upstream library JFYI
