### ISSUE TITLE
Add local file storage as alternative to S3

### ISSUE THREAD

**Issue by tommoor** [outline/outline#5716]
We've heard time and time again that setting up Minio is the most difficult part of hosting Outline, for many usecases folks will just end up having the files store locally on the same physical hardware after all that effort.

I have refactored the [S3 storage](https://github.com/outline/outline/tree/main/server/storage/files) so that it inherits from a base class that can be easily used to implement a local file storage alternative.

**Comment by tommoor** [comment]
**Some thoughts:**

- This will need new routes for serving the files, I suggest putting _all_ the logic under a new "plugin"
- We will need an environment variable for where to store the files on disk at a minimum
- We will need the ability to generate pre-signed urls for public sharing etc, these can use a JWT
- We can use the existing authentication for uploading files, no need for presigned-post here – just have the `getPresignedPost` method return a url e.g. `/api/files.create`
- If methods in `BaseStorage` need renaming to make sense feel free to do so

**Comment by msklywenn** [comment]
Will there be a way to remove minio and have all the files transferred to local storage?

**Comment by tommoor** [comment]
Yes, _Hopefully_ just a matter of removing the AWS env variables and pointing the app at where your files were stored on disk by Minio. The plan is to retain the same directory structure.

**Comment by Limezy** [comment]
Wow that's a great thing and a big deal for the community. Thanks 🙏

**Comment by tommoor** [comment]
I'm looking for folks to give the pre-release a try before a wider release, **outlinewiki/outline:0.72.0-0** – particularly if you'd like to remove minio.

You must include the following two variables in your environment.

### env
```
FILE_STORAGE=local
FILE_STORAGE_LOCAL_ROOT_DIR=/var/lib/outline/data
```


The local root dir points to a path _inside the docker container_, so you will need to map that to a path on your machine's disk. Either a volume if starting fresh:


### docker-compose
```
    volumes:
      - storage-data:/var/lib/outline/data
```

Or, point it to where where minio currently points, something like:

```
    volumes:
      - /minio/data:/var/lib/outline/data
```

**Comment by tommoor** [comment]
> For some of the old document, images does not load and throws 404, even though file exists at the same path. I'm not able to determine the specific repro, but may be those documents are created in 2021.

If you have an example path that would be useful.

**Comment by herzfeldd** [comment]
I have tested this on a new Outline instance without any issues (adding and removing both images and files). Thanks for implementing this - makes self-hosting quite a bit easier!

**Comment by tommoor** [comment]
@ChetanGoti your missing images should be solved by `v0.72.0-1` – let me know if you get a chance to confirm that.

**Comment by tommoor** [comment]
[Documentation](https://docs.getoutline.com/s/hosting/doc/file-storage-N4M0T6Ypu7)

**Comment by DFY8054** [comment]
Thanks for this awesome feature! I have tried locally on my server, everything went smoothly except uploading large files such as 200MB zip/mp4 file, the speed is pretty slow and finally got 413 error. Not sure it's only me or other folks also met the same issue.

```
files.ts:67     POST https://wiki.fengyud.com/api/files.create 413
```

**Comment by DFY8054** [comment]
Thanks for this awesome feature! I have tried locally on my server, everything went smoothly except uploading large files such as 200MB zip/mp4 file, the speed is pretty slow and finally got 413 error. Not sure it's only me or other folks also met the same issue.

```
files.ts:67     POST https://example.com/api/files.create 413
```

**Comment by DFY8054** [comment]
> @tommoor Thanks for this awesome feature! I have tried locally on my server, everything went smoothly except uploading large files such as 200MB zip/mp4 file, the speed is pretty slow and finally got 413 error. Not sure it's only me or other folks also met the same issue.
> 
> ```
> files.ts:67     POST https://example.com/api/files.create 413
> ```
> 
> FILE_STORAGE_UPLOAD_MAX_SIZE=26843545600 is my upload max size, don't have this issue when using AWS S3 storage

Nvm, seems it's limited by Cloudflare as proxy layer: https://community.cloudflare.com/t/does-the-100-mb-limit-apllies-to-all-users-on-my-website/297261/6

**Comment by nicolinux** [comment]
Tested it with a filesystem folder mount and it works if I set the data directory to the `nodejs` user running inside the container.

Snippet from docker-compose:
```
    volumes:
      - ./data/outline:/var/lib/outline/data
```
`# chown 1001 ./data/outline`


Otherwise I get this:
```
wk-outline_1        | [Error: EACCES: permission denied, mkdir '/var/lib/outline/data/uploads'] {
wk-outline_1        |   errno: -13,
wk-outline_1        |   code: 'EACCES',
wk-outline_1        |   syscall: 'mkdir',
wk-outline_1        |   path: '/var/lib/outline/data/uploads',
wk-outline_1        |   status: 500
wk-outline_1        | }
```

Would it make sense to create `/var/lib/outline/data/uploads` and chown it to `nodejs` in the Dockerfile?
https://github.com/outline/outline/blob/main/Dockerfile

**Comment by tommoor** [comment]
I think we can add a `VOLUME` directive to the Dockerfile and hopefully that will also solve the permissions issue

**Comment by tommoor** [comment]
`v0.72.0-2` (just published) should address the permissions issues

**Comment by tommoor** [comment]
@nicolinux let me know if you're able to confirm on your end

**Comment by nicolinux** [comment]
I have tested it but it doesn't work as expected. The "./data/outline" directory is mounted with root permissions and outline can't create uploads. I looked at the Postgres container which does the same but I can't figure out why it works there.

Here are both service definitions from the `docker-compose.yaml` file (there are no named volumes defined anywhere).

```
  wk-postgres:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_USER: xxx
      POSTGRES_PASSWORD: x
      POSTGRES_DB: outline
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - outlinewiki
  wk-outline:
    image: outlinewiki/outline:0.72.0-2
    command: sh -c "yarn db:migrate --env production-ssl-disabled && yarn start"
    environment:
      - DATABASE_URL=postgres://xxx:x@wk-postgres:5432/outline
      - DATABASE_URL_TEST=postgres://xxx:x@wk-postgres:5432/outline-test
      - REDIS_URL=redis://wk-redis:6379
      - AWS_S3_UPLOAD_BUCKET_NAME=outline-bucket
      - FILE_STORAGE=local
      - FILE_STORAGE_UPLOAD_MAX_SIZE=26214400
    env_file:
      - ./env.outline
      - ./env.oidc
    restart: always
    depends_on:
      - wk-postgres
      - wk-redis
    networks:
      - outlinewiki
    volumes:
      - ./data/outline:/var/lib/outline/data
```

Inside the outline container I see that `outline` has the right permissions (user nodejs - 1001):
```
/var/lib $ ls -la /var/lib/
total 24
drwxr-xr-x    1 root     root          4096 Sep 22 00:47 .
drwxr-xr-x    1 root     root          4096 Aug  7 13:09 ..
drwxr-xr-x    2 root     root          4096 Aug  7 13:09 apk
drwxr-xr-x    2 root     root          4096 Aug  7 13:09 misc
drwxr-xr-x    1 nodejs   nodejs        4096 Sep 22 00:47 outline
drwxr-xr-x    2 root     root          4096 Aug  7 13:09 udhcpd
```

But inside `outline`, `data` has the wrong permissions:
```
/var/lib $ ls -la /var/lib/outline/
total 12
drwxr-xr-x    1 nodejs   nodejs        4096 Sep 22 00:47 .
drwxr-xr-x    1 root     root          4096 Sep 22 00:47 ..
drwxr-xr-x    2 root     root          4096 Sep 23 10:40 data
```

On the host, that's how it looks like:
```
root@myhost:/outline# ls -la data/
total 20
drwxr-xr-x  5 root root 4096 Sep 23 12:40 .
drwxr-xr-x  7 root root 4096 Sep 23 12:40 ..
drwxr-xr-x  2 root root 4096 Sep 23 12:40 outline
drwx------ 19   70 root 4096 Sep 23 12:40 pgdata
```

And that's inside the postgres container, here it looks fine - this should happen in the outline container too:
```
/ # ls -la /var/lib/postgresql/
total 12
drwxr-xr-x    1 postgres postgres      4096 Aug 11 18:49 .
drwxr-xr-x    1 root     root          4096 Aug 11 18:49 ..
drwx------   19 postgres root          4096 Sep 23 10:40 data
```

Looking at the postgres alpine layers, line 13, 14 seems to do the same what you have added to the Dockerfile:
https://hub.docker.com/layers/library/postgres/15.4-alpine3.18/images/sha256-f36c528a2dc8747ea40b4cb8578da69fa75c5063fd6a71dcea3e3b2a6404ff7b?context=explore

**Comment by tommoor** [comment]
Hmmm, it seems fine on the registry.

<img width="686" alt="image" src="https://github.com/outline/outline/assets/380914/8d8ccb59-0daa-44e7-a83e-c8c606c5df74">

**Comment by MartynKeigher** [comment]
Also trying to set this up for local storage, and I just pulled 0.72.0-2 and my permissions are different to yours here on fresh install...

![image](https://github.com/outline/outline/assets/3298134/9cc77080-9aff-4dac-a156-a8eee00271fe)

![image](https://github.com/outline/outline/assets/3298134/cb984e7f-2413-4cba-a85d-f1083cd2ad1a)

Here is my docker-compose file for reference. Been staring at file upload issues now for close to 2 days... it's been a wild ride. 

```
version: "3"
services:

  outline-app:
    image: outlinewiki/outline:${OUTLINE_VERSION}
    restart: unless-stopped
    container_name: outline-app
    command: sh -c "yarn start --env=production-ssl-disabled"
    depends_on:
      outline-db:
        condition: service_healthy
      outline-redis:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@outline-db:5432/${POSTGRES_DB}
      - PGSSLMODE=${PGSSLMODE}
      - REDIS_URL=redis://outline-redis:6379
      - URL=${OUTLINE_URL}
      - PORT=3000
      - FORCE_HTTPS=false
      - FILE_STORAGE=local
      - FILE_STORAGE_UPLOAD_MAX_SIZE=52428800
      - DEBUG=http
      - LOG_LEVEL=info
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_AUTH_URI=${OIDC_AUTH_URI}
      - OIDC_TOKEN_URI=${OIDC_TOKEN_URI}
      - OIDC_USERINFO_URI=${OIDC_USERINFO_URI}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SMTP_REPLY_EMAIL=${SMTP_REPLY_EMAIL}
      - SMTP_TLS_CIPHERS=${SMTP_TLS_CIPHERS}
      - SMTP_SECURE=${SMTP_SECURE}
    networks:
      - outline
    ports:
      - "3020:3000"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/D/outline/uploads:/var/lib/outline/data

  outline-db:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    container_name: outline-db
    security_opt:
      - label:disable
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - outline
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - $PWD/postgres/data:/var/lib/postgresql/data

  outline-redis:
    image: redis
    restart: unless-stopped
    container_name: outline-redis
    networks:
      - outline
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - $PWD/redis/data:/data

networks:
  outline:
    external: false
    ```

Any assistance with this would be immensely appreciated!

**Comment by MartynKeigher** [comment]
Just to add, when i roll back to 0.71.0, (same docker-compose as previous post) the error is different...

![image](https://github.com/outline/outline/assets/3298134/c4cc2d6f-232b-43d1-a341-2a194877b154)

**Comment by tommoor** [comment]
> Been staring at file upload issues now for close to 2 days... it's been a wild ride.

@MartynKeigher this is a brand new feature that isn't even released yet. We're still debugging here 😉

**Comment by MartynKeigher** [comment]
Quick update... 

After a small tweak to my docker-compose file, the files.create route now works!!! I modified the volume on `outline-app` from `- /mnt/D/outline/uploads:/var/lib/outline/data` to `- /mnt/D/outline/uploads:/var/lib/outline`.

![image](https://github.com/outline/outline/assets/3298134/4605055b-1afe-49ef-8697-7c2461bcca1c)

![image](https://github.com/outline/outline/assets/3298134/177b31bd-170b-4e8d-b696-447c2d48442e)


My next Q: The successfully uploaded images do not show up in the local `/mnt/D/outline/uploads` folder. Any idea as to why that may be?

**Comment by nicolinux** [comment]
Oh that's a good idea @MartynKeigher! Tom did the right thing with the permissions, the only problem is when the docker process bind-mounts the directory inside the container, it sets the permissions to the root user. I haven't found out how to change that (if that's possible at all). Also in my case, the `./data/outline` directory on the host is not present at all before the containers spin up. So I assume the docker process creates the directories on the host and then bind-mounts then with root permissions.
The solution to mount the parent directory is pretty good and solves this issue I'd say.

**Comment by tommoor** [comment]
Changing the bind to the parent directory may initially appear to work but your data won't be persisted – because there is nothing at the `/data` location Docker will automatically create an anonymous volume.

You can see this volume using commands like `docker volume ls`.

I'm still looking into if there is a better approach for the file system permissions, but ultimately if you're starting fresh the way to go here is just to use a docker volume and it'll work without any permission troubles.

**Comment by tommoor** [comment]
Based on the postgres image's documentation I have a (last?) build and method to try for those wanting file system mounts.

With build `v0.72.0-3` –

Bind the data directory to your host file system as before, eg.

```
  volumes:
      - ./data/outline:/var/lib/outline/data
```

Set the environment variable `FILE_STORAGE_LOCAL_ROOT_DIR` to a path _within_ the volume. e.g here using "attachments" but anything will do:

```
FILE_STORAGE_LOCAL_ROOT_DIR=/var/lib/outline/data/attachments
```

**Comment by MartynKeigher** [comment]
> Also in my case, the `./data/outline` directory on the host is not present at all before the containers spin up.

I did with it with a mix of both the local dirs existing (with 775, and i even think 777 for one test), just to see if there was any difference, & there was not. 

Will try again now, with `v0.72.0-3` specifying the `FILE_STORAGE_LOCAL_ROOT_DIR` environment value, with a folder that PRE-exists (with 775 permissions) & report back,,,

**Comment by MartynKeigher** [comment]
> Set the environment variable `FILE_STORAGE_LOCAL_ROOT_DIR` to a path _within_ the volume. e.g here using "attachments" but anything will do:

Not having much luck here with ... 0.72.0-3

I have the following options set in the docker-compose.yml:

```
environment:
- FILE_STORAGE=local
- FILE_STORAGE_LOCAL_ROOT_DIR=/var/lib/outline/data/uploads
- FILE_STORAGE_UPLOAD_MAX_SIZE=52428800
volumes: 
- /mnt/D/outline/uploads:/var/lib/outline/data:rw
```

& the error is... 

```
yarn run v1.22.19
$ node ./build/server/index.js --env=production-ssl-disabled
ERR ERR ERR ERR Couldn't create root dir for local storage of attachments | ERR ERR ERR ERR Couldn't create root dir for local storage of attachments | error=EACCES: permission denied, mkdir '/var/lib/outline/data/uploads' ERR ERR ERR ERR Couldn't create root dir for local storage of attachments | ERR ERR ERR ERR Couldn't create root dir for local storage of attachments | error=EACCES: permission denied, mkdir '/var/lib/outline/data/uploads' stack=Error: EACCES: permission denied, mkdir '/var/lib/outline/data/uploads'
    at mkdirSync (node:fs:1398:3)
    at mkdirSync (/opt/outline/node_modules/dd-trace/packages/datadog-instrumentations/src/fs.js:265:57)
    at createRootDirForLocalStorage (/opt/outline/build/plugins/storage/server/utils.js:16:27)
    at Object.<anonymous> (/opt/outline/build/plugins/storage/server/api/files.js:22:41)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Hook.Module.require (/opt/outline/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
    at require (node:internal/modules/cjs/helpers:119:18)
    at /opt/outline/build/server/routes/api/index.js:63:15
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/opt/outline/build/server/routes/api/index.js:61:89)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Hook.Module.require (/opt/outline/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/opt/outline/build/server/services/web.js:19:35)
INF INF INF INF Note: Restricting process count to 1 due to use of collaborative service | INF INF INF INF Note: Restricting process count to 1 due to use of collaborative service | label=lifecycle
```

Inside the container: In your example it was "attachments", I am using "uploads". 
My local machine: `/mnt/D/outline/uploads` already exists, but again I tired with it both existing, and not, and still the same error.

**Comment by nicolinux** [comment]
Same here with 0.72.0-3 and with the same error.

I try to avoid named volumes because I don't want to deal with backups of the named volume in `/var/lib/docker/volumes/<namedvolume>` and rather have all data in the same spot as the postgres db. 

So I think it is fine to leave this issue as is - without any special treatment for the `/var/lib/data/outline` directory inside the container. Those who still want to use bind mounts can just chown the host dir to 1001 (nodejs user inside the container) and the permission issue is solved.

**Comment by MartynKeigher** [comment]
So I change my volume mapping back to what I had when it worked... and it worked again... with `0.72.0-3`.

![image](https://github.com/outline/outline/assets/3298134/54c9d1b2-1121-4f5c-8b46-888225574dd0)

Current volume mapping: `- /mnt/D/outline/uploads:/var/lib/outline:rw`

Still can't see the uploads in the local `- /mnt/D/outline/uploads` though? Very odd.

**Comment by MartynKeigher** [comment]
> Those who still want to use bind mounts can just chown the host dir to 1001 (nodejs user inside the container) and the permission issue is solved.

Mind showing the command you use for that please, @nicolinux? What folder are you referring to what you say 'host dir'? -Thanks.

**Comment by nicolinux** [comment]
> > Those who still want to use bind mounts can just chown the host dir to 1001 (nodejs user inside the container) and the permission issue is solved.
> 
> Mind showing the command you use for that please, @nicolinux? What folder are you referring to what you say 'host dir'? -Thanks.

Whit this in your docker-compose.yaml:
```
  volumes:
      - ./data/outline:/var/lib/outline/data
```

The directory inside the container `/var/lib/outline/data` is the one you bind on the docker host on `./data/outline`, then you can just `chown 1001 ./data/outline` on the docker host and have the right permissions for `/var/lib/outline/data` inside the container.

**Comment by nicolinux** [comment]
@tommoor I asked ChatGPT just for fun and showed it my docker-compose.yaml and also the Dockerfile from Outline. Surprisingly it understood everything and also knew about Postgres's way of changing ownership of the data directory inside the container. Here is ChatGPT's answer and a possible solution. I understand that this is too much to change just for this feature, I am just posting it here for anybody who wants to build their own Docker images and implement this solution even though just chowning the host dir to the user 1001 is way easier :)

----------

The `Dockerfile` you've provided for the `wk-outline` service is well-structured. The key points related to your question about permissions are:

1. The service uses the `node:18-alpine` base image for the `runner` stage.
2. A group and user `nodejs` with UID `1001` are being created.
3. Several directories and files, including `/var/lib/outline`, are owned by `nodejs`.
4. The directory `/var/lib/outline/data` is explicitly created, owned by `nodejs`, and made sticky with the permissions set to `1777`.

Given this setup, if `/var/lib/outline/data` is empty and isn't bind-mounted from the host, the permissions would be set as expected, and the `nodejs` user would be able to write to it.

However, when you bind-mount a host directory (e.g., `./data/outline`) to this path, you effectively override these container-side settings with the host's directory settings.

You've mentioned that PostgreSQL manages to adjust the permissions of its bind-mounted data directory. It does this during container runtime, not during image build time. The PostgreSQL container's entry script checks if the data directory is empty, sets the required permissions, and initializes the data.

To mimic this behavior in your `wk-outline` service, you'll need to:

1. **Introduce an entry script**: Create an entry script (`entry.sh` or similar) that:
    - Checks if `/var/lib/outline/data` is empty.
    - Adjusts permissions if necessary.
    - Calls the main application command.

2. **Adjust the `Dockerfile`**:
    - Copy the entry script into the image.
    - Change the `CMD` directive to call this script.

3. **Modify the script**: The script might look something like:

```bash
#!/bin/sh

# Check if directory is empty
if [ -z "$(ls -A /var/lib/outline/data)" ]; then
    chown -R nodejs:nodejs /var/lib/outline/data
fi

exec "$@"
```

Make sure the script has execution permissions (`chmod +x entry.sh`), and remember to copy it into the Docker image during the build.

4. **Update `docker-compose.yaml`** to reflect this change, ensuring the entry script is the first command that runs when the container starts.

This way, even if Docker creates the `./data/outline` directory on the host with root ownership, the entry script will adjust the permissions inside the container when it starts, ensuring the `nodejs` user can write to it.

**Comment by tommoor** [comment]
https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh#L39-L41

Hah, not bad. This seems to be the logic in question

**Comment by jannschu** [comment]
Today I migrated my instance from minio to local file storage. I ran into these two issues:

- Just copying the data directory from minio did not work: Some files in the bucket were not stored as a file system file but in a `xl.meta` file, maybe because I used a versioned bucket. I resolved that by first copying the bucket inside the minio container using the minio [mc cp](https://min.io/docs/minio/linux/reference/minio-mc/mc-cp.html) command (which I also installed as described on that page) by running `mc cp --recursive local/outline outline-dump`. After the bucket was copied I could proceed.
- The users' `avatarUrl` was not correct. It I updated the `useres` PostgreSQL table by hand and changed the URLs from `https://miniio.example.com/outline/public/…` to `/api/files.get?key=public/…`. Also the wiki's/team's logo URL had to be updated like that, more precisely the `preferences` JSONB of the `teams` table. Can also be done from the interface be reuploadin the logo of course.

Maybe that helps someone with their migration, thanks a lot for this feature! :-)

**Comment by mikew** [comment]
IMO this should be done in an entrypoint in the container, but luckily it's possible to do downstream. I've solved it with:

- Running the container as root
- Writing an entrypoint that does the `chmod`
- Finally runs `yarn start` as the `nodejs` user

An example `docker-compose.yml`:

```yaml
services:
  outline:
    image: outlinewiki/outline:latest

    # Hack to get outline to just set the right permissions for its data
    # directory on startup.
    user: root
    entrypoint: /entrypoint

    environment:
      - FILE_STORAGE=local
    volumes:
      - ./persistent/outline:/var/lib/outline/data
      - ./data/entrypoint:/entrypoint
```

and the `entrypoint`:

```sh
#!/usr/bin/env sh
set -e

mkdir -p "$FILE_STORAGE_LOCAL_ROOT_DIR"
chown -R nodejs:nodejs "$FILE_STORAGE_LOCAL_ROOT_DIR"
chmod 1777 "$FILE_STORAGE_LOCAL_ROOT_DIR"

if [ -z "$1" ]; then
  su -s /bin/sh -c "yarn start" nodejs
else
  su -s /bin/sh -c "$*" nodejs
fi
```
