### ISSUE TITLE
App does not work with Cloudflare Rocket Loader

### ISSUE THREAD

**Issue by WarlockFish** [outline/outline#5718]
I have upgraded to version 0.71.0, but the page cannot load at all (page is empty), and following error is reported in the console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'DEPLOYMENT')
    at Modal-2135aae8.js:1:114666
```

Clearing the browser cache or CDN cache doesn't help. Falling back to version 0.70.2 can solve the problem. Has anyone encountered a similar problem?

I deploy Outline using Docker, with Cloudflare Tunnel as a reverse proxy, and access it using Google Chrome (version 115.0.5790.173).

_Originally posted by @cmj2002 in https://github.com/outline/outline/discussions/5701#discussioncomment-6773475_

**Comment by WarlockFish** [comment]
I also encountered this problem 

outline log
```
outline           | {"label":"http","level":"info","message":"  <-- POST /api/auth.info"}
outline           | {"label":"http","level":"info","message":"  xxx POST /api/auth.info 401 10ms -"}
outline           | {"label":"http","level":"info","message":"  <-- GET /"}
outline           | {"label":"http","level":"info","message":"  --> GET / 200 26ms 1.61kb"}
outline           | {"label":"http","level":"info","message":"  <-- POST /api/auth.info"}
outline           | {"label":"http","level":"info","message":"  xxx POST /api/auth.info 401 8ms -"}
outline           | {"label":"http","level":"info","message":"  <-- GET /"}
outline           | {"label":"http","level":"info","message":"  --> GET / 200 19ms 1.61kb"}
outline           | {"label":"http","level":"info","message":"  <-- POST /api/auth.info"}
outline           | {"label":"http","level":"info","message":"  xxx POST /api/auth.info 401 3ms -"}
outline           | {"label":"http","level":"info","message":"  <-- GET /"}
outline           | {"label":"http","level":"info","message":"  --> GET / 200 18ms 1.61kb"}
outline           | {"label":"http","level":"info","message":"  <-- POST /api/auth.info"}
outline           | {"label":"http","level":"info","message":"  xxx POST /api/auth.info 401 1ms -"}
outline           | {"label":"http","level":"info","message":"  <-- GET /"}
outline           | {"label":"http","level":"info","message":"  --> GET / 200 18ms 1.61kb"}
outline           | {"label":"http","level":"info","message":"  <-- POST /api/auth.info"}
outline           | {"label":"http","level":"info","message":"  xxx POST /api/auth.info 401 3ms -"}
```

browser log
```
10:23:38.913 Uncaught TypeError: undefined has no properties
    <anonymous> https://XXX/static/assets/Modal-2135aae8.js:1
Modal-2135aae8.js:1:114652
    <anonymous> https://XXX/static/assets/Modal-2135aae8.js:1

```

**Comment by taoya7** [comment]
清空一下user_authentications表 试试。

**Comment by MrTheFirst** [comment]
Also faced this problem. I use Docker in conjunction with minio and Keycloak. Even public pages that do not require authorization do not work. Went back to the previous build.

**Comment by tommoor** [comment]
Please post the contents of the HTML file when you load the page.

**Comment by MrTheFirst** [comment]
Browser errors (incognito tab without auth)
![2023-08-21_14-39-55](https://github.com/outline/outline/assets/4955590/dbe7e4db-04f7-441a-a6de-cf7f836c90dc)

[view-source.txt](https://github.com/outline/outline/files/12395550/view-source.txt)

**Comment by cmj2002** [comment]
> This is likely related to our introduction of server-generated nonce for all scripts in `0.71.0`, the app will no longer execute scripts that are injected into the page without the correct nonce or scripts that were modified by eg Cloudflare.
> 
> It looks like that's what's happening here, the script tags are modified and/or the nonce is missing from the response headers. I'd suggest you disable Cloudflare features until you find the culprit.

It works for me. It is an issue caused by Cloudflare Rocket Loader. [Its documentation](https://developers.cloudflare.com/speed/optimization/content/rocket-loader/) states:

> Rocket Loader prioritizes your website’s content (text, images, fonts, and more) by deferring the loading of all of your JavaScript until after rendering.
> 
> This type of loading (known as asynchronous loading) leads to earlier rendering of your page content. Rocket Loader handles both inline and external scripts, while maintaining order of execution.

So, Rocket Loader does indeed modify script tags. You can [disable this feature for the whole site](https://developers.cloudflare.com/speed/optimization/content/rocket-loader/enable/), or use a [Configuration Rule](https://developers.cloudflare.com/rules/configuration-rules/) to disable it on a specific hostname.

**Comment by tommoor** [comment]
Sounds good, it should be disabled – Outline already uses best practices regarding script loading so rocket loader isn't necessary anyway.

**Comment by MrTheFirst** [comment]
My Rocket Loader was not enabled and there is an error.

**Comment by tommoor** [comment]
@MrTheFirst it's enabled – it's right there in your screenshot and posted source

**Comment by MrTheFirst** [comment]
@tommoor Oh, I'm sorry .. really, I looked at the settings of a certain domain. Thank you!

**Comment by tommoor** [comment]
☝️ The next release will have a specific error for this case with a pointer to relevant documentation. Ironically(?) this is proving that the new security features are working correctly as they are there to prevent third-party tampering and execution of arbitrary scripts.
