### ISSUE TITLE
Pdf export issue

### ISSUE THREAD

**Issue by thumDer** [outline/outline#5720]
The exported pdf has problems, when a bullet list spans over a page break, as it is visible on the attached screenshot

**Screenshots**
![kép](https://github.com/outline/outline/assets/54556708/a549fa87-7850-489d-98db-1562fb9f056d)

**Outline (please complete the following information):**
- Install: getoutline.com

**Comment by tommoor** [comment]
Is this also reproducible when using Print -> Save as PDF in the browser?

**Comment by thumDer** [comment]
Nope, there is no such problem that way.
