### ISSUE TITLE
Slack CSRF

### ISSUE THREAD

**Issue by ccorcos** [outline/outline#575]
I think you want to assert that the slack state is equal to the cookie state.

https://github.com/outline/outline/blob/master/server/api/auth.js#L23

**Comment by tommoor** [comment]
Hey @ccorcos! The state is an optional parameter but we DO verify it on the client-side here:
https://github.com/outline/outline/blob/883e584da210588d116cbfd7ee03ba3fd8aa1718/app/stores/AuthStore.js#L69-L76

From my understanding of the `state` parameter and how it protects against XSRF I believe that checking this client side is enough, however If you think otherwise please point us in the right direction - happy to fix up.

**Comment by ccorcos** [comment]
Oh interesting. Well lets think about it... 

Is there some way we can get a user to issue that post request with another code?

Suppose someone started slack auth and got the code from the redirect. They could create a form on a phishing website that submits a form with that code when you click a button.

https://github.com/outline/outline/blob/883e584da210588d116cbfd7ee03ba3fd8aa1718/app/stores/AuthStore.js#L80

As a result, the user will be logged in to another account. I think that checks out.

If you checked the cookie equal to the state on the server, then you're ensuring that the browser that made a request for the code is the same as the one posting the message to login with that code.

You can construct an even more secure version as well that is tolerant of XSS as well -- the client can ask the server to construct the auth url, the server can lay a secure cookie (one that you can't read or edit from the client) using `res.cookie(key, value, {secure: true})`. Upon the redirect, the client passes the state to the server and the server ensures that the state matches the secure cookie. If the cookie isn't secure, then client XSS could just read the cookie and send the code with that state.

**Comment by tommoor** [comment]
The `code` is temporary and must be exchanged for an access token in seconds, you couldn't reasonably hardcode it into another website and if you could the only thing you'd be achieving is logging someone else into your account? While an interesting proposition this isn't what we're protecting against here.

The purpose of the state parameter is to check that when the redirect response from Slack is received it matches the request we made and is not made in an iframe or something else without the users knowledge. The actual post request to the API is kind of irrelevant as it's useless without a valid code.

Having said that I think you're right that checking the cookie on the server would be an inherently better solution. 😉

**Comment by ccorcos** [comment]
You wouldn't have to hard code it into a another website -- you can have a script run through the login flow to generate a new code. 

Its not an attack gaining access to someone else's account, its a phishing attack. I admit its pretty weird, but if I'm able to log you into my account even though you think its your account, then I can collect confidential information from you.

I'm only saying all of this because I've been in your position when a security auditor brought it to my attention.

**Comment by tommoor** [comment]
Although this has been closed I'm working on some improvements alongside the post-to-slack functionality that I think will end up making this a non-issue :)
