### ISSUE TITLE
Error when saving a page

### ISSUE THREAD

**Issue by jasonquiz** [outline/outline#576]
Currently I am getting an error every time I try to save an edit to a page.

I get a chrome dialog that says "You  have unsaved changes. Are you sure you want to discard them?"

Outline shows the following errors in oranges

- Failed to load documents
- Error while deleting the document
- Document failed saving
- Document failed to record view

I say "Ok". Most of the changes I made are saved, but the main chrome error shows every time I try to save an edit.

---
Additional context. 
I created a child page, saved, got the chrome error, clicked ok and it seemed to save but then three copies of the page showed up as pages rather than child pages. 
I tried to delete one of the copies. The delete page did nothing after clicking delete. Clicked delete a couple of times, then refreshed the page. One of the duplicate pages were gone. I tried repeating for the other two, but nothing happened, just more of the orange errors listed above.

![screenshot 2018-02-07 11 04 21](https://user-images.githubusercontent.com/961853/35936440-23c59426-0bf8-11e8-8091-3cbd2696c44d.png)
![screenshot 2018-02-07 11 05 45](https://user-images.githubusercontent.com/961853/35936443-25acfb6c-0bf8-11e8-935e-aa29b2308a3b.png)

**Comment by jorilallo** [comment]
@jasonquiz Really sorry about that. It seems that our Redis instance ran out of space and we weren't alerted about it. We upgraded our hardware and will work on better monitoring
