### ISSUE TITLE
Missing sidebar contents in Safari

### ISSUE THREAD

**Issue by lampy255** [outline/outline#5765]
Right hand Sidebar contents fails to appear, or appears only partially in Safari.
Sometimes the sidebar animates out, but has no contents at all.

**To Reproduce**
1. View an Outline page in Safari
2. Trigger the sidebar in any way eg: click history

**Expected behavior**
The sidebar appears from the right hand side with all of its contents.

**Screenshots**
<img width="1840" alt="SideBarBug" src="https://github.com/outline/outline/assets/67034721/283ab1b1-5dd2-47cc-852f-eaf3580c836b">

**Outline:**
- Install: Self Hosted
- Version: 5e7ea165b4f76552a06f806fa163a1aab77070b4

**Desktop:**
 - OS: OSX Ventura 13.4.1
 - Browser Safari 
 - Version 16.5.1

**Comment by tommoor** [comment]
Yea this has been a Safari bug for a while, weird one - it works fine in all other browsers 🤷‍♂️

**Comment by lampy255** [comment]
I see framer-motion is used for sidebar animations and is quite far behind? Looks like they are up to 10.16.2
