### ISSUE TITLE
Slack App does not display help text after first display

### ISSUE THREAD

**Issue by MaxValue** [outline/outline#5768]
When the user has already viewed the help once, the Slack app refuses to show the help text again.

**To Reproduce**
1. Install the Slack App
2. Ensure to have viewed the help text for the `/outline` command.
3. Type `/outline help` or even just `/outline`.
4. See error:
```
How to use /outline

To search your knowledgebase use /outline keyword.
You’ve already learned how to get help with /outline help.
```

**Expected behavior**
The help should always be available. That is what a help function is for.

**Screenshots**
-

**Outline (please complete the following information):**
- Install: getoutline.com
- Version: -

**Desktop (please complete the following information):**
 - OS: -
 - Browser -
 - Version -

**Mobile (please complete the following information):**
 - Device: -
 - OS: -
 - Browser -

**Comment by tommoor** [comment]
It's not an error, just perhaps badly worded copy – there are only two commands search and help, so it's kind of saying that you've already done the second one.

**Comment by MaxValue** [comment]
Maybe do it like the help text of common *nix tools:
```
Type /outline help to display this help text.
```
