### ISSUE TITLE
The Tldraw (beta) embed does not work

### ISSUE THREAD

**Issue by MaxValue** [outline/outline#5769]
When trying to embed a Tldraw share link into an Outline page, nothing happens.

**To Reproduce**
1. Edit an Outline page
2. Start typing `/tld` and select the "Tldraw (beta)" embed feature.
3. Paste your Tldraw search link (e.g. https://www.tldraw.com/r/ZIPDerHMxt4Wq0vEHrkab?viewport=0%2C0%2C1440%2C790&page=page%3AivpBcBV-2NsHMi7AIQgEU)
4. Other embed types would display the embedded content by now, but with this embed type does nothing at all. No message in the console.

**Expected behavior**
An embed frame should appear showing the content of the Tldraw page (in the example it should show "If you can see this, the Outline tldraw embed works!")

**Screenshots**
-

**Outline (please complete the following information):**
- Install: getoutline.com
- Version: -

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Mozilla Firefox (117), Google Chrome (116.0.5845.96) and Outline Desktop (1.1.0)
 - Version -

**Mobile (please complete the following information):**
 - Device: not tested
 - OS: not tested
 - Browser not tested

**Comment by tommoor** [comment]
Previously embedding only worked on `beta.tldraw.com` due to a restriction on their side, it seems that might have been resolved and we can now support the main domain
