### ISSUE TITLE
Peek popups stopped working

### ISSUE THREAD

**Issue by thumDer** [outline/outline#5781]
Previously hovering over an internal link a short peek of the target document was visible in the popup. Now it shows the same generic outline content for all links:

![kép](https://github.com/outline/outline/assets/54556708/e84ab60f-345c-4107-ab80-c8a494a3992a)

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Firefox
 - Version 117.0

**Comment by tommoor** [comment]
Looks like this was broken for custom domains, thanks for the heads up!
