### ISSUE TITLE
Publish shortcut not working on Gnome Firefox

### ISSUE THREAD

**Issue by iexos** [outline/outline#5794]
The shortcut for publish opens new private window on Firefox instead.

**To Reproduce**
1. Create new page
2. Write smth
3. Press `ctrl`+`shift`+`p`
5. Firefox opens a new private window

**Expected behavior**
I expect the document to publish. (Technically, I expect Firefox to intercept that specific shortcut, but I would like one for publishing that works :smile:)

**Outline:**
- Install: self hosted
- Version: 70.2

**Desktop:**
 - OS: Arch Linux, Gnome 44.4
 - Browser: Current Firefox

Maybe `shift`+`enter`?

**Comment by tommoor** [comment]
Ideally it's something that isn't valid text input, shift+enter is used several places in the editor. Probably need to switch to `ctrl+alt+p`

**Comment by iexos** [comment]
still an issue

**Comment by iexos** [comment]
> still an issue

.

**Comment by Ulytas** [comment]
Same issue on Chrome (PWA too) and Firefox afaik. Also tried Ctrl+Enter: the Publish button get highlighted for a second but that's it.
I think it's been around for a while (#1745), you can try a macro. 
Excalidraw don't have this issue for example. idk how though
