### ISSUE TITLE
Error on viewing history

### ISSUE THREAD

**Issue by thumDer** [outline/outline#5795]
For most of our docs it is not possible to view any previous versions from history.
The following error message is shown:

![kép](https://github.com/outline/outline/assets/54556708/c9f7dec7-a4c7-4776-81ea-561bd5f9bc51)

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Firefox
 - Version 117.0

**Comment by tommoor** [comment]
Hmm, this was fixed several days ago. It persists through a reload?

**Comment by thumDer** [comment]
Yep, even after `Ctrl F5`

**Comment by tommoor** [comment]
It seems as though an older commit was accidentally deployed, the issue is resolved now
