### ISSUE TITLE
Deleted page still showing up in collection

### ISSUE THREAD

**Issue by jasonquiz** [outline/outline#581]
I have a page that I deleted, but it is still showing up in my Collection. When I open that collection I get an orange error saying "Failed to load document". I then click on the page (I previously deleted) and it takes me to the "Page not found" screen (and closes the Collection).

**Comment by tommoor** [comment]
I wonder if this is related to this error we saw on the server… https://github.com/outline/outline/issues/574

**Comment by jasonquiz** [comment]
@jorilallo no problem. Emailing it over now.

**Comment by jorilallo** [comment]
This is most likely due redis or backend bugs that we fixed. Closing after addressing the case individually
