### ISSUE TITLE
Embedded new search doesn't search in Mermaid diagrams

### ISSUE THREAD

**Issue by chimit** [outline/outline#5812]
The new document search function doesn't search in Mermaid diagrams:

<img width="441" alt="image" src="https://github.com/outline/outline/assets/839349/0cc8b653-bc93-4055-8f55-37b1ffc4a2e0">

Also, this search panel is not closed when you click Esc which is very annoying when you are in macOS fullscreen mode because the browser quits the fullscreen mode instead of closing the search window.

**To Reproduce**
1. Go to any document with Mermaid diagrams
2. Click on Ctrl/Cmd+F
3. Type any word from a diagram on the page
4. No results found

**Expected behavior**
The found text should be found and highlighted in the diagram.

**Outline (please complete the following information):**
- Install: self-hosted
- Version: v0.71.0

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 16.6 (18615.3.12.11.2)

**Comment by tommoor** [comment]
The mermaid diagram rendering is entirely controlled by Mermaid so I’m not sure it’ll be possible to highlight results there

**Comment by chimit** [comment]
The browser native search could search in Mermaid diagrams but it can't be used anymore. Is there any way to disable this new "embedded" search function?

**Comment by tommoor** [comment]
Just use the keyboard shortcut twice or access the native search from the browser menu, either works

**Comment by chimit** [comment]
Thanks! But what about the Escape button behavior? Should I create a separate ticket for that?

**Comment by tommoor** [comment]
I'm afraid I can't reproduce that issue, there is an Escape key binding and it's working in my testing 🤔 

Perhaps a video might make the issue more apparant?

**Comment by chimit** [comment]
Here is what it looks like. At the end of the video, I press Esc to close the search window. Instead, the browser quits the fullscreen mode.

https://github.com/outline/outline/assets/839349/97b4d860-1e7f-4fea-a8f3-09859e3bac3b

**Comment by tommoor** [comment]
Ah, it's a Safari-specific thing. ok
