### ISSUE TITLE
Update server-side model import syntax

### ISSUE THREAD

**Issue by apoorv-mishra** [outline/outline#5868]
Better to change model's import style from, say `import CollectionGroup from "./CollectionGroup";` to `import { CollectionGroup } from "@server/models";` everywhere. Reason being that in the former, the compiler doesn't err if the _model name is changed_ while in the latter it does. Screenshots :point_down: 

![Screenshot from 2023-09-22 15-24-58](https://github.com/outline/outline/assets/15694566/6a518880-c11d-4176-83cb-9f76937fe62e)
vs
![Screenshot from 2023-09-22 15-25-39](https://github.com/outline/outline/assets/15694566/b21cfac1-2d1b-45e9-a59e-9ca8c4145e24)

**Comment by tommoor** [comment]
I suppose this is a good argument to start moving away from default exports generally

**Comment by apoorv-mishra** [comment]
Generally, yes. Case where default exports might come up as convenient - dynamic imports, like :point_down: 
```js
  filePaths.forEach((filePath: string) => {
    const pkg = require(path.join(process.cwd(), filePath)).default;

    // do something with pkg
  });
```
Although this too can be circumvented by naming all exports with the same name but that may be an unjustified restriction in a number of scenarios, would be better to mark those as default instead.
