### ISSUE TITLE
Add ability to list all comments via API endpoint

### ISSUE THREAD

**Issue by tommoor** [outline/outline#5871]
### Discussed in https://github.com/outline/outline/discussions/5870

<div type='discussions-op-text'>

<sup>Originally posted by **Shaddix** September 22, 2023</sup>
Other good option would be to have an API to retrieve all comments (currently I get the `"message": "documentId: Required"` when requesting `/api/comments.list` without `documentId`.</div>

**Comment by mukul018** [comment]
I can work on it. 
Please assign it to me.

**Comment by Pranav2612000** [comment]
Hey @tommoor Can I pick up this issue next?

**Comment by tommoor** [comment]
Noone else is working on it, the only gotcha is that comments do not include a `teamId` so the join through documents must be used.
