### ISSUE TITLE
LaTeX Equation Rendering Compatibility Issue

### ISSUE THREAD

**Issue by gtavasoli** [outline/outline#5896]
**Description:**
I am encountering an issue with LaTeX equation rendering in my self-hosted Outline wiki. While LaTeX equations are rendering correctly in other platforms like Notion, they do not render as expected within Outline. I would like to report this issue and seek assistance in resolving it.

LaTeX equation `\sigma = \sqrt{\frac{1}{n} \sum_{i=1}^{n}(x_i - \mu)^2}`.

**Expected Behavior:**
The LaTeX equation should render correctly within the document.
![image](https://github.com/outline/outline/assets/1962630/a3f02fd8-fa16-46cb-aa3b-26dacd822c9b)

**Actual Behavior:**
The LaTeX equation does not render as expected and appears.
![image](https://github.com/outline/outline/assets/1962630/9837b894-609e-4cca-9057-68579e0f9ffc)

I would appreciate any guidance or assistance in resolving this compatibility issue. Thank you!

**Comment by tommoor** [comment]
It is rendering correctly here
<img width="282" alt="image" src="https://github.com/outline/outline/assets/380914/1bd802cb-915f-4255-857b-eb03168b9969">

Please follow the bug template, what version of the software are you running?

**Comment by gtavasoli** [comment]
Latest version: [v0.71.0](https://github.com/outline/outline/releases/tag/v0.71.0)

Interestingly, it is now working perfectly. I'm not sure why I encountered issues before.

I apologize for bothering you. 😥

![image](https://github.com/outline/outline/assets/1962630/f24dec0b-f2f3-4ea6-8f9e-b9957e10729a)
