### ISSUE TITLE
Retrieve public image URI's through API

### ISSUE THREAD

**Issue by Nico-L** [outline/outline#5901]
Hello, 

I am planning to use Outline as knowledge base and as source for blog post as well together with some static site builder (astro.build).
When querying the page content with images with the api, the image urls are not usable and images won't be rendered, a 401 error is showing. The issue is similar to https://github.com/outline/outline/issues/5293 but for the api

**To Reproduce**
1. Make a page
2. add an image
3. query the page through the api
4. getting image link as ![](/api/attachments.redirect?id=$GUID)
5. concat domain name to the images links
6. parse the markdown (I used marked)
7. the resulting web page shows a 401 error

**Expected behavior**
a URL usable for an img tag 

**Outline:**
- Install: self-host
- Version: 0.72.0-2 with local storage

Thanks

**Comment by tommoor** [comment]
This is expected behavior, images are private and require authentication to load.

In order to get a public URL for the image you can create a share for the document, publish it, and then use the `shareId` to load the document from the API. You'll then receive signed image urls in the response.

Unfortunately creating a share and publishing it are [separate API calls](https://www.getoutline.com/developers#tag/Shares/paths/~1shares.create/post) right now, but we should allow creating a published share in one step, it was just never needed by the UI previously.

**Comment by Nico-L** [comment]
Thanks @tommoor,

If I understand correctly, to publish documents on a web site I have to make 3 API calls:
* create a share (api/shares.create) -> the response id is the shareId
* publish the share shareId, with "published: true" in the payload
* retrieve the document shareId

Is that correct? My issue here is that the "text" key of the retrieved document data has still the protected link to the images and I have still an  error when I am trying to parse it. I don't see any other url I can use to replace the image url to an authorized one.

What am I doing wrong?

Thanks

**Comment by tommoor** [comment]
If you retrieve the document from the API using the `shareId` and _no other authorization_ it will give you signed public urls in the response. Sorry this isn't more ergonomic, but this usecase wasn't really considered so far.

**Comment by Nico-L** [comment]
Ha yes, I kept the authorization in my final api call. Removing it allows to render the images indeed. This may be non optimal from an ergonomic point of view but I don't bother since I am using a static site generator and these api calls are performed at build time.

Thanks! Outline may weel be the tool I need for non technical people to enter blog notes and basic web site management.

**Comment by tommoor** [comment]
See the linked PR – next release you will only need one API call to create the published share.
