### ISSUE TITLE
Deployment using Docker

### ISSUE THREAD

**Issue by manypozo** [outline/outline#591]
Hi ! Very nice work guys. Congratulations

First time here using Slack Apps. Sorry if this issue is due to my neaby experience.

I am trying to deploy __outline__ using docker but I am having a few issues with the sign-in:
```
OAuth Error: redirect_uri did not match any configured URIs.

Passed URI : http://localhost:3000/auth/slack
Allowed URI : none specified
```

I am actually not quite sure of having inserted the correct environment variables.
I do have set `SLACK_KEY` with my app `client_id` and `SLACK_SECRET` with my app `client_secret`. Also, I had this issue while running the docker 
```
outline_1   | Please set SECRET_KEY env variable with output of `openssl rand -hex 32`
outline_1   | [nodemon] app crashed - waiting for file changes before starting...
```
so I assumed the existing secret key was not valid and I created a new one as suggested and replaced it in `SECRET_KEY`. 

No more modifications performed so far.  Do I need to set-up a `OAuth Access Token` ?

My final goal is to deploy it into `kubernetes` and a personal S3. Of course I would contribute by giving you my insights and kubernetes manifests. 

Thank you very much !

**Comment by tommoor** [comment]
Hey @manypozo unfortunately we can't really provide support on github. However ensure that all of the env variables in the sample file are provided in your environment:

https://github.com/outline/outline/blob/master/.env.sample

You'll also need to make sure the Slack app is setup correctly on their side (eg specifying allowed redirect_uris etc). If you find ways that the documentation could be improved we'd be more than happy to accept a pull request for that.

**Comment by locomot1f** [comment]
I second the need for more clarification in the documentation.
I've recently ventured to host my own outline server.
and all i'm getting is:
`Authentication failed - we were unable to sign you in at this time. Please try again.`
