### ISSUE TITLE
does not delete files locally

### ISSUE THREAD

**Issue by dwightskrute** [outline/outline#5912]
I have completed the installation and configuration for local storage.

For now everything is working correctly.

But I have verified that when it comes to deleting documents with images, or attached files, they continue to remain stored in the directory that I have configured.

**Comment by tommoor** [comment]
Have the documents been permanently deleted from the trash? Are you sure the images aren't referenced in other documents?

**Comment by dwightskrute** [comment]
Sorry for the error, I had a problem with the permissions of the linked directory.
 It's fixed now.
 Great work
