### ISSUE TITLE
Translation not applied (or missing ?) in Account > Preferences

### ISSUE THREAD

**Issue by alkanna** [outline/outline#5924]
**To Reproduce**
1. Go to Account > Preferences
2. Change language from English to something else (French for example) back and forth
3. Notice that the "Behavior" section is not translated properly

**Expected behavior**
The behavior section should update according to the selected language

**Screenshots**
![CleanShot 2023-10-03 at 12 13 42](https://github.com/outline/outline/assets/30343764/1f60dda7-b56f-4d5e-945b-d890311bf85b)

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.72.0

**Comment by tommoor** [comment]
It's not unusual for translations to be missing, very few languages are 100% translated – but the hanging of a previous language other than English when switching here is weird.

**Comment by tommoor** [comment]
I haven't been able to reproduce this behavior testing in local development or production cloud I'm afraid, not sure what's going on here.

**Comment by alkanna** [comment]
I am in france and am using a browser in english, could that be the cause ?
Is there anything I can check in the localStorage maybe ?

**Comment by alkanna** [comment]
I saw that in the `en_US.json` file (in the network tab of the brwser) the entry for the "When enabled, documents have a separate editing mode..." translation is actually missing :

![CleanShot 2023-10-04 at 09 24 06](https://github.com/outline/outline/assets/30343764/d78b6aa3-e50e-48d0-9ebd-1aa8608481c6)

However it is present and with the proper translation in the `fr_FR.json` file...

![CleanShot 2023-10-04 at 09 25 49](https://github.com/outline/outline/assets/30343764/dbffdf25-ed80-4075-b277-0d515d7c9dc7)

**Comment by tommoor** [comment]
> the entry for the "When enabled, documents have a separate editing mode..." translation is actually missing :

It's there

https://github.com/outline/outline/blob/main/shared/i18n/locales/en_US/translation.json#L846

**Comment by tommoor** [comment]
So, I'm 99% sure this is because locale files include 7 day cache headers – the caching needs fixing here to redownload in a new release.
