### ISSUE TITLE
Differentiate which comments have a selection vs are on document

### ISSUE THREAD

**Issue by tommoor** [outline/outline#5927]
Currently, I can be a bit confusing when looking at the list of comments to figure out which comments have associated text, selected and which don't. It may appear broken if the user doesn't know that some comments can have no selection.

**Comment by sharathpuranik** [comment]
This is done really well in Google docs where parts of the docs are highlighted for which the comments are relevant...

**Comment by tommoor** [comment]
closed by 47c13c991654bbd7e8708e85301c38f663d19684
