### ISSUE TITLE
Full width images don't resize correctly with sidebar events

### ISSUE THREAD

**Issue by lampy255** [outline/outline#5929]
**To Reproduce**
1. View any document with a full width image
2. Show/Hide the left sidebar with (cmd + .) or Show/Hide the right sidebar by opening comments or history.
3. Observe that the image shifts horizontally, leaving a large amount of white space

**Expected behavior**
Expect the full width image to grow/shrink in a similar manner to the rest of the document body

**Screenshots**
Before:
<img width="1707" alt="Before" src="https://github.com/outline/outline/assets/67034721/53459e9e-ad2d-4950-be0e-fc740ae07d3d">

After Collapse Left Sidebar:
<img width="1707" alt="AfterLeftSidebar" src="https://github.com/outline/outline/assets/67034721/c6978e8d-3c36-44f6-9628-84fe9e58fa3b">

After Show Right Sidebar:
<img width="1707" alt="AfterRightSidebar" src="https://github.com/outline/outline/assets/67034721/23508b2b-fb21-47ad-abe1-63939b95a719">

**Outline:**
- Install: self hosted
- Version: 4d2a5ae7485573564e971873269eaaf78ef760e2

**Desktop:**
 - OS: OSX Sonoma 14.0
 - Browser Chrome and Safari

**Comment by tommoor** [comment]
This was a bug in 0.71.0 and below, but it should have been fixed in 0.72.0 – the available width is now measured, not sure how to reproduce yet – this is in Brave (chromium)…

https://github.com/outline/outline/assets/380914/2f232c9b-6672-4925-bb6f-04aaa62e0b71

**Comment by lampy255** [comment]
Interestingly it seems to come right if the user clicks anywhere on the document body (Similar to what you found with the sidebar bug)
This is Chrome on MacOS:

https://github.com/outline/outline/assets/67034721/82d7561e-0b76-4880-ad6b-c73fa51abefa

**Comment by tommoor** [comment]
yea, this is the behavior before 0.72.0 so It's tempting to say you're just not running the latest code somehow. Are you using the official docker image?

**Comment by lampy255** [comment]
Yes i'm using "outlinewiki/outline:0.72.0" from dockerhub.
Front end says "v0.72.0" "up to date" in the preferences sidebar.

Its definitely the new code, as I can see various new features/bug fixes that you released in 0.72.0

**Comment by tommoor** [comment]
Figured this out while working on #5939 – the browser has to be wide enough that the document content area stays the same width while the surroundings are being resized. I was working on a laptop and so this was never the case.
