### ISSUE TITLE
Update to v0.72.0 doesn't honour previous seamless editing setting

### ISSUE THREAD

**Issue by lampy255** [outline/outline#5930]
**To Reproduce**
1. With Seamless Editing set to OFF update installation to 0.72.0
2. Observe that the new "Seperate editing" feature is set to OFF for everyone. 

"Seperate editing" is the inverse behaviour of "Seamless editing", and with this setting now being an account preference, every user in an organisation will have to log in and switch their personal "Seperate editing" to ON in order to restore previous behaviour.

**Expected behavior**
Expect the update to honour the previous "Seamless Editing" global preference.  
For example: If Seamless Editing was OFF -> all users seperate editing should be initialised as ON

**Outline:**
- Install: self hosted
- Version: 4d2a5ae7485573564e971873269eaaf78ef760e2

**Desktop:**
 - OS: OSX Sonoma 14.0
 - Browser Chrome and Safari

**Comment by tommoor** [comment]
I'm not able to reproduce this one unfortunately, the user preference falls back to the team preference correctly in my testing. The team preference was unchanged between versions.

**Comment by lampy255** [comment]
And now I can't reproduce it either..
Not sure what happened. Will close this one.
