### ISSUE TITLE
Webhook becomes inactive and disabled - no errors?

### ISSUE THREAD

**Issue by ecker00** [outline/outline#5934]
**To Reproduce**
I'm creating a webhook for Mattermost, but after refreshing the Wehbooks page it comes up under "Inactive" and have a "Disabled" label on it. I don't see any errors in the server logs or errors in the interface.

**Expected behavior**
I don't expect the webhook to be disabled, or at least explain why. I am also reading on issue #423, is this maybe not supposed to work? But at least I'm expecting a error/warning for the state change.

**Screenshots**
![image](https://github.com/outline/outline/assets/1331760/37f94839-ca48-4fd3-bad9-108a603e82d7)

**Outline (please complete the following information):**
- Install: Self-hosted
- Version: 9.0 (docker)

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by ecker00** [comment]
Turns out I am getting emails about the errors, didn't realise that's how it's handled.

> Your webhook (Mattermost) has been automatically disabled as the last 25 delivery attempts have failed. You can re-enable by editing the webhook.

**Follow up question:** Are the webhooks compatible with Slack / Mattermost? (Mattermost's webhook's follow the Slack format)

**Comment by tommoor** [comment]
Webhooks are sent as JSON in our format, you can see the [documentation here](https://docs.getoutline.com/s/guide/doc/webhooks-gB7HYhS6yq). Unfortunately you can't just send Outline data to Mattermost and have it work :) For that we'd need #4271
