### ISSUE TITLE
Incorrect owner assigned in docker image for /var/lib/outline

### ISSUE THREAD

**Issue by TerryMathews** [outline/outline#5937]
**To Reproduce**
On my installation, using local file storage, image uploads would fail (both in docs and profile images).
The docker log led me to believe that there was either an underlying folder permissions issue or ownership issue:

```
outline-docker-compose-wk-outline-1      | [Error: EACCES: permission denied, mkdir '/var/lib/outline/data/public'] {
outline-docker-compose-wk-outline-1      |   errno: -13,
outline-docker-compose-wk-outline-1      |   code: 'EACCES',
outline-docker-compose-wk-outline-1      |   syscall: 'mkdir',
outline-docker-compose-wk-outline-1      |   path: '/var/lib/outline/data/public',
outline-docker-compose-wk-outline-1      |   status: 500
outline-docker-compose-wk-outline-1      | }
```

Logging into the container shell let me see that the owner of /var/lib/outline was nodejs:nodejs, but /var/lib/outline/data was root:root

**Expected behavior**
Image uploads should occur successfully. Accessing the container shell with `docker exec -u 0 -it outline-docker-compose-wk-outline-1 sh` and running `chown -R nodejs:nodejs /var/lib/outline/data` and then rebooting the containers allowed file uploads to proceed successfully.

**Outline (please complete the following information):**
- Install: self-hosted
- Version: v0.72.0-3, installed yesterday from outlinewiki/outline

**Comment by mrtimothyduong** [comment]
Please keep this closed. 

I tried tommoor's fixes but this 'use root' from https://github.com/outline/outline/discussions/8552#discussioncomment-12364808 resolved it for me

**Comment by angelic-knight** [comment]
I fixed this by finding the user that the outline process was using and changing ownership of the my mapped volume to that user.
You shouldn't need to run the outline user as root to fix this.
