### ISSUE TITLE
Complete crash of the application

### ISSUE THREAD

**Issue by Compr0mzd** [outline/outline#5939]
**To Reproduce**
1. Go on my document
2. I try to correct from a "There us" to a "There is" on a certain line
4. See the app unresponsive, refresh to the same URL document is not loading

To be fair with you I have no idea why this issue I have a table with some answers right after this table i have a specific line which makes the app crashes if I select it. 
![image](https://github.com/outline/outline/assets/83233183/d5bd1444-bb8b-4bfa-bb35-dd87d8f5f60c)
The docker memory usage is going up to 400M of RAM. 
I get this infinite cycle inside my docker logs : 
```
2023-10-05T08:46:01.096356823Z INF Processing revisions.create | attempt=0 event={"actorId":"X","collectionId":"X","createdAt":"2023-10-05T08:41:00.934Z","data":null,"documentId":"X","id":"X","ip":"X","modelId":"X","name":"revisions.create","teamId":"X","userId":null} label=worker 
2023-10-05T08:46:01.098331513Z INF NotificationsProcessor running revisions.create | event={"actorId":"X","collectionId":"X","createdAt":"2023-10-05T08:41:00.934Z","data":null,"documentId":"X","id":"X","ip":"X","modelId":"X","name":"revisions.create","teamId":"X","userId":null} label=worker 
2023-10-05T08:46:01.103643266Z INF SlackProcessor running revisions.create | event={"actorId":"X","collectionId":"X","createdAt":"2023-10-05T08:41:00.934Z","data":null,"documentId":"X","id":"X","ip":"X","modelId":"X","name":"revisions.create","teamId":"X","userId":null} label=worker 
2023-10-05T08:46:01.110621141Z INF RevisionCreatedNotificationsTask running | actorId=X collectionId=X createdAt=2023-10-05T08:41:00.934Z data=null documentId=X id=X ip=X label=worker modelId=X name=revisions.create teamId=X userId=null 
2023-10-05T08:46:01.141310339Z INF WebhookProcessor running revisions.create | event={"actorId":"X","collectionId":"X","createdAt":"2023-10-05T08:41:00.934Z","data":null,"documentId":"X","id":"X","ip":"X","modelId":"X","name":"revisions.create","teamId":"X","userId":null} label=worker 
```

I just replaced each ID with X since I don't know if this could be sensitive.

To access outline again I have to close my tab browser and open a new one. And If i try to select again this line in particular the cycle of unresponsiveness continues

**Outline :**
- Install: self hosted
- Version: Latest - 0.72.0 - 56cae8a54563c0cd3b2dd28d64baa184a45c490f

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 
 - Version 117.0.5938.134

**Comment by Compr0mzd** [comment]
I tried to duplicate the document and try to modify the line on the duplicate and it makes the crash appears again

**Comment by AiR-0nE** [comment]
Same issue here with the last update. Few seconds after editing a page i got this on Chrome : 

![2023-10-05_13h03_29](https://github.com/outline/outline/assets/33458876/49e5ef11-9086-477a-80c9-8a0d36a33b87)

**Comment by Compr0mzd** [comment]
> Same issue here with the last update. Few seconds after editing a page i got this on Chrome :
> 
> ![2023-10-05_13h03_29](https://user-images.githubusercontent.com/33458876/272881110-49e5ef11-9086-477a-80c9-8a0d36a33b87.png)

I tried to see what was causing the issie and it seems to be related to the table. Once I create a table inside the page and try to write right after it the app crashes. Is it the same for you  ?

**Comment by AiR-0nE** [comment]
In my case, there is no table in my article, only images and texts. I have no idea how to track this issue. I check my Outline Dockers logs but no error.

**Comment by tommoor** [comment]
Are there a lot of images in the document?

**Comment by AiR-0nE** [comment]
> Are there a lot of images in the document?

Actually 33, but i am pretty sure it was perfectly working before update to 0.72.0

**Comment by tommoor** [comment]
Yea, none of our test documents have tens or hundreds of images in them so it was missed. There will be a patch release for this once resolved

**Comment by Compr0mzd** [comment]
> Yea, none of our test documents have tens or hundreds of images in them so it was a missed regression. There will be a patch release for this once resolved

Great so it's images making an issue thanks for finding out the cause with us

**Comment by AiR-0nE** [comment]
Hello, I update to 0.72.1 this morning, but it does not seems to fix the memory leacks issue. @tommoor did the fix was suppose to be in this version already ? Or it will be in the next one ?

**Comment by Compr0mzd** [comment]
> Hello, I update to 0.72.1 this morning, but it does not seems to fix the memory leacks issue. @tommoor did the fix was suppose to be in this version already ? Or it will be in the next one ?

Same issue. It did not fix this issue for me either after updating

**Comment by tommoor** [comment]
Will need more logs then from the browser, I have no idea what’s happening here

**Comment by AiR-0nE** [comment]
Can this help ? (Sorry it is in French !) 

![image](https://github.com/outline/outline/assets/33458876/bd64e78d-0a2f-4a01-9e80-54cd3ce91b14)

Maybe i can export something else ? Let me know .

**Comment by tommoor** [comment]
Yes it can help you can export this data with the arrow at the top left, it will produce a json file.

Email to tom@getoutline.com

**Comment by tommoor** [comment]
Okay, no more debugging needed – I know what's going on here. There is a regex that's different when using french language to account for the use of ":" in punctuation – it seems that it's quite expensive and is now evaluated on backspace, whereas it wasn't in the previous release.

**Comment by Limezy** [comment]
Thanks, I'm now wondering if this is the reason why I felt my instance was much slower than before !

**Comment by Compr0mzd** [comment]
> Okay, no more debugging needed – I know what's going on here. There is a regex that's different when using french language to account for the use of ":" in punctuation – it seems that it's quite expensive and is now evaluated on backspace, whereas it wasn't in the previous release.
> 
> Should have realized the common thread was French here sooner!

Ahaha very funny because the regrex was introduced after I proposed this idea of unshowing emoji selection After a backspace. 😂
