### ISSUE TITLE
S3 storage doesn't work well with avatars 

### ISSUE THREAD

**Issue by kip-13** [outline/outline#5947]
We have configured S3(minio) as object storage for all the media and it's working well but we noticed `403` errors when trying to get avatars, this objects exists in minio.
It seems all other media use presigned urls but avatars doesn't :thinking: 

**Expected behavior**
The avatars should have the same behavior as other images loaded with presigned urls.

**Screenshots**
![image](https://github.com/outline/outline/assets/34191406/58d99292-e25a-48a7-a6de-f8a30c1ee85d)

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.72.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - 117.0.5938.132

**Comment by tommoor** [comment]
Avatars and organization logos are uploaded with public permissions, there's not really a plan to change this at the moment as it's been that way for many years. You should make sure the `avatars` and `public` buckets are publicly readable

**Comment by kip-13** [comment]
Thanks for the quick answer @tommoor. Yes, we ended up making public those folders in minio.
