### ISSUE TITLE
Closing inline code does not remove tick character

### ISSUE THREAD

**Issue by nicolinux** [outline/outline#5955]
When I type the tick character "`" to close an inline code, the tick remains visible and behaves weirdly when deleted manually. Check out the attached .gif which shows the issue.

**To Reproduce**
1. Open an inline code block with "`", press space and type a word.
2. Close the inline code block with "`", press space

**Expected behavior**
Inline code block highlighted with no visible tick characters after the code block.

**Screenshots**
See attached .gif.

**Outline (please complete the following information):**
- Install: selfhosted, using the awesome project from https://github.com/vicalloy/outline-docker-compose
- Version: 0.72.1 release (ebeb201)

**Desktop (please complete the following information):**
 - OS: macos 13.6
 - Browser Safari, Chrome 117.0.5938.149

![inline_code](https://github.com/outline/outline/assets/1069286/a6bd31ed-bbeb-488e-8b22-b3c69db838c9)

**Comment by tommoor** [comment]
What input language is your machine set to?

**Comment by nicolinux** [comment]
Oh sorry, didn't about it even though it is important. It is set to German. Language is set to English (UK) though.

<img width="827" alt="Screenshot 2023-10-06 at 20 46 09" src="https://github.com/outline/outline/assets/1069286/99482c0e-07c6-4de0-85b5-2a712a421a94">

**Comment by tommoor** [comment]
It's important in this case as it changes the behavior of the backtick key by the looks of your onscreen keyboard.

**Comment by nicolinux** [comment]
Wait, I got it wrong. The keyboard language is set to German. The dictation language ist set to English (UK). 

<img width="827" alt="Screenshot 2023-10-06 at 22 07 45" src="https://github.com/outline/outline/assets/1069286/71cee382-1b65-4c2a-a3b4-c44644a493a7">

**Comment by nicolinux** [comment]
Alright, set the language to English (US). Same problem.

![inline_code2](https://github.com/outline/outline/assets/1069286/1b8da060-fdd2-4d55-b9ac-d11d33298587)

**Comment by tommoor** [comment]
On a US keyboard backtick is accessed without a modifier, so that is the key difference

**Comment by nicolinux** [comment]
Ok, so the problem seems to occur because I use a keyboard with a physical layout (german) and when the input language is set to either German or English (US) which needs a modifier key for the backtick. Is this something that Outline can catch or is it just a unfortunate combination?

**Comment by tommoor** [comment]
Found a similar thread here for another prosemirror-based editor, so it looks like it's possible to fix.

https://github.com/ProseMirror/prosemirror/issues/926#issuecomment-493399783

**Comment by JensSpanier** [comment]
I'm on also using a German keyboard on a mac. I've updatet to `v0.72.2` and the behaviour is still the same:
![Bildschirmaufnahme 2023-10-12 um 12 16 29](https://github.com/outline/outline/assets/42373861/c01e999c-3580-49c0-9f1f-b82b2e752f99)

**Comment by nicolinux** [comment]
Yep, same here.

**Comment by tommoor** [comment]
I guess someone with the right hardware will have to try at fixing it in that case

**Comment by vgwidt** [comment]
Just to add a bit more info, this issue seems to occur when using IME input and also doesn't appear to be limited to inline code.  For example, typing *test, then using IME to insert the last asterisk will yield _test_*

I have the same issue using a Japanese keyboard and workaround it by switching to US input mode when entering these marks.

**Comment by JensSpanier** [comment]
Don't know if this helps, but I tested what's logged when listening to `oninput` on an input field. On Windows there is only one event logged:

```
bubbles: true
​cancelBubble: false
​cancelable: false
​composed: true
​currentTarget: null
​data: "`"
​dataTransfer: null
​defaultPrevented: false
​detail: 0
​eventPhase: 0
​explicitOriginalTarget: <input id="input" class="form-control" type="text">
​inputType: "insertText"
​isComposing: false
​isTrusted: true
​layerX: 0
​layerY: 0
​originalTarget: <input id="input" class="form-control" type="text">
​rangeOffset: 0
​rangeParent: null
​returnValue: true
​srcElement: <input id="input" class="form-control" type="text">​
target: <input id="input" class="form-control" type="text">
​timeStamp: 6174
​type: "input"
​view: Window file:///C:/Users/Jens/Desktop/test.html
​which: 0
```

On Mac there are two events:

```
bubbles: true
cancelBubble: false
cancelable: false
composed: true
currentTarget: null
data: "`"
dataTransfer: null
defaultPrevented: false
detail: 0
eventPhase: 0
explicitOriginalTarget: <input id="input" class="form-control" type="text">
inputType: "insertCompositionText"
isComposing: true
isTrusted: true
layerX: 0
layerY: 0
originalTarget: <input id="input" class="form-control" type="text">
rangeOffset: 0
rangeParent: null
returnValue: true
srcElement: <input id="input" class="form-control" type="text">​
target: <input id="input" class="form-control" type="text">
timeStamp: 2225
type: "input"
view: Window file:///Users/jspanier/Documents/Code/testing/outline/test.html
which: 0
```

```
bubbles: true
cancelBubble: false
cancelable: false
composed: true
currentTarget: null
data: "`"
dataTransfer: null
defaultPrevented: false
detail: 0
eventPhase: 0
explicitOriginalTarget: <input id="input" class="form-control" type="text">
inputType: "insertCompositionText"
isComposing: false
isTrusted: true
layerX: 0
layerY: 0
originalTarget: <input id="input" class="form-control" type="text">
rangeOffset: 0
rangeParent: null
returnValue: true
srcElement: <input id="input" class="form-control" type="text">​
target: <input id="input" class="form-control" type="text">
timeStamp: 3612
type: "input"
view: Window file:///Users/jspanier/Documents/Code/testing/outline/test.html
which: 0
```

See `isComposing` and `inputType`.

Let me know if I can help you with some more testing.

**Comment by almereyda** [comment]
Still an issue.

**Comment by josevavia** [comment]
Yeah, the issue is still present in last versions

**Comment by josevavia** [comment]
@tommoor is there anything we can do to help you solve this issue? With my spanish keyboard it is still happening.

I want to help with this issue but I dont know how
