### ISSUE TITLE
Sidebar should collapse no matter where the mouse is at first click

### ISSUE THREAD

**Issue by Limezy** [outline/outline#5958]
See title

**To Reproduce**
1. Go to a document with the side bar open
2. Click on the collapse button
3. The sidebar doesn't collapse as long as your mouse remains hovering on top of it

**Expected behavior**
I think that this UX is very confusing because you get the impression that there is a bug
Shouldn't the sidebar collapse no natter what for the first time when you click ?
Then, keeping the same UX with the side bar coming back when the mouse is on top of it seems fine

**Outline (please complete the following information):**
- Install: Self hosted
- Version: 0.72.1

**Comment by tommoor** [comment]
This is exactly the issue that was fixed here

https://github.com/outline/outline/commit/e967641bb655253932543550753dc80deaa6209b

**Comment by Limezy** [comment]
Is this commit part of the 0.72.1 release ? If so I have to investigate why it's not working on my instance !

**Comment by tommoor** [comment]
It was, but it must have regressed again – this sidebar is so finicky.
