### ISSUE TITLE
Allow drag&drop of documents under sub-documents

### ISSUE THREAD

**Issue by jorilallo** [outline/outline#596]
Currently only possible to drag and drop to root. Would be helpful to allow drag&drop under a specific document

**Comment by thomasmalley** [comment]
This would be great! I tried drag and drop being used to other Apps like Notion or Nuclio etc. (web) or Ulysses, SublimeText, VS Code and many more (desktop) or just the Sidebar in Finder etc. 
It would be the most intuitive way to organise "Documents & Folders" in my opinion and many people are used to it.

**Comment by dskeithbuck** [comment]
I'm playing with Outline for the first time, and this is one of the first features I looked for.

**Comment by tommoor** [comment]
Closed as complete.
