### ISSUE TITLE
When seamless editing is off, code block's comment option is not visible

### ISSUE THREAD

**Issue by ChetanGoti** [outline/outline#5986]
**To Reproduce**
1. Turn off Seamless editing from the Settings > Features page
2. Edit the page content and Add a code block to the page. 
3. Save it so edit mode is off
4. Select some texts from the code block
5. Notice it shows the menu, but that does not have comment button available

Note:: This works when user is in Edit mode.

**Expected behavior**
User should be able to comment on code block contents when in read mode

**Screenshots**
<img width="789" alt="Screenshot 2023-10-11 at 4 16 28 PM" src="https://github.com/outline/outline/assets/1378002/76a404f0-ebf1-410a-8b22-a19c5fd0314e">
<img width="791" alt="Screenshot 2023-10-11 at 4 16 33 PM" src="https://github.com/outline/outline/assets/1378002/cda80097-30b9-411b-bc0f-ceca05f1800a">

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 118.0.1

**Comment by Limezy** [comment]
I can reproduce, good catch !

**Comment by tommoor** [comment]
closed in a579ecd512fbeaf3df6c069c3162fd1e033d6fb3
