### ISSUE TITLE
Import from Notion not work correctly

### ISSUE THREAD

**Issue by Kirill** [outline/outline#5994]
I try move my collection from Notion to Outline. And start from small database.

**To Reproduce**
1. I publish database https://kirillkr.notion.site/729a727d1f6f41b699088b81c135bfa2?v=aa08563597c041b98efefcab40cb36ef&pvs=4
2. Export to HTML with subpage/without in Current view
3. Import proceed without error.
4. But page is broken

**Screenshots**
![image](https://github.com/outline/outline/assets/302940/70af7c81-b74c-4ca7-aaea-4a0f027bb7e2)
![image](https://github.com/outline/outline/assets/302940/df926ca8-0c68-4f07-b050-8a9a0a2c6659)

**Outline (please complete the following information):**
- Install: self hosted with docker
- Version: v0.72.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi
 - Version: 6.2.3105.58 (Stable channel) (64 бита)

**Comment by tommoor** [comment]
Could you add the HTML export here?

**Comment by Kirill** [comment]
Yes, [please](https://github.com/outline/outline/files/12908884/25b17c11-1530-498b-a386-7ac98d158d2e_Export-9e62f46b-9911-4d5f-a5c1-8933addf0d14.zip).

**Comment by tommoor** [comment]
Some improvements have landed here in regards to importing collections from Notion specifically
