### ISSUE TITLE
Deleting a blank line below an info (or similar) block seems to merge the current block into the upper block

### ISSUE THREAD

**Issue by alkanna** [outline/outline#5996]
**To Reproduce**
- Create an info block
- Add an empty line
- Create any other block just below the empty line
- Try to remove the empty line

Video of the reproduction here : https://share.cleanshot.com/r17jC6Qd

**Expected behavior**
The empty line should be properly deleted and not merged into the upper block

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.72.2

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Browser Arc (chromium)
 - Version latest

**Comment by tommoor** [comment]
This is expected behavior of the editor, you can think of the Backspace key as the opposite of Enter when it comes to blocks. Enter will split into two, and Backspace will join with the previous
