### ISSUE TITLE
AWS S3 URL incorrect on GET files

### ISSUE THREAD

**Issue by mlagoma** [outline/outline#5999]
There appears to be an issue with URL generation for GET request when uploading files.

This is not an issue and works fine with my configuration of outline for version 0.69.1, but it becomes an issue when upgraded to version 0.72.1.

v0.69.1 GET request after image upload:
`https://s3.us-east-1.amazonaws.com/<BUCKET_NAME>/uploads/[...]`

v0.72.1 GET request after image upload:
`https://s3.us-east-1.amazonaws.com/<BUCKET_NAME>/<BUCKET_NAME>/uploads/[...]`

**To Reproduce**
My environment:
https://github.com/encircle360-oss/outline-helm-chart
```
FILE_STORAGE: 's3',
AWS_REGION: props.env?.region,
AWS_S3_UPLOAD_BUCKET_URL: props.bucketURL,
AWS_S3_UPLOAD_BUCKET_NAME: props.bucketName,
AWS_S3_FORCE_PATH_STYLE: true,
AWS_S3_ACL: 'private',
AWS_ACCESS_KEY_ID: 'outline',
AWS_SECRET_ACCESS_KEY: 'outline',
```

1. Using version 0.69.1, confirm uploading images works fine with above environment
2. Upgrade to version 0.72.1 (warning: There seems to be many problems deploying changes to the configuration, particularly env vars, of this helm chart. May require deleting deployment and/or initiating stack action to complete EKS cluster rollback in cloudformation)
3. Confirm uploading images works, but then encounters a 403 (Access Denied) due to incorrect URL on the GET request.

**Expected behavior**
When uploading images with AWS S3 environment, the GET request after image upload should work correctly.

**Comment by tommoor** [comment]
I’m not aware of any meaningful changes to S3
In recent versions, what do the actual config values look like?

**Comment by mlagoma** [comment]
Here's my (partial) environment:
```
    Environment:
      SECRET_KEY:                 5974e36f82085f057223565ac2d0d01427a90248ade611108b4b937672649bd4
      SECRET_KEY:                 <set to the key 'SECRET_KEY' in secret 'outline'>  Optional: false
      UTILS_SECRET:               8c5a14973325ba56694a99856e6be330812b875e5f683dd37022cf76444774bb
      UTILS_SECRET:               <set to the key 'UTILS_SECRET' in secret 'outline'>  Optional: false
      PORT:                       3000
      COLLABORATION_URL:
      URL:                        http://outline.yourdomain.tld
      URL:                        https://<MY_DNS_NAME>
      FORCE_HTTPS:                false
      AWS_REGION:                 us-east-1
      AWS_S3_ACL:                 private
      AWS_S3_FORCE_PATH_STYLE:    true
      AWS_S3_UPLOAD_BUCKET_NAME:  <BUCKET_NAME>
      AWS_S3_UPLOAD_BUCKET_URL:   https://s3.us-east-1.amazonaws.com/<BUCKET_NAME>
      FILE_STORAGE:               s3
      AWS_ACCESS_KEY_ID:          <set to the key 'AWS_ACCESS_KEY_ID' in secret 'outline'>         Optional: false
      AWS_SECRET_ACCESS_KEY:      <set to the key 'AWS_SECRET_ACCESS_KEY' in secret 'outline'>     Optional: false
  ```

**Comment by tommoor** [comment]
As a workaround try moving to the hostname style as the path-style has been deprecated for some time:

```
AWS_S3_FORCE_PATH_STYLE=false
AWS_S3_UPLOAD_BUCKET_URL=https://<BUCKET_NAME>.s3.us-east-1.amazonaws.com
```

**Comment by mlagoma** [comment]
It's working now, thanks! Feel free to close this.

P.S. if anybody is using cdk Bucket properties, this is the change to get the different URL format:
```
-    new CfnOutput(this, 'WikiBucketURL', { value: wikiBucket.urlForObject() })
+    new CfnOutput(this, 'WikiBucketURL', { value: wikiBucket.virtualHostedUrlForObject() })
```
