### ISSUE TITLE
Slack unfurl limited to non-private collections when non-Slack auth provider is used 

### ISSUE THREAD

**Issue by breart** [outline/outline#6004]
We have self-hosted Outline and recently tried to configure Slack unfurl to have rich link previews and faced an issue with user identification. 

This is what we see in the logs:
```
{"label":"http","level":"info","message":"  <-- POST /api/hooks.unfurl"}
{"label":"plugins","level":"debug","message":"No user found for Slack user ID","providerId":"U05BASF0NEP"}
{"label":"http","level":"info","message":"  --> POST /api/hooks.unfurl 404 10ms -"}
```

For some reason, it doesn't use email of the user and instead uses Slack user ID, which I suspect may work well when users use Slack for authorization in Outline, but our main provider is Google, so we don't have Slack user ID associated with each member of the workspace.

**Expected behavior**
Link previews work regardless of the auth provider being used in Outline, as long as Slack integration is configured properly.

**Outline:**
- Install: self-hosted
- Version: 0.72.1

**Comment by tommoor** [comment]
This is a known limitation, working on the ability to link external accounts separate to authentication so that the user can be mapped.

**Comment by brezzhnev** [comment]
Would that require each of the workspace member to connect via Slack?

Have you considered fetching the workspace users during the initial setup along with their emails? Then periodically sync to ensure recently added users are reflected?

**Comment by tommoor** [comment]
It would, fetching the workspace wouldn't tell you which users are linked to which Outline users unfortunately

**Comment by tommoor** [comment]
This sounds good, but I'm not following the last section. 

The "gotcha" here is how to store the mapping of Slack user -> Outline user, currently we use `UserAuthentication` for this, which itself requires a slack `AuthenticationProvider`, we could create one JIT if it doesn't exist, it would need to be `enabled: false` so that Slack doesn't suddenly appear as a login option for the team.
