### ISSUE TITLE
Comment link lost

### ISSUE THREAD

**Issue by MorganReid** [outline/outline#6011]
It doesn't happen necessarily, but it happens often.

**To Reproduce**
1. Open a specific wiki(not in edit mode) by account A
2. select specific content(such as Note) and comment
3. Open same wiki by account B
4. specific content(such as Note) not a comment but a common text

**Expected behavior**
specific content(such as Note) is a comment by account B.

**Screenshots**
account A:
![image](https://github.com/outline/outline/assets/52235796/3c103dc0-864d-4003-89df-4a92b6ecb087)

account B:
![image](https://github.com/outline/outline/assets/52235796/f438c9cc-f264-48c0-9de1-7aca521062a9)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.71.0

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: chrome
 - Version: 109.0.5414.119 (Official Build) (64-bit)

Through the console, I found that the `comment-marker` will be added to the commented content. This does not exist when it is not a comment.
![image](https://github.com/outline/outline/assets/52235796/d97032e0-e035-4e82-9c38-d1c66122786f)

I queried the database and found the `documents` and `comments` tables, but it seems that the mapping relationship between comments and corresponding content is not recorded in it. How is the comment function implemented?

**Comment by tommoor** [comment]
I cannot reproduce with your steps, so as you say there must be more to it. The marker in the content is stored as part of the `document.state` – it's not human readable as it's a CRDT stored in binary format.

Your symptoms would suggest that the edit to the state was not persisted for some reason, if you can reproduce and get server logs that might help.

**Comment by verement** [comment]
It seems that if the commenting user has only View permissions, then the marker for the resulting comment will not be visible to anyone except that user.

**Comment by tommoor** [comment]
This sounds like it could be the issue, the comment on a text functionality should be unavailable to viewers.

**Comment by NangeGao** [comment]
> This sounds like it could be the issue, the comment on a text functionality should be unavailable to viewers.

I think viewers also need to have comment functions. For example, when we publish an instruction manual to users, they need a channel for feedback.

**Comment by tommoor** [comment]
Viewers can still comment on the document from the sidebar, but it's a limitation that they cannot comment on text for now as it actually modifies the document.

**Comment by verement** [comment]
> Viewers can still comment on the document from the sidebar, but it's a limitation that they cannot comment on text for now as it actually modifies the document.

Would there be any reason not to allow this?

**Comment by tommoor** [comment]
Not from a product point of view, it's mainly a technical limitation. To keep the focus on this issue, if there is a way to create a text selection comment as a viewer then that would be the bug here for now.

**Comment by max-mykhailenko** [comment]
> Not from a product point of view, it's mainly a technical limitation. To keep the focus on this issue, if there is a way to create a text selection comment as a viewer then that would be the bug here for now.

@tommoor Do you plan to add this feature sometime in the near future? It would be really helpful, especially when the team is working on large documentation.
