### ISSUE TITLE
Regex match false positive for `NotContainsUrl` validator

### ISSUE THREAD

**Issue by mnixry** [outline/outline#6012]
Introduced in https://github.com/outline/outline/pull/3725

https://github.com/outline/outline/blob/9e3b2c043c850a1d7feb9f94811f005cd7a274d1/server/models/validators/NotContainsUrl.ts#L7-L16

**To Reproduce**

1. Register a user with `www` + any two number or alphabet
2. An error with `Must not contain a URL` appeared in server log and register failed.

**Expected behavior**
User with name in this form should be able to register, or admin may possible to disable this check.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
![image](https://github.com/outline/outline/assets/32300164/6abcdd39-f31e-4645-b93b-61c71b873721)
![image](https://github.com/outline/outline/assets/32300164/bf14e72b-91bf-46c5-923c-7f2140f35fa1)

**Outline (please complete the following information):**
- Install: self-hosted
- Version: latest docker build for `v0.72.2`

**Comment by tommoor** [comment]
This validation is loose on purpose, you really have someone with a name that contains www?

**Comment by mnixry** [comment]
> This validation is loose on purpose, you really have someone with a name that contains www?

Yes, and that is exactly how I found this bug.

Moreover, this validation check applies to every individual who registers through OIDC, Azure, Google, or Slack. The username in this scenario is not within the control of the Outline service host. It appears somewhat counterintuitive that the user experiences a registration failure solely when attempting to sign up for the Outline service, and having to alter the username on these platforms in order to use Outline doesn't make any sense. Furthermore, it's worth highlighting that there appears to be a lack of a comprehensive error message for the user in such instances.
