### ISSUE TITLE
Cannot embed editable Grist page

### ISSUE THREAD

**Issue by phaethon** [outline/outline#6013]
Grist allows 2 forms of embedding (both hide header and sidebar):

1. ?embed=true , which makes content read only for everyone
2. ?style=singlePage , allowing content to be edited according to access rules

Outline allows embedding Grist page. It always adds ?embed=true at the end, thus it is not possible to embed editable Grist page (e.g. a table).

**To Reproduce**
1. Embed Grist table using link with ?style=singlePage at the end;
2. See that content is not editable. Using Web developer tools see that ?embed=true is added at the end.

**Expected behavior**
If ?style=singlePage is already added to the end of the link, it should not get replaced with ?embed=true.
Alternatively, ?style=singlePage should always be added insted of ?embed=true.

**Outline (please complete the following information):**
- Install: self hosted
- Version: tag v0.72.2

I had a quick look at the code and it seems a trivial change in Grist.tsx to replace ?embed=true with ?style=singlePage.
Optionally, as an additional feature input dialog could determine if Grist page should be editable. Dialog currently displaying only Grist URL textbox could contain checkbox - Editable (choosing true adds ?style=singlePage, choosing false adds ?embed=true).

**Comment by yashnirmal** [comment]
Hey @tommoor would love to take this up

**Comment by yashnirmal** [comment]
Getting the below error when building the project using `make up`
Any idea on how can I solve this?


```
[backend] [api] Debugger listening on ws://0.0.0.0:9229/281c56e9-6031-4a47-905f-6f05da10c5e8
[backend] [api] For help, see: https://nodejs.org/en/docs/inspector
[backend] [api] info: [email] SMTP_USERNAME not provided, generating test account... 
[backend] [api] Failed to create directory for local file storage at /var/lib/outline/data
[backend] [api] Error: EACCES: permission denied, mkdir '/var/lib/outline/data'
[backend] [api]     at mkdirSync (node:fs:1382:3)
[backend] [api]     at mkdirSync (/Users/yash/Desktop/vs-workspace/opensource/outline/node_modules/dd-trace/packages/datadog-instrumentations/src/fs.js:265:57)
[backend] [api]     at createRootDirForLocalStorage (/Users/yash/Desktop/vs-workspace/opensource/outline/build/plugins/storage/server/utils.js:16:27)
[backend] [api]     at Object.<anonymous> (/Users/yash/Desktop/vs-workspace/opensource/outline/build/plugins/storage/server/api/files.js:27:41)
[backend] [api]     at Module._compile (node:internal/modules/cjs/loader:1198:14)
[backend] [api]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
[backend] [api]     at Module.load (node:internal/modules/cjs/loader:1076:32)
[backend] [api]     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
[backend] [api]     at Module.require (node:internal/modules/cjs/loader:1100:19)
[backend] [api]     at Module.Hook.Module.require (/Users/yash/Desktop/vs-workspace/opensource/outline/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
[backend] [api]     at require (node:internal/modules/cjs/helpers:119:18)
[backend] [api]     at /Users/yash/Desktop/vs-workspace/opensource/outline/build/server/routes/api/index.js:63:15
[backend] [api]     at Array.forEach (<anonymous>)
[backend] [api]     at Object.<anonymous> (/Users/yash/Desktop/vs-workspace/opensource/outline/build/server/routes/api/index.js:61:89)
[backend] [api]     at Module._compile (node:internal/modules/cjs/loader:1198:14)
[backend] [api]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
[backend] [api]     at Module.load (node:internal/modules/cjs/loader:1076:32)
[backend] [api]     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
[backend] [api]     at Module.require (node:internal/modules/cjs/loader:1100:19)
[backend] [api]     at Module.Hook.Module.require (/Users/yash/Desktop/vs-workspace/opensource/outline/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
[backend] [api]     at require (node:internal/modules/cjs/helpers:119:18)
[backend] [api]     at Object.<anonymous> (/Users/yash/Desktop/vs-workspace/opensource/outline/build/server/services/web.js:19:35) {
[backend] [api]   errno: -13,
[backend] [api]   syscall: 'mkdir',
[backend] [api]   code: 'EACCES',
[backend] [api]   path: '/var/lib/outline/data'
[backend] [api] }
[backend] [api] (node:8396) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
[backend] [api] 
[backend] [api] Please migrate your code to use AWS SDK for JavaScript (v3).
[backend] [api] For more information, check the migration guide at https://a.co/7PzMCcy
[backend] [api] (Use `node --trace-warnings ...` to show where the warning was created)
[backend] [api] info: [lifecycle] Gracefully quitting 
[backend] [api] node --inspect=0.0.0.0 build/server/index.js --services=cron,collaboration,websockets,admin,web,worker exited with code 0
```

**Comment by amoralesc** [comment]
@yashnirmal Assuming you are following [this guide](https://docs.getoutline.com/s/hosting/doc/local-development-5hEhFRXow7) to setup your dev environment, you must have created the `.env` file.

The default values have:

- `FILE_STORAGE`: `local` (save images and file attachments in a local directory managed by Outline)
- `FILE_STORAGE_LOCAL_ROOT_DIR`: `/var/lib/outline/data` (path to where the files are stored)

Since (for good reasons) the program doesn't have default write access to create a directory in this path, it fails. I suggest replacing this variable to a relative path, like `./data`. **Be careful not to commit this directory if you add data!**

Another suggestion is not "upping" the fakes3 service, and using the `./fakes3` directory, which is currently gitignored.

**Comment by amoralesc** [comment]
@tommoor could it be possible to update the `.gitignore` to ignore a pattern like `data/*` or `uploads/*`? This would improve local development

**Comment by yashnirmal** [comment]
> @yashnirmal Assuming you are following [this guide](https://docs.getoutline.com/s/hosting/doc/local-development-5hEhFRXow7) to setup your dev environment, you must have created the `.env` file.
> 
> The default values have:
> 
> * `FILE_STORAGE`: `local` (save images and file attachments in a local directory managed by Outline)
> * `FILE_STORAGE_LOCAL_ROOT_DIR`: `/var/lib/outline/data` (path to where the files are stored)
> 
> Since (for good reasons) the program doesn't have default write access to create a directory in this path, it fails. I suggest replacing this variable to a relative path, like `./data`. **Be careful not to commit this directory if you add data!**
> 
> Another suggestion is not "upping" the fakes3 service, and using the `./fakes3` directory, which is currently gitignored.

Thanks @amoralesc, it worked

But know when getting to localhost:3000, it shows nothing and in the console following errors are coming. can you help me with these
<img width="577" alt="Screenshot 2023-10-21 at 5 23 52 PM" src="https://github.com/outline/outline/assets/78169683/9c37b113-c4eb-4428-b563-c0bc4c540720">

**Comment by amoralesc** [comment]
@yashnirmal There could be a lot of possible errors, so more info will be needed.

For starters, https://localhost:3000/ won't really work on the browser and it isn't the IP you should be using. The sever uses CORS and blocks resources from cross-origins different than `app.outline.dev`. What this means is that you will have to use the URL https://app.outline.dev:3000/.

That said, it seems that there was an error with the SSL protocol. Visit https://app.outline.dev:3000/ and provide more info about what the error is. This could be an error by the SSL installation.

BTW, is your OS Windows? The official docs do say that the supported envs are Unix-like, as far as I'm aware. I would strongly encourage using WSL over Windows for setting the development environment, as Windows may just not work altogether. I created a guide in #6049 that has a step-by-step guide to setting up in WSL2 (Ubuntu).

**Comment by Ghvstcode** [comment]
> Grist allows 2 forms of embedding (both hide header and sidebar):
> 
> 1. ?embed=true , which makes content read only for everyone
> 2. ?style=singlePage , allowing content to be edited according to access rules
> 
> Outline allows embedding Grist page. It always adds ?embed=true at the end, thus it is not possible to embed editable Grist page (e.g. a table).
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Embed Grist table using link with ?style=singlePage at the end;
> 2. See that content is not editable. Using Web developer tools see that ?embed=true is added at the end.
> 
> **Expected behavior** If ?style=singlePage is already added to the end of the link, it should not get replaced with ?embed=true. Alternatively, ?style=singlePage should always be added insted of ?embed=true.
> 
> **Outline (please complete the following information):**
> 
> * Install: self hosted
> * Version: tag v0.72.2
> 
> I had a quick look at the code and it seems a trivial change in Grist.tsx to replace ?embed=true with ?style=singlePage. Optionally, as an additional feature input dialog could determine if Grist page should be editable. Dialog currently displaying only Grist URL textbox could contain checkbox - Editable (choosing true adds ?style=singlePage, choosing false adds ?embed=true).

Not sure that is what happens ATM - [The regex](https://github.com/outline/outline/blob/main/shared/editor/embeds/Grist.tsx#L10) doesn’t replace `?style=singlePage` with `?embed=true ` it just adds `?embed=true` to the string already containing `?style=singlePage` & the embed can be edited. 

A possible improvement like you suggested could be to add a checkbox when embedding to specify if the embed should be editable or not but I think that will require a (significant?) change to the way embeds are currrently being done

**Comment by anthonyronda** [comment]
@Ghvstcode you're correct, appending embed=true is causing the unintended behavior phaethon is seeing. When both URI parameters are there, the embed becomes read only

The change would be "do not append embed=true if style=singlePage is present." It is one or the other, not both

[Documentation source]( https://support.getgrist.com/embedding/)
