### ISSUE TITLE
Bug when using an unknown font within a math block

### ISSUE THREAD

**Issue by Limezy** [outline/outline#6021]
**To Reproduce**
1. Create a document
2. Create a math block with a weird unicode character such as 𝔁𝔂
3. See error

**Expected behavior**
At best, a working math block. If not, a warning without full crash...

**Screenshots**
<img width="900" alt="image" src="https://github.com/outline/outline/assets/24638389/5680e45c-0370-434a-a447-cbee2da1af78">

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.72.1

**Comment by tommoor** [comment]
This issue is upstream in the KaTeX library https://github.com/KaTeX/KaTeX/issues/2647

**Comment by Limezy** [comment]
Is there a way to "catch" that bug and prevent Outline from crashing when it happens ?
I don't really mind the math block not working to be honest, but I don't want to crash my instance each time I try to add a weird unicode character (which happens quite a lot!)

**Comment by tommoor** [comment]
Unfortunately this would need to be caught in the `prosemirror-math` module which hasn't been updated for quiet a while. We'd need to vendorize and fix… at some point but this is low priority.

**Comment by Limezy** [comment]
Understood !
