### ISSUE TITLE
Previous/default code language is no longer used to start new code blocks

### ISSUE THREAD

**Issue by tommoor** [outline/outline#6040]
Not sure what happened here yet, but something regressed – starting a new code block should remember previous language selection.

### Discussed in https://github.com/outline/outline/discussions/6039

<div type='discussions-op-text'>

<sup>Originally posted by **cyr0nk0r** October 19, 2023</sup>
When creating a code block, either through the GUI directly, or if using markdown "```" the default language selected is "javascript".
Please add an option in the admin area to select the default language when code blocks are first created.

Not all of us want javascript to always be the first selection.</div>

**Comment by Pranav2612000** [comment]
Hey @tommoor I'll like to work on this issue.

**Comment by tommoor** [comment]
I actually suspect the problem may be only when creating code through markdown shortcut. If that’s the case it may be a more complex fix, but take a look

**Comment by Pranav2612000** [comment]
I observe its happening even if you create code using the `+` button to add a code block.
In any case, I have the local set up complete. I'll try to fix it and have a PR up soon.

**Comment by Pranav2612000** [comment]
I've come up with a [possible](https://github.com/outline/outline/pull/6062) solution to fix this issue. The reason and the solution are explained in the PR description. Please take a look when you have time. Thank you
