### ISSUE TITLE
OIDC Error: An email field was not returned in the profile parameter, but is required

### ISSUE THREAD

**Issue by YIKAILucas** [outline/outline#6041]
**To Reproduce**
1. set SSO with IBM IAM
2. Click on login in.
3. After login it in and redirect to outline url, it Failed.

![image](https://github.com/outline/outline/assets/32409911/e0dff1b4-256c-4727-a10d-cb129d80ee10)

**Screenshots**
![image](https://github.com/outline/outline/assets/32409911/3ee958dc-a453-4ea8-8a11-4ef00b2ae735)

- Version: [Docker self host latest version]

It is same with this issue #2678

**Comment by tommoor** [comment]
This is not an error that can be fixed. All of the details are there in error message for you to address the issue.

**Comment by tommoor** [comment]
I'm not sure, it depends on too many factors – but the error is that your OIDC provider is not sending `email`.

**Comment by YIKAILucas** [comment]
It works. OIDC return email field
