### ISSUE TITLE
Import from Notion doesn't work

### ISSUE THREAD

**Issue by Bravo0795** [outline/outline#6043]
**To Reproduce**
1. Go to 'Import'
2. Click on 'Notion import'
3. See error

**Screenshots**
![image](https://github.com/outline/outline/assets/131441904/67b31b68-538e-46d0-90e3-fa0a54737aec)

**Outline (please complete the following information):**
- Install: [self hosted]
- Version: [0.72.2]

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [118.0.5993.89]

**Comment by amoralesc** [comment]
I experienced the same behavior (0.72.2). I will upload the logs later when I get a chance. Tried HTML export, Markdown export, files/no files included, and of all them failed

**Comment by tommoor** [comment]
Need more details gang or this will get auto-closed out

**Comment by Bravo0795** [comment]
Please, clarify what details do you need.

**Comment by Bravo0795** [comment]
Did import one more time and it is working.

**Comment by EdiBianco** [comment]
still not working, tried both html and markdown with and without images

**Comment by tommoor** [comment]
How exactly are you exporting from Notion? There have been lots of successful imports since this was closed

**Comment by EdiBianco** [comment]
Hi Tom.
I exported the full team space as markdown, with and without images. It
creates a zip file that failed to be imported. I extracted the zip file and
found out there was another zip inside. I imported that one and the import
finally started, but it's being processing for more than 3 hours now, and
it's just a 50mb file with about 3800 pages but no file/image.

Do you have any hint or suggestions?

Best regards, Edi

**Comment by bennylame** [comment]
I have the same issue, can't believe I'm paying for this.

**Comment by tommoor** [comment]
Hi @bennylame – If you're paying for cloud hosted I would recommend contacting support with the details of the failure, we can assist from there.

**Comment by EdiBianco** [comment]
> Hi @bennylame – If you're paying for cloud hosted I would recommend contacting support with the details of the failure, we can assist from there.

So what someone that is not a subscriber yet can do to see if this tool is well suited for his organization?
I rtied several times importing from Notion and the process keeps running for days before returning a fatal error.
How are you suposted to convince people that it's worth switching if there are all these issues on the import functionality?

**Comment by tommoor** [comment]
Importers are hard, there are a hundred ways it can fail bringing in content from another tool. I misspoke in regards to being a paying customer, but if you're trying to use cloud hosted and want to email in we can debug in more detail.

**Comment by EdiBianco** [comment]
Hey @tommoor it seems like you did it!
I have good news: **the import is working now** when replicating these steps:

1. Select a Teamspace in Notion
2. Click on the three dots on the top right
3. Click on Export
4. Select HTML format, include content=Everything, include subpages=ON and creat folders=ON
5. Export
6. Go to Outline and Import the Notion file

Please note that if the file size is too big the process may fail with an error. In that case try exporting without including all images and files (Step 4 - Include content).

PS. If you need to export "Everything", you can split your Notion's export in smaller chunks by selecting a subpage and its siblings separately!

Good luck!

**Comment by FlowinBeatz** [comment]
> 1. Select a Teamspace in Notion
> 2. Click on the three dots on the top right
> 3. Click on Export

Where did you find "Export"? When I click the three dots there are only settings available.

![image](https://github.com/user-attachments/assets/6afbb9dd-ee7b-4eba-8056-edcb1c791f89)

**Comment by Cloud11PL** [comment]
Following up - I have the same issue. I'm using Outline in cloud and I get `Failed • Uploaded file does not contain any valid collections. It may be corrupt, the wrong type, or version. •`

**Comment by tommoor** [comment]
Please contact support directly and we will be able to investigate the
specific problematic file

**Comment by FlowinBeatz** [comment]
> Following up - I have the same issue. I'm using Outline in cloud and I get `Failed • Uploaded file does not contain any valid collections. It may be corrupt, the wrong type, or version. •` @tommoor could you check if everything is okay with the import feature?

I made the same mistake and exported the wrong files. Follow https://github.com/outline/outline/issues/6043#issuecomment-1942002027 and it'll work.

**Comment by markus-gx** [comment]
> > Following up - I have the same issue. I'm using Outline in cloud and I get `Failed • Uploaded file does not contain any valid collections. It may be corrupt, the wrong type, or version. •` @tommoor could you check if everything is okay with the import feature?
> 
> I made the same mistake and exported the wrong files. Follow [#6043 (comment)](https://github.com/outline/outline/issues/6043#issuecomment-1942002027) and it'll work.
> 
> The trick is not to click the three dots where I did in my [previous comment](https://github.com/outline/outline/issues/6043#issuecomment-2367945938) (in the page listing) but in the top right corner of the Notion app and then select Export:
> 
> <img alt="image" width="311" src="https://private-user-images.githubusercontent.com/4570808/381162540-332557c6-24d3-4aec-b291-cc722e563f1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTIxNjgsIm5iZiI6MTczMDIxMTg2OCwicGF0aCI6Ii80NTcwODA4LzM4MTE2MjU0MC0zMzI1NTdjNi0yNGQzLTRhZWMtYjI5MS1jYzcyMmU1NjNmMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjlUMTQyNDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTgyZGE0N2IyZTI3OWE5Mzc5NmQyOWFjNDU4Nzg5OTE5MWY4MzMxMDlhMWZiZjllYjMyMTA3ZTg3ZjI1MjM5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bn7x4aw7GL5nUpiSJrMXNO6A7nU6v1fXyUmU2RlnmNU">

Found it in the same minute and wanted to comment here 🤣
Funny tbh. Thanks :)

**Comment by FlowinBeatz** [comment]
> Found it in the same minute and wanted to comment here 🤣 Funny tbh. Thanks :)

That'll cost you a coffee ;-)
