### ISSUE TITLE
DropdownMenu is not using the left prop

### ISSUE THREAD

**Issue by amitzur** [outline/outline#605]
This is something I noticed while reading the code.
The property `left` defined in this line: https://github.com/outline/outline/blob/cd2cbf1c1581b595613822c783fb8992d48a3b2d/app/components/DropdownMenu/DropdownMenu.js#L24 is never accessed in `Menu` component.

I suppose this is not intentional, and it's possible to either remove it or use it.

**Comment by tommoor** [comment]
Yep, seems like this could be removed without trouble!

**Comment by amitzur** [comment]
Thanks for addressing this
