### ISSUE TITLE
Updating Outline using Docker always results in an archivedAt column error

### ISSUE THREAD

**Issue by recklessnl** [outline/outline#6071]
I'm currently on version 0.69.2, using Docker on Debian 12. It has worked great for months. I'm trying to upgrade to the latest branches now, but any branch after 0.70 gives me the following error:

```
outline  | yarn run v1.22.19
outline  | $ sequelize db:migrate --env production-ssl-disabled
outline  |
outline  | Sequelize CLI [Node: 18.18.1, CLI: 6.6.1, ORM: 6.33.0]
outline  |
outline  | Loaded configuration file "server/config/database.json".
outline  | Using environment "production-ssl-disabled".
outline  | == 20230419124305-add-archivedat-col-to-notifications: migrating =======
outline  |
outline  |
outline  | ERROR: column "archivedAt" of relation "notifications" already exists
outline  | error Command failed with exit code 1.
outline  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

And does this repeatedly. I'm using Postgres 15 as the database in a separate container. How do I fix this error?

**Comment by tommoor** [comment]
Seems like a migration has partially failed at some point? You can either remove the `notifications.archivedAt` column in your DB or add a row to `SequelizeMeta` with the migration name so that it won't run the migration next time.

Either way you need to access the db through the terminal or a GUI and modify it directly.

**Comment by recklessnl** [comment]
Okay, I can access the postgres database @tommoor, can you share what the commands exactly are to remove the `notifications.archivedAt` column?

**Comment by recklessnl** [comment]
@tommoor could you help a hand here to fix this issue?

**Comment by recklessnl** [comment]
@tommoor Using a graphical tool helped fix the issue - thanks Tom.
