### ISSUE TITLE
Emoji search not working

### ISSUE THREAD

**Issue by wade-dallon** [outline/outline#6073]
After typing ":" to start an emoji search, the search doesn't appear to work as intended:

![image](https://github.com/outline/outline/assets/131477724/4a2f1f4b-2476-45f8-8159-a783278eda46)

I would expect that when typing "Gri", "Grimace" would be an option before "Grinning" and yet it is down the list and there are many items that don't appear to have "Gri" in their name at all.  Most of the time I can't get the emoji's I want to appear.

Typing:
* "Cheq" -> no results
* "che" -> "Chequered Flag" (among others like "Hotel", "Straight Ruler", and "Triangular Ruler")
* "flag" -> "Carp Streamer" (no "Chequered Flag" or other flags)

---

**To Reproduce**
1. Go to a document
2. Type ":"
3. Type search terms
4. See seemingly random results

**Expected behavior**
I'd expect search results that included the terms and sorted alphabetically

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
Tried in each of the following:
 - OS: iOS
 - Browser: chrome, safari

**Comment by tommoor** [comment]
Thanks for raising, these results were terrible

**Comment by patzm** [comment]
awesome! This is already a very long-standing issue. I was just about to finally write a ticket for it, and found this. @tommoor, I can test a beta build if you publish an image somewhere publicly. Otherwise, I will just wait for the next release.
