### ISSUE TITLE
Move files from s3 to local filesystem

### ISSUE THREAD

**Issue by njsubedi** [outline/outline#6077]
When we set these environment variables and start the app,
```
FILE_STORAGE=local
FILE_STORAGE_UPLOAD_MAX_SIZE=26214400
```
 Outline starts uploading the newly uploaded files to the local filesystem. But still, the old files are kept on the S3 server. To remove an unnecessary dependency, the previously uploaded files should be copied to the local filesystem automatically.

**Comment by Limezy** [comment]
You should be moving the files yourself, keeping the same folder architecture as the one within your s3 client

**Comment by tommoor** [comment]
Agreed, @njsubedi – we won't be automating this process. You can use a single terminal command or an S3 GUI to achieve the move.
