### ISSUE TITLE
Cannot log in after upgrade. Validation isIP on lastActiveIp failed (lastActiveIp)

### ISSUE THREAD

**Issue by rudolfdobias** [outline/outline#6083]
We've upgraded the wiki from 0.61.1
 - Most users cannot log in due to error in title
 - The ones who are already logged in cannot perform any write operation

Log is full of these errors:
```
{
"error":"Validation error: Validation isIP on lastActiveIp failed",
"level":"error",
"message":"Failed to update user activeAt",
"stack":"SequelizeValidationError: Validation error: Validation isIP on lastActiveIp failed\n at InstanceValidator._validate (/opt/outline/node_modules/sequelize/lib/instance-validator.js:50:13)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async InstanceValidator.validate (/opt/outline/node_modules/sequelize/lib/instance-validator.js:54:12)\n at async User.save (/opt/outline/node_modules/sequelize/lib/model.js:2426:7)"
}
```

We're using a Slack as login provider.

I have gone through all the users in the DB and experimentally tried to manually fill in missing lastActiveIps. No effect. (Don't worry I have the DB backed up). 
Also, the error says "Failed to update user activeAt" although there is no `activeAt` column in the users table. I'm quite confused here.

**To Reproduce**
1. Have a 0.61.1 version installed
2. Updated to v0.72.2 (tried also 0.69.2)

**Expected behavior**
Users can log in.

**Screenshots**
<img width="443" alt="Screenshot 2023-10-27 at 15 41 06" src="https://github.com/outline/outline/assets/2642842/49f90113-7444-427c-8fbd-494d992c6c4f">
<img width="1680" alt="Screenshot 2023-10-27 at 15 43 45" src="https://github.com/outline/outline/assets/2642842/d184e1ca-a29b-4331-861c-b34d1f32677e">

**Outline (please complete the following information):**
- Install: self hosted
- Version: outlinewiki/outline:0.72.2 docker image

**Desktop (please complete the following information):**
 - OS: OSX 11.7.4
 - Browser chrome

**Comment by tommoor** [comment]
As the error says the ip address being provided is invalid, what proxy are you running in front of Outline? I would check your configuration to ensure that a valid value is set in `X-Forwarded-For`

**Comment by rudolfdobias** [comment]
Thank you for your prompt response. There is an Azure Application Gateway in front of the outline, and it appears that the value of `X-Forwarded-For` is in the format X.X.X.X:56234. My assumption is that Outline might face difficulties parsing the IP when it includes the port information, and this leads to the exception when saving data in the DB-access layer.

In all honesty, this situation can be a bit challenging for an user who is not familiar with Outline internals. Even more, overriding Azure App Gateway to strip the port from the header will be challenging as well... It would greatly enhance devops/admin experience if some of the following options could be considered:

 - Modify Outline to parse the IP from the header, even when it contains the port, or
 - If such an exception occurs, it would be nice that it provides a more descriptive message about the need of clean IP in that header, or
 - Include a notice in the docs emphasizing the need of a clean IP format in that header.
 
 
In any case, those are just my suggestion and thank you for bringing us a great software :)

**Comment by tommoor** [comment]
The defacto standard is for XFF to be an IP address, there is `X-Forwarded-Port` for the port information. While I understand, if we added handling for every malformed input things would quickly become a maintenance burden, in this case you can configure the gateway upstream to return the correct value:

https://azure.microsoft.com/en-us/blog/rewrite-http-headers-with-azure-application-gateway/

**Comment by AbdulrahmanAJ** [comment]
This issue in not solvable in azure app service, since you don't have access over the gateway

**Comment by debugger22** [comment]
@AbdulrahmanAJ Were you able to fix it with Azure app service?

**Comment by CKGrafico** [comment]
Hello for the ones using Azure Container Apps this solved all my problems :)

<img width="714" height="966" alt="Image" src="https://github.com/user-attachments/assets/bd843dc0-858b-4c1b-ac41-3d76d5499d4d" />

Where the startup command is something like:
```
node -e http=require('http');cp=require('child_process');T=3010;L=parseInt(process.env.PORT||3000,10);clean=v=>v?v.split(',').map(x=>x.trim().split(':')[0]).filter(Boolean).join(','):v;s=http.createServer((req,res)=>{h={...req.headers};if(h['x-forwarded-for'])h['x-forwarded-for']=clean(h['x-forwarded-for']);p=http.request({hostname:'127.0.0.1',port:T,path:req.url,method:req.method,headers:h},pr=>{res.writeHead(pr.statusCode,pr.headers);pr.pipe(res)});p.on('error',()=>{res.statusCode=502;res.end('BadGateway')});req.pipe(p)});s.listen(L,()=>{console.log('proxy->'+L+'->'+T)});cp.spawn('node',['./build/server/index.js'],{stdio:'inherit',env:Object.assign({},process.env,{PORT:String(T)})})
```

**Comment by CKGrafico** [comment]
My previous answer has problems with websockets and I was not able to make a better command to support them then.. I've made another image to use as gateway `https://hub.docker.com/r/itgplainconcepts/outline-azure-gateway` this should be your main in port 8080 and outline in sidecar in port 3000

BTW I was forced (I hope temporary to also create an outline copy `https://hub.docker.com/r/itgplainconcepts/outline` but just because the current manifest (or how the images are build) is not compatible with current azure state I'm building the images using this script.

```
# Outline Azure Gateway - Build and Push Script
# Author: itgplainconcepts

$GATEWAY_IMAGE = "itgplainconcepts/outline-azure-gateway"
$OUTLINE_IMAGE = "itgplainconcepts/outline"
$GATEWAY_VERSION = "1.1.0"
$OUTLINE_VERSION = "1.0.1"

Write-Host "Building Outline Azure Gateway..." -ForegroundColor Green

# Build the gateway image using legacy builder (avoids manifest issues with Azure)
$env:DOCKER_BUILDKIT = 0
docker build -f Dockerfile.proxy -t "${GATEWAY_IMAGE}:$GATEWAY_VERSION" -t "${GATEWAY_IMAGE}:latest" .

if ($LASTEXITCODE -ne 0) {
    Write-Host "Gateway build failed!" -ForegroundColor Red
    exit 1
}

Write-Host "Gateway image built successfully!" -ForegroundColor Green

Write-Host ""
Write-Host "Building Outline image..." -ForegroundColor Green

# Build the outline image using legacy builder (avoids manifest issues with Azure)
docker build -f Dockerfile.outline -t "${OUTLINE_IMAGE}:$OUTLINE_VERSION" -t "${OUTLINE_IMAGE}:latest" .

if ($LASTEXITCODE -ne 0) {
    Write-Host "Outline build failed!" -ForegroundColor Red
    exit 1
}

Write-Host "Outline image built successfully!" -ForegroundColor Green

# Show image info
Write-Host ""
Write-Host "Built images:" -ForegroundColor Cyan
docker images | Select-String "itgplainconcepts"

Write-Host ""
Write-Host "Logging into Docker Hub..." -ForegroundColor Yellow
docker login

if ($LASTEXITCODE -ne 0) {
    Write-Host "Docker login failed!" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Pushing images to Docker Hub..." -ForegroundColor Yellow

Write-Host "Pushing gateway version $GATEWAY_VERSION..." -ForegroundColor Cyan
docker push "${GATEWAY_IMAGE}:$GATEWAY_VERSION"

if ($LASTEXITCODE -ne 0) {
    Write-Host "Push failed for gateway version $GATEWAY_VERSION!" -ForegroundColor Red
    exit 1
}

Write-Host "Pushing gateway latest..." -ForegroundColor Cyan
docker push "${GATEWAY_IMAGE}:latest"

if ($LASTEXITCODE -ne 0) {
    Write-Host "Push failed for gateway latest!" -ForegroundColor Red
    exit 1
}

Write-Host "Pushing outline version $OUTLINE_VERSION..." -ForegroundColor Cyan
docker push "${OUTLINE_IMAGE}:$OUTLINE_VERSION"

if ($LASTEXITCODE -ne 0) {
    Write-Host "Push failed for outline version $OUTLINE_VERSION!" -ForegroundColor Red
    exit 1
}

Write-Host "Pushing outline latest..." -ForegroundColor Cyan
docker push "${OUTLINE_IMAGE}:latest"

if ($LASTEXITCODE -ne 0) {
    Write-Host "Push failed for outline latest!" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Successfully published both images to Docker Hub!" -ForegroundColor Green
Write-Host "Your images are now available at:" -ForegroundColor Yellow
Write-Host "  Gateway: https://hub.docker.com/r/itgplainconcepts/outline-azure-gateway" -ForegroundColor Cyan
Write-Host "  Outline: https://hub.docker.com/r/itgplainconcepts/outline" -ForegroundColor Cyan
Write-Host ""
Write-Host "To use your images:" -ForegroundColor Yellow
Write-Host "  docker pull ${GATEWAY_IMAGE}:latest" -ForegroundColor Cyan
Write-Host "  docker pull ${OUTLINE_IMAGE}:latest" -ForegroundColor Cyan
```

**Comment by ashleysommer** [comment]
@CKGrafico Thanks for your contributions to this thread. I'm tackling this same issue myself.
I'd like to be able to deploy on a "real" host like Cloudflare or Vercel or Linode, my workplace requires us to use Azure App Service for hosting, so that's what I'm trying to use.
Azure App Service passes the "real" forwarded IP (without the appended port) using the "X-Client-IP" header.
This is supported in Outline's Koa framework (using the "app.proxyIpHeader" config variable), however Outline does not provide a mechanism to set it.

> "I've made another image to use as gateway"

Can you give more details about how you created it? Is it a simple nginx server that modifies the header and forwards the request? Or something different?

> BTW I was forced (I hope temporary to also create an outline copy https://hub.docker.com/r/itgplainconcepts/outline but just because the current manifest (or how the images are build) is not compatible with current azure state

Can you provide more details about that please? I've got the official Outline image deployed on Azure App Service without issue, is it only a problem on Azure Container Apps?

**Comment by CKGrafico** [comment]
> [@CKGrafico](https://github.com/CKGrafico) Thanks for your contributions to this thread. I'm tackling this same issue myself. I'd like to be able to deploy on a "real" host like Cloudflare or Vercel or Linode, my workplace requires us to use Azure App Service for hosting, so that's what I'm trying to use. Azure App Service passes the "real" forwarded IP (without the appended port) using the "X-Client-IP" header. This is supported in Outline's Koa framework (using the "app.proxyIpHeader" config variable), however Outline does not provide a mechanism to set it.
> 
> > "I've made another image to use as gateway"
> 
> Can you give more details about how you created it? Is it a simple nginx server that modifies the header and forwards the request? Or something different?
> 
> > BTW I was forced (I hope temporary to also create an outline copy https://hub.docker.com/r/itgplainconcepts/outline but just because the current manifest (or how the images are build) is not compatible with current azure state
> 
> Can you provide more details about that please? I've got the official Outline image deployed on Azure App Service without issue, is it only a problem on Azure Container Apps?

probably my explanation was not so good just use the script on my previous comment to generate your custom image and publish that custom image

**Comment by ashleysommer** [comment]
@CKGrafico Can you please link to the codebase you use to generate the image at https://hub.docker.com/r/itgplainconcepts/outline-azure-gateway?

**Comment by CKGrafico** [comment]
> @CKGrafico Can you please link to the codebase you use to generate the image at https://hub.docker.com/r/itgplainconcepts/outline-azure-gateway?
> 

There is no specific code base just running this powershell every time we want to update to a new version https://github.com/outline/outline/issues/6083#issuecomment-3500016337

And add both images to one Azure web app as is possible to add multiple docker images there (exposing only one to the internet)

**Comment by ashleysommer** [comment]
@CKGrafico Yes I understand that.
What I mean, is that Powershell script refers to a file named "Dockerfile.proxy", that is what is used to build the gateway image, it is not part of the standard Outline codebase. Where can I find that file?

**Comment by CKGrafico** [comment]
@ashleysommer sorry this is a super generic proxy you can use others.
Dockerfile.proxy
```
FROM node:18-alpine

# Image metadata
LABEL maintainer="itgplainconcepts"
LABEL description="Azure Gateway Proxy for Outline Wiki with WebSocket support and x-forwarded-for header cleaning"
LABEL version="1.1.0"

# Set working directory
WORKDIR /app

# Copy the proxy file
COPY proxy.js .

# Expose port
EXPOSE 8080

# Default environment variables
ENV PORT=8080

# Default command
CMD ["node", "proxy.js"]
```

proxy.js
```
const http = require('http');

const TARGET_PORT = 3000;
const LISTEN_PORT = parseInt(process.env.PORT || '8080', 10);
const TARGET_HOST = '127.0.0.1';
const XFF_HEADER = 'x-forwarded-for';
const CRLF = '\r\n';

// Function to clean x-forwarded-for header
const cleanXForwardedFor = (value) => {
    return value ? value.split(',').map(x => x.trim().split(':')[0]).filter(Boolean).join(',') : value;
};

// Create HTTP server with proxy logic
const server = http.createServer((req, res) => {
    const headers = { ...req.headers };
    
    // Only clean x-forwarded-for header if present
    if (headers[XFF_HEADER]) {
        headers[XFF_HEADER] = cleanXForwardedFor(headers[XFF_HEADER]);
    }
    
    // Create proxy request to Outline
    const proxyReq = http.request({
        hostname: TARGET_HOST,
        port: TARGET_PORT,
        path: req.url,
        method: req.method,
        headers: headers
    }, (proxyRes) => {
        res.writeHead(proxyRes.statusCode, proxyRes.headers);
        proxyRes.pipe(res);
    });
    
    proxyReq.on('error', () => {
        res.statusCode = 502;
        res.end('Bad Gateway');
    });
    
    req.pipe(proxyReq);
});

// Handle WebSocket upgrades
server.on('upgrade', (req, socket, head) => {
    const headers = { ...req.headers };
    
    // Only clean x-forwarded-for header if present
    if (headers[XFF_HEADER]) {
        headers[XFF_HEADER] = cleanXForwardedFor(headers[XFF_HEADER]);
    }
    
    // Create proxy request for WebSocket upgrade
    const proxyReq = http.request({
        hostname: TARGET_HOST,
        port: TARGET_PORT,
        path: req.url,
        method: req.method,
        headers: headers
    });
    
    proxyReq.on('upgrade', (proxyRes, proxySocket, proxyHead) => {
        // Send the 101 Switching Protocols response
        socket.write('HTTP/1.1 101 Switching Protocols' + CRLF);
        
        // Send response headers
        Object.keys(proxyRes.headers).forEach(key => {
            socket.write(key + ': ' + proxyRes.headers[key] + CRLF);
        });
        
        socket.write(CRLF);
        
        // Forward any initial data
        if (proxyHead.length > 0) {
            socket.write(proxyHead);
        }
        
        // Pipe data between client and target
        proxySocket.pipe(socket);
        socket.pipe(proxySocket);
    });
    
    proxyReq.on('error', (err) => {
        console.error('WebSocket proxy error:', err);
        socket.end();
    });
    
    proxyReq.end();
});

// Start the proxy server
server.listen(LISTEN_PORT, () => {
    console.log(`Proxy server listening on port ${LISTEN_PORT}, forwarding to ${TARGET_HOST}:${TARGET_PORT}`);
    console.log('Proxy is ready to forward requests to Outline container');
});

// Graceful shutdown
process.on('SIGTERM', () => {
    console.log('Received SIGTERM, shutting down gracefully...');
    server.close(() => {
        process.exit(0);
    });
});

process.on('SIGINT', () => {
    console.log('Received SIGINT, shutting down gracefully...');
    server.close(() => {
        process.exit(0);
    });
});
```

**Comment by ashleysommer** [comment]
Hi @CKGrafico 
My PR was recently merged: https://github.com/outline/outline/pull/11595
This means in the next release of Outline, you'll not need the Gateway container anymore. This simplifies deployment greatly (and I was having a bunch of reliability issues with the Gateway container crashing regularly).
I'm using my own build of Outline v1.5.0 with that patch applied and its working great.
You simply need to set `PROXY_IP_HEADER` environment to `"X-Client-IP"` or `"X-Real-IP"`, whichever Azure Container Apps uses, and Outline will use that instead, it doesn't have the extra Port component in the string.

In my deployment on "Azure App Service", I use `PROXY_IP_HEADER="X-Client-IP"`.

**Comment by CKGrafico** [comment]
awesome thanks

**Comment by ashleysommer** [comment]
Just updated to official release of Outline v1.6.0 with the above fix, and I can confirm, working as expected!

**Comment by nadiatazi262-tech** [comment]
Tested and looks good
