### ISSUE TITLE
Self-Hosted Grist iFrame Authentication Issue

### ISSUE THREAD

**Issue by tebriel** [outline/outline#6088]
I'm self-hosting both Outline and Grist, they are both set up behind Microsoft Entra (formerly Active Directory).
If I embed a Grist link into an Outline Page, it asks me to authenticate to Grist, which makes sense.

Microsoft Entra does not allow login windows embedded in an iFrame, so this results in the following error:

> Firefox Can’t Open This Page

> To protect your security, login.microsoftonline.com will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.

I've validated this isn't only with Firefox. I'm unsure how to proceed, if I choose the option to open a new window, I can log in and view the embed but it doesn't update the Outline authentication.

I do have my Grist URL set in Outline's settings.

Is this the responsibility of Outline or of Grist to handle auth when embedded?

**To Reproduce**
1. Self host Outline and Grist
2. Use Microsoft AD Auth for Outline and AD SAML for Grist
3. Paste a link to a private Grist in an Outline Document
4. Click to authenticate
5. See Error

**Expected behavior**

A popup window for authentication to Azure instead of embedded in an iframe.

**Screenshots**
![example authentication request](https://github.com/outline/outline/assets/821688/ac2ebd40-67ad-4a88-a997-5b52a013b915)

![example error](https://github.com/outline/outline/assets/821688/4a9db4a0-f62a-4b2e-b3f1-99190ac766cd)

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.72.2 6f234bef1156910e0f2964702835f900d3e115af

**Workaround**

If your grist has public access set, you can embed it without hitting the authentication, but now your grist is public to anyone with the URL.

**Comment by tommoor** [comment]
Most likely firefox is blocking third party cookies, you can probably add an exception for the domain that Outline is hosted on to enable the iframe to read the auth cookie and know that you're logged in.

As this is a browser limitation there isn't anything that we can do on the platform side.

**Comment by tebriel** [comment]
> Most likely firefox is blocking third party cookies, you can probably add an exception for the domain that Outline is hosted on to enable the iframe to read the auth cookie and know that you're logged in.
> 
> As this is a browser limitation there isn't anything that we can do on the platform side.

@tommoor thanks for the quick response. As I noted, this happens in other browsers, specifically I tested in Chrome and Safari after Firefox. Microsoft disallows loading the login workflow in an iFrame to prevent clickjacking.

If you establish a grist session the embed works, so for anyone who might run into this, the solution is to log in to grist and refresh outline, the iFrame will use your session and show the embed, however you cannot ever use the button to click to log in because Microsoft prevents the the login workflow from loading within an iFrame for security reasons. Additionally your grist and outline subdomains must be in the same domain so that the session cookies can be shared across the two.

**Comment by saheljalal** [comment]
Having the same issue self hosted v0.87.3 with GitHub integration and embedding. Not sure how to fix this but would be nice if it was working out of the box.

<img width="837" height="627" alt="Image" src="https://github.com/user-attachments/assets/26e467cf-8749-4444-aabb-97ea1b8b885f" />

<img width="546" height="328" alt="Image" src="https://github.com/user-attachments/assets/fc3dd678-3c4b-41bb-addb-85aa4ac99d05" />

**Comment by tommoor** [comment]
It is impossible to fix, this is a security restriction applied from GitHub's side. Instead use the built in "Mention" functionality to embed GitHub links:
https://www.getoutline.com/changelog/issue-integrations

**Comment by saheljalal** [comment]
Unfortunately not seeing an option for "Mention", only "Keep as link" and "Embed".

<img width="700" height="217" alt="Image" src="https://github.com/user-attachments/assets/f16e4dbc-4128-4a32-8ea2-799bea59ca91" />

**Comment by tommoor** [comment]
You would need to use one of the repositories that you have given access to through the integration, I'm sure.

**Comment by saheljalal** [comment]
Very cool, that works now. I was under the impression that public links would work as well. Maybe a feature enhancement to GH integration. Thanks so much for your help!

**Comment by tommoor** [comment]
I agree, it feels like they _should_
