### ISSUE TITLE
Export collection to MD fails to export all docs

### ISSUE THREAD

**Issue by ovizii** [outline/outline#6094]
Export collection to MD fails to export all docs

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to collection
2. Click on export
3. Select  Markdown and include attachments
4. Get notification about export completion
5. Download and open exported zip file
6. Notice missing documents

**Expected behavior**
I expect an export of a collection to contain all documents and images

**Screenshots**

Exporting this:
![image](https://github.com/outline/outline/assets/837902/42053196-1597-409e-95d1-aa1725c33063)

Results:
![image](https://github.com/outline/outline/assets/837902/d3d45000-0fb4-42b4-9af7-98b1003dbeb5)

![image](https://github.com/outline/outline/assets/837902/4abb3d13-1a16-4c3d-896e-20f41bb95a92)

![image](https://github.com/outline/outline/assets/837902/e4422500-25c6-4d48-87a8-f0c1ec21b204)

![image](https://github.com/outline/outline/assets/837902/1bf2fd2d-00b6-4340-b4de-680776c91ddb)

![image](https://github.com/outline/outline/assets/837902/690a2df5-1a2b-4251-978a-1680b8c62501)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.72.2

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Chrome
 - Version 118.0.5993.118

**Comment by MitPitt** [comment]
This is still a problem. UI says that export is 600MB, meanwhile when I download the zip file, it's randomly between 18MB and 25MB. Obviously having missing files. Thankfully, json export seems to work fine.
