### ISSUE TITLE
Airtable regex issue

### ISSUE THREAD

**Issue by usfwc** [outline/outline#6095]
Airtable seems to have begun requiring appId and shareId in newly created embed links. I've tested this using my own airtable account, cloning existing views and creating new links; I have confirmed that new share links cannot be viewed using the https://airtable.com/embed/shareId structure, and must follow https://airtable.com/embed/appId/shareId.

In the airtable embed regex function, I suggest changing app.* from a non-capturing group to capturing group, creating a new variable appId, and adding it to the frame src url.

In case some users are providing share links without appId, it may be useful to make this bit conditional, based on the existence of appId in the provided airtable share url. I expect this will become less necessary in time, as airtable rolls out this change.

Thanks!

--

**To Reproduce**
1. Find an active airtable embed in an existing outline installation
2. Go to the source base in airtable, duplicate the view, re-share the view with the same permissions
3. Attempt to embed the new airtable share link
4. Confirm that link cannot embed (and that previous link continues to function)

**Expected behavior**
Any airtable shared view link provided by airtable will properly be embedded in an outline page (via iframely)

**Screenshots**
<img width="771" alt="Screen Shot 2023-10-30 at 9 32 24 AM" src="https://github.com/outline/outline/assets/137528001/39efe3ae-749a-45cb-a719-b23623de6c27">

**Outline:**
- Install: self hosted
- Version: 0.72.2

**Comment by crawfordmorgan** [comment]
Oops. Meant to post this bug from my personal account. Commenting to follow more easily.
