### ISSUE TITLE
Page menu too large for mobile display

### ISSUE THREAD

**Issue by AverageMarcus** [outline/outline#6100]
When opening a pages menu it is possible that it is too large for the screen and is not scrollable. This leads to some items at the top being inaccessible and it not being possible to close the menu again. 

**To Reproduce**
1. While using a mobile device
2. Go to any page
3. Click on the top right menu icon
4. See the menu appear, filling the screen and not being scrollable

**Expected behavior**
The menu should appear below the menu button icon (so it can be closed again) and the items should be scrollable if it is larger than the available display space. 

**Screenshots**
![image](https://github.com/outline/outline/assets/3384072/4505677e-0709-409d-bf65-7454349f6dce)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.72.2

**Desktop (please complete the following information):**

**Mobile (please complete the following information):**
 - Device: iPhone 15 Pro Max
 - OS: iOS17.1
 - Browser safari (as a pwa)

**Comment by tommoor** [comment]
Thanks, this has already been addressed on `main` – a fix will be in the next release.

**Comment by AverageMarcus** [comment]
Oh fantastic news! Thank you. Sorry for the noise. I checked closed issues but didn't see anything that seemed to match.
