### ISSUE TITLE
TeX: \neq gets rendered as newline in public view

### ISSUE THREAD

**Issue by libnewton** [outline/outline#6106]
**To Reproduce**
1. Create doc
2. Add some text, add math in between like `foo bar $$1 \neq 2$$ foo`
3. publish
4. view doc with the public link
5. the TeX is broken as the \\neq is interpreted as a line break

**Expected behavior**
the TeX is rendered correctly and the viewer is not inserting a newline in the middle of it

**Screenshots**
N/A

**Outline:**
- Install: self-hosted
- Version: v0.72.2

**Desktop:**
 - OS: Linux
 - Browser: Chromium, Firefox
 - Version: N/A

**Mobile:**
 - Device: Not tested
 - OS: N/A
 - Browser: N/A

**Comment by tommoor** [comment]
fixed by #5553
