### ISSUE TITLE
Account deletion not possible if emails are disabled

### ISSUE THREAD

**Issue by BlueIce** [outline/outline#6107]
It is not possible to delete my account if the instance has emails disabled.

I think the problem is that the delete button is disabled, because the form is not valid.
See https://github.com/outline/outline/blob/1d6ef2e1b3140231abf7d422e8799c8e873d95b8/app/scenes/UserDelete.tsx#L97
And the form validation is tied to the confirmation code which is irrelevant when emails are disabled. 

**To Reproduce**
1. Login to an outline instance with emails disabled
2. Go to 'Preferences'
3. Click on 'Delete account'
4. Confirmation pop-up is shown
5. 'Delete my account' button is disabled

**Expected behavior**
The 'Delete my account' button is clickable and I can delete my account.

**Outline:**
- Install: self hosted
- Version: v0.72.2

**Comment by tommoor** [comment]
If the button is disabled then you're either running in development mode and should set `NODE_ENV=production` or `SMTP_HOST` has a value set.

**Comment by BlueIce** [comment]
The configuration is `NODE_ENV=production` and `SMTP_HOST=` (no value set).

I was trying to find a way to delete an account without needing to configure an email server. This seems to be not possible currently.
