### ISSUE TITLE
there is no ways to stop the processing when the exports fail

### ISSUE THREAD

**Issue by sweeticetea** [outline/outline#6109]
**To Reproduce**
1. deleted the picture from server folder, and the wiki file which contained the picture left a blank picture.
2. tried to export html/json
3. the web kept rolling forever
4. checked the log from docker, said cannot find the link to the picture i deleted on server
5. update from 0.72.1 to 0.72.2,but still rolling

**Expected behavior**
ways to stop the exports

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
![33](https://github.com/outline/outline/assets/54834868/1c79538b-c45b-42b5-9eb3-8bc228208ea2)
![11](https://github.com/outline/outline/assets/54834868/115a39e8-ab7c-4acd-8a75-e65e20879416)
![22](https://github.com/outline/outline/assets/54834868/e697771c-49b3-4532-aa42-c1fe3ab597a9)

**Outline (please complete the following information):**
- Install:self hosted
- Version:  0.72.2

**Comment by tommoor** [comment]
It will fail after a number of retries

**Comment by sweeticetea** [comment]
@tommoor thanks for the comment! but i find it still rolling now, for 4 and 5 hours. is there any way to stop it manually? I tried to restart the docker, didnt work.

**Comment by tommoor** [comment]
Is it actually processing on the server or just animation in the UI?

**Comment by sweeticetea** [comment]
@tommoor thanks for the comment! I double check the logs, the error in the Screenshots didnt show up any more. so I assume now just animation in the UI? Thanks for your help. Is there some ways to remove that?

**Comment by sweeticetea** [comment]
@tommoor yeah，my bad😉
Thanks again! btw, have you consider that delete the pic from the server while I delete it through the web?I dont have much developing experience, does it have something hard to overcome?

**Comment by tommoor** [comment]
Files are automatically deleted from the server once all references are deleted in documents and all of those documents are permanently deleted from the trash. Before that they must be retained as they're available in the document history.

**Comment by sweeticetea** [comment]
@tommoor not files, just pictures.take new feature Local file system for instance. when i upload a picture and try to delete it through"Delete image"icon, it only disappears from the web and remains on the server in the `uploads` folder
![1](https://github.com/outline/outline/assets/54834868/db5ffc1f-f9ab-4080-a98b-d9757c2ee346)

**Comment by tommoor** [comment]
Yes, the rules are as I explained above.

**Comment by sweeticetea** [comment]
@tommoor thanks for the comment. I upload a picture to a file, and I delete the file permanently also in the trash, but the picture still in the `uploads`  file. logs doesnt show any error like permission deny. the file and picture are just upload for test so there should be no other references.

**Comment by tommoor** [comment]
Unfortunately I'm unable to reproduce the file being left, it is correctly cleared here. You should see a `DeleteAttachmentTask` running in the logs after the document is permanently deleted out the trash.

**Comment by sweeticetea** [comment]
> You can remove the record in the database, other than that no as we didn't take into account files randomly being deleted from the storage 😉

record how to remove it from database incase someone has the same issue:
```bash
docker exec -it <postgres container id> psql -U user -d outline
SELECT * FROM attachments; #remove the record which the pic had been remove already
SELECT * FROM file_operations WHERE type = 'export'; #you should see the state remains creating, update it to complete. and you will be find
```
