### ISSUE TITLE
Deleted Collections is s 404 and shows incorrect User

### ISSUE THREAD

**Issue by prologic** [outline/outline#6111]
Really sorry but I cannot reproduce this as I don't yet fully understand how this happened.

One of our internal users did "something", and one of our collections is just gone / deleted. I _assume_ they accidently deleted the collection, I can't see any other way to reproduce this.

There are two issues I see here:

1. The reported users is the current user logged in viewing the deleted pages. There doesn't appear to be a way to see "who" actually deleted the collection. This is confusing and misleading.
2. The "Deleted Collections" link currently 404's so resorting the deleted collection seems to be impossible?

<img width="1148" alt="Screenshot 2023-11-04 at 08 10 52" src="https://github.com/outline/outline/assets/1290234/0e760c8f-3547-4cfc-bd58-9b5d9c3b26a8">

<img width="1712" alt="Screenshot 2023-11-04 at 08 11 02" src="https://github.com/outline/outline/assets/1290234/987386d9-5912-40dd-88df-5f2ec5a78127">

**Comment by prologic** [comment]
The most immediate question I have right now, is:

> How do I restore this accidently deleted collection?

More importantly as well, how do we lock collections from accidental mass deletion? 🙏

**Comment by tommoor** [comment]
I think what's happening here is that the last user that updated the document is displayed in the banner. If a document is individually deleted then this will be correct, but if the containing collection is deleted then that "updatedBy" value on each individual document is not updated.

> How do I restore this accidently deleted collection?

You can't, the action is permanant – but you can restore each document individually while they still exist in trash or restore from a database backup.

> how do we lock collections from accidental mass deletion?

You can ensure that only select users have admin rights in the collection.

**Comment by prologic** [comment]
I restored the collection and all documents by poking at the database.

Can we fix the bugs and address improvements I've identified here? Specifically I'd like to see:

- A way to protect documents and collections
- A way to undelete collections from the UI which currently 404's
- The correct use shown in this case, or who deleted the underlying collection.

As an aside a UI for displaying the events table (audit log) would also be super helpful! 🙏

**Comment by tommoor** [comment]
> A way to protect documents and collections

This exists in user roles as mentioned above, you have control over who can delete a collection.

> A way to undelete collections from the UI which currently 404's

Existing tracking issue here: https://github.com/outline/outline/issues/3141

> The correct use shown in this case, or who deleted the underlying collection.

Fix here: https://github.com/outline/outline/pull/6116

> A UI for displaying the events table (audit log) would also be super helpful

A detailed audit log is one of the features in the [licensed edition](https://www.getoutline.com/pricing).

**Comment by prologic** [comment]
Thank you 🙇‍♂️
