### ISSUE TITLE
Do not show Slack option on settings/security/#sign-in as auth providers in self-hosted

### ISSUE THREAD

**Issue by WillGoGithub** [outline/outline#6132]
When enabling the Slack integration, an error prompt indicates that SLACK_CLIENT_ID and SLACK_CLIENT_SECRET cannot be empty. After providing the necessary values in the environment variables and restarting, the integration becomes functional.

However, the 'Login with Slack' option appears on the login page. Unfortunately, under settings/security#sign-in, there is no option available to disable the Slack sign-in feature.

**To Reproduce**
1. Use Microsoft as first login
2. Setting SLACK_CLIENT_ID and SLACK_CLIENT_SECRET
3. docker-compose up -d (or docker-compose down first)
4. See bug

#4794 #4743 

**Expected behavior**
Can disable Slack sign-in 

**Screenshots**
![image](https://github.com/outline/outline/assets/45837931/558cd257-a716-4daf-a6de-87397b08c522)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.72.2

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: chrome
 - Version: 118

**Comment by tommoor** [comment]
Going to merge this into #1945 as it's currently expected behavior. The Slack search will not work well without also using it for user sign-in as we're not able to link the Slack user with the Outline user.

**Comment by grdederick** [comment]
@WillGoGithub I ran into a similar issue when going through the setup. If you aren't using the slack integration at all, you can leave the auth settings blank if you remove the placeholders in the other Slack integration section too. This will remove the Slack authentication button from the sign in page. https://github.com/outline/outline/blob/854802e1377962ffeb1604edd8dde7f1a667b940/.env.sample#L160
