### ISSUE TITLE
Error when templatizing a document that contains other documents

### ISSUE THREAD

**Issue by andreineacsu** [outline/outline#6149]
**To Reproduce**
1. Go to a document that contains at least 2 other documents;
2. Click on Templatize

**Expected behavior**
Should be able to templatize a document that contains other documents.

**Screenshots**
<img width="732" alt="Screenshot 2023-11-13 at 20 41 26" src="https://github.com/outline/outline/assets/3153007/018bddb9-ab98-47f0-955e-93f85c807de9">

**Outline (please complete the following information):**
- Install: self hosted
- Version: 6f234bef1156910e0f2964702835f900d3e115af

**Comment by tommoor** [comment]
This is addressed on `main` and will be fixed in 0.73.0
