### ISSUE TITLE
cannot comment for the code

### ISSUE THREAD

**Issue by TaoChan1005** [outline/outline#6154]
When I upgrade to 0.73.1, I can not comment on the code block.  When I select the words, the menu would show, but I cannot click.

**Comment by florian-obradovic** [comment]
Same for me.
Browser = current Google Chrome Version 119.0.6045.159:
![CleanShot 2023-11-16 at 10 33 45](https://github.com/outline/outline/assets/57985125/41853ab5-cd38-48ed-99c6-8dd7ef772d8e)

**Comment by flotpg** [comment]
Thanks @tommoor
