### ISSUE TITLE
Backspace should decrease intent

### ISSUE THREAD

**Issue by andreineacsu** [outline/outline#6156]
**To Reproduce**
1. Go to a document
2. Add an unordered list
3. Intent at least 2 levels
4. When on level 2 when hitting backspace the bullet disappears.

**Expected behavior**
When on level 2 hitting backspace should decrease intent to level 1.

**Outline (please complete the following information):**
- Install: self hosted
- Version: 2c870f0dbbad072b70f0fa9941f0f227e47c33f1

**Comment by tommoor** [comment]
This is standard behavior in most text editors, do you have an example that works differently?

- `Tab` increases indent
- `Shift`+`Tab` will decrease indent

**Comment by andreineacsu** [comment]
Yeah, make sense. Thanks for the quick reply. I was comparing with coda.io.

**Comment by tommoor** [comment]
Interesting, will check out the behavior over there!
