### ISSUE TITLE
The command db:create exit code 1 when database already exists

### ISSUE THREAD

**Issue by soundstep** [outline/outline#6157]
The command `yarn sequelize db:create` exit with an exit code of `1` when the database already exists:

```sh
ERROR: database "outline" already exists
error Command failed with exit code 1.
```

I would expect the command to exit with 0 so that the command can be used in any automated system or Docker entrypoint.

For example we have added in out docker entrypoint:

```sh
yarn sequelize db:migrate
```

I would expect to be able to add:

```sh
yarn sequelize db:create
yarn sequelize db:migrate
```

Currently the only solution would be to add `yarn sequelize db:create || true` which would prevent to see real errors with the database creation.

**To Reproduce**
1. Clone the repo https://github.com/outline/outline
2. Run: `yarn install --frozen-lockfile && yarn build`
3. Run: `docker compose up -d`
4. Run `yarn sequelize db:create` twice
5. See "ERROR: database "outline" already exists"

**Expected behavior**
Expecting a message that the database exists with an exit code of `0`.

**Screenshots**
<img width="901" alt="Screenshot 2023-11-15 at 09 39 20" src="https://github.com/outline/outline/assets/133293/f7e48e2f-96eb-412e-bf72-c09628dff903">

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.72.2 using Docker (`FROM outlinewiki/outline:0.72.2`)

**Desktop (please complete the following information):**
 - OS: OSX 13.1 (M1)
 - Browser Chrome
 - Version 119.0.6045.123

**Comment by tommoor** [comment]
It's unwise to add database creation to the docker entrypoint – It's a command that should only ever be ran once and could result in confusing situations particularly in a docker environment where volumes are easily lost.

If you must do so you could attempt to connect to the database and if it fails run the creation command.
