### ISSUE TITLE
User authentication already exists error

### ISSUE THREAD

**Issue by BrunoAFK** [outline/outline#6159]
After changing my password in Authelia, I can't log in to my Outline account, which is a self-hosted version. Authelia is giving the green light, but there is an error within Outline:

`{"error":"User authentication def94844-cc08-417a-936a-3ae21b837f48 already exists for f79c606c-6de9-48fb-9c55-2d8e2a874c5e, tried to assign to c12b68e9-64c7-4f22-85e4-733fcc0912b3","level":"error","message":"Error during authentication","stack":"UnauthorizedError: User authentication def94844-cc08-417a-936a-3ae21b837f48 already exists for f79c606c-6de9-48fb-9c55-2d8e2a874c5e, tried to assign to c12b68e9-64c7-4f22-85e4-733fcc0912b3\n at AuthenticationError (/opt/outline/build/server/errors.js:40:34)\n at accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:121:43)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}`

**To Reproduce**
1. Use Authelia for sign-in.
2. Change the password for Authelia.
3. Try to log back into Outline.

**Expected behavior**
Be able to log in to my Outline account.

**Outline (please complete the following information):**
- Install: selfhosted
- Version: v0.73.1

**Comment by andreyrd** [comment]
Same problem happens if you use Mattermost for sign-in and update your email address.

**Comment by tommoor** [comment]
> Are there any plans to at least allow updating a user's email from the admin UI?

Seems very reasonable, not against it!
