### ISSUE TITLE
Import error from another instance

### ISSUE THREAD

**Issue by erickne** [outline/outline#6161]
Actually, my Outline instance (0.73.0) is running in a docker. But I created another instance in GCP Cloud Run.

The new instance is running fine, with S3 (GCP bucket) properly configured (I've already tested importing images).

I exported the data as markdown and imported it into the new instance. I have tried with JSON, but it throws another error.

![image](https://github.com/outline/outline/assets/1703652/f842a26b-9297-4db2-801d-1b2c6cb899e2)

```
The document "image" is too large to import, please reduce the length and try again
Unexpected token l in JSON at position 0
```

**Considerations**
- Both zip files (json and md) are correctly compressed 
- I deployed using version 0.73.0. Then I tried with 0.72.0. Same errors.

**Expected behavior**
The exported data from initial instance should be imported into the new one.

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 0.73.0 and 0.72.0

**Comment by tommoor** [comment]
Are you able to provide the export file for debugging?

**Comment by tommoor** [comment]
Something is weird about this export, all of the file attachments (images etc) should be contained in an `uploads` folder – this isn't the case according to your output above which would explain the issue.

**Comment by erickne** [comment]
From the UI. Is there another way?

![image](https://github.com/outline/outline/assets/1703652/66696598-8090-4370-8ce8-e3f4ac22a487)

**Comment by tommoor** [comment]
In version 0.73.0, self-hosted yea?

**Comment by erickne** [comment]
Great news @tommoor ! Do you have a date for the release?
