### ISSUE TITLE
`JSONImportTask` should not go through Markdown converter

### ISSUE THREAD

**Issue by tommoor** [outline/outline#6174]
Follow on from https://github.com/outline/outline/pull/5553 – we need to avoid the markdown translation to avoid lossyness going forward.

**Comment by tommoor** [comment]
After #3000 this has gotten more important

**Comment by hmacr** [comment]
@tommoor I'm so sorry I didn't realize this issue was assigned to you 😓

**Comment by tommoor** [comment]
Okay in this case, it was only assigned to me as I thought noone else would be willing to work on it

**Comment by hmacr** [comment]
Got it. I usually pick issues that are unassigned - somehow missed it here.
