### ISSUE TITLE
embed tldraw feature not work when readonly

### ISSUE THREAD

**Issue by seong889** [outline/outline#6188]
tldraw embed function not work on page when readonly mode

this [code](https://github.com/outline/outline/blob/e2ad3f9e73bc8a7a383532660aaf3c6c2a85be63/shared/editor/embeds/Tldraw.tsx#L17C1-L18C1) only accept start with `https://www.tldraw.com/v/` but read only url started `https://www.tldraw.com/r` 

Is this an intended feature? or bugs?

**Comment by Pranav2612000** [comment]
@tommoor I'll like to work on this issue. Seems like a simple fix – updating the regex should fix the issue.

**Comment by Pranav2612000** [comment]
@seong889 On taking a second look, I see that the [regex](https://github.com/outline/outline/blob/e2ad3f9e73bc8a7a383532660aaf3c6c2a85be63/shared/editor/embeds/Tldraw.tsx#L17C1-L18C1) accepts only `https://www.tldraw.com/r` and not the others.
I observed that the snapshot urls start with `https://www.tldraw.com/s`. I'll add support for these.

Can you please let me know what kind of urls start with `https://www.tldraw.com/v`. ( I couldn't find them 😢 ). I'll also add support for these.

**Comment by seong889** [comment]
@Pranav2612000 
![Screenshot_20231124_133745_Samsung Internet](https://github.com/outline/outline/assets/14970965/232395ed-df0a-4fab-90ce-6aa01df0c685)
sorry. cannot change a locale 

- Click share button, and share project menu
  - reload new page
- Click share, check read only and click copy read only url


this url(`https://www.tldraw.com/v/-2VIEZVwrbtdNq0Pmfpf2?viewport=-608%2C-549%2C1998%2C1943&page=page%3AWd7DfjA-igxOMso931W_S`) is result of `copy read only url`

**Comment by Pranav2612000** [comment]
Great. Thank you @seong889 
I've already created a PR will also add support for these urls to it.
