### ISSUE TITLE
Separate the AWS S3 upload endpoint and assets serving endpoint

### ISSUE THREAD

**Issue by syahnur197** [outline/outline#6194]
Currently the app is relying on these env vars, either `AWS_S3_ACCELERATE_URL` or `AWS_S3_UPLOAD_BUCKET_URL` for both serving the assets and upload the assets if we set `FILE_STORAGE` to s3.

If `AWS_S3_ACCELERATE_URL` is set, the app won't use `AWS_S3_UPLOAD_BUCKET_URL` value to upload and serve the assets, as we can see [here](https://github.com/outline/outline/blob/main/server/storage/files/S3Storage.ts#L53C11-L53C28)

Currently, we can set AWS Cloufront URL to `AWS_S3_ACCELERATE_URL` to serve our assets via CDN and to upload if we want "transfer acceleration". 

The problems with this behaviour:-
- we are forced to enable transfer acceleration which might incur [additional charges](https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration.html#:~:text=When%20you%20use%20Transfer%20Acceleration%2C%20additional%20data%20transfer%20charges%20might%20apply.%20For%20more%20information%20about%20pricing%2C). What if we want to upload via normal S3 non CDN endpoint and serve our file via CDN endpoint?
- some S3 compatible service (.e.g., DO Spaces) have not support uploading files via their CDN endpoints thus breaking the integration (which I have confirmed with DO support team)

![image](https://github.com/outline/outline/assets/18722385/12bfd039-d5cd-492b-b6fd-7b7605e42915)

**To Reproduce**
1. Set `AWS_S3_ACCELERATE_URL` to your DO Spaces Bucket CDN endpoint
2. Try to upload an image in your wiki doc, it wouldn't work

**Expected behavior**
Able to upload file to DO Spaces Bucket

**Side note**
- I have tried using S3cmd to upload my file to DO Spaces via DO Spaces CDN endpoint, it doesn't work.
- I tried setting the non CDN endpoint to `AWS_S3_ACCELERATE_URL` env var, it works
- I tried setting the CDN endpoint to `AWS_S3_UPLOAD_BUCKET_URL` env var, it doesn't work
- I haven't tested using AWS S3 + Cloudfront
- I have asked DO to allow us to upload assets via CDN endpoint to make their API consistent with AWS S3, waiting for their response.

**Outline (please complete the following information):**
- Install: self hosted
- Version: 6f234bef1156910e0f2964702835f900d3e115af

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 119.0.6045.159

**Comment by amoralesc** [comment]
I agree that separating these would be great for extending the support to other S3-compatible storage services! Other services like DO only allow uploading from the normal endpoints, but have a dedicated endpoints for serving through CDN.

As a side note, I have managed to successfully configure a DigitalOcean Spaces bucket in Outline with the following configuration (it doesn't use the CDN endpoints).

1. Create the DO Spaces bucket normally
2. In the bucket settings, set the _File Listing_ to `Restricted`
3. Set the _CDN_ as `Enabled` (although technically, I'm not using it) 
4. Set the _CORS Configurations_ to (the order matters!):

    | Order | Origins | Allowed Methods | Allowed Headers |
    | :-: | :-: | :-: | :-: |
    | 1 | https://outline.mydomain.tld | PUT, DELETE, POST | * |
    | 2 | * | GET | | 

5. At Outline, set the env variables to:

- `AWS_REGION` to the [DO region slug](https://docs.digitalocean.com/products/platform/availability-matrix/)
- `AWS_S3_FORCE_PATH_STYLE` to `false`
- `AWS_S3_ACL` to `private`
- `AWS_S3_UPLOAD_BUCKET_URL` to the bucket's origin endpoint (https://mybucket.myregion.digitaloceanspaces.com)
- `AWS_S3_ACCELERATE_URL` same as above (not using the CDN)
- `AWS_S3_UPLOAD_BUCKET_NAME` to my bucket's name
- `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to my generated Spaces API Access Key credentials

**Comment by syahnur197** [comment]
@amoralesc thank you for attempting to replicate the bug on your end. 

There was no issue on my end using the DO Spaces Origin Endpoint when uploading and serving assets in Outline. The issue only happens when I set the CDN Endpoint. Can you please try it on your end?

![image](https://github.com/outline/outline/assets/18722385/51a74ea7-49c3-441e-955c-63f6f16b9eaa)

**Comment by amoralesc** [comment]
@syahnur197 Yes, I can confirm that DO's CDN endpoint doesn't work correctly. The obvious cause is that it's only enabled for GET requests. For future users reading this thread, while this feature request hasn't been solved, define the ACCELERATE env variable to the same origin endpoint.
