### ISSUE TITLE
Mermaid diagrams are not visible in PDF or HTML download. & +1 blank page in PDF download

### ISSUE THREAD

**Issue by fwaegele** [outline/outline#6205]
Either on the website or in the macOS app: 
When downloading a page with a mermaid diagram as PDF or HTML, the diagram is not showing. 

In the PDF download there is also one blank page added. This also happens if there is no diagram. 

When using the system print dialog the diagram is printed. 

- Outline hosted trial version at getoutline.com
- Used web browser Edge: Version 119.0.2151.72 (Official build) (arm64)
- Also Safari: Version 17.0 (19616.1.27.211.1)
- MacOs app version: Version 1.2.2

**Comment by tommoor** [comment]
Thanks for raising, I have a solution for this and should get a fix out within the day

**Comment by fwaegele** [comment]
@tommoor Thanks a lot! It works :) 👍
