### ISSUE TITLE
Images - 3 request for one image

### ISSUE THREAD

**Issue by Meettya** [outline/outline#6211]
Strange behavior for images - every image requested 3 times.

**To Reproduce**
1. Go to https://docs.getoutline.com/s/guide
2. Open Developer panel -> Network
3. Update page
4. See error - 3 times request for one image

**Expected behavior**
Every image should have one request

**Screenshots**
![Screenshot 2023-11-24 195302](https://github.com/outline/outline/assets/154763/6d5ab5e5-4dab-4694-a8da-72cec00e5586)

**Outline (please complete the following information):**
- Install: [getoutline.com]

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Microsoft Edge]
 - Version [120.0.2210.22]

**Comment by Meettya** [comment]
I have some experience in TS, can try to fix.

**Comment by tommoor** [comment]
I'm not seeing the same behavior. Could it be a browser extension?

**Comment by EspadaV8** [comment]
In a private Firefox window the only image I see requested multiple times is  <https://outline-production-attachments.s3-accelerate.amazonaws.com/public/292079f8-0319-4111-bb5b-315e8ae8f14e/2a65015e-9770-4b35-ac9b-907ce0d2c9b6/555601440978_d74a1103147f1f9f506e_192.png>, and that file is referenced 3 times within the document.

As a side note, it looks like Cloudfront isn't correctly caching assets. The images I checked all have response headers show a `Miss from cloudfront`. Etags are being returned though, so locally the file is served from cache, this would just be impacting internal AWS bandwidth costs.

```
HTTP/1.1 200 OK
Content-Type: image/png
Content-Length: 7113
Connection: keep-alive
x-amz-id-2: AYffJNt5t9bMSi134WNsmbs+IOo/avZNvd85mb8dyM5nwKQb/p8pGEoD1EYUtvYVnUwBGLjmuHk=
x-amz-request-id: GGEH7KCV3PJ1ARM8
Date: Mon, 27 Nov 2023 09:54:20 GMT
Last-Modified: Mon, 27 Jun 2022 18:41:18 GMT
ETag: "2506be52510fe23692d1318d9740f6cc"
x-amz-server-side-encryption: AES256
Cache-Control: max-age=31557600
x-amz-version-id: VQ0Xx5CVEK7snIavuQSrC5sRC3FO96TB
Accept-Ranges: bytes
Server: AmazonS3
X-Cache: Miss from cloudfront
Via: 1.1 efb8a232eeb70ecdf19fbd8538dcbf5e.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: MEL52-P2
X-Amz-Cf-Id: _4SSPd7TlfdT0ESDPwsM6zWzB66olHXKaxfh8QidMdEbULgCkVqE1w==
```

**Comment by tommoor** [comment]
You have "Disable cache" enabled in dev tools, so this is only a problem while the inspector is open

<img width="231" alt="image" src="https://github.com/outline/outline/assets/380914/25c7c6f1-6b29-4d1f-b6c5-0662c006ec8b">
