### ISSUE TITLE
Add button to empty trash

### ISSUE THREAD

**Issue by tommoor** [outline/outline#6215]
- This functionality should only be available to admins
- Should include a confirmation prompt
- Needs a new API endpoint so we don't need to make hundreds of API requests

**Comment by hmacr** [comment]
@tommoor I was thinking of solving this issue next.
Are there any other issues with higher priority?

**Comment by tommoor** [comment]
In terms of quicks wins this is a pretty good one!

**Comment by rockingrohit9639** [comment]
Can I work on this issue ? @tommoor

**Comment by tommoor** [comment]
Seems like @hmacr is on it already

**Comment by rockingrohit9639** [comment]
Ohh ok @tommoor
