### ISSUE TITLE
Reordering Documents in Collection

### ISSUE THREAD

**Issue by tommoor** [outline/outline#622]
Requested by Ada Support.

The ability to drag and drop to reorder/move documents in a collection.

Related https://github.com/outline/outline/issues/517

**Comment by tommoor** [comment]
This came recommended and looks great if we restrict the sidebar to just reordering: https://github.com/atlassian/react-beautiful-dnd

To move a document to another parent you'd have to use the existing move functionality, that seems reasonable?

**Comment by jasonquiz** [comment]
Would be great if we could drag it to another Collection. I find myself trying to do this with out thinking about it and then realize it doesn't work.

**Comment by natefduncan** [comment]
My team and I have started using Outline and this is a feature that we'd love to be able to use. I know it's probably low on the priority list, but just wanted to let you know that there's more interest out there.

**Comment by thomasmalley** [comment]
I think #596 might be related somehow ✌🏼️

**Comment by anteprimorac** [comment]
@tommoor any progress on this? If you didn't start building this, I am happy to contribute.

**Comment by tommoor** [comment]
No meaningful progress. The API largely supports the functionality already, there is an `order` property that can be sent. 

Previously I've thought that the sidebar UI component would pretty much need rebuilding from scratch to support drag-and-drop, but that is mainly if we also need to support dragging documents between collections and dragging nested documents to different levels. Whilst that would definitely be nice perhaps the pragmatic path forward is to just add reordering first.

**Comment by anteprimorac** [comment]
I agree we can iterate on this later to add the ability to move the document to a different collection.

Do you have a workflow, like adding special labels and assigning, set in place for managing issues?

**Comment by tommoor** [comment]
I can assign you if you prefer, I'd say 95% of the time folks offer to help but that a PR never materializes – the curse of open source.

**Comment by tommoor** [comment]
This may work, it has no dependencies: 
https://github.com/tajo/react-movable

**Comment by anteprimorac** [comment]
@tommoor I think `react-beautiful-dnd` is a better choice in the long run because it supports moving items between two or more droppable lists.

I have started working on this, actually already have a working prototype for the UI part. I am going to create a WIP PR soon.

**Comment by MatheusRV** [comment]
Are you considering being able to reorder the collections?

**Comment by tommoor** [comment]
Yes, we should allow that for sure, the strategy will have to be different from documents though as the entire document structure for a collection is stored in one place it's easy to do an atomic update – not so much for collections.

An approach using [fractional indexes](https://observablehq.com/@dgreensp/implementing-fractional-indexing) might be sound.

**Comment by aam1r** [comment]
This will be a nice feature addition to organize collections

**Comment by tommoor** [comment]
Thanks everyone, this is now live in production and will be in the next docker release:

![image](https://user-images.githubusercontent.com/380914/103473582-3d3b8c80-4d4f-11eb-93bc-e55b91ebc2b0.png)
