### ISSUE TITLE
Non image files are currupted during zip import

### ISSUE THREAD

**Issue by aponad** [outline/outline#6229]
All non image files imported to Outline are currupted.

**To Reproduce**
1. Create markdown document with non image file as attachment.
2. Archive this directory.
3. Import it to Outline.
4. Download attachement.
6. Try opening it.

**Expected behavior**
Imported files are not modified or corrupted.

**Outline (please complete the following information):**
- Install: self hosted (Docker)
- Version: v0.73.1

Works fine on `v0.72.2` and I was unable to recreate it on `main` branch with node `v18` or `v20` (switch to `yauzl` seems to fix it).

I think this is related to `node-unzipper` library and this issue https://github.com/ZJONSSON/node-unzipper/issues/286#issuecomment-1747739500. 

---

I am able to reproduce this problem in `v0.73.1` `ImportMarkdownZipTask.test.ts` tests:
```js
  it("should not corrupt files in zip", async () => {
    const fileOperation = await buildFileOperation();
    Object.defineProperty(fileOperation, "stream", {
      get() {
        return fs.createReadStream(
          path.resolve(__dirname, "..", "..", "test", "fixtures", "outline-markdown-with-pdf.zip")
        );
      },
    });
    jest.spyOn(FileOperation, "findByPk").mockResolvedValue(fileOperation);

    const props = {
      fileOperationId: fileOperation.id,
    };

    const task = new ImportMarkdownZipTask();
    const response = await task.perform(props);

    expect(response.attachments.size).toEqual(1);

    const attachments = Array.from(response.attachments.values());
    const attachment = attachments.find((att) =>
      att.key.endsWith("license.pdf")
    );

    attachment?.buffer.then((buffer) => {
      const md5 = createHash("md5");
      md5.write(buffer);
      const hash = md5.digest().toString("hex");
      expect(hash).toEqual("bda05f729bb1cfc11a08576d738b5add");
    });
  }, 10000);
```

Fixture: [outline-markdown-with-pdf.zip](https://github.com/outline/outline/files/13498373/outline-markdown-with-pdf.zip)

**Comment by tommoor** [comment]
Hi @aponad thanks for filing – I was able to confirm with your test that this is already fixed on main (we removed `unzipper` due to similar issues elsewhere).
