### ISSUE TITLE
Direct links to comments jump to the wrong comment

### ISSUE THREAD

**Issue by jannschu** [outline/outline#6231]
The button "Open thread" shown in notification mails or link copied from the "Copy link" button on comments do jump to the wrong comment.

**To Reproduce**
1. Create two comments on two different places in a document.
2. Click on the "…" link on the second/lower comment and press "Copy link".
3. Open the link in the browser.
4. The wrong comment is highlighted, often the first one but for longer documents also other comments are highlighted and jumped to.

We noticed this when we tried to use the "Open Thread" link in the notification mails.

This is probably a different issue, but then searching with STRG+F for the comment opens the Outline search bar which seems not to cover the comments.

**Expected behavior**
The comment the notification refers to or that was used to copy the link should be jumped to.

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.73.1

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 120.0

**Comment by tommoor** [comment]
I haven't been able to reproduce this issue so far unfortunately

**Comment by tommoor** [comment]
Found an issue with scrolling to the comment, perhaps this is what you were referring to here
