### ISSUE TITLE
Sidebar does not collapse when moving mouse in from another window

### ISSUE THREAD

**Issue by ssenior45** [outline/outline#6234]
**To Reproduce**

1. Make sure the side bar is collapsed and not pinned
2. Lose the focus on the Outline window by clicking on another application
3. Move the mouse in from the left such that the sidebar comes into view
4. Keep moving the mouse to the right out of the sidebar
5. Notice that the sidebar does not collapse

So this is becoming an annoyance for me as I have Outline open in its own window as a Chrome PWA and I'm constantly going into Outline to grab text to copy and paste into my terminal. The sidebar not collapsing is making this workflow a pain.

**Expected behavior**

Once you move out of the sidebar content it should always collapse.

**Screenshots**

If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**

- Install: self hosted
- Version: 0.73.1

**Desktop (please complete the following information):**

 - OS: MacOS Sonoma 14.1.1 (23B81)
 - Browser: Chrome
 - Version: Version 119.0.6045.159 (Official Build) (arm64)

**Comment by tommoor** [comment]
Closing as unfixable for now I'm afraid
