### ISSUE TITLE
Importing Markdown appears to corrupt images

### ISSUE THREAD

**Issue by routerino** [outline/outline#6239]
Tested with standalone markdown and markdown that has been exported from outline. When importing markdown as a zip file, images get corrupted. It appears that somehow the data at the start of the image gets some how transposed down the file? See binary comparison below.

**To Reproduce**
1. Create a collection with an image (tested with PNG)
2. Export collection as markdown (images are working in the export)
3. Delete collection
4. Import same collection immediately (or any other markdown zip)
5. All images are non-functional, do not render. Downloading the post-import collection shows corrupted files for images.

**Expected behavior**
Functional Images post import

**Screenshots**
Here is a binary comparison of the two images. As seen, the initial data has somehow been pushed further down the image.

![image](https://github.com/outline/outline/assets/45954722/3951794d-bab7-488d-8a90-a7881fe88bbc)

**Outline:**
- Install: Self Hosted
- Version: 0.73.1 (official docker image)

**Desktop:**
 - OS: Windows 11
 - Browser chrome
 - Version 119.0.6045.200

**Comment by tommoor** [comment]
Fixed in https://github.com/outline/outline/pull/6162
