### ISSUE TITLE
The workspace associated with your user is scheduled for deletion and cannot at accessed at this time

### ISSUE THREAD

**Issue by aaronyyan** [outline/outline#6244]
I deleted the all the created workspaces, and then prompted: 
 
“The workspace associated with your user is scheduled for deletion and cannot at accessed at this time.”
 
Now I have deleted the all workspace, but I can still see it.

![image](https://github.com/outline/outline/assets/39476555/60f0b390-0f55-47e3-8a0d-75351f9531a7)

Is there any solution?

**Comment by tommoor** [comment]
I would probably just create a fresh database at that point
