### ISSUE TITLE
outline user clicks logout, but in fact there is no logout on keycloak

### ISSUE THREAD

**Issue by back920096** [outline/outline#6249]
outline user clicks logout, but in fact there is no logout on keycloak. As a result, when logging in again, the user will skip entering the password and log in directly. There is no way to log out and switch to another user.

![image](https://github.com/outline/outline/assets/28179698/5889bfa2-8ff2-4b13-854f-77a8e11a685d)
![image](https://github.com/outline/outline/assets/28179698/3d6c4544-bc36-4c8c-8db6-cd8bd3fc809e)

**Comment by tommoor** [comment]
This one is filed here https://github.com/outline/outline/issues/3954
