### ISSUE TITLE
Visual issue when publicly sharing a file with /notice or /warning inside a bullet list

### ISSUE THREAD

**Issue by Drusy** [outline/outline#6250]
The publicly shared HTML page is shrinked or visually unstable when the content of the page contain an notice/warning tag  inside a bullet list.

**To Reproduce**
1. Create a document using a bullet list items
2. Inside the bullet list, add a /notice or a /warning tag
3. Share the document using a public link
4. All the content written after step 2. is now shown or visually broken
    5.a If there are two notice/warning tags, the content is now shown
    5.b If there is only one notice, the content is visually broken 

**Expected behavior**
The exact same page using the public link or the editor.

**Screenshots**

1. Only one tag

Inside the editor:
![Screenshot 2023-12-05 at 16 54 17](https://github.com/outline/outline/assets/2833240/87d61ab5-9cb5-46da-9d38-4f708c32bb7e)

In the public page:
![Screenshot 2023-12-05 at 16 54 11](https://github.com/outline/outline/assets/2833240/e979a7ad-00a3-440d-9cd6-50b7208a75b6)

2. Two tags

Inside the editor:
![Screenshot 2023-12-05 at 16 58 45](https://github.com/outline/outline/assets/2833240/884646cc-508a-427f-aff9-0b09f34dfc85)

In the public page:
![Screenshot 2023-12-05 at 16 58 47](https://github.com/outline/outline/assets/2833240/f8b9f7d0-57bf-4716-bbe8-91f1811926bd)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.73.1 - https://github.com/outline/outline/commit/2c870f0dbbad072b70f0fa9941f0f227e47c33f1

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 119.0.6045.199

**Comment by tommoor** [comment]
Will be fixed by #3000
