### ISSUE TITLE
Fail to upgrade to v0.74.0 with error "Migration 20231120074257-add-column-id-to-user-permissions.js (up) failed: Original error: permission denied to create extension 'uuid-ossp'"

### ISSUE THREAD

**Issue by nh4ttruong** [outline/outline#6259]
Fail to upgrade from v0.73.1 to v0.74.0 with message error:
```
yarn run v1.22.19
$ node ./build/server/index.js
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
(node:28) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
{"label":"lifecycle","level":"info","message":"\nIs your team enjoying Outline? Consider supporting future development by sponsoring the project:\n\nhttps://github.com/sponsors/outline\n"}
{"label":"database","level":"info","message":"Running migrations…"}
{"label":"database","level":"info","message":"Migrating 20231120074257-add-column-id-to-user-permissions.js…"}
{"level":"warn","message":"Migration 20231120074257-add-column-id-to-user-permissions.js (up) failed: Original error: permission denied to create extension \"uuid-ossp\""}
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

**To Reproduce**
1. Upgrade to v0.74.0
2. Get error `{"level":"warn","message":"Migration 20231120074257-add-column-id-to-user-permissions.js (up) failed: Original error: permission denied to create extension \"uuid-ossp\""}
error Command failed with exit code 1.`

**Outline (please complete the following information):**
- Install: self hosted (Kubernetes Deployment)
- Version: v0.73.1

**Comment by tommoor** [comment]
This a permissions error on your database, you should make sure you have permission to create extensions.

This module is considered “trusted”, that is, it can be installed by non-superusers who have CREATE privilege on the database.

**Comment by nh4ttruong** [comment]
Thank for reference link. I use `postgres:12` image and not config/setup any unusual permissions on it. I found that [the documentation for version 12](https://www.postgresql.org/docs/12/uuid-ossp.html) not mention the quote until version 13.

**Comment by tommoor** [comment]
Great, thankyou – good to know!

**Comment by cuong-tran** [comment]
How to fix this, guys?

**Comment by cuong-tran** [comment]
in my case, postgres is running inside docker, and that docker is configured to have `POSTGRES_USER: postgres`. But strangely postgres is not a SUPERUSER, instead it was `rdsadmin_user`.
So I had to access to docker's shell, open postgres with `psql` command, then switch to `rdsadmin_user` (luckily it doesn't require a password) then run the SQL command to create the needed extension: `CREATE EXTENSION IF NOT EXISTS "uuid-ossp";` manually

**Comment by cuong-tran** [comment]
I'm using this: `image: docker.io/postgres:15.4`

**Comment by cuong-tran** [comment]
> Just upgrade postgres to at least 13 man!
> 
> > Thank for reference link. I use `postgres:12` image and not config/setup any unusual permissions on it. I found that [the documentation for version 12](https://www.postgresql.org/docs/12/uuid-ossp.html) not mention the quote until version 13.

I'm using this: `docker.io/postgres:15.4`
