### ISSUE TITLE
Public share links

### ISSUE THREAD

**Issue by tommoor** [outline/outline#626]
This would be pretty legit and a good growth tactic. Needs some design love and a little discussion before we start implementation…

- Where do you share from (presume a new icon in top right)?
- How do you revoke share links?
- Can there be multiple share links to the same document?
- Any restrictions on who can share / can it be turned off at team level?

**Comment by jorilallo** [comment]
@tommoor How about having a organization level option to revoke shared documents. This way the team admins will also have access and visibility to shared links. Not sure if document needs multiple, could keep the v1 KISS

**Comment by tommoor** [comment]
In which case a simple share `key` stored on the doc would suffice to bypass auth for that document. We can make it read-only too.

The more complicated thing about this feature is making the rest of the app work without being signed in – you wouldn't have access to see the rest of the collection structure etc so it could look similar to how editing mode does currently for public viewing.
