### ISSUE TITLE
Menu content not visible on mobile

### ISSUE THREAD

**Issue by MDXDave** [outline/outline#6261]
On mobile, the menu content is only visible when pressing on the container. 

**To Reproduce**
1. Open outline on a mobile device 
2. Open the menu
3. See error

**Screenshots**
https://github.com/outline/outline/assets/6099976/29d54fe4-959d-4e55-9cb3-2831d8df4496

**Outline (please complete the following information):**
- Install: self-hosted
- Version: v0.74.0 (Docker) 

**Mobile (please complete the following information):**
 - Device: Samsung Galaxy S23 Ultra 
 - OS: Android 14
 - Browser: Brave (chromium)

**Comment by tommoor** [comment]
Interesting, this doesn't reproduce on iOS.

**Comment by MDXDave** [comment]
Deleting the cache for the website seems to have fixed the issue.
