### ISSUE TITLE
Suspended Login Error Does Not Get Displayed To User Properly

### ISSUE THREAD

**Issue by ruizehung** [outline/outline#6296]
**To Reproduce**
1. Set up Google as OIDC provider following https://github.com/outline/outline/issues/883#issuecomment-1680808066
2. Go to http://127.0.0.1:3000/ (or your Outline url)
3. Suspend an existing user
4. Login as the suspended user
5. See the error message not being displayed properly

**Expected behavior**
The error message should be properly displayed.

**Screenshots**
Current behavior. Notice that the `notice` query parameter in `http://127.0.0.1:3000/?notice=suspended` is `suspended`
<img width="1917" alt="image" src="https://github.com/outline/outline/assets/35753861/21375be6-9d93-416b-a291-26a7cd123d4a">

Expected behavior. The error message should be properly displayed. Looking into the code, the notice should be `user-suspended`
<img width="1917" alt="image" src="https://github.com/outline/outline/assets/35753861/714ed251-8e9f-4ac2-affd-93a201b8fc83">

**Outline (please complete the following information):**
- Install: self hosted
 - Version: `feaadc82768fb8a2e3f713891712f00027940a76`

**Desktop (please complete the following information):**
 - OS: Mac OS 13.6 (22G120)
 - Browser: Arc
 - Version: 13.6 (22G120)
The problem can also be reproduced with 
 - Browser: Chrome
 - Version: Version 120.0.6099.109 (Official Build) (arm64)

I tried looking into the code, I found there are two places that still do `ctx.redirect("/?notice=suspended");`, which should be `ctx.redirect("/?notice=user-suspended");`. See https://github.com/search?q=repo:outline/outline%20notice%3Dsuspended&type=code. I can raise a PR to fix those.

**Comment by tommoor** [comment]
Thanks, I would definitely expect fixing those spots to address the issue! You're saying you tried that? 🤔

**Comment by ruizehung** [comment]
Actually update this line fix the issue

https://github.com/outline/outline/blob/0213221a7c2d91a46bed4ab249e5e3ce7f724d38/server/middlewares/passport.ts#L89

I forgot to update the docker base image in `Dockerfile` so my changes weren't reflected : )
Will raise a PR
