### ISSUE TITLE
Freeze when open document in chromium browser

### ISSUE THREAD

**Issue by matsukky** [outline/outline#6298]
Hello, I have installed outline on my server (via docker), I can connect and access to the welcome page without any problem. But when I try to open a document with a chromium browser, the page freezes and ends up crashing. I've tried clearing the cache several times and trying other chromium browsers, but it didn't work. On the other hand, it worked with safari and firefox, and I could write so i don't think it's a websocket probleme..

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.74

**Desktop (please complete the following information):**
 - OS: MacOS M2 Sonoma
 - Browser: Arc/Brave

**Comment by tommoor** [comment]
What is the content of the doc?
Does the tab go to 100% cpu usage?
Are you able to pause execution in the developer tools inspector and see where in the code is being executed?

**Comment by matsukky** [comment]
This happened with a page that had just been created, and the tab rose to 100% very quickly. Unless I'm not doing the job correctly, I can't pause execution.

**Comment by tommoor** [comment]
Open the developer tools first, then once you enter the document and the issue begins hit this button as quickly as possible. You should be able to see where in the call stack time is being spent.

<img width="1467" alt="Screenshot 2023-12-17 at 4 57 03 PM" src="https://github.com/outline/outline/assets/380914/770d03de-3901-4abf-b7e8-d45409bc76a7">

**Comment by matsukky** [comment]
I had indeed done the manipulation wrong. I'm not sure I understood what to do next, sorry, but I see that it stops on ``editable: () => !this.props.readOnly`` which comes from a file index.tsx

**Comment by tommoor** [comment]
Okay, that doesn't really tell us anything unfortunately.

If you go to the performance tab you can record while the lockup is happening and then export the result as a json file, you would only need to record a couple of seconds of high CPU

**Comment by matsukky** [comment]
I just can't do it. No matter how hard I try, I can't get the profile back. Whether I try to start the process before reloading the page, or as soon as possible after opening it.

**Comment by matsukky** [comment]
Could the problem be due to my nginx configuration?

**Comment by tommoor** [comment]
I'm afraid I have no idea, it's never come up before. Does it happen on all new documents?

**Comment by matsukky** [comment]
New and old alike. Basically, from a Chrome browser, no page can be edited and viewed.

**Comment by tommoor** [comment]
I would try in incognito, it might be a browser extension.

**Comment by matsukky** [comment]
I tried with a browser (brave) that I installed for the occasion, the problem is the same. As I said earlier, safari and firefox are not affected by this problem...

**Comment by matsukky** [comment]
Update: this works on opera gx... although it seems to me that it is also a chromium browser...

**Comment by matsukky** [comment]
the problem came from the [Word Replacer II](https://chromewebstore.google.com/detail/word-replacer-ii/djakfbefalbkkdgnhkkdiihelkjdpbfh)extension which had reinstalled itself on brave from my old use and which is installed on my Arc. Sorry to have wasted your time...
