### ISSUE TITLE
document not displayed in the catalog

### ISSUE THREAD

**Issue by YIKAILucas** [outline/outline#6316]
**To Reproduce**
1. New a doc.
2. publish this doc.
3. The document did not appear on the left side catalog. I need to refresh the whole page to show the doc in the catalog.

**Expected behavior**
It will Immediately display in the left side after publish this doc.

**Screenshots**
No shots because it didn't display normally.

**Outline (please complete the following information):**
- Install: self hosted
- Version:  6f234be

**Desktop (please complete the following information):**
 - OS: PC
 - Browser: Arc 
 - Version: 1.21.2

**Comment by tommoor** [comment]
You should upgrade to the latest version and see if that fixes the issue first

**Comment by YIKAILucas** [comment]
It partly works. After published, the doc display well. But after deleted, the doc may not disappear.

version: outline v0.74.0

**Comment by tommoor** [comment]
Need more information to go off here, if you can capture the websocket messages that are received in developer tools when deleting a document that may help.
