### ISSUE TITLE
Markdown Mermaid codeblock not recognised

### ISSUE THREAD

**Issue by tomjones1977** [outline/outline#6344]
**To Reproduce**
1. Create a page
2. Paste markdown codeblock in or use API to run document.update
3. Mermaid diagrams with ```mermaid at the start are not displayed as mermaid diagrams until manually changed in the web interface

**Expected behavior**
Markdown submitted via API respects codeblock language selection

**Screenshots**
N/A

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 0.72.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Firefox
 - Version Latest

**Comment by tommoor** [comment]
Hi @tomjones1977 – the language should be set to `mermaidjs` for this to work, cheers

**Comment by tomjones1977** [comment]
That was rapid, and works perfectly, thanks!
