### ISSUE TITLE
Missing documentation for integrating collections to Slack channels

### ISSUE THREAD

**Issue by kaibrueckers** [outline/outline#6348]
When following the documentation and setting up posting to Slack, there's an error when connecting an Outline collection to a channel. That's because the redirect URL (`${env.URL}/auth/slack.post`) for posting is not set up within the Slack app. This wasn't explained in the respective [section](https://docs.getoutline.com/s/hosting/doc/slack-G2mc8DOJHk) of the documentation and should be added.

**Outline:**
- Install: self hosted
- Version: v0.73.1 - https://github.com/outline/outline/commit/e4d00783585f2a509da3565723227d2b5959a2e9

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version 120.0.6099.130

**Comment by tommoor** [comment]
✅  updated
