### ISSUE TITLE
Incompatibility with the famous Dark Reader extension in chrome

### ISSUE THREAD

**Issue by badihi** [outline/outline#6353]
When you open a simple document while using Dark Reader extension, the browser hangs.

**To Reproduce**
1. Install and enable Dark Reader extension
2. Open outline and create a new doc
3. Insert a new heading
4. The page freezes and crashes

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.74.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 120

**Comment by tommoor** [comment]
Did you file an issue on dark reader? Outline has its own dark mode you can safely disable the extension on the site it is not required
