### ISSUE TITLE
Document went missing when I changed the Page Name

### ISSUE THREAD

**Issue by jasonquiz** [outline/outline#636]
I changed a Page name to include an underscore so that it would show up first in the list under that Collection. When I did this the Page moved to the top of the Collection (as expected), but when I tried to view the page I got the error "Not Found. We’re unable to find the page you’re accessing.".

Is there a way to get this page back? 
Page Link: https://www.getoutline.com/doc/_-getting-started-uzrC2wzQv8
Old Page Link:  https://www.getoutline.com/doc/getting-started-uzrC2wzQv8

**Comment by jasonquiz** [comment]
Ok I found that if I clicked on the "..." more icon and chose "Download", the information was there.

I am going to delete the Document with the bad link and copy/paste the info back in.

Leaving this open because it seems to be a bug of some kind.

**Comment by tommoor** [comment]
Thanks for the report @jasonquiz – I was able to reproduce this bug easily.

**Comment by jorilallo** [comment]
@jasonquiz Just merged a fix, it should be out in the next 30min. Please refresh your app and thanks again for reporting

**Comment by jasonquiz** [comment]
@jorilallo Thanks so much! I will let you know if I see this issue again.
