### ISSUE TITLE
Error: Upload Notion .zip with html content 

### ISSUE THREAD

**Issue by BananaJoe42** [outline/outline#6374]
**To Reproduce**
1. Go to 'Settings' -> 'Workspace' -> 'Import' 
2. Click on 'Notion Import'
3. Choose .zip File (exported from Notion with the setting: Format: 'HTML' 
'Failed • Uploaded file does not contain any valid documents'

**Expected behavior**
An imported page from notion.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - Browser  safari
 - Version 16.5.2

**Comment by tommoor** [comment]
Hi @BananaJoe42 – 'Settings' -> 'Workspace' -> 'Import' is for _bulk_ import and only works for importing an entire workspace into Outline at this time.

If you want to import an individual document you can import the html through the regular import options on a collection or just by dragging the html file into the sidebar.
