### ISSUE TITLE
Found a minor bug in useInterval hook

### ISSUE THREAD

**Issue by mass2527** [outline/outline#6380]
In the current implementation, there's no way to stop the interval because the `delay` parameter, which is of type `number`, cannot be set to `null`.

I guess this hook's author copied code from [overreacted](https://overreacted.io/making-setinterval-declarative-with-react-hooks/) and forgot to include a `null` type for the `delay` parameter.

Can I make a pull request to fix this issue?

```ts
import * as React from "react";

type Callback = () => void;

/**
 * Hook to set up an interval that calls a callback.
 *
 * @param callback The callback to call.
 * @param delay The delay in milliseconds.
 */
export default function useInterval(callback: Callback, delay: number) {
  const savedCallback = React.useRef<Callback>();

  // Remember the latest callback.
  React.useEffect(() => {
    savedCallback.current = callback;
  }, [callback]);

  // Set up the interval.
  React.useEffect(() => {
    function tick() {
      savedCallback.current?.();
    }

    if (delay !== null) {
      const id = setInterval(tick, delay);
      return () => clearInterval(id);
    }

    return undefined;
  }, [delay]);
}

```

**Comment by tommoor** [comment]
I'm sorry, what is the bug you've found? `useInterval` is only used in one place and it is never set to `null`

**Comment by mass2527** [comment]
Thank you for your comment!

Then, no problem.
Since there is a `null` check logic in the `useEffect` setup function,
I assume that the author's intention with this code is to stop the interval when a `null` delay is provided.
