### ISSUE TITLE
Show groups in facepile on private collection

### ISSUE THREAD

**Issue by sjthiessen** [outline/outline#6397]
When a collection is shared with at least one single user, an icon is shown in the upper right corner via which an overview over the permissions is accessible. However if the collection is only shared with groups, that icon is missing, offering no option to view the permissions.

Might be related to https://github.com/outline/outline/issues/6192 ?

Sidenote: The mobile view doesn't offer the permissions view at all.

**To Reproduce**
1. Setup a collection that is only shared with groups and login as a user which is member of one of these group
2. Open the overview page of this collection
3. Search for a possibility to view permissions

**Expected behavior**
I'd suggest adding the group-icon in the corner if the collection is shared with at least one group.

**Screenshots**
![Screenshot 2024-01-16 1259452](https://github.com/outline/outline/assets/74589534/5bca7f01-a162-4ad9-9e26-c82f9743fe13)

**Outline (please complete the following information):**
- Install: self hosted via docker
- Version (image): outlinewiki/outline:0.74.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 121.01

**Mobile (please complete the following information):**
 - Device: Pixel 4a 5G
 - OS: Android 14
 - Browser: Firefox

**Comment by tommoor** [comment]
Permissions are always accessible from the "..." menu if you have access. We'll soon be changing this design to bring it inline with documents under a "Share" button

**Comment by sjthiessen** [comment]
Oh somehow I must've missed that!
