### ISSUE TITLE
Admin API key returns code 403 when deleting or archiving a document

### ISSUE THREAD

**Issue by gmiles32** [outline/outline#6402]
I am currently writing a python package to sync my obsidian vault with self-hosted outline via API requests. When I try to make a delete document API request (`document.delete`), I get a "403 Authorization Error," even though my API key has Admin privileges. My API key has worked with the following requests without issue:
- `collections.list`
- `documents.list`
- `collections.create`
- `collections.delete`
- `documents.create`
- `documents.info`

I got the same error for `documents.archive` API request. I have also tried permanent options `True` and `False`. I am using the python `requests` package to make all POST requests, but I was able to reproduce the error with `curl` on Linux. 

**To Reproduce**
1. Create an API key for an admin user
2. Create a collection and a published document, get the document ID
3. Run either of the following curl commands:
```bash
curl https://outline.domain.com/api/documents.delete -X 'POST' -H 'content-type: application/json' -H 'accept: application/json' -d '{"token": API_KEY,"id": DOCUMENT_ID,"permanent": true}'
curl https://outline.domain.com/api/documents.delete -X 'POST' -H 'Authorization: Bearer API_KEY' -H 'content-type: application/json' -H 'accept: application/json' -d '{"id": DOCUMENT_ID,"permanent": true}'
```

**Expected behavior**
Code 200 with an admin API key, and the document should be deleted.

**Outline**
- Install: self hosted
- Version: sha256:1f01d5ebd561b32d973bf4cd0f2d945bdea68e585aa3233fbbdc9ce508f754bd

**Desktop**
 - OS: Fedora 38 Workstation
 - Browser: Firefox
 - Version: 121.0

**Comment by tommoor** [comment]
Is the document in a private collection? Does the admin API key have a membership to the collection?

**Comment by gmiles32** [comment]
Thanks for getting back to me - 1) The document is in a public collection and 2) The admin API key has membership to the collection, since my user has access to the collection

**Comment by tommoor** [comment]
I believe the issue might be that you must delete the issue trash first (without `permanent: true`) and then delete permanently with a second request.

**Comment by gmiles32** [comment]
Can you explain a little more what you mean? I tried what I think you suggested, which was to delete the document with `permanent: false`, and then delete again with `permanent: true`, both times I got the `403 Authorization Error`. I also tried to clear the trash manually, and then delete the document (with both permanent `true` and `false`), same error. I also tried to unpublish the document first, but I got the same 403 error.

It's really weird, because I can create, retrieve and update documents in the same collection without issue. I'll try in some of my other collections to see if I can troubleshoot further.

**Comment by gmiles32** [comment]
Issue solved, it was a problem with my code and not with Outline - thanks for your help anyways!

**Comment by gmiles32** [comment]
Solved
