### ISSUE TITLE
Administrator of a collection can't remove comments of documents inside this collection

### ISSUE THREAD

**Issue by LudovicGodart** [outline/outline#6404]
We have teams that have Administrator privileges for a particular collection.
It is not possible for them to delete comments from documents that come from the collection where they are supposed to have all the rights.
The only way for them to have deletion rights is to upgrade them to Global Administrator, but that's absolutely not what we want.

**To Reproduce**
1. Be admin of a collection
2. Someone post a comment in a document of that collection
3. Try to delete it -> You can't

**Expected behavior**
An admin of a collection should be able to manage comments inside it.

**Outline (please complete the following information):**
- Install: self hosted
- Version: https://github.com/outline/outline/releases/tag/v0.74.0

**Comment by tommoor** [comment]
Removing bug label as this was as designed, although I can see the argument.
