### ISSUE TITLE
GitHub integration

### ISSUE THREAD

**Issue by tommoor** [outline/outline#6406]
We're planning on making GitHub the first authenticated editor integration, the initial version will allow connecting GitHub to the workspace and then show authenticated details on link hover.

After that we'll work on embedding link details into in-page widgets, once #3000 finally lands which would currently block that.

**Comment by almereyda** [comment]
This will be welcome prior art for a GitLab integration, eventually contributed by the community.

**Comment by almereyda** [comment]
Released with [v0.84.0](https://github.com/outline/outline/releases/tag/v0.84.0).
