### ISSUE TITLE
Can't un-publish docs with archived children

### ISSUE THREAD

**Issue by JayPadz** [outline/outline#6408]
Reproduction steps:
1) Create a document (AAA) in a collection.
2) Create a child document (BBB) that is a child of AAA, add some content.
3) Create a child document (CCC) that is a child of BBB, add some content.
4) Archive document CCC
5) Archive document BBB
6) Click "unpublish" on document AAA
7) See the following error message pop up in the bottom right
![can't unpub](https://github.com/outline/outline/assets/13203745/363579ee-f1b3-4980-8173-70585cf95197)

Expectations: During step #6 the document would be unpublished and revert to draft state without error.

Notes/suggestions/considerations: Perhaps consider the concept of unpublished documents overall. Why should a nested document be prevented from being unpublished? Perhaps pop-up a modal dialog box explaining "This document and X total sub documents will be unpublished together. With button options "Yes unpublish all X documents" or "Do nothing, go back". 

Of course if the documents are published by other people you might say something related to that if it's applicable? "You're trying to unpublish X documents, Y of which are not created by you. Permission denied. You can only unpublish documents you've created." or something like that

**Comment by includesec-erik** [comment]
The title might be more appropriate as "Can't un-publish docs that used to have children"
