### ISSUE TITLE
Allow filter search by parent

### ISSUE THREAD

**Issue by tommoor** [outline/outline#6428]
Sometimes it would be useful to filter search results to those contained within a parent document tree

**Comment by Pranav2612000** [comment]
Hey @tommoor I'll like to work on this. Do you have a UI in mind of how this could work?

**Comment by tommoor** [comment]
I do, unfortunately the UI does not exist yet in the product as we need to have a dropdown with a filter that will also search against a backend API. For these we want to start moving to radix (#6456) but that hasn't begun yet, so it's a little blocked.
