### ISSUE TITLE
Outline Wiki fails to handle http basic auth when being nginx reverse proxied

### ISSUE THREAD

**Issue by ksaadDE** [outline/outline#6429]
Long story short:
My setup uses two docker stacks. Outline Wiki (btw your documentation is not up to date, it's using docker-compose instead of `docker compose`!). Authentik as OIDC provider and another nginx docker compose stack as websrv.

I tried to put Outline Wiki behind HTTP Basic Auth in the config of the nginx container. However, the Outline Wiki container refuses to accept the HTTP Basic Auth that works certainly with another software. The refusal is shown by popups all the time that the HTTP Basic Auth Credentials would be needed. Even when supplying them nginx keeps asking.

This is only happening with the Outline Wiki Software for me. Some software invalidates (due to the auth mechanisms build in the software) Http Basic Auth, which might be the case here.

**To Reproduce**

1. download docker stack
2. put it in the nginx config behind http basic auth
3. go on the nginx address that resolves to your outline wiki and it will keep you asking for the http basic authentication

**Expected behavior**
It should only ask once and not multiple times, so that all routes (api, locales, auth etc) are successfully accessible after once authenticating via HTTP Basic Auth.

**Screenshots**

* not needed

**Outline (please complete the following information):**

* Install: docker
* Version: latest

**Desktop (please complete the following information):**

* OS: Linux
* Browser All except Safari (didn't test the latter)
* Version latest

nginx:latest
authentik:latest

I'd like to add it was kinda a hassle to set it up via docker compose, took about two hours. The lacking local authentication or better to say, the OIDC / OpenID requirement is the most significant part in this. I've seen the other issues complaining about that and I'd like to complain about that as well. Also, I had to remove the pre-confugred HTTPs stuff and I had to change a lot of the configs (changing the docker networks, ports etc). Though that's not the point here, despite I just wanted to test the hell you made :)

For graphical reference of the stack:

![veryprofessionalchart](https://uploads.linear.app/47519575-84a7-4b8b-8a29-c645d1bb39ee/27dae6d9-ab6e-4c39-84f0-18388e7b3d5a/78d6ac75-1ce8-477d-a06d-0cd7bc8824cc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQ3NTE5NTc1LTg0YTctNGI4Yi04YTI5LWM2NDVkMWJiMzllZS8yN2RhZTZkOS1hYjZlLTRjMzktODRmMC0xODM4OGU3YjNkNWEvNzhkNmFjNzUtMWNlOC00NzdkLWEwNmQtMGNkN2JjODgyNGNjIiwiaWF0IjoxNzA2MjM1ODA0LCJleHAiOjMzMjc2Nzk1ODA0fQ.XF5WDESNlDIT1aAbVdv0afn2LH72rtV_BY61-kHG2cU)

**Comment by tommoor** [comment]
There is no plan to support this functionality I'm afraid, if you'd like to submit a PR it could be evaluated if the changes to support it are minimal.

**Comment by ksaadDE** [comment]
> There is no plan to support this functionality I'm afraid, if you'd like to submit a PR it could be evaluated if the changes to support it are minimal.

Sure send me the LOC where I need to look at

**Comment by ksaadDE** [comment]
@tommoor 
Kindly look into this, it may help: https://github.com/koajs/basic-auth

**Comment by ksaadDE** [comment]
> There is no plan to support this functionality  

Outline should support this by default, if it uses the standard HTTP.  It just needs adjustment of the middleware and use of headers.
