### ISSUE TITLE
Airtable embedding again

### ISSUE THREAD

**Issue by gretalee** [outline/outline#6449]
I can not embed an Airtable

**Steps to Reproduce**
1. Within a document I start typing "/air"
2. A modal appears with one input "Paste a airtable link ..."
3. I paste the link and hit enter
4. nothing happens  (modal is still open)
5. I hit tab key
6. nothing happens (modal is still open)
7. I click in the document outside of the modal
8. The input-modal closes, but nothing else happens. I can just see my started text "/air"

**Expected behavior**
After inserting an airtable link and hitting enter, the airtable-content should show up.

**Outline (please complete the following information):**
- Install: getoutline.com
- Version: (I use the web version)

**Desktop (please complete the following information):**
 - OS: MacOS Montery 12.6.
 - Browser: Google Chrome 120.0.6099.234
 - Version 120.0.6099.234

**Comment by tommoor** [comment]
This was addressed https://github.com/outline/outline/issues/6095 and will be in the next release
