### ISSUE TITLE
Update collection "permissions" to look more like document sharing

### ISSUE THREAD

**Issue by tommoor** [outline/outline#6454]
These two concepts are essentially the same, we can bring the treatment much more inline and clarify the permissions while we're doing it.

Follow on from #2359

**Comment by DataGoblin** [comment]
I hope this is on topic. Are there any plans to make permissions more granular? 

For example, we have a collection and then a document, nested under that document are a few more documents. One of those documents we would want to limit its visibility to a specific group or people individually. 

Permissions at a collection-level are bearable but without document-level permissions, it creates a mess of overlap where we need to create multiple collections for the same topic.

**Comment by tommoor** [comment]
Bulk of code is now merged behind a flag
