### ISSUE TITLE
Switching between read/edit permission should update remote clients in realtime

### ISSUE THREAD

**Issue by tommoor** [outline/outline#6455]
When updating the document permission of a user it should update their permissions in realtime without needing to reload the tab.

Follow on from https://github.com/outline/outline/issues/2359

**Comment by almereyda** [comment]
Testing this with 2505fea1035c479f09a7c661c48d0c36b89742b4 and two different users in different browser contexts yesterday and just now this already works in direction of

- edit to read

An eventual client will update the document state and switch to a read-only view.

Switching from

- read to edit

requires the reload.

**Comment by almereyda** [comment]
Still confusing and counter-intuitive, because it works in one direction,
but not in the other.
