### ISSUE TITLE
Add option to archive all notifications

### ISSUE THREAD

**Issue by tommoor** [outline/outline#6463]
The API already exists, `notifications.update_all` with `archivedAt` timestamp. I suggest that the settings cog here is converted to a menu with the options:

* Archive all notifications
* Notification settings

![image](https://uploads.linear.app/47519575-84a7-4b8b-8a29-c645d1bb39ee/12a89b08-c56b-42b5-a103-daa593e92d70/8f982c70-55ea-44ea-8baa-45e5e1579fcd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQ3NTE5NTc1LTg0YTctNGI4Yi04YTI5LWM2NDVkMWJiMzllZS8xMmE4OWIwOC1jNTZiLTQyYjUtYTEwMy1kYWE1OTNlOTJkNzAvOGY5ODJjNzAtNTVlYS00NGVhLThiYWEtNDVlNWUxNTc5ZmNkIiwiaWF0IjoxNzA2NzU0ODE2LCJleHAiOjMzMjc3MzE0ODE2fQ.jPnVG2gluuEfnUdJ2sMX2ULEShKBx7HKjvjA9njVzHs "=406x")

**Comment by hmacr** [comment]
@tommoor Once a notification is archived, do we want to hide it in the notifications-list?

Also, do we want to support archiving a single notification?

**Comment by tommoor** [comment]
> Once a notification is archived, do we want to hide it in the notifications-list?

Yep, we can think of it the same as deleting for now.

> do we want to support archiving a single notification?

Can support this later, I don't think it's worth introducing a `...` menu on the notification just for this and there are no right click context menus yet
