### ISSUE TITLE
More icons (Request in issue)

### ISSUE THREAD

**Issue by tommoor** [outline/outline#6469]
Please comment with your collection icon requests in this issue with a checkbox, like so

### Done
- [x] Hashtag
- [x] Airplane
- [x] Carrot
- [x] Ramen
- [x] Flame
- [x] Server
- [x] Apple
- [x] Android
- [x] Windows

**Comment by Limezy** [comment]
- [ ] Cake
- [ ] Ice-cream
- [ ] Fork
- [ ] Carrot
...

I know it's not very "corporate" and would understand that you'd deny this kind of lexical field, but Outline is a perfect tool for receipe management

**Comment by tommoor** [comment]
Yes, I'll create a separate issue for that

**Comment by lampy255** [comment]
- [ ] Truck
- [ ] Building / High rise

**Comment by listiges-kaenguru** [comment]
- [ ] House / Home
- [ ] Heart / Love
- [ ] Palm on Island

**Comment by Mrbibi38** [comment]
- [ ] Apple
- [ ] Windows
- [ ] Linux (penguin)
- [ ] Shield
- [ ] Wifi
- [ ] Laptop
- [ ] Monitor

It will be awesome to have a lot of icons like notion, or maybe have a way to add some icon in the self hosted version.

**Comment by tommoor** [comment]
Added another [80 icons today](https://github.com/outline/outline/pull/6803)

**Comment by TheDevMinerTV** [comment]
[ ] Server

**Comment by tommoor** [comment]
There is already a server rack icon
