### ISSUE TITLE
Add option to use emoji for collection icons

### ISSUE THREAD

**Issue by tommoor** [outline/outline#6475]
Related https://github.com/outline/outline/issues/6469 and #2356 

Should be relatively straight forward, all the pieces exist.

**Comment by tommoor** [comment]
I think actually (1) is preferable, using the same column. It is easy to differentiate between an emoji and an icon, there is a world where custom icons can be uploaded in the future and I wouldn't want to introduce another third column for that so I think it makes sense to keep it centralized.

In the medium term can probably rename the column on `document` from emoji -> icon to match and use the same schema.

**Comment by tommoor** [comment]
@hmacr still interested in taking this or shall we pass it along?

**Comment by hmacr** [comment]
@tommoor Oh yes definitely! I have been out for 2 weeks on personal time off.

I'm starting on #6215, and would take this one after that; so, in a day or two hopefully.
If customers are waiting for this feature, I can take it first; or pass it along too :)

**Comment by shiny** [comment]
How lucky I am, waiting this feature for years. :tada:
