### ISSUE TITLE
Newly Invited Users to Outline are Unable to Access the Platform

### ISSUE THREAD

**Issue by TeddyPapercup** [outline/outline#6483]
I have attempted to invite a cohort of new users to access my company's Outline space. I have invited them using the invite function, then added them to the relevant user groups, as per my normal workflow. The new members appear on my side as invited members that have never signed in. I have informed them to use SSO to access Outline, but all have been unable to access the platform and receive the error message shown in the screenshot attached. 

I have tried re-inviting, un-inviting and re-inviting etc, but have the new users are still unable to access Outline. All users have reported that they do not receive an email invite. 

**To Reproduce**
1. Go to 'Groups', select the relevant group and then click '+Add People'
2. Click on 'Invite them to Papercup'
3. Add names and email addresses, then 'Send invites'.
4. Scroll down to 'the relevant names in the listand click 'Add' to add them to the group'
5. See error

**Expected behavior**
The new user should receive an invite and/or are able to access Outline using SSO.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: self hosted v0.67.2
- Version: [commit sha if self hosted]

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma Version 14.2.1 (23C71)
 - Browser Chrome
![unnamed](https://github.com/outline/outline/assets/158740996/21aaa939-6114-4120-90c0-3cfcc45bcf2f)

**Mobile (please complete the following information):**

**Comment by tommoor** [comment]
- Please provide the server logs from when the user attempts to sign-in.
- Do you have allowed domains setup in security settings?
- Do the users have emails in OpenID connect?
