### ISSUE TITLE
Remember previous location Setting

### ISSUE THREAD

**Issue by MrSparkle23** [outline/outline#6486]
The "Remember previous location" option isn't saved properly.

**To Reproduce**
1. Go to /settings/preferences
2. Click on "Remember previous location" to disable the option
3. Refresh page
4. "Remember previous location" is enabled again

<img width="718" alt="Screenshot 2024-02-03 at 20 50 12" src="https://github.com/outline/outline/assets/117304540/9f33d780-4a4e-4bd6-9223-d5b3c5dcdef5">

**Expected behavior**
Option saved and persists through refresh

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.74.0 docker image

**Comment by tommoor** [comment]
This issue is addressed on `main` already and will be fixed in the next release. In the meantime you should be able to upload an avatar to bypass the problem
