### ISSUE TITLE
MS teams

### ISSUE THREAD

**Issue by bzyg7b** [outline/outline#650]
Are there any plans to make this work with MS teams as it does with Slack?

**Comment by tommoor** [comment]
Hey @bzyg7b – no immediate plans, It's looking like we'll support Google Auth next. Would that work for your team?

**Comment by bzyg7b** [comment]
@tommoor Google Auth could work for us. If it was up to me we would all be on Slack haha

**Comment by tommoor** [comment]
Cool. Closing in favor of https://github.com/outline/outline/issues/656 - there's no plan to support signin with MS Teams.
