### ISSUE TITLE
Can't place cursor with mouse in image caption

### ISSUE THREAD

**Issue by thumDer** [outline/outline#6513]
**To Reproduce**
1. Insert an image
2. Write some caption text
3. Click anywhere in the written caption, the cursor won't move
4. The same happens with existing captions as well, cursor always gets inserted at the beginning.

**Expected behavior**
Place the cursor in the caption text with mouse click

**Screenshots**
![399498F9-9BB6-4F9D-B167-23401A8AC252](https://github.com/outline/outline/assets/54556708/53826123-6316-45f3-92ad-086c996a2830)

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: Win 11 Pro 23H2
 - Browser Firefox
 - Version 122.0.1

**Comment by tommoor** [comment]
This does appear to be a Firefox-only issue, thanks

**Comment by tommoor** [comment]
Looks like the issue is 3 years old, you know at least it isn't 15 years old – something I've seen before.

https://bugzilla.mozilla.org/show_bug.cgi?id=1289000
