### ISSUE TITLE
Outline fails to show comments from users

### ISSUE THREAD

**Issue by larubbio** [outline/outline#6516]
I've experienced several cases where I comment on a document, another user either also comments, or replies to my comments. I receive an email from outline with the users comment and a button that should take me to the thread. When I click the button, the page loads, I very briefly see the comments load, but once the page completes loading my comments remain but the other users are no longer visible.

Looking in the network tab, I see a 400 response when POSTing to /api/comments.info with a body of `{id: null}` and 403 errors POSTing to the same url with values for the `id`
 
**To Reproduce**
1. Receive email from getoutline.com after a user comments
2. Click on 'Open Thread'

**Expected behavior**
I expect to see all the comments made on a document.

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Firefox
 - Version: 122.0.1

**Comment by tommoor** [comment]
I have some thoughts on recent changes that may have caused this, will take a look
