### ISSUE TITLE
Table of contents list getting cut off when resizing window

### ISSUE THREAD

**Issue by binaryfire** [outline/outline#6563]
The table of contents list is being cut off when the window is resized. See:

![image](https://uploads.linear.app/47519575-84a7-4b8b-8a29-c645d1bb39ee/26f37800-2dc4-41ca-bc07-2c96d92e16c2/7de0338f-8cc6-42fe-b07d-7bb89c307047?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQ3NTE5NTc1LTg0YTctNGI4Yi04YTI5LWM2NDVkMWJiMzllZS8yNmYzNzgwMC0yZGM0LTQxY2EtYmMwNy0yYzk2ZDkyZTE2YzIvN2RlMDMzOGYtOGNjNi00MmZlLWIwN2QtN2JiODljMzA3MDQ3IiwiaWF0IjoxNzA4NDg0Mzc2LCJleHAiOjMzMjc5MDQ0Mzc2fQ.2RQS43b484wgGQ9C5gtU3X5ivIiHtGKMNDJGu9G1_NI "=274x")

**Comment by binaryfire** [comment]
It happens when switching over to the the largest breakboint (1600px).

**Comment by hmacr** [comment]
@tommoor I suppose this can be closed since it was fixed as part of #6943
