### ISSUE TITLE
bug: v0.75.0: OIDC auth results in redirect loop and "User authentication X already exists for Y, tried to assign to Z"

### ISSUE THREAD

**Issue by lrstanley** [outline/outline#6565]
Upgrading to 0.75.0, I am now receiving a redirect loop upon login, where it never successfully logs in and keeps redirecting to the OIDC endpoint. I see the following logs during login:

```console
outline {"error":"User authentication TRUNCATED already exists for 6b0d655c-334a-4745-a2ae-12b89f58f1d5, tried to assign to 13dbfa83-cffb-4bfd-80b1-c9c89eb32cc4","level":"error","message":"Error during authentication","stack":"Error: User authentication TRUNCATED already exists for 6b0d655c-334a-4745-a2ae-12b89f58f1d5, tried to assign to 13dbfa83-cffb-4bfd-80b1-c9c89eb32cc4\n    at userProvisioner (/opt/outline/build/server/commands/userProvisioner.js:54:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:73:12)"}
outline {"error":"User authentication TRUNCATED already exists for 6b0d655c-334a-4745-a2ae-12b89f58f1d5, tried to assign to 13dbfa83-cffb-4bfd-80b1-c9c89eb32cc4","level":"error","message":"Error during authentication","stack":"Error: User authentication TRUNCATED already exists for 6b0d655c-334a-4745-a2ae-12b89f58f1d5, tried to assign to 13dbfa83-cffb-4bfd-80b1-c9c89eb32cc4\n    at userProvisioner (/opt/outline/build/server/commands/userProvisioner.js:54:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:73:12)"}
outline {"error":"User authentication TRUNCATED already exists for 6b0d655c-334a-4745-a2ae-12b89f58f1d5, tried to assign to 13dbfa83-cffb-4bfd-80b1-c9c89eb32cc4","level":"error","message":"Error during authentication","stack":"Error: User authentication TRUNCATED already exists for 6b0d655c-334a-4745-a2ae-12b89f58f1d5, tried to assign to 13dbfa83-cffb-4bfd-80b1-c9c89eb32cc4\n    at userProvisioner (/opt/outline/build/server/commands/userProvisioner.js:54:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:73:12)"}
```

**To Reproduce**
1. Login, initialize OIDC login the first time (so it saves for further OIDC login attempts)
2. You will be redirected to the `/?notice=auth-error` endpoint, but it will attempt to login again, and won't stop to show the actual auth error to the user.

**Expected behavior**
1. In the event of an authentication error, it should not redirect, it should show a popup or similar with the generic error.
2. The underlying error shouldn't occur, ofc (the change of the email should be seamlessly handled, which is what I expect caused it).

**Screenshots**

redirect loop video (cancelled the request after a few loops to prevent Github from blocking the requests):
https://cdn.liam.sh/share/2024/02/firefox_EQq2Yocfj0.mp4

**Outline:**
- Install: self hosted
- Version: 0.75.0 (tag, docker image)

**Desktop:**
 - OS: Windows 11
 - Browser Firefox
 - Version 123.0

**Additional notes:**

- I have attempted to wipe all cookies, and cache, with no luck. Same happens in incognito.
- I have a login email restriction in place, if this is useful.
- I have recently renamed the email on my OIDC provider, and updated my email allow list to accommodate. I logged in fine, after the change of the email, and it pulled things correctly, but it looks like it doesn't like it with some recent change. This occurred before the 0.75.0 upgrade, though.

Some additional info from the database:
```
outline=# SELECT * FROM authentication_providers;
                  id                  | name |   providerId   | enabled |                teamId                |         createdAt
--------------------------------------+------+----------------+---------+--------------------------------------+----------------------------
 6b0d655c-334a-4745-a2ae-12b89f58f1d5 | oidc | liamstanley.io | t       | bf4f9e8d-cce0-405b-9728-d054c5e5a930 | 2023-12-02 20:38:09.128+00
 13dbfa83-cffb-4bfd-80b1-c9c89eb32cc4 | oidc | liam.sh        | t       | bf4f9e8d-cce0-405b-9728-d054c5e5a930 | 2024-02-06 13:52:17.597+00
(2 rows)

outline=# SELECT * FROM authentications;
 id | userId | teamId | service | token | scopes | createdAt | updatedAt
----+--------+--------+---------+-------+--------+-----------+-----------
(0 rows)

outline=# SELECT "userId", "authenticationProviderId", "providerId", "createdAt", "updatedAt" FROM user_authentications;
                userId                |       authenticationProviderId       |       providerId        |        createdAt         |         updatedAt
--------------------------------------+--------------------------------------+-------------------------+--------------------------+----------------------------
 ce43d306-62c7-400a-8f9d-6ef64ee6a7f4 | 6b0d655c-334a-4745-a2ae-12b89f58f1d5 | CgcxODQ3MzY1EgZnaXRodWI | 2023-12-02 20:38:09.2+00 | 2024-02-01 15:10:14.117+00
(1 row)
```

**Comment by tommoor** [comment]
Your `providerId` being based on the email domain is causing the underlying problem – typically it's an opaque database ID that wouldn't change with the change of email.

The best thing would likely be to remove the new record and rename the `providerId` on the old one manually to the new domain.

**Comment by lrstanley** [comment]
Thanks -- I was able to swap to the new provider to correct the auth error, and delete the old provider:
```sql
UPDATE "user_authentications"
	SET "authenticationProviderId" = '13dbfa83-cffb-4bfd-80b1-c9c89eb32cc4'
	WHERE "userId" = 'ce43d306-62c7-400a-8f9d-6ef64ee6a7f4';
DELETE FROM "authentication_providers"
	WHERE "id" = '6b0d655c-334a-4745-a2ae-12b89f58f1d5';
```

Is there anything that could have prevented the issue with the email being updated? I don't believe anything changed as far as the OIDC endpoint itself, or the ID of the user that was returned.
