### ISSUE TITLE
Inline comment shown as page comment

### ISSUE THREAD

**Issue by thumDer** [outline/outline#6580]
A comment created on selection shows up as expected for the author, but other users can't see neither the quote, nor the highlight on the text.

**Expected behavior**
Same experience for all users.

**Screenshots**
For the author:
![Untitled](https://github.com/outline/outline/assets/54556708/70aca624-c1f4-4a6a-9401-50ed47daff8f)

For other users: (multiple browsers)
![image](https://github.com/outline/outline/assets/54556708/a125f509-71dc-4148-b1b7-ae436ad471c3)

**Outline (please complete the following information):**
- Install: getoutline.com 

**Desktop (please complete the following information):**
 - OS: Win11 23H2
 - Browser Firefox
 - Version 122.0.1

**Comment by tommoor** [comment]
Could i confirm this is on cloud hosted? Are other changes to the document synchronising correctly?

**Comment by thumDer** [comment]
> Could i confirm this is on cloud hosted? Are other changes to the document synchronising correctly?

Yes, it is on cloud hosted, and I haven't noticed any other sync issues

**Comment by tommoor** [comment]
If you open the command menu (cmd+k) and select "Clear IndexedDB cache" it should fix it, I'm not sure why yet.

**Comment by thumDer** [comment]
I've tried, but I've got this:
![image](https://github.com/outline/outline/assets/54556708/dd0067d2-1d78-406e-95f7-dffcabf75d49)

**Comment by tommoor** [comment]
Strange, this is standard functionality in any modern browser – are you running Firefox in a particularly restricted mode?

**Comment by thumDer** [comment]
I don't know about any restriction. Just updated to 124.0.1 but nothing changed.
