### ISSUE TITLE
License unclear or unspecified

### ISSUE THREAD

**Issue by Chealer** [outline/outline#6584]
[The current (as of 0.75.2) LICENSE file](https://github.com/outline/outline/blob/0054b7152ec211b0f34dd41b2fbfb63c5dc54994/LICENSE) starts with:

> 
> Business Source License 1.1
> 
> Parameters
> 
> Licensor:             General Outline, Inc.
> Licensed Work:        Outline 0.71.0
>                       The Licensed Work is (c) 2020 General Outline, Inc.
> Additional Use Grant: You may make use of the Licensed Work, provided that
>                       you may not use the Licensed Work for a Document
>                       Service.

It is unclear how to interpret this. Does this mean the license only applies to version 0.71.0, effectively meaning that the current version is not licensed, or is it merely outdated?

**Comment by tommoor** [comment]
It's meerly outdated, we need some tooling to automatically update the license. The license applies despite the version mismatch

**Comment by Chealer** [comment]
The file now indicates 0.87.4 and [seems to be regularly outdated](https://github.com/outline/outline/commits/main/LICENSE), so I suppose this was resolved.
