### ISSUE TITLE
fail to logout

### ISSUE THREAD

**Issue by sweeticetea** [outline/outline#6586]
**To Reproduce**
1. Click on logout
2. see the Page has refreshed
3. still remain login status

**Expected behavior**
logout to the login page

**Screenshots**
![image](https://github.com/outline/outline/assets/54834868/ba98d262-9aa0-4cbf-8938-1839e4262c36)

**Screencast**

https://github.com/outline/outline/assets/54834868/6ef8543f-5aaa-47b6-8b91-7736e720d58e

**Outline (please complete the following information):**
- Install: [self hosted]
- Version: [0.75.2]

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [chrome]
 - Version [ 121.0.6167.187]

**Comment by tommoor** [comment]
Your screenshot failed to load, please provide more information in order to debug – a screencast would be idea.

**Comment by sweeticetea** [comment]
reload the screenshot @tommoor

**Comment by tommoor** [comment]
Are you using OIDC login? You will need to with set `OIDC_DISABLE_REDIRECT=true` or point `OIDC_LOGOUT_URI` at your OIDC providers logout uri.
