### ISSUE TITLE
Outline doesn't recognize correct HSTS header (Strict Transport Security bug)

### ISSUE THREAD

**Issue by recklessnl** [outline/outline#6593]
I use Caddy to reverse proxy my Outline instance to a private domain. I reverse proxy many services this way. I use the following headers for every service on each of my subdomains, including Outline:

```
header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
		#X-Xss-Protection "0"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "SAMEORIGIN"
		Cache-Control "public, max-age=15, must-revalidate"
		Content-Security-Policy "frame-ancestors 'self'"
		Cross-Origin-Opener-Policy "same-origin-allow-popups"
		Cross-Origin-Resource-Policy "same-origin"
		Referrer-Policy "strict-origin-when-cross-origin"
		Permissions-Policy "accelerometer=(none); ambient-light-sensor=(none); autoplay=(self); camera=(none); encrypted-media=(none); fullscreen=(self); geolocation=(none); gyroscope=(none); magnetometer=(none); microphone=(none); midi=(none); payment=(none); picture-in-picture *; speaker=(none); sync-xhr=(none); usb=(none); vr=(none)"
	}
```

For each domain I have, HTST gets properly recognized and passes the HTST tests on [Mozilla Observatory](https://observatory.mozilla.org/). But Outline for some reason is the only service that I reverse proxy that does not recognize the HTST header:

![image](https://uploads.linear.app/47519575-84a7-4b8b-8a29-c645d1bb39ee/e51dd83e-b337-4dec-b59b-d8726ade4d7c/97e717e5-0bec-4fc7-be19-fe83f95fdfc0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQ3NTE5NTc1LTg0YTctNGI4Yi04YTI5LWM2NDVkMWJiMzllZS9lNTFkZDgzZS1iMzM3LTRkZWMtYjU5Yi1kODcyNmFkZTRkN2MvOTdlNzE3ZTUtMGJlYy00ZmM3LWJlMTktZmU4M2Y5NWZkZmMwIiwiaWF0IjoxNzA4NzQ2MzIwLCJleHAiOjMzMjc5MzA2MzIwfQ.sp7B6eD4uLsvjQgGl0l8MB80OIJjAN3ltPunQlgSLcs)

With the exact same headers and the exact same caddy reverse proxy setup, all my other services recognize HTST just fine and pass the Mozilla Observatory test, which leads me to believe this has something to do with Outline.

* Outline version: 0.75.2
* Caddy version: v2.7.6 h1
* OS: Debian 12.1
* Using local file storage for images, not S3.
* Browser: Mozilla Firefox

In Firefox, it will look like this:

![Screenshot (7)](https://uploads.linear.app/47519575-84a7-4b8b-8a29-c645d1bb39ee/5754f390-c405-4089-9fdc-c436e032dadd/8b2f2f7a-a443-44e1-895e-8af914255b09?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQ3NTE5NTc1LTg0YTctNGI4Yi04YTI5LWM2NDVkMWJiMzllZS81NzU0ZjM5MC1jNDA1LTQwODktOWZkYy1jNDM2ZTAzMmRhZGQvOGIyZjJmN2EtYTQ0My00NGUxLTg5NWUtOGFmOTE0MjU1YjA5IiwiaWF0IjoxNzA4NzQ2MzIwLCJleHAiOjMzMjc5MzA2MzIwfQ.VWZh2iPPx1F_JCLkUByBkdJDqUOD4DfR9u_B1E4Dsek)

![image](https://uploads.linear.app/47519575-84a7-4b8b-8a29-c645d1bb39ee/5e3486d4-aad0-4d26-ac96-14eb7997bfa6/ea829cf8-dd4f-446e-89fe-e4502a657019?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQ3NTE5NTc1LTg0YTctNGI4Yi04YTI5LWM2NDVkMWJiMzllZS81ZTM0ODZkNC1hYWQwLTRkMjYtYWM5Ni0xNGViNzk5N2JmYTYvZWE4MjljZjgtZGQ0Zi00NDZlLTg5ZmUtZTQ1MDJhNjU3MDE5IiwiaWF0IjoxNzA4NzQ2MzIwLCJleHAiOjMzMjc5MzA2MzIwfQ.gYtWz0fCo2JIb23I1B-qZ1hG970k4_taYPsvgr0M5Fc)

**Comment by tommoor** [comment]
I'm not really clear what the bug is you're describing, headers served from your proxy are not really related to Outline itself?

**Comment by recklessnl** [comment]
The current headers listed above work fine in other apps (Home Assistant, Rocket Chat, etc etc) but for some reason only Outline doesn't parse the HTST header. The code is the same - so it makes no sense why Outline doesn't parse the HTST line like the other apps do (which would be the expected behavior)

**Comment by tommoor** [comment]
> Outline doesn't parse the HTST header

I'm sorry, I still don't know what you mean by "parse the header"?

**Comment by ksaadDE** [comment]
> I'm sorry, I still don't know what you mean by "parse the header"? The proxy is further forward in the stack than Outline, which as no knowledge of the HSTS header you're adding

I assume it is in the similar category of issues like the HTTP Basic Auth Header. 
If outlinewiki sets HSTS it overwrites the forwarded header (if configure like that) and in the case of HTTP Basic Auth it overwrites the needed field as well.  Or likely it drops the HSTS at some point. 

idk what framework you are using (node.js?) for the web server but looking into this is worthy (for example):
https://github.com/outline/outline/blob/main/server/middlewares/authentication.ts

**Comment by recklessnl** [comment]
Exactly, well said. As stated in my initial post - only Outline uniquely has this issue.

**Comment by tommoor** [comment]
Open to a PR to address this

**Comment by tommoor** [comment]
Right, but a HSTS header is already in all app responses – this isn't missing. The header defaults to the following:

`Strict-Transport-Security: max-age=15552000; includeSubDomains`

**Comment by tommoor** [comment]
Closing this out as I'm unable to map this report to any behavior in Outline, as above HSTS is included on all production responses. The issue here is very likely somewhere in your own configuration

**Comment by ksaadDE** [comment]
> I'm not a programmer, but @ksaadDE do you have an idea on how to fix this?

Not for outline, but you probably have to drop the HSTS header that is being sent by outline and then overwrite it. At least that's a thought on this on the rproxy side.  The overwriting is probably the issue. 

@tommoor the question is, why is it not working with outline but working with most other apps?

**Comment by tommoor** [comment]
I'm still missing a proper description of what "not working" means in this case – if you can communicate exactly what _Outline_ is doing wrong in terms of expected vs actual behavior then that would be useful. Once you involve a proxy it's no longer in Outline's domain.

**Comment by ksaadDE** [comment]
> Once you involve a proxy it's no longer in Outline's scope.

The question is why does outline break the proxy functionality, when other web apps work fine with the similar or even same configuration? That should be worth investigation on your side.

Everyone of us uses proxies nowadays (nginx, lighthttpd, caddy etc). Especially in a Docker or Kubernetes environment it is of uttermost importance that the proxies can work with your web app.

> what "not working" means in this case 

A variety of outline functionalities are not working. Especially the websocket stuff breaks, which even does not work after proper configuration. Or in this case the HSTS Header, or in the other case the HTTP Basic Auth Header.

**Comment by kenji21** [comment]
> Right, but a HSTS header is already in all app responses – this isn't missing. The header defaults to the following:
> 
> `Strict-Transport-Security: max-age=15552000; includeSubDomains`

Can the value be setted ?

> The max-age must be at least 31536000 seconds (1 year).
from https://hstspreload.org page via https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Strict_Transport_Security_Cheat_Sheet.html
