### ISSUE TITLE
Issue with using dash character in page title

### ISSUE THREAD

**Issue by tsl8r** [outline/outline#660]
When you add a dash to the title of a post it throws a slash to escape the character in the title of the page. In this example `Data - Pell Graduation Rates` converts to `Data \- Pell Graduation Rates`

![screen shot 2018-05-31 at 10 52 10 am](https://user-images.githubusercontent.com/6257209/40796060-0f43200a-64c1-11e8-961c-8e4c1cf56ed1.png)

I'll probably take this task but I wanted to list it out in case it was already resolved in a separate PR.

**Comment by tommoor** [comment]
Thanks @tsl8r – will take a look at this as a relatively high priority one 😄

**Comment by tommoor** [comment]
@tsl8r fixed up, thanks for the issue 🙏. You will still see the slashes appear in previously saved document titles until the document is saved again.
