### ISSUE TITLE
API Responding 403 when Publish true

### ISSUE THREAD

**Issue by josephlalley1** [outline/outline#6608]
When using GetOutline API to update a document, it is responding with 403 when the publish is set to true, and the doc you want to update is NOT a draft. 

This difference may have appeared in 0.75.x as we didn’t have an issue before.

**To Reproduce**
1. Spin up Outline locally.
2. Create a document and publish it
3. Then attempt to CURL an update to the document (ensure that PUBLISH: TRUE) is in the curl command
curl -X POST 'https://app.outline.dev/api/documents.update' \
    --header "authorization: Bearer $OUTLINE_TOKEN_LOCAL" \
    --header 'content-type: application/json' \
    --header 'accept: application/json' \
    --data '{
        "id": "test-dPSCO2ULAJ",
        "title": "API test",
        "text": "hello",
        "append": true,
        "publish": true
    }'

**Expected behavior**
Judging from the docs, I would say this is expected behaviour, BUT it sending back a 403 is very misleading, a better response message would be useful.
{"ok":false,"error":"authorization_error","status":403,"message":"Authorization error"}

**Outline (please complete the following information):**
- Install: Local [getoutline.com]
- Version: 0.75.x

**Comment by tommoor** [comment]
This was fixed here bc3271b4ab2c7aa07e3147cbb31b160fc1b69b83 and will be in the next release. In the meantime don't pass `publish: true` unless explicitly publishing a draft, as a workaround.
