### ISSUE TITLE
Backups do not save emoji icons, videos and preferences

### ISSUE THREAD

**Issue by saint11** [outline/outline#6613]
**To Reproduce**
1. Backup your database in Settings>Export>Export Data
2. Go to your new Outline instance
3. Import it

**Expected behavior**
It should restore everything, including videos and server preferences.

**Screenshots**
Videos look like this:
![image](https://github.com/outline/outline/assets/4672703/121fb633-9b5a-4a12-bf19-7060326a7a14)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.75.2
 - Firefox

**Comment by tommoor** [comment]
> It should restore everything, including videos and server preferences.

This is not how it's designed, export is for exporting documents not as a backup of the server. Which export option are you using? There are three…

**Comment by tommoor** [comment]
Yes, agreed!
