### ISSUE TITLE
Print wiki page shows a scroll

### ISSUE THREAD

**Issue by rgomezceis** [outline/outline#6615]
If I want to print a page using Edge/Chrome it shows a scroll.

![image](https://uploads.linear.app/47519575-84a7-4b8b-8a29-c645d1bb39ee/94430d68-0da4-43e9-9704-4ab39b64e1bc/2a96da08-093f-442c-8d16-95c4b9628476?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQ3NTE5NTc1LTg0YTctNGI4Yi04YTI5LWM2NDVkMWJiMzllZS85NDQzMGQ2OC0wZGE0LTQzZTktOTcwNC00YWIzOWI2NGUxYmMvMmE5NmRhMDgtMDkzZi00NDJjLThkMTYtOTVjNGI5NjI4NDc2IiwiaWF0IjoxNzA5MzAwMDI4LCJleHAiOjMzMjc5ODYwMDI4fQ.0YeYLCMrUoXzAdt4mySzOQrTpsuE6LKKdh3HPV27j5k)

However in Firefox works well

![image](https://uploads.linear.app/47519575-84a7-4b8b-8a29-c645d1bb39ee/6744c20e-a1b9-4315-8e73-048ac63d5314/cce7a2d1-9f72-4fad-bbdf-930291c4b2bb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQ3NTE5NTc1LTg0YTctNGI4Yi04YTI5LWM2NDVkMWJiMzllZS82NzQ0YzIwZS1hMWI5LTQzMTUtOGU3My0wNDhhYzYzZDUzMTQvY2NlN2EyZDEtOWY3Mi00ZmFkLWJiZGYtOTMwMjkxYzRiMmJiIiwiaWF0IjoxNzA5MzAwMDI4LCJleHAiOjMzMjc5ODYwMDI4fQ.gkILjTPJyMn1q_f_N7me6VwHZ739Ei8e4lDJ0SH9bnQ)

**Comment by tommoor** [comment]
I cannot reproduce at all, if you have any more details on the type of content that causes this to happen it might help. Can you share the page?

**Comment by rgomezceis** [comment]
> I cannot reproduce at all, if you have any more details on the type of content that causes this to happen it might help. Can you share the page?

Here: [conceptos-basicos-kubernetes.md](https://github.com/outline/outline/files/14457822/conceptos-basicos-kubernetes.md)

**Comment by AipNooBest** [comment]
I confirm the bug, after updating from 0.74.0 to 0.75.2 not only the scroll bar appears, but also all other pages are not loaded - only the first page is displayed. However, the number of pages increases depending on the size of the document
![image](https://github.com/outline/outline/assets/47401054/cf70bad8-6235-46c3-8c2d-3944e9204702)

**Comment by Pranav2612000** [comment]
Did a git bisect and looks like https://github.com/outline/outline/commit/53ff144f0021bee3c4ca6ca305fdeb2b201f7d57 is the problematic commit. Will look into it more and have a fix ready soon.

**Comment by tommoor** [comment]
That makes sense, in it's own way – must be rendering inside the MobileWrapper for some reason when printing. I've still not been able to reproduce, could be a Windows thing?

**Comment by Pranav2612000** [comment]
I was able to reproduce it on a mac ( although on a local development build ).
The issue is due to https://github.com/outline/outline/blob/fd34a6d19c6c9190c583f0594339eab1ef81e39c/app/components/MobileScrollWrapper.tsx#L11
