### ISSUE TITLE
401 Unauthorized error for shared documents

### ISSUE THREAD

**Issue by fan-wen** [outline/outline#6625]
This bug is happening to me (self-hosted, v0.75.2) and also observable on the official website - e.g. [https://docs.getoutline.com/s/hosting/doc/requirements-ULdYnwi4wG](https://docs.getoutline.com/s/hosting/doc/requirements-ULdYnwi4wG)

**To Reproduce**
1. Go to [any shared page link](https://docs.getoutline.com/s/hosting/doc/requirements-ULdYnwi4wG)
2. Click on developer console
3. See error

```
api/documents.info 401 (Unauthorized)
api/collections.info 401 (Unauthorized)
api/auth.info 401 (Unauthorized)
```

**Expected behavior**
No authentication should be required (and therefore no error) if a visitor is accessing a shared page.

**Comment by tommoor** [comment]
Hi, this is not an error – it's behaving as designed, the request is to check if you're logged in.
