### ISSUE TITLE
HTML import breaks code by escaping dollar signs

### ISSUE THREAD

**Issue by panos--** [outline/outline#6638]
The HTML import performs dollar sign escaping over the whole document. This also escapes dollar signs in code (inline and blocks). But in code, other than in regular text, these escapes are preserved when rendering the document.

This also affects the Confluence import, effectively halting our migration effort.

**To Reproduce**
Save the following HTML code as file and import using the *Import document* action.

```html
<!DOCTYPE html>
<html>
    <head>
        <title>Code Block Dollar Signs</title>
        <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>

    <body>

<p>Here is a shell script:</p>
<pre><code>foo=($BASH $BASH_VERSION)
for i in &quot;${foo[@]}&quot;; do
    printf &#39;%s=%s\n&#39; &#39;\$i&#39; &quot;$i&quot;
done</code></pre>
<p>And this is inline code: <code>i=3; echo "\$i=$i"</code></p>
<p>And this is just an amount of money: $100</p>
<p>And this is an escaped dollar sign: \$</p>

        </body>
</html>
```

This results in the following Markdown:

````markdown
Here is a shell script:

```
foo=(\$BASH \$BASH_VERSION)
for i in "\${foo[@]}"; do
    printf '%s=%s\n' '\\$i' "\$i"
done
```

And this is inline code: `i=3; echo "\\$i=\$i"`

And this is just a an amount of money: \$100

And this is an escaped dollar sign: \\\$
````

Note that all the dollar signs in code are escaped.

**Expected behavior**
Instead, it should be converted into this Markdown:

````markdown
Here is a shell script:

```
foo=($BASH $BASH_VERSION)
for i in "${foo[@]}"; do
    printf '%s=%s\n' '\$i' "$i"
done
```

And this is inline code: `i=3; echo "\$i=$i"`

And this is just a an amount of money: \$100

And this is an escaped dollar sign: \\\$
````

**Screenshots**
n/a

**Outline (please complete the following information):**
- Install: self hosted
- Version: outlinewiki/outline-enterprise:0.75.3

**Desktop (please complete the following information):**
n/a

**Mobile (please complete the following information):**
n/a

**Comment by panos--** [comment]
Locally I tested the following fix.

Remove this block from [server/commands/documentImporter.ts](https://github.com/outline/outline/blob/fd34a6d19c6c9190c583f0594339eab1ef81e39c/server/commands/documentImporter.ts#L66-L68):

```ts
  // Escape any dollar signs in the text to prevent them being interpreted as
  // math blocks
  text = text.replace(/\$/g, "\\$");
```

Instead, escape dollar signs using turndown's escaping mechanism by adding the following line to the escapes in [server/utils/turndown/index.ts](https://github.com/outline/outline/blob/fd34a6d19c6c9190c583f0594339eab1ef81e39c/server/utils/turndown/index.ts#L60):

```ts
  [/\$/g, "\\$"],
```

Seems to work fine. But I don't know if it's the best solution.

If desired I could submit a PR.

**Comment by tommoor** [comment]
> If desired I could submit a PR.

Feel free, it sounds like the correct approach
