### ISSUE TITLE
Can't rename documents and problems with deleting drafts

### ISSUE THREAD

**Issue by DamienMrtl** [outline/outline#6648]
When renaming a document the old name is showing even after refresh.
Can't delete draft documents.

https://github.com/outline/outline/assets/7550391/114b0b1d-f62b-42db-adee-0458ed6b3f7b

https://github.com/outline/outline/assets/7550391/160750b6-41f6-4717-9d2e-9a88530fc978

**Outline (please complete the following information):**
- Install: Self hosted Docker
- Version: 0.75.2 (Docker tag)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 122.0.6261.94

**Comment by tommoor** [comment]
Next step would be to open the browser developer tools and see which requests are failing and why

**Comment by DamienMrtl** [comment]
The delete request seems to work fine:
<img width="653" alt="image" src="https://github.com/outline/outline/assets/7550391/db676ee8-bb8e-4a9b-908e-ba530753ac4b">

<img width="746" alt="image" src="https://github.com/outline/outline/assets/7550391/01b0664b-bfe7-4011-a03a-38138467d25e">


And then I get a 404 on the documents.info request:
<img width="732" alt="image" src="https://github.com/outline/outline/assets/7550391/5af95abe-10b7-4543-8664-0771f0e77b12">

Idk if this is normal because the document just was deleted. But also it's strange it's not the save id used in this requrest vs the delete request, but it is for the same doc.
