### ISSUE TITLE
Exported MD files end with backslash

### ISSUE THREAD

**Issue by CR0CKER** [outline/outline#6672]
**To Reproduce**
1) Export any file ad markdown
2) open MD file in a text editor
3) See backslash that should not be there if the purpose is to export proper markdown

**Expected behavior**
Exported MD files should not contain a backslash at the end of the file that's not visible in Outline prior to exporting. 

**Outline (please complete the following information):**
- Install: getoutline.com

**Comment by tommoor** [comment]
This occurs if you have blank spaces at the end of the document 👍
