### ISSUE TITLE
Webhook plugin does not send a notification

### ISSUE THREAD

**Issue by iljalukin** [outline/outline#6673]
It seems that in the line https://github.com/outline/outline/blob/main/plugins/webhooks/server/processors/WebhookProcessor.ts#L27 ``DeliverWebhookTask.schedule({ event, subscriptionId: subscription.id })`` is not executed. If I change it to ``new DeliverWebhookTask().perform({ event, subscriptionId: subscription.id })``, it works again.
I think it is related to changes in the commit https://github.com/outline/outline/commit/f9a11a28d8fadecda301cc68c51199957af3d213.

Best regards 
Ilja

**Comment by tommoor** [comment]
Thanks for the find, this code is not yet in a released version. closed in fb50b8440022a026e5b0c68f7fd29151a8d52dfb
