### ISSUE TITLE
Collection Permissions

### ISSUE THREAD

**Issue by tommoor** [outline/outline#668]
> It would be nice to have a way to set "View / Edit Permissions" on Collections & Documents. This way documentation could be locked down and viewed (or edited) only by specific users on the team.

### UX

In a first instance it would be good to have this at a collection level. By default all collections currently give write access to everyone.

One idea for the UI/UX would enable you to modify 'everyone' as a group that can have read/write toggled or removed altogether. That way you can set up the permissions easily to be a number of variations:

- everyone write access
- everyone read, and single / multiple user write access
- single user write access
- multiple user read access / multiple user write access

#### Membership

```
userId (optional, either userId OR role)
role
collectionId
createdById
createdAt
deletedAt
```

Thread: https://spectrum.chat/outline?thread=c4eb57e4-10c5-48ef-a1f3-626ba7c5c32f

**Comment by satyadeepk** [comment]
Collection level permissions seem to be a good idea to start with. Use-case wise, collections are vaguely mapped to various teams in a company.

Just trying to understand the above schema. 
Is `role`  referring to a group of users?  If so, shouldn't we need a `permission` column in the above table with READ/WRITE values?

What will the default permissions be? (Assuming `everyone` is a group and all new members automatically join that group)

**Comment by tommoor** [comment]
Trying to remember my thinking now, this was meant as a note to jog my memory only 😄.

I believe `role` would be better named as `group`, and be an enum that only accepts "everyone" for now and you're right about `permission` being needed. Default permissions would remain as they are today so everyone can read and write. So, something like:

| column       | type            | required |
|--------------|-----------------|----------|
| userId       | uuid            | optional |
| group        | enum "everyone" | optional |
| permission        | enum "read", "read_write" | optional |
| collectionId | uuid            | required |
| createdById  | uuid            | required |
| createdAt    | datetime        | required |
| updatedAt    | datetime        | required |

**Comment by satyadeepk** [comment]
Makes more sense now.

Group would also need a group_members table for user-group mapping, right?

Also, if the same user satisfies multiple permissions, some convention would be needed to determine the precedence.

**Comment by kjano** [comment]
Just to express support for this idea: I would love a feature to have collection-level user permissions, e.g., for private slack channels.

**Comment by mashdot** [comment]
Just was looking for an alternative to Gitbook to manage documentation spaces for various clients. The biggest feature I need is team management. That is being able to create documentation / collections which can only be seen and edited by certain users. Then have common documentation that can be seen and read only by everyone.

Basically it would be great to have team / user management of collections and documents, including hiding collections from the menu to those who do not have access.

**Comment by tommoor** [comment]
Hey folks, a first version of this is now live which enables setting a collection private and inviting only specific team members. Click on the overflow (...) menu, and then "Permissions…" to manage:

![image](https://user-images.githubusercontent.com/380914/50729749-f11fc800-10f3-11e9-9016-dc9cf7b1ab0a.png)

**Comment by satyadeepk** [comment]
Just tried it - it's simple and works great! 👍 
Should link sharing be enabled by default for private collections? Or should it be configurable on a per collection basis?

I noticed a little issue in the current link sharing implementation. When a user shares a public link to a private document I don't have access to, it does not open when I am logged in (gives 403). But works fine in logged out state.
Also, I can see that document in /settings/shares screen, even when I don't have access to it.

**Comment by tommoor** [comment]
> Should link sharing be enabled by default for private collections? Or should it be configurable on a per collection basis?

Right now it's global, but I had a similar thought – that it would be good to be able to disable per-collection.

> When a user shares a public link to a private document I don't have access to, it does not open when I am logged in 

I'll check into these issues as a matter of priority 👌

**Comment by nayatec** [comment]
Yes ! Great thank you ! It's a start, but already very usefull !

**Comment by tommoor** [comment]
The bugs are addressed and the first pass of the feature is deployed and release. Closing this out and opened two more granular followup issues:

https://github.com/outline/outline/issues/840
https://github.com/outline/outline/issues/841
