### ISSUE TITLE
Copying text discards formatting

### ISSUE THREAD

**Issue by foreverigor** [outline/outline#6681]
I don't know if this counts as a bug or a feature request. When copying text in Outline 
all formatting and, under some circumstances, information is lost.

**To Reproduce**
Copy text with any formatting enabled and paste it in Outline.

**Expected behavior**
Some (or all) formatting is retained when copying

**Screenshots**
All formatting and all custom structure (lists, etc) is lost when text is copied.
This is especially problematic for text with urls where the information is part of the
"formatting". See here for an example:
<img width="685" alt="Screenshot 2024-03-16 at 22 32 52" src="https://github.com/outline/outline/assets/32497625/ef8fdbc1-b2d9-4623-b5d4-49e1067ec00b">

**Outline (please complete the following information):**
- Install: Self-hosted
- Version: 0.75.2/ 7685637 (latest docker image)

**Desktop (please complete the following information):**
 - OS: macOS, iOS
 - Browser: Chrome/ Any

**Comment by tommoor** [comment]
You are copying from Outline and pasting into Outline? Are you sure you don't have a browser extension or something similar operating on the clipboard content?

This is core functionality, I can't reproduce at the moment

**Comment by foreverigor** [comment]
> You are copying from Outline and pasting into Outline? Are you sure you don't have a browser extension or something similar operating on the clipboard content?
> 
> This is core functionality, I can't reproduce at the moment

You're right, I must have messed up something in my settings
