### ISSUE TITLE
When a query fails provide the SQL query in the logs

### ISSUE THREAD

**Issue by bmm-alc** [outline/outline#6691]
_Originally posted by @bmm-alc in https://github.com/outline/outline/discussions/6686#discussioncomment-8832042_

Having the SQL query that would have save us a lot of time when trying to understand which component was failing.

**Comment by tommoor** [comment]
I think generally this is considered unwise as it's easy for confidential values to end up in the logs. We have datadog tracing throughout which provides this information sanitized inside DataDog when an error occurs

**Comment by bmm-alc** [comment]
Hi Tom,

I understand your point, but for those who don't use datadog or sentry (our case) is there something that could facilitate troubleshooting such issue.

Thanks

**Comment by tommoor** [comment]
Ah yes, I just remembered you can set `DEBUG=database` and all database queries will be output to the console, this should suffice?

**Comment by bmm-alc** [comment]
Hi Tom,

I forgot to write we activated this while troubleshooting but it did not add values, we only get such messages
```
2024-03-18 15:35:06.497 {"label":"database","level":"info","message":"Document 2fc4fc6e-ee9a-4411-a2f7-b5d9231e11a2 is in database state"}
``` 
nothing else

**Comment by tommoor** [comment]
Hmm yes, would need `LOG_LEVEL=debug` as well for those to be output. Perhaps we can add a warning or something if `DEBUG` configuration is set without the log level.
