### ISSUE TITLE
Self-hosted iframely is difficult to configure

### ISSUE THREAD

**Issue by cdauth** [outline/outline#6694]
I have set up a self-hosted instance of iframely and tried to configure it in Outline.

I encountered the following pain points:
1. It seems that iframely support is only enabled when `IFRAMELY_API_KEY` is not empty. For a self-hosted instance of iframely, no API key is required. As a workaround, I set `IFRAMELY_API_KEY=none`, which the self-hosted instance doesn't seem to mind.
2. Outline seems to make requests to `${IFRAMELY_URL}/api/oembed`. However, the API for self-hosted instances is reachable under `/oembed`. As a workaround, I have configured a redirect from `/api/` to `/` on my iframely instance.

I would suggest the following improvements:
1. Enable iframely support if `IFRAMELY_URL` *or* `IFRAMELY_API_KEY` is not empty.
2. Make requests to `${IFRAMELY_URL}/oembed`. If someone requires `/api` in their URL for some reason, they can always append that to `IFRAME_URL`.

**Comment by tommoor** [comment]
This was primarily built for the cloud product so you might be the first person to actually try and run it against a self-hosted iframely  😉 

Thanks for the feedback

**Comment by cdauth** [comment]
Amazing, thank you!
