### ISSUE TITLE
Keycloak and Outline : email required

### ISSUE THREAD

**Issue by romstann** [outline/outline#6698]
### Discussed in https://github.com/outline/outline/discussions/6697

<div type='discussions-op-text'>

<sup>Originally posted by **romstann** March 21, 2024</sup>
Hi everyone, 

I'm trying to setup Outline since a week, and now I'm stuck on the authentification problem. 
I set up Keycloak, create a realm, a user, and when I try to login into outline, I get this error message : 

`{"error":"An email field was not returned in the profile parameter, but is required.","level":"error"`

Email is set up onto Keycloak for the user and here is my SCOPE : 
`OIDC_SCOPES="openid email"`
I've try already multiple things : 
`OIDC_SCOPES=openid email`
`OIDC_SCOPES=openid profile email`

I've found lots of issues regarding this email problem but no one get an answer with a solution that's work for me. 

In Keycloak, I found the session as active, authentification is working. 
I have activate user logs into Keycloak and LOGIN & CODE_TO_TOKEN are working fine. 
Into Client SCOPE : Email, Profile are on the "Default" status
Into Realm Configuration : Login with email is checked

both services are running on the same docker network. 

If you have any idea it could be very nice 🙏 </div>

**Comment by tommoor** [comment]
This is a configuration issue with Keycloak, not a bug in Outline – you already have the discussion open, which is the right place for this.
