### ISSUE TITLE
Insert document link with "+" character

### ISSUE THREAD

**Issue by tommoor** [outline/outline#670]
It would be useful to match the shortcut provided by Paper to search and insert a document while typing with the + shortcut. There is a useful plugin for 'suggestions' in Slate that could do most of the heavy lifting:

https://yarnpkg.com/en/package/slate-suggestions

**Comment by thenanyu** [comment]
Yeah I would like to see some kind of keyboard shortcut — how about a raw CMD+K without anything highlighted? That seems like it would be consistent with the current behavior of the link menu

**Comment by msantic** [comment]
Hey @tommoor, any news on this? My company is considering Outline for our next knowledge base system but missing this feature. I can also help with implementation if it's not high on your prioriry list right now...

**Comment by tommoor** [comment]
Work is ongoing here – https://github.com/outline/rich-markdown-editor/pull/189 – I believe there is more complete than has been pushed to the repo, it's almost done.

**Comment by MatheusRV** [comment]
@tommoor This is already done?

**Comment by thenanyu** [comment]
https://twitter.com/outlinewiki/status/1278044885178707968?s=20
