### ISSUE TITLE
triple-click issue while edit a code block

### ISSUE THREAD

**Issue by dalamudx** [outline/outline#6701]
it contains the first letter of next line while triple-click on a line

**To Reproduce**
1. Create a code block.
3. Click on copy button.
4. Paste the code into another code block.
5. Triple-click on pasted code line and paste it.

**Expected behavior**
a triple-click select 1 line

**Screenshots**
![recording](https://github.com/outline/outline/assets/88395653/030cc72f-0f72-41ca-8247-f95f1548cecc)

**Outline (please complete the following information):
- Install: self hosted
- Version: 7685637

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 118.0.5993.159

**Mobile (please complete the following information):**

**Comment by tommoor** [comment]
Unfortunately I haven't been able to reproduce so far, are you able to reproduce the issue on getoutline.com?

**Comment by dalamudx** [comment]
> getoutline.com

yup,same as self hosted
![recording](https://github.com/outline/outline/assets/88395653/2e2d8473-3a33-41c2-a3b9-f0698b29ac40)
i tried firefox works fine,then update to the latest chrome,also browse in private,still have the same issue.

**Comment by tommoor** [comment]
Gotcha, I still can't reproduce in chrome unfortunately.

We don't actually do anything special for this behavior, it's just the browser default. Perhaps try turning off the line numbers (In settings -> preferences) and see if that makes a difference at all.

**Comment by dalamudx** [comment]
Odd,these are also the same.I think its my os env's fault,it would have a negligible effect for me.
Should i close the issue?if people are facing the same problem,then reopen it.

**Comment by tommoor** [comment]
> Should i close the issue?if people are facing the same problem,then reopen it.

Yes, I think that's the way right now. If others are able to reproduce we'll reopen.
