### ISSUE TITLE
Outline not invalidating login token on firefox

### ISSUE THREAD

**Issue by RichardLourens** [outline/outline#6725]
I have connected outline with our local ADFS service. I have set the outline "OIDC_LOGOUT_URI" parameter to point to our ADFS logout endpoint, which correctly invalidates the ADFS token. However, while using firefox, when I return to outline, the user is still logged in. If i go to my same outline instance with chrome and login + logout there aswell, the login token is succesfully deleted and both browsers have logged out the user correctly. 

When looking at the cookie access token value, using the browser developer tools,  I can see that it remains the exact same after logging out and back in on firefox. Which isn't the case on chrome. 

**To Reproduce**
1. login with ADFS on firefox
2. logout with ADFS on firefox
3. return to outline and notice the user is still logged in
4. Login + logout with ADFS on chrome.
5. The user is now correctly logged out of outline. 

**Expected behavior**
Expect outline to remove the access token for the user when pressing the logout button on firefox.

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.75.2

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Firefox 123.0 (64-bit)
 - Chrome 120.0.6099.224

**Comment by tommoor** [comment]
Hi RichardLourens, 

This sounds like expected behavior – logging out on ADFS does not immediately cancel any associated Outline session, but the session will be checked at a maximum of every 5 minutes. I think this is what you're seeing here

**Comment by RichardLourens** [comment]
Hi tommoor, thanks for the response. I forgot to add some information, my apologies. This behaviour is explicitly only seen on Firefox. When I logout using chrome, the user is correctly and instantly logged out, returning to outline sends me back to the outline login screen. (which is what I expect to happen).

If it were as you state, I would expect the user to also still be logged in on chrome after pressing the logout button, which isn't the case.

**Comment by tommoor** [comment]
closed by e0ae044f4
