### ISSUE TITLE
Documents on thrash are visible by everyone

### ISSUE THREAD

**Issue by WilliamSoler** [outline/outline#6808]
**To Reproduce**
1. Delete a file from a collection whose permissions only allow accessibility by a user or group.
2. A user who could access the mentioned file before, can now see it in the thrash files

**Expected behavior**

**Outline (please complete the following information):**
- Install: self-hosted
- Version: v0.75.2

**Comment by potatoone** [comment]
I have tested it on the latest community edition and there is no problem.
Subdocuments that are deleted from a **collection** with **no access** will not be seen in the recycle bin by users without **permission**.
Unless you re-grant **collection** access to another person or group, excluding **Viewer,** after deleting the subdocument.
😉
