### ISSUE TITLE
Raw Markdown editor and preview (enhancement)

### ISSUE THREAD

**Issue by Mrbibi38** [outline/outline#6815]
Related to [787](https://github.com/outline/outline/issues/787).

Having the option of having the raw Mardown text on one side and the preview on the other would be incredible.
The option could, for example, be activated like the edit mode with a button in the top right-hand corner?

Could this feature be added? 
Or has it been squeezed out since the discussion mentioned in the ticket below?

That's the last thing we need to make this application perfect.
I recently discovered Outline and I think it's the only missing feature that keeps me on Obsidian.

Incredible work btw!

**Comment by tommoor** [comment]
Raw markdown is not compatible with many types of content that Outline aims to support or with multiplayer editing as it's implemented, it's just too limited. 

There are no plans to support this functionality. You can, however, paste Markdown into a document where it will be automatically converted.
