### ISSUE TITLE
Multiple Workspaces not supported on Self-Hosted version?

### ISSUE THREAD

**Issue by jprima** [outline/outline#6837]
I use the self-hosted option and am unable to use multiple workspaces (like I can do on the outline-hosted cloud version).

**To Reproduce**
1. Self host
2. Check the top bar and no option for add/create workspace

**Expected behavior**
option for add/create workspace

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
![2024-04-23_11-00-59](https://github.com/outline/outline/assets/21128673/3f8ac0ae-33f2-4711-a674-323b213a9bdb)

**Outline (please complete the following information):**
- Install: self hosted
- Version: [0.75.2]

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome/Brave
 - Version latest

**Comment by tommoor** [comment]
Hi, this feature is not supported in self-hosted currently. It may well come to one of the editions in the future, but closing this out for now as it's not a bug.

**Comment by delta-whiplash** [comment]
@tommoor is there any update about this implementation ?

**Comment by tommoor** [comment]
The answer is still the same here, it will never be supported in community edition

**Comment by Akorian** [comment]
>"Perhaps it would have been correct to write it among the limitations!

IMHO you can cross out "Perhaps" this must be added there... It is a real big limitation...

**Comment by ezvr** [comment]
This is horrible predatory behaviour. Finding this out, after spending 4 hours integrating this tool to our intranet is infuriating. Not listing this dealbreaker in the "pricing" category, while knowing FULL WELL that any real team needs this is horrible from your end.

I will NEVER EVER spend any € on your product, because this is dishonest, manipulative. Be honest, and list all the things you paywall upfront, like any normal business does.

**Comment by tommoor** [comment]
The feature still doesn't exist on either self-hosted edition 🤷 , it's cloud-only because of the technical complexities involved (each workspace is a subdomain).

Multiple workspaces is actually a rare need because of the complete separation it creates.

**Comment by teopost** [comment]
Without this feature the free version is completely useless.

**Comment by samuelgfeller** [comment]
I would love this feature on the self-hosted version too! Really missing it!
