### ISSUE TITLE
Windows 10 & Windows 11 Outline client not work

### ISSUE THREAD

**Issue by yazmeyaa** [outline/outline#6838]
Windows 10 & Windows 11 Outline client not work.
Windows defender disabled, firewalls disabled

Installing older version (1.8.1) solves the problem

**To Reproduce**
1. Install latest client version ([Outline Client 1.10.1](https://github.com/Jigsaw-Code/outline-apps/releases/tag/v1.10.1)) on Windows 10 or Windows 11
2. Import key
3. Try to connect

**Expected behavior**
It must work

**Screenshots**
![photo_2024-04-23_13-39-15](https://github.com/outline/outline/assets/86918027/34f42cb2-08e5-4f95-ae7e-136d31006e42)

**Outline (please complete the following information):**
- Install: [[getoutline.com or self hosted]](https://github.com/Jigsaw-Code/outline-apps/releases)
- Version: 1.10.1

**Desktop (please complete the following information):**
 - OS: Windows 10 | Windows 11
 - Browser any
 - Version any

**Comment by tommoor** [comment]
Wrong repo, this is not the correct project
