### ISSUE TITLE
Image upload issue

### ISSUE THREAD

**Issue by mhannan** [outline/outline#685]
There seems problem while copy/pasting the image. I copied image form MS Paint, which was pasted successfully in the Canvas, but all of sudden 'Unable to save changes' message appeared. 

I tried number of times but could not get success. There seems problems when we are dealing with images. Also it does not allow very easily to resume typing once you tried to past the image in document. Need to test this usability feature.

**Comment by tommoor** [comment]
Hey @mhannan ! Thanks for the report, took a look at this just now – it does seem like there is a race condition when uploading larger images that take longer than the autosave period to upload.

I was able to reproduce the error message however in my testing the document still saves correctly behind the scenes

**Comment by tommoor** [comment]
Hi @mhannan, you should find this issue resolved now.
