### ISSUE TITLE
Invalid redirect on OAuth errors when using reverse proxies

### ISSUE THREAD

**Issue by vaab** [outline/outline#6859]
Using OAuth mecanism, using a reverse proxy, and upon OAuth errors, the existing logic will fail to replace the inner hosting port (usually 3000 in a docker container), and will end up redirecting to `https://external.address.org:3000` instead of `https://external.address.org`. 

This can be traced back to: https://github.com/outline/outline/blob/main/server/middlewares/passport.ts#L43

Indeed, the serving host string in `ctx.get("host")` will be the host value received by the inner request made by the proxy... targetting the inner container and port (usually 3000). The link given to the source show it tries then to replace the internal host with a provided correct external hostname, but forgets about the port number : effectively overwriting only the host name and leaving the port number intact.

Hence the issue.

**Comment by tommoor** [comment]
What is your `URL` in env set to? If you're hitting this code path then you've already hit an error which should still remain in the url.

**Comment by vaab** [comment]
my `URL` env is set to 'https://mydomain.org' which is the internet facing domain.

This is served via *apache* in a docker container that acts as a reverse proxy, apache is told to contact `outline:3000`, which is what is required for apache to contact *outline* and is what it uses as `Host:` value in HTTP headers to query *outline* container (but it doesn't fail to provide `X-Forwarded-Host` with `mydomain.org`).

At the end, when hitting this code lines, I get redirected to `https://mydomain.org:3000`, and it is clear why in the code lines I pointed to, and I understand it as a bug (replacing only the domain part and forgetting about the port part).

**Comment by tommoor** [comment]
I believe `host` should be the external host here – your proxy should pass it through.
