### ISSUE TITLE
cannot unarchive archived documents

### ISSUE THREAD

**Issue by wildsylvan** [outline/outline#6861]
**To Reproduce**
1. Archive a document (published)
2. Go to the archive menu
3. Try to unarchive the document
4. There's no option to restore it. See screenshot

**Expected behavior**
You can unarchive the document

**Screenshots**
![image](https://github.com/outline/outline/assets/19886441/a32ded17-8a25-40b7-a644-6712361f157d)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.76.0 (f7ea19cfcd5250bf02cc5e6378592fa5d31ca006)

**Desktop (please complete the following information):**
 - OS: win 11
 - Browser: chrome
 - Version: 124.0.6367.119 (Official Build) (64-bit)

**Comment by tommoor** [comment]
I cannot reproduce, does the option appear after reloading the app?

**Comment by wildsylvan** [comment]
nop :/

can you try to archive a document with sub documents? and then try to archive a root document?
