### ISSUE TITLE
Upgrade indicator showing "Up to date" when upgrade is available

### ISSUE THREAD

**Issue by multipleofzero** [outline/outline#6872]
**To Reproduce**
1. Go to 'Preferences'
2. In the sidebar, check the version indicator under 'Installation'
3. It says 'Up to date' even if there is a newer version available

**Expected behavior**
The indicator should reveal that there is an upgrade available

**Screenshots**
These screenshots are from before and after an upgrade (i.e. a few minutes apart on May 6th 2024)
![Screenshot 2024-05-06 at 10 02 15](https://github.com/outline/outline/assets/51087741/43d172a4-1e26-46a8-83ff-5e34953521f9)
![Screenshot 2024-05-06 at 10 15 20](https://github.com/outline/outline/assets/51087741/0a8ee926-8dff-4c62-9546-1d18114911f4)

**Outline (please complete the following information):**
- Install: self hosted (container, enterprise)
- Version: v0.75.4 (before), v0.76.1 (now); both from hub.docker.com

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1
 - Browser: Firefox (125.0.2)
 - Browser: Chromium (117.0.5846.0)

**Comment by tommoor** [comment]
Could you reload the page and see if a request to the github API is successfully made?

**Comment by multipleofzero** [comment]
Sorry for the long wait. I have checked the request to the github API and it is successful (returns HTTP 200 status code). But then, there currently is no newer version... Maybe I should check again when there is an update available?

Here is the start of the JSON reply received from the github API:

`[
  {
    "url": "https://api.github.com/repos/outline/outline/releases/154007586",
    "assets_url": "https://api.github.com/repos/outline/outline/releases/154007586/assets",
    "upload_url": "https://uploads.github.com/repos/outline/outline/releases/154007586/assets{?name,label}",
    "html_url": "https://github.com/outline/outline/releases/tag/v0.76.1",
    "id": 154007586,
    "author": {
      "login": "tommoor",
      "id": 380914,
      "node_id": "MDQ6VXNlcjM4MDkxNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/380914?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tommoor",
      "html_url": "https://github.com/tommoor",
      "followers_url": "https://api.github.com/users/tommoor/followers",
      "following_url": "https://api.github.com/users/tommoor/following{/other_user}",
      "gists_url": "https://api.github.com/users/tommoor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tommoor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tommoor/subscriptions",
      "organizations_url": "https://api.github.com/users/tommoor/orgs",
      "repos_url": "https://api.github.com/users/tommoor/repos",
      "events_url": "https://api.github.com/users/tommoor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tommoor/received_events",
      "type": "User",
      "site_admin": false
    },
    "node_id": "RE_kwDOA4rpZM4JLfgi",
    "tag_name": "v0.76.1",
    "target_commitish": "main",
    "name": "v0.76.1",
    "draft": false,
    "prerelease": false,
    "created_at": "2024-05-03T13:04:58Z",
    "published_at": "2024-05-03T13:48:54Z",
    "assets": [

    ],
    "tarball_url": "https://api.github.com/repos/outline/outline/tarball/v0.76.1",
    "zipball_url": "https://api.github.com/repos/outline/outline/zipball/v0.76.1",
    "body": "### Fixes\r\n\r\n- When importing a HTML file with tables it would be imported as raw HTML if a cell contained a list or heading\r\n- Fixed an issue that prevented unarchiving documents\r\n- Fixed an issue that prevented connecting Slack channels to a collection",
    "reactions": {
      "url": "https://api.github.com/repos/outline/outline/releases/154007586/reactions",
      "total_count": 9,
      "+1": 9,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    }
  },
  {
    "url": "https://api.github.com/repos/outline/outline/releases/153386085",
<snip>
`
