### ISSUE TITLE
Error when connecting collection to Slack

### ISSUE THREAD

**Issue by matmannion** [outline/outline#688]
Clicking the Connect button sends me to this URL: https://warwick.slack.com/oauth?client_id=REDACTED&redirect_uri=https%3A%2F%2Fwww.getoutline.com%2Fauth%2Fslack.post&state=REDACTED&scope=incoming-webhook&team=&install_redirect=&single_channel=0

This just shows an error message:

```
OAuth Error: redirect_uri did not match any configured URIs.

Passed URI : https://www.getoutline.com/auth/slack.post
Allowed URI : https://www.getoutline.com/auth/slack.callback
Allowed URI : https://www.getoutline.com/auth/slack.commands
```

**Comment by tommoor** [comment]
Thanks @matmannion looks like I missed that one on the Slack settings side, I've submitted for review and just waiting on approval from Slack.

**Comment by tommoor** [comment]
The changes were approved 🎉
