### ISSUE TITLE
Webhook doesn't work

### ISSUE THREAD

**Issue by arladmin** [outline/outline#6882]
**To Reproduce**
1. Create a Webhook, like so:
![image](https://github.com/outline/outline/assets/64059154/1916f013-e359-4db8-87a3-32169a98cb0a)

2. Visit various Documents (as Public/not-logged-in)
3. The webhook doesn't execute

**Expected behavior**
The Webhook should have executed on every single view

**Outline (please complete the following information):**
- Install: [getoutline.com or self hosted] Self-hosted
- Version: [commit sha if self hosted] 0.76.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 124.0.6367.119

**Mobile (please complete the following information):**

**Comment by tommoor** [comment]
Views are only recorded for logged in users, so this is expected behavior currently

**Comment by arladmin** [comment]
@tommoor 

> Views are only recorded for logged in users, so this is expected behavior currently

So, not only there are no Analytics integrations allowed, for this 'Self-hosted/Open-Source' tool (besides Google), even the views are not allowed to be recorded!

Is this, exclusively, and 'Internal Knowledge Base-ish' tool, because the marketing doesn't immediately make that clear, and the number of limitations, for an Open-Source/Self-Hosted tool, is rather astounding?

**Comment by tommoor** [comment]
> So, not only there are no Analytics integrations allowed

Where did you read that?

> even the views are not allowed to be recorded!

The count is recorded in the database, but this does not result in a webhook. This is mainly abuse prevention, we don't want to be in a situation where a single visit to the public website generates a corresponding outgoing HTTP request from the server.

> Is this, exclusively an 'Internal Knowledge Base-ish' tool

It's certainly the main focus of the project.

**Comment by arladmin** [comment]
> > So, not only there are no Analytics integrations allowed
> 
> Where did you read that?
>

What do you mean?

How is it possible to add, example, Matomo?


> > even the views are not allowed to be recorded!
> 
> The count is recorded in the database, but this does not result in a webhook. This is mainly abuse prevention, we don't want to be in a situation where a single visit to the public website generates a corresponding outgoing HTTP request from the server.
> 

Why not?
What do you imagine all the analytics tools do in such cases?

> > Is this, exclusively an 'Internal Knowledge Base-ish' tool
> 
> It's certainly the main focus of the project.

Why is this not explicitly mentioned in all the branding? 
Why do users have to realise this by themselves, that too after wasting their time?

**Comment by tommoor** [comment]
> How is it possible to add, example, Matomo, Umami, Plausible, anything?

Well, there is a difference between not allowed and not built yet – you're welcome to contribute an equivalent integration to Google Analytics for any of these providers.

> What do you imagine all the analytics tools do in such cases?

I'm not sure of any analytics tools that would sent out a webhook for every single client side view, even if they did these tools have different usage patterns and infrastructure requirements to Outline. This was a tradeoff made to keep things performant, in 5+ years of the product existing you're the first person to request the functionality so I'd say it was a decent one.

> Why is this not explicitly mentioned in all the branding?

The tagline is literally "A fast, collaborative, knowledge base for _your team_".

As a sidenote, your general attitude comes across as rude and entitled – please contribute positively to the project, or don't contribute at all.

**Comment by arladmin** [comment]
@tommoor Why do you keep deflecting or denying things (partly the reason behind my 'rudeness').

> > How is it possible to add, example, Matomo, Umami, Plausible, anything?
> 
> Well, there is a difference between not allowed and not built yet – you're welcome to contribute an equivalent integration to Google Analytics for any of these providers. Requests have just been minimal thus far.

I responded only to your statement regarding the absence of Analytics integrations, besides Google:

> Where did you read that?

---

> in 5+ years of the product existing you're the first person to request the functionality so I'd say it was a decent one.

Really? What are these then?

1. https://github.com/outline/outline/discussions/5644
2. https://github.com/outline/outline/discussions/5087

---

> The tagline is literally "A fast, collaborative, knowledge base for _your team_".

I concede.

Although, the 'Publish to Web' feature does make the concept difficult to quickly grasp.

---

> As a sidenote, your general attitude comes across as rude and entitled – please contribute positively to the project, or don't contribute at all.

Yeah, i share those sentiments as well. But i do call out BS for what it is, when necessary.
