### ISSUE TITLE
Email Login Option Missing in Latest Docker Image

### ISSUE THREAD

**Issue by amitshuklabag** [outline/outline#6885]
I've encountered an issue while using the latest Docker image of Outline, where the option to log in with email is no longer visible, despite having OIDC enabled with vicalloy/oidc-server. I attempted to disable OIDC, but the issue persisted.

I also tested previous releases and found that the problem only occurs in versions after v0.75.0. In releases v0.75.0 and earlier, the email login option is visible.

Additionally, SMTP is enabled in my app, and the checkbox for email within the security tab is selected.

Could you please investigate this matter and provide a fix?

**Comment by AmsellemJoseph** [comment]
Hey, I also have the same issue, 

Until v0.75.0 included, email login option is visible, but after, not at all.

Thx a lot for your responses.

**Comment by hairy-tortoise** [comment]
If you create an account via
`docker compose run --rm outline node build/server/scripts/seed.js your@email.com`
you can see the button, but you can only login via the mail address specified in the command

**Comment by amitshuklabag** [comment]
only admin, then invited users not be able to use this option anymore?

**Comment by tommoor** [comment]
Do you have an `SMTP_USERNAME` defined in env?

**Comment by amitshuklabag** [comment]
I'm using local postfix and setup the required SMTP, even though it's working. I tested it by inviting users and they received email as well.

**Comment by acaisimon** [comment]
I also have the issue since the update to v0.76.
In v0.75 my env looks like this  `SMTP_USERNAME=` `SMTP_PASSWORD=`
When I set `SMTP_USERNAME` and `SMTP_PASSWORD` in v0.76 the login option is back but SMTP Auth isn't technical required.
SMTP Auth is important for security reasons but not technical required. Maybe someone can agree this.

**Comment by acaisimon** [comment]
@tommoor yes correct and it had worked until v0.76.
`SMTP_HOST=10.80.3.38
SMTP_PORT=25
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_FROM_EMAIL=foo@bar.com
SMTP_REPLY_EMAIL=foo@bar.com
SMTP_SECURE=false`

**Comment by tommoor** [comment]
Yes, this was a bad assumption on my part that any valid SMTP setup would include auth.
