### ISSUE TITLE
H5, H6: reintroduce level-5 and level-6 headings

### ISSUE THREAD

**Issue by EduNetEurope** [outline/outline#6898]
Because since a recent version, h4 (and h5 and h6) are not shown in the outline anymore ! So there is easy way to know the link

(But I feel it's not a bad thing not to have all the headings showing up in the heading)

_Originally posted by @Limezy in https://github.com/outline/outline/discussions/4153#discussioncomment-3705182_

**Comment by EduNetEurope** [comment]
When I copy & paste text from Word, I can get level-4 headings.
How can I create a level 4 heading within Outline?

**Comment by EduNetEurope** [comment]
Solved: 
You can only create new level-4 headings by typing ####, followed by the text.
It looks like you cannot turn an existing level-3 heading into a level-4 heading. :-(

**Comment by tommoor** [comment]
We won't be changing this limitation, H4 already looks the same as a bold tag – it's not possible to distinguish headings below this size.

**Comment by Enet4** [comment]
> We won't be changing this limitation, H4 already looks the same as a bold tag – it's not possible to distinguish headings below this size.

What if Outline had support for automatic numbering in the headings like this?

> # 1. Section
> ## 1.1. Subsection 1
> ## 1.2. Subsection 2
> ...
> #### 1.2.1.1. Foo
> ##### 1.2.1.1.1. Bar

Could this then be reconsidered?

I had this use case in which I'd need to follow a specification template which can have headings as deep as h6.
