### ISSUE TITLE
Cannot @mention user explicitly added to document

### ISSUE THREAD

**Issue by tommoor** [outline/outline#6901]
### Discussed in https://github.com/outline/outline/discussions/6900

<div type='discussions-op-text'>

<sup>Originally posted by **EduNetEurope** May 12, 2024</sup>
It looks like users can only be @mentioned when the collection is shared with them but not when they have been invited / added to a set of nested documents within a collection?

I am in a document.
I click on "Share". User A is listed with editing rights. 
When I add a comment and try to @mention user A, user A cannot be selected.
</div>

**Comment by EduNetEurope** [comment]
@tommoor 
Thanks for following up on it.

**Comment by tommoor** [comment]
closed in [2ecc900](https://github.com/outline/outline/commit/2ecc9009f0531f70680b32db54be911b6aa4ab18)

**Comment by EduNetEurope** [comment]
Brilliant! Thanks!
