### ISSUE TITLE
"Maximum workspaces" error when logging in with google (gmail.com)

### ISSUE THREAD

**Issue by dennorske** [outline/outline#6902]
### Discussed in https://github.com/outline/outline/discussions/6889

<div type='discussions-op-text'>

<sup>Originally posted by **dennorske** May 10, 2024</sup>
Hello!

I am running 0.76.1 with docker (compose), and I got most things set up with a breeze. I got SMTP working, and I have enabled my workspace to be logged in with Google login, configured as described in the documentation.

I created a workspace initially by logging in with my google account, linked to my Google Workspace environment (lets call it `example.com` for ease). 

Now when I try to invite a user that has a `gmail.com` address to the existing workspace:
The user goes to the login page, and tries to log in with google (same email address), and it results in outline saying 
> "error":"The maximum number of workspaces has been reached"

I have also attempted to allow gmail.com to sign up via google in the allowed domains section for the workspace in Outline.

[...]

It seems to me that new "domains" end up making new workspaces on outline. How can users I invite, log in with google, without getting that error?

I really appreciate your input. And I am very sorry if I had misunderstood something with this.</div>

Testing:

<div type='discussions-op-text'>I tried with a different (personal) email and I am still seeing the same behaviour.

   - I go to members > invite new user > write in my gmail account
   - I log out from my main domain.com account
   - I try to log in with my gmail.com account
   - Getting "Maximum reached" error.

It only happens with the OAuth provider - not if I use magic link to sign in.

</div>

**Comment by tommoor** [comment]
`v0.76.2-0` pre-release is publishing now with a probable fix for this, let me know how it goes.

**Comment by dennorske** [comment]
I confirm the issue is gone on my end, tested with my own account + 2 other users. Great work @tommoor 👏
