### ISSUE TITLE
New row with shift+enter

### ISSUE THREAD

**Issue by bruninoit** [outline/outline#6903]
**To Reproduce**
1. Create a new doc
2. Write a text line (for example First row) then use shift+enter and write another text line (for example Second row)
3. Save the doc and copy share link
4. Open the link

**Expected behavior**
See the text as
First row
Second row

But it will be showed as
First row\nSecond row

Version: 0.76.0-2
Self-Hosted

**Comment by tommoor** [comment]
I cannot reproduce, please fill out the bug template with version etc

**Comment by bruninoit** [comment]
> I cannot reproduce, please fill out the bug template with version etc

Done

**Comment by tommoor** [comment]
Unfortunately still unable to reproduce anything like this in the latest versions – here's a shared example:<br>[https://docs.getoutline.com/s/9a43de8a-0da5-4ccc-8cff-971c2d092a04](https://docs.getoutline.com/s/9a43de8a-0da5-4ccc-8cff-971c2d092a04)<br><br>I would recommend upgrading to the latest build.
