### ISSUE TITLE
Images are lost on Publish

### ISSUE THREAD

**Issue by matmannion** [outline/outline#691]
When I insert an image, either from the clipboard or by dragging and dropping from the file system into the editor, the image shows up in the editor (and allows you to add a caption) but is lost on publish.

Environment: 
Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)
Ubuntu 18.04

**Comment by tommoor** [comment]
Hey @matmannion is it possible that the image had not completely uploaded before you published?

**Comment by matmannion** [comment]
That seems unlikely. I had been editing the page for about 20 minutes and had added 4 or 5 images, went to publish, all images disappeared.

**Comment by tommoor** [comment]
The warning now exists if you try and leave edit mode with images uploading (4ed2b4b47597468ffa4e7f39dd3fdc6319a3da15). I'll leave this open for a bit incase a solid repro case comes up.

**Comment by matmannion** [comment]
I can't reproduce this now so I'm happy for this to be closed.
