### ISSUE TITLE
Firefox issues

### ISSUE THREAD

**Issue by willwade** [outline/outline#692]
On Firefox the text editor link function is popping up rapidly and closing rapidly. I.e. you can't create a link in a document in firefox currently

**Comment by tommoor** [comment]
Will take a look, the editor hasn't had a lot of testing in Firefox.

**Comment by tommoor** [comment]
A couple more Firefox issues for the list:

- [ ] Sidebar does not scroll
- [ ] Cannot edit checkboxes

**Comment by alelapeyre** [comment]
Hi, another issue, the document download not working.

Firefox version: **Firefox 63.0a1 (2018-07-13)**
