### ISSUE TITLE
Insights data can't be disabled since 0.76

### ISSUE THREAD

**Issue by fribor** [outline/outline#6936]
Since uprading to v.0.76 we can't deactivate the Insights panel and the detailed statistics about who read the document any longer. Would be great, if Insights could be completly disabled in future versions on self-hosted deployments. 

Within Germany, the work council has strong say on what can be tracked within a workplace and what can't. If certain tracking can't be disabled, a work council has the legal right to overrule a software decision by management. Thus, we risk losing the approval for using the software within our company.

**Comment by tommoor** [comment]
Fixed in d36332273e95aee666672cebd17302b68e9295c8 – will be in the next release.
