### ISSUE TITLE
The upload of files >20 kB fails with local storage adapter configured

### ISSUE THREAD

**Issue by krupper** [outline/outline#6951]
All tested files (png, jpg, pdf, docx, xlsx, zip, app, mov) that are larger than approx. 20 kB cannot be uploaded, but the following error message appears: "Sorry, an error occurred uploading the file". Sometimes only really small files (< 5 kB) are working.

Neither the server log nor Sentry give any output about the error or any other kind of reaction to the attempted upload. The FILE_STORAGE_UPLOAD_MAX_SIZE option is set to 26214400.

The client tries to send an HTTP Post request to the server:
https://wiki.adventisten.de/api/attachments.create but gets an 404 response with the following content:
```
 {   
"Log-Id" : "18fbb8eb60f-d3ca289c",
"Request Time" : "2024-05-27 19:37:23 GMT",
"Error" : "The specified URL cannot be found " 
}
```

Additionally the client logs this error from the server:
```
Object { stack: "", … }
​
__sentry_captured__: true
​
message: ""
​
name: "NotFoundError"
​
stack: "ExtendableError2@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:40:287186\nNotFoundError@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:40:287721\nApiClient/this.fetch@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:40:291042\nasync*ApiClient/this.post@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:40:291500\nuploadFile@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:49:246458\nEditor/T<@https://wiki.domain.tld/static/assets/Section.6jmjk5m1.js:1:1351817\ninsertFiles@https://wiki.domain.tld/static/assets/Section.6jmjk5m1.js:1:339410\nasync*drop@https://wiki.domain.tld/static/assets/Section.6jmjk5m1.js:1:996479\nrunCustomHandler/<@https://wiki.domain.tld/static/assets/Section.6jmjk5m1.js:1:242734\nsomeProp@https://wiki.domain.tld/static/assets/Section.6jmjk5m1.js:1:284862\nrunCustomHandler@https://wiki.domain.tld/static/assets/Section.6jmjk5m1.js:1:242674\nEditorView/i.input.eventHandlers[a]@https://wiki.domain.tld/static/assets/Section.6jmjk5m1.js:1:280358\nsentryWrapped@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:40:234372\nEventListener.handleEvent*_wrapEventTarget/</<@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:40:253548\ninstrumentDOM/</</<@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:40:140135\ninitInput@https://wiki.domain.tld/static/assets/Section.6jmjk5m1.js:1:280284\nEditorView@https://wiki.domain.tld/static/assets/Section.6jmjk5m1.js:1:280509\ncreateView@https://wiki.domain.tld/static/assets/index.wEBp-mJ_.js:1:235460\ninit@https://wiki.domain.tld/static/assets/index.wEBp-mJ_.js:1:233536\ncomponentDidMount@https://wiki.domain.tld/static/assets/index.wEBp-mJ_.js:1:231836\nYi@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:26:86558\ndk@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:26:103427\ne.unstable_runWithPriority@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:18:3813\ngg@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:26:45274\nUj@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:26:100146\nLj@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:26:96247\njg/<@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:26:45497\ne.unstable_runWithPriority@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:18:3813\ngg@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:26:45274\njg@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:26:45444\nV2@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:18:2865\nx.port1.onmessage@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:18:1565\nEventHandlerNonNull*@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:18:1489\n@https://wiki.domain.tld/static/assets/index.OUpknVRH.js:18:4419\n"
​
<prototype>: Object { stack: "", … }
console.js:36:19
    instrumentConsole console.js:36
    insertFiles insertFiles.ts:191
    (Async: promise callback)
    insertFiles insertFiles.ts:187
    drop uploadPlugin.ts:74
    runCustomHandler index.js:3007
    someProp index.js:5307
    runCustomHandler index.js:3005
    a index.js:2974
    sentryWrapped helpers.js:91
    (Async: EventListener.handleEvent)
    _wrapEventTarget trycatch.js:213
    instrumentDOM dom.js:78
    initInput index.js:2973
    EditorView index.js:5114
    createView index.tsx:449
    init index.tsx:300
    componentDidMount index.tsx:212
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 2
    V2 scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    (Async: EventHandlerNonNull)
    <anonym> scheduler.production.min.js:12
    <anonym> scheduler.production.min.js:20
``` 

**To Reproduce**
1. Configure local storage adapter
1. Create a new collection
2. Create a new document inside a collection
3. Drag and Drop a file into the document (edit mode)
4. See error message at the bottom right

**Expected behavior**
The file upload runs without interuption. Afterwards, the file is offered to download by a link in the document.

**Screenshots**
![grafik](https://github.com/outline/outline/assets/10078017/e85330b4-7135-4122-a9c6-cabeb9cef232)

**Outline:**
- Install: self hosted
- Version: f7ea19c (0.76.0)

**Desktop:**
 - OS: macOS
 - Browser: chrome, firefox
 - Version: chrome: 124.0.6367.61, firefox: 124.0.2 (64-Bit)

**Mobile (please complete the following information):**
Not tested

**Comment by tommoor** [comment]
There are thousands of installations using this option with issue, so it's most likely some issue with a proxy infront of the app. 

What is the network error / server logs associated with the error?

**Comment by krupper** [comment]
I tought the same, but the servers response is not from my WAF infront of it. I am sorry that I missed the client network error at the first place. I have updated the original issue post now. Unfortunately, the server does not log anything regarding the upload request or the corresponding error.

**Comment by tommoor** [comment]
```
 {   
"Log-Id" : "18fbb8eb60f-d3ca289c",
"Request Time" : "2024-05-27 19:37:23 GMT",
"Error" : "The specified URL cannot be found " 
}
```

☝️ This response is not from Outline, we don't send errors in that format – so if you can track it down it will probably help pinpoint the problem. The `POST api/attachments.create` endpoint does exist.

**Comment by krupper** [comment]
Thank you for the fast reply. The `POST api/attachments.create` endpoint does work with a few small files in my enviroment too. I am going to look deeper in my infrastructure with the error. But what is about the second error logged by the client? Is it some kind of a reaction to the failed http request?

**Comment by tommoor** [comment]
> Is it some kind of a reaction to the failed http request?

Exactly, yep

**Comment by tommoor** [comment]
I'm closing this out for now as this isn't reproducible on other installations, feel free to post the solution here once you find it though as it'll help others in the future.

**Comment by vember31** [comment]
Hi @krupper  - know this is a few months later but I'm struggling with a similar issue where file uploads & attachments do not work.  I use Cloudflare's WAF, and have tried fully disabling it for Outline but haven't figured out how to get uploads working.  Would you happen to advice on what you identified within your web application firewall that was causing issues?

**Comment by vember31** [comment]
Just in case anyone comes across this and wonders what the issue was (at least for me) - it was because I'm running Outline in Kubernetes via a helm chart. With helm, if you _don't_ put the quotes around large values, it will treat them as numbers and potentially render them with scientific notation.

So, while I'd had my max size in bytes to whatever equates to 25Mb or so, helm was rendering it as something like 2.5e10 bytes or something. Upon putting the bytes value as a string, it was no longer rendering as scientific notation.
