### ISSUE TITLE
Authorization failed. You may have lost access to the document.

### ISSUE THREAD

**Issue by ChinaeduO** [outline/outline#6997]
**To Reproduce**
1. Go to create a document.
2. Click on the body to add content
4. See error: A cloud at the bottom right telling me: Authorization failed. You may have lost access to the document. Also I am not able to add content to my newly create content. Reloading the page does nothing. Sometimes it works after reloading x times. And then it is not working. Sometimes the cloud is there, but I can edit.

**Expected behavior**
As a creator of the document I can edit it when I have just created it.

**Screenshots**
![image](https://github.com/outline/outline/assets/107402400/003f83da-eceb-40d8-bb0e-5c126524f949)

**Outline (please complete the following information):**
- Install: self hosted
-  SSO Microsoft
- Version: 0.76.1

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Arc, Chrome, Firefox

Log:
Console:
![image](https://github.com/outline/outline/assets/107402400/0dccca43-2025-47a8-a79f-49c9a3fad9a3)

Network log:
![image](https://github.com/outline/outline/assets/107402400/2f960f94-866f-42d3-ad72-e853000d4da4)

I observed that the websockets only consists of one message binary. And that the same websocket is initialized multiple time. Waiting long enough (2 minutes) eventually fixes that behavior. And a websocket has multiple binary messages. As you can see below, there are multiple websockets started to the same destination? With the one appearing at the top, that is pending, the edit function works. Before, I could not edit a newly created document.
![image](https://github.com/outline/outline/assets/107402400/1127a47d-f2fe-45a0-a09f-4753e70629b5)

**EDIT:**
I saw that I update to version 0.76.2-0 by accident. Downgraded again, but error still exists.

**Comment by tommoor** [comment]
Please open the network inspector, and provide as much details as you can about the failed requests – in particular websockets.

**Comment by ChinaeduO** [comment]
I have updated my post with logs.

**Comment by foi** [comment]
@ChinaeduO 

I updated from 0.74.0 to 0.76.1 and also came across this issue. The cause was phantom teams in the teams table, and any logged-in users triggered the creation of an entry in the users table within the new team.

How I solved that issue: I set up some parameters for phantom teams:  `update teams set "guestSignin" = false, "memberTeamCreate" = false where id = ('some phantom team ids')` then restart outline and redis.

**Comment by ChinaeduO** [comment]
> @ChinaeduO
> 
> I updated from 0.74.0 to 0.76.1 and also came across this issue. The cause was phantom teams in the teams table, and any logged-in users triggered the creation of an entry in the users table within the new team.
> 
> How I solved that issue: I set up some parameters for phantom teams: `update teams set "guestSignin" = false, "memberTeamCreate" = false where id = ('some phantom team ids')` then restart outline and redis.

Where did u do that @foi ?

**Comment by foi** [comment]
in outline database

**Comment by ChinaeduO** [comment]
Implementing workarounds inside the DB doesn't sound good to me.
That issue should be fixed at source, shouldn't @tommoor ?

**Comment by tommoor** [comment]
> The cause was phantom teams in the teams table

I honestly have no idea how this would be related.

**Comment by ChinaeduO** [comment]
> > The cause was phantom teams in the teams table
> 
> I honestly have no idea how this would be related, it feels like a red herring but you should check if there are multiple teams in the db

You have any other idea for the reason ? @tommoor

**Comment by ChinaeduO** [comment]
> but you should check if there are multiple teams in the db

No multiple teams in db, just one.
