### ISSUE TITLE
Collection becomes an unowned collection

### ISSUE THREAD

**Issue by wuwei-yu** [outline/outline#7004]
When the user sets the Permission in Collection permissions to No Access and then leaves the collection, the collection will become an unowned collection, no one will be able to access it, and the administrator will not be able to see it. It will always take up space and cannot be cleaned unless you directly operate the database to grant user permissions and then delete it. This issue also occurs after the user chooses to log out.

**Comment by tommoor** [comment]
I think the best thing here is to put some protections in at the API level that prevent removing the last admin from a collection, in the same way we have for a team.
