### ISSUE TITLE
title formatting misapplies to next line

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#702]
1. https://www.dropbox.com/s/hqs8kpt1qtzfm9w/Screenshot%202018-06-22%2016.12.25.png?dl=0
2. https://www.dropbox.com/s/051if8db7ked8uh/Screenshot%202018-06-22%2016.13.21.png?dl=0

**Comment by tommoor** [comment]
Weird one… don't think I've ever come across this

**Comment by tommoor** [comment]
This was fixed by 2c0802372b594590e03f1e0f0983a29a3a970a79
