### ISSUE TITLE
table only occupy half when the column number is 1

### ISSUE THREAD

**Issue by IamTaoChen** [outline/outline#7029]
**To Reproduce**
1. create a table
2. delete the column to 1
<img width="535" alt="image" src="https://github.com/outline/outline/assets/42793494/f74b0e57-9e4a-4bfe-9a1b-88764dafe15b">

**Expected behavior**
The table should occupy the whole screen, but now only half

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: self hosted
- Version: main-branch

**Comment by IamTaoChen** [comment]
suddenly, it's good.
<img width="1011" alt="image" src="https://github.com/outline/outline/assets/42793494/444dcf09-453f-473a-8822-819064289c6b">

**Comment by tommoor** [comment]
Hi @IamTaoChen – this would be the result of resizing the first column and then removing the second column. Agreed that this needs special-casing though
