### ISSUE TITLE
Frontend becomes unresponsive when zooming many images

### ISSUE THREAD

**Issue by lampy255** [outline/outline#7034]
Steps to reproduce the behaviour:
1. Make a gallery of images by placing images in table cells (One per cell)
2. Publish the page
3. Zoom and Un-Zoom each image one by one
4. Eventually the page becomes unresponsive 

**Outline:**
- Install: Self Hosted
- Version: v0.77.0 fd17364

**Desktop:**
 - OS: macOS Sonoma 14.5
 - Browser Safari
 - Version 17.5

**Comment by tommoor** [comment]
Was this an existing document? aka do you think this is a regression from 0.76.0?

**Comment by lampy255** [comment]
Yes this was an existing document. So far I have been unable to replicate on a new document..

**Comment by tommoor** [comment]
I was able to reproduce
