### ISSUE TITLE
Dropping large image in table cell causes overflow

### ISSUE THREAD

**Issue by lampy255** [outline/outline#7039]
**To Reproduce**
Steps to reproduce the behaviour:
1. Create a table
2. Drop a large image into any table cell
3. Observe that the image overflows the viewport
4. In order to resize the image to something more reasonable, the user has to horizontally scroll until they can find the resize handle.

**Expected behaviour**
The user will expect the same behaviour as when a large image is dropped anywhere else on the document. IE: Regardless of the image resolution, it should never render wider than the document body.

**Outline:**
- Install: Self Hosted
- Version: v0.77.0 [fd17364](https://github.com/outline/outline/commit/fd17364ebf0012cdf3e9a325a0f528d27b7aa638)

**Desktop:**
 - OS: macOS Sonoma 14.5
 - Browser: Safari
 - Version: 17.5

**Comment by tommoor** [comment]
You can also resize from the left handle, although it might feel unnatural to do so.

**Comment by tusharagrawall** [comment]
Give me the honour of doing this issue. I'll fix this within minutes.
