### ISSUE TITLE
Document Events are very different after upgrading to v0.77.0

### ISSUE THREAD

**Issue by anukrishna888** [outline/outline#7042]
We had an Outline Integration to an external tool - using the webhooks feature. The workflow was all set and running, until we upgraded to v0.77.0. The payload in the event was very different than before. The workflow failed as the content was not successfully extracted from Outline.

**To Reproduce**
1. Upgrade to latest version.
2. Run the previous webhook workflow integration.
3. API fails with exception.

**Expected behavior**
The payload structure should have been maintained as such so that previous integrations will work fine.

**Screenshots**
New payload:
![image](https://github.com/outline/outline/assets/136442526/91c52c52-8da8-434d-8ab2-8edb6bf0d2e9)

Old payload:
![image (3)](https://github.com/outline/outline/assets/136442526/07f7491b-2203-4d8a-9a45-a4792f0d0934)

Thankyou!

**Comment by tommoor** [comment]
Addressed in `v0.77.1`
