### ISSUE TITLE
delete pictures from web but remain on the server

### ISSUE THREAD

**Issue by sweeticetea** [outline/outline#7045]
**To Reproduce**
1. In Windows 10, drag and drop a photo onto the web to upload it
2. delete the picture
3. no delete record in docker log(docker_log)
4. and the picture remains on server(the_remained_pic)

**Expected behavior**
when delete the picture on web,  hope it will be removed from server as well

**Screenshots**
![docker_log](https://github.com/outline/outline/assets/54834868/171ca157-e560-4e57-8cd2-0e9f61f99018)
![the_remained_pic](https://github.com/outline/outline/assets/54834868/3c090905-ef37-44d6-86c0-47e731a0a90e)

my configs
![config sh](https://github.com/outline/outline/assets/54834868/1e6b7b82-ef3c-46a2-b088-3d8d7c7605ed)
![docker-compose yml](https://github.com/outline/outline/assets/54834868/cfc32650-1b62-402d-b100-7c0f29d18dd2)
![env outline](https://github.com/outline/outline/assets/54834868/0213d30e-819f-4aa0-a167-39ccbddaf099)

**Outline (please complete the following information):**
- Install: [self hosted]
- Version: 0.77.1

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [chrome]
 - Version [116.0.5845.188]

**Comment by tommoor** [comment]
Orphaned uploads are removed as part of running the scheduled job:
https://docs.getoutline.com/s/hosting/doc/scheduled-jobs-RhZzCt770H

If this doesn't happen then the file is still referenced somewhere in the document history and must be permanently deleted from trash as well.

**Comment by yzr95924** [comment]
> Orphaned uploads are removed as part of running the scheduled job: https://docs.getoutline.com/s/hosting/doc/scheduled-jobs-RhZzCt770H
> 
> If this doesn't happen then the file is still referenced somewhere in the document history and must be permanently deleted from trash as well.

the info at the above link is very limited, can anyone provide a example to trigger the scheduled job? Thanks.
