### ISSUE TITLE
Editor formatting toolbar blocks content (Android PWA)

### ISSUE THREAD

**Issue by libnewton** [outline/outline#7052]
The new text toolbar (h1, h2, h3, indentation, etc.) is blocking content on Android, when the on-screen keyboard is shown.

**To Reproduce**
1. Open Outline v0.77.0 or v0.77.1 in Android as browser site or PWA (not tested iOS)
2. Add a document, add bullet points with content
3. Open on-screen keyboard, close it (or open another App/Document)
4. The toolbar is not affixed on the top of the keyboard, but it is floating in the middle of the document
5. The toolbar is blocking the view of content, you can still write behind the toolbar, but the view is blocked.

**Expected behavior**
The toolbar is sticked to the bottom, which is the top border of the keyboard in case the on-screen keyboard is shown.

**Screenshots**
![Screenshot_20240616-103458](https://github.com/outline/outline/assets/45080708/25fbc040-03c8-4c56-bbb0-2fda5e923826)

**Outline:**
- Install: self-host
- Version: v0.77.0 and v0.77.1

**Desktop**
N/A

**Mobile:**
- Device: Google Pixel 7
- OS: Android 13
-  Browser: Chrome + PWA installed outline

**Comment by tommoor** [comment]
Yea, we've got it as close as possible but unfortunately the API's still don't exist to reliably always position a toolbar above the keyboard. This can still happen when you tap into focus on Android – scrolling down should resolve.

see: https://github.com/w3c/csswg-drafts/issues/7475

**Comment by tommoor** [comment]
Weird, I have a Pixel 7 for testing – there won't be an option to change the style of toolbar here but will look for other ways to resolve.

**Comment by kiberdruzhinnik** [comment]
Any progress here? Still do not understand how to avoid this. Using my Pixel 7 though
