### ISSUE TITLE
Images gone missing on Wiki Pages

### ISSUE THREAD

**Issue by byebb** [outline/outline#7059]
After a while, sometimes randomly important images get missing and are just not visible anymore.
Empty blackholders are there that still show where an image must have been and also what ratio (resolution).

Really important information has been lost.. this is not how it should be, because the wiki has to be reliable for us.

**To Reproduce**
Difficult to reproduce as I do not know why this is happening at all.

**Expected behavior**
I would expect that images that are uploaded once in a document are there clearly visible until I delete them myself.

**Screenshots**

![image](https://github.com/outline/outline/assets/4288893/0e7b1f91-a8fa-4b95-92d8-30fa8330e18c)

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.77.0

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 125.0.6422.176

**Comment by tommoor** [comment]
- What storage strategy are you using? 
- What does the network request to the image look like, is it an error?
- You can find the ID of the image and then the matching record in the `attachments` table to find the path on disk and see if the file is still there.

**Comment by lifeofguenter** [comment]
This is same issue as: https://github.com/outline/outline/issues/7065

**Comment by byebb** [comment]
> * What storage strategy are you using?
> * What does the network request to the image look like, is it an error?
> * You can find the ID of the image and then the matching record in the `attachments` table to find the path on disk and see if the file is still there.

We are using MinIO S3 Storage.

Request URL: `https://%website.com%/api/attachments.redirect?id=11a46aae-69f0-4d26-ba4b-1a9cabfdfcdc`

From what I can tell, we are getting 500 Errors:

```
{ok: false, error: "internal_error", status: 500, message: "Internal error"}
error: "internal_error"
message: "Internal error"
ok: false
status: 500
```

not sure, if this is of any help:

![image](https://github.com/outline/outline/assets/4288893/d3ee46ad-a15e-4fe7-8d6e-86966d3945e0)

--

![image](https://github.com/outline/outline/assets/4288893/17ee3f26-4e47-4803-8de5-8963a8a3433d)

--

As a summary: Attachment redirects are not working based on given IDs.

**Comment by tommoor** [comment]
That's helpful in that now we know it's an unexpected server error, you'll need to find the associated error in the server logs and post that though.
