### ISSUE TITLE
AWS S3 uploads broken when using instance roles on AWS

### ISSUE THREAD

**Issue by bagedevimo** [outline/outline#7060]
Since we upgraded by 0.76 to 0.77, we've had image uploads fail with HTTP 400.

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>a non-empty Access Key (AKID) must be provided in the credential.</Message><ArgumentName>X-Amz-Credential</ArgumentName><ArgumentValue>/20240616/ap-southeast-2/s3/aws4_request</ArgumentValue><RequestId>snip</RequestId><HostId>snip</HostId></Error>
```

**To Reproduce**
Configure a self hosted instance of Outline, per the documentation. Instead of supplying AWS_ACCESS_KEY_ID, assign the relevant instances / containers an IAM role which gives them the correct access to S3. Prior to 0.77, image upload worked. On, and after, 0.77 image upload fails.

**Expected behavior**
Image uploads should work using instance provider credentials

**Outline (please complete the following information):**
Self hosted, version: v0.77.1 ( e733fd2)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Arc
 - Version Version 1.41.0 (49440), Chromium Engine Version 124.0.6367.92

**Comment by bagedevimo** [comment]
A bit of internal digging suggests that https://github.com/outline/outline/pull/6731 could be a likely cause, with the previous version of the SDK finding these credentials automatically, but the newer version requiring a slightly different config.

**Comment by bagedevimo** [comment]
We have a local branch which seems to resolve the issue - we'll do some more testing and submit an PR if it's an actual fix

**Comment by tommoor** [comment]
This particular configuration was never official supported by Outline and not documented, so help with fixing is appreciated
