### ISSUE TITLE
Image upload & viewing stopped working with S3

### ISSUE THREAD

**Issue by lifeofguenter** [outline/outline#7065]
Trying to upload an image now gives me the following error from AWS/S3:

```
<Error><Code>InvalidArgument</Code><Message>a non-empty Access Key (AKID) must be provided in the credential.</Message>
```

viewing images also do not work anymore

maybe related to recent library upgrade?

**Comment by tommoor** [comment]
This seems like https://github.com/outline/outline/issues/7060 – are you using IAM roles instead of client ID and secret to authenticate S3?

**Comment by lifeofguenter** [comment]
Yes, this is indeed the same issue as #7060 - would it be possible to do a patch release for that?

The majority of systems on AWS eco-system would be using IAM roles instead of hardcoded credentials, so it might be affecting a number of users.

**Comment by tommoor** [comment]
Yes, will wrap up in a patch release with other fixes within 24h

**Comment by tommoor** [comment]
Release[ v0.77.2](https://github.com/outline/outline/releases/tag/v0.77.2)
