### ISSUE TITLE
Excerpts functionality

### ISSUE THREAD

**Issue by jhult** [outline/outline#708]
From [Confluence documentation](https://confluence.atlassian.com/doc/excerpt-macro-148062.html):

> The Excerpt macro is used to mark a part of a page's content for re-use. Defining an excerpt enables other macros, such as the Excerpt Include and Blog Posts macros, to display the marked content elsewhere.
> 
> You can only define one excerpt per page. In other words, you can only add the Excerpt macro once to a page.

This functionality would be nice. We utilize this today in our Confluence instance.

**Comment by jhult** [comment]
This might relate to #680.

**Comment by MatheusRV** [comment]
@jhult Is this done?
@tommoor ping

**Comment by tommoor** [comment]
It's not, we don't have functionality like this

**Comment by jhult** [comment]
Bump

**Comment by matbrgz** [comment]
Up

**Comment by jhult** [comment]
Bump

**Comment by max-critcrew** [comment]
It would be awesome to have this feature! :)

**Comment by phil-flip** [comment]
would love to have it as well..
