### ISSUE TITLE
Frontend becomes unresponsive when zooming image and scrolling at same time

### ISSUE THREAD

**Issue by lampy255** [outline/outline#7083]
**To Reproduce:**
Steps to reproduce the behaviour:
1. Make large scroll input (spin mouse scroll wheel and leave it free-wheeling)
2. Zoom an image
3. Observe that the frontend is now unresponsive

**Notes:**
The problem seems to occur when a user zooms an image whilst simultaneously scrolling. This can happen unintentionally with a mouse that has a free-spinning scroll wheel.
This is similar to #7034 but with different steps to reproduce.
This also affects older versions of Outline, but instead of making the frontend unresponsive it causes the image to stick to the centre of the viewport (See #6026).

**Outline:**
- Install: Self Hosted
- Version: v0.77.2 [f4c7a99](https://github.com/outline/outline/commit/f4c7a99a36889b11a1af8dccd045d4d2eebb0d7f)

**Desktop:**
 - OS: Mac OS Sonoma 14.5
 - Browser: Safari

Can also reproduce in Chrome on a Windows machine.

**Comment by tommoor** [comment]
Could you see if it reproduces on the source library? May have to file this issue upstream

https://rpearce.github.io/react-medium-image-zoom

**Comment by lampy255** [comment]
Yes I can reproduce in a sandbox with that library. Would you like me to open the issue on their repo?

**Comment by tommoor** [comment]
If you wouldn't mind!

**Comment by lampy255** [comment]
Oh looks like its a known issue... 

https://github.com/rpearce/react-medium-image-zoom/issues/439
