### ISSUE TITLE
[BUG/Maybe Feature]Html elements does not take effect in editor

### ISSUE THREAD

**Issue by hoiwanchang** [outline/outline#7084]
Html element does not take effect in editor.

**To Reproduce**
1. create a new document
2.paset code below
<details>
<summary>code</summary>

```
<details open>
  <summary>Hello</summary>
  World!
</details>
```

</details>

**Expected behavior**
expect it works like above, it could collapse and open not showing the html code like plain text

**Screenshots**
![Screenshot from 2024-06-19 08-34-20](https://github.com/outline/outline/assets/24208826/7572e837-4b15-499b-afe0-5a828c8a25ea)

**Outline (please complete the following information):**
- Install: self hosted
- Version: release v0.77.2

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Browser Edge
 - Version 126.0.2592.61 (Official build) (64-bit)

**Comment by tommoor** [comment]
The Outline editor does not support arbitrary HTML, there is an existing request for collapsible notices (#6286) which I think this falls into. Headings can also be collapsed already
