### ISSUE TITLE
document image hide when print

### ISSUE THREAD

**Issue by seong889** [outline/outline#7087]
When print a document, attached images are hide.

- document
![image](https://github.com/outline/outline/assets/14970965/bab23b29-bbe6-4300-8edf-1e5a01b887ee)
- print
![image](https://github.com/outline/outline/assets/14970965/6d03c433-79c7-4782-989f-0cc0aa450522)

**environment**
- storage : local
- version : 0.77.2

**Comment by santiagobiali** [comment]
Same issue in selfhosted Outline v0.83.0, but only in Chrome and Edge browsers. In Firefox the images are fine when printing.

Google Chrome 135.0.7049.85
Edge 135.0.3179.73
Firefox 137.0.1
