### ISSUE TITLE
Markdown internal links after import 

### ISSUE THREAD

**Issue by emanuelearena** [outline/outline#7089]
The Import function doesn't generate properly Markdown internal links between documents. This happens both with an external markdown library and with an Outline Markdown export. Tried without success with different internal link syntax in the imported document (e.g. `[My File](/mypath/myfile.md)` , `[My File](./mypath/myfile.md)`). 
Link is generated as an external link.

**To Reproduce**
Issue can be reproduced by exporting in Markdown format a test collection with internal links and then importing it back.

**Expected behavior**
Markdown internal links should be reproduced in Outline

**Screenshots**
![image](https://github.com/outline/outline/assets/173257454/e5482c52-9e9a-4366-bfe7-b93469f031f9)
Example of a test collection with an internal link in `Document referencing` pointing to `Document referenced`

-----

![image](https://github.com/outline/outline/assets/173257454/d75dad3a-d2bc-47fc-a1e5-15dda1fe9053)
How `Document referencing.md` appears in the markdown zip export

----

![image](https://github.com/outline/outline/assets/173257454/45db2c31-c275-431b-9157-d25f5c51f8da)
How `Document referencing.md` is generated after importing it back in outline. The link is to the address `https://./Document%20referenced.md`

**Outline:**
- Install: self hosted
- Version: 0.77.2

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 125.0.6422.176

**Comment by emanuelearena** [comment]
I'm using the bulk import through the Settings. Thanks

**Comment by hmacr** [comment]
I'd like to work on this, if that's alright.
