### ISSUE TITLE
Filtering Issue with `/` Command When Using Chinese Input

### ISSUE THREAD

**Issue by IamTaoChen** [outline/outline#7090]
#### Bug Description
When using the `/` command to filter options like `table`, it works correctly in English by typing `/t`. However, when using Chinese input, the filter doesn't work as expected. For instance, typing `/b` for `表格` (pinyin: `biaoge`) does not yield the correct results.

#### Steps to Reproduce
1. Switch to the Chinese input method.
2. Attempt to use the `/` command to filter options.
3. Observe that filtering doesn't work as it does in English.

#### Expected Behavior
The filtering functionality should work consistently regardless of the input language. Typing `/b` should filter and display `表格` just as `/t` filters and displays `table` in English.

#### Screenshots
- Filtering in English:
  ![English Filter](https://github.com/outline/outline/assets/42793494/e37e65ad-0198-429d-8afd-602109675705)
  
- Attempting to filter in Chinese:
  ![Chinese Filter](https://github.com/outline/outline/assets/42793494/9de0f96d-2e68-4d2d-b30b-5e1b2d9c7144)
  ![Chinese Filter Pinyin](https://github.com/outline/outline/assets/42793494/587f514c-253b-4c32-a769-3675f36842a5)

#### Environment
- OS: [Your OS]
- Browser: [Your Browser]
- Outline version: [Your Outline Version]

#### Possible Solutions
1. Uniform the `/` menu filtering to support both English and Chinese (and potentially other languages) by recognizing their respective input methods.
2. Implement a more flexible filter that can handle different languages based on the input method or context.

#### Additional Context
Uniform filtering across different languages will greatly enhance user experience for bilingual or non-English users. This functionality is crucial for maintaining consistency and usability in a multilingual environment.

**Comment by tommoor** [comment]
It works correctly when you type a chinese character, no?

**Comment by IamTaoChen** [comment]
> It works correctly when you type a chinese character, no?
<img width="347" alt="image" src="https://github.com/outline/outline/assets/42793494/94348ead-11e0-4b91-949e-fb969a8fbc6c">

Yes, it works. Maybe this is OK. I am just used to typing in English.

**Comment by tommoor** [comment]
As I understand it there isn't a native way of searching Chinese characters given the pinyin, it would require extra libraries with all the conversions embedded

**Comment by tommoor** [comment]
I'm closing this as won't fix, there isn't a reasonable way to support pinyin filtering for chinese input
