### ISSUE TITLE
Cannot remove logo

### ISSUE THREAD

**Issue by jerryterrell** [outline/outline#7091]
Cannot remove logo.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Details' under workspace
3. Click on 'Remove' next to a previously uploaded logo

**Expected behavior**
The logo is removed and reset to default

**Screenshots**
Screenshot of the console:
![image](https://github.com/outline/outline/assets/148170019/a7ed36ea-fb54-400c-8320-97bfbde23752)

**Outline (please complete the following information):**
- Install: getoutline.com
- Version:

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge, Firefox
 - Version:

**Comment by tommoor** [comment]
Thanks for filing
