### ISSUE TITLE
Document becomes uneditable after changing the title (or) emoji.

### ISSUE THREAD

**Issue by hmacr** [outline/outline#7107]
After changing the title (or) emoji in a document, it becomes uneditable.
Share, publish, and other actions are not displayed.

**To Reproduce**
1. Change the title / emoji of a document.
2. Verify the document is uneditable and actions are hidden.

**Comment by tommoor** [comment]
Hmm, I can't reproduce – the collection relationship should be there through `Document.findByPk` in the return value of `documentUpdater` – I think the situation might be more granular/edge case.

**Comment by tommoor** [comment]
Oh it's because the return value from `documentUpdater` isn't used… that doesn't explain why I can't repro though

**Comment by hmacr** [comment]
Ahh right! That explains it.

Try with a private collection - that's where the collection membership checks kick in.

**Comment by hmacr** [comment]
Do you want me to modify the PR to use the return value?

**Comment by tommoor** [comment]
☝️ got it here, thanks for the report
