### ISSUE TITLE
BadRequestError in /slack.callback

### ISSUE THREAD

**Issue by tommoor** [outline/outline#711]
## Error in Outline

**BadRequestError** in **/slack.callback?code=XXX
code_already_used

[View on Bugsnag](https://app.bugsnag.com/atlas-1/outline/errors/5b1e6f732a9e1c001a91f9f4?event_id=5b3adab19300eb0018722df4&i=gh&m=ci)

## Stacktrace

    server/errors.js:32 - new InvalidRequestError
    server/slack.js:40 - _callee2$
    server/slack.js:157 - step
    server/slack.js:157 - none

[View full stacktrace](https://app.bugsnag.com/atlas-1/outline/errors/5b1e6f732a9e1c001a91f9f4?event_id=5b3adab19300eb0018722df4&i=gh&m=ci)

*Created by Tom Moor via Bugsnag*

**Comment by tommoor** [comment]
Attempted all of the Slack signin options multiple times, I'm not sure what's going on here 🤔

**Comment by tommoor** [comment]
You can trigger this by going back after connecting Slack. I think this is the only reasonable explanation.

**Comment by benmort** [comment]
@tommoor did you get to the bottom of this error? coming across it myself

**Comment by benmort** [comment]
it may reattempt the get request when the first has timed out and hit the slack auth twice with the some code parameters
