### ISSUE TITLE
The maximum number of teams has been reached

### ISSUE THREAD

**Issue by dabaobbb** [outline/outline#7127]
**To Reproduce**
1. I use gitlab authentication ,filled all the stuff
2. First time ,I somewhat login success
3. then I logout ,again login , it always redirct to the current login page and outline logs showed the error below
4. {"error":"The maximum number of teams has been reached","stack":"UnauthorizedError: The maximum number of teams has been reached\n    at new AuthenticationError (/opt/outline/build/server/errors.js:32:34)\n    at accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:42:11)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async OAuth2Strategy._verify (/opt/outline/build/server/routes/auth/providers/oidc.js:93:22)","level":"error","message":"Error during authentication"}

version is the latest

**Comment by tommoor** [comment]
Hi, your version cannot be the latest as this error does not exist in the latest edition – upgrading to https://github.com/outline/outline/releases/tag/v0.77.2 should resolve the issue.

**Comment by dabaobbb** [comment]
Thanks, I will check the image verion
