### ISSUE TITLE
Comment reactions

### ISSUE THREAD

**Issue by apoorv-mishra** [outline/outline#7137]
Badly missing out on comment reactions. We already have the picker ready so can reuse that.

**Comment by hmacr** [comment]
## Design / Implementation Notes
- New `reactions` table, with foreign keys to `users` and `comments` (can be extended to `documents` later when needed), with the following columns.
  - id
  - emoji
  - userId
  - commentId
  - createdAt (added by default in `IdModel`)
  - updatedAt (added by default in `IdModel`)
- We expect the `reactions` table to grow rapidly in comparison to other tables. So, the server model will not be a `ParanoidModel` - better to delete the entries instead.
- Reaction uniqueness: `emoji:userId:commentId`.
- New `reactions` column in `comments` table to store the JSON cache of all the reactions to a comment - helps query faster. Its structure 👇
```
{
  "emoji_A": ["user_id_A", "user_id_B"],
  "emoji_B": ["user_id_B",
}
```
- New APIs - `comments.add_reaction` & `comments.remove_reaction` . These APIs will update the `reactions` table and the `reactions` column in comments table.
- New websocket events - `comments.add_reaction` & `comments.remove_reaction`.
- In the frontend comment thread, add a reaction list. (Not completely sure of this FE design).
  - Each reaction item could have the emoji and its count.
  - A button that triggers a modal to display all the users who have reacted to a comment.
    - The comments are displayed in a sidebar with little room - I think this makes it not ideal to show the users in a tooltip.

@tommoor Lmk how this looks.

**Comment by tommoor** [comment]
Looks good, the one bit I would push back on is mutating the shape of the `reactions` object in the response – this will complicate things in the long term having two different versions of the that object. I also don't think the user details will be needed the majority of the time – we won't display usernames of reactons by default on the screen, you'll have to interact or hover over them in some way to see those.

We could still expose a `reactions.list` endpoint that takes a `commentId` param to get full details.

**Comment by hmacr** [comment]
Got it &mdash; makes it cleaner (we don't have to worry about `users.update` events too) 👌 

On the FE side &mdash; I'm thinking a modal trigger, alongside the reactions, which would use the `reactions.list` API.
