### ISSUE TITLE
CIDR IP Addresses get converted into fractions

### ISSUE THREAD

**Issue by lampy255** [outline/outline#7140]
**To Reproduce**
1. Type out a CIDR IP Address in a document EG: "10.0.101.1/24"
2. Outline overrides this to become "10.0.101.½4"

**Expected behavior**
IP Addresses should be recognised and not converted into fractions

**Outline:**
- Install: Self Hosted
- Version: [f4c7a99](https://github.com/outline/outline/commit/f4c7a99a36889b11a1af8dccd045d4d2eebb0d7f)

**Comment by tommoor** [comment]
The responsible code is here…

https://github.com/outline/outline/blob/main/app/editor/extensions/SmartText.ts#L5-L11
