### ISSUE TITLE
Display logo/branding on individual shared documents

### ISSUE THREAD

**Issue by tommoor** [outline/outline#7162]
### Discussed in https://github.com/outline/outline/discussions/7160

<div type='discussions-op-text'>

<sup>Originally posted by **loosus** June 28, 2024</sup>
On publicly shared documents (where no login is required), we would like our logo to appear in the upper-left corner.  We already have the "Public Branding" feature enabled.
<img width="771" alt="image" src="https://github.com/outline/outline/assets/25268183/a73076ae-fa15-4524-9de8-7200ee47b9f9">
</div>

**Comment by apoorv-mishra** [comment]
The TOC toggle button is expected to take up the branding logo here?

**Comment by tommoor** [comment]
It's always been this way but I think we need to be consistent and place the team logo / name in the top left in this situation, outside of the sidebar. 

The TOC button I'm not sure about where to place it yet, will have to see what works best

**Comment by apoorv-mishra** [comment]
How about keeping it adjacent to the team logo itself? Weird though that it becomes part of document header that way 🙈 

![Screenshot 2024-06-30 at 23 33 23](https://github.com/outline/outline/assets/15694566/c3c67721-c584-4ec1-a73e-b9d514f36515)

By the way this is for a doc which:
1. Is accessed via `shareId`(through share url)
2. Has no nested docs

And of course, public branding is enabled for the team.

**Comment by tommoor** [comment]
It's not great yea, I think we should include the team name there too like we do on docs with a sidebar. 

Maybe I need to mock up some options before we move forward here
