### ISSUE TITLE
Sign In button in homepage header goes to slack login by default

### ISSUE THREAD

**Issue by satyadeepk** [outline/outline#717]
The `Sign In` button on top right in the homepage uses slack login even in the case where only Google login is enabled. 

### Two options
1. Remove the "Sign In" button from the header, as it's already in the hero element.
2. Show a drop down with "Login with Slack" and "Login with Google" based on whichever is enabled in .env

**Comment by tommoor** [comment]
I think I'll have it redirect to the homepage and scroll to the login section. The login link is mainly there for the other non-home content pages

**Comment by satyadeepk** [comment]
That makes sense!
