### ISSUE TITLE
0.77.2 version Cannot upload image

### ISSUE THREAD

**Issue by YIKAILucas** [outline/outline#7177]
**Expected behavior**
I am encountering a 500 Internal Server Error when attempting to upload an image. The details are as follows:
1. Upload a image
2. the image briefly appears on the screen.
3. The image quickly disappears.
4. display 500 error

And I rollback to 0.76.1, It back to normal. 

**Screenshots**
<img width="1573" alt="image" src="https://github.com/outline/outline/assets/32409911/66cfc009-a5fc-4361-bace-6af70a66c10d">

<img width="1199" alt="image" src="https://github.com/outline/outline/assets/32409911/e9301019-72ea-46cb-9596-00fa5591b0c4">

**Outline (please complete the following information):**
- Install: [self hosted]
- Version: 0.77.2

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [Firefox]
<img width="710" alt="image" src="https://github.com/outline/outline/assets/32409911/64804874-59c5-4974-84cb-e2ec698e220f">

**Comment by tommoor** [comment]
There will be a matching server error log if the status is `500` with more details

**Comment by tommoor** [comment]
The only change of significance in 0.77.2 is that we now consider all the sources of AWS credentials again, rather than just `AWS_ACCESS_KEY_ID`.

As such AWS credentials will be loaded in the following order – it's likely you have some old creds on your server or similar that are now being used wherease in `0.77.1` only the environment variables were considered:

- Loaded from AWS Identity and Access Management (IAM) roles for Amazon EC2
- Loaded from the shared credentials file (~/.aws/credentials)
- Loaded from environment variables
- Loaded from a JSON file on disk

**Comment by YIKAILucas** [comment]
How can I set AWS_ACCESS_KEY_ID as the highest priority???

**Comment by tommoor** [comment]
> How can I set AWS_ACCESS_KEY_ID as the highest priority???

The order is decided by the AWS library, it cannot be changed

**Comment by YIKAILucas** [comment]
The problem is that, I use the same outline.env, it works in 0.76.1 version, but it doesn't work in 0.80.2 version. The Minio storage error. I think it most likely an AWS config problem. And my env file is below. How to fix it? Thanks for your help.

```shell
AWS_ACCESS_KEY_ID=2tFppgOQrsDxCHaYRhEQ
AWS_SECRET_ACCESS_KEY=eiiGYOCwwdf5Pire9YQH0e2yYkq2oJFJDtDNFNf6
AWS_S3_UPLOAD_BUCKET_URL=https://minio.ttok.com
AWS_S3_UPLOAD_BUCKET_NAME=iuxzmuwqkhlo9udl3fp9kyrir3
#AWS_S3_ACCELERATE_URL=
AWS_S3_FORCE_PATH_STYLE=true
AWS_S3_ACL=private

```

**Comment by ChinaeduO** [comment]
@YIKAILucas did u find a fix, I am facing the same issue

**Comment by ChinaeduO** [comment]
In my case storage was full. Had the following error in the browser:

`<Error><Code>XMinioStorageFull</Code><Message>Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.</Message><BucketName>xxx</BucketName><Resource>/xxx</Resource><RequestId>xxx</RequestId><HostId>xxx</HostId></Error>`
