### ISSUE TITLE
Document import max capped due to maxStateLength

### ISSUE THREAD

**Issue by bridge-four** [outline/outline#7185]
Document import max length is capped at ~1Mb, which causes generic ZIP imports to fail.

**To Reproduce**
1. Go to Settings-> Import
2. Click on Markdown -> Import
3. Select a Zip archive, which includes a test file `test.png` over 1Mb
4. Import fails. See this error in docker log:

```
{"error":"The document \"test\" is too large to import, please reduce the length and try again","level":"error","message":"Error processing task in ImportMarkdownZipTask","stack":"BadRequestError: The document \"test\" is too large to import, please reduce the length and try again\n    at InvalidRequestError (/opt/outline/build/server/errors.js:99:34)\n    at documentImporter (/opt/outline/build/server/commands/documentImporter.js:66:43)"}
```

**Expected behavior**
Outline would respect the FILE_STORAGE_IMPORT_MAX_SIZE variable

**Outline (please complete the following information):**
- Install: Self hosted
- Version: 0.77.2

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 126

**Investigation**:
Looks to be due to [this](https://github.com/outline/outline/blob/main/server/commands/documentImporter.ts#L76-L81):
```
  // Sanity check – text cannot possibly be longer than state so if it is, we can short-circuit here
  if (text.length > DocumentValidation.maxStateLength) {
    throw InvalidRequestError(
      `The document "${title}" is too large to import, please reduce the length and try again`
    );
  }
```

and [this](https://github.com/outline/outline/blob/f9dadf554803b210b3ae6a5b45c2e267bbb6c4d1/shared/validations.ts#L50):
```
maxStateLength: 1500 * 1024,
```

**Comment by tommoor** [comment]
Closing as expected behavior for now – a .png cannot be imported as a document, that's why you're seeing the size error.
