### ISSUE TITLE
Default Search Filter Fails to Include Titles Containing Keywords

### ISSUE THREAD

**Issue by jochne** [outline/outline#7187]
When searching for keywords, the default search filter does not include titles that contain the keywords. The default search should include both titles and body text when searching for keywords. Enabling the "Search Titles Only" option should restrict the search to titles only.

**To Reproduce**

1. Go to the search feature.
2. Enter a keyword that is present in the title of some documents.
3. Perform the search using the default filter.
4. Observe that titles containing the keyword are not included in the search results.
5. Enable the "Search Titles Only" option.
6. Perform the search again.
7. Verify that the search now only returns results from titles.

**Expected behavior**
The expected behavior is that the default search should encompass both titles and body text. Additionally, when the "Search Titles Only" option is enabled, the search should only return results from titles.

**Screenshots**
![CleanShot 2024-07-03 at 9  50 05@2x](https://github.com/outline/outline/assets/21233677/e7bfba01-d60b-4c92-99e0-d7d70bc056d4)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.77.2

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version 126.0.6478.115 (arm64)

**Comment by tommoor** [comment]
Unfortunately what you're seeing is the limitations of postgres search, it just isn't optimized for CJK languages as the tokenisation requires spaces. There isn't a short term fix here as we'd basically have to make a "real" search engine such as Meilisearch or Elasticsearch an optional add-on.

Combining with #3207

**Comment by zincnan** [comment]
> Unfortunately what you're seeing is the limitations of postgres search, it just isn't optimized for CJK languages as the tokenisation requires spaces. There isn't a short term fix here as we'd basically have to make a "real" search engine such as Meilisearch or Elasticsearch an optional add-on.
> 
> Combining with [#3207](https://github.com/outline/outline/issues/3207)

Can I configure a better Chinese or Japanese search myself now, such as ELASTICSEARCH? I added the ELASTICSEARCH_URL and ran the service, but it seems that outline cannot interact with ES to build an index for the documents.
