### ISSUE TITLE
Suddenly unable to edit documents (authentication issue?)

### ISSUE THREAD

**Issue by multipleofzero** [outline/outline#7190]
**To Reproduce**
1. Open existing page
2. Check bottom right corner: see "cloud with x" symbol

OR

1. Create a new page
2. Set a title (works)
3. Try to write something into the "body" of the page (does not work, no characters appear)
4. Publish the page
5. Edit the just published page (still has the "cloud with x"): editing apparently works despite the "cloud with x"

**Expected behavior**
Pages can be created and edited w/o the "cloud with x" being displayed.

**Screenshots**
<img width="1305" alt="2024-07-03_outline_issue" src="https://github.com/outline/outline/assets/51087741/ee8682b5-b97f-4887-a09a-0d70d88b4721">

**Outline (please complete the following information):**
- Install: self hosted (enterprise)
- Version: 0.77.2

**Desktop (please complete the following information):**
 - OS: macOS and Linux
 - Browser: Firefox, Chrome, Chromium, Brave
 - Version: current (e.g. FF 127.0.2, Chromium 117.0.5846.0)

**Findings so far**

There are lots of

```[HocuspocusProvider] The provided authentication token isn’t allowed to connect to this server. Will try again.```

messages visible in the developer tools (for sure in FF, Chromium).

And there are "batches" of messages like the following in the server's logs:

```
Jul 03 14:26:39 host.example.com outline[425293]: [onAuthenticate] Expired token
Jul 03 14:26:39 host.example.com outline[425293]: {"label":"multiplayer","level":"info","message":"New connection to \"document.b1355205-0bf2-4114-bef6-3a6a5eb45b29\""}
```

**Note:** the installation used to work as expected until today. There was no obvious change on the infrastructure or software between the working and non-working state.

Any hints would be much appreciated.

**Comment by multipleofzero** [comment]
There are also repeating (many) 101 responses (in developer tools' "network" tab) apparently when Outline is (trying to) open a websocket connection for `document.<UUID>`.

**Comment by tommoor** [comment]
The token is generated on load of the app (call to `auth.info`) and lasts 24 hours, reloading the app can you check that this call is succeeding and returning a valid token.

**Comment by multipleofzero** [comment]
Thank you for the quick reply. I have just checked again (after a reboot of my machine): everything seems to be back to normal now!

There is indeed a (successful) request to `auth.info` when (re)loading the app. Both, the `HocuspocusProvider` and the "too many" 101 repsonses are gone from the dev tools. In both browsers, FF and Chromium.

It is after business hours for us, so I cannot get feedback from team members. But I fear this was a transient issue (for whatever reason). I will double check tomorrow and update this issue again.

**Comment by tommoor** [comment]
I would double check the date/time is correct on your server
