### ISSUE TITLE
Allow choosing location when duplicating document

### ISSUE THREAD

**Issue by tommoor** [outline/outline#7193]
Currently when duplicating it just places the document next to the existing automatically, this is often not desired – it would be better to show the file explorer and allow choosing where to duplicate to.

**Comment by infinite-persistence** [comment]
Any preference in mind?
1. Putting the explorer inside the existing Copy dialog (remain single dialog)
2. Copy --> type Title --> select destination (2 dialogs)
3. Something else?

**Comment by hmacr** [comment]
I think we should use the same design as "Templatize document" - can be accessed in `Document menu -> Templatize` (option 1 in your suggestions). cc @tommoor 

![Screenshot 2024-11-26 at 7 17 55 PM](https://github.com/user-attachments/assets/359445c2-8f4c-4771-a9f6-bb5eeb69ff23)
