### ISSUE TITLE
Un-deletable content in page

### ISSUE THREAD

**Issue by loosus** [outline/outline#7195]
We copied and pasted some content from a Word document (a table), and not only did it not successfully transfer; it also now shows a broken-image icon and cannot be removed from the page.  In fact, it cannot even be selected.

How it appears in published mode:
<img width="590" alt="image" src="https://github.com/outline/outline/assets/25268183/7abdd06a-ef12-42db-9071-336e56d98891">

How it appears in edit mode:
<img width="548" alt="image" src="https://github.com/outline/outline/assets/25268183/ff93fff0-a5e2-4712-9a5d-6b7b21e1a0f1">

We are on the cloud version and can give you a link to it in a DM if necessary.

**Comment by tommoor** [comment]
At a minimum you should be able to drag a selection over the broken image and hit Backspace to delete even if it cannot be selected directly.

**Comment by loosus** [comment]
Would you believe that it's just gone now?  Weird.  Maybe it was just front-end/local to the browser?  No idea.
