### ISSUE TITLE
Searching on publicly shared page makes images in page disappear

### ISSUE THREAD

**Issue by loosus** [outline/outline#7196]
1. Make a page called Page A.
2. In Page A, add an image at the top.
3. Publish Page A.
4. Share Page A publicly.
5. Add a second page, Page B, that is nested within the previously created page.
6. Publish Page B.
7. In an Incognito/InPrivate window, browse to the publicly shared version of Page A.
8. In the left pane of the public version of Page A, click in the search box.
9. In the search box, type a few letters that you know can be found within the two documents.  (The problem does not occur until a search term is matched with a page within the nested documents.)

The image you added to Page A will disappear.

**Expected behavior**

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: [getoutline.com or self hosted]
- Version: [commit sha if self hosted]

**Desktop (please complete the following information):**

**Mobile (please complete the following information):**

**Comment by tommoor** [comment]
Are you able to reproduce on https://docs.getoutline.com/s/guide ?

**Comment by loosus** [comment]
> Are you able to reproduce on https://docs.getoutline.com/s/guide ?

Yes.  If I type "co" in the search box, the image disappears.

I've noticed that occasionally, the image does not always fully disappear.  It just "blinks" (I guess quickly disappearing and reappearing?).  But it mostly disappears.

FWIW, I'm on the latest version of Chrome on MacOS.

**Comment by tommoor** [comment]
Got it, yep that should be easy to track down
