### ISSUE TITLE
OIDC with Gitlab creating multiple workspaces upon login

### ISSUE THREAD

**Issue by greenertux** [outline/outline#7201]
**To Reproduce**
1. Log in using Gitlab
2. Click on the top left "Wiki" symbol
3. You will see more workspaces appearing over time as you log in and out repeatedly. Interestingly when you log in again you are sometimes randomly assigned to an workspace team, sometimes to a new one.

**Expected behavior**
Only one workspace should exist with all users in it.

**Screenshots**
![grafik](https://github.com/outline/outline/assets/13280348/c4bcc065-68dd-4cad-8d7f-969c370353f1)

**Outline (please complete the following information):**
- Install: Docker self hosted
- Version: 0.77.2

**Comment by tommoor** [comment]
Hard to make sense of, for sure. Could you show what is the contents of the `teams` table in the db.

**Comment by greenertux** [comment]
![Screenshot Outline Teams Table](https://github.com/outline/outline/assets/13280348/4b7f2c81-7476-47c8-a0b9-29c76a3b9595)
Thanks for your quick reply, this is our `teams `table in the db

**Comment by tommoor** [comment]
This seems expected if there are multiple teams. Could you also post the `authentication_providers` table content and that should be enough to debug from here.

**Comment by greenertux** [comment]
This is the authentication_providers table, thanks for your help.

![Screenshot Outline Authentication_Providers Table](https://github.com/outline/outline/assets/13280348/d3723669-786b-4d3c-8ecc-b0e8da43c2c3)

**Comment by tommoor** [comment]
Tracing the code I'm still not really able to see how this is possible, what is `URL` env set to?

**Comment by greenertux** [comment]
URL in docker.env is set to https://outline.ruppiner-kliniken.de

**Comment by marpetr** [comment]
I'm also observing the same behavior in v0.77.3 using GitLab auth provider. Every now and then a new authentication provider, team and user combo is created, and a random one is picked when logging in.

**Comment by tommoor** [comment]
It makes no sense, there should _never_ be more than a single team when self-hosting.

https://github.com/outline/outline-enterprise/blob/d1445993300c9a46306fe549a44cf59fd4be4ae7/plugins/oidc/server/auth/oidc.ts#L94

This call finds the team related with the login, in the case of self-hosted it literally just queries the first team in the database:

https://github.com/outline/outline-enterprise/blob/d1445993300c9a46306fe549a44cf59fd4be4ae7/server/utils/passport.ts#L128

**Comment by greenertux** [comment]
Is there anything else we can try or do you have any plans on how to proceed with this issue?

**Comment by greenertux** [comment]
Problem still exists with 0.78 even when I start with a clean database. Could it be that something is saved in Gitlab that confuses Outline?

**Comment by tommoor** [comment]
This is a serious issue that still needs investigating, will try to do so before next release but very short on time.

**Comment by greenertux** [comment]
Would it help if I set up a Gitlab and Outline instance and give you access? Can you provide a means of contacting you directly in case that would help?

**Comment by tommoor** [comment]
Access to a GitLab instance that reproduces the issue would be helpful, no need for Outline. Contact details are on this page: https://www.tommoor.com

**Comment by greenertux** [comment]
Sent you the access data for a public Gitlab test instance via e-mail.

**Comment by DevBuilderX** [comment]
I am also seeing the same behavior using Vault OIDC

**Comment by tommoor** [comment]
There are some potential fixes in a new prerelease build `v0.79.2-0`, see if it resolves the issue. Ideally you'd try this on a fresh database as existing duplicate rows will cause indeterminate behavior.

**Comment by greenertux** [comment]
> There are some potential fixes in a new prerelease build `v0.79.2-0`, see if it resolves the issue. Ideally you'd try this on a fresh database as existing duplicate rows will cause indeterminate behavior.

Awesome, happy to test it! Is there a docker image for the prerelease version?

**Comment by tommoor** [comment]
It's building right now, should be available in next 5 minutes.

**Comment by greenertux** [comment]
Looks like v0.79.2-0 indeed fixes our issues - I have tested with a fresh database and data volume.

**Comment by greenertux** [comment]
Could it be, that the fixes from v.79.2-0 did not make it into upstream? 
We upgraded to 0.80.1 yesterday and the issues with multiple workspaces and users in the wrong one came back. Reverting to v.79.2-0 helped, so we're good for now, but of course we would like update to future versions at some point.
