### ISSUE TITLE
Проблема с редактированием текста. Вылет из программы. 

### ISSUE THREAD

**Issue by allowq-tech** [outline/outline#7213]
В коллекции КНИГА о CRM , постоянно выкидывает из редактирования каждые 20 секунд. Браузер Хром от Гугл. В яндексе такая же ситуация. Без VPN. 
![image  4OvssR](https://github.com/outline/outline/assets/175110390/523be6b7-1c81-4208-8ee4-478720431e16)

**Comment by rgaliull** [comment]
I see that you are using the built-in translator in your browser, turn off the translation and check again.

Судя по скрину, вы используете встроенный переводчик в браузере, выключите перевод и проверьте снова.
