### ISSUE TITLE
Buttons don't behave as they use to/ fail upoad failed everytime

### ISSUE THREAD

**Issue by dashvtka** [outline/outline#7216]
Hello, Buttons on the page are not working. 
When you try to open the collections, just to watch the tree of docs, it opens the page of the collection you've tried to watch.
Not working buttons:
1) creating a new doc from a left toolbar.
2) publish
3) settings
4) closing bar with collections
5) in process of creating comments:
5.1) publish
5.2) cancel
5.3) adding image

When you create a new document, it cannot be published or renamed. It cannot save the name of the document.
When you want to upload a copied picture, it's always saying that upload is failed.
When you try to make a file attachment, it says that upload failed.
**Outline (please complete the following information):**
- Install: getoutline.com
- Version: 0.78.0-0

**Desktop (please complete the following information):**
 - OS: windows 10 pro
 -  Browser: chrome, safari, edge, яндекс

**Mobile (please complete the following information):**
 - Device: iPhone11
 - OS: iOS 16.1.1
 - Browser: chrome, safari, edge, яндекс

**Comment by tommoor** [comment]
Your report is confusing as it says `getoutline.com` but also a version number, I'm guessing this is self-hosted?

It sounds like most requests to the server are erroring in the background, please provide logs from the server itself and from the browser console to better see what is happening.

**Comment by dashvtka** [comment]
i was clicking on settings button

**Comment by dashvtka** [comment]
I cannot get logs from server as I am a regular user of outline. And person who made outline for documentation cannot help me to solve these problems.

**Comment by dashvtka** [comment]
So there are some problems can be on server on which is hosted outline? 
If is it correct, I'll talk with person who responsible for this field. Thank you a lot for fast answers.

**Comment by tommoor** [comment]
I'm closing this now, if you gather error logs feel free to reopen
