### ISSUE TITLE
Drafts count in sidebar is incorrect if there are more than 25 drafts

### ISSUE THREAD

**Issue by tommoor** [outline/outline#7219]
Because we only fetch the first page. There was an assumption that most people have less than 25 drafts, which holds true but those with more have noticed this 😉

**Comment by tommoor** [comment]
The pragmatic thing to do here is just show `25+`, there is no need for this count to be deadly accurate

**Comment by aqeebpathan** [comment]
I'm new to contributing. Could you please share a screenshot where the issue is present?
