### ISSUE TITLE
OIDC Token Revocation and Expiration

### ISSUE THREAD

**Issue by bridge-four** [outline/outline#7221]
With an OIDC authentication configuration, Outline is currently setting its own access token cookie with an arbitrary expiration period of 3 months. 

https://github.com/outline/outline/blob/37e68413f0b59b7fdd21ee18db1373f8aac5685c/server/routes/auth/index.ts#L34-L37

Best security practices recommend using the OIDC provider's token management capabilities to handle token expiration and revocation.

**To Reproduce**
1. Revoke a token/user on OIDC provider platform
2. User continues to use Outline fully-authenticated with their issued `accessToken` cookie 

**Expected behavior**
App should use access and refresh token provided by OIDC provider, automatically obtaining new access tokens upon expiration. This allows OIDCs to control expiration periods and enforce specific access policies.

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.77.2

**Desktop (please complete the following information):**
- OS: MacOS
- Browser: Chrome
- Version: 126

**Comment by tommoor** [comment]
> User continues to use Outline fully-authenticated with their issued accessToken cookie

This isn't entirely correct – we check the OIDC token every time the app is loaded, so they will be logged out immediately upon reopening the app.

> App should use access and refresh token provided by OIDC provider,

I don't see any path to making this change, re-using the credentials would be a very odd approach here. One thing we could do is to refresh the token more often if the app stays open and is not reloaded. I think there's certainly also a need to make the session timeout less "arbitrary" and a configurable value.

**Comment by bridge-four** [comment]
Hi @tommoor, thanks for the quick response! What exactly do you mean by every time the app is loaded? I'm just trying to figure out what I might be doing wrong because I can definitely reproduce the behavior I described with OIDC setup using Okta:

1. Log into Outline with test user, complete OIDC flow. Close browser.
2. Use Okta admin console to clear the user session for test user (which also revokes OIDC/OAuth tokens)
![Screenshot 2024-07-10 at 4 22 35 PM](https://github.com/outline/outline/assets/12418879/b01a4345-01ac-45eb-9a82-d160eca46e6f)
2. Reopen browser and re-visit Outline, verify I am still authenticated.

**Comment by tommoor** [comment]
We only check a max of every five minutes so you might just have to wait that amount of time.

**Comment by bridge-four** [comment]
Hmmm nope, I waited over 30min before re-opening Outline, still auth'd 🤔  Happy to pursue any other troubleshooting steps you'd suggest or provide additional configuration info to track down. Lmk!

**Comment by tommoor** [comment]
Take a look for `ValidateSSOAccessTask` in the logs, this would be run open opening the app

**Comment by bridge-four** [comment]
Oh, interesting, yeah I'm seeing a bunch of these invalid JSON logs for `ValidateSSOAccessTask`:

```
{"label":"worker","level":"info","message":"ValidateSSOAccessTask running","userId":"[redacted]"}
{"error":"invalid json response body at https://[redacted].okta.com/oauth2/v1/userinfo reason: Unexpected end of JSON input","level":"error","message":"Error processing task in ValidateSSOAccessTask","stack":"BadRequestError: invalid json response body at https://[redacted].okta.com/oauth2/v1/userinfo reason: Unexpected end of JSON input\n    at InvalidRequestError (/opt/outline/build/server/errors.js:99:34)\n    at OIDCClient.userInfo (/opt/outline/build/server/utils/oauth.js:36:47)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async UserAuthentication.validateAccess (/opt/outline/build/server/models/UserAuthentication.js:83:9)\n    at async Promise.any (index 0)\n    at async /opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:33:23\n    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:507:18\n    at async ValidateSSOAccessTask.perform (/opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:19:5)\n    at async Queue.<anonymous> (/opt/outline/build/server/services/worker.js:120:14)"}
```

Is it possible for me to extract the raw access token from the database to troubleshoot? Curious why that request is failing.

**Comment by tommoor** [comment]
> Is it possible for me to extract the raw access token from the database 

Not directly, it's encrypted. The easiest would be to patch `build/server/utils/fetch.js` (you can mount a file in it's place, patch inside the docker container, or build from source) to log out the `init` object which would include all request info – I can probably add this as a debug option in future releases.

**Comment by bridge-four** [comment]
Cool, patched fetch.js and investigated `init` object in logs. This is interesting - it appears that it's using an expired access token as the bearer token, which results in a 401 to the `userinfo`, explaining the `ValidateSSOAccessTask` failures. 

Exploring some more and I noticed these log entries too:
```
{"label":"authentication","level":"debug","message":"No refresh token found, skipping refresh"}
```
and sure enough, in postgresql, there aren't any entries in the `refreshToken` column of the `user_authentications` table for any of my users. This seems unexpected - any ideas?

**Comment by tommoor** [comment]
> there aren't any entries in the refreshToken column

If there isn't a refresh token stored then it's generally because your OIDC provider isn't sending one – often this is a setting that needs explicitly enabling

**Comment by bridge-four** [comment]
Yep you're right - the solution here was adding `offline_access` to the OIDC_SCOPES in `docker.env`. Totally missed that before. With that scope added, looks like it's populating the `refreshToken` column now with new sessions and I hopefully won't see any more failures with `ValidateSSOAccessTask`. I'll do some additional validation and close this out if I don't see any other issues - thanks for the assistance @tommoor !
