### ISSUE TITLE
Comment button sometimes doesn't show up after page reload

### ISSUE THREAD

**Issue by threema-danilo** [outline/outline#7226]
**To Reproduce**
1. Go to a page within a collection
2. Using the collection navigation, go to a different page within that collection
3. Highlight a word. The "comment" icon shows up in the pop-up menu
4. Reload the page
5. The pop-up menu does not appear anymore when highlighting a word. When going into the edit mode, the regular menu (with text formatting) does appear, but it does not include the comment button
6. Navigate to a different page using the collection navigation (without page reload), commenting works again

Note: In some cases, the comment button does show up after a page reload, and it seems to depend on the collection or on the complexity of the page itself. In some collections, it shows up almost always. In other collections, with pages containing very little content, it only shows up in maybe 1 or 2 out of 10 reloads. My suspicion is that it's a race condition while loading the page, causing state inconsistencies.

**Expected behavior**

I would expect the comment icon to always show up when highlighting words.

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.77.2

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 127.0.2

(Also reproduced in Brave browser on macOS)

**Comment by tommoor** [comment]
What are the permissions on the collection/document? I'm not able to reproduce in development or cloud currently, but you mentioned it was inconsistent

**Comment by threema-danilo** [comment]
@tommoor I have permissions to edit pages in that collection. Or were you asking about something else?

Maybe @nliechti has something to add to this? He also managed to reproduce.

**Comment by nliechti** [comment]
I could not really reproduce anything reliable yet. I now have a complete subsection of one Collection where wether the commenting nor editing works. Not sure if these are connected, but i wanted to mention that here.
Other documents in the Collection work just fine.

**Comment by tommoor** [comment]
It all sounds related in that the policy your frontend is receiving says that you don't have access to these features for some reason. Just need to figure out which api response is giving incorrect policy results :/

**Comment by Azn9** [comment]
I sometimes have the same issue. When this happens, is there any log/request etc. that we could record to help you identify the issue @tommoor ?

**Comment by tommoor** [comment]
Most telling would be, are there any other actions missing? Eg in the document menu are all usual options there?

If you can record which policies are returned in the `documents.info` request that would be ideal

**Comment by tommoor** [comment]
Let me know if it's any better in `v0.79.0`
