### ISSUE TITLE
When duplicating a page without publishing, mentioned people are notified immediately

### ISSUE THREAD

**Issue by threema-danilo** [outline/outline#7227]
**To Reproduce**
1. Create a page with multiple mentions
2. Those people are notified
3. Duplicate the page, but do not publish the page
4. Even without publishing the page, the mentioned people are notified

**Expected behavior**
I would expect mentioned people to be notified only when publishing. This is important e.g. when duplicating meeting notes containing mentions (therefore using the previous page as a template). I only want people to be mentioned after the publication (when having cleaned up the contents of the previous meeting notes).

(Being able to duplicate a page without publishing is a fairly recent feature. This behavior is probably just an oversight?)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.77.2

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 127.0.2

**Comment by tommoor** [comment]
> Even without publishing the page, the mentioned people are notified

In my testing duplicating the page won't create a notification, but if you _edit_ the page at all then notifications are triggered at this point. I think this is desired/expected behavior as it's the same as any other draft

**Comment by threema-danilo** [comment]
Ah, I see what you mean. So the way to go - if I wanted to avoid notifications - is removing the mentions before saving for the first time?

**Comment by tommoor** [comment]
Yes, I think so. You can also create a template without the mentions in it but have placeholders instead where the mentions will go upon creating a new doc
