### ISSUE TITLE
OIDC with Apple requires response_mode

### ISSUE THREAD

**Issue by Zgrill2** [outline/outline#7231]
When using OIDC with Apple for Outline either Outline or Apple has an issue with a request or response (depending on configuration). 

**To Reproduce the Apple OIDC Request Error**

1. Configure Outline OIDC with Apple
```OIDC_CLIENT_ID=
OIDC_CLIENT_SECRET=
OIDC_AUTH_URI=https://appleid.apple.com/auth/authorize
OIDC_TOKEN_URI=https://appleid.apple.com/auth/token
OIDC_USERINFO_URI=https://does.not.exist.com/api/oidc/userinfo (Apple does not support this endpoint)
OIDC_USERNAME_CLAIM=email
OIDC_DISPLAY_NAME=Sign-in with Apple
OIDC_SCOPES="openid email"
```
To setup `OIDC_CLIENT_ID` and `OIDC_CLIENT_SECRET` Okta has created a fantastic guide [here](https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple). If you prefer Apple's official docs, they are [here](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/configuring_your_webpage_for_sign_in_with_apple). I used Apple's docs but ended up finding the Okta doc when I had to use the private key generated by Apple to create the `OIDC_CLIENT_SECRET`.
2. Start the Outline server via `docker compose up`
3. Navigate to `outline.example.com` in a web browser
4. Click the OIDC button (labeled "Sign-in with Apple" if using the configs in step 1)
5. Redirected to Apple and will see the error "response_mode must be form_post when name or email scope is requested."

**Screenshots**
Invalid Request (error in step 5 above)
![image](https://github.com/user-attachments/assets/025b5d77-093f-41bf-9738-7ce708649538)

**To Reproduce the Outline OIDC Response Error**
Also tried excluding `email` from `OIDC_SCOPES`. Steps to reproduce the behavior:
1. Exclude email from OIDC_SCOPES. Should look like: `OIDC_SCOPES="openid"`` (Rest of config from previous repro steps unchanged)
2. Follow rest of steps in Reproduce the Apple OIDC Request Error above
3. When redirected back to Outline, will still see the login screen. Browser dev tools Network calls will show a 401 unauthorized response for the call to `https://outline.example.com/api/auth.info`
4. Additionally, opening Outline in a browser on the same or a different computer will hand and result in a gateway timeout error. No logs appear in Outline during this. To resolve this, must fully stop the docker stack and then start it.

**Screenshots**
Error log in Outline
```ERR Error during authentication | error=An email field was not returned in the profile parameter, but is required. stack=UnauthorizedError: An email field was not returned in the profile parameter, but is required.
    at AuthenticationError (/opt/outline/build/server/errors.js:44:34)
    at OAuth2Strategy._verify (/opt/outline/build/plugins/oidc/server/auth/oidc.js:65:47)
    at /opt/outline/node_modules/passport-oauth2/lib/strategy.js:196:24
    at _passportOauth.Strategy.userProfile (/opt/outline/build/plugins/oidc/server/auth/oidc.js:25:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
```
Screenshot of Outline post redirect back to Outline
<img width="345" alt="image" src="https://github.com/user-attachments/assets/1e6da093-88a1-4eb3-b49a-e8253834cac3">

Screenshot of 401 Unauthorized post redirect back to Outline
<img width="867" alt="Outline_401" src="https://github.com/user-attachments/assets/8a13093c-6ba7-431f-b9d3-eff16b06e771">

**Expected behavior**
Apple prompts for a login, then redirects to Outline which is now authenticated.

**Outline (please complete the following information):**
- Install: Self Hosted via Docker
- Version: `outlinewiki/outline:0.75.2@sha256:7c7038f39760ffb882c5b9290a60174598de03a031995a140d48d60a06c3881c`

**Desktop (please complete the following information):**
 - OS: MacOS 14.4.1 w/ Apple Silicon (arm64)
 - Browser: Chrome
 - Version: 126.0.6478.127

**Desktop (please complete the following information):**
 - OS: Windows 11 (x64)
 - Browser: Chrome
 - Version: 126.0.6478.127

**Mobile (please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17.5.1
 - Browser: Safari

*Additional Notes*
- Used in-private browsing
- Tried manually including `&response_mode=form_post` in the GET request to Apple authorize endpoint. 
```
https://appleid.apple.com/auth/authorize?response_type=code&redirect_uri=https%3A%2F%2Foutline.example.com%2Fauth%2Foidc.callback&scope=openid%20email&state=aa1a4e7eed8fe98b&client_id=com.example&response_mode=form_post
```
Doing this allows me to sign into Apple but on redirect to Outline results in Not Found: `POST https://outline.example.com/auth/oidc.callback 404 Not Found`.

**Comment by tommoor** [comment]
Is this a bug or is this Apple not conforming to the same standards as everyone else? 😉 

I think we can be happy to fix this as long as it doesn't introduce special cases just for Apple into the OIDC logic. e.g. supporting POST response is totally fine, and supporting having `response_mode=form_post` in the `OIDC_AUTH_URI` url is also very doable. I suspect though that it still won't work if they do not have a userinfo endpoint?

**Comment by Zgrill2** [comment]
I upgraded in my dev environment to the latest outline image `outlinewiki/outline:latest@sha256:c1cd4081888d8139b0eeecc0bfa45cfbf359364587934297c154b55e64f92873` just to confirm the issue is still present in master. It is.

I changed my `OIDC_AUTH_URI` to `https://outline.example.com?response_mode=form_post` as suggested and it did get me past the "response_mode must be form_post when name or email scope is requested." error. Unfortunately for whatever reason once the callback uri (`https://outline.example.com/auth/oidc.callback`) is hit, it returns a 404.

From the container logs
```
2024-07-13T00:07:02.925962750Z INF   <-- POST /auth/oidc.callback | label=http 
2024-07-13T00:07:02.927564140Z INF   --> POST /auth/oidc.callback 404 2ms - | label=http 
```

<img width="799" alt="Outline_callback_404" src="https://github.com/user-attachments/assets/15adad8c-f3c6-48ff-9a1c-8b54046f60a2">

**Comment by tommoor** [comment]
This is because there is no `POST` handler registered for the callback but I think it would be totally fine and easy to add that and handle both get and post.

**Comment by tommoor** [comment]
☝️ merged, let me know if you give it a try

**Comment by Zgrill2** [comment]
Hello, gave it a shot and it did get me past that error. 

The next error I hit was `plugins/oidc/server/auth/oidc.ts:90` as the userinfo path doesn't exist in apple so I was supplying a dummy path. I spun up a get endpoint with fastapi and returned `{"email": "email@example.com"}` and that let me to the final error I got stuck on:

```
2024-07-13T05:30:36.653985929Z ERR Error during authentication | error=null value in column "providerId" of relation "user_authentications" violates not-null constraint stack=Error
    at Query.run (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /opt/outline/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresQueryInterface.insert (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)
    at async UserAuthentication.save (/opt/outline/node_modules/sequelize/lib/model.js:2490:35)
    at async /opt/outline/node_modules/sequelize/lib/model.js:2541:13
    at async Promise.all (index 0)
    at async /opt/outline/node_modules/sequelize/lib/model.js:2522:9
    at async Promise.all (index 0)
    at async User.save (/opt/outline/node_modules/sequelize/lib/model.js:2511:7)
    at async user.create (/opt/outline/node_modules/sequelize/lib/model.js:1362:12)
    at async userProvisioner (/opt/outline/build/server/commands/userProvisioner.js:176:18)
    at async accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:79:12) 
```

I tried but couldn't get past this one; I'm not familiar enough with the standard to know where `providerId` comes from or what values are expected.

Suffice to say though that the Sign-in with Apple implementation is too non-standard to conform without handing this special case within Outline. From some cursory reading I did into the lack of a userinfo endpoint it seems true the email and other required info can be obtained or derived still which is why Apple decided not to implement that endpoint, but that is clearly not in compliance with the OIDC specification.

**Comment by tommoor** [comment]
You would need to return a `id` for the user in the userinfo response. I'd need to take a look if the token from Apple can be parsed as a JWT, it might contain all the information needed without hitting the userinfo endpoint and that would potentially still be compliant in a way that can be changed.

This isn't super high on the list though as Outline is designed for teams and they tend not to use Apple sign-in as the goto authentication method
