### ISSUE TITLE
Link didn't consider port cause open error

### ISSUE THREAD

**Issue by Mowd** [outline/outline#7245]
Outline didn't handle port of url which cause outline try to open document inside the workspace.

**To Reproduce**
1. Setup a self-hosted Outline on https://example.com:3000
2. Create a document and add a link to https://example.com/some/path (it's not outline)
3. Open this link will cause 404 not found inside the outline.

**Expected behavior**
I except it will redirect me to the URL, not try to open a document inside the outline.

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.77.3

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge
 - Version: 127.0.2651.49

**Comment by Pranav2612000** [comment]
Hey @tommoor ! I'll like to work on this.

**Comment by Mowd** [comment]
@tommoor I've checked this issue, and the link still considered internal in 0.79.1

outline is host on https://example.com:3000
when I click a link (https://example.com/somepage), it still try to redirect me to https://example.com:3000/somepage

**Comment by tommoor** [comment]
☝️ Ah fixed, the code that was changed in shared lib only affected the server side.
