### ISSUE TITLE
image failed to load

### ISSUE THREAD

**Issue by thumDer** [outline/outline#7248]
Some of our pages have lost all embedded images, and they look like as attached. It is also not possible to download them, as expected. This pages were fine before (like a few months before when they were authored)

**To Reproduce**
¯|_(ツ)_/¯

**Expected behavior**
Show my images

**Screenshots**
![image](https://github.com/user-attachments/assets/81d44658-ea32-4ed1-9cf4-6d548cd2e7a8)

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: win 11
 - Browser: multiple

**Comment by tommoor** [comment]
If this is an issue with getoutline.com I recommend you contact the support email directly hello@getoutline.com with details of the affected documents

**Comment by tommoor** [comment]
It looks like these were remote images that are no longer accessible

**Comment by thumDer** [comment]
Right, thanks! Is there any way to differentiate between embedded and uploaded (or internal vs external) images? So far I wasn't able to.

**Comment by tommoor** [comment]
Currently only by right clicking on the image to get the url, however in the case of an image that failed to load like this that option is no longer possible.

The case of externally hosted images hasn't been considered too much, improvements need to be made here to make that url accessible
