### ISSUE TITLE
Importing .txt with accented letters causes character not found encoding char

### ISSUE THREAD

**Issue by sf-jd** [outline/outline#725]
1- Select "..." on the top right
2- Click on import document
3- Select a txt file containing accented/tilde characters (í, é, ó)
4- Notice that after import the characters are replaced with a ? character

When importing a .txt file created in windows with notepad, the letters ó í é ú etc are replaced by the ? character as if the encoding was not being properly read.
When attempting to write the actual letters, there's no problem.

Adding a screencap for reference.
![imported-document-notildes](https://user-images.githubusercontent.com/21987975/43109422-2726c9d0-8ebd-11e8-91f3-4f944f070c26.PNG)

**Comment by tommoor** [comment]
Are you able to save the document in UTF8 character set and see if it imports correctly then?
