### ISSUE TITLE
429 Client Error: Too Many Requests for url when using API

### ISSUE THREAD

**Issue by Lunaden** [outline/outline#7263]
Hello,

I am experiencing a `429 Client Error: Too Many Requests` error when using the API to create multiple user groups. The specific URL causing the issue is `https://wiki.contoso.domain/api/groups.create`.

**Details:**
- **API URL:** `https://wiki.contoso.domain/api/groups.create`
- **Error Message:** `429 Client Error: Too Many Requests`
- **Environment:** On-premise container, Outline version 0.77.2

**Steps to Reproduce:**
1. Attempt to create multiple user groups via the API.
2. Encounter the `429 Too Many Requests` error.

**Troubleshooting Attempts:**
- I checked the API documentation but found no mention of a rate limit or specific indications regarding the 429 error.
- The interface does not appear to offer any options to modify a potential rate limiter.
- The environment file contains the following configurations, but they do not seem to affect the API rate limit:

```env
# Optionally enable rate limiter at application web server
RATE_LIMITER_ENABLED=false

# Configure default throttling parameters for rate limiter
RATE_LIMITER_REQUESTS=10000
RATE_LIMITER_DURATION_WINDOW=60
```

**Questions:**
1. Is there an undocumented rate limit for the API, particularly for the `groups.create` endpoint?
2. Are there any configurations or settings within the application that could influence this rate limit?
3. Is it possible to adjust or disable the rate limiter for the API, and if so, how can this be achieved?

Thank you for your assistance.

Best regards,

**Comment by beliven-valentino-cossar** [comment]
Hi @tommoor, I'm encountering the same issue. If I comment out the `RATE_LIMITER_ENABLED` environment variable or set it to false, the problem doesn't occur. However, when `RATE_LIMITER_ENABLED` is set to true with the following configurations:
```
RATE_LIMITER_REQUESTS=1000
RATE_LIMITER_DURATION_WINDOW=60
```
I still face the issue. I replicated this locally by creating 11-15 groups (without members).

I also tried adjusting the settings to:
```
RATE_LIMITER_REQUESTS=5000
RATE_LIMITER_DURATION_WINDOW=10
```
But it didn't resolve the problem (always with 11-15 groups).

**Comment by tommoor** [comment]
This is expected behavior, the `RATE_LIMITER` env variables set a default rate limit which covers all endpoints. Individual mutation endpoints and those contacting third-party services have tighter limits depending on their functionality.

**Comment by beliven-valentino-cossar** [comment]
Thank you @tommoor! So, once activated the rate limiter, on specific endpoints there are specific rules not customizable from env vars?

Maybe it is worth updating the rate limiter documentation (https://docs.getoutline.com/s/hosting/doc/rate-limiter-HSqErsUgXH)?

**Comment by tommoor** [comment]
There is already a sentance there, but I will try and make it more clear – thanks!

**Comment by beliven-valentino-cossar** [comment]
Super, thank you @tommoor! 👍
