### ISSUE TITLE
After upgrade from 0.61.1 to 0.77.3, existing users can't log in through Google

### ISSUE THREAD

**Issue by alexislefebvre** [outline/outline#7271]
We duplicated our instance of Outline and upgraded it from 0.61.1 to 0.77.3, existing users can't log in through Google.

We followed this documentation to generate new credentials for the new sub-domain bound to this new instance: https://docs.getoutline.com/s/hosting/doc/google-hOuvtCmTqQ

**To Reproduce**
1. Open Outline
2. Log in through Google
3. Get an error about the Google auth

**Expected behavior**
Log in should work.

**Logs**

```
{"label":"http","level":"info","message":"  <-- GET /auth/google.callback?state=[…]&code=[…]&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=1&hd=[…]&prompt=consent"}
{"error":"Validation error","level":"error","message":"Error during authentication","stack":"Error\n    at Query.run (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /opt/outline/node_modules/sequelize/lib/sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresQueryInterface.insert (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)\n    at async User.save (/opt/outline/node_modules/sequelize/lib/model.js:2490:35)\n    at async user.create (/opt/outline/node_modules/sequelize/lib/model.js:1362:12)\n    at async userProvisioner (/opt/outline/build/server/commands/userProvisioner.js:176:18)\n    at async accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:79:12)"}
{"label":"http","level":"info","message":"  --> GET /auth/google.callback?state=[…]&code=[…]&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=1&hd=[…]&prompt=consent 302 264ms 69b"}
{"label":"http","level":"info","message":"  <-- GET /?notice=auth-error"}
```

**Formatted stack trace**

```
Error
at Query.run (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
at /opt/outline/node_modules/sequelize/lib/sequelize.js:315:28
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PostgresQueryInterface.insert (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)
at async User.save (/opt/outline/node_modules/sequelize/lib/model.js:2490:35)
at async user.create (/opt/outline/node_modules/sequelize/lib/model.js:1362:12)
at async userProvisioner (/opt/outline/build/server/commands/userProvisioner.js:176:18)
at async accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:79:12)
```

Is it trying to create one user? This account already exists in the database.

**Screenshots**
.

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.77.3

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS 
 - Browser: Mozilla Firefox
 - Version: 128.0

**Comment by alexislefebvre** [comment]
I check the data which was used to check if the user existed, and after some research, it looked for the correct email but the wrong team. We removed the team which had no user. And now we have an error:

> {"level":"warn","message":"\nThis version of Outline cannot start until a data migration is complete.\nBackup your database, run the database migrations and the following script:\n(Note: script run needed only when upgrading to any version between 0.54.0 and 0.61.1, including both)\n\n$ node ./build/server/scripts/20210226232041-migrate-authentication.js\n"}

We initially copy-pasted the whole database with `rsync`, we'll try to transfer the database with the export / import function to see if that fixes the issue.

**Comment by alexislefebvre** [comment]
We fixed the issue by removing one team that was bound to the Slack auth, that we don't use:

```sql
outline=# SELECT * FROM authentication_providers;
       id     |  name  | providerId | enabled |  teamId      |         createdAt          
--------------+--------+------------+---------+--------------+----------------------------
 2e4ba4d7-[…] | google | […]        | t       | ef4e6cf1-[…] | 2022-01-19 12:37:45.01+00
 aaf01e1f-[…] | slack  | T02[…]     | t       | 330e03c8-[…] | 2022-01-19 12:37:45.098+00
(2 rows)

outline=# DELETE FROM authentication_providers WHERE id = 'aaf01e1f-[…]';
DELETE 1

outline=# DELETE FROM events WHERE "teamId" = '330e03c8-[…]';
DELETE 3

outline=# DELETE FROM teams WHERE id = '330e03c8-[…]';
DELETE 1
```

**Comment by tommoor** [comment]
Thanks for documenting, I'm glad you got this working. In self-hosted mode there should never be more than a single team in the database, the behavior can be unpredictable if that ends up being the case.
