### ISSUE TITLE
Healthcheck not included in v0.78.0 release

### ISSUE THREAD

**Issue by almereyda** [outline/outline#7279]
The healthcheck is not accessible from the built container image.

**To Reproduce**
1. Pull the v0.78.0 image
2. Remove manual healthchecks in `compose.yml`
3. Restart the Outline container with it. It doesn't have a healthcheck.
4. Run `docker-compose exec outline bash -c "type wget"`

```
bash: line 1: type: wget: not found
```

**Expected behavior**

The healthcheck works.

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.78.0

**Additional information**

#7085 implemented a healtcheck in the `Dockerfile.base` image, which is ultimately not used in the `Dockerfile`.

It is loaded first in

https://github.com/outline/outline/blob/fd1e14d1db0cb5a3f2f9013302be85b693d05731/Dockerfile#L2

But then it is discared again by building on top of

https://github.com/outline/outline/blob/fd1e14d1db0cb5a3f2f9013302be85b693d05731/Dockerfile#L7-L8

These two lines are maybe some debugging code (`# ---`?) that was left in place?

- https://hub.docker.com/layers/outlinewiki/outline/0.78.0/images/sha256-e5de42e0b5225af9340f521cc0a868d07ad5695574c24fddeb3cdc92935dc8b7?context=explore

**Comment by almereyda** [comment]
I'm using #7094 as a workaround.

**Comment by almereyda** [comment]
Blaming the two lines, these are the commits where those lines had been touched:

f35676f3473e358f3778095c2dcf9cb7f1e1d644 `curl` had been removed

14a96e7262836664486347334c26c0032f6a3758 both Dockerfiles were cosmetically improved

**Comment by tommoor** [comment]
I'll remove it from the release notes

**Comment by SilasPeters** [comment]
I don't have a linear account. Is there another way to know the current status of this issue?

**Comment by tommoor** [comment]
The status is mirrored here, nothing has changed just yet

**Comment by almereyda** [comment]
Eventually this could also be a good chance for a cycle that includes removing the two-Dockerfile approach with a base image and the application build separated. To me it appears this could have been avoided with a single file to look at. For maintainability, it would be my choice.

Yet I figure this may be related to the different code bases of the open core and the commercial product. This way the second stage of the enterprise version can build upon the same base image.

For what it's worth, the build machine is also equipped with a layer cache. Meaning identical lines in the Dockerfile following the same order will yield the same content-addressable hash. If enterprise and open core versions were built on the same machine, while their Dockerfiles overlap significantly at the beginning, the build cache will make sure not to waste precious cycles.

Reference:

- [Multi-stage builds | Docker Docs](https://docs.docker.com/build/building/multi-stage/)

**Comment by almereyda** [comment]
Many thanks. 7013a87 is the obvious solution to this, in contrast to my prior comment.
