### ISSUE TITLE
Discord support

### ISSUE THREAD

**Issue by muit** [outline/outline#729]
Hi!

I have to say Outline is amazing! Really fast and minimalisthic, easy to use, great design in general!

I was wondering if you ever though about adding Discord support.
My team and I use it daily and it feels like we are missing a great tool.

It would be really great if we could have support for it, I think a lot more people would be as excited as I am for Outline.

No matter what, thanks for your work, :)
Muit

**Comment by jasonquiz** [comment]
I second this.

My work team uses Slack, but I would love to use Outline for some of the Discord groups I am in.

**Comment by tommoor** [comment]
Thanks gents, it would be good to get an idea for what kind of functionality you're after here. @muit what does discord support look like to you?

**Comment by jasonquiz** [comment]
I assumed @muit was referring to logging in with Discord and then having the same search/expand functionality that Slack has with Outline. Not sure if that is even possible, but it would be nice.

A lot of the groups I game with online use Discord (similar to slack) for communicating around specific games. Being able to log in with Discord would make it easy to set up an Outline wiki for the group. =

**Comment by muit** [comment]
Well, I though being able to log in like you do with slack would be awesome, I've not seen anything nearly similar to it, and when having a team to setup its a plus to be able to share an account.

I dont know what kind of support does discord provide for this, but what I know is that their API is extensive and they have an active bot development community.

NOTE: @jasonquiz just perfectly described the idea haha

**Comment by tommoor** [comment]
It does like like they have an OAuth API so it wouldn't be too hard. I'm more concerned from a UX pov as I don't want to keep adding login methods to the homepage how would be the best way to go about that…

Perhaps this comes with team subdomains so the right login options show up on your teams domain 😉

**Comment by MatheusRV** [comment]
Related to https://github.com/outline/outline/issues/1120, i vote to close this in favor of passport.
