### ISSUE TITLE
Only 25 teams are showing up in the "Share" dropdown

### ISSUE THREAD

**Issue by feingold-ant** [outline/outline#7291]
**To Reproduce**
1. Click the "Share" button to share a collection
2. Note that only 25 teams/groups are showing up in the dropdown. Many more show up in Preferences -> Groups.

**Expected behavior**
There should be some pagination so that all of the groups show up in the share flow under "add or invite ...".

**Screenshots**
I didn't include a screenshot so as not to leak our teams.

**Outline (please complete the following information):**
- Install: self hosted
- Version: d1445993300c9a46306fe549a44cf59fd4be4ae7

**Comment by tommoor** [comment]
Just a heads up that once you start typing a search term the missing groups matching the filter will load in

**Comment by feingold-ant** [comment]
This is what I'm seeing:
- If I try to share my private collection with a group, I'm only seeing the first 25 groups. No amount of typing and waiting makes new groups appear.
- If I go to Preference -> Groups and scroll down, the rest of the groups get loaded.
- Now if I try to share my private collection, the rest of the groups are there in the dropdown.

**Comment by feingold-ant** [comment]
Thanks Tom!
