### ISSUE TITLE
Document title is missing from 'new document published' notification emails

### ISSUE THREAD

**Issue by bkndryhi** [outline/outline#7300]
After upgrading from version 0.75.0 to 0.78.0 we noticed that document titles are now missing from 'new document published' notification emails. (not sure if it's technically a bug, as it might be related to the new 'auto-publish' feature introduced in https://github.com/outline/outline/pull/7243, but it looks weird when I get a bunch of these emails)

**To Reproduce**
1. Go to a published collection
2. Create a new document with the title 'Test'
3. Click on 'Done editing'
4. Check the inbox of a user subscribed to the collection

**Expected behavior**
Document title is present in the email (?)

**Screenshots**
![image](https://github.com/user-attachments/assets/8d420cd8-68db-4bd6-b7e5-7176aea0e312)

**Outline**
- Install: self-hosted
- Version: outlinewiki/outline:0.78.0 image from DockerHub as of 07/23/2024

**Comment by xanderio** [comment]
I believe this is happening as outline on publishes pages on creation, as to creating a draft which must then be published manually. As the just created and published page doesn't have a title we get the lovely "" title :D
