### ISSUE TITLE
Empty body on public document

### ISSUE THREAD

**Issue by maurxce** [outline/outline#7303]
I have published a document to be publicly viewable, but it doesn't display a body, just the title (browser and curl)

**To Reproduce**
1. Create a document
2. Publish it
3. Copy and visit the public URL

**Expected behavior**
Full document is shown, including the body

**Screenshots**
Editor:
![image](https://github.com/user-attachments/assets/898e9bf3-e5c7-4434-b34d-d70e94115165)

Viewer:
![image](https://github.com/user-attachments/assets/3ca36fac-fbd6-4029-9578-98d1b8f0a6d5)

**Outline (please complete the following information):**
- Install: selfhosted
- Version: v0.77.3

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome, Edge
 - Version 126.0.6478.183, 126.0.2592.113

**Comment by tommoor** [comment]
In your first screenshot you can see the disconnected icon in the bottom right – your changes have not persisted to the server and are saved in the browser only. This is likely some sort of configuration issue with websockets, you can see more information in the developer console and server logs to diagnose the issue

**Comment by maurxce** [comment]
I forgot to enable web sockets 🤦 
I really appreciate the fast response!
