### ISSUE TITLE
Share modal doesn't scroll when it gets too long

### ISSUE THREAD

**Issue by bkrausz** [outline/outline#7328]
On latest Chrome...you can see the modal flows below the window (look for the border radius):

![CleanShot 2024-07-30 at 16 58 26@2x](https://github.com/user-attachments/assets/9931d24f-5274-4685-949b-175757a4c0de)

Flexbox doesn't seem to play nice with overflow: scroll. Also seeing this on mobile. I got a fix working for desktop, but it's somewhat ugly so decided to punt to a ticket:

```
diff --git a/app/components/Modal.tsx b/app/components/Modal.tsx
index 5cb396b51..10017c9d8 100644
--- a/app/components/Modal.tsx
+++ b/app/components/Modal.tsx
@@ -120,7 +120,7 @@ const Modal: React.FC<Props> = ({
                     <SmallContent style={style} shadow>
                       <ErrorBoundary component="div">{children}</ErrorBoundary>
                     </SmallContent>
-                    <Header>
+                    <Header shrink={false}>
                       {title && <Text size="large">{title}</Text>}
                       <NudeButton onClick={onRequestClose}>
                         <CloseIcon />
@@ -256,7 +256,8 @@ const Header = styled(Flex)`
 const Small = styled.div`
   animation: ${fadeAndScaleIn} 250ms ease;
 
-  margin: 25vh auto auto auto;
+  margin: 20vh auto auto auto;
+  max-height: 75vh;
   width: 75vw;
   min-width: 350px;
   max-width: 450px;
@@ -285,6 +286,7 @@ const Small = styled.div`
 
 const SmallContent = styled(Scrollable)`
   padding: 12px 24px 24px;
+  overflow: hidden auto;
 `;
 
 export default observer(Modal);
```

I think the right approach is to move off of flexbox for the modal, then `max-height`, etc, can work better, but not positive.

**Comment by tommoor** [comment]
@apoorv-mishra didnt you recently change/fix this?

**Comment by bkrausz** [comment]
@apoorv-mishra I'm on the UI that shows the existing list of members, not the typeahead for new members. It's currently impossible to scroll through the list of all existing members

**Comment by apoorv-mishra** [comment]
Ahh! Sorry for the oversight. Will take a look today...
