### ISSUE TITLE
Uploading Logo results in garbled Images - Images in Documents are fine

### ISSUE THREAD

**Issue by rattencreep** [outline/outline#7329]
When uploading a new logo, be it profile or workspace logo, the resulting image is garbled.

**To Reproduce**
1. Go to 'Profile'
2. Click on 'Photo -> Upload'
3. Select image
![Screenshot 2024-07-25 102458](https://github.com/user-attachments/assets/a2b0be15-157c-45d8-9c9d-d8b286258c66)
5. see this as the new logo image:
![Screenshot 2024-07-25 102506](https://github.com/user-attachments/assets/cb94b25b-8ee2-4c56-89b6-4ce76eaa8b0a)

**Expected behavior**
See this as the new logo image:
![Screenshot 2024-07-25 102458](https://github.com/user-attachments/assets/a2b0be15-157c-45d8-9c9d-d8b286258c66)

**Outline**
- Install: self hosted
- Version: outlinewiki/outline:0.78.0 (docker image)

No errors can be found in the logs.

What can I do to fix this?

**Comment by tommoor** [comment]
No idea, this has never been reported - can you upload the original file here?

**Comment by rattencreep** [comment]
Sorry to have bothered you. It seems to be a browser issue. The above results occur while using LibreWolf. When using Brave all works as expected.
