### ISSUE TITLE
Cannot re-share document link after link revocation

### ISSUE THREAD

**Issue by alelapeyre** [outline/outline#733]
Hello,

After revoking a shared link, I cannot share the document link anymore.

### Steps to reproduce
- Create document
- Share link (the link appears in `settings/shares`)
- Revoke link
- On document, re-share link
- The shared link does not appears in `settings/shares` and i've got a **Not Found** error when opening the link

**Comment by tommoor** [comment]
Thanks for reporting @alelapeyre – It sounds like this should be an easy fix 😄
