### ISSUE TITLE
Want to add URL cards

### ISSUE THREAD

**Issue by QYG2297248353** [outline/outline#7331]
It's kind of like an embedded webpage, which makes the link display more perfect.

For example: https://www.amap.com/place/B03DF069TH

Can be display, link, title, card, preview image

![image](https://github.com/user-attachments/assets/be717ee8-d042-4164-896e-c13d0f6eb5d2)

**Comment by QYG2297248353** [comment]
I'd like to know if it's highly likely to be implemented, and if so, how long would it take to implement a feature point

**Comment by tommoor** [comment]
100% likelihood, just a matter of timing

**Comment by QYG2297248353** [comment]
> 100% likelihood, just a matter of timing

Awesome, really looking forward to this feature. There is almost no support for this feature in similar product voids.

Thanks for your hard work!
