### ISSUE TITLE
Some pictures are imported incorrectly

### ISSUE THREAD

**Issue by ultimatebash** [outline/outline#7341]
I have exported a Confluence Space via HTML export and imported it into Outline via the importer.

I have included images on the various pages, which are also working so far.

Only with one image, it shows the link instead of the image.
The image is represented on 3 pages in total, and on all 3 only the link is displayed instead of the image.
Link: `![](/api/attachments.redirect?id=a4d857e9-8f48-4473-9a80-41d786ac70b0&display=link" =1700x900.2996254681648")
`
**To Reproduce**
1. export Space from confluence via html zip
2. import it via the importer function
3. See error

**Expected behavior**
All pictures to be imported correctly, no links instead
**Screenshots**
![image](https://github.com/user-attachments/assets/513b66f1-db85-4a72-8ab7-16ea529c347d)
The picture above the link is also displayed on the 3 pages, but correctly

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.78, no access to see the sha
- 
**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome
 - Version  125.0.6422.141 64-Bit

**Mobile (please complete the following information):**
not used

**Comment by tommoor** [comment]
The Confluence importer is not part of the community edition, I'd recommend emailing support to get a fix prioritized here!

**Comment by ultimatebash** [comment]
okay thanks, Can I refer to this post, or do I have to repeat it in the email?

Thank you

**Comment by tommoor** [comment]
Yes, you can refer to this

**Comment by tommoor** [comment]
Fixed elsewhere
