### ISSUE TITLE
Attachments are displayed on the wrong page

### ISSUE THREAD

**Issue by ultimatebash** [outline/outline#7342]
I have a self-hosted outline wiki with an imported Confluence Space that also includes images.

The images are on page A, but the corresponding "attachments" are displayed on page B.

If I delete the text "Attachments" and the corresponding link on page B, the images on page A still remain.

Why are the attachments displayed on another page?

If I delete the attachments, the images remain there, so it's not a major problem, but it could still lead to confusion within the team

**To Reproduce**
1. Import Confluence Space with pictures included
2. See error

**Expected behavior**
That the attachments can also be found on the same page as the images 

**Screenshots**
![Screenshot_20240802_122825_censored](https://github.com/user-attachments/assets/df23084c-7875-4286-a1e0-2dcaaec83281)
had to censor some text, as you can see, there are no pictures on this page, but it shows the attachments of other pages

**Outline (please complete the following information):**

Install: self hosted
Version: 0.78, no access to see the sha

**Desktop (please complete the following information):**

OS: Ubuntu 22.04
Browser Chrome
Version 125.0.6422.141 64-Bit
Mobile (please complete the following information):
not used

**Comment by tommoor** [comment]
You should open up and check the contents of the Confluence export, you'll likely find it's exactly the same – we just import what's given in terms of content. The `Attachments` heading is not required by Outline at all and comes from Confluence, you can safely delete it.

**Comment by ultimatebash** [comment]
Thanks
