### ISSUE TITLE
Pasting text doesn't replace placeholders

### ISSUE THREAD

**Issue by gabschne** [outline/outline#7346]
Copy-and-paste does not work with placeholders. The pasted text becomes part of the placeholder and is also replaced when something is typed in.

**To Reproduce**
1. Create a template with a placeholder
2. Create a new document from the template.
3. Copy a text (e.g. a link or any other text).
4. Place the cursor on the placeholder. It'll then automatically jump to the beginning of the placeholder.
5. Paste the copied text from step 3.
6. The pasted text becomes part of the placeholder and will be replaced when something is typed in.

**Expected behavior**
Pasting text should also replace placeholders.

**Outline (please complete the following information):**
- Install: self-hosted
- Version: v0.78.0

**Desktop (please complete the following information):**
 - Browser Chromium/Vivaldi
 - Version 6.8.3381.46

**Comment by tommoor** [comment]
Thanks for reporting
