### ISSUE TITLE
Login with Google created a new account

### ISSUE THREAD

**Issue by zimbatm** [outline/outline#7354]
Duplicate accounts can get created by using different Login methods.

**To Reproduce**

1. Create an account with email ~and password~
2. Login with Google using the same email.

Check jonas@numtide.com as an example.

**Expected behavior**

Complain that an account with the same email already exists, and propose to add this login method. Then ask for the user password to avoid an attack where Google Workspace gets setup by the attacker. 

**Screenshots**
N/A

**Outline:**
- Install: getoutline.com

**Comment by tommoor** [comment]
> Create an account with email and password

There are no passwords in Outline, I'm not sure what you mean with these reproduction steps

**Comment by zimbatm** [comment]
I mean email + magic link. You can check; there are now two accounts with my email address. The first one associated with numtide.getoutline.com, and the second one created numtide1.getoutline.com.

**Comment by tommoor** [comment]
Hey – as far as I can tell this is expected behavior as the same email address can exist in multiple workspaces. If you have an account with an email address at `numtide.getoutline.com` and attempt to sign-in with SSO from that specific subdomain it should link the account.

**Comment by zimbatm** [comment]
Hmm. Aren't the accounts centralized since they can access multiple workspaces? Maybe that's where my confusion is coming from.

If I go to https://numtide.getoutline.com/, it doesn't show the Google login option. And if I go to https://numtide1.getoutline.com it doesn't allow me to login with the magic email link. I had a poke in the settings and couldn't find a way to enable/disable those options.

**Comment by tommoor** [comment]
> Aren't the accounts centralized since they can access multiple workspaces?

Each workspace has separate accounts, I'd recommend emailing into support hello@getoutline.com and we'll get you sorted out.
