### ISSUE TITLE
Commenting only works in dark mode

### ISSUE THREAD

**Issue by christophenne** [outline/outline#7360]
It seems that the little "comment" popover only appears when in dark mode, not in light mode. In light mode I always get the formatting popover. 

**To Reproduce**
1. Open a document
2. Select a word you want to add a comment too
3. The shown popover depends on the used theme: In light mode, the formatting options appear, in dark mode the comment popover.

**Expected behavior**
Same behavior in both modes. 

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.77.3 / 07ae7fca81f738e5cd40488ecad6d42073aac27f

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version 128.0.3

**Comment by tommoor** [comment]
@christophenne cannot reproduce – are you sure you're not switching between edit and view mode?
