### ISSUE TITLE
Hide viewers on a page and the sidebar

### ISSUE THREAD

**Issue by cn42** [outline/outline#7364]
Currently it is not possible to hide viewers on a page and at the sidebar. 

**To Reproduce**
See the screenshot

**Expected behavior**
A setting per page or in general to hide the viewer at the pages

**Screenshots**
![Screenshot of one page as example](https://github.com/user-attachments/assets/3255ec19-03b3-40fc-abbf-826847263837)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.78.0

**Comment by tommoor** [comment]
Do you have manage role on the collection and edit permission on the document? With both of these permissions there is the option to hide viewers.

<img width="414" alt="image" src="https://github.com/user-attachments/assets/a8e6d348-b57a-4082-9714-ffc40a172a0b">

**Comment by cn42** [comment]
I found the button to disable the statistics, but I don't want to disable it. I just want to hide them on the pages or at least anonymize them in this view.

**Comment by tommoor** [comment]
Yes they are just hidden

**Comment by cn42** [comment]
Is it possible to turn it off by default for every page in the settings or do I need to do it every time I create a new page?

**Comment by tommoor** [comment]
> Is it possible to turn it off by default for every page 

Not currently, the idea here is that you might use it for individual sensitive pages. We'll consider for the future though, what is your usecase?

**Comment by riotbib** [comment]
Hi @tommoor, thanks for your awesome work on Outline,

sorry to bump this closed issue.

> Do you have manage role on the collection and edit permission on the document? With both of these permissions there is the option to hide viewers.

I cannot find this setting to hide the viewers. We are running v0.87.4.

Could you point me to the correct menu?

![Image](https://github.com/user-attachments/assets/922111bc-b8de-405b-87cc-bacfd585aa28)

Congratulations on v1.0.0 by the way!

**Comment by tommoor** [comment]
Hi, the option is available at the bottom of the document menu – "Enable viewer insights"

<img width="241" height="183" alt="Image" src="https://github.com/user-attachments/assets/521e3a76-ba11-4508-bc7c-0fa1d20ee657" />

**Comment by riotbib** [comment]
Thanks a lot, found the option.

Last question on this old issue: I could contribute a PR for disabling Viewer Insights per collection or even globally. Could start working on that in the first quarter of 2026.

If were to create an Issue for brainstorming that idea, would this feature something you would merge (if my PR holds up to your expectations)?

**Comment by tommoor** [comment]
It sounds acceptable, yes 👍🏻
