### ISSUE TITLE
Left hand side bar invisible

### ISSUE THREAD

**Issue by Benl0** [outline/outline#7372]
Loading up Outline, the collections, account info and settings buttons and drop down are invisible. The buttons are still there and I can interact with them but that's all. Opening a file, refreshing or clearing browser cache does resolve it.
I have tried this on Windows 11 PC with Firefox and Chrome, the windows app and on an Android phone using Firefox. Same behaviour across all. I have checked with other users in our workspace and they are fine. I believe they were using the web app on Windows 10.

If I do click into `getoutline.com/settings` the sidebar does reappear, unfortunately, clicking back to home page does not resolve this.
Also, I do have uBlock Origin installed on Firefox, but have disabled it for `getoutline.com` domains.

Also spotted this when grabbing more screenshots. If I click away from the desktop app, the sidebar does appear. No Idea why, but I can see that `<body>` tag gains the following property `class="backgrounded"`. I don't see any other tags update nor are there any messages in the console.

Could this simply be an issue with my account?

**To Reproduce**
1. Open Outline (sorry I'm really not doing anything else)

**Expected behavior**
Visible sidebar

---

**Screenshots**
_WebApp_
![Web app](https://github.com/user-attachments/assets/7a39fdc4-9b0f-4eb6-827c-5a52a70bc468)

_Desktop app_
![Desktop app](https://github.com/user-attachments/assets/163ebdcb-6868-4d8c-9cf5-c15be30e52d4)

**Outline (please complete the following information):**
- Install: `envypost.getoutline.com`
- Version: app 1.3.1

**Desktop (please complete the following information):**
 - OS: Win11 22H2 Build
 - Browser: Firefox | Chrome
 - Version: 129.0   | 127.0.6533.100

**Mobile (please complete the following information):**
 - Device: Pixel 4a 5G
 - OS: Android 14 (UP1A.231105.001.B2)
 - Browser: Firefox

**Comment by tommoor** [comment]
closed in [a54218d](https://github.com/outline/outline/commit/a54218d9ccb5969eb502a6fd0f5a049407e080f2) – thanks for reporting, deployment is going out now

**Comment by Benl0** [comment]
Thank you @tommoor. That's fixed it everywhere!
