### ISSUE TITLE
Inline comment button not available in floating editing toolbar after initial page load

### ISSUE THREAD

**Issue by almereyda** [outline/outline#7386]
When opening a page via its canonical URL, the comment button is not shown in the editing toolbar when selecting text right after initial page load.

**To Reproduce**
1. Open a page with its canonical URL pasted into the URL bar of a new tab
2. Select a piece of text
3. See the editing toolbar, but without commenting option

**Expected behavior**

The comment button shows right away.

**Workaround**

When Outline is loaded once in the tab, it's possible to navigate to another document and return. The comment button will show upon revisiting the entry page.

**Screenshots**

After initial page load:

![grafik](https://github.com/user-attachments/assets/21e5d187-7054-4481-8fbf-39b527f873c0)

After returning:

![grafik](https://github.com/user-attachments/assets/cb90d0c1-0488-4362-b018-4224c7ad9e9a)

**Outline:**
- Install: self hosted
- Version: v0.78.0

**Desktop (please complete the following information):**
 - OS: Fedora 40
 - Browser: Firefox
 - Version: 129.0

**Comment by tommoor** [comment]
I've not been able to reproduce this issue

**Comment by almereyda** [comment]
It seems to be related to Firefox Account Containers in combination with GitLab as IdP. When the link is pasted into a new tab and the domain is pinned to a certain container, it will be reopened in that, but not having the full security context available.

Login flows are frequently broken this way, as also seen with authenticated GitLab Pages.

Still reproduces consistently.

What to do, investigate out of curiosity, or close as won't fix, due to the involvement of a custom third-party?

**Comment by tommoor** [comment]
I don't know how these things you mention would affect the in-app UI to be honest, feel free to investigate – there could be some race condition here that's just not triggering for me perhaps but we cache the policies so if you have permission to comment it should be immediately available.

**Comment by almereyda** [comment]
Let me investigate some time and report back here.

Meanwhile I'm closing this, due to a known workaround and the small known user base that is affected (me).

Feel free to leave a comment if this happens some place else again and we can reopen.
