### ISSUE TITLE
Scrollable editor elements are unresponsive in latest Chrome

### ISSUE THREAD

**Issue by fan-wen** [outline/outline#7388]
**To Reproduce**
1. Create a new document and insert a table (in Chrome browser - this issue doesn't exist in Safari)
2. Add multiple columns until the last columns are hidden (**this issue only happens when the last columns are hidden**)
3. Scroll to the last columns and click any cell to edit
4. Cannot edit the content of those cells (when you click, it will jump to the beginning/first column on the left of the table)

**Expected behavior**
User should be able to edit the content in those cells

**Screenshots**
<img width="885" alt="image" src="https://github.com/user-attachments/assets/1c0e0ea3-e109-43c5-8f47-0880e16520f4">

**Outline (please complete the following information):**
- Install: the issue happens on both getoutline.com and my self-hosted instance
- Version: 0.78.0

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome **This issue is not happening in Safari though**
 - Version: 127.0.6533.100

**Comment by tommoor** [comment]
I've not been able to reproduce your report in Chrome 127, please make sure that other browser extensions are not affecting the edtior.

https://github.com/user-attachments/assets/20adca85-5283-47e8-8133-bcc51c6ea479

**Comment by fan-wen** [comment]
> I've not been able to reproduce your report in Chrome 127, please make sure that other browser extensions are not affecting the edtior.
> 
>  Screenity.video.-.Aug.14.2024.mp4

I just created a new Chrome profile and made sure no extension is on. It's still the same:
https://www.loom.com/share/359a61bfb68046588bbc5ced2ad87fb9?sid=24ec062f-fc4b-4ce1-9ad1-37a69d12c5a9

**Comment by tommoor** [comment]
It seems like Chromium 127 includes new code around scroll containers, I suspect it's incompatible somehow but as yet have still not reproduced to pinpoint it. This is likely also the same bug as https://github.com/outline/outline/issues/7378 

https://developer.chrome.com/blog/new-in-chrome-127?hl=en#keyboard-focusable-scroll-containers

**Comment by tommoor** [comment]
I have confirmed is is caused by the above change which is rolling out as part of 127. If you go to chrome://flags and set "Enables keyboard focusable scrollers" to disabled the issue no longer appears.

**Comment by fan-wen** [comment]
This is great! Since our team is also using this and it might be hard for everyone to find the flags & turn it off, any chance there's a quick fix from the code side? @tommoor

**Comment by tommoor** [comment]
No fix yet, found this thread which also seems related:

https://discuss.prosemirror.net/t/codeblock-with-white-space-pre-fails-to-set-selection-only-under-very-particular-circumstances/6422/7
