### ISSUE TITLE
Switching Language does not take effect

### ISSUE THREAD

**Issue by zevinto** [outline/outline#7398]
**To Reproduce**
1. Go to 'Preferences/Display'
2. Click on 'language'
3. You can see that the interface language has not changed.

**Expected behavior**
Global languages ​​can be translated normally

**Screenshots**

https://github.com/user-attachments/assets/10b1bbfb-89cc-4c34-9d97-8310b863af13

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.78.0

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.6.1
 - Browser: Chrome
 - Version 126.0.6478.183

**Comment by tommoor** [comment]
Take a look in the developer tools to see if the network requests to load the language files are failing, and if so how. 

Does it work after reloading the page

**Comment by zevinto** [comment]
@tommoor Currently tested in a local deployment: 
- The network request to load the language file fails with a 404.

https://github.com/user-attachments/assets/c075cdf2-9776-416b-8b2c-02dcc3233301


- After reloading the page and restarting, the language is still not loaded.

https://github.com/user-attachments/assets/02fec545-baf3-4f9d-87cf-7a9fa1df3ea9

**Comment by tommoor** [comment]
🤷 can't reproduce I'm afraid. What is the contents of the 404 response?

**Comment by zevinto** [comment]
All relevant responses are like this：
`{"ok":false,"error":"not_found","status":404,"message":"Resource not found"}`
At the same time, the problem is located in language.ts:47

https://github.com/user-attachments/assets/0a2e3d1f-ba78-458e-80c1-e63bd4a399e6

**Comment by tommoor** [comment]
`vite` should not be in the stack traces like this, it looks like you're running in development mode – is that on purpose?

**Comment by zevinto** [comment]
I ran it in Local Development mode without changing anything. The purpose is to see how the various functions of the project work. Is there any problem with this?
[Local Development](https://docs.getoutline.com/s/hosting/doc/local-development-5hEhFRXow7)

**Comment by tommoor** [comment]
Given it's development environment there are lot more variables in play, if it happens again add some debugging in this method to see what's going on…

https://github.com/outline/outline/blob/53cc2d8154bce8c917dbd949912a0874149e88c0/server/routes/index.ts#L97-L116
