### ISSUE TITLE
Children of archived document don't appear on the Archive page at once

### ISSUE THREAD

**Issue by apoorv-mishra** [outline/outline#7404]
Child doc appearing only after reload 👇 

https://github.com/user-attachments/assets/3ab9c8bf-dc61-4805-89a6-9a0870e3868c

**Comment by tommoor** [comment]
I was considering using [lifecycle hooks](https://github.com/outline/outline/pull/7407) for this, but perhaps even better would be to add an `onArchive` option to the `Relation` decorator, similar to `onDelete` that can define the behavior.
