### ISSUE TITLE
When switching languages, the floating menu's tab function does not show the table option.

### ISSUE THREAD

**Issue by DiamondYuan** [outline/outline#7410]
**To Reproduce**

To switch the interface language to Chinese:
1. Change the language setting to Chinese.
2. Open any document.
3. Type the "/" character.
4. Press the "tab" key.

**Expected behavior**

find table

**Screenshots**

<img width="446" alt="Screenshot 2024-08-19 at 13 20 36" src="https://github.com/user-attachments/assets/bd7f65d0-e8f1-4bf3-b650-a8d3d40367be">

**Outline (please complete the following information):**
- Install: [getoutline.com or self hosted]

self hosted

- Version: [commit sha if self hosted]
- 
0.78.0

**Desktop (please complete the following information):**

**Mobile (please complete the following information):**

**Comment by tommoor** [comment]
In my mind folks using Chinese language would not be searching in English, but happy to support both as best as possible.
