### ISSUE TITLE
Cursor not rendering in code block which scrolls horizontally

### ISSUE THREAD

**Issue by wasnertobias** [outline/outline#7412]
**To Reproduce**
1. Be in edit mode on any page
2. Create new code block
3. Insert any string long string into the new code block, e.g.,```verylong string in only one line, where is my cursor? even bigger to make it overflow on literally any screen, because this is when the bug actually seems to happen. At least with this right here it should be reproducible!```
4. Click on "Done" to save the page
5. Edit the page again
6. Click in the code block

**Expected behavior**
Cursor renders

**Outline:**
- Install: self-hosted
- Version: 0.78.0

**Desktop:**
 - OS: macOS 14.6.1
 - Browser Chrome
 - Version 127.0.6533.120

**Comment by wasnertobias** [comment]
We are using the enterprise version btw.

**Comment by wasnertobias** [comment]
Might relate to #7388

No release in the meantime, though.

**Comment by tommoor** [comment]
Yep, it's the same issue – there will be a release soon
