### ISSUE TITLE
Deleted docs aren't immediately reflected in Trash upon collection deletion

### ISSUE THREAD

**Issue by apoorv-mishra** [outline/outline#7413]
Steps:
1. Go to "Trash".
2. Reload once to ensure all collections are collapsed.
3. Delete one of the collections.

https://github.com/user-attachments/assets/4ad6aed7-6042-433e-ad1d-65f77756f2da

Related #7404

**Comment by tommoor** [comment]
@apoorv-mishra pushed the change above, while it doesn't fix the case where the documents are not already available locally I think that's acceptable behavior here.
