### ISSUE TITLE
changed E-Mail address in OIDC provider breaks login

### ISSUE THREAD

**Issue by akoyaxd** [outline/outline#7422]
**To Reproduce**
1. Login to outline via oidc
2. Change Mail address in IDP Provider
3. Logout of outline and try to login again

Changing the Mail address back fixes it again.
Tested Upstream IDP: Keycloak 25

**Expected behavior**
Login works and E-Mail of users gets updated in outline

**Screenshots**
![image](https://github.com/user-attachments/assets/cd3a3bb6-1db6-4f53-8cfd-c7ec6ee5690a)

**Outline (please complete the following information):**
- Install: self hosted
- Version: [v0.78.0](https://github.com/outline/outline/releases/tag/v0.78.0)

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version na
 -

**Comment by tommoor** [comment]
Outline will use the `id` value provided in the OIDC profile information  – if this is the same as the email address then this is unavoidable I'm afraid. You must make sure the `id` value provided to Outline is another unique ID.

Otherwise, the only alternative is to update the email in the database to match the new email under `user_authentications`

**Comment by akoyaxd** [comment]
Thanks for the quick answer. I'd kindly like to challenge that this is the issue.
Keycloak definitely provides an UUID as the ID for my user. I can see it also in the `user_authentications` table in the `providerId` attribute.

After some deeper look I guess the issue is related to the changed domain of my Mail address. Since it looks like Outline creates a provider for each Mail Domain that a users logs in to from OIDC. So my user belongs theoretically to a new provider while he is already existing in another one.

**Comment by tommoor** [comment]
Yes, that makes sense – unfortunately the current OIDC auth uses the domain from the logging in users email as the `providerId`, this was a poor decision but will be tricky to change – the domain of the OIDC server itself should have been used.
