### ISSUE TITLE
Smart quotes  should not be triggered in an inline code block

### ISSUE THREAD

**Issue by tommoor** [outline/outline#7449]
Smart quotes when in an inline code block:* "Type `a"b` and the " will turn into a unicode smart quote.

**Comment by ChuckJonas** [comment]
This still happens all the time to me.  I honestly wish I could just disable smart quotes as they are far more trouble than its worth, especially when the majority of our use is technical writing with code blocks.  

It seems like the better way to handle "smart quotes" would be to create them on render only.  Everything goes in as `"` during the render step, it can be decided based on context to use the fancy quotes or not...
