### ISSUE TITLE
Issues editing documents on iOS

### ISSUE THREAD

**Issue by amassis** [outline/outline#745]
Hey team Outline!

I am trying to edit a document using Safari on my iPad, but the canvas doesn’t seem too happy about it.
I noticed:
1) When iOS suggests me the next word, if I touch the word, the expected behavior would be for that word to replace whatever word I was typing. Example, I am typing “what” and the keyboard suggests “whatever”. If I touch the suggested word (“whatever” in the example) it should be accepted as a replacement for the word I was typing (“what” in the example). Actual result in Outline is just adding a blank space to the word being typed.

2) If I typed something wrong, I select it and type something else on top of it. Expected behavior is for that wrong word to be replaced by whatever I am typing. Actual behavior is that nothing happens, keyboard entry is not accepted when a word or phrase is selected (I believe it has something to do with the toolbar that pops up). In this case I am forced to use “delete” to erase all wrong letters/words before typing what I want.

3) The toolbar shows up behind iOS’s editing comands (screenshot)
![3ab0c2bf-8d7e-43d6-a680-f0c78024126a](https://user-images.githubusercontent.com/10330917/43844722-c2e49998-9b00-11e8-9be3-dd1cc0776b37.png)

I put these three behaviors together as they seem to be related to the interaction between the canvas, the keyboard and the “clipboard” (or whatever it is we call it these days 😀

Thanks
Alex

**Comment by tommoor** [comment]
Unfortunately it seems this may be an iOS issue, there is no way to hide the toolbar. https://bugs.webkit.org/show_bug.cgi?id=147406

We can keep this open to track it though

**Comment by amassis** [comment]
@tommoor I have also noticed that not only selecting text and typing over it doesn’t work, but using “undo” in iOS also doesn’t work.

**Comment by tommoor** [comment]
I'm combining this with https://github.com/outline/outline/issues/1027 – there are a lot of issues with soft keyboards in the current editor framework, centralizing the reports into one issue for now.
