### ISSUE TITLE
Unable to Start Outline After Seeding Admin Account: Repeated Migration Request

### ISSUE THREAD

**Issue by arnolem** [outline/outline#7479]
Impossible d'installer Outline avec uniquement l'authentification par lien. En utilisant le seed, l'application ne démarre plus et la base de données demande sans cesse une migration qui n'existe pas.

**To Reproduce**
1 - Install https://github.com/outline/outline/archive/refs/tags/v0.78.0.tar.gz
2 - Create an ENV without any authentication system
3 - Run the build: `yarn install --frozen-lockfile && yarn build`
4 - Create the database: `yarn sequelize db:create`
5 - Create the tables: `yarn sequelize db:migrate`

The command yarn start successfully starts the server.

Next, we need to create a Team and an initial User who will be an administrator. Since I don't have an authentication system, I thought of using the following command: `node build/server/scripts/seed.js arnaud@domain.tld`
(Let me know if there is a better solution for setting up email link authentication)

After running the seed, I do get a link that allows me to log in, but it is no longer possible to start the server.

`yarn start`
```
yarn run v1.22.22
$ node ./build/server/index.js
{"level":"warn","message":"\nThis version of Outline cannot start until a data migration is complete.\nBackup your database, run the database migrations and the following script:\n(Note: script run needed only when upgrading to any version between 0.54.0 and 0.61.1, including both)\n\n$ node ./build/server/scripts/20210226232041-migrate-authentication.js\n"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

`yarn sequelize db:migrate`
```
yarn run v1.22.22
$ /srv/www/vhosts/docs/node_modules/.bin/sequelize db:migrate

Sequelize CLI [Node: 20.17.0, CLI: 6.6.2, ORM: 6.37.3]

Loaded configuration file "server/config/database.json".
Using environment "production".
No migrations were executed, database schema was already up to date.
Done in 0.40s.
```

**Expected behavior**
I am looking for a solution to create an administrator account without setting up a third-party authentication provider.

**Screenshots**
![image](https://github.com/user-attachments/assets/8df002ac-bd2e-415a-8c4f-e50e30d6fb47)

**Outline :**
- Install: self hosted
- Version: fd1e14d1db0cb5a3f2f9013302be85b693d05731

**Comment by tommoor** [comment]
The script is for development, it is not designed to run in a production scenario. If you want to move forward you can skip over this migration by inserting the row in the `SequelizeMeta` table in the database matching the migration name – you should see the pattern from all the other successful ones that will be in there already.

**Comment by arnolem** [comment]
Thank you for your response.

> The script is for development, it is not designed to run in a production scenario.

How can I create a user with "Magic Link" authentication only if the seed command is not the correct method?

> If you want to move forward you can skip over this migration by inserting the row in the `SequelizeMeta` table in the database matching the migration name – you should see the pattern from all the other successful ones that will be in there already.

I tried applying this migration to the database, but I don't think that is the issue.
![image](https://github.com/user-attachments/assets/9444f7b3-4856-4951-a943-6ba27b953460)

Despite adding the migration, the problem persists, and the application is still unable to start.
![image](https://github.com/user-attachments/assets/e1bf7e12-e324-4bca-aafd-440fdad8b25a)

I’m not sure how to proceed from here.

**Comment by saranchyev** [comment]
I just encountered this problem myself. Adding migration to the `SequelizeMeta` table does not help. You need to add `return` to the `server/utils/startup.ts` file, at the very beginning of the `checkDataMigrations` function. Then restart the project build and run it again.
![image](https://github.com/user-attachments/assets/47beddc0-e52d-4528-830d-7eeb09571a01)

**Comment by tommoor** [comment]
I believe the logic could be tweaked to check if the team was created before 2024 and otherwise continue.

**Comment by arnolem** [comment]
Indeed, the problem is exactly as you mentioned.

Here is a script that bypasses the incorrect verification:

```
sed -i 's/export async function checkDataMigrations() {/export async function checkDataMigrations() { return;/g' server/utils/startup.ts
```
