### ISSUE TITLE
Google OIDC without GApps

### ISSUE THREAD

**Issue by cxcv** [outline/outline#748]
Currently, the Google OpenID Connect implementation checks for a Google Apps "Hosted Domain" claim, it would be great to relax this so that normal users can authenticate (at least for hacking).

**Comment by tommoor** [comment]
I think it would make sense to move this requirement to an environment variable similar to `GOOGLE_ALLOWED_DOMAINS` [here](https://github.com/outline/outline/blob/master/.env.sample#L25).

Perhaps `GOOGLE_HD_REQUIRED`

**Comment by cxcv** [comment]
Yes, I'll update the pr

**Comment by tommoor** [comment]
closing as stale
