### ISSUE TITLE
Incorrect text in deleted banner when passed expiry

### ISSUE THREAD

**Issue by tommoor** [outline/outline#7485]
In the space between a document in the trash expiring and the cron job running it looks like this. Ideally would say "deleted today" perhaps?

<img width="882" alt="image" src="https://github.com/user-attachments/assets/e3bd5f37-8330-44c1-9f6e-64395ee4792a">

**Comment by Its-kushal** [comment]
Hi @tommoor,

I noticed the issue with the negative days displayed in the deleted banner text. I would like to work on fixing this by updating the logic to properly handle the date display when a document is in the space between expiring and being permanently deleted by the cron job.

My proposed approach is to:

    - Identify and update the condition that calculates the remaining days until permanent deletion.
    - Ensure that if the calculated value is less than or equal to zero, the banner will display "deleted today" instead of showing a negative day count.

Please let me know if this approach sounds good or if there are any additional considerations you’d like me to keep in mind. I’m looking forward to contributing to this project!

Thanks, Kushal
