### ISSUE TITLE
Code under numbered list is split up into lines instead of maintaining one code block

### ISSUE THREAD

**Issue by kbkozlev** [outline/outline#7493]
When having a code block under a numbered list, when pressing enter, instead of creating a new line in the code block, a whole new code block is created.

**To Reproduce**
1. create a file 
2. create a numbered list 
3. under the numbered list, create a code block with /code
4. press shift + enter

**Expected behavior**
This should create a new line in the code block 

**Screenshots**

https://github.com/user-attachments/assets/9315f1eb-bffc-4294-ab7e-f476dc485485

**Outline (please complete the following information):**
- Install: self hosted
- Version: v.0.78.0

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome

**Comment by tommoor** [comment]
Thanks for the clear video, seems simple enough

**Comment by tommoor** [comment]
I'm actually unable to recreate, it may be this was already fixed on `main`.

**Comment by tommoor** [comment]
Ah yes, fixed here https://github.com/outline/outline/issues/7363

**Comment by kbkozlev** [comment]
I'm running outline inside of docker and it should be the latest version. Is this fix pushed onto the last version?

**Comment by tommoor** [comment]
There has not been a release since the bug was fixed, it will be in the next

**Comment by kbkozlev** [comment]
Ahh, Ok. Thank you for you amazing work!
