### ISSUE TITLE
Difficulty in creating Code block

### ISSUE THREAD

**Issue by amassis** [outline/outline#750]
When I started using Getoutline I would create a code block nad it would look like this:
<img width="765" alt="screen shot 2018-08-10 at 19 15 58" src="https://user-images.githubusercontent.com/10330917/43983656-3f0dacbc-9cd2-11e8-9975-0a72dddf2210.png">

Now I can't replicate that behavior, when I try a code block this is what I get:
<img width="383" alt="screen shot 2018-08-10 at 19 16 37" src="https://user-images.githubusercontent.com/10330917/43983670-5040f124-9cd2-11e8-97ee-4ac476fd5572.png">

Is that a bug or am I doing something wrong?
Thanks
Alex

**Comment by tommoor** [comment]
Outline supports both inline and block code formatting, this creates inline code:

![image](https://user-images.githubusercontent.com/380914/43984184-e54ae064-9cb3-11e8-9335-8fdbf1669482.png)

This is the block menu and creates code blocks:

![image](https://user-images.githubusercontent.com/380914/43984202-f4e39822-9cb3-11e8-8716-4fea222e9b9c.png)

You can also use the Markdown shortcut ```

**Comment by amassis** [comment]
Hey Tom, how can I see the block menu? I only see the inline one when I select text...
Thanks


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
