### ISSUE TITLE
Mac OS app not working and showing a white screen

### ISSUE THREAD

**Issue by moicalcob** [outline/outline#7510]
**To Reproduce**
1. Install Outline destkop app version 1.3.1 in a Mac using an Apple Silicon processor.
2. Open the app

**Expected behavior**
I should be able to access my Outline docs.

**Screenshots**
<img width="1432" alt="Screenshot 2024-09-02 at 09 42 57" src="https://github.com/user-attachments/assets/2fda6788-0f85-42e4-8a46-5298b5a8d015">

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by moicalcob** [comment]
Hey @tommoor I could replicate the issue every time I open the app. It's was not working at all until I clicked on `Clear application data` 🤔 

<img width="297" alt="Screenshot 2024-09-03 at 10 31 19" src="https://github.com/user-attachments/assets/5bbe84a1-f880-44e2-959b-e97acbd8a731">

It's working fine now so unfortunately I can't provide much more info, but it's been broken for a few days

**Comment by tommoor** [comment]
Ah that's unfortunate, if it happens again we can open developer tools and see what is breaking. In the meantime I'm going to close this out as the Mac app isn't developed in this repo. Please email hello@getoutline.com if it occurs again
