### ISSUE TITLE
Video scrolling problem

### ISSUE THREAD

**Issue by matziu** [outline/outline#7517]
Docker-compose
nginx proxy manager
ssl / le
outline 0.78.0
video file upload via /wideo *.mp4 and *.mov (iphone).

cant use progress bar in video player, I can only play from beggining.
browser: chrome, edge

https://github.com/user-attachments/assets/226a0c61-a6d5-4ebc-bcf0-7b489d9711d5

**Comment by tommoor** [comment]
I've been unable to reproduce so far, this reproduces in Chrome + Edge – correct?

**Comment by matziu** [comment]
Yes, I tested firefox too and works well.

https://github.com/user-attachments/assets/efeeb840-0575-4b9b-a9a4-44f626edf672

**Comment by matziu** [comment]
sample video with problem:

https://github.com/user-attachments/assets/d273d27c-7bed-4831-bd98-e43488242416

**Comment by matziu** [comment]
I test it multiple ways always have the same problem.
I share You test page: https://wiki.dbgcloud.pl/s/da6025a8-f0d9-481b-bfe9-6f9cde313792

**Comment by tommoor** [comment]
Please update to the latest version ([v0.80.2](https://github.com/outline/outline/releases/tag/v0.80.2)) and see if it continues, I can reproduce on your shared link but not on cloud or local versions.

**Comment by matziu** [comment]
I update version to latest stable and have same weird problem.
Can you help me commercially with this problem?

**Comment by tommoor** [comment]
Commercially?

**Comment by tommoor** [comment]
Ah, the problem is that I cannot reproduce the issue yet so I can't fix it without being able to create the bug in the development environment.

**Comment by matziu** [comment]
I can run another instance without any data and give You all access. I use docker-compose so istn complicated.
