### ISSUE TITLE
Collection Manager can create template, but cannot managing template

### ISSUE THREAD

**Issue by seong889** [outline/outline#7521]
Collection Manager can create template by collection's menu.
![image](https://github.com/user-attachments/assets/0181834b-1bc6-499d-9a89-322a2f9df7a9)

However, Collection Manager who is not an Admin cannot edit or delete templates because there is no screen available to view the list of templates.

![image](https://github.com/user-attachments/assets/9d7fa09c-4a5f-40b4-862c-40d5dc7ab943)
- Settings page on collection manager(not admin)

Additionally, a user with Admin privileges cannot view the entire list of templates on the server.

So, No one can manage the templates created by the Collection Manager.

### Version
 
![image](https://github.com/user-attachments/assets/b1b6711d-7072-4136-a391-405d1fbacb0a)

**Comment by tommoor** [comment]
Fixed in `v0.79.0`
