### ISSUE TITLE
Resize sidebar

### ISSUE THREAD

**Issue by tommoor** [outline/outline#753]
It would be nice to have the ability to collapse the sidebar into a compact view. @maxvoltar dunno if you fancy helping out? 😉

**Comment by maxvoltar** [comment]
On it.

**Comment by maxvoltar** [comment]
https://share.goabstract.com/711b7bc8-c02e-46aa-99ae-00e8d4b0c5ab

**Comment by tommoor** [comment]
For those without Abstract access:

![image](https://user-images.githubusercontent.com/380914/44044660-24a08074-9edb-11e8-89bb-fc19190a3271.png)

**Comment by MarceloCajueiro** [comment]
Awesome.

**Comment by shankscoder** [comment]
Any progress on this? On smaller screens especially when you're at the larger breakpoints, the sidebar occupies a large portion of the screen and detracts from readability. 

Would be good if the ability to manually toggle the sidebar exists even in larger screen breakpoints.

**Comment by MatheusRV** [comment]
The ability to resize sidebar as you want and save the size in browser db it's a pretty fancy feature.

**Comment by MatheusRV** [comment]
Could someone rename this task to "Ability to collapse & resize sidebar "

**Comment by guilherme-diniz** [comment]
I'm going to implement this. Can i use some package to do it, like the one implemented for bootstrap ?

**Comment by tommoor** [comment]
Open to a package for the resizing but it must add minimal size to bundle, please post here and we can discuss before adding?

In terms of the designs above they're pretty out of date now, I'd probably go for something a bit simpler where the sidebar is resizable within bounds and if you go below a certain point it collapses to a ~16px strip down the left side of the screen, hovering that strip shows the entire sidebar.

**Comment by guilherme-diniz** [comment]
I was thinking in using this one https://split.js.org/

**Comment by MatheusRV** [comment]
Visual Hover Draggable Area and Collapse Button ![image](https://user-images.githubusercontent.com/23284276/91918365-11bd6e00-ec99-11ea-9b10-4563d210b44e.png)

Minimal Menu
![image](https://user-images.githubusercontent.com/23284276/91918433-3c0f2b80-ec99-11ea-92b0-4c8af65c37b4.png)
