### ISSUE TITLE
Email magic link redirect to 443 ports

### ISSUE THREAD

**Issue by AngelPone** [outline/outline#7539]
I have to serve the outline app on a non-standard https ports, in my case, which is 2443.
I successfully setup login with email magic link.
The magic link itself is https://mydomain.com:2443/auth/email.callback?token=token&client=web.
After I clicked the link and it automatically redirect to https://mydomain.com/auth/email.callback?token=token&client=web&follow=true, which I think is a bug.

**To Reproduce**
1. self-host outline with environment variables below
```
URL=https://mydomain.com:2443
PORT=3000
```
3. setup reverse proxy with nginx configuration below

```
server {
    listen 2443 ssl;

    http2 on;

    server_name mydomain.com;

    ssl_certificate /etc/letsencrypt/live/npm-1/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/npm-1/privkey.pem;

    ssl_session_cache shared:SSL:1m;
    ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256;
    ssl_prefer_server_ciphers on;

    ssl_dhparam /etc/nginx/ssl/dhparam.pem;

    location / {

        proxy_pass http://172.17.0.1:3000/;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;proxy_set_header Host $host;
	   proxy_set_header Host $http_host;
	   proxy_set_header X-Real-IP $remote_addr;
	   proxy_set_header X-Scheme $scheme;
	   proxy_set_header X-Forwarded-Proto $scheme;
	   proxy_redirect off;
    }

}
```

5. Send email magic link to a user
6. See error

**Expected behavior**
Should not redirect to 443 port

**Outline (please complete the following information):**
- Install: self hosted
- Version: ce85b8f94dd9c390b1e4667f564dc805d13271f2

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 0.79.0

**Comment by tommoor** [comment]
Not really sure how this happens but the redirect code is here if anyone wants to look at it 

https://github.com/outline/outline/blob/ce85b8f94dd9c390b1e4667f564dc805d13271f2/plugins/email/server/auth/email.ts#L100

**Comment by tommoor** [comment]
Closing for now as this is not a bug in Outline but a problem with your nginx configuration not passing the port forward in the host header it appears.

**Comment by shendongyuxmxm** [comment]
> Closing for now as this is not a bug in Outline but a problem with your nginx configuration not passing the port forward in the host header it appears. 

hi, I encountered the same issue. Could you please tell me how to configure it? Thx. My Nginx configuration is as follows:


 server {
        listen       30080;
        server_name  wiki.xxx.net;

        location / {
                proxy_pass http://127.0.0.1:3600/;

                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;

                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;proxy_set_header Host $host;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                #proxy_set_header X-Scheme $scheme;
                proxy_set_header X-Scheme http;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_redirect off;
                }
       }

**Comment by AngelPone** [comment]
@shendongyuxmxm  This is my configuration.

```
    location / {

        proxy_pass http://172.17.0.1:3000/;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Host $host;
	proxy_set_header X-Forwarded-Host $http_host;
	proxy_set_header Host $Host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Scheme $scheme;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_redirect off;
	proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
```

**Comment by seesea2024** [comment]
```
	proxy_set_header Host $host;
	proxy_set_header X-Forwarded-Host $http_host;
```
$http_host keeps port but $host not. It looks X-Forwarded-Host has higher priority than Host, that is why the previous conf works.

It is highly recommended to use conf below:
```
	proxy_set_header Host $http_host;
	proxy_set_header X-Forwarded-Host $http_host;
```
