### ISSUE TITLE
comment icon shows on print

### ISSUE THREAD

**Issue by Gd-Hao** [outline/outline#7545]
**To Reproduce**
1. Go to any doc longer than one page
2. Click on print
3. See comment icon on preview of print page.

**Expected behavior**

**Screenshots**
![print_ver](https://github.com/user-attachments/assets/e641d922-9a12-4f4c-a108-198a7811a7af)
![webpage](https://github.com/user-attachments/assets/e3d6dbf6-5645-4ab9-bc89-7740a2a1b2d8)

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.78.0 33086a16cea195e2e3e6c53fcaa105ad4513ddc7ca1c4e92517fdea4b2040fbe

**Desktop (please complete the following information):**
 - OS: win11
 - Browser Edge
 - Version 128.0.2739.42

**Comment by tommoor** [comment]
Addressed in `v0.79.0`
