### ISSUE TITLE
Update from 0.78.0 migration error

### ISSUE THREAD

**Issue by jesili** [outline/outline#7546]
**To Reproduce**
1. Update outline using the docker compose
```
{"label":"database","level":"info","message":"Migrating 20240625051656-remove-emoji-column.js…"}
{"label":"database","level":"info","message":"Migrated 20240625051656-remove-emoji-column.js in 0.143s"}
{"label":"database","level":"info","message":"Migrating 20240806080954-group-users-paranoid.js…"}
{"label":"database","level":"info","message":"Migrated 20240806080954-group-users-paranoid.js in 0.023s"}
{"label":"database","level":"info","message":"Migrating 20240810080954-group-users-remove-deleted-at.js…"}
{"level":"warn","message":"Migration 20240810080954-group-users-remove-deleted-at.js (up) failed: Original error: Validation error"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
...
{"level":"warn","message":"Migration 20240810080954-group-users-remove-deleted-at.js (up) failed: Original error: column \"deletedAt\" of relation \"group_users\" does not exist"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Outline (please complete the following information):**
- Install: [self hosted]
- Version: [0.78.0]

**Comment by michellaurent** [comment]
I have the same issue when migrating from 0.78.0 to 0.79.0

**Comment by tommoor** [comment]
Did migrations fail part way through and you ran them twice?

This error doesn't make any sense as the migration milliseconds before `20240806080954-group-users-paranoid.js` queries the column that it's complaining doesn't exist :/

**Comment by jesili** [comment]
> Did migrations fail part way through and you ran them twice?
> 
> This error doesn't make any sense as the migration milliseconds before (`20240806080954-group-users-paranoid.js`) in your logs queries the `deletedAt` column that it's complaining doesn't exist :/

I use the docker compose to run the application, and i put the command ` command: sh -c "yarn start --env=production-ssl-disabled"` in the docker.yaml directly. So when it hits the error, it keeps restarting. This is the reason that the log shows multiple same error.

**Comment by jesili** [comment]
I also tried to add the column "deletedAt" manually into the database, but is doesn't work. The migration does remove that column, but still occurs the error. I have rollback to 0.78.0, it works fine now.

**Comment by tommoor** [comment]
I see now the first error is a `Validation error` and then the subsequent try fails because the migration is already half applied. Unfortunately unclear what the `validation error` refers to exactly.

**Comment by jesili** [comment]
> I see now the first error is a `Validation error` and then the subsequent try fails because the migration is already half applied. Unfortunately unclear what the `validation error` refers to exactly.

Hi, I have tried the new version 0.79.1, this time it does not appear the `Validation error` but still has `column \"deletedAt\" of relation \"group_users\" does not exist"` error.

**Comment by chi-yuer** [comment]
> > I see now the first error is a `Validation error` and then the subsequent try fails because the migration is already half applied. Unfortunately unclear what the `validation error` refers to exactly.
> 
> Hi, I have tried the new version 0.79.1, this time it does not appear the `Validation error` but still has `column \"deletedAt\" of relation \"group_users\" does not exist"` error. To reproduce:
> 
> 1. run `docker compose -f outline.yaml down`
> 2. modify the outline.yaml to latest version
> 3. run `docker compose -f outline.yaml up -d`
> 4. run docker logs
> 
> ```
> yarn run v1.22.22
> $ node ./build/server/index.js --env=production-ssl-disabled
> The environment variable AWS_S3_UPLOAD_MAX_SIZE is deprecated and will be removed in a future release. Use FILE_STORAGE_UPLOAD_MAX_SIZE instead
> {"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
> {"label":"database","level":"info","message":"Running migrations…"}
> {"label":"database","level":"info","message":"Migrating 20240810080954-group-users-remove-deleted-at.js…"}
> {"level":"warn","message":"Migration 20240810080954-group-users-remove-deleted-at.js (up) failed: Original error: column \"deletedAt\" of relation \"group_users\" does not exist"}
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

For temporary solution, you can try comment this line of code:

```javascript
// server/migrations/20240810080954-group-users-remove-deleted-at.js
// line 6

await queryInterface.removeColumn('group_users', 'deletedAt');
```

**Comment by tommoor** [comment]
@jesili this is expected now given you're in a state where the migration was half-applied, you can do as @chi-yuer mentioned or easier would be to add the column manually so that the migration can remove it. Any `deletedAt` column on group_user will do.

**Comment by jesili** [comment]
> @jesili this is expected now given you're in a state where the migration was half-applied, you can do as @chi-yuer mentioned or easier would be to add the column manually so that the migration can remove it. Any `deletedAt` column on group_user will do.

Thank you, it works after i add the column manually.

**Comment by MPeli** [comment]
I added `deletedAt` manually. Then I got a validation error.

```
The environment variable AWS_S3_UPLOAD_MAX_SIZE is deprecated and will be removed in a future release. Use FILE_STORAGE_UPLOAD_MAX_SIZE 
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"label":"database","level":"info","message":"Running migrations…"}
{"label":"database","level":"info","message":"Migrating 20240810080954-group-users-remove-deleted-at.js…"}
{"level":"warn","message":"Migration 20240810080954-group-users-remove-deleted-at.js (up) failed: Original error: Validation error"}
error Command failed with exit code 1.

**Comment by MPeli** [comment]
This helped

```sql
SELECT * FROM "SequelizeMeta" WHERE name LIKE '%group-users-remove-deleted-at%';
```

If this shows no results, we can add the migration record:

```sql
INSERT INTO "SequelizeMeta" (name) 
VALUES ('20240810080954-group-users-remove-deleted-at.js');
```
