### ISSUE TITLE
Microsoft Teams Authentication

### ISSUE THREAD

**Issue by ambroselittle** [outline/outline#755]
My org is looking to move off of Slack and onto other platforms, and from Google to Microsoft. 

So, while I think this solution is super slick, I'm curious how much trouble it would be--if we did the modifications in a fork--to remove those dependencies (and possibly swap in a Teams integration). 

We'd like to host internally, so auth is less of a concern for us, FWIW.

Thanks in advance.

**Comment by jhult** [comment]
I would also be interested in authenticating with Microsoft (specifically Teams/Office 365).

**Comment by snovak7** [comment]
I have done part with Azure AD integration, I will make PR soon.

**Comment by tommoor** [comment]
Hello everyone, Microsoft sign-in has now been completed and is available on the cloud hosted version of Outline, here:
https://app.getoutline.com/create

For self-hosted it will be included in the next release `v0.55.0` which is currently estimated to be within the week.
