### ISSUE TITLE
The user who is inviting shouldn't appear in the invite list

### ISSUE THREAD

**Issue by apoorv-mishra** [outline/outline#7559]
If I can't invite myself, I shouldn't appear in the invite list in the first place.
<img width="441" alt="Screenshot 2024-09-09 at 12 28 45 PM" src="https://github.com/user-attachments/assets/6717260c-f9fd-41dd-9ce1-6901e40bdb63">

<img width="709" alt="Screenshot 2024-09-09 at 12 52 31 PM" src="https://github.com/user-attachments/assets/ecf4225a-19b8-48db-84d1-8a1007dd08a8">

**Comment by tommoor** [comment]
closed by 0c080038d7ade724adb9cf684c8f9372a6c48ad1
