### ISSUE TITLE
Incorrect PATH configuration fails in modified shell environment

### ISSUE THREAD

**Issue by egetin** [outline/outline#756]
[PATH modification in docker-compose.yml](https://github.com/outline/outline/blob/master/docker-compose.yml#L39) file breaks environment, when PATH is modified on local environment and contains custom folders that don't exist in the node image. Following link explains why:
https://docs.docker.com/compose/compose-file/#variable-substitution

Following or similar will happen with custom local PATH:

> /usr/local/bin/yarn: 2: /usr/local/bin/yarn: sed: not found
> /usr/local/bin/yarn: 3: /usr/local/bin/yarn: readlink: not found
> /usr/local/bin/yarn: 5: /usr/local/bin/yarn: uname: not found
> module.js:549
>     throw err;
>     ^
> 
> Error: Cannot find module '/opt/outline/yarn.js'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Function.Module.runMain (module.js:693:10)
>     at startup (bootstrap_node.js:191:16)
>     at bootstrap_node.js:612:3

I suggest that PATH should be defined in Dockerfile and not in docker-compose.yml file. It's not being modified constantly and it doesn't require additional content from local environment. It will also fix this problem :)

**Comment by tommoor** [comment]
Sounds reasonable, would accept a patch for this

**Comment by tommoor** [comment]
closed by 059cccd36f6d4d4c53e441ed3853b86293445aee
