### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'target') when typing Korean characters.

### ISSUE THREAD

**Issue by MinjeJeon** [outline/outline#7574]
I'm encountering a JavaScript error when inputting Korean characters into a text field on Outline. This consistently causes the last character on each line to disappear.

**To Reproduce**
1. Create a new document
2. Begin typing the Korean character 'ㄱ' into the document.
3. The specified error message appears in the console
(content.js:9 Uncaught TypeError: Cannot read properties of undefined (reading 'target')  at content.js:9:514800)

**Screenshots**
![ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/68fd208a-5c1b-42cf-b0db-d1c324b5497e)

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 0.79.1

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome 128, Edge 128

**Comment by MinjeJeon** [comment]
I tried it on a different computer today, and it seems to be working fine. It might be an IME or OS issue, so I'll check it again tomorrow.

**Comment by tommoor** [comment]
Potentially a browser extension too

**Comment by MinjeJeon** [comment]
I've checked the issue tracker on Prosemirror. It seems like an upstream issue, so I'll close this issue.

https://github.com/ProseMirror/prosemirror/issues/1484

**Comment by tommoor** [comment]
We still need to pull in the fix then
