### ISSUE TITLE
Not all document editors listed as contributors

### ISSUE THREAD

**Issue by oakbrad** [outline/outline#7613]
When viewing a document with multiple editors, only the creator is shown as a "contributor" and in the facepile

**To Reproduce**
1. Go to a document with multiple editors, see their edits in the document history
2. View insights, only the creator and not the editors are listed
3. Over the API, the `document.collaboratorIds` only includes the creator's UUID

**Expected behavior**
I would expect everyone who has edited the document to be listed as a contributor/collaborator. Some documents do list all the editors, but I have many that don't even though I can see their edits in the document's history. 

It's not clear to me why some edits get users listed as contributors and some don't.

**Screenshots**
This document has 3 editors, but only the creator listed as a contributor:
![Screenshot 2024-09-16 at 17 38 30](https://github.com/user-attachments/assets/5d7e95ad-2d2b-4685-b559-b8d51197f2fb)

![Screenshot 2024-09-16 at 17 39 24](https://github.com/user-attachments/assets/7e5bc0e6-833b-496c-80ba-bd1559decb68)

When I request this document from `documents.info` I similarly only see the creator's UUID in the array of collaborators.

**Outline (please complete the following information):**
- Install: self hosted, docker
- Version: 0.79.1

**Desktop (please complete the following information):**
 - OS: Nac
 - Browser Firefox

**Comment by tommoor** [comment]
What type of edits are those that are unlisted in collaborators?

**Comment by oakbrad** [comment]
Both edits added a few sentences to the text of the document, fixed some typos.

The only pattern I can see is when my account (admin) makes an edit to a user document, I show up as a contributor and in the facepile. When users edit a document I create, they do not, but I see their edits in the history.

**Comment by tommoor** [comment]
Okay, one more question – If you go to the revision history and then back to insights do the users appear then?

**Comment by oakbrad** [comment]
They do not

**Comment by tommoor** [comment]
I guess you should check the response for `documents.info` and see if there are multiple ids in the `collaboratorIds` property or not.

**Comment by oakbrad** [comment]
Originally that's what I was doing, I thought I was doing something wrong in my app but then noticed that Outline shows it incorrectly as well when I compared History to Insights.

When I get the above document with `documents.info`, the `collaboratorIds` has a single UUID which corresponds to the creator that's listed on Insights page. For that document, I would expect the array to contain 3 (the creator and two editors associated with the revisions). The editors are not included in either the API response or the Outline Insights page.

**Comment by tommoor** [comment]
@oakbrad in what sense? Unfortunately where the editors where not recorded that data cannot be fixed, however it should be correct going forward
