### ISSUE TITLE
URL encoding for remote assets with special chars in filename

### ISSUE THREAD

**Issue by thehuze** [outline/outline#7625]
If you upload file with name that contains special chars like "+' and you setup storing of these files in S3, then you'll receive error trying accessing them.

**To Reproduce**
1. Setup storing images in S3
2. Paste in any document any file with name like "+.jpg"
3. Your file is uploaded to S3
4. Open your document and meet HTTP 403 trying to access this file (in case with AWS S3)

**Expected behavior**
Outline should encode special symbols to Hexadecimal format before trying to access files from remote storage.
https://documentation.n-able.com/N-central/userguide/Content/Further_Reading/API_Level_Integration/API_Integration_URLEncoding.html

**Outline (please complete the following information):**
- Install: self-hosted
- Version: tag 0.78.0

**Desktop (please complete the following information):**
 - OS: Linux / Fedora
 - Browser Chrome 
 - Version 128.0.6613.113 (Official Build) (64-bit)

**Comment by tommoor** [comment]
I'm not able to reproduce, files with "+" in the name work correctly here. Are you actually using AWS S3 or some "compatible" equivalent?

**Comment by thehuze** [comment]
Yes, I use AWS S3.

I tried to reproduce it, it turns out that the bug does not reproduce with files in the document. It seems that the error occurs when trying to get a user's avatar with special chars in filename.

I see attempts in the developer console to GET requests to https://prod-files-secure.s3.us-west-2.amazonaws.com/9ea2d2ee-9197-49bb-9cea-11a0a38ccec2/bb45f623-7143-42f1-b643-cd76fedb0581/image.png with response HTTP 403
I do not know why these requests are made there because there is no prod-files-secure bucket in my configuration. Is it something embedded in the Outline?

**Comment by tommoor** [comment]
> there is no prod-files-secure bucket in my configuration. Is it something embedded in the Outline?

No, this is in your config somewhere.
