### ISSUE TITLE
Custom home pages

### ISSUE THREAD

**Issue by MarceloCajueiro** [outline/outline#763]
Hello guys,

Would be great to have custom home pages for the dashboard and for each collection.

Something like this:

![image](https://user-images.githubusercontent.com/26076/44728936-020c5d00-aab4-11e8-9b7c-b1b27dd07af5.png)

What do you thing about?

Other thing we have plans to add in this kind of home page are metrics embedding charts from [metabase](https://github.com/metabase/metabase). Since each collection represents an area in the company we are planning make public the goals and KPIs and we thought outline as a google place for that.

**Comment by treasuretron** [comment]
+1 would love this, having our wiki load straight to Recently viewed is not as welcoming as a custom page with the most important (instead of most recent) links. Thanks!

**Comment by tommoor** [comment]
As an admin it's now possible to "pin" documents to the home screen.

**Comment by treasuretron** [comment]
thanks @tommoor I now see that! Sorry to necropost!! We just need to upgrade :)
