### ISSUE TITLE
0.80.0 - Docker - Version mismatch

### ISSUE THREAD

**Issue by gu1ll0me** [outline/outline#7635]
Using Docker image tag `0.80.0` displays version 0.79.1 in the Preferences menu.

- Install: self hosted
- Version: 0.80.0

**Comment by b-d-e** [comment]
+1 to this, was just about to make an issue for the same thing
<img width="139" alt="image" src="https://github.com/user-attachments/assets/b5f15b63-a8ca-45a3-afef-3c5419f78852">
<img width="473" alt="image" src="https://github.com/user-attachments/assets/34929d3a-602a-466b-b38f-32d176e66ab5">
