### ISSUE TITLE
Add visual feedback when uploading team logo

### ISSUE THREAD

**Issue by coleylogan** [outline/outline#764]
👋Hi team! 

I was perusing Outline and found there is no visual feedback that a photo is uploading for the team logo. 

I uploaded two photos of similar size and the upload time varied. The first time it took longer and I admit I rage clicked. The inconsistency in the upload time wouldn't be a biggie if there were visual feedback that the upload was happening. 

**Steps I took**
1. Settings
2. Details
3. Logo > Upload
4. Select a photo from iCloud
5. Zoom to crop
6. Click Crop Logo

<img width="1775" alt="screen shot 2018-08-28 at 6 09 58 pm" src="https://user-images.githubusercontent.com/520681/44759365-998ea180-aaee-11e8-973a-19ed94d5cced.png">

**Comment by tommoor** [comment]
Thanks for filing @coleylogan 😄
