### ISSUE TITLE
Home permanently redirects to login redirect

### ISSUE THREAD

**Issue by gabschne** [outline/outline#7655]
_**Meta:** I am writing this issue in the middle of a short break, so sorry for the quick and dirty style. I'll come back later and might rewrite some parts or answer any questions if needed._

It seems like home redirects permanently to the redirect URL of login.

Only OIDC is active as a login provider.

**To Reproduce**
1. Copy any URL with path other than `/home`.
2. Logout and clear all site data of the wiki.
3. Reopen the previously copied URL.
4. Log in.
5. You'll be redirected (at this point correctly) to the path.
6. Click on "Home" or open `/home` or the base URL (even works in a new tab). You'll be redirected to the path of the login redirect URL every time.

 Fun fact: Deleting the `lastVisitedPath` key-value in the local storage fixes the issue for **NEW** tabs, but not the initial one. 

**Expected behavior**
Open the home page on click of "Home" or when navigating to `/home` or the base URL.

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 0.80.1 (container image) (I'm quite sure this wasn't an issue before the update from 0.79.1).

**Comment by tommoor** [comment]
Interesting, did you see what the value of `lastVisitedPath` is in this case?
