### ISSUE TITLE
Visibility status of sidebar cannot be toggled when logged in

### ISSUE THREAD

**Issue by almereyda** [outline/outline#7660]
When opening a share link when being logged in, it adapts the sidebar toggle status from the editing interface, yet cannot be toggled. The button doesn't exist. This way I'm potentially stuck to the sidebar being hidden, unaware of eventual subdocuments.

**To Reproduce**

1. Create and publish a document
2. Create a share link for the document
3. Open the share link in the same browser session
4. Find the sidebar share the toggle state from the editor, but not offer a toggle button.

**Expected behavior**

Either the sidebar for shares with sub-documents is always visible (preferred), or it is possible to toggle the stickiness of the sidebar.

**Screenshots**

Editor / sidebar folded:

![grafik](https://github.com/user-attachments/assets/8c34b583-333e-47c7-a0aa-f1c6892ac362)

Viewer / sidebar folded:

![grafik](https://github.com/user-attachments/assets/940e200e-effd-4318-be83-6dd46b0118ca)

Editor / sidebar unfolded:

![grafik](https://github.com/user-attachments/assets/6c21965c-c36e-4b30-96e4-f7a2f661931f)

Viewer / sidebar unfolded:

![grafik](https://github.com/user-attachments/assets/d1251478-6d7b-483d-af32-e2ae099c6092)

**Outline:**
- Install: self-hosted
- Version: v0.79.1

**Desktop:**
 - OS: Ubuntu
 - Browser Firefox
 - Version 130

**Comment by marvelxcodes** [comment]
I'd like to work on this bug. Please assign it to me, I'd be happy to contribute.

**Comment by tommoor** [comment]
> Either the sidebar for shares with sub-documents is always visible (preferred), or it is possible to toggle the stickiness of the sidebar.

Agreed with the preferred option here, we should just ignore the collapsed sidebar from signed in state.

> I'd like to work on this bug. Please assign it to me, I'd be happy to contribute.

Issues cannot be assigned to non-collaborators, but feel free to submit a PR.

**Comment by tommoor** [comment]
Closed by https://github.com/outline/outline/pull/7842
