### ISSUE TITLE
Home Redirect Bug  v0.80.2

### ISSUE THREAD

**Issue by RyousukeUchino** [outline/outline#7662]
#### Environment

- Docker Outline v0.80.2

#### Steps to Reproduce

1. Log in using Slack authentication.
2. Ensure that you have already opened `/setting/security`.
3. Click "Return to App" and you will be redirected back to `/setting/security`.
4. Even after logging out and logging back in, you will be redirected to `/setting/security`.
5. Directly navigating to `/home` results in a redirect, but navigating to `/search` works as expected.

#### Bug Description

It is not possible to navigate to `/home`. This issue persists even when the setting "Remember last opened location" is disabled. Each time a redirect occurs, the following log is output to the console:

```log
Logger.ts:26 [lifecycle] Spending post login path {path: '/settings/security'}
Logger.ts:26 [lifecycle] Spending post login path {path: '/settings/security'}
Logger.ts:26 [lifecycle] Spending post login path {path: '/settings/security'}
```

The redirect path seems to be the page that was open at the time of logout.
Basic troubleshooting steps such as hard cache clearing and container restarts have already been performed.

**Outline (please complete the following information):**
- Install: self hosted Ubuntu 22.04 LTS
- Version: self hosted Outline v0.80.2

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version  129.0.2792.52

**Comment by psychedelicu** [comment]
I have the save issue. When i click Home it redirect me to a doc. Also, there is an 404 error on some docs if i open them drectly from the left sidebar.

<img width="1356" alt="image" src="https://github.com/user-attachments/assets/866da95a-5c59-4f47-894c-f9603cdba04e">
