### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by alfakini** [outline/outline#767]
Hey outline people!

Congratulations for the awesome work on Outline!

I have issues with insecure content coming from S3 buckets over `http`. The problem is that I configured the S3 integration using the `https` URL. Seems that the problem is in these lines where there is a replacement in the url string. Sorry, I didn't dive deep to investigate it: https://github.com/outline/outline/blob/master/server/utils/s3.js#L40

> Loading mixed (insecure) display content “http://XXX.s3.amazonaws.com/CCC/avatars/XXX-YYY-ZZZ/XXX-YYY-ZZZ” on a secure page

What do you think?

**Comment by tommoor** [comment]
@alfakini once the avatars are uploaded the urls are stored in the db. Is it possible that you previously had it set as http? Check your db records to see what's stored there.

**Comment by alfakini** [comment]
That makes sense @tommoor! Thanks :)
