### ISSUE TITLE
maybe typo: node version specified in the Local Development setup guide will break the setup process.

### ISSUE THREAD

**Issue by Abhi-Bohora** [outline/outline#7695]
In the local development setup guide [`local-development`](https://docs.getoutline.com/s/hosting/doc/local-development-5hEhFRXow7) this is the node version specified in the dependencies section (v16 LTS preferred). But if we switch to that node version and run `make up`  than we will get this error.
![setup](https://github.com/user-attachments/assets/652b4c76-e19b-43f2-afd2-628f5029c969)
Everything works fine if we switch to node (v20 LTS)

:( I couln't find other labels other than bug

**Comment by tommoor** [comment]
Updated ✅
