### ISSUE TITLE
Shouldn’t it be possible to log in with an email magic link even if the account has already logged in via another method?

### ISSUE THREAD

**Issue by HHHHhgqcdxhg** [outline/outline#7698]
I want to be able to log in using an email magic link even after the account has already logged in via SSO.

I configured OIDC login, and after logging into the account using the same email via OIDC, when I try to log in again using the email magic link, it redirects me to auth/oidc. However, I want to log in with the email magic link instead.

The reason for this requirement is that my Outline instance is deployed on a machine at my home, and I can directly connect to my home server via `outline.somedomain.com`. At the same time, I’ve also set up a Cloudflare tunnel to access my Outline instance via `outline111.someotherdomain.com`, which connects to my home server through Cloudflare.

The issue is that when I log in via OIDC, the OIDC provider will redirect me to the configured callback URL. The callback URL I’ve configured for OIDC is on `outline111.someotherdomain.com`, so I cannot log in to `outline.somedomain.com` using OIDC. However, with the email magic link, I can manually modify the domain in the link sent to my email to log in via `outline.somedomain.com`.

I noticed this piece of code in `plugins/email/server/auth/email.ts`. I’m wondering if the logic behind this code is reasonable. Shouldn’t it be possible to log in with an email magic link even if the account has already logged in via another method?

```typescript
    // If the user matches an email address associated with an SSO
    // provider then just forward them directly to that sign-in page
    if (user.authentications.length) {
      const authenticationProvider =
        user.authentications[0].authenticationProvider;
      ctx.body = {
        redirect: `${team.url}/auth/${authenticationProvider?.name}`,
      };
      return;
    }
```

**To Reproduce**
1. login with email magic link
2. config oidc
3. login oidc with the same email
4. try to login with email magic link

**Expected behavior**
login with email magic link

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.80.2

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 129.0.6668.70

**Comment by HHHHhgqcdxhg** [comment]
By the way, on the desktop, I can copy cookies to make the OIDC login work across both domains. However, this is much harder to achieve on mobile. With the email magic link, I can simply modify the domain in the received link to decide which domain to log in to.

**Comment by tommoor** [comment]
Hi – this is by design as a security measure, otherwise you could bypass 2FA methods on the SSO authentication by signing in through email
