### ISSUE TITLE
"Back to app" link broken if you logged out from the profile settings page (`/settings`)

### ISSUE THREAD

**Issue by micolous** [outline/outline#7707]
If you visit `/settings` while not logged in, it is impossible to go "back to the app" again from any settings page after logging in.

## Steps to reproduce

I'm using the Generic OIDC auth provider with `OIDC_DISABLE_REDIRECT=true`.

1. While logged into Outline, visit the Profile page (`/settings`).

2. Log out of outline.  Outline will:
   * terminate the session
   * redirect the browser to `/` and shows a button to login using the configured identity provider
   * set `postLoginRedirectPath = '/settings'` in session storage.

3. Click the button to login using the configured identity provider, approve any consent dialogs.

   Outline should send you to the profile page (`/settings`) when done (this is expected).

4. Click `Back to App`.

## Expected behaviour

You are taken back to the Outline app.

## Actual behaviour

Outline redirects you to `/`, then a moment later redirects you back to `/settings` (Profile page).

Navigating to other settings pages and then clicking "Back to App" also redirects you to the profile page.

Manually navigating to `/home` also redirects you `/settings`.

Each time you attempt to leave the settings page, the logger shows:

```
[lifecycle] Spending post login path 
Object { path: "/settings" }
Logger.ts:26:12
```

## Workaround

Clear the `postLoginRedirectPath` session storage item.

## Versions

**Outline (please complete the following information):**
- Install: self hosted Docker
- Version: 0.80.2

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox 130.0.1, Safari 17.6

**Mobile (please complete the following information):**
Not tested

**Comment by micolous** [comment]
Actually, this may be a duplicate of https://github.com/outline/outline/issues/7662

**Comment by micolous** [comment]
I added a breakpoint in the same spot https://github.com/outline/outline/commit/ce91071995cab05dbacdc76c1d0d1b875f8d2ea4 changed, and manually cleared session storage at that point, and it fixed the issue.

So I'm pretty sure https://github.com/outline/outline/commit/ce91071995cab05dbacdc76c1d0d1b875f8d2ea4 will fix this.

**Comment by tommoor** [comment]
Great, I was going to point out that issue too
