### ISSUE TITLE
After docker compose pull and up postgres exited

### ISSUE THREAD

**Issue by Lipown** [outline/outline#7711]
After latest upgrade postgres was exiting with below. Solved by adding version 16 to postgres in Docker compose file.

I suggest that docker compose file here in this repo should have firmly stated version of postgres

```
outline-postgres-1  | 
outline-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
outline-postgres-1  | 
outline-postgres-1  | 
outline-postgres-1  | 2024-10-01 11:46:51.744 UTC [1] FATAL:  database files are incompatible with server
outline-postgres-1  | 2024-10-01 11:46:51.744 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
```

**Comment by tommoor** [comment]
It's always best practice to pin your images (including Outline) at a specific version, this is mentioned in the docs:
https://docs.getoutline.com/doc/docker-7pfeLP5a8t#h-docker-compose

The compose file in this repo is for development purposes

**Comment by Lipown** [comment]
> It's always best practice to pin your images (including Outline) at a specific version, this is mentioned prominently in the docs: https://docs.getoutline.com/doc/docker-7pfeLP5a8t#h-docker-compose
> 
> The compose file in this repo is for development purposes

Appreciate your response but your link requires some login. I cannot find it in public documentation unfortunately :(
