### ISSUE TITLE
Search queries as URL parameters to support browser quick search keywords

### ISSUE THREAD

**Issue by almereyda** [outline/outline#7722]
The search form currently has this path:

> /html/body/div/div/div/div[2]/div/div[2]/div/div/div[1]/input

The Firefox web browser does not offer to add a search entry to it.

[On Wikipedia](https://de.wikipedia.org/wiki/Wikipedia:Hauptseite) the path looks like this:

> /html/body/div[1]/header/div[2]/div/div/div/form/div/div/div[1]/input

It has an additional form element that encapsulates the search input.

```html
<form id="searchform" class="cdx-typeahead-search__form" action="/w/index.php">
…
<input class="cdx-text-input__input" search-results-label="Suchergebnisse" accesskey="f" autocapitalize="sentences" title="Durchsuche die Wikipedia [Alt+Umschalt+f]" placeholder="Wikipedia durchsuchen" aria-label="Wikipedia durchsuchen" name="search" role="combobox" autocomplete="off" aria-autocomplete="list" aria-controls="cdx-typeahead-search-menu-0" aria-expanded="false" type="search" size="1">
…
</form>
```

Unfortunately it is not possible to craft a request that Outline can understand. The current way of passing the search term is to amend it as a path fragment to the search URL route, separated with a slash.

https://docs.example.org/search/example

Another example is given by DuckDuckGo:

```html
<form class="searchbox_form__LHyY9" role="search" aria-label="Searchbox" id="searchbox_homepage" method="GET" action="/">
…
<input aria-autocomplete="both" aria-controls="listbox--3" aria-expanded="true" aria-haspopup="listbox" aria-label="Search with DuckDuckGo" role="combobox" class="searchbox_input__bEGm3" type="text" name="q" autocomplete="off" id="searchbox_input" autocapitalize="none" autocorrect="off" placeholder="Suchen, ohne getrackt zu werden" required="" minlength="1" data-reach-combobox-input="" data-state="suggesting" value="">
…
</form>
```

In both cases the search term gets appended as a URL parameter after a question mark `?`, the `name` of the search input field, an equal sign and the field value. DuckDuckGo choose to use the `GET` `method` for their form.

https://docs.example.org/search?q=example

If Outline supported the URL parameter syntax for the search endpoint, one could encapsulate the input with a form that points at the endpoint, accepting to receive a search query value as a URL parameter, and would be able to add the Outline search form to a browser's quick search.

Reference:

- [\<input type="search"\> - HTML: HyperText Markup Language | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search)
- [\<form\>: The Form element - HTML: HyperText Markup Language | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form)
- [Sending form data - Learn web development | MDN](https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data)

**Comment by tommoor** [comment]
The OpenSearch standard is supposed to resolve this, we expose the correct meta tags and XML files for this to "just work" in theory:

https://app.getoutline.com/opensearch.xml

**Comment by almereyda** [comment]
Indeed, the file exists on our instance. I don't know how the search form would be bound to it.

Is it reproducible on your instance, that right clicking the search field does not show the "add as search engine" context menu item?

**Comment by tommoor** [comment]
<img width="574" alt="image" src="https://github.com/user-attachments/assets/d159db84-ed1c-468c-85eb-41c0a04e4f1d">

Yep, but only FireFox seems to support this well

**Comment by almereyda** [comment]
I can confirm that a self-hosted Outline also offered itself there.

It did not offer itself when right clicking the search box.
