### ISSUE TITLE
Associated uploaded data does not get deleted after deleting the source document

### ISSUE THREAD

**Issue by kuricialm** [outline/outline#7726]
Hi, I hope its an issue with my setup and not a missing feature, could you please as I find myself needing to manage the backend data more frequently as I add more users, which could lead to unnecessary storage upgrades down the line. 

**To Reproduce**
When creating an outline document and uploading some media on it such as PDF, photos or zip files and then delete this document. Everything that has been associated with this document will still remain in my either local uploads folder or S3 and I have to go filter and remove individual files that i don't need.

**Expected behavior**
Any uploads associated with a document to be deleted with the deletion of that document.

**Outline (please complete the following information):**
- Install: selfhosted
- Version: synology / docker / release v0.80.2

**Desktop (please complete the following information):**
 - OS: Mac Sequoia
 - Browser: Safari 18, Chrome 129

**Comment by tommoor** [comment]
Data will remain on disk until all references are _permanently_ deleted and the [cron job](https://docs.getoutline.com/s/hosting/doc/scheduled-jobs-RhZzCt770H) runs to cleanup loose attachments.
