### ISSUE TITLE
 throw new TypeError('Parameter "url" must be a string, not ' + typeof url);

### ISSUE THREAD

**Issue by astranavt** [outline/outline#773]
i use docker-compose up and app not start.

url.js:103
outline_1   |     throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
outline_1   |     ^
outline_1   | 
outline_1   | TypeError: Parameter "url" must be a string, not undefined
outline_1   |     at Url.parse (url.js:103:11)
outline_1   |     at Object.urlParse [as parse] (url.js:97:13)
outline_1   |     at new Sequelize (/opt/node_modules/sequelize/lib/sequelize.js:114:28)
outline_1   |     at Object.<anonymous> (/opt/outline/server/sequelize.js:13:26)
outline_1   |     at Module._compile (module.js:652:30)
outline_1   |     at loader (/opt/node_modules/babel-register/lib/node.js:144:5)
outline_1   |     at Object.require.extensions.(anonymous function) [as .js] (/opt/node_modules/babel-register/lib/node.js:154:7)
outline_1   |     at Module.load (module.js:565:32)
outline_1   |     at tryModuleLoad (module.js:505:12)
outline_1   |     at Function.Module._load (module.js:497:3)
outline_1   |     at Module.require (module.js:596:17)
outline_1   |     at require (internal/module.js:11:18)
outline_1   |     at Object.<anonymous> (/opt/outline/server/models/ApiKey.js:2:1)
outline_1   |     at Module._compile (module.js:652:30)
outline_1   |     at loader (/opt/node_modules/babel-register/lib/node.js:144:5)
outline_1   |     at Object.require.extensions.(anonymous function) [as .js] (/opt/node_modules/babel-register/lib/node.js:154:7)
outline_1   |     at Module.load (module.js:565:32)
outline_1   |     at tryModuleLoad (module.js:505:12)
outline_1   |     at Function.Module._load (module.js:497:3)
outline_1   |     at Module.require (module.js:596:17)
outline_1   |     at require (internal/module.js:11:18)
outline_1   |     at Object.<anonymous> (/opt/outline/server/models/index.js:2:1)
outline_1   |     at Module._compile (module.js:652:30)
outline_1   |     at loader (/opt/node_modules/babel-register/lib/node.js:144:5)
outline_1   |     at Object.require.extensions.(anonymous function) [as .js] (/opt/node_modules/babel-register/lib/node.js:154:7)
outline_1   |     at Module.load (module.js:565:32)
outline_1   |     at tryModuleLoad (module.js:505:12)
outline_1   |     at Function.Module._load (module.js:497:3)
outline_1   |     at Module.require (module.js:596:17)
outline_1   |     at require (internal/module.js:11:18)
outline_1   |     at Object.<anonymous> (/opt/outline/server/utils/updates.js:8:1)
outline_1   |     at Module._compile (module.js:652:30)
outline_1   |     at loader (/opt/node_modules/babel-register/lib/node.js:144:5)
outline_1   |     at Object.require.extensions.(anonymous function) [as .js] (/opt/node_modules/babel-register/lib/node.js:154:7)
outline_1   |     at Module.load (module.js:565:32)
outline_1   |     at tryModuleLoad (module.js:505:12)
outline_1   |     at Function.Module._load (module.js:497:3)
outline_1   |     at Module.require (module.js:596:17)
outline_1   |     at require (internal/module.js:11:18)
outline_1   |     at Object.<anonymous> (/opt/outline/server/index.js:9:1)
outline_1   |     at Module._compile (module.js:652:30)
outline_1   |     at loader (/opt/node_modules/babel-register/lib/node.js:144:5)
outline_1   |     at Object.require.extensions.(anonymous function) [as .js] (/opt/node_modules/babel-register/lib/node.js:154:7)
outline_1   |     at Module.load (module.js:565:32)
outline_1   |     at tryModuleLoad (module.js:505:12)
outline_1   |     at Function.Module._load (module.js:497:3)
outline_1   |     at Module.require (module.js:596:17)
outline_1   |     at require (internal/module.js:11:18)
outline_1   |     at Object.<anonymous> (/opt/outline/index.js:26:13)
outline_1   |     at Module._compile (module.js:652:30)
outline_1   |     at Object.Module._extensions..js (module.js:663:10)
outline_1   |     at Module.load (module.js:565:32)
outline_1   |     at tryModuleLoad (module.js:505:12)
outline_1   |     at Function.Module._load (module.js:497:3)
outline_1   |     at Function.Module.runMain (module.js:693:10)
outline_1   |     at startup (bootstrap_node.js:191:16)
outline_1   |     at bootstrap_node.js:612:3
outline_1   | error Command failed with exit code 1.
outline_1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tommoor** [comment]
Have you correctly set the env variables as described in the installation steps?

https://github.com/outline/outline#installation

**Comment by Adekoreday** [comment]
hope you are not mixing ES6 and ES5 or ES7 syntax in your code thats how i fixed mine
