### ISSUE TITLE
SequelizeDatabaseError: relation "teams" does not exist

### ISSUE THREAD

**Issue by Julianhm9612** [outline/outline#775]
I have a error, after the loging with Google. Google redirect to the main page of outline with the token auth, but the console show this error:

![image](https://user-images.githubusercontent.com/24255842/45576280-3154f500-b83c-11e8-97c7-e7f7405f252f.png)

**Comment by tommoor** [comment]
Hey @Julianhm9612 unfortunately I don't have the bandwidth to provide support for the open source project here. Did you follow the installation instructions and ensure that the database has been migrated?

**Comment by Julianhm9612** [comment]
Yes, i followed the installation instructions.

I will try another computer.

Thanks @tommoor! :D

**Comment by ekussberg** [comment]
I have the same issue by logging in via Slack, how did you solve this?

**Comment by saicrazyfire** [comment]
I ran into this issue as well but using a Slack app. I had to run `yarn sequelize:migrate` while the docker-compose was still active.

Run `docker ps -a` to get the container ID of `outline_outline_1`. Then run `docker exec -it {{container_id}} /bin/sh`.

From there, you should see a terminal which you can run `yarn sequelize:migrate` and then exit after completion. 

Question for the maintainer: Is there anyway for the docker-compose file to run this command by itself on first run?

**Comment by tommoor** [comment]
@saicrazyfire It's possible, but not wise to automatically run migrations – usually you want to do things like make a backup and ensure that the site is in maintenance mode / offline before migrating the database.
