### ISSUE TITLE
Cannot use Minio as S3 storage in latest version.

### ISSUE THREAD

**Issue by YIKAILucas** [outline/outline#7754]
I upgrade from 0.76.1 to 0.80.2. The Minio storage cannot be access, It might because the change about AWS_ACCESS_KEY_ID in v0.77.2 #7177.
and I use rancher to run the docker image, thus I would like use outline.env to set up all config file.

How to fix the problem  ???

**Outline (please complete the following information):**
- Install: [self hosted]
- Version: [0.80.2]

**Comment by tommoor** [comment]
Please stop filing duplicate issues
