### ISSUE TITLE
Image uploaded to S3 but document not updated with correct image URL

### ISSUE THREAD

**Issue by MrZeroo00** [outline/outline#777]
Hello,

I am having trouble adding images to documents.
I am using a self-hosted Outline with .env variables set.
Here's what I get when uploading an image:
<img width="594" alt="screen-shot-2018-09-21-13-08-45" src="https://user-images.githubusercontent.com/7818591/45878601-f43fb400-bda1-11e8-8b98-44b1584b12a2.png">
The image is uploaded to S3, I can see it through my AWS Explorer but the document isn't updated with the S3 URL and stays like this: 

> blob:http://test.xxx.xxx:3000/6de24125-316f-4cee-b4ee-c5f448f1745d

I can from the network requests that AWS return the correct URL:

![screen-shot-2018-09-21-13-21-28](https://user-images.githubusercontent.com/7818591/45878609-002b7600-bda2-11e8-8005-0a4f68983652.png)
)

This is what I get when I refresh the page:

![screen-shot-2018-09-21-13-19-25](https://user-images.githubusercontent.com/7818591/45878624-12a5af80-bda2-11e8-9baf-5987a859c71a.png)

How to debug this?

Thanks!

**Comment by tommoor** [comment]
@MrZeroo00 as this issue doesn't exist on the hosted version it's difficult to say. Unfortunately I don't have time to support everyone that wishes to run Outline locally.

Did you make any progress debugging?

**Comment by MrZeroo00** [comment]
No, it's doesn't seem easy to debug.
What could help me is an example of your SaaS configuration (from S3 and .env). I guess you're doing the same thing I am trying to do on your side.

**Comment by leinue** [comment]
I encountered this problem too.
