### ISSUE TITLE
Mermaid Diagram Rendering

### ISSUE THREAD

**Issue by wenny111** [outline/outline#7777]
1. Mermaid Changes Not Reflected in History
2. Unsupported Chinese Comma, refer to [(https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/1294)]
![企业微信截图_17289005586367](https://github.com/user-attachments/assets/20f85a46-13a3-4a81-89ab-e600458a23a6)

**Outline (please complete the following information):**
- Version: v0.80.0

**Desktop (please complete the following information):**
 - OS: Windows 11 Version 23H2 (Build 22631.3880)
 - Browser: chrome
 - Version 127.0.6533.100 (正式版本) （64位） (cohort: Stable)

**Comment by tommoor** [comment]
I'm afraid this bug must be fixed upstream in Mermaid, please file an issue there
