### ISSUE TITLE
Pasting or creating specific link introduces a bugged empty line

### ISSUE THREAD

**Issue by alexpana** [outline/outline#778]
I couldn't reproduce this with any link, but this one seems to break the editor consistently: `https://www.gamasutra.com/view/news/165359/GDC_2012_10_tutorial_tips_from_Plants_vs_Zombies_creator_George_Fan.php`

Either pasting this as a link or pasting the text and adding the link afterwards results in a newline being added before the link. From the erroneous empty line before the link the cursor cannot move down. Moving the cursor right makes it jump to the second character on the second line (inside the link). This new line cannot be deleted.

**Comment by tommoor** [comment]
Very strange, and reproducible – thanks for filing!

**Comment by tommoor** [comment]
From what I can tell it's to do with the length of the link, if the link is long enough to wrap onto a new line the bug will happen. You can probably get around it by selecting some text and hitting `CMD+V` with the link on the clipboard which will make the selected text itself a link 😄
