### ISSUE TITLE
Show count of occurrences in find and replace

### ISSUE THREAD

**Issue by tommoor** [outline/outline#7819]
It would be nice to include the equivalent of this `1/x` language from chromium. Customer requested

<img width="401" alt="image" src="https://github.com/user-attachments/assets/59a2e489-5e57-427f-8da2-365dfcc74a2a">

This UI from Pitch is a lot bigger but could inspire a little redesign here soon 

<img width="331" alt="image" src="https://github.com/user-attachments/assets/40f981db-b6f6-477e-9fde-60fc10297cf9">

**Comment by govindplal** [comment]
can i work on this?

**Comment by tommoor** [comment]
You're welcome to take a stab
