### ISSUE TITLE
SelectionToolbar background cut off my sidebar

### ISSUE THREAD

**Issue by infinite-persistence** [outline/outline#7836]
The last few buttons in the toolbar doesn't have a background, and blends in with the sidebar.

![image](https://github.com/user-attachments/assets/e0fe3f0c-7eb7-4568-ba82-68a2f82d0fad)

- Install: local development
- Version: `3692d9c9`

I'm also running this under VMWare -- not sure if that matters.

**Comment by tommoor** [comment]
I know which change caused this
