### ISSUE TITLE
LaTeX doesn't render in "Contents" tab

### ISSUE THREAD

**Issue by xhyrom** [outline/outline#7837]
LaTeX doesn't render in "Contents" tab

**To Reproduce**
1. Create header with latex e. g `# $$F_1 = 5$$`
2. Look at contents tab

**Expected behavior**
![image](https://github.com/user-attachments/assets/7bdcec43-da5a-45d5-812f-a878ef14505a)

**Screenshots**
![image](https://github.com/user-attachments/assets/6d59103a-b212-4dfd-a549-efe1cb359e89)

**Outline (please complete the following information):**
- Install: self hosted
- Version: https://github.com/outline/outline/commit/9b807f7a9e04a39177bd68934b05e06daa0d4a49

**Desktop (please complete the following information):**
- OS: Linux
- Browser Chrome
- Version 129.0.6668.89

**Comment by tommoor** [comment]
I'm afraid this won't be supported
