### ISSUE TITLE
Triple clicking last line of code block marks all lines above

### ISSUE THREAD

**Issue by misi70** [outline/outline#7858]
A triple click in text usually selects the complete line. This also works in code blocks in Outline. But triple clicking the last line in a code block marks all lines in the code block above the last line.

Expected behavior would be that triple clicking the last line in a text block selects this line.

Workaround is to add an additional empty line at the end of the text block.

Selfhosted in Docker, Version 0.80.2
Browser: Firefox 131.0.3

**Comment by tommoor** [comment]
This does appear to only be an issue in Firefox

**Comment by tommoor** [comment]
Closed by https://github.com/outline/outline/pull/7876
