### ISSUE TITLE
Anchor-Link: scrolls before images load > wrong position

### ISSUE THREAD

**Issue by e1ke** [outline/outline#7867]
**To Reproduce**
1. Create a document with a few images
2. Set multiple headings
3. Copy links from headings somewhere in the middle
4. Open url to heading (eg https://outline.COMPANY.COM/s/8856..............6d3#h-please-scroll-to-this-heading)

**Expected behavior**
The Webrowser should have scrolled to the expected heading

**Actual behavior**
The position after opening the page is far more top than the actual heading. The page is scrolling to the heading, before the images are loaded. After the images have been loaded, I refresh the page, then the position is exactly on the expected heading.
At least I assume that that is the reason.

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.80.2
- commit sha: 9b807f7a9e04a39177bd68934b05e06daa0d4a49

**Desktop**
Windows 10
Brave (same on Firefox)

**Comment by tommoor** [comment]
The fix here is to make sure we store image sizes against all images that are uploaded, not just those that are resized – this will prevent the relayout.

**Comment by tommoor** [comment]
This should be the case for any newly uploaded images, let me know if you're still seeing this behavior on documents where the images have been added in a recent version (I cannot currently reproduce)
