### ISSUE TITLE
French language accents are blocking in Outline search

### ISSUE THREAD

**Issue by Slygeers** [outline/outline#7869]
French language accents are blocking in Outline search

**To Reproduce**
1. Configure Outline in French from A & Z.
2. Create an article containing the word "empêcher" for example
3. Go to the search bar, enter "empecher" without the accent. However, this is for all French words with an accent.

**Expected behavior**
On Outline with the French language, the accents are blocking. They are case sensitive, and therefore the search is truncated. For example, the word "empêcher" has an accent of type **"^"**, and if we enter "empecher", which has the same meaning, and which has the same spelling except for the accent, we find no results. An option to work around the bug would be welcome, for example "case sensitive search"

**Screenshots**

_Without_
![image](https://github.com/user-attachments/assets/deff4819-a599-41be-8c91-9b1658ad0afe)

_With_
![image](https://github.com/user-attachments/assets/b47ffbda-cbb1-4906-8e93-706b5fb25f72)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.80.2
- commit sha: https://github.com/outline/outline/commit/9b807f7a9e04a39177bd68934b05e06daa0d4a49

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser : Opera / Chrome / Edge
 - Version : Last

**Comment by tommoor** [comment]
Unfortunately this is a technical limitation at this time due to our reliance on Postgres' internal FTS. To support such searching we would need to have a dependency on running a separate search engine. I'm going to combine this with #3207 because it's essentially the same problem

**Comment by Slygeers** [comment]
> Unfortunately this is a technical limitation at this time due to our reliance on Postgres' internal FTS. To support such searching we would need to have a dependency on running a separate search engine. I'm going to combine this with #3207 because it's essentially the same problem

Thank you for your quick response. Hopefully there will be a workaround one day. In the meantime, I have a script that re-enters the title in the article, without the accent, in order to improve keyword searching. Have a nice day

**Comment by tommoor** [comment]
I think we'll also lean on vector search more in the future, which will also help with this type of issue as a side effect. Thanks for your support

**Comment by DebianRoxx** [comment]
It seems it's possible inside postgresql : https://stackoverflow.com/questions/28627951/postgresql-accent-case-insensitive-search
