### ISSUE TITLE
Lightboxes of images pasted to comments break after minimising

### ISSUE THREAD

**Issue by almereyda** [outline/outline#7891]
When opening an image from a comment into the lightbox, it can only be minimised once.

The mouse cursor will remain the minus magnifier icon that showed before minimising.

Clicking the image does not incur any reaction from the interface.

The mouse cursor over other images will also not change to a plus magnifier anymore.

Can someone reproduce this behaviour on v0.80.2?

*Edit:* Sorry, used the `issues/new` route and wasn't presented with the choice for a template at `issues/new/choose`.

**Comment by tommoor** [comment]
Coincidentally reported and fixed earlier today https://github.com/outline/outline/issues/7883

**Comment by almereyda** [comment]
What a coincident.
