### ISSUE TITLE
The page scrolls to the very top, after switching from view to edit mode

### ISSUE THREAD

**Issue by DianaRunieieva** [outline/outline#7910]
When switching between viewing and editing modes, the user is returned to the very top of the page, because of which you have to scroll down every time to return to the desired element.

**To Reproduce**
1. Go to the document view page
2. Scroll down to the middle of the page
3. Press "Edit" button

**Expected behavior**
Edit mode opens without changing the page position, in the same place where the user was in viewing mode.

**Screenshots**

https://github.com/user-attachments/assets/9e763ec8-e649-4e8e-bbf7-2d5176236906

**Desktop (please complete the following information):**
 - Browser chrome
 - Version latest

**Comment by tommoor** [comment]
Hmm, this didn't used to be the case – must have regressed.

**Comment by guninwasan** [comment]
Hey @tommoor / @DianaRunieieva can I tackle this issue?

**Comment by ysmintor** [comment]
I have the same issue. Please fix this bug.

**Comment by tommoor** [comment]
I found where this regression happened so I'll take the fix
