### ISSUE TITLE
Templates shared with the workspace are not being displayed to users

### ISSUE THREAD

**Issue by apoorv-mishra** [outline/outline#7919]
### Discussed in https://github.com/outline/outline/discussions/7915

<div type='discussions-op-text'>

<sup>Originally posted by **notfounnd** November  8, 2024</sup>
I have in my Outline instance some document templates registered at the workspace level. I verified today that these doc templates that I have in the tool are not being displayed to be used by users.

Is this behavior normal?

To get around this I had to share the template to a view group of users.</div>

**Comment by tommoor** [comment]
Dupe of #7916
