### ISSUE TITLE
The Keyboard shortcuts page has a layout bug

### ISSUE THREAD

**Issue by nayatec** [outline/outline#792]
Hi :-)
There is a layout bug in the keyboard shortcuts page : 
![image](https://user-images.githubusercontent.com/43960749/48007466-fd010500-e117-11e8-9e08-a284a89c2c41.png)

There is a layout bug at the begining shifting everything afterwards.

**Comment by nayatec** [comment]
I just tried on Chrome Version 70.0.3538.77 (Build officiel) (64 bits) on an old windows server 2008 R2, and it works ok !
So it seems to be a browser/OS related bug....

**Comment by tommoor** [comment]
Thanks for the info, I think it's likely because of the typeface it's falling back to. The layout here is probably a little fragile when the line height changes, still seems worth fixing 😄

**Comment by nayatec** [comment]
You're right. My system falls to Ubuntu which provoke the bug. If i remove it from the font-family property 
 it falls back to Cantarell on my system and is displaying ok.

**Comment by nayatec** [comment]
Thanks !
