### ISSUE TITLE
After deleted GSuite user, user can still use hosted version of getoutline.com

### ISSUE THREAD

**Issue by teddychan** [outline/outline#795]
## How to reproduce
- Add a new GSuite user
- Login to getoutline.com using Google
- Play around~~
- Go to GSuite admin page, delete that new user

## Expect
- the user should log out from getoutline.com and can't access any content anymore.

### For the deleted user
- He can visit the getoutline.com, able to view and modify, and owned all content.

### For the other Google Active user
- We can still see the deleted user, seems we need to suspend it manually?
but can't delete it now.

![image](https://user-images.githubusercontent.com/1013507/48038704-c0331d80-e1ac-11e8-8c12-a02a1152ece4.png)

**Comment by tommoor** [comment]
Hey! Thanks for the feedback, seems like there are a couple of ways this could be improved:

- [ ] Allow permanent deletion of a user when they have already been removed in GSuite
- [ ] Check that the user is still valid in Slack / Google when first loading the app (perhaps this can be done async to avoid slowing down initial load)

In the meantime, suspending the user will do everything you need – it's just a manual process as you've found.
