### ISSUE TITLE
Multi-digit numbers in numbered lists go off page in exported PDFs

### ISSUE THREAD

**Issue by designatedsuccessor** [outline/outline#7958]
If you export any document to PDF that contains a numbered list that has goes beyond step 9 (so, 10, 11, 12, etc.), part of the step's number cannot be seen because the number goes off the left side of the page.  Example of an exported PDF:

![image](https://github.com/user-attachments/assets/55b6f37e-e46c-41c5-8720-091bf5044f03)

The numbers on the left should be 99, 100, and 101.

Outline:
- Install: getoutline.com

Desktop (please complete the following information):
 - OS: Windows 11 23H2
 - Browser: Chrome
 - Version: Version 129.0.6668.101

**Comment by infinite-persistence** [comment]
Ah, no wonder couldn't repro (exporting to PDF via Ctrl+P works fine).
Mobile mode with large list does clip, but that's an offscreen clip.

Maybe just a margin setting with gotenberg?
