### ISSUE TITLE
Store images in private bucket

### ISSUE THREAD

**Issue by tommoor** [outline/outline#796]
Right now images are stored publicly on S3 with high entropy URL's to ensure that finding / accessing them is not possible without going through the wiki. However, this can be improved by requiring a signature to access the images…

Implementation would probably look like:

- Change the url that is stored in the document to point to an Outline API url, something like:
`https://www.getoutline.com/api/images.info?id=XXX`
- Have the API forward these requests/response to the backing storage with the correct signature
- On export we have two options, either:
    - download the images, store them in the ZIP and replace the url to a local path
    - embed an access token in the urls so that they work when loaded elsewhere

**Comment by teddychan** [comment]
For self-hosted solution, may be the easiest method is to use S3 bucket policy.
Allow certain IPs to visit those images.

**Comment by himanshuagarwal272** [comment]
Hey, I am thinking of picking this up! Any more suggestions @tommoor?

**Comment by tommoor** [comment]
I still think that the api "proxy" is the way to go for loading authenticated images, even doing this half of the task would be very useful.

The tricky part is what to do on export as it really complicates the existing process somewhat, i'd imagine we'd be able to search the documents for images and include them in the zip as suggested in the PR description.

**Comment by himanshuagarwal272** [comment]
> I still think that the api "proxy" is the way to go for loading authenticated images, even doing this half of the task would be very useful.
> 
> The tricky part is what to do on export as it really complicates the existing process somewhat, i'd imagine we'd be able to search the documents for images and include them in the zip as suggested in the PR description.

Let me start working on the first half and Let's discuss how can we go forward with the other part
