### ISSUE TITLE
CPU and memory spikes

### ISSUE THREAD

**Issue by soundstep** [outline/outline#7982]
We have been self-hosting Outline for a couple of years, we updated the version from `0.78.0` to `0.81.0`.

We are seeing unusual CPU and memory spikes, the spikes are killing our 2GB containers while the instances were previously running well with 1GB instances.

![Screenshot 2024-11-19 at 12 21 59](https://github.com/user-attachments/assets/038b8bd5-6fae-4a20-bf7d-a27af5f431ba)

We suspect the instances are trying to send emails, while we never set up any of the [SMTP env vars](https://docs.getoutline.com/s/hosting/doc/smtp-cqCJyZGMIB).

We guessed this because we have Github Action workflows that post updates to our Outline instance using the API every hour and the spike is every hour. We are not posting many pages, 3 or 4 `document.update`. We have around 250 members. Here are the logs we're seeing:

![Screenshot 2024-11-19 at 12 17 17](https://github.com/user-attachments/assets/d038eb1d-1ede-45df-bb8c-ef7158750bce)

The error:

![Screenshot 2024-11-19 at 14 36 14](https://github.com/user-attachments/assets/85e2bcb4-6f94-4cbb-91fc-a0d3cf6fafc0)

The number of errors:

![Screenshot 2024-11-19 at 14 47 22](https://github.com/user-attachments/assets/0e4323ae-763b-4ab7-a75d-486f5a37f245)

We turned off the Github Actions that are posting the updates to the Outline and it is a clear outcome. We turned the CI jobs off before `13:00`, see how the line became flat:

<img width="761" alt="Screenshot 2024-11-19 at 14 57 54" src="https://github.com/user-attachments/assets/0d27b61f-e2d3-40f5-8f49-2693d9dc15d1">

Can you give us some support with this issue?

**To Reproduce**
1. Self-hosted an outline instance, with no SMTP set up
2. Trigger emails notification with an API document update
3. The memory and CPU should be spiking

**Expected behavior**
Some activities but not to the point reaching 2GB memory usage and overwhelmed CPUs.

**Screenshots**
See above

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.81.0 (Docker: `FROM outlinewiki/outline:0.81.0`)

**Desktop (please complete the following information):**
 - OS: MacOS 14.7
 - Browser Chrome

**Comment by tommoor** [comment]
`v0.81.1` should resolve your issues

**Comment by soundstep** [comment]
@tommoor Outstanding response time!

Thank you for picking that up, we love Outline ;)

This looks very fixed, the update was made at `9:00`.

Thanks again!

![Uploading Screenshot 2024-11-20 at 09.40.49.png…]()
