### ISSUE TITLE
Sometimes it show blank page after login by Google

### ISSUE THREAD

**Issue by teddychan** [outline/outline#799]
# ENV
1. Self-hosted
2. Google Login
3. Lastest outline https://github.com/outline/outline/commit/4260b5e664667a14ab9683abf98fae9fa113442f
4. Mac Chrome Version 70.0.3538.77 (Official Build) (64-bit) 
5. Run by `yarn dev`, node 8.12.0 Ubuntu 16.04

# Issue
We get a blank after login with Google.

# Error we can have
Notice the URL should go to `URL/dashboard` 
but it gets stuck in `/#`

![image](https://user-images.githubusercontent.com/1013507/48246301-ea454380-e429-11e8-9b7c-998780038a5e.png)

It happens from time to time.
If we clear the Chrom Application cache, it will work again for a while.

**Comment by tommoor** [comment]
If you click on `bundle.js` in the error in the console you should see the response that came back that triggered the Unexpected token. Is it invalid js?

I'd recommend not running `yarn dev` as the app will be running development checks and be much slower, although that might prove useful for debugging this… 😄

**Comment by teddychan** [comment]
Agree we should run in production ENV.
but we are testing in local and found that it don't work.

BTW, the problem seems more clear now.
The css seems fail to be generated.

![image](https://user-images.githubusercontent.com/1013507/48303171-e86ea380-e541-11e8-976c-59b24e7b557f.png)

**Comment by tommoor** [comment]
@teddychan I think the solution here is to not run in development mode, I'm afraid It's difficult for me to debug further and am trying to concentrate my efforts on solving issues in the hosted version of the application.
