### ISSUE TITLE
Mermaid is out of date

### ISSUE THREAD

**Issue by mgmorcos** [outline/outline#7995]
Mermaid is out of date, so newer diagrams (e.g., Timeline) are not available

**To Reproduce**
1. Add Mermaid block to a document
2. Paste example Timeline diagram into the Mermaid block:
```
timeline
    title History of Social Media Platform
    2002 : LinkedIn
    2004 : Facebook
         : Google
    2005 : Youtube
    2006 : Twitter
```
3. See Error: No diagram type found for text timeline

**Expected behavior**
Timeline diagram is rendered without error.

**Outline (please complete the following information):**
- Install: self hosted (via Docker)
- Version: [0.81.1](https://registry.hub.docker.com/layers/outlinewiki/outline/0.81.1/images/sha256-75cb95106729fc33d086b967f871619d47445b140e14c4affa4edd826d2cbb9d?context=explore)

**Comment by tommoor** [comment]
Already addressed for next release https://github.com/outline/outline/pull/7964
