### ISSUE TITLE
The expiresIn of S3Storage.getSignedUrl is always 900

### ISSUE THREAD

**Issue by MinjeJeon** [outline/outline#8012]
In outline/server/storage/files/S3Storage.ts, the expiresIn parameter is defined in the command. However, it is documented in @aws-sdk/s3-request-presigner that expiresIn should be located in a different parameter.

**Expected behavior**

The expiresIn parameter should be correctly set according to the command definition, for example, { expiresIn: 3600 }.

```
const url = await getSignedUrl(client, command, { expiresIn: 3600 });
```

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: self-hosted
- Version: v0.81.1

**Comment by tommoor** [comment]
Good spot – how did you notice this?

**Comment by MinjeJeon** [comment]
Sometimes it fails to show photos or videos. I've checked it through Chrome Developer Mode and noticed some 403 responses from my self-hosted S3 service.
