### ISSUE TITLE
Image uploads correctly, GET attachments.redirect uses wrong URL

### ISSUE THREAD

**Issue by dwbrite** [outline/outline#8025]
When uploading an image, the file successfully uploads to minio, but is not attached to the document. Further investigation reveals a GET request to amazonaws.com, which does not match AWS_S3_UPLOAD_BUCKET_URL.

On refresh, the image is not attached to the document.

**To Reproduce**
Unknown at this time.

**Expected behavior**
Image should apply to the document.

**Screenshots**
![image](https://github.com/user-attachments/assets/177da52a-05d3-46fc-9ffc-f4d107c9d1ca)

Note the POST request to `outline.dwbrite.com:9000`. The upload succeeds for minio. This also suggests the AWS_S3_UPLOAD_BUCKET_URL is correct. 

**Env vars**
```
- name: AWS_S3_UPLOAD_BUCKET_NAME
  value: "outline"
- name: AWS_S3_UPLOAD_BUCKET_URL
  value: "https://outline.dwbrite.com:9000/outline"
- name: AWS_S3_FORCE_PATH_STYLE
  value: "true"
- name: AWS_REGION
  value: "local"
```

**Outline (please complete the following information):**
- Install: self-hosted
- Version: Tested on 0.72.2, 0.78.0, 0.81.1

**Desktop (please complete the following information):**
 - OS: Fedora 41
 - Firefox
 - Version :shrug: 

**Mobile (please complete the following information):**
 - Device: -
 - OS: Android 14
 - Chrome

**Comment by dwbrite** [comment]
Avatar uploads continue to work fine, even while attaching images fails. So far I've tested with images, videos, and files, and all of these fail and try to redirect to amazonaws.com. Though files and videos do display a (faulty) UI element.

**Comment by tommoor** [comment]
I believe with non-AWS servers you need to set `AWS_S3_FORCE_PATH_STYLE=true`

**Comment by dwbrite** [comment]
That env var was already set ^

https://github.com/outline/outline/discussions/5616 has a similar problem, and notes that the bucket URL shouldn't include the bucket name in the path. Unfortunately this doesn't work for me either, and now the upload process fails with a 400, and attachments in posts still redirect to amazonaws.com.

![image](https://github.com/user-attachments/assets/f5d7cec2-514a-4193-828f-5960b0d9f049)


Current env vars:
AWS_REGION : local
AWS_S3_FORCE_PATH_STYLE : true
AWS_S3_UPLOAD_BUCKET_NAME : outline
AWS_S3_UPLOAD_BUCKET_URL : https://outline.dwbrite.com:9000
...

**Comment by dwbrite** [comment]
@tommoor figured it out. Because my Outline Minio api is at `outline.dwbrite.com:9000` and the bucket is named `outline`, getEndpoint in S3Storage returns undefined, which ends up setting the S3 client endpoint to undefined:

```
private getEndpoint() {
    if (env.AWS_S3_ACCELERATE_URL) {
      return env.AWS_S3_ACCELERATE_URL;
    }

    // support old path-style S3 uploads and new virtual host uploads by
    // checking for the bucket name in the endpoint url.
    if (env.AWS_S3_UPLOAD_BUCKET_NAME) {
      const url = new URL(env.AWS_S3_UPLOAD_BUCKET_URL);
      if (url.hostname.startsWith(env.AWS_S3_UPLOAD_BUCKET_NAME + ".")) {
        return undefined;
      }
    }

    return env.AWS_S3_UPLOAD_BUCKET_URL;
  }
  ```

**Comment by dwbrite** [comment]
lmk if I should toss up a PR. I've updated my project to rename the bucket to `outline-data` :+1:

**Comment by dwbrite** [comment]
Stream of consciousness considerations for this code:

Assuming the endpoint _is_ supposed to be virtual-host style, why would we want to default to AWS if the user accidentally included the bucket name? Could we filter off the bucket name from the endpoint url? Could we just throw an error instead? I mean, I can imagine a scenario in which we have a container at bucket.bucket.com (no path), where URL is bucket.com and bucket-name is bucket. :thinking: 

Maybe the best solution is to add that FORCE_PATH exception and make a note in the docs...

**Comment by tommoor** [comment]
It looks like this was briefly the case, but caused issues. Unfortunately the report in question wasn't linked to the commit – it's very difficult to change this behavior without breaking existing installations

https://github.com/outline/outline/commit/8b4b2ca7412d0929ac49c67843ae05ed06ffe71d

**Comment by dwbrite** [comment]
In that case it sounds like "AWS_S3_FORCE_PATH_STYLE" is a slight misnomer, but, "don't break user-space" is a pretty good line to draw. Maybe another env var to disable this.

Regardless of a "proper" solution, I guess I'm happy enough that I can work around it by changing the bucket name - and hopefully this thread will help someone else in the future :shrug:

**Comment by tommoor** [comment]
I think we'll add a warning log here and call it resolved, does that sound reasonable?
