### ISSUE TITLE
Auto add \ in when save the document

### ISSUE THREAD

**Issue by teddychan** [outline/outline#803]
Both cloud and self hsoted,
Try to type the text:

```
#team-sre
```

As below:
![image](https://user-images.githubusercontent.com/1013507/48637792-b3fb5b80-ea09-11e8-8fde-e5f5f3bbcc86.png)

After saving, you will get
![image](https://user-images.githubusercontent.com/1013507/48637832-d0979380-ea09-11e8-9ce2-5d26ccc5819b.png)

Edit again and save:
![image](https://user-images.githubusercontent.com/1013507/48637840-d55c4780-ea09-11e8-8f38-23f6041e2a27.png)

**Comment by tommoor** [comment]
Thanks, will fix as a priority
