### ISSUE TITLE
Uploading via API causing issues "

### ISSUE THREAD

**Issue by AlexWHughes** [outline/outline#8035]
Trying to build a script to pull down images from our previous CMS and upload them to existing pages on Outline. (https://www.getoutline.com/developers#tag/attachments/POST/attachments.create)

The issue I am hitting is no matter what i try to send Outline when creating attachments I still get the following result.

    "ok": false,

    "error": "validation_error",
    "status": 400,
    "message": "size: Expected number, received string"

I have tried to use postman with the same result and its driving me mad. 
<img width="701" alt="Screenshot 2024-11-29 at 12 28 08 am" src="https://github.com/user-attachments/assets/49be391e-6711-472f-b78d-7a0a0ea23c5c">

**Comment by tommoor** [comment]
The API always expects a JSON body, not form-encoded

**Comment by tommoor** [comment]
Alternatively, for images... if you base64 encode the image and put it inside of markdown syntax, then it will be automatically converted to an attachment.

**Comment by NangeGao** [comment]
> The API always expects a JSON body, not form-encoded

I met the same problem. Any example please?
How can I get the image size before create an attachment?

**Comment by NangeGao** [comment]
```
curl https://myoutline.com/api/attachments.create \
  --request POST \
  --header 'Authorization: Bearer ol_api_alSxxxxxxxxxxxxxxxxxxxxx' \
  --header 'Content-Type: application/json' \
  --data '{
  "name": "favicon.png",
  "documentId": "af2d42d1-553b-4a2b-9ae1-ba4393285955",
  "contentType": "image/png",
  "size": 3037,
  "preset":"documentAttachment"
}'
```
I write the request like this. I think `name` is just the attachment name, so how do I pass the path of the local image, such as `/home/abc/images/favicon.png`?

**Comment by whuwangyong** [comment]
I met the same problem

**Comment by whuwangyong** [comment]
> ```
> curl https://myoutline.com/api/attachments.create \
>   --request POST \
>   --header 'Authorization: Bearer ol_api_alSxxxxxxxxxxxxxxxxxxxxx' \
>   --header 'Content-Type: application/json' \
>   --data '{
>   "name": "favicon.png",
>   "documentId": "af2d42d1-553b-4a2b-9ae1-ba4393285955",
>   "contentType": "image/png",
>   "size": 3037,
>   "preset":"documentAttachment"
> }'
> ```
> 
> I write the request like this. I think `name` is just the attachment name, so how do I pass the path of the local image, such as `/home/abc/images/favicon.png`?

I tried your code, and it worked! By the way, the documentation didn't mention the "preset" thing at all. But I can use the responsed attachment url in document :(

**Comment by tommoor** [comment]
> By the way, the documentation didn't mention the "preset" thing at all

This was already updated on `main` to make `documentAttachment` the default, so it's not required any more. Change will be in the next release.
