### ISSUE TITLE
Shared and unpublished Documents are not shown in "Shared with me"

### ISSUE THREAD

**Issue by threema-norbert** [outline/outline#8037]
Shared and unpublished Documents are not shown in "Shared with me".

**To Reproduce**
1. Share a draft with a Person
2. The person you shared it to can only open the document with the link send by Email

**Expected behavior**
The shared draft should also be shown under "Shared with me". Maybe in a separate section or just dotted like in the Tree.

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.81.1

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Brave

**Comment by tommoor** [comment]
I'm afraid I haven't been able to reproduce, sharing drafts is definitely core functionality and it's appearing under "Shared with me" in my testing.

**Comment by threema-norbert** [comment]
Seemed to be a fluke. We cannot reproduce it ourselves, thanks for the fast reply.
