### ISSUE TITLE
Allow set image size

### ISSUE THREAD

**Issue by teddychan** [outline/outline#804]
Wanna know if possible to allow change the image display size?

seems no way to modify it in outline.

Example of image.resize.in.github.flavored.markdown

https://gist.github.com/uupaa/f77d2bcf4dc7a294d109

**Comment by tommoor** [comment]
It doesn't look like the linked example actually works for their markdown, however it does look like a reasonable way to store the size.

I'd probably prioritize being able to set the float value (left / center / right) before changing the size as this is better done in an image editor before you upload the image to Outline.

**Comment by locomot1f** [comment]
I'd be cool with being able to align images. 
would that give the ability to wrap text around the image?

**Comment by dkkb** [comment]
> It doesn't look like the linked example actually works for their markdown, however it does look like a reasonable way to store the size.
> 
> I'd probably prioritize being able to set the float value (left / center / right) before changing the size as this is better done in an image editor before you upload the image to Outline.

Here's the situation: the editor wants me to place some text on the right after I put the image on the left, but the image and following text aren't always related.

Also, sometimes the image is extremely large, but we can't see it clearly when we put it in the center; on the other hand, some small images will resize to quite large, which is unbalanced.

It would be fantastic if we could change the image size.

**Comment by dkkb** [comment]
#editor_improvement

**Comment by max-mykhailenko** [comment]
Can we reopen this issue? It looks good for me

**Comment by abunet** [comment]
please add support for this. Non technical users (functional users) can't switch from an image editor to the wiki easily.
