### ISSUE TITLE
Suggest to set the www in .env

### ISSUE THREAD

**Issue by teddychan** [outline/outline#805]
If the hostname is not using `www`, e.g. using `wiki`

The latest 1.6.2 version will always force a redirect to:

https://github.com/outline/outline/blob/3c563e300126cd43a7396b15ab3fe40364921fe8/server/routes.js#L85

```
ctx.redirect(`${process.env.URL}?notice=invalid-auth`);
```

Suggest making `www` hostname in the .env file.

**Comment by tommoor** [comment]
Issue should be resolved on latest master, lmk if you still have any problems 😄
