### ISSUE TITLE
Lag with "Enable Embeds" button

### ISSUE THREAD

**Issue by infinite-persistence** [outline/outline#8073]
- [x] The button takes a while to update after clicked. The longest I've seen is over a minute, after a bunch of toggling back and forth.
- [x] Toggling this setting increments the view count.  Can understand why it is happening, but should that be counted?

https://github.com/user-attachments/assets/59e1c022-dca9-4896-a9ab-747d3f7d2451

**Comment by tommoor** [comment]
Weird, it seems likely this is a mobx bug where the UI is not responding to data changes until something else calls a render perhaps
