### ISSUE TITLE
LDAP/Active Directory Login

### ISSUE THREAD

**Issue by muuvmuuv** [outline/outline#809]
It would be so great if our employees could log in with LDAP-Service or AD and host it on our own servers. Our company is currently searching for a MediaWiki alternative that is more flexible and modern, would be great to finally found one!

We could also add it by ourselves if someone could direct us in a direction of how to implement LDAP/AD into Outline.

**Comment by tommoor** [comment]
Hey @muuvmuuv, thanks for the idea. 

I'd say that I'm hesitantly open to the idea right now as it's not something that the hosted version can make use of and does introduce quite a large maintenance burden to the project. If you were to go ahead and build it I'd love to see the complexity and if it's possible to integrate but there is a chance your team may end up having to keep the work on your own fork of the project.

If you decide to give it a try you can find the two current authentication methods here for reference: https://github.com/outline/outline/tree/master/server/auth

**Comment by IBlackI** [comment]
I have made a working implementation in this pull request.
https://github.com/outline/outline/pull/939

**Comment by matteo-bruni** [comment]
Is LDAP supported after passport.js merge in #1934 ? or does it require additional implementation?

**Comment by karas84** [comment]
I'm also interested in LDAP support.

Should this issue be added to "Authentication" Project? https://github.com/outline/outline/projects/5 @tommoor

**Comment by iamsaumya** [comment]
Hello everyone, 

A few days back, @tommoor answered the query around the inclusion of LDAP.  Please read his comment [here](https://github.com/outline/outline/pull/1953#issuecomment-825723299). Thanks!

**Comment by matteo-bruni** [comment]
too bad I wanted to use outline in the lab at the university where I work but it seems not possible, I will have to find an alternative (but I totally understand the reasons for your choice)

the passport implementation seems trivial but outline lacks a frontend interface for entering the password

**Comment by muuvmuuv** [comment]
Nice, will bring it onto our internal board to review the enterprise edition with LDAP support. Thanks for your work.
