### ISSUE TITLE
Color `slate` is inaccessible in light mode

### ISSUE THREAD

**Issue by henningmu** [outline/outline#8113]
The [`slate` color](https://github.com/outline/outline/blob/a458690bfcf854ddab8b1131fc3d20366a966cb3/shared/styles/theme.ts#L11) used throughout Outline is inaccessible in light mode. It has a contrast of 2.47 against the white background. [WCAG AA recommends](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) a contrast of at least 4.5. 

This is not a problem in dark mode, where the contrast ratio is 7.51 and passes even WCAG AAA recommendations.

**Expected behavior**

Change the color of `slate` to something more readable / accessible.

I propose using `#64748b` which matches slate-500 from Tailwind and passes WCAG AA with a contrast ratio of 4.76 against a white background.

I'm happy to PR the change myself, if you agree with the color value (or tell me which one to use) 🙌

**Screenshots**

Here are some prominent usages of slate in light mode. I believe the information, albeit secondary, is too important to be hard to read.

<img width="502" alt="image" src="https://github.com/user-attachments/assets/2385f7f6-555d-4d3d-b9f6-8b1d98e89174" />

<img width="435" alt="image" src="https://github.com/user-attachments/assets/b121333d-a28b-4371-9bf2-cdefd32d05cb" />

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: all

**Comment by tommoor** [comment]
Fair – honestly the entire grey palette needs resetting as there is a mix of grey hue's but will see if there is a way to fix this quickly

**Comment by henningmu** [comment]
Thank you 🙌
