### ISSUE TITLE
Slack Integration not working

### ISSUE THREAD

**Issue by Nogah-Goldberg** [outline/outline#812]
Hi,
I forked this repository and am trying to integrate with Slack.
I added to the env file my credentials: 

SLACK_KEY
SLACK_SECRET

I see the 'sign in with slack button' and i also get to this page
<img width="630" alt="screen shot 2018-12-02 at 13 44 57" src="https://user-images.githubusercontent.com/31074212/49339315-7d902400-f638-11e8-9ae3-1b75c30b6fab.png">

but for some reason when clicking 'continue' i keep getting 'Internal Server Error' 
this is the error i get in the logs:
<img width="1116" alt="screen shot 2018-12-02 at 13 46 34" src="https://user-images.githubusercontent.com/31074212/49339331-b4663a00-f638-11e8-80bd-367deba94008.png">

(by the way the same thing is happening with gmail integration)

What am I missing? Thanks

**Comment by tommoor** [comment]
It looks as though your SECRET_KEY is not set or an invalid length 

https://github.com/outline/outline/blob/67cd250316e2f8404c7f055651ec6f93fbbee6b3/.env.sample#L9

**Comment by Nogah-Goldberg** [comment]
@tommoor 
I set my secret key according to this:
# Please use `openssl rand -hex 32` to create SECRET_KEY
SECRET_KEY=openssl rand -hex 32

shouldn't this be enough?

**Comment by tommoor** [comment]
Well, you need to actually run that command in a terminal window and set the key to the output so it looks similar to the sample. I trust you did that?

**Comment by Nogah-Goldberg** [comment]
thanks
