### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by teddychan** [outline/outline#814]
We use getoutline.com, there is a bug:

Content:
```
> test: [`http://www.google.com`](http://www.google.com)
```

Error:
![image](https://user-images.githubusercontent.com/1013507/49640687-2976ac80-fa49-11e8-8a5b-9b24af81fdf1.png)

We can make it work if remove the
```
`
```

**Comment by tommoor** [comment]
Thanks @teddychan. If anyone decides to look into this the bug itself will be in the https://github.com/outline/rich-markdown-editor repo

**Comment by teddychan** [comment]
Wanna know if any update on it.

as it quite annoying that we are trying to copy from markdown from other sources, and save it to outline

it doesn't work and blocking us to migrate to use outline
