### ISSUE TITLE
Import error: The documet is too large to import, please reduce the length and try again

### ISSUE THREAD

**Issue by wforte88** [outline/outline#8164]
**To Reproduce**
1. Go to 'Settings'
2. Click on 'Import'
3. Click on 'Markdown' and send a massive zip with MD files and images
4. See error in logs "The documet $DocName is too large to import, please reduce the length and try again"

**Expected behavior**
Successful file import within the upload limit variable. The ENV of the self-hosted version:
AWS_S3_UPLOAD_MAX_SIZE=300000000
FILE_STORAGE_UPLOAD_MAX_SIZE=300000000
FILE_STORAGE_IMPORT_MAX_SIZE=300000000
FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE=300000000

**Screenshots**
![image](https://github.com/user-attachments/assets/ad8c3405-aee3-4463-8848-3c3624b6cbd6)
The file "Gercon-01" have 734kb and the limit is 300Mb.

**Outline (please complete the following information):**
- Install: [self hosted]
- Version: [0.81.1]

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Chrome]
 - Version [131.0.6778.140]

**Mobile (please complete the following information):**

**Comment by tommoor** [comment]
This is expected behavior, there is an upper limit on the size of individual documents in Outline to protect the performance of the entire system. 

You would need to split up that document in a way that makes sense for your content

**Comment by AreChen** [comment]
> This is expected behavior, there is an upper limit on the size of individual documents in Outline to protect the performance of the entire system.
> 
> You would need to split up that document in a way that makes sense for your content

May I ask what the maximum length of a single markdown document is?
Recently, I encountered this issue when uploading a 516KB markdown document: "The document 'Emx' is too large to import. Please reduce the length and try again."
