### ISSUE TITLE
Embed Services

### ISSUE THREAD

**Issue by tommoor** [outline/outline#817]
Continuing from https://github.com/outline/outline/pull/680 – Please add requests for additional services as comments on this issue.

- [x] Prezi
- [x] Abstract
- [ ] Speakerdeck
- [ ] Leanboard
- [ ] Twitter
- [ ] Google Maps
- [ ] Looker
- [ ] Overflow.io

**Comment by nnblack1980** [comment]
Abstract please :)

**Comment by tommoor** [comment]
I can promise that Outline will be the first service to have Abstract embeds 😉

**Comment by nnblack1980** [comment]
Excellent news - thanks @tommoor

**Comment by jbrewer** [comment]
[ ] Google Slides 
[ ] Notion
[ ] Asana

**Comment by coleylogan** [comment]
Github to see a brief summary of any issues I reference in docs.

**Comment by locomot1f** [comment]
- [ ] Mindmeister

**Comment by locomot1f** [comment]
so... I love the option to embed google slides.
One option that would be awesome would be to embed the "presentation" format of the slide, as opposed to the "edit".
so, if I try to embed this link - https://docs.google.com/presentation/d/1a_18aJ8rshQWK8q5bwT5wG2z97o9Lb315-uTEfXN-eo/**edit**?usp=sharing - it's fine
but if I try this link - https://docs.google.com/presentation/d/1a_18aJ8rshQWK8q5bwT5wG2z97o9Lb315-uTEfXN-eo/**present**?usp=sharing - i get a blank box where the presentation should be.

**Comment by tommoor** [comment]
That would be nice, unfortunately it looks like Google sets some security headers that prevent the presentation version from being embedded as an iframe 😢 

![image](https://user-images.githubusercontent.com/380914/51625847-1c007d80-1f36-11e9-856a-65607996ed26.png)

**Comment by atomobianco** [comment]
- [ ] LaTex (through https://katex.org/ or else)

**Comment by aam1r** [comment]
* [ ] Whimsical or [mermaid](https://mermaidjs.github.io/#/)

**Comment by MatheusRV** [comment]
- [X] PowerBI (done in https://github.com/outline/outline/pull/1325)
- [ ] Linkedin SlideShare
- [ ] SlideShare
- [ ] DailyMotion
- [ ] Flickr
- [ ] Giphy
- [ ] Kickstarter Campaign
- [ ] Kickstater Catalogue
- [ ] Vimeo
- [ ] Twitter Tweet
- [ ] Twitter HashTag Feed
- [ ] Twitter Profile Feed
- [ ] Spotify Playlist
- [ ] Scribd
- [ ] Instagram Post
- [ ] Instagram HashTag Feed
- [ ] Instagram Profile Feed
- [ ] Instagram Profile Grid
- [ ] TikTok
- [ ] embed.ly
- [ ] Google Analytics
- [ ] Any URL
- [ ] WordPress Blog Post
- [ ] Wordpress Blog Post Catalogue
- [ ] Trello
- [ ] Taiga
- [ ] Yelp
- [ ] Google Maps
- [ ] ArcGIS StoryMap
- [ ] Tumblr
- [ ] Wikipedia
- [ ] Wikimedia
- [ ] Behance
- [ ] Adobe Spark 
- [ ] Adobe Dimension
- [ ] Tiled
- [ ] StackShare
- [ ] CodePen
- [ ] Plunker
- [ ] Pastebin.com
- [ ] jsFiddle
- [ ] Snipit
- [ ] RunKit
- [ ] TuneUp
- [ ]

**Comment by milesstoetzner** [comment]
Hey, 

see my MR for Google Drawings Integration https://github.com/outline/outline/pull/1814

**Comment by matbrgz** [comment]
Still need it.

**Comment by matbrgz** [comment]
- [X] Google DataStudio (https://github.com/outline/outline/pull/2293)
- [X] Google Forms (https://github.com/outline/outline/pull/2291)
- [X] Google Sites (https://github.com/outline/outline/pull/2290)
- [X] Google Calendar (https://github.com/outline/outline/pull/2292)

**Comment by pdxrlk** [comment]
- [ ] Asana (but I don't think their security allows normal iframe to work)

**Comment by aam1r** [comment]
@tommoor - Please reopen this. This was a good issue to keep track of embed requests.

**Comment by matbrgz** [comment]
@tommoor could you please reopen here?

**Comment by wesleyguirra** [comment]
Please add support to metabase

**Comment by tommoor** [comment]
It would be nice to remove the maintenance of these from this project you're right. That oss looks very interesting if anyone wants to take a stab

**Comment by Limezy** [comment]
It would also be nice to be able to chose in the settings which embed services we want to use. Right now it's all or none, which seems OK but what about when there will be 100 of them ?
Would also be nice to be able to configure our own services as a plugin for instance. I can think of some embedded service that will never be added to the main repo. They are too "niche" for that (specific medieval musice scores integration...)

**Comment by almereyda** [comment]
The "classical" go to shop for this service as an SaaS is https://embed.ly/ btw.

To solve plugins, we first need to reopen #2219 and design it. ;)

Then there'll be plenty of room for bulk-selecting an SaaS or FLOSS embed service, and for refactoring existing and future integrations into plugins.

**Comment by luclu** [comment]
I don't want to bloat this issue as I think the surfacing approach via an embedding-frameworks is sound, but please let me append to the list:

- [ ] wekan
- [ ] diagrams.net
- [ ] netbox

**Comment by matbrgz** [comment]
@luclu Currently Outline already support Diagrams.Net

**Comment by u23a** [comment]
[markmap](https://github.com/gera2ld/markmap) please. It renders markdown to mindmap.

**Comment by zeekhuge** [comment]
Would be great to fave following embeds as well.
- [ ] Nocodb -  https://docs.nocodb.com/setup-and-usages/share-base/
- [ ] Github projects
- [ ] Jira Tables - https://jira.atlassian.com/browse/CONFCLOUD-72958

**Comment by bpetit** [comment]
> Would be great to fave following embeds as well.
> 
>     * [ ]  Nocodb -  https://docs.nocodb.com/setup-and-usages/share-base/
> 
>     * [ ]  Github projects
> 
>     * [ ]  Jira Tables - https://jira.atlassian.com/browse/CONFCLOUD-72958

should we open a new FR for this ?

**Comment by s256** [comment]
I would also like to see _Gitlab_ embeds as well, ideally supporting the cloud and the self-hosted version.

**Comment by baditaflorin** [comment]
What would be the requirements of embedding this? 

I know in jira you can create a PAT token, would this suffice to allow the user to see private issues that the user has access to?
