### ISSUE TITLE
Draw.io & Interactive SVG support

### ISSUE THREAD

**Issue by bharatrajagopalan** [outline/outline#820]
Hi

Outline looks absolutely fabulous.

I wanted to check if there was a plan to use draw.io to manage diagrams on outline. draw.io offers html5 and webdav integration

https://github.com/jgraph/drawio-html5

Also my project uses plantuml to create interactive svgs - so i can click on refs in one diagram to say go to another. I was wondering if outline supports/plans to support one of the following

a) native interactive svg support - when i upload svgs they are loaded as svgs into S3 but show up as a picture - i would expect them to be loaded inline so that the links work and content is searchable

b) plantuml support-  would be great to simply type plantuml in markdown to generate uml diagrams including the capability to including other plantuml content (constants/skins etc) from another location. I know gitlab has added this support

If so hopefully SVG+ draw.io support can be linked so that draw.io can be used to save and manage these. draw.io can create interactive svgs.

Otherwise really excited about Outline!

Bharat

**Comment by tommoor** [comment]
Howdy, do you have any examples of the types of SVG's you're looking to include? I'm intrigued 😄 

Unfortunately there is no security model for inline SVG's so embedding them directly in the document / html would be a vector for XSS and running untrusted javascript 😢 

Perhaps draw.io support would get around this… Is it possible to share a link to a document on draw.io?

**Comment by bharatrajagopalan** [comment]
Hi there

I am struggling to upload SVGs here - so here is a screenshot instead :)

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/15735432/50182459-46dc2e00-0307-11e9-8aa4-cdfa8b45a172.png">

And here is another one using draw.io to create an interactive map

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/15735432/50182504-64a99300-0307-11e9-8c64-9806c0d40ef7.png">

**Comment by JSilversun** [comment]
It would be great if you provide integration with draw.io please

**Comment by NebojsaKrtolica** [comment]
Wiki.js (only markdown pages, not WYSIWYG) has the feature proposed in the OP (embedded, when clicking on a rendered diagram it leads users to the embeddable diagrams.net and upon saving returns them to the wiki page)

**Comment by Junaida432** [comment]
you can try [ArialNarrow.com](https://arialnarrow.com/) It provides a simple way to create SVGs using Arial Narrow.
