### ISSUE TITLE
Chronological collections

### ISSUE THREAD

**Issue by tommoor** [outline/outline#821]
This is a relatively quick win feature that we planned from day 1 – the ability to enforce a collection be in chronological order. This is particularly useful for meeting notes, changelogs, and other time series documents.

### TODO

- Allow creation of "journal" [collection type](https://github.com/outline/outline/blob/master/server/models/Collection.js#L29). This will not be updatable afterwards in the first instance.
- Add the "journal" option to the new collection modal
- Ensure that the sorting on the server respects this setting

**Comment by jorilallo** [comment]
🙌

Sent via Superhuman iOS ( https://sprh.mn/?vip=jtlallo@gmail.com )

**Comment by tommoor** [comment]
This is effectively complete, the default for a new collection is not chronological
