### ISSUE TITLE
Integrate Outline with Open Collective

### ISSUE THREAD

**Issue by xdamman** [outline/outline#822]
Open collectives need a wiki. I would love to see if we could integrate the two apps together.

The big blocking point right now is that most collectives don't have their own domain name or a slack community. 

How could we go around that restriction?

**Comment by xdamman** [comment]
(sorry totally missed the notification of your answer)
Yeah that's an issue. Everything is public on open collective. Would be good to chat about this. Let me know what works for you. I'm at xavier at opencollective.com

**Comment by tommoor** [comment]
closing this out as a won't do for now.
