### ISSUE TITLE
can we deploy ootline on my own VPS without Slack or Google account

### ISSUE THREAD

**Issue by chorylee** [outline/outline#828]
Can we deploy outline on my own VPS server without slack or google accout

**Comment by tommoor** [comment]
You can of course install it on your own server, however it would still require Slack or Google login.

You could fork the codebase to remove this requirement however you'd need to substitute it with some other account mechanism to allow users to login and attribute changes.

**Comment by chorylee** [comment]
@tommoor thank you. Is there any way to use email login shen self hosted in my VPS server

**Comment by tommoor** [comment]
Yes, you could absolutely add email login as an auth mechanism however the main Outline project does not include it so it would need to be developed

**Comment by leinue** [comment]
@chorylee maybe u can try authing.cn
