### ISSUE TITLE
Partial word match in search

### ISSUE THREAD

**Issue by tommoor** [outline/outline#830]
E.g right now searching "road" does not bring up results for "roadmap"

This may also help with https://github.com/outline/outline/issues/826 a touch.

**Comment by tommoor** [comment]
![image](https://user-images.githubusercontent.com/380914/50812398-70b1c080-12c7-11e9-897b-1199136784f7.png)

**Comment by quickerlab** [comment]
If side effect there, may be possible add advanced option？
thanks

**Comment by tommoor** [comment]
It won't match "map" at this time due to the way that the index is queried. In terms of advanced options what kind of thing are you thinking?

I think it would be good to add some filters to search within a specific collection and by a specific author.

**Comment by keriwarr** [comment]
partial word match in URLs would be awesome. e.g. "KubiScan" would preferably find documents containing "https://github.com/cyberark/KubiScan"
