### ISSUE TITLE
Heading is cropped while printing

### ISSUE THREAD

**Issue by nayatec** [outline/outline#838]
While printing, the main header is cropped, and this is not related to margins :
![image](https://user-images.githubusercontent.com/43960749/50776290-e5213b00-1298-11e9-8c82-b9eb24067030.png)

I guess this would be a matter of CSS.
Regards
Olivier

**Comment by tommoor** [comment]
Tested on macOS and this issue doesn't exist, seems it's likely a linux-only issue.

**Comment by tommoor** [comment]
Well, you have a screenshot – so it definitely happened! I'm going to close out for now please reopen the issue if you figure out how to reproduce 😄
