### ISSUE TITLE
Add ability to return to search results after reviewing document

### ISSUE THREAD

**Issue by coleylogan** [outline/outline#845]
Currently, if you search and click a result, it takes you to the document as expected.

However, if that document doesn't have what you're looking for, it appears you have to go back and start the search process again. 

To enhance this experience, perhaps offer the option to go back to search results after previewing the document.

**Comment by tommoor** [comment]
Does the back button work okay for you? Do you have any examples of the kind of behavior you're expecting? This does sound like potentially low hanging fruit…

**Comment by tommoor** [comment]
Made a pretty big improvement to this yesterday, when returning from a document back to search results the page now loads instantly rather than having to reload the search 😄

**Comment by tommoor** [comment]
Counting this as addressed
