### ISSUE TITLE
Ability to search Outline via a Zendesk integration

### ISSUE THREAD

**Issue by coleylogan** [outline/outline#848]
It would be ultra helpful to be able to search documents in Outline from Zendesk. This could help support teams have a manageable, quality internal knowledge base. 

Functions: 
- Search documents and document text
- Limit scope of search to specific Collections via integration settings
- Ability to review document content
- Ability to click a link and review the full document in Outline

I'll tell all my support friends that use Zendesk if we can do this. Other great CRMs include Front.

**Comment by tommoor** [comment]
@coleylogan hey I know this isn't a direct issue for you any more but I was wondering – do you think a browser extension could also have been a good solution for this problem? The advantage of that is it would also work with other support tools.
