### ISSUE TITLE
Moving document is not possible with more than 2 levels

### ISSUE THREAD

**Issue by nayatec** [outline/outline#852]
Hi :-)

When you want to move a doc (within a collection) with more than 2 levels it is not possible because the possibilities ar not displayed.

Example :
![image](https://user-images.githubusercontent.com/43960749/50964485-b6d97080-14cf-11e9-93c4-a4639b3ba32a.png)

Now i want to move "First TestDoc" as a child of "/First SubColl/First SubCollDoc" but i can't :

![image](https://user-images.githubusercontent.com/43960749/50964624-10da3600-14d0-11e9-95c6-44c1c9348910.png)

Same for a doc that is not already a child of my first level "First SubColl", for example "Second TestDoc" :
![image](https://user-images.githubusercontent.com/43960749/50964699-43842e80-14d0-11e9-874c-a997080d3f2a.png)

In that case i can understand that it would be only possible to move one level deeper, to keep the screen not overloaded in case of large collections, but we definitely need to be able to move deeper into the same level.

Sorry if i'm not clear enough, it was not easy for me either to fully understand what was the point :-)

**Comment by tommoor** [comment]
Will take a look! 

Sidenote: Could you do me a favor and let me know what OS you are using what font-face is being used? It looks really terrible and I'd like to improve that too.

**Comment by nayatec** [comment]
I'm on Debian 9, and it seems to be Ubuntu.

**Comment by locomot1f** [comment]
I am on Linux also, using Firefox 64.0
When I click to Move a document, I don't get this dialouge at all.
I can also not use the drag/drop feature to move docs around.
