### ISSUE TITLE
Inline color rendering

### ISSUE THREAD

**Issue by tommoor** [outline/outline#860]
Suggestion came in via email. This would be a small neat enhancement – when a hex color is entered into a document, automatically render the color swatch next to it ala most chat tools.

Note: Slate decorators are the thing to use to achieve this

**Comment by tommoor** [comment]
I started a spike on this, unfortunately it clashes with hashtags. I'm not sure if it's reasonable to say that you can't have a hashtag that's also a HEX code, but that would be the only reasonable solution 😬

**Comment by tommoor** [comment]
Closing as won't implement for now

**Comment by alex3305** [comment]
What a bummer. I just came across this issue and having `#ab1234` rendered as a small color block like in VS Code would be awesome!

<img width="144" height="46" alt="Image" src="https://github.com/user-attachments/assets/041b8c96-8791-45d0-a7ed-e3424c87c60d" />

**Comment by alex3305** [comment]
Wow! Thanks for this 😍! 

Of course missing this small feature wasn't a showstopper or anything, but I think it's pretty awesome that you decided to add this. And very swiftly 😄.

I have migrated from Obsidian to Outline in May 2024 and honestly I have been pretty impressed with the stability and usefulness for me and my family. Outline does not have all the bells and whistles to compete with something like Notion - which it is often compared to - but that doesn't seem a bad thing to me. Having a distraction-less environment for note taking with the ease of use that Outline provides is maybe plain but also plainly awesome!

Although I have to review my self-hosted instance configuration at some time to perhaps implement some missing features like embedded content - which is now broken most of the time 😇 - I like that Outline just works. So I just wanted to say that I really appreciate your efforts and I hope that Outline will grow as a commercial success for you, and that small users like me can keep hosting it for ourselves. 

Thanks 🚀
