### ISSUE TITLE
Slack command to create a new doc

### ISSUE THREAD

**Issue by tommoor** [outline/outline#870]
e.g. `/outline new This is the title`

Outline should respond in the channel with an attachment for the newly created document

**Comment by co16353sidak** [comment]
Hey @tommoor, would like to work in this as my first contribution here, please give me the go ahead and some guidance.

**Comment by tommoor** [comment]
Hi Sidak, I believe this one is relatively straight forward, we'd simply need to add to this handler for the keyword combination:

https://github.com/outline/outline/blob/master/server/api/hooks.js#L49

I'd probably refactor it to split into two method based on whether the first word is "new" or not

**Comment by tapaswenipathak** [comment]
Hi folks: Can I work on the ticket or is the ticket internal?

**Comment by tommoor** [comment]
Open and outstanding

**Comment by rubenmoya** [comment]
Doesn't a document need to be in a collection? How do we choose in which one we add it?

**Comment by tommoor** [comment]
Good point – Slack has some options to [build UI](https://api.slack.com/reference/block-kit/block-elements#multi_select) now so the slash command would trigger a dialog inside of Slack that can ask for the collection, that certainly makes things a lot more complicated though.

I'd probably leave this issue on the back burner for now, in the future we could enable drafts without requiring them to be in a collection until the point of publish.

**Comment by matbrgz** [comment]
@tommoor could you please reopen it?
