### ISSUE TITLE
Internationalization & Localization

### ISSUE THREAD

**Issue by glaand** [outline/outline#880]
Title says everything!

**Comment by tommoor** [comment]
Well, it says something 😆

What language are you after? Would you be willing to help translate?

**Comment by glaand** [comment]
Hey Tom

Yes! I would help with European Portuguese and High German

Best regards

**Comment by MSG-maniac** [comment]
Chinese，I can translate

**Comment by Vinetos** [comment]
I can translate in French

**Comment by tommoor** [comment]
Awesome folks, having these offers definitely bumps translation in priority 😄

**Comment by vitorleal** [comment]
Brazilian Portugues and Spanish

**Comment by MatheusRV** [comment]
@tommoor What about this implementation? Need some help?

**Comment by tommoor** [comment]
Hey @MatheusRV , would be happy if you’d like to work on a PR for the foundation of this if you have experience. Currently no work has been prioritized on this front

**Comment by MatheusRV** [comment]
@tommoor could you rename this as Internationalization & Localization (l10n) is so important as I18N.

https://www.w3.org/International/questions/qa-i18n/

**Comment by dmumedical** [comment]
We have translation team and can help with german and russian, maybe also with arabic language.

**Comment by glaand** [comment]
I will get my hands dirty with this feature. Anyway, i was the one who opened the issue 😆

Sunday you are going to hear/read more from me !

**Comment by glaand** [comment]
Being developed at https://github.com/outline/outline/pull/1624

**Comment by tommoor** [comment]
Hey folks, we're really close to closing this out now – if you'd like to help contribute some of the initial translations there are instructions here:

https://github.com/outline/outline/blob/9b573a2b8bc88c5374056fd707978be532283bc7/CONTRIBUTING.md#how-to-translate-outline-via-crowdin

**Comment by mustafa-online** [comment]
I wanna start with Arabic Language, but it's now exist yet! how to add it ??

**Comment by baditaflorin** [comment]
@tommoor I would want to help with Romanian translation, could you please add it to https://crowdin.com/ ?

**Comment by tommoor** [comment]
@baditaflorin added now
