### ISSUE TITLE
Error in /collections/90a8d20a-33fe-42ce-817e-727f8689d8c5/new

### ISSUE THREAD

**Issue by tommoor** [outline/outline#882]
## Error in Outline

**Error** in **/collections/90a8d20a-33fe-42ce-817e-727f8689d8c5/new**
Uncaught Error: `Node.create` requires a `object` string.

[View on Bugsnag](https://app.bugsnag.com/atlas-1/outline/errors/5b589d965a220c00185307c9?event_id=5c49418f003439c4160c0000&i=gh&m=ci)

## Stacktrace

    node_modules/slate/lib/slate.js:2227 - create

[View full stacktrace](https://app.bugsnag.com/atlas-1/outline/errors/5b589d965a220c00185307c9?event_id=5c49418f003439c4160c0000&i=gh&m=ci)

*Created by Jori Lallo via Bugsnag*

**Comment by jorilallo** [comment]
testing...
