### ISSUE TITLE
yarn start improperly redirects to localhost

### ISSUE THREAD

**Issue by pfista** [outline/outline#884]
I'm having some trouble trying to run Outline in production mode.

When I run `yarn start`, loading the main Outline homepage redirects to `localhost`. When I run `yarn dev`, the site works perfectly fine. I haven't had any luck with docker so far (something goes wrong with S3 and other environment variables aren't being built in the image properly).

Here's a [video example](https://www.useloom.com/share/811ed466c90d4959ab249c7a88abdb0f) of what's happening.

[Here is my](https://gist.github.com/pfista/bd72d1a53bc18a9b555bbb9a226007d1) `package.json` and `.env`.

What am I doing wrong? Thanks for the help!

**Comment by locomot1f** [comment]
let me know what information you need from me as well. 
I'm having the same problem
when I run from the initial `make up` everything runs fine.
I have other problems connecting to Slack, that I'm still trying to figure out... but I can atleast reach my website.
If I use `yarn start` I get a long log, basically telling me
`(node:5730) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:5730) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
    at Socket.<anonymous> (/root/outline/node_modules/ioredis/lib/redis.js:289:21)`

**Comment by locomot1f** [comment]
i don't know if it's related, but now I can't pull up my localhost on Firefox
Chrome works fine
Firefox gives me the error: `Firefox can’t establish a connection to the server at ... `

**Comment by locomot1f** [comment]
When I run `yarn test`
the first part finishes just fine, for the Apps
When it gets to the server part, it hangs on:
` RUNS  server/api/documents.test.js`

**Comment by pfista** [comment]
So I found out what the cause of the infinite redirect was when I ran outline in production mode and now everything is working great :) Hopefully this will help others with the same issue.

I'm using Nginx and my configuration wasn't properly passing the `X-Forwarded-Proto` header which caused `enforceHttps` into the infinite redirect.

Here's what my working Nginx configuration looks like now:

```
server {

        server_name {{server_name}};

        location / {
            proxy_pass  http://localhost:3000/;
        }

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;

        ...
```

**Comment by IamGabrielWu** [comment]
I met the same issue.
Just 
```
grep enforceHttps -r *
``` 
and comment out the enforce https. it should fix
