### ISSUE TITLE
TypeError: Cannot read property 'size' of null

### ISSUE THREAD

**Issue by miluoshi** [outline/outline#888]
When I have a link at the end of the document and I try to remove it character by character, the editor crashes with an error: 
Something Unexpected Happened
`TypeError: Cannot read property 'size' of null`

![image](https://user-images.githubusercontent.com/1130547/51827321-65abe800-22e9-11e9-8543-3ac13330c048.png)

EDIT: I found out that the problem occurs when I try to remove the last character of the link. If I select the whole word and delete the link as whole there is no problem.

**Comment by tommoor** [comment]
Thanks for reporting, I've seen this one in the error logs – it seems to be caused by a bug in the underlying editor framework, for ref:

https://github.com/ianstormtaylor/slate/issues/2428

**Comment by tommoor** [comment]
This has been resolved 😄
