### ISSUE TITLE
[bug] Inline code block editing

### ISSUE THREAD

**Issue by miluoshi** [outline/outline#890]
### Example 1: 

> `code block`

When I remove first character `c` (press backspace with cursor behind the character), the result is: 

> co`de block`

Not only the `c` character is not removed, but also the second character is pushed out of the code block.

### Example 2:

> `code block`

When I place a cursor after `co` and hit backspace, the result is:

> code` text`

The whole word is pushed outside of code block instead of removing a single character `o`

**Comment by tommoor** [comment]
Thanks, the offending code is here if you feel capable and are willing to tackle, otherwise we do prioritize editor bugs so it'll get tackled soon

https://github.com/outline/rich-markdown-editor/blob/master/src/plugins/KeyboardBehavior.js#L135-L162
