### ISSUE TITLE
[bug] table not rendering after v0.23.0

### ISSUE THREAD

**Issue by niteshpurohit** [outline/outline#891]
Example 

When I put this into the document 
```
#TEAM
| Name | Role | Contact |
|:---:|:---:|:---:|
| NAME | ROLE | CONTACT|
| NAME | ROLE | CONTACT|
| NAME | ROLE | CONTACT|
```

It's empty with Heading 'TEAM'.

before v0.23.0 it was working fine.

**Comment by tommoor** [comment]
Hi @niteshpurohit – I can reproduce. Although tables were never officially supported (there are no tools to author them in the editor yet) the underlying serializer did

**Comment by niteshpurohit** [comment]
Thanks @tommoor, I will wait for it. Coming weekend I will see if can contribute to this project. Maybe not to author but to render the table.

**Comment by tommoor** [comment]
Thanks, this issue has now been fixed

https://github.com/outline/outline/commit/945e7ffb7bbca907544e7aa5b9fc2fef61314ce5
