### ISSUE TITLE
Top of the page cut off (in Chrome)

### ISSUE THREAD

**Issue by dynamix** [outline/outline#895]
Created a new account (hosted version). The top of the content is always scrolled out of view and I can not see / reach it. Happens for pages I created and for the "Welcome to Outline" page in Chrome (macOS,  72.0.3626.96) - Safari works (macOS 12.0.1). (I turned off all plugins @ Chrome)

Chrome (can not scroll down/up)
![image](https://user-images.githubusercontent.com/5939/52429605-a800d080-2b04-11e9-933a-296de72cbfc8.png)

Safari (works)
![image](https://user-images.githubusercontent.com/5939/52429654-c36bdb80-2b04-11e9-8ad2-4d29c4424298.png)

**Comment by tommoor** [comment]
Thanks for reporting, it looks like this behavior changed with the release of Chrome 72 this week – everything worked correctly in Chrome 71 😢 

Will investigate!
