### ISSUE TITLE
Markdown inline addition ++thing++ disappears on finishing edit

### ISSUE THREAD

**Issue by johnmcdowall** [outline/outline#897]
Trying out the markdown support, and inline additions like `++cats++` and deletions like `~~dogs~~` work fine in the editor: 

![feb-15-2019 15-43-14](https://user-images.githubusercontent.com/237175/52890262-b53b4200-3138-11e9-9f3a-36cfd8c01789.gif)

But finishing editing removes the addition? Seems weird. 

![screen shot 2019-02-15 at 3 46 06 pm](https://user-images.githubusercontent.com/237175/52890293-db60e200-3138-11e9-80d5-c1091c8b81d2.jpg)

Not sure if this is an issue with Outline the product or the markdown serializer.

**Comment by johnmcdowall** [comment]
@tommoor Thanks for the fix in 9.0.1!

**Comment by tommoor** [comment]
I'll update Outline production instance in the next few hours
