### ISSUE TITLE
Turn off force HTTPS in production mode

### ISSUE THREAD

**Issue by G-Thompson-Ops** [outline/outline#899]
Hi all,

I'm wondering if there is a way to make it so when the app is started via 'yarn start' it does not force the https redirect?

As far as I can tell even though it does this it doesn't actually listen on the HTTPS port, even if its mapped in the docker-compose file as '443:443'.

I've been having an awful time trying to get slack OAUTH2 working in dev mode and have decided I might stand a better chance in production.

Any help would be greatly appreciated.

**Comment by tommoor** [comment]
> As far as I can tell even though it does this it doesn't actually listen on the HTTPS port, even if its mapped in the docker-compose file as '443:443'.

That's correct – there is a presumption that HTTPS is handled by your load balancer. Certificate handling is kept out of the core codebase. I don't think it would be wise to allow http connections in production as an option but for the purposes of debugging you can simply delete these lines:

https://github.com/outline/outline/blob/master/server/index.js#L74-L79
