### ISSUE TITLE
Once signed in with slack on production mode error 'Not Found'

### ISSUE THREAD

**Issue by G-Thompson-Ops** [outline/outline#900]
Hi all,

I'm almost at a point where I can begin testing Outline in it's intended Production mode.

I'm using Nginx which has an SSL cert issued by certbot - with a reverse proxy pointed toward http://localhost:3000

My issue is as follows:

When starting outline via yarn start - the inital landing page loads fine. Once I go to log in with slack and I'm returned to the website it simply shows:

Not Found

This is on every page, including the homepage post Slack login.

What's odd is if I then start with yarn dev I can log in via Slack with any user that has already tried to log in using 'production' mode, and the entire wiki works as intended.

If I try and use a new slack account whilst in dev mode I get a string of errors:

```
outline_1  |   AccessDenied: Access Denied
outline_1  |       at Request.extractError (/opt/outline/node_modules/aws-sdk/lib/services/s3.js:577:35)
outline_1  |       at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
outline_1  |       at Request.emit (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
outline_1  |       at Request.emit (/opt/outline/node_modules/aws-sdk/lib/request.js:683:14)
outline_1  |       at Request.transition (/opt/outline/node_modules/aws-sdk/lib/request.js:22:10)
outline_1  |       at AcceptorStateMachine.runTo (/opt/outline/node_modules/aws-sdk/lib/state_machine.js:14:12)
outline_1  |       at /opt/outline/node_modules/aws-sdk/lib/state_machine.js:26:10
outline_1  |       at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:38:9)
outline_1  |       at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:685:12)
outline_1  |       at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
outline_1  |       at Request.emit (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
outline_1  |       at Request.emit (/opt/outline/node_modules/aws-sdk/lib/request.js:683:14)
outline_1  |       at Request.transition (/opt/outline/node_modules/aws-sdk/lib/request.js:22:10)
outline_1  |       at AcceptorStateMachine.runTo (/opt/outline/node_modules/aws-sdk/lib/state_machine.js:14:12)
outline_1  |       at /opt/outline/node_modules/aws-sdk/lib/state_machine.js:26:10
outline_1  |       at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:38:9)
outline_1  |       at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:685:12)
outline_1  |       at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
outline_1  |       at callNextListener (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
outline_1  |       at IncomingMessage.onEnd (/opt/outline/node_modules/aws-sdk/lib/event_listeners.js:269:13)
outline_1  |       at emitNone (events.js:111:20)
outline_1  |       at IncomingMessage.emit (events.js:208:7)
outline_1  |       at endReadableNT (_stream_readable.js:1064:12)
outline_1  |       at _combinedTickCallback (internal/process/next_tick.js:138:11)
outline_1  |       at process._tickDomainCallback (internal/process/next_tick.js:218:9)
outline_1  |   From previous event:
outline_1  |       at Promise.each.hook (/opt/outline/node_modules/sequelize/lib/hooks.js:130:22)
outline_1  |   From previous event:
outline_1  |       at Function.runHooks (/opt/outline/node_modules/sequelize/lib/hooks.js:124:20)
outline_1  |       at Promise.try.then (/opt/outline/node_modules/sequelize/lib/model.js:3531:33)
outline_1  |   From previous event:
outline_1  |       at model.save (/opt/outline/node_modules/sequelize/lib/model.js:3519:8)
outline_1  |       at Function.create (/opt/outline/node_modules/sequelize/lib/model.js:1998:8)
outline_1  |       at sequelize.transaction.then.then.instance (/opt/outline/node_modules/sequelize/lib/model.js:2096:19)
outline_1  |       at runCallback (timers.js:810:20)
outline_1  |       at tryOnImmediate (timers.js:768:5)
outline_1  |       at processImmediate [as _immediateCallback] (timers.js:745:5)
outline_1  |   From previous event:
outline_1  |       at Function.findOrCreate (/opt/outline/node_modules/sequelize/lib/model.js:2084:8)
outline_1  |       at _callee2$ (/opt/outline/server/auth/slack.js:49:44)
outline_1  |       at tryCatch (/opt/outline/node_modules/regenerator-runtime/runtime.js:65:40)
outline_1  |       at Generator.invoke [as _invoke] (/opt/outline/node_modules/regenerator-runtime/runtime.js:303:22)
outline_1  |       at Generator.prototype.(anonymous function) [as next] (/opt/outline/node_modules/regenerator-runtime/runtime.js:117:21)
outline_1  |       at step (/opt/outline/server/auth/slack.js:35:191)
outline_1  |       at /opt/outline/server/auth/slack.js:35:361
outline_1  |       at <anonymous>

```

Any help would be appreciated as it has been in the past. This is the last hurdle to getting this working - and I can prehaps write up documentation explaining how to set up Outline in production mode via self-hosting (as documentation appears very scarce at this time).

To add:
I'm using a real S3 bucket and a RDS hosted instance of Postgres, if that makes any difference.

**Comment by G-Thompson-Ops** [comment]
I've found the following in my nginx error logs:

`2019/02/19 08:32:55 [error] 3618#0: *100 connect() failed (111: Connection refused) while connecting to upstream, client: 185.13.72.199, server: slce.club, request: "GET /__webpack_hmr HTTP/1.1", upstream: "htt$: "http://127.0.0.1:3000/__webpack_hmr", host: "slce.club", referrer: "https://slce.club/dashboard"`

**Comment by G-Thompson-Ops** [comment]
I've managed to fix the S3 errors when running in Dev mode. Sadly, production mode still just shows Not Found on every page - likley related to the error I posted above. 

The S3 errors were permissions related.

At this point the system is fully functional in dev mode - now just to understand why it all goes wrong in production.

**Comment by G-Thompson-Ops** [comment]
Another night of tinkering around and I think I'm getting closer to the issue:

This is something to do with how the node application changes how it reacts to requests passed to it from dev to production mode.

In production mode is there an expectation that Nginx will be used to serve all static files and pages?

If not, does anyone have an nginx config that can pass through requests to the node app in the way it expects them (which must differ from dev to production mode, because my dev mode works fine).

As it stands in production mode all static pages load fine (/integrations as an example) as does the home page BEFORE a user has logged in. This suggests to me that the way requests need to be passed by proxy to the node app must differ.

My nginx config is currently as follows:

`    server {

    server_name slce.club;

 location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
  }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/slce.club/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/slce.club/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
`

**Comment by G-Thompson-Ops** [comment]
Yet more investigation:

Doesn't look to be anything to do with Nginx.

Same issue occurs when I open :3000 and try to use the website on that port, directly into the Node application.

**Comment by tommoor** [comment]
> In production mode is there an expectation that Nginx will be used to serve all static files and pages?

Nope, there is no use of Nginx – static assets are served by the node application.

**Comment by tommoor** [comment]
Are you still seeing mention of `__webpack_hmr` in the logs? That's a development-only thing

**Comment by G-Thompson-Ops** [comment]
Hi Tom - Not any more. The logs are just showing 

```
2019/02/19 22:04:44 [error] 31157#0: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 86.0.193.30, server: slce.club, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "slce.club"
2019/02/19 22:04:50 [error] 31157#0: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 86.0.193.30, server: slce.club, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "slce.club"
```

When running in prod mode and I get the 'Not Found' error on the webpage.

This is using a fresh git clone too - all I have changed is the .env to have my creds/keys and the server/index.js to remote force HTTPS (as this is handled by nginx).

I've tried fresh Databases (One thats never been used before, spun up on AWS), opening my S3 bucket fully public for testing purposes, nothing seems to be able to get me into the website.

Appreciate the help!

**Comment by esprimo** [comment]
I had the same problem and managed to solve it by running `npm run build`, which builds the `dist` folder (didn't see this mentioned it the docs, but maybe it is). After that production mode works fine for me.

**Comment by OwlWen** [comment]
> I had the same problem and managed to solve it by running `npm run build`, which builds the `dist` folder (didn't see this mentioned it the docs, but maybe it is). After that production mode works fine for me.

Thanks @esprimo , running 'npm run build' is worked.
