### ISSUE TITLE
HTML Lists bullet point / number become invisible

### ISSUE THREAD

**Issue by indiejoseph** [outline/outline#907]
I'vs just adding an ordered list and unordered list, and what it's rendered is no different from a paragraph, after inspected to the HTML DOM, I've seen all list items are `<p/>` instead of `<li/>`.

<img width="412" alt="screenshot 2019-03-06 at 12 52 41 pm" src="https://user-images.githubusercontent.com/577551/53856838-c3310400-400e-11e9-93f3-3b4bd3f9e933.png">

**Comment by indiejoseph** [comment]
And once saved, all the list format gone...

**Comment by indiejoseph** [comment]
More information, if I enter `- blah blah`, the result is normal, but it went wrong if I click on a new line, click (+) button and the list icon

**Comment by tommoor** [comment]
Thanks for reporting, working through a fix. In the meantime the keyboard shortcuts you identified will continue to work 👍
