### ISSUE TITLE
Deleting a document should only redirect if currently viewing said document

### ISSUE THREAD

**Issue by tommoor** [outline/outline#911]
When deleting a document from a list it jumps you to the collection

**Comment by ns23** [comment]
Can i work on this issue ?

**Comment by tommoor** [comment]
Sure, no work has begun on it 👍

**Comment by ns23** [comment]
Thank you. Since this is my first contribution, can you please guide me on from where should I begun?

**Comment by tommoor** [comment]
The code in question is here:

https://github.com/outline/outline/blob/master/app/scenes/DocumentDelete.js#L30-L38

**Comment by ns23** [comment]
I will start working on it

**Comment by ns23** [comment]
Hello 
I am trying to set up dev environment using docker.
 I am getting below error
![image](https://user-images.githubusercontent.com/10084011/54709890-6edc6700-4b6c-11e9-9899-1012402d2281.png)

**Comment by tommoor** [comment]
Hi @ns23 – the error states that the port is in use, so something else on your machine is already using port 5432 – probably another instance of postgres.

**Comment by tommoor** [comment]
This issue was addressed here https://github.com/outline/outline/pull/921
