### ISSUE TITLE
[security] npm audit results

### ISSUE THREAD

**Issue by captn3m0** [outline/outline#916]
I ran a npm audit on the latest master and it returns back with the following:

>found 89 vulnerabilities (76 low, 3 moderate, 10 high) in 29458 scanned packages
> 89 vulnerabilities require semver-major dependency updates.

Noting down all moderate and high severity vulnerabilities here:

| package    | severity | command-to-fix                  | vulnerability                        | advisory                         | path                                                                 |
|------------|----------|---------------------------------|--------------------------------------|----------------------------------|----------------------------------------------------------------------|
| base64-url | high     | npm install koa-connect@2.0.1   | Out-of-bounds Read                   | https://npmjs.com/advisories/660 | koa-connect>connect>express-session>uid-safe>base64-url              |
| fresh      | high     | npm install koa-connect@2.0.1   | Regular Expression Denial of Service | https://npmjs.com/advisories/526 | koa-connect>connect>fresh                                            |
| fresh      | high     | npm install koa-connect@2.0.1   | Regular Expression Denial of Service | https://npmjs.com/advisories/526 | koa-connect>connect>serve-favicon>fresh                              |
| fresh      | high     | npm install koa-connect@2.0.1   | Regular Expression Denial of Service | https://npmjs.com/advisories/526 | koa-connect>connect>serve-static>send>fresh                          |
| minimatch  | high     | npm install sequelize-cli@5.4.0 | Regular Expression Denial of Service | https://npmjs.com/advisories/118 | sequelize-cli>gulp>vinyl-fs>glob-stream>glob>minimatch               |
| minimatch  | high     | npm install sequelize-cli@5.4.0 | Regular Expression Denial of Service | https://npmjs.com/advisories/118 | sequelize-cli>gulp>vinyl-fs>glob-stream>minimatch                    |
| minimatch  | high     | npm install sequelize-cli@5.4.0 | Regular Expression Denial of Service | https://npmjs.com/advisories/118 | sequelize-cli>gulp>vinyl-fs>glob-watcher>gaze>globule>glob>minimatch |
| minimatch  | high     | npm install sequelize-cli@5.4.0 | Regular Expression Denial of Service | https://npmjs.com/advisories/118 | sequelize-cli>gulp>vinyl-fs>glob-watcher>gaze>globule>minimatch      |
| negotiator | high     | npm install koa-connect@2.0.1   | Regular Expression Denial of Service | https://npmjs.com/advisories/106 | koa-connect>connect>compression>accepts>negotiator                   |
| negotiator | high     | npm install koa-connect@2.0.1   | Regular Expression Denial of Service | https://npmjs.com/advisories/106 | koa-connect>connect>serve-index>accepts>negotiator                   |
| lodash     | moderate | npm install sequelize-cli@5.4.0 | Prototype Pollution                  | https://npmjs.com/advisories/782 | sequelize-cli>gulp>vinyl-fs>glob-watcher>gaze>globule>lodash         |
| mime       | moderate | npm install koa-connect@2.0.1   | Regular Expression Denial of Service | https://npmjs.com/advisories/535 | koa-connect>connect>serve-static>send>mime                           |
| morgan     | moderate | npm install koa-connect@2.0.1   | Code Injection                       | https://npmjs.com/advisories/736 | koa-connect>connect>morgan                                           |

**Comment by captn3m0** [comment]
Commit that I ran this on: 7b7ec52eeedf9ed105614f3b64e6c490b85c44e5

**Comment by tommoor** [comment]
Thanks for reporting 👍

**Comment by captn3m0** [comment]
I did try npm audit with `npm audit --only-prod` and it gave the same results. Perhaps the dependency usage is not marked correctly in `package.json`?
