### ISSUE TITLE
Showing the absolute path of the found articles on search function

### ISSUE THREAD

**Issue by glaand** [outline/outline#919]
It would be very informative to know which absolute path the article belongs to, since multiple articles can contain the same technical words.

For example :
Two child documents named as Arbeitsabläufe are in the same collection but belong to different main documents.

 - Departments / [CC] Customer Care / Arbeitsabläufe
 - Departments / [AF] Admin & Finance / Arbeitsabläufe
![image](https://user-images.githubusercontent.com/17197309/54357017-52689800-465d-11e9-9a67-c05f89ede6ef.png)

**Comment by glaand** [comment]
Ideal Solution would be this:

![image](https://user-images.githubusercontent.com/17197309/54358465-ca848d00-4660-11e9-8ce5-855b38eb1208.png)

**Comment by tommoor** [comment]
Good idea 👍

**Comment by glaand** [comment]
https://github.com/outline/outline/pull/920 - There you go!
