### ISSUE TITLE
Editor.js

### ISSUE THREAD

**Issue by AWalton** [outline/outline#924]
Thought you might consider swapping Slate to [Editor.js](https://github.com/codex-team/editor.js). It's main difference is that it's block-based, like [Notion](https://notion.so). This makes it easier to extend with more block types like tables, split sections into multi-column areas etc.

**Comment by tommoor** [comment]
Howdy, the current editor is block based too 😄 

If you have any specific asks for the editor itself then happy to chat about them. Table support is on the cards. We won't be swapping out for Editor.js in the short term as it doesn't have Markdown support amongst other things but will keep an eye on the project!
