### ISSUE TITLE
Indenting text belonging to a list item not working

### ISSUE THREAD

**Issue by atomobianco** [outline/outline#925]
Here trying to make indentation for text that belongs to a list item, with the following initial markdown:
```
Some opening:
- First point.
	This should indent with previous line
- Second point.
	This should indent as well

A new paragraph.
```
Rendered text **should** become:

> Some opening:
> 
> - First point.
>   This should indent with previous line
> - Second point.
>   This should indent as well
> 
> A new paragraph.

But is instead rendered as:

> Some opening:
> 
> - First point. This should indent with previous line
> - Second point. This should indent as well
> A new paragraph.

Tried to make it aligned with new-line as well, but once saved it always gets concatenated to the same previous line.

**Comment by tommoor** [comment]
This works correctly as of https://github.com/outline/outline/pull/1227
