### ISSUE TITLE
Inline code blocks not created unless space character afterwards

### ISSUE THREAD

**Issue by jamesarosen** [outline/outline#934]
I copied and pasted some text:
```
Not if I weaken first. Smooth as an android's bottom, eh, Data? And blowing into maximum
warp speed, you appeared for an instant to be in two places at once. Fate protects fools,
little children and ships named Enterprise. You did exactly what you had to do. You
considered all your options, you tried every alternative and then you made the hard choice.
```

Then I fenced some off it off as code:
```
Not if I weaken first. Smooth as `an` android's bottom, eh, Data? And blowing into maximum
warp speed, you appeared for an instant to be in two places at once. Fate protects fools,
little children and ships named Enterprise. You did exactly `what` you had to do. You
considered all your options, you tried every alternative and then you made the hard choice.
```

If the next thing I do is click away, then none of those backticks turn into code blocks:
![non-code](https://user-images.githubusercontent.com/2406/56003851-7976b180-5c7d-11e9-9c0a-3024e2992de1.png)

If the next thing I do is press space after typing a backtick, then the editor creates a code block from the very first to the very last backtick:
![too-much-code](https://user-images.githubusercontent.com/2406/56003861-885d6400-5c7d-11e9-80f0-fa00697ebe2b.png)

Neither of those obey the Markdown spec.

**Comment by tommoor** [comment]
Hey James, the editor is designed to trigger the inline code when you hit space, I'll take a look at changing that so that it happens when typing the second "`"

**Comment by jamesarosen** [comment]
It also didn't kick in if I added punctuation between the closing backtick and the space:

```
For example, an `<input />`, which …
```

**Comment by tommoor** [comment]
Yep, that's expected right now – the space must be directly after the backtick. This is a great example of why that isn't an ideal approach though 👍
