### ISSUE TITLE
Improve self-hosted installation guide

### ISSUE THREAD

**Issue by Pummelchen** [outline/outline#938]
Hello,

it would be nice to have a step-by-step installation guide for outline for Debian please.

**Comment by sunrez** [comment]
Hi,

I would like to second this comment.  Are there any step-by-step instructions to self host this without using Docker?

I too run Debian.

**Comment by Pummelchen** [comment]
I dropped this project sadly as the developers want 200$ for support and somehow totally misunderstood Git and what an open source community is all about. Good Bye.

**Comment by pedrofracassi** [comment]
Same here. My team works on a non-profit open source project, I thought this open source piece of software would be a good thing for us to use. They don't seem to get open source.

**Comment by paladini** [comment]
Our team would like to use this project too, but on a self-hosted approach. I tried really hard to setup this project on our AWS servers but have no success, what's pretty sad. Your project seems to be awesome and we know that you need to make money, but you're not going to get money and become a true Notion alternative if you don't want to help the developers and companies that want to make your project bigger.

If this project works for our team, as an open-source and self-hosted project, certainly we will take some devs from our team and put they to develop new Outline features that we need at our company, as well finding and fixing bugs that you platform certainly have.

**Comment by tommoor** [comment]
> I dropped this project sadly as the developers want 200$ for support and somehow totally misunderstood Git

Hi @Pummelchen  – we already poured many hundreds of hours of work and thousands of dollars into this project, nobody owes you free support I'm afraid.

--- 

I've updated the ticket title – the self hosting docs do need some love and that will happen soon.

**Comment by DarthFudd** [comment]
A co-worker ran into similar problems, and asked me to take over the install. It looks like someone on the dev team is already looking into the issue, so I'm posting this message just to document that there's one more interested party. I'll check back in a few days to see if there's a fix.

Just curious, @tommoor, have your tried flat-out selling your technology to the Wikipedia foundation? You've got a better way to edit wiki pages, and they've talking about making Wikipedia a lot easier to edit. 'Seems worth an ask.

**Comment by captn3m0** [comment]
Is anyone else here trying to run on top of Kubernetes/AWS? Happily running outline on self-hosted mode for a few months now (with upgrades in the interim). Planning to open source a terraform module soon (WIP).

Since there are no official docker images available for outline, we've been doing builds on Docker Hub: https://hub.docker.com/r/razorpay/outline/tags (github source is just a mirror: https://github.com/razorpay/outline)

Happy to help if anyone here is facing issues.

**Comment by spectrumzhang** [comment]
no self-host detail installation docs yet, give up, byebye.

**Comment by paladini** [comment]
Our team is giving up on the project too. We will stick with Notion or any other open-source tool.

**Comment by tommoor** [comment]
The README has been updated since this ticket was filed with improved instructions:
https://github.com/outline/outline#installation

We'll have some official docker builds soon available to make things even easier soon. Of course you're welcome to use Notion or any other open source solution. Don't forget that we run a hosted version of the service at https://getoutline.com that requires zero technical know-how.

**Comment by sunrez** [comment]
First, thanks for updating the documentation.  I tried the steps out on a Debian 9 machine (using npm from nodesource, nodejs v10.16.0 .

1)  I get an error at this step when doing the db sequalize:

> outline@0.18.0 sequelize:migrate /root/outline
> sequelize db:migrate


Sequelize CLI [Node: 10.16.0, CLI: 5.5.0, ORM: 5.9.0]

Loaded configuration file "server/config/database.json".
Using environment "development".

ERROR: Error parsing url: undefined

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! outline@0.18.0 sequelize:migrate: `sequelize db:migrate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the outline@0.18.0 sequelize:migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-30T19_09_30_478Z-debug.log
root@outline:~/outline# npm run sequelize:migrate

> outline@0.18.0 sequelize:migrate /root/outline
> sequelize db:migrate

2)  How does one self-host and *NOT* have any dependencies on Slack or Google for login/authentication?  Any thoughts of supporting LDAP?  The goal in self-hosting is to not be reliant on external services.

**Comment by tommoor** [comment]
Hi @sunrez, to answer your questions:

1. Current thoughts on LDAP are that we'd like to support a pluggable authentication system for things like that. However it's not within the scope of the project as it stands today. There's a fork here that you might try: https://github.com/outline/outline/pull/939

2. You can use any S3 compatible service instead, there are lots of these such as [minio](https://github.com/minio/minio)

**Comment by sunrez** [comment]
Hi @tommoor,

1.  I think there is a small mistake in the readme directions, I think Step 4 ("Copy the file .env.sample to .env and fill out the essential fields...") should come before Step 3: "Migrate database schema with yarn sequelize:migrate or npm run sequelize:migrate"  .

Without having a .env file, I was unable to get the sequelize:migrate command to run

2.  I don't know if this is a minio/Outline compatability or user error on my part, but when trying to login, I get the error message below.  I did some searching it it looks it could be related to minio AES encryption

``
InvalidArgument: Server side encryption specified but KMS is not configured
      at Request.extractError (/root/outline/node_modules/aws-sdk/lib/services/s3.js:585:35)
      at Request.callListeners (/root/outline/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/root/outline/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/root/outline/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/root/outline/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/root/outline/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /root/outline/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/root/outline/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/root/outline/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/root/outline/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/root/outline/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/root/outline/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/root/outline/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/root/outline/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /root/outline/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/root/outline/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/root/outline/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/root/outline/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/root/outline/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/root/outline/node_modules/aws-sdk/lib/event_listeners.js:299:13)
      at IncomingMessage.emit (events.js:203:15)
      at IncomingMessage.EventEmitter.emit (domain.js:448:20)
      at endReadableNT (_stream_readable.js:1129:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by tommoor** [comment]
> I think there is a small mistake in the readme directions

Hey @sunrez – thanks for that, I've gone ahead and improved that further. I also worked with a new developer to get them onboarded yesterday and as part of that we found a couple more 'gotchas' getting set up and documented those too.

**Comment by tommoor** [comment]
With the much improved step-by-step readme I'm going to count this as resolved for now.

**Comment by sunrez** [comment]
@tommoor ,

If you're amenable, I'd like to provide a few more hints using Outline w/Minio for self-hosting.  I'll send an "addendum" if you're OK with that!

**Comment by Nicicalu** [comment]
> I'll admit, I'm definitely lacking the skill here to understand what I'm doing wrong.
> 
> That said, I feel like this could maybe use some more love? It'd be really nice if the provided `docker-compose.yml` + `docker.env` (from [the docker installation docs](https://app.getoutline.com/share/770a97da-13e5-401e-9f8a-37949c19f97e/doc/docker-7pfeLP5a8t)) worked out of the box, fully self-hosted with minio. This doesn't currently seem to be the case.
> 
> I've been pulling my hair out trying to get it running. Even requiring a custom Slack app would be fine if the rest just worked right away.
> 
> I'm on day three trying to get it going, and I'm losing hope! 😅

@tonycoculuzzi Do you have a working version with minio in `docker-compose.yml`
