### ISSUE TITLE
Hard-to-recreate loss-of-data bug on screen exit, despite hitting 'cancel' on popup

### ISSUE THREAD

**Issue by DarthFudd** [outline/outline#942]
I typed in a full page of text, hit a button to go to another screen, hit cancel on the popup warning me to avoid losing data, and then still lost the entered data. After about ten attempts to recreate the bug, I could only recreate it once. In the recreated case I only lost a few characters of text.

I'm not 100% sure of what I did the first time I ran into the bug, but I think I hit the outline "General" button (which was visible at the time) after entering a page of text, then hit cancel on the warning about losing data, then hit the "General" button again, and then the page of entered data was gone. I tried hitting the browser back button, but was unable to recover the lost page of data.

When I recreated the bug after several attempts, I was hitting the browser back button instead of "General", but the procedure was very similar. I entered some text, hit browser back, hit cancel on the warning, hit browser back a second time, and then lost the input data. To emphasize, in every other attempt to recreate the bug, the input data was saved just fine. Sometimes it auto-saved even before I could hit the back button the first time, sometimes it auto-saved after I hit cancel on the popup the first time, and sometimes the popup kept coming up several times until the auto-save kicked in.

Hypothesis: the network I'm on has been having serious DNS and connectivity issues lately. We lose connections and/or DNS service several times per day, in a very unpredictable pattern. Sometimes we go the whole day with no visible problems, other times we get the problem several times per hour. We've learned to just hit refresh after a few seconds until the connection works. I suspect that this loss-of-data bug only happens when we lose the connection.

I've attached a screenshot that I took during my attempts to recreate the bug, but it doesn't show the bug. Unfortunately, I don't have screen shots which show the bug. By the time I started taking screen shots on every testing attempt, the bug was no longer happening.

![outline-data-loss-attempt-1](https://user-images.githubusercontent.com/14284644/56825096-d8abf880-681d-11e9-8daa-0554246fa5a9.png)

**Comment by tommoor** [comment]
Hey Darth, thanks for the report! If you do manage to hone in the reproduction steps more, let us know – otherwise we'll keep an eye out for this and try and recreate.
