### ISSUE TITLE
Remove hosted pages from open source project

### ISSUE THREAD

**Issue by tommoor** [outline/outline#945]
In order to simplify the open source project we're planning to remove the content pages from the OSS repo, todo:

- [ ] Pricing
- [ ] About
- [ ] Integrations
- [ ] Terms
- [ ] Privacy
- [ ] Simple self hosted, logged out homepage

**Comment by himanshuagarwal272** [comment]
I have made changes in this pull request #941

**Comment by himanshuagarwal** [comment]
@tommoor this pull request #941 makes the required changes. Any plans on this?
