### ISSUE TITLE
InVision live image embed support

### ISSUE THREAD

**Issue by jim-hines** [outline/outline#946]
Unable to paste live embed links from InVision. Doesn't even allow it to be written. 
[Broken Embeds.mov.zip](https://github.com/outline/outline/files/3154879/Broken.Embeds.mov.zip)

**Comment by tommoor** [comment]
Interesting, I've not seen that url pattern before – I think you might be trying to paste HTML when all you need is a share link, could you check what's being copied to your clipboard?

**Comment by jim-hines** [comment]
@tommoor sure thing 

`https://opal.invisionapp.com/static-signed/live-embed/306046891/358512109/2/latest/5VfHs62Fe41PXYffw6hoPSAi5olEM8sTV1thziQXZmqVW5euu9SFhp6pX2XSc7TopFwtbdL2rZFlEMwIjaeIiDywlE/en---Chat---Modal---Content-Preview---Scroll-Collapse-2x.png`

Invision instructs to use this embedded link for live embeds. When I use a public share link it just gets formatted as a normal link in Outline. No fancy smancy live embed.

**Comment by tommoor** [comment]
Interesting, I guess this is a single artboard? Right now Outline only supports prototype share links from invision – which produce an embedded iframe – this link is more like a remote image, I think the functionality could be added to embed this

**Comment by tommoor** [comment]
Better late than never!
