### ISSUE TITLE
Outline giving Blank Page After Login with Slack

### ISSUE THREAD

**Issue by kevalkothari** [outline/outline#948]
Hi Guys,

As long as I login with Slack and Allow signup with Slack  it redirects to /dashboard  page and show empty page with error on console as shown below 

![Error On Dashboard Screen](https://user-images.githubusercontent.com/1439447/57471636-3a9e4080-72a9-11e9-95c8-6e626e01e985.png)

Any idea what's wrong with install ?

**Comment by tommoor** [comment]
My guess is that the JS bundle doesn't exist, it looks like it's trying to parse a HTML page as javascript from that limited screenshot.

You should make sure that `yarn build` has been ran and that the compiled JS files exist on disk. This runs by default in the bundled Dockerfile

https://github.com/outline/outline/blob/master/Dockerfile#L13

**Comment by kevalkothari** [comment]
Hi @tommoor 

I was missing that and after running `yarn build`  and then running it I was able to see the WIKI dashboard  👍  😃 

Thank you for your quick help.
