### ISSUE TITLE
Add `append` ability to document edit API endpoint

### ISSUE THREAD

**Issue by tommoor** [outline/outline#950]
This would be great for gradually building a document over time, think – a Zapier hook or cron job.

I'd imagine it could be easily added as an additional, optional boolean flag.

**Comment by arpitsingh94** [comment]
Hi. I'd like to take up this issue

**Comment by tommoor** [comment]
Go for it, please ensure the solution has test coverage. Let me know if you have any questions about the implementation

**Comment by arpitsingh94** [comment]
Hi. I made the changes to the API to add the 'append' ability. It is working as expected.
I am facing difficulties in running the tests on my system. 
I am running `make test` and all the backend tests are failing with the error:
`SequelizeConnectionError: database "outline-test" does not exist`

**Comment by tommoor** [comment]
You'll need to manually create the test database, either from a GUI or command lind

**Comment by arpitsingh94** [comment]
Hi, created a PR for this. Please check.
