### ISSUE TITLE
Bug: Page jumps to top when selecting text

### ISSUE THREAD

**Issue by jim-hines** [outline/outline#952]
This is a pretty irritating bug. Add text to a page so that it scrolls. Select text, the page will jump to the top. The longer the page is, the more irritating the bug. Seeing this is Chrome, haven't tested in other browsers.

[Outline jump bug lowfi.mov.zip](https://github.com/outline/outline/files/3193316/Outline.jump.bug.lowfi.mov.zip)

**Comment by tommoor** [comment]
Thanks for filing with such clear reproduction steps
