### ISSUE TITLE
Rich markdown editor does not support IME

### ISSUE THREAD

**Issue by howardlau1999** [outline/outline#954]
I am a user from China and I am self-hosting Outline for my team. However, I found that when I try to input Chinese with Microsoft IME, the editor seemed not to support the IME at all. It stopped the IME from correctly getting input. I think this is an editor bug. 

By the way, the Microsoft Japanese IME was not supported either.

**Comment by tommoor** [comment]
Hey, the editor is built on a framework called Slate – could you give this demo page a try and let me know if the issues also exist there?

https://www.slatejs.org/#/rich-text

**Comment by howardlau1999** [comment]
> Hey, the editor is built on a framework called Slate – could you give this demo page a try and let me know if the issues also exist there?
> 
> https://www.slatejs.org/#/rich-text

Yes. The CJK IME works better on this demo page, but not perfectly working. It seems to randomly drop something already input and thus making the IME malfunctioning. But it is more usable than Outline's editor because the problem appears less frequently.

**Comment by howardlau1999** [comment]
> Hey, the editor is built on a framework called Slate – could you give this demo page a try and let me know if the issues also exist there?
> 
> https://www.slatejs.org/#/rich-text

After checking the issues of this project, I have found that many users encountered the same problem as mine. So I believe that they should be working on this bug now and close this issue. Thank you!

**Comment by howardlau1999** [comment]
Maybe we could try switching to another editor framework other than Slate to temporarily solve the problem. The issue was open in Nov. 2018 and has not been closed up to now.

**Comment by howardlau1999** [comment]
By the way, the issue link related to this problem is:  #https://github.com/ianstormtaylor/slate/issues/2368
