### ISSUE TITLE
Markdown for urls not being transformed into links

### ISSUE THREAD

**Issue by caljess599** [outline/outline#957]
I've tried every way I know how to specify a url and link text in markdown and none of them appear to work. Is there no way to set a link with the keyboard? Using the mouse every time is a real pain. Please help/add to documentation. Thanks.

**Comment by tommoor** [comment]
Hi, you can select text with the keyboard and use `CMD+K` to insert a link, you can also select text and then `CMD+V` to paste a link that's on your clipboard.

There is an issue open to track writing a markdown link: https://github.com/outline/rich-markdown-editor/issues/5

Hope this helps!

**Comment by Aerlinger** [comment]
I believe this is happening because the markdown serializer is being a bit overzealous on escaping causing the link markdown to show up as raw text. I believe this is the same as this issue: https://github.com/tommoor/slate-md-serializer/issues/14.
