### ISSUE TITLE
issue with docker compose and reverse proxy

### ISSUE THREAD

**Issue by FlowShowcontrol** [outline/outline#958]
Hi

I am trying to include outine in my docker compose setup behind a nginx reverse proxy.

I followed the required steps in the installation but when running `make up` the resulting sql calls return null.

<img width="990" alt="Screen Shot 2019-05-30 at 2 10 55 AM" src="https://user-images.githubusercontent.com/10196339/58599349-36e65400-8280-11e9-8138-050effacab86.png">

The env file is exactly the same as the sample except for changing user and pass for the database link. The migration seem to have ran fine. Any ideas?

**Comment by tommoor** [comment]
What are you seeing at the local url? It would be expected to have no users as a fresh install.

**Comment by FlowShowcontrol** [comment]
Allright so changing subdomains to false made everything visible. One more issue remains: the avatars are not loaded and in the console there is a CONNECTION REFUSED error for the connections to the fake s3 docker.

**Comment by FlowShowcontrol** [comment]
Fixed
