### ISSUE TITLE
Release v0.30.0

### ISSUE THREAD

**Issue by captn3m0** [outline/outline#960]
While the changelog says 0.30.0 is released, it is not there on the releases/tags pages: https://github.com/outline/outline/tags

**Comment by captn3m0** [comment]
@tommoor help please?

https://www.getoutline.com/changelog#v0.30.0 is confusing till there is an actual release.

**Comment by tommoor** [comment]
@captn3m0 the hosted version usually runs a version closer to master which allows an additional opportunity to catch bugs before publishing an official release for self-hosted environments.

If you're not using the hosted version of Outline the GitHub releases page should be used as reference:
https://github.com/outline/outline/releases
