### ISSUE TITLE
Gitlab/Github SSO

### ISSUE THREAD

**Issue by Arteneko** [outline/outline#962]
The wiki looks great but as a user, one thing is a real deal breaker: SSO with *google* or *slack*.

Is there a way to add Gitlab, or at least Github, as SSO option?

**Comment by tommoor** [comment]
Hey, filed this as an idea. Unfortunately while we only support third-party authentication it's never going to work for all teams. Google and Slack certainly captures the 90th percentile.

**Comment by IvanDelsinne** [comment]
> while we only support third-party authentication

Isn't Github/Gitlab SSO 3rd-party authentication?

**Comment by tommoor** [comment]
It is, sorry put another way – I meant whilst we _don't_ support email notification

**Comment by IvanDelsinne** [comment]
Okay, I'll just fork it and make a primitive Gitlab SSO implementation for my needs for now.

**Comment by almereyda** [comment]
@Arteneko Is your git tree with the changes available somewhere? And could we promote it to a Pull Request?

In the end it feels very much a bummer, that self-deployed authentication systems like any OpenID Connect provider (GitLab) or #939 are not available right away.

This seems like a blocker for a truly self-hosted instance of outline, but might be another issue.

**Comment by Arteneko** [comment]
I did a recent repo cleanup and mistakenly removed my fork, I also forgot about this issue.

**Comment by almereyda** [comment]
Is it safe to assume you also don't retain a copy of your fork on your development machine?

**Comment by Arteneko** [comment]
I indeed don't have a copy of my fork, but I know I didn't get far in my implementation tries.

I forked again and will look again, once I set it up on my computer.

**Comment by almereyda** [comment]
Thank you! Looking forward to read about your progress

**Comment by Arteneko** [comment]
I haven't had the time to look into it yet, but if you could give a few pointers on where authentication is handled and such, it'd be awesome.

I'm trying to set the environment up in local, which is not the easiest thing to do, tbh.

**Comment by tacurran** [comment]
@Arteneko we have a similar concern, and looked into using github. I'm not sure that the roadmap here includes a larger credential, oauth, oidc effort. We thought about using https://github.com/ory/kratos for the credential creation, and then https://github.com/ory/hydra for the id federation. Look at the following and let me know what you think:
https://github.com/ory/kratos-selfservice-ui-node
https://www.ory.sh/kratos/docs/self-service/flows/user-login-user-registration/openid-connect-social-sign-in-oauth2/

**Comment by whatl3y** [comment]
I like the idea of implementing a spec as well to provide custom authentication workflows (particularly a way to perform SSO from our home grown app(s)), but I just created #1447 for GitHub-specific support in case it helps in the meantime.

**Comment by almereyda** [comment]
Followed up by #1934.

See #1953 for example.

**Comment by n-rodriguez** [comment]
Maybe http://www.passportjs.org/packages/passport-gitlab2/

**Comment by tommoor** [comment]
See the PR above – Gitlab does not have the concept of signing into a team in the same way that many OAuth providers do, this makes it currently incompatible with Outline. You'd have to have a whitelist of user accounts or allow anyone with a Gitlab account to sign in when self-hosted.

If this changes in the future we'll re-evaluate.

**Comment by n-rodriguez** [comment]
> You'd have to have a whitelist of user accounts or allow anyone with a Gitlab account to sign in when self-hosted.

This sounds perfectly acceptable for small teams who want to use outline :+1:

**Comment by almereyda** [comment]
This can be reopened.

It is certainly possible to limit GitLab OIDC clients to certain groups. We're doing this with OAuth2-proxy in front of documentation that is only targeted for people in certain groups, but not in others.

- https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#gitlab-auth-provider
