### ISSUE TITLE
AWS US-East-2 V4 400 Bad Request

### ISSUE THREAD

**Issue by FlowShowcontrol** [outline/outline#968]
Hi

I updated to the latest outline and filled out my env as such:

`AWS_ACCESS_KEY_ID=AKIAI7PJZAXXXXXXXXXXXX
AWS_SECRET_ACCESS_KEY=FKyhw2ZeENHNRFFQ0HD+ru7XXXXXXXXXXX
AWS_REGION=ap-us-east-2
AWS_S3_UPLOAD_BUCKET_URL=https://s3.us-east-2.amazonaws.com
AWS_S3_UPLOAD_BUCKET_NAME=mybucketname
AWS_S3_UPLOAD_MAX_SIZE=26214400`

When attempting to change a profile picture, console returns with a 400 Bad Request Error.

My bucket has all blocking disabled in the bucket properties. CORS policy is set for proper GET POST methods. What am I missinng here?

**Comment by tommoor** [comment]
It looks like the correct `AWS_REGION` for your bucket would be `us-east-2` – the example in the sample is for asia pacific – I'll clarify this.

**Comment by tommoor** [comment]
The documentation has been updated: https://github.com/outline/outline/commit/b9e48e86c15c09ab5a5110d293f143bd51b149a9

**Comment by FlowShowcontrol** [comment]
Hi Tom,

I changed the region to us-east-2 but the problem remains...
