### ISSUE TITLE
DOCKER OFFLINE - Connect ECONNREFUSED 127.0.0.1:5432 postgres

### ISSUE THREAD

**Issue by juracite** [outline/outline#969]
Hello i recently wanted to look into your solution on offline using Docker, i ran the make up on **Windows**, but i get this :

![image](https://user-images.githubusercontent.com/7281376/60259125-cd854f80-98d6-11e9-99a2-e6ac413457b4.png)

I filled the SLACK attributes informations.

**Comment by Sohib** [comment]
I have encounterd this same issue. the way i solved it is by modifying `.env` file with the following changes. 
```
#replace localhost by postgres
DATABASE_URL=postgres://user:pass@postgres:5432/outline
DATABASE_URL_TEST=postgres://user:pass@postgres:5432/outline-test
```
and 
```
#replace localhost by redis
REDIS_URL=redis://redis:6379
```

**Comment by juracite** [comment]
Thank you Sohib, it works now ;)
