### ISSUE TITLE
Feature request: table of content

### ISSUE THREAD

**Issue by teddychan** [outline/outline#971]
Hi @tommoor 
Any chance to support the table of content in the doc?
Like having the H1, H2 auto-generated table of content is really useful and nice.

**Comment by tommoor** [comment]
Hey Teddy, there's actually already a TOC – it's on the right hand side of the page and appears as some horizontal lines until you mouse over.

![image](https://user-images.githubusercontent.com/380914/60409348-1f003980-9b78-11e9-811a-881f59c5e0b4.png)

Having said that It's pretty high on my list to give this UI a revamp and make it (optionally) more prominent. If you have any good examples in mind from other products I'd be happy to use for inspiration

**Comment by teddychan** [comment]
oh, really don't notice have such thing.
Let's me ping our team.
but prefer to make the TOC more easy to read.

**Comment by tommoor** [comment]
Definitely, the fact that you didn't notice just bumps this one up in priority 😄

**Comment by pfeiffer** [comment]
Sorry to bump this closed issue - is there any plans to support inserting more a prominent ToC in the beginning a document? We're migrating from Notion to Outline and really miss having a (dynamically updated) ToC in the beginning of our long documents.

**Comment by tommoor** [comment]
Hey @pfeiffer – no worries, thanks for the ping. Do you think a TOC that's always visible but collapsible at the top is preferable?

**Comment by pfeiffer** [comment]
Yup! I'm thinking inserting a TOC-element using the toolbox just like image / table / code block. Clicking on a link in the TOC will scroll to the given heading. Example:

![image](https://user-images.githubusercontent.com/195925/65941314-a6cd3c80-e422-11e9-9fdc-54a627c11907.png)

I don't think it's necessary that it's collapsible, as it's possible for editors to make it collapsible by inserting it below a heading.
