### ISSUE TITLE
Introduce policy architecture

### ISSUE THREAD

**Issue by tommoor** [outline/outline#989]
Currently RBAC policies are only available on the server-side. As permissions become more granular we need a way to serialize and send these policies down to the client alongside other data.

Once the client has policy information it can be used to disable/enable UI elements, such as admin menu options, doc editing etc.

**Comment by tapaswenipathak** [comment]
Hi @tommoor: I would like putting a PR for the feature. Can I take the ticket or is it internal?

**Comment by tommoor** [comment]
I'd like to keep this one internal as I have specific ideas on implementation, thanks
