### ISSUE TITLE
Sync Backups to Git

### ISSUE THREAD

**Issue by captn3m0** [outline/outline#997]
Does a one-way backup operation that writes to a remote Git repo sound like a good idea?

We're looking at disaster scenarios for when outline goes down, and would like to have a always-available read-only replica available for Outline. A simple git repo sync sounds the easiest.

Planning to write a script for now, but can look at instead adding it to core if it sounds like a general usecase.

**Comment by tommoor** [comment]
The endpoint you're looking for is called `collections.exportAll` (there's also an equivalent `collections.export` that takes a `collectionId`) right now it will send an email to the authenticated user with a zip of the documents, this is because the export could take some time and has to be done on a background job.

I'll leave this issue open as a documentation request

**Comment by tommoor** [comment]
We back up the postgres database to a replica. Is there a reason that wouldn't work for your team?

**Comment by captn3m0** [comment]
We have a replica configured, but we are worried about disaster scenarios and losing _immediate availability_ of our playbooks.

If our outline application goes down, we want to ensure that we can bring it back without having access to it. A DB-replica just ensures that we have a backup copy, but that isn't necessarily in a usable state since we'd need to bring outline back first. The other alternative is running select queries on the DB to get our content back, which I'd rather avoid.

The export API is a step towards it, but we can't script it end-to-end, because of the email-only and email-sent-to-authenticated-user limitation.

I envision something like the following in the UI:

```
Provide a Git Remote URL: _________________
Provide a Deploy Key: 
___________________________________________
___________________________________________
___________________________________________
Git Branch: master
```

and every edit to any document automatically getting synced back to this git repository.


If that is too much, a synchronous-flow that exports all content would also work, and we scan script using that.

**Comment by captn3m0** [comment]
I've added git push support in `outliner`, which we're using for regular automated backups against the exportAll API (#1013).

https://github.com/captn3m0/outliner#push has details.

**Comment by isafe** [comment]
`#!/usr/bin/env python

import requests
import json
import time

API_KEY = 'api token'
BASE_URL = 'https://wiki.example.com/api/'

def backup():
    headers = { "content-type": "application/json",
                "accept": "application/json",
                "authorization": "Bearer {0}".format(API_KEY)
              }
    session = requests.session()
    request = session.post("{0}{1}".format(BASE_URL, 'collections.export_all'), headers=headers)
    data = request.json()
    if data["success"]:
        file_id = data["data"]["fileOperation"]["id"]
        post_data = {"id": file_id}
        time.sleep(5)
        req = session.post("{0}{1}".format(BASE_URL, 'fileOperations.redirect'), headers=headers, data=json.dumps(post_data))
        with open("export.zip","wb") as backup:
            backup.write(req.content)
    else:
        print("backup failed!")

if __name__ == '__main__':
    backup()`

**Comment by alexanderadam** [comment]
> I've added git push support in `outliner`, which we're using for regular automated backups against the exportAll API (#1013).

Thank you.
But does that mean that [a native git-push-sync like the one in wiki.js](https://docs.requarks.io/storage/git) won't be implemented in outline?

**Comment by helmut72** [comment]
> But does that mean that [a native git-push-sync like the one in wiki.js](https://docs.requarks.io/storage/git) won't be implemented in outline?

A Git backend like in wiki.js would be awesome, even for files. Makes automated document creation and workflows a lot easier. Also using full featured text editors like vscode is possible.
