### ISSUE TITLE
[security] Token returned as part of response for invalid API call

### ISSUE THREAD

**Issue by captn3m0** [outline/outline#998]
I'm not sure of all API calls, but for the `collection.create` API call (note the missing `s`), the response includes the token that was used to call it.

```ruby
{"token"=>"AAAAAAAAAAAAAAAAAAAAAAA",
 "name"=>"Name",
 "description"=>"Imported Collection",
 "status"=>200,
 "ok"=>true}
```

Ideally, no response should return a token back to the user.

**Comment by captn3m0** [comment]
Any invalid API call does this:

```bash
curl -s  https://kb.example.com/api/auths.info -d "{\"token\": \"$OUTLINE_TOKEN\"}" -H "Content-Type: application/json"|jq
{
  "token": "AAAAAAA",
  "status": 200,
  "ok": true
}
```

**Comment by tommoor** [comment]
@captn3m0 seems like this only affects invalid API calls, it's weird that it returns 200 at all
